//COIN, DESERT
//Section
class TWC_Infantry_ColdWar_COIN_Desert_Rifleman: TWC_Infantry_ColdWar_Regular_Desert_Rifleman
{
	CATEGORY(TWC_Infantry_COIN_Desert)
	linkedItems[]=
	{
		"SP_P58_FightingOrderNBC",
		"UK3CB_BAF_H_Beret_RA",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
	respawnLinkedItems[]=
	{
		"SP_P58_FightingOrderNBC",
		"UK3CB_BAF_H_Beret_RA",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
	weapons[]=
	{
		"UK3CB_BAF_L1A1_Wood",
		"Throw",
		"Put"
	};
	respawnweapons[]=
	{
		"UK3CB_BAF_L1A1_Wood",
		"Throw",
		"Put"
	};
	magazines[]=
	{
		MAG_7("UK3CB_BAF_762_20Rnd"),
		MAG_2("CUP_HandGrenade_L109A2_HE"),
		"SmokeShell"
	};
	respawnmagazines[]=
	{
		MAG_7("UK3CB_BAF_762_20Rnd"),
		MAG_2("CUP_HandGrenade_L109A2_HE"),
		"SmokeShell"
	};
};
class TWC_Infantry_ColdWar_COIN_Desert_Rifleman_SUIT: TWC_Infantry_ColdWar_Regular_Desert_Rifleman_SUIT
{
	CATEGORY(TWC_Infantry_COIN_Desert)
	linkedItems[]=
	{
		"SP_P58_FightingOrderNBC",
		"UK3CB_BAF_H_Beret_RA",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
	respawnLinkedItems[]=
	{
		"SP_P58_FightingOrderNBC",
		"UK3CB_BAF_H_Beret_RA",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
	weapons[]=
	{
		"TWC_L1A1_SUIT",
		"Throw",
		"Put"
	};
	respawnweapons[]=
	{
		"TWC_L1A1_SUIT",
		"Throw",
		"Put"
	};
	magazines[]=
	{
		MAG_7("UK3CB_BAF_762_20Rnd"),
		MAG_2("CUP_HandGrenade_L109A2_HE"),
		"SmokeShell"
	};
	respawnmagazines[]=
	{
		MAG_7("UK3CB_BAF_762_20Rnd"),
		MAG_2("CUP_HandGrenade_L109A2_HE"),
		"SmokeShell"
	};
};
class TWC_Infantry_ColdWar_COIN_Desert_SectionCommander: TWC_Infantry_ColdWar_Regular_Desert_SectionCommander
{
	CATEGORY(TWC_Infantry_COIN_Desert)
	backpack = "TWC_Backpack_ColdWar_COIN_SectionCommander";
	linkedItems[]=
	{
		"SP_P58_FightingOrderNBC",
		"UK3CB_BAF_H_Beret_RA",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
	respawnLinkedItems[]=
	{
		"SP_P58_FightingOrderNBC",
		"UK3CB_BAF_H_Beret_RA",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
};
class TWC_Infantry_ColdWar_COIN_Desert_2iC: TWC_Infantry_ColdWar_Regular_Desert_2iC
{
	CATEGORY(TWC_Infantry_COIN_Desert)
	backpack = "TWC_Backpack_ColdWar_COIN_2iC";
	linkedItems[]=
	{
		"SP_P58_FightingOrderNBC",
		"UK3CB_BAF_H_Beret_RA",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
	respawnLinkedItems[]=
	{
		"SP_P58_FightingOrderNBC",
		"UK3CB_BAF_H_Beret_RA",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
};
class TWC_Infantry_ColdWar_COIN_Desert_MG: TWC_Infantry_ColdWar_Regular_Desert_MG
{
	CATEGORY(TWC_Infantry_COIN_Desert)
	linkedItems[]=
	{
		"SP_P58_FightingOrderNBC",
		"UK3CB_BAF_H_Beret_RA",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
	respawnLinkedItems[]=
	{
		"SP_P58_FightingOrderNBC",
		"UK3CB_BAF_H_Beret_RA",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
	weapons[]=
	{
		"sp_l4_lmg",
		"Throw",
		"Put"
	};
	respawnweapons[]=
	{
		"sp_l4_lmg",
		"Throw",
		"Put"
	};
	magazines[]=
	{
		MAG_10("SP_30Rnd_762_L4"),
		"SmokeShell"
	};
	respawnmagazines[]=
	{
		MAG_10("SP_30Rnd_762_L4"),
		"SmokeShell"
	};
};
class TWC_Infantry_ColdWar_COIN_Desert_ASSMG: TWC_Infantry_ColdWar_Regular_Desert_ASSMG
{
	CATEGORY(TWC_Infantry_COIN_Desert)
	backpack = "TWC_Backpack_ColdWar_COIN_ASSMG";
	linkedItems[]=
	{
		"SP_P58_FightingOrderNBC",
		"UK3CB_BAF_H_Beret_RA",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
	respawnLinkedItems[]=
	{
		"SP_P58_FightingOrderNBC",
		"UK3CB_BAF_H_Beret_RA",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
};

//Platoon Command
class TWC_Infantry_ColdWar_COIN_Desert_Platoon_Commander: TWC_Infantry_ColdWar_Regular_Desert_Platoon_Commander
{
	CATEGORY(TWC_Infantry_COIN_Desert)
	backpack = "TWC_Backpack_ColdWar_COIN_Platoon_Commander";
	linkedItems[]=
	{
		"SP_P58_FightingOrderNBC",
		"UK3CB_BAF_H_Beret_RA",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
	respawnLinkedItems[]=
	{
		"SP_P58_FightingOrderNBC",
		"UK3CB_BAF_H_Beret_RA",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
};
class TWC_Infantry_ColdWar_COIN_Desert_Platoon_Sergeant: TWC_Infantry_ColdWar_Regular_Desert_Platoon_Sergeant
{
	CATEGORY(TWC_Infantry_COIN_Desert)
	backpack = "TWC_Backpack_ColdWar_COIN_Platoon_Sergeant";
	linkedItems[]=
	{
		"SP_P58_FightingOrderNBC",
		"UK3CB_BAF_H_Beret_RA",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
	respawnLinkedItems[]=
	{
		"SP_P58_FightingOrderNBC",
		"UK3CB_BAF_H_Beret_RA",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
};
class TWC_Infantry_ColdWar_COIN_Desert_Platoon_Medic: TWC_Infantry_ColdWar_Regular_Desert_Platoon_Medic
{
	CATEGORY(TWC_Infantry_COIN_Desert)
	backpack = "TWC_Backpack_ColdWar_COIN_Platoon_Medic";
	linkedItems[]=
	{
		"SP_P58_FightingOrderNBC",
		"UK3CB_BAF_H_Beret_RA",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
	respawnLinkedItems[]=
	{
		"SP_P58_FightingOrderNBC",
		"UK3CB_BAF_H_Beret_RA",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
};
class TWC_Infantry_ColdWar_COIN_Desert_CSM: TWC_Infantry_ColdWar_Regular_Desert_CSM
{
	CATEGORY(TWC_Infantry_COIN_Desert)
	backpack = "TWC_Backpack_ColdWar_COIN_Platoon_Sergeant";
	linkedItems[]=
	{
		"SP_P58_FightingOrderNBC",
		"UK3CB_BAF_H_Beret_RA",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
	respawnLinkedItems[]=
	{
		"SP_P58_FightingOrderNBC",
		"UK3CB_BAF_H_Beret_RA",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
};

//Company
class TWC_Infantry_ColdWar_COIN_Desert_Company_Commander: TWC_Infantry_ColdWar_Regular_Desert_Company_Commander
{
	CATEGORY(TWC_Infantry_COIN_Desert)
	backpack = "TWC_Backpack_ColdWar_COIN_Platoon_Commander";
	linkedItems[] =
	{
		"SP_P58_FightingOrderNBC",
		"UK3CB_BAF_H_Beret_RA",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
	respawnLinkedItems[] =
	{
		"SP_P58_FightingOrderNBC",
		"UK3CB_BAF_H_Beret_RA",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
};
class TWC_Infantry_ColdWar_COIN_Desert_Company_2iC: TWC_Infantry_ColdWar_Regular_Desert_Company_2iC
{
	CATEGORY(TWC_Infantry_COIN_Desert)
	backpack = "TWC_Backpack_ColdWar_COIN_Platoon_Commander";
	linkedItems[] =
	{
		"SP_P58_FightingOrderNBC",
		"UK3CB_BAF_H_Beret_RA",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
	respawnLinkedItems[] =
	{
		"SP_P58_FightingOrderNBC",
		"UK3CB_BAF_H_Beret_RA",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
};
class TWC_Infantry_ColdWar_COIN_Desert_Company_Sergeant: TWC_Infantry_ColdWar_Regular_Desert_Company_Sergeant
{
	CATEGORY(TWC_Infantry_COIN_Desert)
	backpack = "TWC_Backpack_ColdWar_COIN_Platoon_Sergeant";
	linkedItems[] =
	{
		"SP_P58_FightingOrderNBC",
		"UK3CB_BAF_H_Beret_RA",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
	respawnLinkedItems[] =
	{
		"SP_P58_FightingOrderNBC",
		"UK3CB_BAF_H_Beret_RA",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
};

//Sniper Team
class TWC_Infantry_ColdWar_COIN_Desert_Sniper: TWC_Infantry_ColdWar_Regular_Desert_Sniper
{
	CATEGORY(TWC_Infantry_COIN_Desert)
	linkedItems[]=
	{
		"SP_P58_FightingOrderNBC",
		"UK3CB_BAF_H_Beret_RA",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
	respawnLinkedItems[]=
	{
		"SP_P58_FightingOrderNBC",
		"UK3CB_BAF_H_Beret_RA",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
};
class TWC_Infantry_ColdWar_COIN_Desert_Spotter: TWC_Infantry_ColdWar_Regular_Desert_Spotter
{
	CATEGORY(TWC_Infantry_COIN_Desert)
	linkedItems[]=
	{
		"SP_P58_FightingOrderNBC",
		"UK3CB_BAF_H_Beret_RA",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
	respawnLinkedItems[]=
	{
		"SP_P58_FightingOrderNBC",
		"UK3CB_BAF_H_Beret_RA",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
};

//Artillery Crew
class TWC_Infantry_ColdWar_COIN_Desert_Artillery_Commander: TWC_Infantry_ColdWar_Regular_Desert_Artillery_Commander
{
	CATEGORY(TWC_Infantry_COIN_Desert)
	linkedItems[]=
	{
		"SP_P58_FightingOrderNBC",
		"UK3CB_BAF_H_Beret_RA",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
	respawnLinkedItems[]=
	{
		"SP_P58_FightingOrderNBC",
		"UK3CB_BAF_H_Beret_RA",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
};
class TWC_Infantry_ColdWar_COIN_Desert_Artillery_Crew: TWC_Infantry_ColdWar_Regular_Desert_Artillery_Crew
{
	CATEGORY(TWC_Infantry_COIN_Desert)
	linkedItems[]=
	{
		"SP_P58_FightingOrderNBC",
		"UK3CB_BAF_H_Beret_RA",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
	respawnLinkedItems[]=
	{
		"SP_P58_FightingOrderNBC",
		"UK3CB_BAF_H_Beret_RA",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
};
class TWC_Infantry_ColdWar_COIN_Desert_FO: TWC_Infantry_ColdWar_Regular_Desert_FO
{
	CATEGORY(TWC_Infantry_COIN_Desert)
	linkedItems[]=
	{
		"SP_P58_FightingOrderNBC",
		"UK3CB_BAF_H_Beret_RA",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
	respawnLinkedItems[]=
	{
		"SP_P58_FightingOrderNBC",
		"UK3CB_BAF_H_Beret_RA",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
};

//Aircraft
class TWC_Infantry_ColdWar_COIN_Desert_FAC: TWC_Infantry_ColdWar_Regular_Desert_FAC
{
	CATEGORY(TWC_Infantry_COIN_Desert)
	linkedItems[]=
	{
		"SP_P58_FightingOrderNBC",
		"UK3CB_BAF_H_Beret_RA",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
	respawnLinkedItems[]=
	{
		"SP_P58_FightingOrderNBC",
		"UK3CB_BAF_H_Beret_RA",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
};