//COIN, NBC
//Section
class TWC_Infantry_ColdWar_COIN_NBC_Rifleman: TWC_Infantry_ColdWar_Regular_NBC_Rifleman
{
	CATEGORY(TWC_Infantry_COIN_NBC)
	linkedItems[]=
	{
		"SP_P58_FightingOrderNBC",
		"UK3CB_BAF_H_Beret_RA",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
	respawnLinkedItems[]=
	{
		"SP_P58_FightingOrderNBC",
		"UK3CB_BAF_H_Beret_RA",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
	weapons[]=
	{
		"UK3CB_BAF_L1A1_Wood",
		"Throw",
		"Put"
	};
	respawnweapons[]=
	{
		"UK3CB_BAF_L1A1_Wood",
		"Throw",
		"Put"
	};
	magazines[]=
	{
		MAG_7("UK3CB_BAF_762_20Rnd"),
		MAG_2("CUP_HandGrenade_L109A2_HE"),
		"SmokeShell"
	};
	respawnmagazines[]=
	{
		MAG_7("UK3CB_BAF_762_20Rnd"),
		MAG_2("CUP_HandGrenade_L109A2_HE"),
		"SmokeShell"
	};
};
class TWC_Infantry_ColdWar_COIN_NBC_Rifleman_SUIT: TWC_Infantry_ColdWar_Regular_NBC_Rifleman_SUIT
{
	CATEGORY(TWC_Infantry_COIN_NBC)
	linkedItems[]=
	{
		"SP_P58_FightingOrderNBC",
		"UK3CB_BAF_H_Beret_RA",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
	respawnLinkedItems[]=
	{
		"SP_P58_FightingOrderNBC",
		"UK3CB_BAF_H_Beret_RA",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
	weapons[]=
	{
		"TWC_L1A1_SUIT",
		"Throw",
		"Put"
	};
	respawnweapons[]=
	{
		"TWC_L1A1_SUIT",
		"Throw",
		"Put"
	};
	magazines[]=
	{
		MAG_7("UK3CB_BAF_762_20Rnd"),
		MAG_2("CUP_HandGrenade_L109A2_HE"),
		"SmokeShell"
	};
	respawnmagazines[]=
	{
		MAG_7("UK3CB_BAF_762_20Rnd"),
		MAG_2("CUP_HandGrenade_L109A2_HE"),
		"SmokeShell"
	};
};
class TWC_Infantry_ColdWar_COIN_NBC_SectionCommander: TWC_Infantry_ColdWar_Regular_NBC_SectionCommander
{
	CATEGORY(TWC_Infantry_COIN_NBC)
	backpack = "TWC_Backpack_ColdWar_COIN_SectionCommander";
	linkedItems[]=
	{
		"SP_P58_FightingOrderNBC",
		"UK3CB_BAF_H_Beret_RA",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
	respawnLinkedItems[]=
	{
		"SP_P58_FightingOrderNBC",
		"UK3CB_BAF_H_Beret_RA",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
};
class TWC_Infantry_ColdWar_COIN_NBC_2iC: TWC_Infantry_ColdWar_Regular_NBC_2iC
{
	CATEGORY(TWC_Infantry_COIN_NBC)
	backpack = "TWC_Backpack_ColdWar_COIN_2iC";
	linkedItems[]=
	{
		"SP_P58_FightingOrderNBC",
		"UK3CB_BAF_H_Beret_RA",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
	respawnLinkedItems[]=
	{
		"SP_P58_FightingOrderNBC",
		"UK3CB_BAF_H_Beret_RA",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
};
class TWC_Infantry_ColdWar_COIN_NBC_MG: TWC_Infantry_ColdWar_Regular_NBC_MG
{
	CATEGORY(TWC_Infantry_COIN_NBC)
	linkedItems[]=
	{
		"SP_P58_FightingOrderNBC",
		"UK3CB_BAF_H_Beret_RA",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
	respawnLinkedItems[]=
	{
		"SP_P58_FightingOrderNBC",
		"UK3CB_BAF_H_Beret_RA",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
	weapons[]=
	{
		"sp_l4_lmg",
		"Throw",
		"Put"
	};
	respawnweapons[]=
	{
		"sp_l4_lmg",
		"Throw",
		"Put"
	};
	magazines[]=
	{
		MAG_10("SP_30Rnd_762_L4"),
		"SmokeShell"
	};
	respawnmagazines[]=
	{
		MAG_10("SP_30Rnd_762_L4"),
		"SmokeShell"
	};
};
class TWC_Infantry_ColdWar_COIN_NBC_ASSMG: TWC_Infantry_ColdWar_Regular_NBC_ASSMG
{
	CATEGORY(TWC_Infantry_COIN_NBC)
	backpack = "TWC_Backpack_ColdWar_COIN_ASSMG";
	linkedItems[]=
	{
		"SP_P58_FightingOrderNBC",
		"UK3CB_BAF_H_Beret_RA",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
	respawnLinkedItems[]=
	{
		"SP_P58_FightingOrderNBC",
		"UK3CB_BAF_H_Beret_RA",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
};

//Platoon Command
class TWC_Infantry_ColdWar_COIN_NBC_Platoon_Commander: TWC_Infantry_ColdWar_Regular_NBC_Platoon_Commander
{
	CATEGORY(TWC_Infantry_COIN_NBC)
	backpack = "TWC_Backpack_ColdWar_COIN_Platoon_Commander";
	linkedItems[]=
	{
		"SP_P58_FightingOrderNBC",
		"UK3CB_BAF_H_Beret_RA",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
	respawnLinkedItems[]=
	{
		"SP_P58_FightingOrderNBC",
		"UK3CB_BAF_H_Beret_RA",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
};
class TWC_Infantry_ColdWar_COIN_NBC_Platoon_Sergeant: TWC_Infantry_ColdWar_Regular_NBC_Platoon_Sergeant
{
	CATEGORY(TWC_Infantry_COIN_NBC)
	backpack = "TWC_Backpack_ColdWar_COIN_Platoon_Sergeant";
	linkedItems[]=
	{
		"SP_P58_FightingOrderNBC",
		"UK3CB_BAF_H_Beret_RA",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
	respawnLinkedItems[]=
	{
		"SP_P58_FightingOrderNBC",
		"UK3CB_BAF_H_Beret_RA",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
};
class TWC_Infantry_ColdWar_COIN_NBC_Platoon_Medic: TWC_Infantry_ColdWar_Regular_NBC_Platoon_Medic
{
	CATEGORY(TWC_Infantry_COIN_NBC)
	backpack = "TWC_Backpack_ColdWar_COIN_Platoon_Medic";
	linkedItems[]=
	{
		"SP_P58_FightingOrderNBC",
		"UK3CB_BAF_H_Beret_RA",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
	respawnLinkedItems[]=
	{
		"SP_P58_FightingOrderNBC",
		"UK3CB_BAF_H_Beret_RA",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
};
class TWC_Infantry_ColdWar_COIN_NBC_CSM: TWC_Infantry_ColdWar_Regular_NBC_CSM
{
	CATEGORY(TWC_Infantry_COIN_NBC)
	backpack = "TWC_Backpack_ColdWar_COIN_Platoon_Sergeant";
	linkedItems[]=
	{
		"SP_P58_FightingOrderNBC",
		"UK3CB_BAF_H_Beret_RA",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
	respawnLinkedItems[]=
	{
		"SP_P58_FightingOrderNBC",
		"UK3CB_BAF_H_Beret_RA",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
};

//Company
class TWC_Infantry_ColdWar_COIN_NBC_Company_Commander: TWC_Infantry_ColdWar_Regular_NBC_Company_Commander
{
	CATEGORY(TWC_Infantry_COIN_NBC)
	backpack = "TWC_Backpack_ColdWar_COIN_Platoon_Commander";
	linkedItems[] =
	{
		"SP_P58_FightingOrderNBC",
		"UK3CB_BAF_H_Beret_RA",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
	respawnLinkedItems[] =
	{
		"SP_P58_FightingOrderNBC",
		"UK3CB_BAF_H_Beret_RA",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
};
class TWC_Infantry_ColdWar_COIN_NBC_Company_2iC: TWC_Infantry_ColdWar_Regular_NBC_Company_2iC
{
	CATEGORY(TWC_Infantry_COIN_NBC)
	backpack = "TWC_Backpack_ColdWar_COIN_Platoon_Commander";
	linkedItems[]=
	{
		"SP_P58_FightingOrderNBC",
		"UK3CB_BAF_H_Beret_RA",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
	respawnLinkedItems[]=
	{
		"SP_P58_FightingOrderNBC",
		"UK3CB_BAF_H_Beret_RA",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
};
class TWC_Infantry_ColdWar_COIN_NBC_Company_Sergeant: TWC_Infantry_ColdWar_Regular_NBC_Company_Sergeant
{
	CATEGORY(TWC_Infantry_COIN_NBC)
	backpack = "TWC_Backpack_ColdWar_COIN_Platoon_Sergeant";
	linkedItems[] =
	{
		"SP_P58_FightingOrderNBC",
		"UK3CB_BAF_H_Beret_RA",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
	respawnLinkedItems[] =
	{
		"SP_P58_FightingOrderNBC",
		"UK3CB_BAF_H_Beret_RA",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
};

//Sniper Team
class TWC_Infantry_ColdWar_COIN_NBC_Sniper: TWC_Infantry_ColdWar_Regular_NBC_Sniper
{
	CATEGORY(TWC_Infantry_COIN_NBC)
	linkedItems[]=
	{
		"SP_P58_FightingOrderNBC",
		"UK3CB_BAF_H_Beret_RA",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
	respawnLinkedItems[]=
	{
		"SP_P58_FightingOrderNBC",
		"UK3CB_BAF_H_Beret_RA",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
};
class TWC_Infantry_ColdWar_COIN_NBC_Spotter: TWC_Infantry_ColdWar_Regular_NBC_Spotter
{
	CATEGORY(TWC_Infantry_COIN_NBC)
	linkedItems[]=
	{
		"SP_P58_FightingOrderNBC",
		"UK3CB_BAF_H_Beret_RA",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
	respawnLinkedItems[]=
	{
		"SP_P58_FightingOrderNBC",
		"UK3CB_BAF_H_Beret_RA",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
};

//Artillery Crew
class TWC_Infantry_ColdWar_COIN_NBC_Artillery_Commander: TWC_Infantry_ColdWar_Regular_NBC_Artillery_Commander
{
	CATEGORY(TWC_Infantry_COIN_NBC)
	linkedItems[]=
	{
		"SP_P58_FightingOrderNBC",
		"UK3CB_BAF_H_Beret_RA",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
	respawnLinkedItems[]=
	{
		"SP_P58_FightingOrderNBC",
		"UK3CB_BAF_H_Beret_RA",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
};
class TWC_Infantry_ColdWar_COIN_NBC_Artillery_Crew: TWC_Infantry_ColdWar_Regular_NBC_Artillery_Crew
{
	CATEGORY(TWC_Infantry_COIN_NBC)
	linkedItems[]=
	{
		"SP_P58_FightingOrderNBC",
		"UK3CB_BAF_H_Beret_RA",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
	respawnLinkedItems[]=
	{
		"SP_P58_FightingOrderNBC",
		"UK3CB_BAF_H_Beret_RA",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
};
class TWC_Infantry_ColdWar_COIN_NBC_FO: TWC_Infantry_ColdWar_Regular_NBC_FO
{
	CATEGORY(TWC_Infantry_COIN_NBC)
	linkedItems[]=
	{
		"SP_P58_FightingOrderNBC",
		"UK3CB_BAF_H_Beret_RA",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
	respawnLinkedItems[]=
	{
		"SP_P58_FightingOrderNBC",
		"UK3CB_BAF_H_Beret_RA",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
};

//Aircraft
class TWC_Infantry_ColdWar_COIN_NBC_FAC: TWC_Infantry_ColdWar_Regular_NBC_FAC
{
	CATEGORY(TWC_Infantry_COIN_NBC)
	linkedItems[]=
	{
		"SP_P58_FightingOrderNBC",
		"UK3CB_BAF_H_Beret_RA",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
	respawnLinkedItems[]=
	{
		"SP_P58_FightingOrderNBC",
		"UK3CB_BAF_H_Beret_RA",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
};