class 2000_USMC_Base: B_Soldier_base_F
{
scope=2;
displayName="Rifleman";
faction="twc_public_usmc";
editorSubcategory = "US_Men_2000";
vehicleClass="US_Men_2000";
icon="iconMan";
nakedUniform="U_BasicBody";
uniformClass="rhs_uniform_FROG01_wd";
twc_radioType = "ACRE_PRC148";
twc_radioChannel = 3;
backpack="TWC_Backpack_USMC2000_Rifleman";
linkedItems[]=
{
"CUP_V_B_Interceptor_Grenadier_M81",
"rhsusf_lwh_helmet_marpatwd",
"ItemMap",
"ItemCompass",
"ItemWatch"
};
respawnLinkedItems[]=
{
"CUP_V_B_Interceptor_Grenadier_M81",
"rhsusf_lwh_helmet_marpatwd",
"ItemMap",
"ItemCompass",
"ItemWatch"
};
Items[]=
{
"ACE_fieldDressing",
"ACRE_PRC148",
"ACE_EarPlugs",

"ACE_fieldDressing",
"ACE_fieldDressing",
"ACE_fieldDressing",
"ACE_packingBandage",
"ACE_packingBandage",
"ACE_packingBandage",
"ACE_packingBandage",
"ACE_packingBandage",
"ACE_elasticBandage",
"ACE_elasticBandage",
"ACE_elasticBandage",
"ACE_elasticBandage",
"ACE_elasticBandage",
"ACE_quikclot",
"ACE_quikclot",
"ACE_morphine",
"ACE_epinephrine",
"ACE_tourniquet",
"ACE_tourniquet",
"ACE_MapTools"
};
respawnitems[]=
{
"ACE_fieldDressing",
"ACRE_PRC148",
"ACE_EarPlugs",

"ACE_fieldDressing",
"ACE_fieldDressing",
"ACE_fieldDressing",
"ACE_packingBandage",
"ACE_packingBandage",
"ACE_packingBandage",
"ACE_packingBandage",
"ACE_packingBandage",
"ACE_elasticBandage",
"ACE_elasticBandage",
"ACE_elasticBandage",
"ACE_elasticBandage",
"ACE_elasticBandage",
"ACE_quikclot",
"ACE_quikclot",
"ACE_morphine",
"ACE_epinephrine",
"ACE_tourniquet",
"ACE_tourniquet",
"ACE_MapTools"
};
weapons[]=
{
"Throw",
"Put",
"CUP_TWC_arifle_M16A4_Grip_clean"
};
respawnweapons[]=
{
"Throw",
"Put",
"CUP_TWC_arifle_M16A4_Grip_clean"
};
magazines[]=
{
"CUP_30Rnd_556x45_Stanag",
"CUP_30Rnd_556x45_Stanag",
"CUP_30Rnd_556x45_Stanag",
"CUP_30Rnd_556x45_Stanag",
"CUP_30Rnd_556x45_Stanag",
"CUP_30Rnd_556x45_Stanag",
"CUP_30Rnd_556x45_Stanag",
"CUP_30Rnd_556x45_Stanag",
"CUP_30Rnd_556x45_Stanag_Tracer_Red",
"CUP_30Rnd_556x45_Stanag_Tracer_Red",
"HandGrenade",
"HandGrenade",
"1Rnd_HE_Grenade_shell",
"SmokeShell",
"SmokeShell"
};
Respawnmagazines[]=
{
"CUP_30Rnd_556x45_Stanag",
"CUP_30Rnd_556x45_Stanag",
"CUP_30Rnd_556x45_Stanag",
"CUP_30Rnd_556x45_Stanag",
"CUP_30Rnd_556x45_Stanag",
"CUP_30Rnd_556x45_Stanag",
"CUP_30Rnd_556x45_Stanag",
"CUP_30Rnd_556x45_Stanag",
"CUP_30Rnd_556x45_Stanag_Tracer_Red",
"CUP_30Rnd_556x45_Stanag_Tracer_Red",
"HandGrenade",
"HandGrenade",
"1Rnd_HE_Grenade_shell",
"SmokeShell",
"SmokeShell"
};
};

class 2000_USMC_Base_d: 2000_USMC_Base
{
scope=2;
uniformClass="rhs_uniform_FROG01_d";
linkedItems[]=
{
"CUP_V_B_Interceptor_Grenadier_M81",
"rhsusf_lwh_helmet_marpatd_ess",
"ItemMap",
"ItemCompass",
"ItemWatch"
};
respawnLinkedItems[]=
{
"CUP_V_B_Interceptor_Grenadier_M81",
"rhsusf_lwh_helmet_marpatd_ess",
"ItemMap",
"ItemCompass",
"ItemWatch"
};

};


class 2000_USMC_Squadleader: 2000_USMC_Base
{
scope=2;
displayName="Squad Leader@USMC Section";
icon="iconManLeader";
backpack="TWC_Backpack_USMC2000_Sectionleader";
linkedItems[]=
{
"CUP_V_B_Interceptor_Rifleman_M81",
"rhsusf_mich_helmet_marpatwd",
"ItemMap",
"ItemMicroDAGR",
"ItemCompass",
"ItemWatch"
};
respawnLinkedItems[]=
{
"CUP_V_B_Interceptor_Rifleman_M81",
"rhsusf_mich_helmet_marpatwd",
"ItemMap",
"ItemMicroDAGR",
"ItemCompass",
"ItemWatch"
};
weapons[]=
{
"Throw",
"Put",
"ACE_Yardage450",
"twc_CUP_arifle_M16A4_Grip_acog",
"rhsusf_weap_m1911a1"
};
respawnweapons[]=
{
"Throw",
"Put",
"ACE_Yardage450",
"twc_CUP_arifle_M16A4_Grip_acog",
"rhsusf_weap_m1911a1"
};
magazines[]=
{
"rhsusf_mag_7x45acp_MHP",
"rhsusf_mag_7x45acp_MHP",
"CUP_30Rnd_556x45_Stanag",
"CUP_30Rnd_556x45_Stanag",
"CUP_30Rnd_556x45_Stanag",
"CUP_30Rnd_556x45_Stanag",
"CUP_30Rnd_556x45_Stanag",
"CUP_30Rnd_556x45_Stanag",
"CUP_30Rnd_556x45_Stanag",
"CUP_30Rnd_556x45_Stanag",
"CUP_30Rnd_556x45_Stanag_Tracer_Red",
"CUP_30Rnd_556x45_Stanag_Tracer_Red",
"HandGrenade",
"HandGrenade",
"1Rnd_HE_Grenade_shell",
"SmokeShell",
"SmokeShell"
};
Respawnmagazines[]=
{
"rhsusf_mag_7x45acp_MHP",
"rhsusf_mag_7x45acp_MHP",
"CUP_30Rnd_556x45_Stanag",
"CUP_30Rnd_556x45_Stanag",
"CUP_30Rnd_556x45_Stanag",
"CUP_30Rnd_556x45_Stanag",
"CUP_30Rnd_556x45_Stanag",
"CUP_30Rnd_556x45_Stanag",
"CUP_30Rnd_556x45_Stanag",
"CUP_30Rnd_556x45_Stanag",
"CUP_30Rnd_556x45_Stanag_Tracer_Red",
"CUP_30Rnd_556x45_Stanag_Tracer_Red",
"HandGrenade",
"HandGrenade",
"1Rnd_HE_Grenade_shell",
"SmokeShell",
"SmokeShell"
};
};
class 2000_USMC_Squadleader_d: 2000_USMC_Squadleader
{
uniformClass="rhs_uniform_FROG01_d";
linkedItems[]=
{
"CUP_V_B_Interceptor_Rifleman_M81",
"rhsusf_lwh_helmet_marpatd",
"ItemMap",
"ItemMicroDAGR",
"ItemCompass",
"ItemWatch"
};
respawnLinkedItems[]=
{
"CUP_V_B_Interceptor_Rifleman_M81",
"rhsusf_lwh_helmet_marpatd",
"ItemMap",
"ItemMicroDAGR",
"ItemCompass",
"ItemWatch"
};
};

class 2000_USMC_Teamleader: 2000_USMC_Base
{
scope=2;
displayName="Team Leader";
icon="iconManLeader";
backpack="TWC_Backpack_USMC2000_Teamleader";
weapons[]=
{
"Throw",
"Put",
"ACE_Yardage450",
"twc_CUP_arifle_M16A4_Grip_acog",
"rhsusf_weap_m1911a1"
};
respawnweapons[]=
{
"Throw",
"Put",
"ACE_Yardage450",
"twc_CUP_arifle_M16A4_Grip_acog",
"rhsusf_weap_m1911a1"
};
magazines[]=
{
"rhsusf_mag_7x45acp_MHP",
"rhsusf_mag_7x45acp_MHP",
"CUP_30Rnd_556x45_Stanag",
"CUP_30Rnd_556x45_Stanag",
"CUP_30Rnd_556x45_Stanag",
"CUP_30Rnd_556x45_Stanag",
"CUP_30Rnd_556x45_Stanag",
"CUP_30Rnd_556x45_Stanag",
"CUP_30Rnd_556x45_Stanag",
"CUP_30Rnd_556x45_Stanag",
"CUP_30Rnd_556x45_Stanag_Tracer_Red",
"CUP_30Rnd_556x45_Stanag_Tracer_Red",
"HandGrenade",
"HandGrenade",
"1Rnd_HE_Grenade_shell",
"SmokeShell",
"SmokeShell"
};
Respawnmagazines[]=
{
"rhsusf_mag_7x45acp_MHP",
"rhsusf_mag_7x45acp_MHP",
"CUP_30Rnd_556x45_Stanag",
"CUP_30Rnd_556x45_Stanag",
"CUP_30Rnd_556x45_Stanag",
"CUP_30Rnd_556x45_Stanag",
"CUP_30Rnd_556x45_Stanag",
"CUP_30Rnd_556x45_Stanag",
"CUP_30Rnd_556x45_Stanag",
"CUP_30Rnd_556x45_Stanag",
"CUP_30Rnd_556x45_Stanag_Tracer_Red",
"CUP_30Rnd_556x45_Stanag_Tracer_Red",
"HandGrenade",
"HandGrenade",
"1Rnd_HE_Grenade_shell",
"SmokeShell",
"SmokeShell"
};
};
class 2000_USMC_Teamleader_d: 2000_USMC_Teamleader
{
uniformClass="rhs_uniform_FROG01_d";
linkedItems[]=
{
"CUP_V_B_Interceptor_Rifleman_M81",
"rhsusf_lwh_helmet_marpatd",
"ItemMap",
"ItemCompass",
"ItemWatch"
};
respawnLinkedItems[]=
{
"CUP_V_B_Interceptor_Rifleman_M81",
"rhsusf_lwh_helmet_marpatd",
"ItemMap",
"ItemCompass",
"ItemWatch"
};
};
class 2000_USMC_Grenadier: 2000_USMC_Base
{
scope=2;
displayName="Grenadier";
backpack="TWC_Backpack_USMC2000_Rifleman";
weapons[]=
{
"Throw",
"Put",
"twc_CUP_arifle_M16A4_GL"
};
respawnweapons[]=
{
"Throw",
"Put",
"twc_CUP_arifle_M16A4_GL"
};
magazines[]=
{
"1Rnd_HE_Grenade_shell",
"1Rnd_HE_Grenade_shell",
"1Rnd_HE_Grenade_shell",
"1Rnd_HE_Grenade_shell",
"1Rnd_HE_Grenade_shell",
"1Rnd_HE_Grenade_shell",
"1Rnd_HE_Grenade_shell",
"1Rnd_HE_Grenade_shell",
"CUP_30Rnd_556x45_Stanag",
"CUP_30Rnd_556x45_Stanag",
"CUP_30Rnd_556x45_Stanag",
"CUP_30Rnd_556x45_Stanag",
"CUP_30Rnd_556x45_Stanag",
"CUP_30Rnd_556x45_Stanag",
"CUP_30Rnd_556x45_Stanag",
"CUP_30Rnd_556x45_Stanag_Tracer_Red",
"CUP_30Rnd_556x45_Stanag_Tracer_Red",
"HandGrenade",
"HandGrenade",
"SmokeShell",
"SmokeShell"
};
Respawnmagazines[]=
{
"1Rnd_HE_Grenade_shell",
"1Rnd_HE_Grenade_shell",
"1Rnd_HE_Grenade_shell",
"1Rnd_HE_Grenade_shell",
"1Rnd_HE_Grenade_shell",
"1Rnd_HE_Grenade_shell",
"1Rnd_HE_Grenade_shell",
"1Rnd_HE_Grenade_shell",
"CUP_30Rnd_556x45_Stanag",
"CUP_30Rnd_556x45_Stanag",
"CUP_30Rnd_556x45_Stanag",
"CUP_30Rnd_556x45_Stanag",
"CUP_30Rnd_556x45_Stanag",
"CUP_30Rnd_556x45_Stanag",
"CUP_30Rnd_556x45_Stanag",
"CUP_30Rnd_556x45_Stanag_Tracer_Red",
"CUP_30Rnd_556x45_Stanag_Tracer_Red",
"HandGrenade",
"HandGrenade",
"SmokeShell",
"SmokeShell"
};
};

class 2000_USMC_Grenadier_d: 2000_USMC_Grenadier
{
uniformClass="rhs_uniform_FROG01_d";
linkedItems[]=
{
"CUP_V_B_Interceptor_Rifleman_M81",
"rhsusf_lwh_helmet_marpatd",
"ItemMap",
"ItemCompass",
"ItemWatch"
};
respawnLinkedItems[]=
{
"CUP_V_B_Interceptor_Rifleman_M81",
"rhsusf_lwh_helmet_marpatd",
"ItemMap",
"ItemCompass",
"ItemWatch"
};
};
class 2000_USMC_Breacher: 2000_USMC_Base
{
scope=2;
displayName="Breacher";
backpack="TWC_Backpack_USMC2000_Breacher";
weapons[]=
{
"Throw",
"Put",
"twc_m1014",
"rhsusf_weap_m1911a1"
};
respawnweapons[]=
{
"Throw",
"Put",
"twc_m1014",
"rhsusf_weap_m1911a1"
};
magazines[]=
{
"rhsusf_mag_7x45acp_MHP",
"rhsusf_mag_7x45acp_MHP",
"rhsusf_8Rnd_00Buck",
"rhsusf_8Rnd_00Buck",
"rhsusf_8Rnd_00Buck",
"rhsusf_8Rnd_00Buck",
"rhsusf_8Rnd_00Buck",
"rhsusf_8Rnd_Slug",
"rhsusf_8Rnd_Slug",
"rhsusf_8Rnd_Slug",
"rhsusf_8Rnd_Slug",
"HandGrenade",
"HandGrenade",
"SmokeShell",
"SmokeShell"
};
Respawnmagazines[]=
{
"rhsusf_mag_7x45acp_MHP",
"rhsusf_mag_7x45acp_MHP",
"rhsusf_8Rnd_00Buck",
"rhsusf_8Rnd_00Buck",
"rhsusf_8Rnd_00Buck",
"rhsusf_8Rnd_00Buck",
"rhsusf_8Rnd_00Buck",
"rhsusf_8Rnd_Slug",
"rhsusf_8Rnd_Slug",
"rhsusf_8Rnd_Slug",
"rhsusf_8Rnd_Slug",
"HandGrenade",
"HandGrenade",
"SmokeShell",
"SmokeShell"
};
};

class 2000_USMC_Breacher_d: 2000_USMC_Breacher
{
uniformClass="rhs_uniform_FROG01_d";
linkedItems[]=
{
"CUP_V_B_Interceptor_Rifleman_M81",
"rhsusf_lwh_helmet_marpatd",
"ItemMap",
"ItemCompass",
"ItemWatch"
};
respawnLinkedItems[]=
{
"CUP_V_B_Interceptor_Rifleman_M81",
"rhsusf_lwh_helmet_marpatd",
"ItemMap",
"ItemCompass",
"ItemWatch"
};
};
class 2000_USMC_Autorifleman: 2000_USMC_Base
{
scope=2;
displayName="Autorifleman";
backpack="TWC_Backpack_USMC2000_Autorifleman";
weapons[]=
{
"Throw",
"Put",
"rhs_weap_m249"
};
respawnweapons[]=
{
"Throw",
"Put",
"rhs_weap_m249"
};
magazines[]=
{
"rhsusf_200rnd_556x45_mixed_box",
"rhsusf_200rnd_556x45_mixed_box",
"rhsusf_200rnd_556x45_mixed_box",
"HandGrenade",
"SmokeShell",
"SmokeShell"
};
Respawnmagazines[]=
{
"rhsusf_200rnd_556x45_mixed_box",
"rhsusf_200rnd_556x45_mixed_box",
"rhsusf_200rnd_556x45_mixed_box",
"HandGrenade",
"SmokeShell",
"SmokeShell"
};
};

class 2000_USMC_Autorifleman_d: 2000_USMC_Autorifleman
{
uniformClass="rhs_uniform_FROG01_d";
linkedItems[]=
{
"CUP_V_B_Interceptor_Rifleman_M81",
"rhsusf_lwh_helmet_marpatd",
"ItemMap",
"ItemCompass",
"ItemWatch"
};
respawnLinkedItems[]=
{
"CUP_V_B_Interceptor_Rifleman_M81",
"rhsusf_lwh_helmet_marpatd",
"ItemMap",
"ItemCompass",
"ItemWatch"
};
};
class 2000_USMC_AsstAutorifleman: 2000_USMC_Base
{
scope=2;
displayName="Asst. Automatic Rifleman";
icon="iconManMG";
backpack="TWC_Backpack_USMC2000_Autorifleman";
weapons[]=
{
"Throw",
"Put",
"CUP_TWC_arifle_M16A4_Grip_clean"
};
respawnweapons[]=
{
"Throw",
"Put",
"CUP_TWC_arifle_M16A4_Grip_clean"
};
magazines[]=
{
"CUP_30Rnd_556x45_Stanag",
"CUP_30Rnd_556x45_Stanag",
"CUP_30Rnd_556x45_Stanag",
"CUP_30Rnd_556x45_Stanag",
"CUP_30Rnd_556x45_Stanag",
"CUP_30Rnd_556x45_Stanag",
"CUP_30Rnd_556x45_Stanag",
"CUP_30Rnd_556x45_Stanag",
"CUP_30Rnd_556x45_Stanag_Tracer_Red",
"CUP_30Rnd_556x45_Stanag_Tracer_Red",
"HandGrenade",
"HandGrenade",
"SmokeShell",
"SmokeShell"
};
Respawnmagazines[]=
{
"CUP_30Rnd_556x45_Stanag",
"CUP_30Rnd_556x45_Stanag",
"CUP_30Rnd_556x45_Stanag",
"CUP_30Rnd_556x45_Stanag",
"CUP_30Rnd_556x45_Stanag",
"CUP_30Rnd_556x45_Stanag",
"CUP_30Rnd_556x45_Stanag",
"CUP_30Rnd_556x45_Stanag",
"CUP_30Rnd_556x45_Stanag_Tracer_Red",
"CUP_30Rnd_556x45_Stanag_Tracer_Red",
"HandGrenade",
"HandGrenade",
"SmokeShell",
"SmokeShell"
};
};

class 2000_USMC_AsstAutorifleman_d: 2000_USMC_AsstAutorifleman
{
uniformClass="rhs_uniform_FROG01_d";
linkedItems[]=
{
"CUP_V_B_Interceptor_Rifleman_M81",
"rhsusf_lwh_helmet_marpatd",
"ItemMap",
"ItemCompass",
"ItemWatch"
};
respawnLinkedItems[]=
{
"CUP_V_B_Interceptor_Rifleman_M81",
"rhsusf_lwh_helmet_marpatd",
"ItemMap",
"ItemCompass",
"ItemWatch"
};
};

class 2000_USMC_Medic: 2000_USMC_Base
{
scope=2;
displayName="Corpsman";
icon="iconManMedic";
backpack="TWC_Backpack_USMC2000_Medic";
attendant = 1;

magazines[]=
{
"CUP_30Rnd_556x45_Stanag",
"CUP_30Rnd_556x45_Stanag",
"CUP_30Rnd_556x45_Stanag",
"CUP_30Rnd_556x45_Stanag",
"CUP_30Rnd_556x45_Stanag",
"CUP_30Rnd_556x45_Stanag_Tracer_Red",
"CUP_30Rnd_556x45_Stanag_Tracer_Red",
"SmokeShell",
"SmokeShell"
};
Respawnmagazines[]=
{
"CUP_30Rnd_556x45_Stanag",
"CUP_30Rnd_556x45_Stanag",
"CUP_30Rnd_556x45_Stanag",
"CUP_30Rnd_556x45_Stanag",
"CUP_30Rnd_556x45_Stanag",
"CUP_30Rnd_556x45_Stanag_Tracer_Red",
"CUP_30Rnd_556x45_Stanag_Tracer_Red",
"SmokeShell",
"SmokeShell"
};
};

class 2000_USMC_Marksman: 2000_USMC_Base
{
scope=2;
displayName="Marksman";

magazines[]=
{
"CUP_30Rnd_556x45_Stanag_Tracer_Red",
"CUP_30Rnd_556x45_Stanag_Tracer_Red",
"CUP_30Rnd_556x45_Stanag_Tracer_Red",
"CUP_30Rnd_556x45_Stanag_Tracer_Red",
"CUP_30Rnd_556x45_Stanag_Tracer_Red",
"CUP_30Rnd_556x45_Stanag_Tracer_Red",
"CUP_30Rnd_556x45_Stanag_Tracer_Red",
"SmokeShell",
"SmokeShell"
};
Respawnmagazines[]=
{
"CUP_30Rnd_556x45_Stanag_Tracer_Red",
"CUP_30Rnd_556x45_Stanag_Tracer_Red",
"CUP_30Rnd_556x45_Stanag_Tracer_Red",
"CUP_30Rnd_556x45_Stanag_Tracer_Red",
"CUP_30Rnd_556x45_Stanag_Tracer_Red",
"CUP_30Rnd_556x45_Stanag_Tracer_Red",
"CUP_30Rnd_556x45_Stanag_Tracer_Red",
"SmokeShell",
"SmokeShell"
};
weapons[]=
{
"Throw",
"Put",
"twc_CUP_arifle_M16A4_Grip_acog_sdmr"
};
respawnweapons[]=
{
"Throw",
"Put",
"twc_CUP_arifle_M16A4_Grip_acog_sdmr"
};
};

class 2000_USMC_Medic_d: 2000_USMC_Medic
{
uniformClass="rhs_uniform_FROG01_d";
linkedItems[]=
{
"CUP_V_B_Interceptor_Rifleman_M81",
"rhsusf_lwh_helmet_marpatd",
"ItemMap",
"ItemCompass",
"ItemWatch"
};
respawnLinkedItems[]=
{
"CUP_V_B_Interceptor_Rifleman_M81",
"rhsusf_lwh_helmet_marpatd",
"ItemMap",
"ItemCompass",
"ItemWatch"
};
};

class 2000_USMC_Platoon_Commander: 2000_USMC_Squadleader
{
scope=2;
displayName="USMC Platoon Commander";
backpack="rhsusf_assault_eagleaiii_coy";
icon="iconManLeader";
linkedItems[]=
{
"rhsusf_spc_squadleader",
"rhsusf_mich_helmet_marpatwd",
"ItemMap",
"ItemcTab",
"ItemCompass",
"ItemWatch"
};
respawnLinkedItems[]=
{
"rhsusf_spc_squadleader",
"rhsusf_mich_helmet_marpatwd",
"ItemMap",
"ItemcTab",
"ItemCompass",
"ItemWatch"
};
};
class 2000_USMC_Platoon_Sergeant: 2000_USMC_Platoon_Commander
{
scope=2;
displayName="USMC Platoon Commander";
backpack="rhsusf_assault_eagleaiii_coy";
icon="iconManLeader";
linkedItems[]=
{
"rhsusf_spc_squadleader",
"rhs_uniform_FROG01_d",
"ItemMap",
"ItemcTab",
"ItemCompass",
"ItemWatch"
};
respawnLinkedItems[]=
{
"rhsusf_spc_squadleader",
"rhs_uniform_FROG01_d",
"ItemMap",
"ItemcTab",
"ItemCompass",
"ItemWatch"
};
};
class 2000_USMC_VehicleCommander: 2000_USMC_Base
{
scope=2;
displayName="Vehicle Commander";
uniformClass="CUP_U_B_USArmy_PilotOverall";
backpack="TWC_Backpack_Modern_HeloPilot";
linkedItems[]=
{
"UK3CB_BAF_H_CrewHelmet_B",
"rhsusf_spc_crewman",
"ItemMap",
"ItemCompass",
"ItemWatch",
"ItemcTab"
};
respawnlinkedItems[]=
{
"UK3CB_BAF_H_CrewHelmet_B",
"rhsusf_spc_crewman",
"ItemMap",
"ItemCompass",
"ItemWatch",
"ItemcTab"
};
weapons[]=
{
"Throw",
"Put",
"rhs_weap_m4"
};
respawnweapons[]=
{
"Throw",
"Put",
"rhs_weap_m4"
};
magazines[]=
{
"rhs_mag_30Rnd_556x45_Mk318_Stanag",
"rhs_mag_30Rnd_556x45_Mk318_Stanag",
"rhs_mag_30Rnd_556x45_Mk318_Stanag",
"SmokeShell",
"SmokeShell"
};
Respawnmagazines[]=
{
"rhs_mag_30Rnd_556x45_Mk318_Stanag",
"rhs_mag_30Rnd_556x45_Mk318_Stanag",
"rhs_mag_30Rnd_556x45_Mk318_Stanag",
"SmokeShell",
"SmokeShell"
};
};
class 2000_USMC_VehicleCrew:2000_USMC_vehiclecommander
{
	backpack ="";
displayName="Vehicle Crew";
};
class 2000_USMC_HeliPilot: 2000_USMC_Base
{
scope=2;
displayName="USMC Helicopter Pilot";
uniformClass="CUP_U_B_USArmy_PilotOverall";
backpack="TWC_Backpack_Modern_HeloPilot";
linkedItems[]=
{
"CUP_H_USMC_Helmet_Pilot",
"CUP_V_B_PilotVest",
"ItemMap",
"ItemCompass",
"ItemWatch",
"ItemcTab"
};
respawnLinkedItems[]=
{
"CUP_H_USMC_Helmet_Pilot",
"CUP_V_B_PilotVest",
"ItemMap",
"ItemCompass",
"ItemWatch",
"ItemcTab"
};
weapons[]=
{
"Throw",
"Put",
"rhsusf_weap_m1911a1",
"rhs_weap_m4"
};
respawnweapons[]=
{
"Throw",
"Put",
"rhsusf_weap_m1911a1",
"rhs_weap_m4"
};
magazines[]=
{
"rhs_mag_30Rnd_556x45_Mk318_Stanag",
"rhs_mag_30Rnd_556x45_Mk318_Stanag",
"rhs_mag_30Rnd_556x45_Mk318_Stanag",
"rhsusf_mag_7x45acp_MHP",
"rhsusf_mag_7x45acp_MHP",
"SmokeShell",
"SmokeShell"
};
Respawnmagazines[]=
{
"rhs_mag_30Rnd_556x45_Mk318_Stanag",
"rhs_mag_30Rnd_556x45_Mk318_Stanag",
"rhs_mag_30Rnd_556x45_Mk318_Stanag",
"rhsusf_mag_7x45acp_MHP",
"rhsusf_mag_7x45acp_MHP",
"SmokeShell",
"SmokeShell"
};
};

class 2000_USMC_crewchief:2000_USMC_HeliPilot
{
scope=2;
displayName="Helicopter Crew Chief";
uniformClass="CUP_U_B_USArmy_PilotOverall";
backpack="TWC_Backpack_Modern_HeloPilot";
};
class 2000_USMC_JetPilot: 2000_USMC_Base
{
_generalMacro="Modern_USMCJetPilot";
scope=2;
displayName="Fixed Wing Pilot";
faction="twc_public_usmc";
editorSubcategory = "Men_Modern";
vehicleClass="Men_Modern";
icon="iconMan";
nakedUniform="U_BasicBody";
uniformClass="CUP_U_B_USMC_PilotOverall";
backpack="TWC_Backpack_Modern_HeloPilot";
linkedItems[]=
{
"RHS_jetpilot_usaf",
"CUP_V_B_PilotVest",
"ItemMap",
"ItemCompass",
"ItemWatch",
"ItemcTab"
};
respawnLinkedItems[]=
{
"RHS_jetpilot_usaf",
"CUP_V_B_PilotVest",
"ItemMap",
"ItemCompass",
"ItemWatch",
"ItemcTab"
};
weapons[]=
{
"Throw",
"Put",
"rhsusf_weap_m9"
};
respawnweapons[]=
{
"Throw",
"Put",
"rhsusf_weap_m9"
};
magazines[]=
{
"rhsusf_mag_15Rnd_9x19_JHP",
"rhsusf_mag_15Rnd_9x19_JHP",
"SmokeShell",
"SmokeShell"
};
Respawnmagazines[]=
{
"rhsusf_mag_15Rnd_9x19_JHP",
"rhsusf_mag_15Rnd_9x19_JHP",
"SmokeShell",
"SmokeShell"
};
};
class 2000_USMC_MortarGunner: 2000_USMC_Rifleman
{
scope=2;
displayName="USMC Mortar Gunner";
icon="iconMan";
backpack="rhsusf_assault_eagleaiii_coy";
linkedItems[]=
{
"rhsusf_spc_corpsman",
"UK3CB_BAF_H_Mk7_Camo_D",
"ItemMap",
"ItemCompass",
"ItemWatch"
};
respawnLinkedItems[]=
{
"rhsusf_spc_corpsman",
"UK3CB_BAF_H_Mk7_Camo_D",
"ItemMap",
"ItemCompass",
"ItemWatch"
};
weapons[]=
{
"Throw",
"Put",
"twc_rhs_weap_m4a1_acog_lazer",
"UK3CB_BAF_L16"
};
respawnweapons[]=
{
"Throw",
"Put",
"twc_rhs_weap_m4a1_acog_lazer",
"UK3CB_BAF_L16"
};
magazines[]=
{
"rhs_mag_30Rnd_556x45_Mk318_Stanag",
"rhs_mag_30Rnd_556x45_Mk318_Stanag",
"rhs_mag_30Rnd_556x45_Mk318_Stanag",
"SmokeShell"
};
Respawnmagazines[]=
{
"rhs_mag_30Rnd_556x45_Mk318_Stanag",
"rhs_mag_30Rnd_556x45_Mk318_Stanag",
"rhs_mag_30Rnd_556x45_Mk318_Stanag",
"SmokeShell"
};
};
class 2000_USMC_MortarAssistant: 2000_USMC_MortarGunner
{
displayName="USMC Mortar Assistant";
backpack="rhsusf_assault_eagleaiii_coy";
weapons[]=
{
"Throw",
"Put",
"twc_rhs_weap_m4a1_acog_lazer",
"UK3CB_BAF_L16_Tripod"
};
respawnweapons[]=
{
"Throw",
"Put",
"twc_rhs_weap_m4a1_acog_lazer",
"UK3CB_BAF_L16_Tripod"
};
};
class 2000_USMC_Sniper: 2000_USMC_Base
{
scope=2;
displayName="USMC Sniper";
nakedUniform="U_BasicBody";
uniformClass="rhs_uniform_FROG01_d";
backpack="rhsusf_assault_eagleaiii_coy";
linkedItems[]=
{
"rhsusf_spc_light",
"rhsusf_mich_helmet_marpatwd_norotos_headset",
"ItemMap",
"ItemcTab",
"ItemCompass",
"ItemWatch"
};
respawnLinkedItems[]=
{
"rhsusf_spc_light",
"rhsusf_mich_helmet_marpatwd_norotos_headset",
"ItemMap",
"ItemcTab",
"ItemCompass",
"ItemWatch"
};
weapons[]=
{
"Throw",
"Put",
"ACE_Vector",
"rhs_weap_m40a5_d"
};
respawnweapons[]=
{
"Throw",
"Put",
"ACE_Vector",
"rhsusf_weap_m1911a1",
"rhs_weap_m40a5_d"
};
magazines[]=
{
"rhsusf_mag_7x45acp_MHP",
"rhsusf_mag_7x45acp_MHP",
"rhsusf_10Rnd_762x51_m118_special_Mag",
"rhsusf_10Rnd_762x51_m118_special_Mag",
"rhsusf_10Rnd_762x51_m118_special_Mag",
"rhsusf_10Rnd_762x51_m118_special_Mag",
"rhsusf_10Rnd_762x51_m118_special_Mag",
"HandGrenade",
"SmokeShell",
"SmokeShell",
"SmokeShell"
};
Respawnmagazines[]=
{
"rhsusf_mag_7x45acp_MHP",
"rhsusf_mag_7x45acp_MHP",
"rhsusf_10Rnd_762x51_m118_special_Mag",
"rhsusf_10Rnd_762x51_m118_special_Mag",
"rhsusf_10Rnd_762x51_m118_special_Mag",
"rhsusf_10Rnd_762x51_m118_special_Mag",
"rhsusf_10Rnd_762x51_m118_special_Mag",
"HandGrenade",
"SmokeShell",
"SmokeShell",
"SmokeShell"
};
};
class 2000_USMC_Spotter: 2000_USMC_Sniper
{
displayName="USMC Spotter";
icon="iconManLeader";
nakedUniform="U_BasicBody";
uniformClass="rhs_uniform_FROG01_d";
backpack="rhsusf_assault_eagleaiii_coy";
weapons[]=
{
"Throw",
"Put",
"ACE_Vector",
"rhs_weap_m4_carryhandle_pmag"
};
respawnweapons[]=
{
"Throw",
"Put",
"ACE_Vector",
"rhs_weap_m4_carryhandle_pmag"
};
magazines[]=
{
"rhsusf_mag_7x45acp_MHP",
"rhsusf_mag_7x45acp_MHP",
"CUP_30Rnd_556x45_Stanag",
"CUP_30Rnd_556x45_Stanag",
"CUP_30Rnd_556x45_Stanag",
"CUP_30Rnd_556x45_Stanag",
"CUP_30Rnd_556x45_Stanag",
"CUP_30Rnd_556x45_Stanag",
"HandGrenade",
"SmokeShell",
"SmokeShell",
"SmokeShell"
};
Respawnmagazines[]=
{
"rhsusf_mag_7x45acp_MHP",
"rhsusf_mag_7x45acp_MHP",
"CUP_30Rnd_556x45_Stanag",
"CUP_30Rnd_556x45_Stanag",
"CUP_30Rnd_556x45_Stanag",
"CUP_30Rnd_556x45_Stanag",
"CUP_30Rnd_556x45_Stanag",
"CUP_30Rnd_556x45_Stanag",
"HandGrenade",
"SmokeShell",
"SmokeShell",
"SmokeShell"
};
};
class 2000_USMC_FAC: 2000_USMC_Base
{
scope=2;
displayName="USMC FAC";
backpack="rhsusf_assault_eagleaiii_coy";
linkedItems[]=
{
"rhsusf_spc_crewman",
"rhsusf_mich_helmet_marpatwd",
"ItemMap",
"ItemcTab",
"ItemCompass",
"ItemWatch"
};
respawnLinkedItems[]=
{
"rhsusf_spc_crewman",
"rhsusf_mich_helmet_marpatwd",
"ItemMap",
"ItemcTab",
"ItemCompass",
"ItemWatch"
};
weapons[]=
{
"Throw",
"Put",
"UK3CB_BAF_Soflam_Laserdesignator",
"rhs_weap_m4_carryhandle_pmag"
};
respawnweapons[]=
{
"Throw",
"Put",
"UK3CB_BAF_Soflam_Laserdesignator",
"rhs_weap_m4_carryhandle_pmag"
};
magazines[]=
{
"CUP_30Rnd_556x45_Stanag_Tracer_Red",
"CUP_30Rnd_556x45_Stanag_Tracer_Red",
"CUP_30Rnd_556x45_Stanag_Tracer_Red",
"CUP_30Rnd_556x45_Stanag_Tracer_Red",
"CUP_30Rnd_556x45_Stanag_Tracer_Red"
};
Respawnmagazines[]=
{
"CUP_30Rnd_556x45_Stanag_Tracer_Red",
"CUP_30Rnd_556x45_Stanag_Tracer_Red",
"CUP_30Rnd_556x45_Stanag_Tracer_Red",
"CUP_30Rnd_556x45_Stanag_Tracer_Red",
"CUP_30Rnd_556x45_Stanag_Tracer_Red"
};
};