	class 1970_British_Base: B_Soldier_base_F
	{
		scope=1;
		modelSides[] = {0,1,2,3};
		displayName="Base";
		faction="twc_public_baf";
		editorSubcategory = "Men_1990W";
		vehicleClass="Men_1990W";
		icon="iconMan";
		nakedUniform="U_BasicBody";
		uniformClass="CUP_U_B_BDUv2_dirty_DPM";
		weapons[]=
		{
			"Throw",
			"Put",	
			"UK3CB_BAF_L1A1_Wood"
		};
		respawnweapons[]=
		{
			"Throw",
			"Put",	
			"UK3CB_BAF_L1A1_Wood"
		};
		magazines[]=
		{
			"UK3CB_BAF_762_20Rnd",
			"UK3CB_BAF_762_20Rnd",
			"UK3CB_BAF_762_20Rnd",
			"UK3CB_BAF_762_20Rnd",
			"UK3CB_BAF_762_20Rnd",
			"UK3CB_BAF_762_20Rnd_T",
			"UK3CB_BAF_762_20Rnd_T",
			"UK3CB_BAF_762_20Rnd_T",
			"HandGrenade",
			"SmokeShell"
		};
		Respawnmagazines[]=
		{
			"UK3CB_BAF_762_20Rnd",
			"UK3CB_BAF_762_20Rnd",
			"UK3CB_BAF_762_20Rnd",
			"UK3CB_BAF_762_20Rnd",
			"UK3CB_BAF_762_20Rnd",
			"UK3CB_BAF_762_20Rnd_T",
			"UK3CB_BAF_762_20Rnd_T",
			"UK3CB_BAF_762_20Rnd_T",
			"HandGrenade",
			"SmokeShell"
		};	
		linkedItems[]=
		{
			"UK3CB_BAF_H_Beret_PWRR",
			
			"ItemCompass",
			"ItemWatch"
		};
		respawnLinkedItems[]=
		{
			"UK3CB_BAF_H_Beret_PWRR",
			
			"ItemCompass",
			"ItemWatch"
		};
		Items[]=
		{
			"ACE_EarPlugs",
			"ACE_fieldDressing",
				
			"ACE_fieldDressing",
			"ACE_fieldDressing",
			"ACE_fieldDressing",
			"ACE_packingBandage",
			"ACE_packingBandage",
			"ACE_packingBandage",
			"ACE_packingBandage",
			"ACE_packingBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_quikclot",
			"ACE_quikclot",
			"ACE_morphine",
			"ACE_tourniquet",
			"ACE_tourniquet",
			"ACE_MapTools"
		};
		respawnitems[]=
		{
			"ACE_EarPlugs",
			"ACE_fieldDressing",
				
			"ACE_fieldDressing",
			"ACE_fieldDressing",
			"ACE_fieldDressing",
			"ACE_packingBandage",
			"ACE_packingBandage",
			"ACE_packingBandage",
			"ACE_packingBandage",
			"ACE_packingBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_quikclot",
			"ACE_quikclot",
			"ACE_morphine",
			"ACE_tourniquet",
			"ACE_tourniquet"
		};		
	};
	class 1970_British_SectionCommander: 1970_British_Base
	{
		scope=2;
		displayName="Section Leader @British Army";
		icon="iconManLeader";
		backpack="TWC_Backpack_1970_Sectionlead";
		uniformClass="UK3CB_BAF_U_JumperUniform_Plain";
		linkedItems[]=
		{
			"CUP_V_CDF_6B3_2_Green",
			"UK3CB_BAF_H_Beret_PWRR",
			"ItemMap",
			"ItemCompass",
			"ItemWatch"
		};
		respawnLinkedItems[]=
		{
			"CUP_V_CDF_6B3_2_Green",
			"UK3CB_BAF_H_Beret_PWRR",
			"ItemMap",
			"ItemCompass",
			"ItemWatch"
		};
		weapons[]=
		{
			"Throw",
			"Put",
			"Binocular",
			"UK3CB_BAF_L1A1",
			"UK3CB_BAF_L9A1"
		};
		respawnweapons[]=
		{
			"Throw",
			"Put",
			"Binocular",
			"UK3CB_BAF_L1A1",
			"UK3CB_BAF_L9A1"
		};
		magazines[]=
		{
			"UK3CB_BAF_762_20Rnd",
			"UK3CB_BAF_9_13Rnd",
			"UK3CB_BAF_9_13Rnd",
			"UK3CB_BAF_762_20Rnd",
			"UK3CB_BAF_762_20Rnd",
			"UK3CB_BAF_762_20Rnd",
			"UK3CB_BAF_762_20Rnd",
			"UK3CB_BAF_762_20Rnd_T",
			"UK3CB_BAF_762_20Rnd_T",
			"UK3CB_BAF_762_20Rnd_T",
			"HandGrenade",
			"SmokeShell"
		};
		Respawnmagazines[]=
		{
			"UK3CB_BAF_762_20Rnd",
			"UK3CB_BAF_9_13Rnd",
			"UK3CB_BAF_9_13Rnd",
			"UK3CB_BAF_762_20Rnd",
			"UK3CB_BAF_762_20Rnd",
			"UK3CB_BAF_762_20Rnd",
			"UK3CB_BAF_762_20Rnd",
			"UK3CB_BAF_762_20Rnd_T",
			"UK3CB_BAF_762_20Rnd_T",
			"UK3CB_BAF_762_20Rnd_T",
			"HandGrenade",
			"SmokeShell"
		};
	};
	class 1970_British_Rifleman: 1970_British_Base
	{
		scope=2;
		displayName="Rifleman";
		uniformClass="CUP_U_B_BDUv2_dirty_DPM";
		backpack="TWC_Backpack_1970_rifleman_2";
		twc_nobackpack = 1;
		linkedItems[]=
		{
			"UK3CB_BAF_H_Beret_PWRR",
			
			"ItemCompass",
			"ItemWatch"
		};
		respawnLinkedItems[]=
		{
			"UK3CB_BAF_H_Beret_PWRR",
			
			"ItemCompass",
			"ItemWatch"
		};
	};
	
	class 1970_British_pointman: 1970_British_Base
	{
		scope=2;
		displayName="Pointman";
		backpack="TWC_Backpack_1970_rifleman_1";
		uniformClass="CUP_U_B_BDUv2_dirty_DPM";
		linkedItems[]=
		{
			"twc_interceptor_od",
			"CUP_H_RUS_Altyn_Shield_Up_khaki",
			"ItemCompass",
			"ItemWatch"
		};
		respawnLinkedItems[]=
		{
			"twc_interceptor_od",
			"CUP_H_RUS_Altyn_Shield_Up_khaki",
			"ItemCompass",
			"ItemWatch"
		};
	};
	class 1970_British_Marksman: 1970_British_Base
	{
		scope=2;
		displayName="Rifleman (SUIT)";
		uniformClass="CUP_U_B_BDUv2_dirty_DPM";
		icon="iconManMG";
		backpack="TWC_Backpack_1970_rifleman_2";
		linkedItems[]=
		{
			"UK3CB_BAF_H_Beret_PWRR",
			
			"ItemCompass",
			"ItemWatch"
		};
		respawnLinkedItems[]=
		{
			"UK3CB_BAF_H_Beret_PWRR",
			
			"ItemCompass",
			"ItemWatch"
		};
		weapons[]=
		{
			"Throw",
			"Put",	
			"TWC_UK3CB_BAF_L1A1_Wood_SUIT"
		};
		respawnweapons[]=
		{
			"Throw",
			"Put",	
			"TWC_UK3CB_BAF_L1A1_Wood_SUIT"
		};
	};
	class 1970_British_2IC: 1970_British_Base
	{
		scope=2;
		displayName="2IC";
		backpack="TWC_Backpack_1970_2ic";
		twc_nobackpack = 0;
		linkedItems[]=
		{
			"UK3CB_BAF_H_Beret_PWRR",
			"CUP_V_CDF_6B3_2_Green",
			
			"ItemCompass",
			"ItemWatch"
		};
		respawnLinkedItems[]=
		{
			"UK3CB_BAF_H_Beret_PWRR",
			"CUP_V_CDF_6B3_2_Green",
			
			"ItemCompass",
			"ItemWatch"
		};
	};
	
	class 1970_British_MachineGunner: 1970_British_Base
	{
		scope=2;
		displayName="GPMG Gunner";
		uniformClass="CUP_U_B_BDUv2_dirty_DPM";
		backpack="TWC_Backpack_1970_machineGunner";
		linkedItems[]=
		{
			"UK3CB_BAF_H_Beret_PWRR",
			"CUP_V_O_SLA_Carrier_Belt",
			
			"ItemCompass",
			"ItemWatch"
		};
		respawnLinkedItems[]=
		{
			"UK3CB_BAF_H_Beret_PWRR",
			"CUP_V_O_SLA_Carrier_Belt",
			
			"ItemCompass",
			"ItemWatch"
		};
				weapons[]=
		{
		"Throw",
		"Put",
		"UK3CB_BAF_L7A2"
		};
		respawnweapons[]=
		{
		"Throw",
		"Put",
		"UK3CB_BAF_L7A2"
		};
				magazines[]=
		{
		"UK3CB_BAF_762_100Rnd_T",
		"UK3CB_BAF_762_100Rnd_T",
		"UK3CB_BAF_762_100Rnd_T",
		"UK3CB_BAF_762_100Rnd_T",
		"SmokeShell"
		};
		Respawnmagazines[]=
		{
		"UK3CB_BAF_762_100Rnd_T",
		"UK3CB_BAF_762_100Rnd_T",
		"UK3CB_BAF_762_100Rnd_T",
		"UK3CB_BAF_762_100Rnd_T",
		"SmokeShell"
		};
		Items[]=
		{
			"ACE_EarPlugs",
			"ACE_EntrenchingTool",
			"ACE_fieldDressing",
				
			"ACE_fieldDressing",
			"ACE_fieldDressing",
			"ACE_fieldDressing",
			"ACE_packingBandage",
			"ACE_packingBandage",
			"ACE_packingBandage",
			"ACE_packingBandage",
			"ACE_packingBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_quikclot",
			"ACE_quikclot",
			"ACE_morphine",
			"ACE_epinephrine",
			"ACE_tourniquet",
			"ACE_tourniquet",
			"ACE_MapTools"
		};
		respawnitems[]=
		{
			"ACE_EarPlugs",
			"ACE_EntrenchingTool",
			"ACE_fieldDressing",
				
			"ACE_fieldDressing",
			"ACE_fieldDressing",
			"ACE_fieldDressing",
			"ACE_packingBandage",
			"ACE_packingBandage",
			"ACE_packingBandage",
			"ACE_packingBandage",
			"ACE_packingBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_quikclot",
			"ACE_quikclot",
			"ACE_morphine",
			"ACE_epinephrine",
			"ACE_tourniquet",
			"ACE_tourniquet"
		};	
	};
	
		class 1970_British_mg_assistant: 1970_British_Rifleman
	{
		displayName="GPMG Assistant";
		backpack="TWC_Backpack_1970_machineGunner_ass";
		twc_nobackpack = 0;
		linkedItems[]=
		{
			"UK3CB_BAF_H_Beret_PWRR",
			"CUP_V_O_Ins_Carrier_Rig_MG",
			
			"ItemCompass",
			"ItemWatch"
		};
		respawnLinkedItems[]=
		{
			"UK3CB_BAF_H_Beret_PWRR",
			"CUP_V_O_Ins_Carrier_Rig_MG",
			
			"ItemCompass",
			"ItemWatch"
		};
	};
	


	class 1970_British_Medic: 1970_British_Base
	{
		scope=2;
		displayName="Medic";
		backpack="TWC_Backpack_USMC2000_Medic";
		attendant = 1;
		magazines[]=
		{
			"SmokeShell",
			"UK3CB_BAF_762_20Rnd",
			"UK3CB_BAF_762_20Rnd",
			"UK3CB_BAF_762_20Rnd",
			"UK3CB_BAF_762_20Rnd",
			"SmokeShell",
			"SmokeShell",
			"SmokeShell",
			"SmokeShell"
		};
		Respawnmagazines[]=
		{
			"SmokeShell",
			"UK3CB_BAF_762_20Rnd",
			"UK3CB_BAF_762_20Rnd",
			"UK3CB_BAF_762_20Rnd",
			"UK3CB_BAF_762_20Rnd",
			"SmokeShell",
			"SmokeShell",
			"SmokeShell",
			"SmokeShell"
		};
		linkedItems[]=
		{
			"UK3CB_BAF_H_Beret_PWRR",
			"twc_interceptor_od",
			
			"ItemCompass",
			"ItemWatch"
		};
		respawnLinkedItems[]=
		{
			"UK3CB_BAF_H_Beret_PWRR",
			"twc_interceptor_od",
			
			"ItemCompass",
			"ItemWatch"
		};
		class EventHandlers: EventHandlers
		{
			init = "init = if(local (_this select 0))then{(_this select 0) setVariable [""ace_medical_medicClass"",1]};";
		};
	};
	class 1970_British_HeliPilot: 1970_British_Base
	{
		scope=2;
		displayName="Helicopter Pilot";
		uniformClass="CUP_U_B_BDUv2_roll_gloves_OD";
		backpack="TWC_Backpack_1970_Sectionlead";
		linkedItems[]=
		{
			"CUP_H_BAF_PILOT",
			"ItemCompass",
			"ItemWatch"
		};
		respawnLinkedItems[]=
		{
			"CUP_H_BAF_PILOT",
			"ItemCompass",
			"ItemWatch"
		};
		weapons[]=
		{
			"Throw",
			"Put",
			"UK3CB_BAF_L9A1"
		};
		respawnweapons[]=
		{
			"Throw",
			"Put",
			"UK3CB_BAF_L9A1"
		};
		magazines[]=
		{
			"SmokeShell",
			"UK3CB_BAF_9_13Rnd",
			"UK3CB_BAF_9_13Rnd",
			"SmokeShell"
		};
		Respawnmagazines[]=
		{
			"SmokeShell",
			"UK3CB_BAF_9_13Rnd",
			"UK3CB_BAF_9_13Rnd",
			"SmokeShell"

		};
		
		Items[]=
		{
			"ACE_EarPlugs",
			"ACE_fieldDressing",
			"ACE_fieldDressing",
			"ACE_fieldDressing",
			"ACE_fieldDressing",
			"ACE_packingBandage",
			"ACE_packingBandage",
			"ACE_packingBandage",
			"ACE_packingBandage",
			"ACE_packingBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_quikclot",
			"ACE_quikclot",
			"ACE_morphine",
			"ACE_epinephrine",
			"ACE_tourniquet",
			"ACE_tourniquet",
			"ACE_MapTools"
		};
		respawnitems[]=
		{
			"ACE_EarPlugs",
			"ACE_fieldDressing",
			"ACE_fieldDressing",
			"ACE_fieldDressing",
			"ACE_fieldDressing",
			"ACE_packingBandage",
			"ACE_packingBandage",
			"ACE_packingBandage",
			"ACE_packingBandage",
			"ACE_packingBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_quikclot",
			"ACE_quikclot",
			"ACE_morphine",
			"ACE_epinephrine",
			"ACE_tourniquet",
			"ACE_tourniquet"
		};	
	};
	class 1970_British_Crewchief: 1970_British_HeliPilot
	{
		scope=2;
		displayName="Helicopter Crew Chief";
	};
	class 1970_British_JetPilot: 1970_British_HeliPilot
	{
		displayName="Jet Pilot";
	};
		class 1970_British_FSTCommander: 1970_British_Base 
	{
		scope=2;
		displayName="FST Commander (90's Woodland)@Fire Support Team";
		icon="iconManLeader";
		uniformClass="UK3CB_BAF_U_Smock_DPMW";
		backpack="TWC_Backpack_1990_Sectionlead";
		linkedItems[]=
		{
			"UK3CB_BAF_V_PLCE_Webbing_DPMW",
			"UK3CB_BAF_H_Mk6_DPMW_C",
			
			"ItemCompass",
			"ItemWatch"
		};
		respawnLinkedItems[]=
		{
			"UK3CB_BAF_V_PLCE_Webbing_DPMW",
			"UK3CB_BAF_H_Mk6_DPMW_C",
			
			"ItemCompass",
			"ItemWatch"
		};
		weapons[]=
		{
			"Throw",
			"Put",
			"Binocular",
			"UK3CB_BAF_L85A1_SUSAT3D",
			"UK3CB_BAF_L9A1"
		};
		respawnweapons[]=
		{
			"Throw",
			"Put",
			"Binocular",
			"UK3CB_BAF_L85A1_SUSAT3D",
			"UK3CB_BAF_L9A1"
		};
		magazines[]=
		{
			"UK3CB_BAF_762_20Rnd",
			"UK3CB_BAF_9_13Rnd",
			"UK3CB_BAF_9_13Rnd",
			"UK3CB_BAF_762_20Rnd",
			"UK3CB_BAF_762_20Rnd",
			"UK3CB_BAF_762_20Rnd",
			"UK3CB_BAF_762_20Rnd_T",
			"UK3CB_BAF_762_20Rnd_T",
			"HandGrenade",
			"HandGrenade",
			"SmokeShell",
			"SmokeShell",
			"SmokeShell"
		};
		Respawnmagazines[]=
		{
			"UK3CB_BAF_762_20Rnd",
			"UK3CB_BAF_9_13Rnd",
			"UK3CB_BAF_9_13Rnd",
			"UK3CB_BAF_762_20Rnd",
			"UK3CB_BAF_762_20Rnd",
			"UK3CB_BAF_762_20Rnd",
			"UK3CB_BAF_762_20Rnd_T",
			"UK3CB_BAF_762_20Rnd_T",
			"HandGrenade",
			"HandGrenade",
			"SmokeShell",
			"SmokeShell",
			"SmokeShell",
			"B_IR_Grenade"
		};
	};

	class 1970_British_FSTForwardObserver: 1970_British_Base
	{
		scope=2;
		displayName="FST Forward Observer (90's Woodland)";
		icon="iconManExplosive";
		uniformClass="UK3CB_BAF_U_Smock_DPMW";
		backpack="UK3CB_BAF_B_Bergen_DPMW_Rifleman_B";
		linkedItems[]=
		{
			"UK3CB_BAF_V_PLCE_Webbing_DPMW",
			"UK3CB_BAF_H_Mk6_DPMW_C",
			
			"ItemCompass",
			"ItemWatch"
		};
		respawnLinkedItems[]=
		{
			"UK3CB_BAF_V_PLCE_Webbing_DPMW",
			"UK3CB_BAF_H_Mk6_DPMW_C",
			
			"ItemCompass",
			"ItemWatch"
		};
		weapons[]=
		{
			"Throw",
			"Put",
			"CUP_SOFLAM",
			"UK3CB_BAF_L85A1_SUSAT3D"
		};
		respawnweapons[]=
		{
			"Throw",
			"Put",
			"CUP_SOFLAM",
			"UK3CB_BAF_L85A1_SUSAT3D"
		};
		magazines[]=
		{
			"UK3CB_BAF_762_20Rnd_T",
			"UK3CB_BAF_762_20Rnd_T",
			"UK3CB_BAF_762_20Rnd_T",
			"UK3CB_BAF_762_20Rnd",
			"UK3CB_BAF_762_20Rnd",
			"UK3CB_BAF_762_20Rnd",
			"UK3CB_BAF_762_20Rnd",
			"UK3CB_BAF_762_20Rnd",
			"HandGrenade",
			"HandGrenade",
			"SmokeShell",
			"SmokeShell",
			"Laserbatteries"
		};
		Respawnmagazines[]=
		{
			"UK3CB_BAF_762_20Rnd",
			"UK3CB_BAF_762_20Rnd",
			"UK3CB_BAF_762_20Rnd",
			"UK3CB_BAF_762_20Rnd",
			"UK3CB_BAF_762_20Rnd_T",
			"UK3CB_BAF_762_20Rnd_T",
			"HandGrenade",
			"HandGrenade",
			"SmokeShell",
			"SmokeShell",
			"Laserbatteries"
		};
	};

	class 1970_British_FSTAssistant: 1970_British_Base 
	{
		scope=2;
		displayName="FST Assistant (90's Woodland)";
		uniformClass="UK3CB_BAF_U_Smock_DPMW";
		backpack="UK3CB_BAF_B_Carryall_DPMW";
		
		linkedItems[]=
		{
			"UK3CB_BAF_V_PLCE_Webbing_DPMW",
			"UK3CB_BAF_H_Mk6_DPMW_C",
			
			"ItemCompass",
			"ItemWatch"
		};
		respawnLinkedItems[]=
		{
			"UK3CB_BAF_V_PLCE_Webbing_DPMW",
			"UK3CB_BAF_H_Mk6_DPMW_C",
			
			"ItemCompass",
			"ItemWatch"
		};
		weapons[]=
		{
			"Throw",
			"Put",
			"UK3CB_BAF_L85A1_SUSAT3D"
		};
		respawnweapons[]=
		{
			"Throw",
			"Put",	
			"UK3CB_BAF_L85A1_SUSAT3D"
		};
		magazines[]=
		{
			"UK3CB_BAF_762_20Rnd_T",
			"UK3CB_BAF_762_20Rnd_T",
			"UK3CB_BAF_762_20Rnd_T",
			"UK3CB_BAF_762_20Rnd",
			"UK3CB_BAF_762_20Rnd",
			"UK3CB_BAF_762_20Rnd",
			"UK3CB_BAF_762_20Rnd",
			"UK3CB_BAF_762_20Rnd",
			"HandGrenade",
			"HandGrenade",
			"SmokeShell",
			"SmokeShell"
		};
		Respawnmagazines[]=
		{
			"UK3CB_BAF_762_20Rnd_T",
			"UK3CB_BAF_762_20Rnd_T",
			"UK3CB_BAF_762_20Rnd_T",
			"UK3CB_BAF_762_20Rnd",
			"UK3CB_BAF_762_20Rnd",
			"UK3CB_BAF_762_20Rnd",
			"UK3CB_BAF_762_20Rnd",
			"UK3CB_BAF_762_20Rnd",
			"HandGrenade",
			"HandGrenade",
			"SmokeShell",
			"SmokeShell"
		};
	};
		
//////////////////////////////  Mounted  //////////////////////////////
	class 1970_British_sniper: 1970_British_Base
	{
		displayName="Marksman";
		backpack="TWC_Backpack_1970_sniper";
		uniformClass="CUP_U_B_BDUv2_roll_gloves_OD";
		scope=2;
		linkedItems[]=
		{
			"CUP_H_SLA_BeanieGreen",
			
			"ItemCompass",
			"ItemWatch"
		};
		respawnLinkedItems[]=
		{
			"CUP_H_SLA_BeanieGreen",
			
			"ItemCompass",
			"ItemWatch"
		};
		weapons[]=
		{
			"ukcw_l42",
			"Throw",
			"Binocular",
			"Put"
		};
		respawnweapons[]=
		{
			"ukcw_l42",
			"Throw",
			"Binocular",
			"Put"
		};
		magazines[]=
		{
			"ukcw_l42_10rnd_mag",
			"ukcw_l42_10rnd_mag",
			"ukcw_l42_10rnd_mag",
			"ukcw_l42_10rnd_mag",
			"ukcw_l42_10rnd_mag",
			"SmokeShell"
		};
		Respawnmagazines[]=
		{
			"ukcw_l42_10rnd_mag",
			"ukcw_l42_10rnd_mag",
			"ukcw_l42_10rnd_mag",
			"ukcw_l42_10rnd_mag",
			"ukcw_l42_10rnd_mag",
			"SmokeShell"
		};
		Items[]=
		{
			"ACE_EarPlugs",
			"ACE_fieldDressing",
			"ACE_rangecard",
			"ACE_fieldDressing",
			"ACE_fieldDressing",
			"ACE_fieldDressing",
			"ACE_packingBandage",
			"ACE_packingBandage",
			"ACE_packingBandage",
			"ACE_packingBandage",
			"ACE_packingBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_quikclot",
			"ACE_quikclot",
			"ACE_morphine",
			"ACE_tourniquet",
			"ACE_tourniquet",
			"ACE_MapTools"
		};
		respawnitems[]=
		{
			"ACE_EarPlugs",
			"ACE_fieldDressing",
			"ACE_rangecard",
			"ACE_fieldDressing",
			"ACE_fieldDressing",
			"ACE_fieldDressing",
			"ACE_packingBandage",
			"ACE_packingBandage",
			"ACE_packingBandage",
			"ACE_packingBandage",
			"ACE_packingBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_quikclot",
			"ACE_quikclot",
			"ACE_morphine",
			"ACE_tourniquet",
			"ACE_tourniquet"
		};
	};

	class 1970_British_Spotter: 1970_British_sniper
	{
		displayName="Team Leader @Sharpshooter Team";
		backpack="TWC_Backpack_1970_Sectionlead";
	};
	
	class 1970_British_Vehicle_Commander: 1970_British_Base
	{
		displayName="Vehicle Commander @Armour Crew";
		backpack="TWC_Backpack_1990_armourcrew_webbing";
		scope=2;
		linkedItems[]=
		{
			"CUP_V_B_Interceptor_Base_Olive",
			"CUP_H_CVC",
			
			"ItemCompass",
			"ItemWatch"
		};
		respawnLinkedItems[]=
		{
			"CUP_V_B_Interceptor_Base_Olive",
			"CUP_H_CVC",
			
			"ItemCompass",
			"ItemWatch"
		};
		weapons[]=
		{
			"UK3CB_BAF_L9A1",
			"Throw",
			"Binocular",
			"Put"
		};
		respawnweapons[]=
		{
			"UK3CB_BAF_L9A1",
			"Throw",
			"Binocular",
			"Put"
		};
		magazines[]=
		{
			"UK3CB_BAF_9_13Rnd",
			"UK3CB_BAF_9_13Rnd",
			"UK3CB_BAF_9_13Rnd",
			"SmokeShell"
		};
		Respawnmagazines[]=
		{
			"UK3CB_BAF_9_13Rnd",
			"UK3CB_BAF_9_13Rnd",
			"UK3CB_BAF_9_13Rnd",
			"SmokeShell"
		};
	};
    class 1970_British_Vehicle_Crew: 1970_British_Vehicle_Commander
	{
		displayName="Vehicle Crew";
		backpack="";
		twc_nobackpack = 1;
		linkedItems[]=
		{
			"twc_interceptor_od",
			"CUP_H_PMC_EP_Headset",
			
			"ItemCompass",
			"ItemWatch"
		};
		respawnLinkedItems[]=
		{
			"twc_interceptor_od",
			"CUP_H_PMC_EP_Headset",
			
			"ItemCompass",
			"ItemWatch"
		};
		weapons[]=
		{
			"UK3CB_BAF_L9A1",
			"Throw",
			"Put"
		};
		respawnweapons[]=
		{
			"UK3CB_BAF_L9A1",
			"Throw",
			"Put"
		};
	};
