	class 1990_British_Base: B_Soldier_base_F
	{
		scope=1;
		displayName="Base";
		faction="twc_public_baf";
		editorSubcategory = "Men_1990W";
		vehicleClass="Men_1990W";
		icon="iconMan";
		nakedUniform="U_BasicBody";
		uniformClass="UK3CB_BAF_U_Smock_DPMW";
		linkedItems[]=
		{
			"UK3CB_BAF_V_PLCE_Webbing_DPMW",
			"UK3CB_BAF_H_Mk6_DPMW_A",
			"ItemMap",
			"ItemCompass",
			"ItemWatch"
		};
		respawnLinkedItems[]=
		{
			"UK3CB_BAF_V_PLCE_Webbing_DPMW",
			"UK3CB_BAF_H_Mk6_DPMW_A",
			"ItemMap",
			"ItemCompass",
			"ItemWatch"
		};
		Items[]=
		{
			"ACE_EarPlugs",
			"ACE_fieldDressing",
			"ACRE_PRC343",	
			"rhsusf_ANPVS_14",
			"ACE_fieldDressing",
			"ACE_fieldDressing",
			"ACE_fieldDressing",
			"ACE_packingBandage",
			"ACE_packingBandage",
			"ACE_packingBandage",
			"ACE_packingBandage",
			"ACE_packingBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_quikclot",
			"ACE_quikclot",
			"ACE_morphine",
			"ACE_epinephrine",
			"ACE_tourniquet",
			"ACE_tourniquet",
			"ACE_MapTools"
		};
		respawnitems[]=
		{
			"ACE_EarPlugs",
			"ACE_fieldDressing",
			"ACRE_PRC343",	
			"rhsusf_ANPVS_14",
			"ACE_fieldDressing",
			"ACE_fieldDressing",
			"ACE_fieldDressing",
			"ACE_packingBandage",
			"ACE_packingBandage",
			"ACE_packingBandage",
			"ACE_packingBandage",
			"ACE_packingBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_quikclot",
			"ACE_quikclot",
			"ACE_morphine",
			"ACE_epinephrine",
			"ACE_tourniquet",
			"ACE_tourniquet"
		};		
	};
	class 1990_British_SectionCommander: 1990_British_Base
	{
		scope=2;
		displayName="Section Leader @British Army";
		icon="iconManLeader";
		backpack="TWC_Backpack_1990_Sectionlead";
		weapons[]=
		{
			"Throw",
			"Put",
			"Binocular",
			"UK3CB_BAF_L85A1_SUSAT3D_Lazer",
			"ukcw_hipower"
		};
		respawnweapons[]=
		{
			"Throw",
			"Put",
			"Binocular",
			"UK3CB_BAF_L85A1_SUSAT3D_Lazer",
			"ukcw_hipower"
		};
		magazines[]=
		{
			"UK3CB_BAF_556_30Rnd",
			"ukcw_13rd_9x19",
			"ukcw_13rd_9x19",
			"UK3CB_BAF_556_30Rnd",
			"UK3CB_BAF_556_30Rnd",
			"UK3CB_BAF_556_30Rnd",
			"UK3CB_BAF_556_30Rnd",
			"UK3CB_BAF_556_30Rnd_T",
			"UK3CB_BAF_556_30Rnd_T",
			"UK3CB_BAF_556_30Rnd_T",
			"CUP_HandGrenade_L109A2_HE",
			"CUP_HandGrenade_L109A2_HE",
			"SmokeShell",
			"SmokeShell"
		};
		Respawnmagazines[]=
		{
			"UK3CB_BAF_556_30Rnd",
			"ukcw_13rd_9x19",
			"ukcw_13rd_9x19",
			"UK3CB_BAF_556_30Rnd",
			"UK3CB_BAF_556_30Rnd",
			"UK3CB_BAF_556_30Rnd",
			"UK3CB_BAF_556_30Rnd",
			"UK3CB_BAF_556_30Rnd_T",
			"UK3CB_BAF_556_30Rnd_T",
			"UK3CB_BAF_556_30Rnd_T",
			"CUP_HandGrenade_L109A2_HE",
			"CUP_HandGrenade_L109A2_HE",
			"SmokeShell",
			"SmokeShell"
		};
	};
	class 1990_British_Rifleman: 1990_British_Base
	{
		scope=2;
		displayName="Rifleman(90`s Woodland)";
		backpack="TWC_Backpack_1990_Rifleman";
		weapons[]=
		{
			"Throw",
			"Put",	
			"UK3CB_BAF_L85A1_SUSAT3D"
		};
		respawnweapons[]=
		{
			"Throw",
			"Put",	
			"UK3CB_BAF_L85A1_SUSAT3D"
		};
		magazines[]=
		{
			"UK3CB_BAF_556_30Rnd",
			"UK3CB_BAF_556_30Rnd",
			"UK3CB_BAF_556_30Rnd",
			"UK3CB_BAF_556_30Rnd",
			"UK3CB_BAF_556_30Rnd",
			"UK3CB_BAF_556_30Rnd_T",
			"UK3CB_BAF_556_30Rnd_T",
			"UK3CB_BAF_556_30Rnd_T",
			"CUP_HandGrenade_L109A2_HE",
			"CUP_HandGrenade_L109A2_HE",
			"SmokeShell"
		};
		Respawnmagazines[]=
		{
			"UK3CB_BAF_556_30Rnd",
			"UK3CB_BAF_556_30Rnd",
			"UK3CB_BAF_556_30Rnd",
			"UK3CB_BAF_556_30Rnd",
			"UK3CB_BAF_556_30Rnd",
			"UK3CB_BAF_556_30Rnd_T",
			"UK3CB_BAF_556_30Rnd_T",
			"UK3CB_BAF_556_30Rnd_T",
			"CUP_HandGrenade_L109A2_HE",
			"CUP_HandGrenade_L109A2_HE",
			"SmokeShell"
		};	
	};
	class 1990_British_Rifleman_AT: 1990_British_Base
	{
		scope=2;
		displayName="Rifleman AT";
		backpack="";
		weapons[]=
		{
			"Throw",
			"Put",	
			"UK3CB_BAF_L85A1_SUSAT3D",
			"rhs_weap_m72a7"
		};
		respawnweapons[]=
		{
			"Throw",
			"Put",	
			"UK3CB_BAF_L85A1_SUSAT3D"
		};
		magazines[]=
		{
			"UK3CB_BAF_556_30Rnd",
			"UK3CB_BAF_556_30Rnd",
			"UK3CB_BAF_556_30Rnd",
			"UK3CB_BAF_556_30Rnd",
			"UK3CB_BAF_556_30Rnd",
			"UK3CB_BAF_556_30Rnd_T",
			"UK3CB_BAF_556_30Rnd_T",
			"UK3CB_BAF_556_30Rnd_T",
			"CUP_HandGrenade_L109A2_HE",
			"SmokeShell"
		};
		Respawnmagazines[]=
		{
			"UK3CB_BAF_556_30Rnd",
			"UK3CB_BAF_556_30Rnd",
			"UK3CB_BAF_556_30Rnd",
			"UK3CB_BAF_556_30Rnd",
			"UK3CB_BAF_556_30Rnd",
			"UK3CB_BAF_556_30Rnd_T",
			"UK3CB_BAF_556_30Rnd_T",
			"UK3CB_BAF_556_30Rnd_T",
			"CUP_HandGrenade_L109A2_HE",
			"SmokeShell"
		};	
	};
	class 1990_British_Gunner: 1990_British_Base
	{
		scope=2;
		displayName="Gunner";
		icon="iconManMG";
		backpack="TWC_Backpack_1990_Gunner";
		weapons[]=
		{
			"Throw",
			"Put",	
			"UK3CB_BAF_L86A1_SUSAT3D"
		};
		respawnweapons[]=
		{
			"Throw",
			"Put",	
			"UK3CB_BAF_L86A1_SUSAT3D"
		};
		magazines[]=
		{
			"UK3CB_BAF_556_30Rnd",
			"UK3CB_BAF_556_30Rnd",
			"UK3CB_BAF_556_30Rnd",
			"UK3CB_BAF_556_30Rnd",
			"UK3CB_BAF_556_30Rnd",
			"UK3CB_BAF_556_30Rnd",
			"UK3CB_BAF_556_30Rnd",
			"UK3CB_BAF_556_30Rnd_T",
			"UK3CB_BAF_556_30Rnd_T",
			"UK3CB_BAF_556_30Rnd_T",
			"UK3CB_BAF_556_30Rnd_T",
			"UK3CB_BAF_556_30Rnd_T",
			"CUP_HandGrenade_L109A2_HE",
			"SmokeShell"
		};
		Respawnmagazines[]=
		{
			"UK3CB_BAF_556_30Rnd",
			"UK3CB_BAF_556_30Rnd",
			"UK3CB_BAF_556_30Rnd",
			"UK3CB_BAF_556_30Rnd",
			"UK3CB_BAF_556_30Rnd",
			"UK3CB_BAF_556_30Rnd",
			"UK3CB_BAF_556_30Rnd",
			"UK3CB_BAF_556_30Rnd_T",
			"UK3CB_BAF_556_30Rnd_T",
			"UK3CB_BAF_556_30Rnd_T",
			"UK3CB_BAF_556_30Rnd_T",
			"UK3CB_BAF_556_30Rnd_T",
			"CUP_HandGrenade_L109A2_HE",
			"SmokeShell"
		};
	};
	class 1990_British_2IC: 1990_British_Rifleman
	{
		displayName="2IC";
		backpack="TWC_Backpack_1990_2IC";
	};
	
			class 1990_British_MachineGunner: 1990_British_Gunner
	{
		displayName="GPMG Gunner";
		backpack="TWC_Backpack_1990_machineGunner";
				weapons[]=
		{
		"Throw",
		"Put",
		"UK3CB_BAF_L7A2"
		};
		respawnweapons[]=
		{
		"Throw",
		"Put",
		"UK3CB_BAF_L7A2"
		};
				magazines[]=
		{
		"UK3CB_BAF_762_200Rnd",
		"UK3CB_BAF_762_200Rnd",
		"SmokeShell"
		};
		Respawnmagazines[]=
		{
		"UK3CB_BAF_762_200Rnd",
		"UK3CB_BAF_762_200Rnd",
		"SmokeShell"
		};
	};
	
		class 1990_British_mg_assistant: 1990_British_Rifleman
	{
		displayName="GPMG Assistant";
		backpack="TWC_Backpack_1990_machineGunner";
	};
	

	
	class 1990_British_Platoon_Commander: 1990_British_Base
	{
		scope=2;
		displayName="Platoon Commander";
		backpack="TWC_Backpack_1990_Platoon_Command";
		weapons[]=
		{
			"Throw",
			"Put",
			"Binocular",
			"UK3CB_BAF_L85A1_SUSAT3D"
		};
		respawnweapons[]=
		{
			"Throw",
			"Put",
			"Binocular",
			"UK3CB_BAF_L85A1_SUSAT3D"
		};
		magazines[]=
		{
			"UK3CB_BAF_556_30Rnd",
			"UK3CB_BAF_556_30Rnd",
			"UK3CB_BAF_556_30Rnd_T",
			"UK3CB_BAF_556_30Rnd_T",
			"CUP_HandGrenade_L109A2_HE",
			"CUP_HandGrenade_L109A2_HE"
		};
		Respawnmagazines[]=
		{
			"UK3CB_BAF_556_30Rnd",
			"UK3CB_BAF_556_30Rnd",
			"UK3CB_BAF_556_30Rnd_T",
			"UK3CB_BAF_556_30Rnd_T",
			"CUP_HandGrenade_L109A2_HE",
			"CUP_HandGrenade_L109A2_HE"
		};
	};
	class 1990_British_Platoon_Sergeant: 1990_British_Platoon_Commander
	{
		displayName="Platoon Sergeant";
		backpack="TWC_Backpack_1990_Platoon_Sergeant";
	};
	class 1990_British_Platoon_CSM: 1990_British_Platoon_Commander
	{
		displayName="Company Sergeant Major";
	};
	class 1990_British_Medic: 1990_British_Base
	{
		scope=2;
		displayName="Medic";
		backpack="TWC_Backpack_1990_Medic";
		attendant = 1;
		weapons[]=
		{
			"Throw",
			"Put",
			"ukcw_hipower"
		};
		respawnweapons[]=
		{
			"Throw",
			"Put",
			"ukcw_hipower"
		};
		magazines[]=
		{
			"SmokeShell",
			"ukcw_13rd_9x19",
			"ukcw_13rd_9x19",
			"ukcw_13rd_9x19",
			"ukcw_13rd_9x19",
			"SmokeShell",
			"SmokeShell",
			"SmokeShell",
			"SmokeShell"
		};
		Respawnmagazines[]=
		{
			"SmokeShell",
			"ukcw_13rd_9x19",
			"ukcw_13rd_9x19",
			"ukcw_13rd_9x19",
			"ukcw_13rd_9x19",
			"SmokeShell",
			"SmokeShell",
			"SmokeShell",
			"SmokeShell"
		};
		class EventHandlers: EventHandlers
		{
			init = "init = if(local (_this select 0))then{(_this select 0) setVariable [""ace_medical_medicClass"",1]};";
		};
	};
	class 1990_British_HeliPilot: 1990_British_Base
	{
		scope=2;
		displayName="Helicopter Pilot";
		backpack="TWC_Backpack_USMC_vehiclecommander";
		linkedItems[]=
		{
			"UK3CB_BAF_H_PilotHelmetHeli_A",
			"UK3CB_BAF_V_Pilot_DPMT",
			"ItemMap",
			"ItemCompass",
			"ItemWatch"
		};
		respawnLinkedItems[]=
		{
			"UK3CB_BAF_H_PilotHelmetHeli_A",
			"UK3CB_BAF_V_Pilot_DPMT",
			"ItemMap",		
			"ItemCompass",
			"ItemWatch"
		};
		weapons[]=
		{
			"Throw",
			"Put",
			"ukcw_hipower"
		};
		respawnweapons[]=
		{
			"Throw",
			"Put",
			"ukcw_hipower"
		};
		magazines[]=
		{
			"SmokeShell",
			"ukcw_13rd_9x19",
			"ukcw_13rd_9x19",
			"SmokeShell"
		};
		Respawnmagazines[]=
		{
			"SmokeShell",
			"ukcw_13rd_9x19",
			"ukcw_13rd_9x19",
			"SmokeShell"

		};
	};
	class 1990_British_JetPilot: 1990_British_HeliPilot
	{
		displayName="Jet Pilot";
		uniformClass="UK3CB_BAF_U_HeliPilotCoveralls_RAF";
		backpack="B_AssaultPack_blk";
		linkedItems[]=
		{
			"UK3CB_BAF_H_PilotHelmetHeli_A",
			"CUP_V_B_PilotVest",
			"ItemMap",
			"ItemCompass",
			"ItemWatch"
		};
		respawnLinkedItems[]=
		{
			"UK3CB_BAF_H_PilotHelmetHeli_A",
			"CUP_V_B_PilotVest",
			"ItemMap",
			"ItemCompass",
			"ItemWatch"
		};	
		weapons[]=
		{
			"Throw",
			"Put",
			"ukcw_hipower"
		};
		respawnweapons[]=
		{
			"Throw",
			"Put",
			"ukcw_hipower"
		};
		magazines[]=
		{
			"SmokeShell",
			"ukcw_13rd_9x19",
			"ukcw_13rd_9x19",
			"SmokeShell"
		};
		Respawnmagazines[]=
		{
			"SmokeShell",
			"ukcw_13rd_9x19",
			"ukcw_13rd_9x19",
			"SmokeShell"
		};
	};
		class 1990_British_FSTCommander: 1990_British_Base 
	{
		scope=2;
		displayName="FST Commander (90's Woodland)@Fire Support Team";
		icon="iconManLeader";
		uniformClass="UK3CB_BAF_U_Smock_DPMW";
		backpack="TWC_Backpack_1990_Sectionlead";
		linkedItems[]=
		{
			"UK3CB_BAF_V_PLCE_Webbing_DPMW",
			"UK3CB_BAF_H_Mk6_DPMW_C",
			"ItemMap",
			"ItemCompass",
			"ItemWatch"
		};
		respawnLinkedItems[]=
		{
			"UK3CB_BAF_V_PLCE_Webbing_DPMW",
			"UK3CB_BAF_H_Mk6_DPMW_C",
			"ItemMap",
			"ItemCompass",
			"ItemWatch"
		};
		weapons[]=
		{
			"Throw",
			"Put",
			"Binocular",
			"UK3CB_BAF_L85A1_SUSAT3D",
			"ukcw_hipower"
		};
		respawnweapons[]=
		{
			"Throw",
			"Put",
			"Binocular",
			"UK3CB_BAF_L85A1_SUSAT3D",
			"ukcw_hipower"
		};
		magazines[]=
		{
			"UK3CB_BAF_556_30Rnd",
			"ukcw_13rd_9x19",
			"ukcw_13rd_9x19",
			"UK3CB_BAF_556_30Rnd",
			"UK3CB_BAF_556_30Rnd",
			"UK3CB_BAF_556_30Rnd",
			"UK3CB_BAF_556_30Rnd_T",
			"UK3CB_BAF_556_30Rnd_T",
			"CUP_HandGrenade_L109A2_HE",
			"CUP_HandGrenade_L109A2_HE",
			"SmokeShell",
			"SmokeShell",
			"SmokeShell"
		};
		Respawnmagazines[]=
		{
			"UK3CB_BAF_556_30Rnd",
			"ukcw_13rd_9x19",
			"ukcw_13rd_9x19",
			"UK3CB_BAF_556_30Rnd",
			"UK3CB_BAF_556_30Rnd",
			"UK3CB_BAF_556_30Rnd",
			"UK3CB_BAF_556_30Rnd_T",
			"UK3CB_BAF_556_30Rnd_T",
			"CUP_HandGrenade_L109A2_HE",
			"CUP_HandGrenade_L109A2_HE",
			"SmokeShell",
			"SmokeShell",
			"SmokeShell",
			"B_IR_Grenade"
		};
	};

	class 1990_British_FSTForwardObserver: 1990_British_Base
	{
		scope=2;
		displayName="FST Forward Observer (90's Woodland)";
		icon="iconManExplosive";
		uniformClass="UK3CB_BAF_U_Smock_DPMW";
		backpack="UK3CB_BAF_B_Bergen_DPMW_Rifleman_B";
		linkedItems[]=
		{
			"UK3CB_BAF_V_PLCE_Webbing_DPMW",
			"UK3CB_BAF_H_Mk6_DPMW_C",
			"ItemMap",
			"ItemCompass",
			"ItemWatch"
		};
		respawnLinkedItems[]=
		{
			"UK3CB_BAF_V_PLCE_Webbing_DPMW",
			"UK3CB_BAF_H_Mk6_DPMW_C",
			"ItemMap",
			"ItemCompass",
			"ItemWatch"
		};
		weapons[]=
		{
			"Throw",
			"Put",
			"CUP_SOFLAM",
			"UK3CB_BAF_L85A1_SUSAT3D"
		};
		respawnweapons[]=
		{
			"Throw",
			"Put",
			"CUP_SOFLAM",
			"UK3CB_BAF_L85A1_SUSAT3D"
		};
		magazines[]=
		{
			"UK3CB_BAF_556_30Rnd_T",
			"UK3CB_BAF_556_30Rnd_T",
			"UK3CB_BAF_556_30Rnd_T",
			"UK3CB_BAF_556_30Rnd",
			"UK3CB_BAF_556_30Rnd",
			"UK3CB_BAF_556_30Rnd",
			"UK3CB_BAF_556_30Rnd",
			"UK3CB_BAF_556_30Rnd",
			"CUP_HandGrenade_L109A2_HE",
			"CUP_HandGrenade_L109A2_HE",
			"SmokeShell",
			"SmokeShell",
			"Laserbatteries"
		};
		Respawnmagazines[]=
		{
			"UK3CB_BAF_556_30Rnd",
			"UK3CB_BAF_556_30Rnd",
			"UK3CB_BAF_556_30Rnd",
			"UK3CB_BAF_556_30Rnd",
			"UK3CB_BAF_556_30Rnd_T",
			"UK3CB_BAF_556_30Rnd_T",
			"CUP_HandGrenade_L109A2_HE",
			"CUP_HandGrenade_L109A2_HE",
			"SmokeShell",
			"SmokeShell",
			"Laserbatteries"
		};
	};

	class 1990_British_FSTAssistant: 1990_British_Base 
	{
		scope=2;
		displayName="FST Assistant (90's Woodland)";
		uniformClass="UK3CB_BAF_U_Smock_DPMW";
		backpack="UK3CB_BAF_B_Carryall_DPMW";
		
		linkedItems[]=
		{
			"UK3CB_BAF_V_PLCE_Webbing_DPMW",
			"UK3CB_BAF_H_Mk6_DPMW_C",
			"ItemMap",
			"ItemCompass",
			"ItemWatch"
		};
		respawnLinkedItems[]=
		{
			"UK3CB_BAF_V_PLCE_Webbing_DPMW",
			"UK3CB_BAF_H_Mk6_DPMW_C",
			"ItemMap",
			"ItemCompass",
			"ItemWatch"
		};
		weapons[]=
		{
			"Throw",
			"Put",
			"UK3CB_BAF_L85A1_SUSAT3D"
		};
		respawnweapons[]=
		{
			"Throw",
			"Put",	
			"UK3CB_BAF_L85A1_SUSAT3D"
		};
		magazines[]=
		{
			"UK3CB_BAF_556_30Rnd_T",
			"UK3CB_BAF_556_30Rnd_T",
			"UK3CB_BAF_556_30Rnd_T",
			"UK3CB_BAF_556_30Rnd",
			"UK3CB_BAF_556_30Rnd",
			"UK3CB_BAF_556_30Rnd",
			"UK3CB_BAF_556_30Rnd",
			"UK3CB_BAF_556_30Rnd",
			"CUP_HandGrenade_L109A2_HE",
			"CUP_HandGrenade_L109A2_HE",
			"SmokeShell",
			"SmokeShell"
		};
		Respawnmagazines[]=
		{
			"UK3CB_BAF_556_30Rnd_T",
			"UK3CB_BAF_556_30Rnd_T",
			"UK3CB_BAF_556_30Rnd_T",
			"UK3CB_BAF_556_30Rnd",
			"UK3CB_BAF_556_30Rnd",
			"UK3CB_BAF_556_30Rnd",
			"UK3CB_BAF_556_30Rnd",
			"UK3CB_BAF_556_30Rnd",
			"CUP_HandGrenade_L109A2_HE",
			"CUP_HandGrenade_L109A2_HE",
			"SmokeShell",
			"SmokeShell"
		};
	};
		
//////////////////////////////  Mounted  //////////////////////////////
	class 1990_British_Vehicle_Commander: 1990_British_Base
	{
		displayName="Vehicle Commander";
		uniformClass="UK3CB_BAF_U_CombatUniform_DPMT";
		backpack="B_AssaultPack_blk";
		linkedItems[]=
		{
			"UK3CB_BAF_V_Pilot_DPMT",
			"UK3CB_BAF_H_CrewHelmet_DPMT",
			"ItemMap",
			"ItemCompass",
			"ItemWatch"
		};
		respawnLinkedItems[]=
		{
			"UK3CB_BAF_V_Pilot_DPMT",
			"UK3CB_BAF_H_CrewHelmet_DPMT",
			"ItemMap",
			"ItemCompass",
			"ItemWatch"
		};
		weapons[]=
		{
			"Throw",
			"Put"
		};
		respawnweapons[]=
		{
			"Throw",
			"Put"
		};
		magazines[]=
		{
			"SmokeShell",
			"SmokeShell"
		};
		Respawnmagazines[]=
		{
			"SmokeShell",
			"SmokeShell"
		};
	};
    class 1990_British_Vehicle_Crew: 1990_British_Vehicle_Commander
	{
		displayName="Vehicle Crew";
		backpack="";
	};
//////////////////////////////////////////////////////////////////
//                                                              //
//                    1990 Desert British                       //
//                                                              //
//////////////////////////////////////////////////////////////////

	class 1990_British_SectionCommander_Desert: 1990_British_SectionCommander
	{
		displayName="Section Leader @British Army";
		editorSubcategory = "Men_1990D";
		vehicleClass="Men_1990D";
		uniformClass="TWC_Smock_Desert";
		backpack="TWC_Backpack_1990_Sectionlead_Desert";
		linkedItems[]=
		{
			"UK3CB_BAF_V_PLCE_Webbing_DDPM",
			"UK3CB_BAF_H_Mk6_DDPM_A",
			"ItemMap",
			"ItemCompass",
			"ItemWatch"
		};
		respawnLinkedItems[]=
		{
			"UK3CB_BAF_V_PLCE_Webbing_DDPM",
			"ItemMap",
			"ItemCompass",
			"ItemWatch"
		};
				weapons[]=
		{
			"Throw",
			"Put",
			"Binocular",
			"UK3CB_BAF_L85A1_SUSAT3D",
			"ukcw_hipower"
		};
		respawnweapons[]=
		{
			"Throw",
			"Put",
			"Binocular",
			"UK3CB_BAF_L85A1_SUSAT3D",
			"ukcw_hipower"
		};
		magazines[]=
		{
			"UK3CB_BAF_556_30Rnd_T",
			"UK3CB_BAF_556_30Rnd_T",
			"ukcw_13rd_9x19",
			"ukcw_13rd_9x19",
			"ukcw_13rd_9x19",
			"UK3CB_BAF_556_30Rnd_T",
			"UK3CB_BAF_556_30Rnd",
			"UK3CB_BAF_556_30Rnd",
			"UK3CB_BAF_556_30Rnd",
			"UK3CB_BAF_556_30Rnd",
			"UK3CB_BAF_556_30Rnd",
			"CUP_HandGrenade_L109A2_HE",
			"CUP_HandGrenade_L109A2_HE",
			"SmokeShell",
			"SmokeShell"
		};
		Respawnmagazines[]=
		{
			"UK3CB_BAF_556_30Rnd_T",
			"UK3CB_BAF_556_30Rnd_T",
			"ukcw_13rd_9x19",
			"ukcw_13rd_9x19",
			"ukcw_13rd_9x19",
			"UK3CB_BAF_556_30Rnd_T",
			"UK3CB_BAF_556_30Rnd",
			"UK3CB_BAF_556_30Rnd",
			"UK3CB_BAF_556_30Rnd",
			"UK3CB_BAF_556_30Rnd",
			"UK3CB_BAF_556_30Rnd",
			"CUP_HandGrenade_L109A2_HE",
			"CUP_HandGrenade_L109A2_HE",
			"SmokeShell",
			"SmokeShell"
		};		
	};
	class 1990_British_Rifleman_Desert: 1990_British_Rifleman
	{
		displayName="Rifleman";
		editorSubcategory = "Men_1990D";
		vehicleClass="Men_1990D";
		uniformClass="TWC_Smock_Desert";
		backpack="";
		linkedItems[]=
		{
			"UK3CB_BAF_V_PLCE_Webbing_DDPM",
			"UK3CB_BAF_H_Mk6_DDPM_A",
			"ItemMap",
			"ItemCompass",
			"ItemWatch"
		};
		respawnLinkedItems[]=
		{
			"UK3CB_BAF_V_PLCE_Webbing_DDPM",
			"UK3CB_BAF_H_Mk6_DDPM_A",
			"ItemMap",
			"ItemCompass",
			"ItemWatch"
		};
	};
	class 1990_British_Rifleman_AT_Desert: 1990_British_Rifleman
	{
		displayName="Rifleman AT";
		editorSubcategory = "Men_1990D";
		vehicleClass="Men_1990D";
		uniformClass="TWC_Smock_Desert";
		backpack="";
						weapons[]=
		{
		"Throw",
		"UK3CB_BAF_L85A1_SUSAT3D_Lazer",
		"rhs_weap_m72a7",
		"Put"
		};
				respawnweapons[]=
		{
		"Throw",
		"UK3CB_BAF_L85A1_SUSAT3D_Lazer",
		"rhs_weap_m72a7",
		"Put"
		};
		linkedItems[]=
		{
			"UK3CB_BAF_V_PLCE_Webbing_DDPM",
			"UK3CB_BAF_H_Mk6_DDPM_A",
			"ItemMap",
			"ItemCompass",
			"ItemWatch"
		};
		respawnLinkedItems[]=
		{
			"UK3CB_BAF_V_PLCE_Webbing_DDPM",
			"UK3CB_BAF_H_Mk6_DDPM_A",
			"ItemMap",
			"ItemCompass",
			"ItemWatch"
		};
	};
	class 1990_British_Gunner_Desert: 1990_British_Gunner
	{
		displayName="Gunner";
		editorSubcategory = "Men_1990D";
		vehicleClass="Men_1990D";
		uniformClass="TWC_Smock_Desert";
		backpack="TWC_Backpack_1990_Gunner_Desert";
		linkedItems[]=
		{
			"UK3CB_BAF_V_PLCE_Webbing_DDPM",
			"UK3CB_BAF_H_Mk6_DDPM_A",
			"ItemMap",
			"ItemCompass",
			"ItemWatch"
		};
		respawnLinkedItems[]=
		{
			"UK3CB_BAF_V_PLCE_Webbing_DDPM",
			"ItemMap",
			"ItemCompass",
			"ItemWatch"
		};
	};
	class 1990_British_2IC_Desert: 1990_British_2IC
	{
		displayName="2IC";
		editorSubcategory = "Men_1990D";
		vehicleClass="Men_1990D";
		uniformClass="TWC_Smock_Desert";
		backpack="TWC_Backpack_1990_2IC_Desert";
		linkedItems[]=
		{
			"UK3CB_BAF_V_PLCE_Webbing_DDPM",
			"UK3CB_BAF_H_Mk6_DDPM_A",
			"ItemMap",
			"ItemCompass",
			"ItemWatch"
		};
		respawnLinkedItems[]=
		{
			"UK3CB_BAF_V_PLCE_Webbing_DDPM",
			"UK3CB_BAF_H_Mk6_DDPM_A",
			"ItemMap",
			"ItemCompass",
			"ItemWatch"
		};
	};
	class 1990_British_Platoon_Commander_Desert: 1990_British_Platoon_Commander
	{
		displayName="Platoon Commander";
		editorSubcategory = "Men_1990D";
		vehicleClass="Men_1990D";
		uniformClass="TWC_Smock_Desert";
		backpack="TWC_Backpack_1990_Platoon_Command_Desert";
		linkedItems[]=
		{
			"UK3CB_BAF_V_PLCE_Webbing_DDPM",
			"UK3CB_BAF_H_Mk6_DDPM_A",
			"ItemMap",
			"ItemCompass",
			"ItemWatch"
		};
		respawnLinkedItems[]=
		{
			"UK3CB_BAF_V_PLCE_Webbing_DDPM",
			"UK3CB_BAF_H_Mk6_DDPM_A",
			"ItemMap",
			"ItemCompass",
			"ItemWatch"
		};
	};
	class 1990_British_Platoon_Sergeant_Desert: 1990_British_Platoon_Sergeant
	{
		scope=2;
		displayName="Platoon Sergeant";
		editorSubcategory = "Men_1990D";
		vehicleClass="Men_1990D";
		uniformClass="TWC_Smock_Desert";
		backpack="TWC_Backpack_1990_Platoon_Sergeant_Desert";
		linkedItems[]=
		{
			"UK3CB_BAF_V_PLCE_Webbing_DDPM",
			"UK3CB_BAF_H_Mk6_DDPM_A",
			"ItemMap",
			"ItemCompass",
			"ItemWatch"
		};
		respawnLinkedItems[]=
		{
			"UK3CB_BAF_V_PLCE_Webbing_DDPM",
			"UK3CB_BAF_H_Mk6_DDPM_A",
			"ItemMap",
			"ItemCompass",
			"ItemWatch"
		};
	};
	class 1990_British_Platoon_CSM_Desert: 1990_British_Platoon_Commander_Desert
	{
		displayName="Company Sergeant Major( 90`s Desert)";
	};
	class 1990_British_Medic_Desert: 1990_British_Medic
	{
		displayName="Medic";
		editorSubcategory = "Men_1990D";
		vehicleClass="Men_1990D";
		uniformClass="TWC_Smock_Desert";
		attendant = 1;
		backpack="TWC_Backpack_1990_Medic_Desert";
				weapons[]=
		{
		"Throw",
		"UK3CB_BAF_L85A2",
		"Put"
		};
				respawnweapons[]=
		{
		"Throw",
		"UK3CB_BAF_L85A2",
		"Put"
		};
		linkedItems[]=
		{
			"UK3CB_BAF_V_PLCE_Webbing_DDPM",
			"UK3CB_BAF_H_Mk6_DDPM_A",
			"ItemMap",
			"ItemCompass",
			"ItemWatch"
		};
		respawnLinkedItems[]=
		{
			"UK3CB_BAF_V_PLCE_Webbing_DDPM",
			"UK3CB_BAF_H_Mk6_DDPM_A",
			"ItemMap",
			"ItemCompass",
			"ItemWatch"
		};
				magazines[]=
		{
			"UK3CB_BAF_556_30Rnd",
			"UK3CB_BAF_556_30Rnd",
			"UK3CB_BAF_556_30Rnd_T",
			"SmokeShell",
			"SmokeShell"
		};
		Respawnmagazines[]=
		{
			"UK3CB_BAF_556_30Rnd",
			"UK3CB_BAF_556_30Rnd",
			"UK3CB_BAF_556_30Rnd_T",
			"SmokeShell",
			"SmokeShell"
		};
		class EventHandlers: EventHandlers
		{
			init = "init = if(local (_this select 0))then{(_this select 0) setVariable [""ace_medical_medicClass"",1]};";
		};
	};
    class 1990_British_HeliPilot_Desert: 1990_British_HeliPilot
	{
		displayName="Helicopter Pilot";
		editorSubcategory = "Men_1990D";
		vehicleClass="Men_1990D";
		uniformClass="TWC_Smock_Desert";
		linkedItems[]=
		{
			"UK3CB_BAF_H_PilotHelmetHeli_A",
			"UK3CB_BAF_V_Pilot_DDPM",
			"ItemMap",
			"ItemCompass",
			"ItemWatch"
		};
		respawnLinkedItems[]=
		{
			"UK3CB_BAF_H_PilotHelmetHeli_A",
			"UK3CB_BAF_V_Pilot_DDPM",
			"ItemMap",		
			"ItemCompass",
			"ItemWatch"
		};
	};
	
	class 1990_British_FSTCommander_Desert: 1990_British_FSTCommander
	{
		scope=2;
		displayName="FST Commander (90's Desert)@Fire Support Team";
		icon="iconManLeader";
		editorSubcategory = "Men_1990D";
		vehicleClass= "Men_1990D";
		uniformClass="UK3CB_BAF_U_Smock_DDPM";
		backpack="TWC_Backpack_1990_Sectionlead_Desert";
		linkedItems[]=
		{
			"UK3CB_BAF_V_PLCE_Webbing_DDPM",
			"UK3CB_BAF_H_Mk6_DDPM_C",
			"ItemMap",
			"ItemCompass",
			"ItemWatch"
		};
		respawnLinkedItems[]=
		{
			"UK3CB_BAF_V_PLCE_Webbing_DDPM",
			"UK3CB_BAF_H_Mk6_DDPM_C",
			"ItemMap",
			"ItemCompass",
			"ItemWatch"
		};
	};	
	class 1990_British_FSTForwardObserver_Desert: 1990_British_FSTForwardObserver
	{
		scope=2;
		displayName="FST Forward Observer (90's Desert)";
		editorSubcategory = "Men_1990D";
		vehicleClass="Men_1990D";
		uniformClass="UK3CB_BAF_U_Smock_DDPM";
		backpack="UK3CB_BAF_B_Bergen_DDPM_Rifleman_B";
		linkedItems[]=
		{
			"UK3CB_BAF_V_PLCE_Webbing_DDPM",
			"UK3CB_BAF_H_Mk6_DDPM_C",
			"ItemMap",
			"ItemCompass",
			"ItemWatch"
		};
		respawnLinkedItems[]=
		{
			"UK3CB_BAF_V_PLCE_Webbing_DDPM",
			"UK3CB_BAF_H_Mk6_DDPM_C",
			"ItemMap",
			"ItemCompass",
			"ItemWatch"
		};
	};
	class 1990_British_FSTAssistant_Desert: 1990_British_FSTAssistant
	{
		scope=2;
		displayName="FST Assistant (90's Desert)";
		editorSubcategory = "Men_1990D";
		vehicleClass="Men_1990D";
		uniformClass="UK3CB_BAF_U_Smock_DDPM";
		backpack="UK3CB_BAF_B_Carryall_DDPM";
		linkedItems[]=
		{
			"UK3CB_BAF_V_PLCE_Webbing_DDPM",
			"UK3CB_BAF_H_Mk6_DDPM_C",
			"ItemMap",
			"ItemCompass",
			"ItemWatch"
		};
		respawnLinkedItems[]=
		{
			"UK3CB_BAF_V_PLCE_Webbing_DPMW",
			"UK3CB_BAF_H_Mk6_DPMW_C",
			"ItemMap",
			"ItemCompass",
			"ItemWatch"
		};
	};
//////////////////////////////  Royal Marines  //////////////////////////////

	class 1990_RM_base: 1990_British_SectionCommander_Desert
	{
		displayName="Section Leader";
		scope = 1;
		editorSubcategory = "Men_1990RM";
		vehicleClass="Men_1990RM";
		uniformClass="UK3CB_BAF_U_Smock_DPMW_DDPM";
		linkedItems[]=
		{
			"UK3CB_BAF_V_PLCE_Webbing_DPMW",
			"UK3CB_BAF_H_Mk6_DPMW_A",
			"ItemMap",
			"ItemCompass",
			"ItemWatch"
		};
		respawnLinkedItems[]=
		{
			"UK3CB_BAF_V_PLCE_Webbing_DPMW",
			"UK3CB_BAF_H_Mk6_DPMW_A",
			"ItemMap",
			"ItemCompass",
			"ItemWatch"
		};
				magazines[]=
		{
		"UK3CB_BAF_556_30Rnd_T",
		"UK3CB_BAF_556_30Rnd_T",
		"UK3CB_BAF_556_30Rnd_T",
		"UK3CB_BAF_556_30Rnd",
		"UK3CB_BAF_556_30Rnd",
		"UK3CB_BAF_556_30Rnd",
		"UK3CB_BAF_556_30Rnd",
		"UK3CB_BAF_556_30Rnd",
		"UK3CB_BAF_556_30Rnd",
		"SmokeShell",
		"CUP_HandGrenade_L109A2_HE"
		};
		Respawnmagazines[]=
		{
		"UK3CB_BAF_556_30Rnd_T",
		"UK3CB_BAF_556_30Rnd_T",
		"UK3CB_BAF_556_30Rnd_T",
		"UK3CB_BAF_556_30Rnd",
		"UK3CB_BAF_556_30Rnd",
		"UK3CB_BAF_556_30Rnd",
		"UK3CB_BAF_556_30Rnd",
		"UK3CB_BAF_556_30Rnd",
		"UK3CB_BAF_556_30Rnd",
		"SmokeShell",
		"CUP_HandGrenade_L109A2_HE"
		};
		weapons[]=
		{
			"Throw",
			"Put",
			"Binocular",
			"UK3CB_BAF_L85A1_SUSAT3D_Lazer"
		};
		respawnweapons[]=
		{
			"Throw",
			"Put",
			"Binocular",
			"UK3CB_BAF_L85A1_SUSAT3D_Lazer"
		};

	};


	class 1990_RM_British_SectionCommander_Mix: 1990_RM_base
	{
		displayName="Section Leader";
		editorSubcategory = "Men_1990RM";
		scope = 2;
		vehicleClass="Men_1990RM";
		backpack="TWC_Backpack_1990_Sectionlead";
		weapons[]=
		{
			"Throw",
			"Put",
			"Binocular",
			"UK3CB_BAF_L85A1_SUSAT3D_Lazer",
			"ukcw_hipower"
		};
		respawnweapons[]=
		{
			"Throw",
			"Put",
			"Binocular",
			"UK3CB_BAF_L85A1_SUSAT3D_Lazer",
			"ukcw_hipower"
		};
		magazines[]=
		{
			"UK3CB_BAF_556_30Rnd_T",
			"UK3CB_BAF_556_30Rnd_T",
			"ukcw_13rd_9x19",
			"ukcw_13rd_9x19",
			"ukcw_13rd_9x19",
			"UK3CB_BAF_556_30Rnd_T",
			"UK3CB_BAF_556_30Rnd",
			"UK3CB_BAF_556_30Rnd",
			"UK3CB_BAF_556_30Rnd",
			"UK3CB_BAF_556_30Rnd",
			"UK3CB_BAF_556_30Rnd",
			"CUP_HandGrenade_L109A2_HE",
			"CUP_HandGrenade_L109A2_HE",
			"SmokeShell",
			"SmokeShell"
		};
		Respawnmagazines[]=
		{
			"UK3CB_BAF_556_30Rnd_T",
			"UK3CB_BAF_556_30Rnd_T",
			"ukcw_13rd_9x19",
			"ukcw_13rd_9x19",
			"ukcw_13rd_9x19",
			"UK3CB_BAF_556_30Rnd_T",
			"UK3CB_BAF_556_30Rnd",
			"UK3CB_BAF_556_30Rnd",
			"UK3CB_BAF_556_30Rnd",
			"UK3CB_BAF_556_30Rnd",
			"UK3CB_BAF_556_30Rnd",
			"CUP_HandGrenade_L109A2_HE",
			"CUP_HandGrenade_L109A2_HE",
			"SmokeShell",
			"SmokeShell"
		};		

	};
	class 1990_RM_British_Rifleman_Mix: 1990_RM_base
	{
		displayName="Rifleman";
		editorSubcategory = "Men_1990RM";
		scope = 2;
		vehicleClass="Men_1990RM";
		backpack="";

	};
	class 1990_RM_British_Rifleman_AT_Mix: 1990_RM_base
	{
		displayName="Rifleman AT";
		editorSubcategory = "Men_1990RM";
		scope = 2;
		vehicleClass="Men_1990RM";
		backpack="";
						weapons[]=
		{
		"Throw",
		"UK3CB_BAF_L85A1_SUSAT3D_Lazer",
		"rhs_weap_m72a7",
		"Put"
		};
				respawnweapons[]=
		{
		"Throw",
		"UK3CB_BAF_L85A1_SUSAT3D_Lazer",
		"rhs_weap_m72a7",
		"Put"
		};

	};
	class 1990_RM_British_Gunner_Mix: 1990_RM_base
	{
		displayName="Gunner";
		editorSubcategory = "Men_1990RM";
		scope = 2;
		vehicleClass="Men_1990RM";
		backpack="TWC_Backpack_1990_Minimi";

		weapons[]=
		{
		"Throw",
		"Put",
		"UK3CB_BAF_L110A1"
		};
		respawnweapons[]=
		{
		"Throw",
		"Put",
		"UK3CB_BAF_L110A1"
		};
						magazines[]=
		{
		"UK3CB_BAF_556_200Rnd_T",
		"SmokeShell",
		"CUP_HandGrenade_L109A2_HE"
		};
		Respawnmagazines[]=
		{
		"UK3CB_BAF_556_200Rnd_T",
		"SmokeShell",
		"CUP_HandGrenade_L109A2_HE"
		};
	};
		class 1990_RM_British_Marksman_Mix: 1990_British_Gunner_Desert
	{
		displayName="Marksman";
		editorSubcategory = "Men_1990RM";
		vehicleClass="Men_1990RM";
		uniformClass="UK3CB_BAF_U_Smock_DPMW_DDPM";
		backpack="TWC_Backpack_1990_Gunner";
				linkedItems[]=
		{
			"UK3CB_BAF_V_PLCE_Webbing_DPMW",
			"UK3CB_BAF_H_Mk6_DPMW_A",
			"ItemMap",
			"ItemCompass",
			"ItemWatch"
		};
		respawnLinkedItems[]=
		{
			"UK3CB_BAF_V_PLCE_Webbing_DPMW",
			"UK3CB_BAF_H_Mk6_DPMW_A",
			"ItemMap",
			"ItemCompass",
			"ItemWatch"
		};

	};
	class 1990_RM_British_2IC_Mix: 1990_RM_base
	{
		displayName="2IC";
		editorSubcategory = "Men_1990RM";
		scope = 2;
		vehicleClass="Men_1990RM";
		backpack="TWC_Backpack_1990_2IC";

	};

		class 1990_RM_British_Medic_Mix: 1990_RM_base
	{
		displayName="Medic";
		editorSubcategory = "Men_1990RM";
		scope = 2;
		attendant = 1;
		vehicleClass="Men_1990RM";
		backpack="TWC_Backpack_1990_Medic";

	};

	//////////////////////////////  Mounted  //////////////////////////////
	
    class 1990_British_Vehicle_Commander_Desert: 1990_British_Vehicle_Commander
	{
		displayName="Vehicle Commander";
		editorSubcategory = "Men_1990D";
		vehicleClass="Men_1990D";
		uniformClass="TWC_Smock_Desert";
		linkedItems[]=
		{
			"UK3CB_BAF_V_PLCE_Webbing_DDPM",
			"UK3CB_BAF_H_CrewHelmet_DDPM_ESS_A",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"UK3CB_BAF_G_Tactical_Black"
		};
		respawnLinkedItems[]=
		{
			"UK3CB_BAF_V_PLCE_Webbing_DDPM",
			"UK3CB_BAF_H_CrewHelmet_DDPM_ESS_A",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"UK3CB_BAF_G_Tactical_Black"
		};
	};
    class 1990_British_Vehicle_Crew_Desert: 1990_British_Vehicle_Crew
	{
		displayName="Vehicle Crew";
		editorSubcategory = "Men_1990D";
		vehicleClass="Men_1990D";
		uniformClass="TWC_Smock_Desert";
		linkedItems[]=
		{
			"UK3CB_BAF_V_PLCE_Webbing_DDPM",
			"UK3CB_BAF_H_CrewHelmet_DDPM_A",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"UK3CB_BAF_G_Tactical_Black"
		};
		respawnLinkedItems[]=
		{
			"UK3CB_BAF_V_PLCE_Webbing_DDPM",
			"UK3CB_BAF_H_CrewHelmet_DDPM_A",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"UK3CB_BAF_G_Tactical_Black"
		};
	};
	class 1990_British_Tank_Commander_Desert: B_Soldier_base_F
	{
		_generalMacro="1990_Desert_British_Tank Commander";
		scope=2;
		displayName="Vehicle Commander";
		faction="twc_public_baf";
		editorSubcategory = "Men_1990D";
		vehicleClass="Men_1990D";
		icon="iconMan";
		nakedUniform="U_BasicBody";
		uniformClass="UK3CB_BAF_U_CombatUniform_DDPM_ShortSleeve";
		backpack="";
		linkedItems[]=
		{
        "UK3CB_BAF_V_Pilot_DDPM",
		"UK3CB_BAF_H_CrewHelmet_B",
		"ItemMap",
		"ItemCompass",
		"ItemWatch"
		};
		respawnLinkedItems[]=
		{
        "UK3CB_BAF_V_Pilot_DDPM",
		"UK3CB_BAF_H_CrewHelmet_B",
		"ItemMap",
		"ItemCompass",
		"ItemWatch"
		};
		weapons[]=
		{
		"CUP_smg_MP5A5",
		"Throw",
		"Put"
		};
		respawnweapons[]=
		{
		"CUP_smg_MP5A5",
		"Throw",
		"Put"
		};
		magazines[]=
		{
		"CUP_30Rnd_9x19_MP5",
		"CUP_30Rnd_9x19_MP5",
		"CUP_30Rnd_9x19_MP5",
		"SmokeShell",
		"SmokeShell",
		"SmokeShell"
		};
		Respawnmagazines[]=
		{
		"CUP_30Rnd_9x19_MP5",
		"CUP_30Rnd_9x19_MP5",
		"CUP_30Rnd_9x19_MP5",
		"SmokeShell",
		"SmokeShell",
		"SmokeShell"
		};
		Items[]=
		{
		"ACE_EarPlugs",
		"ACRE_PRC148",
		"rhsusf_ANPVS_14",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_morphine",
		"ACE_morphine",
		"ACE_tourniquet",
		"ACE_EarPlugs"
		};
		respawnitems[]=
		{
		"ACE_EarPlugs",
		"ACRE_PRC148",
		"rhsusf_ANPVS_14",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_morphine",
		"ACE_morphine",
		"ACE_Flashlight_KSF1",
		"ACE_IR_Strobe_Item",
	    "ACE_MapTools"
		};
	};
    class 1990_British_Tank_Crew_Desert: 1990_British_Tank_Commander_Desert
	{
		_generalMacro="1990_Desert_Tank_Crew";
		scope=2;
		displayName="Vehicle Crew";
		faction="twc_public_baf";
		editorSubcategory = "Men_1990D";
		backpack="";
		vehicleClass="Men_1990D";
		icon="iconMan";
		nakedUniform="U_BasicBody";
};
	
	    class 1990_British_Sniper_desert: B_Soldier_base_F
	{
		_generalMacro="1990_Desert_Sniper";
		scope=2;
		displayName="Sniper";
		faction="twc_public_baf";
		editorSubcategory = "Men_1990D";
		vehicleClass="Men_1990D";
		icon="iconMan";
		nakedUniform="U_BasicBody";
		uniformClass="TWC_Smock_Desert";
		linkedItems[]=
		{
        "UK3CB_BAF_V_PLCE_Webbing_DDPM",
		"UK3CB_BAF_H_Mk6_DDPM_C",
		"ItemMap",
		"ItemCompass",
		"ItemWatch"
		};
		respawnLinkedItems[]=
		{
        "UK3CB_BAF_V_PLCE_Webbing_DDPM",
		"UK3CB_BAF_H_Mk6_DDPM_C",
		"ItemMap",
		"ItemCompass",
		"ItemWatch"
		};
		weapons[]=
		{
		"Throw",
		"Put",
		"Binocular",
		"twc_l96_d",
		"ukcw_hipower"
		};
		respawnweapons[]=
		{
		"Throw",
		"Put",
		"Binocular",
		"twc_l96_d",
		"ukcw_hipower"
		};
		magazines[]=
		{
		"UK3CB_BAF_762_L42A1_10Rnd",
		"UK3CB_BAF_762_L42A1_10Rnd",
		"ukcw_13rd_9x19",
		"ukcw_13rd_9x19",
		"ukcw_13rd_9x19",
		"UK3CB_BAF_762_L42A1_10Rnd",
		"UK3CB_BAF_762_L42A1_10Rnd",
		"UK3CB_BAF_762_L42A1_10Rnd",
		"SmokeShell",
		"SmokeShell"
		};
		Respawnmagazines[]=
		{
		"UK3CB_BAF_762_L42A1_10Rnd",
		"UK3CB_BAF_762_L42A1_10Rnd",
		"ukcw_13rd_9x19",
		"ukcw_13rd_9x19",
		"ukcw_13rd_9x19",
		"UK3CB_BAF_762_L42A1_10Rnd",
		"UK3CB_BAF_762_L42A1_10Rnd",
		"UK3CB_BAF_762_L42A1_10Rnd",
		"SmokeShell",
		"SmokeShell"
		};
		Items[]=
		{
		"ACE_fieldDressing",
		"ACRE_PRC343",	
		"ACE_RangeCard",
		"rhsusf_ANPVS_14",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_morphine",
		"ACE_morphine",
		"ACE_EarPlugs"	
		};
		respawnitems[]=
		{
		"ACE_fieldDressing",
		"ACRE_PRC343",	
		"ACE_RangeCard",
		"rhsusf_ANPVS_14",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_morphine",
		"ACE_morphine",
		"ACE_EarPlugs"		
		};
	};
	
		    class 1990_British_Spotter_desert: B_Soldier_base_F
	{
		_generalMacro="1990_Desert_spotter";
		scope=2;
		displayName="Spotter";
		faction="twc_public_baf";
		editorSubcategory = "Men_1990D";
		vehicleClass="Men_1990D";
		icon="iconMan";
		nakedUniform="U_BasicBody";
		uniformClass="TWC_Smock_Desert";
		backpack="TWC_Backpack_1990_Sectionlead_Desert";
		linkedItems[]=
		{
        "UK3CB_BAF_V_PLCE_Webbing_DDPM",
		"UK3CB_BAF_H_Mk6_DDPM_C",
		"ItemMap",
		"ItemCompass",
		"ItemWatch"
		};
		respawnLinkedItems[]=
		{
        "UK3CB_BAF_V_PLCE_Webbing_DDPM",
		"UK3CB_BAF_H_Mk6_DDPM_C",
		"ItemMap",
		"ItemCompass",
		"ItemWatch"
		};
		weapons[]=
		{
		"Throw",
		"Put",
		"Binocular",
		"UK3CB_BAF_L85A1_SUSAT3D",
		"ukcw_hipower"
		};
		respawnweapons[]=
		{
		"Throw",
		"Put",
		"Binocular",
		"UK3CB_BAF_L85A1_SUSAT3D",
		"ukcw_hipower"
		};
		magazines[]=
		{
		"UK3CB_BAF_762_L42A1_10Rnd",
		"UK3CB_BAF_762_L42A1_10Rnd",
		"ukcw_13rd_9x19",
		"ukcw_13rd_9x19",
		"ukcw_13rd_9x19",
		"UK3CB_BAF_762_L42A1_10Rnd",
		"UK3CB_BAF_762_L42A1_10Rnd",
		"UK3CB_BAF_556_30Rnd",
		"UK3CB_BAF_556_30Rnd_t",
		"UK3CB_BAF_556_30Rnd",
		"UK3CB_BAF_556_30Rnd_t",
		"UK3CB_BAF_556_30Rnd",
		"SmokeShell",
		"SmokeShell"
		};
		Respawnmagazines[]=
		{
		"UK3CB_BAF_762_L42A1_10Rnd",
		"UK3CB_BAF_762_L42A1_10Rnd",
		"ukcw_13rd_9x19",
		"ukcw_13rd_9x19",
		"ukcw_13rd_9x19",
		"UK3CB_BAF_762_L42A1_10Rnd",
		"UK3CB_BAF_762_L42A1_10Rnd",
		"UK3CB_BAF_556_30Rnd",
		"UK3CB_BAF_556_30Rnd_t",
		"UK3CB_BAF_556_30Rnd",
		"UK3CB_BAF_556_30Rnd_t",
		"UK3CB_BAF_556_30Rnd",
		"SmokeShell",
		"SmokeShell"
		};
		Items[]=
		{
		"ACE_fieldDressing",
		"ACRE_PRC343",	
		"rhsusf_ANPVS_14",
		"ACE_EarPlugs",	
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_Tripod",
		"ACE_SpottingScope",
		"ACE_morphine",
		"ACE_morphine"
		};
		respawnitems[]=
		{
		"ACE_fieldDressing",
		"ACRE_PRC343",	
		"rhsusf_ANPVS_14",
		"ACE_EarPlugs",	
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_Tripod",
		"ACE_SpottingScope",
		"ACE_morphine",
		"ACE_morphine"		
		};
	};
	
		class 1990_British_MachineGunner_Desert: 1990_British_Gunner
	{
		displayName="GPMG Gunner";
		editorSubcategory = "Men_1990D";
		vehicleClass="Men_1990D";
		uniformClass="TWC_Smock_Desert";
		backpack="TWC_Backpack_1990_machineGunner_Desert";
				weapons[]=
		{
		"Throw",
		"Put",
		"UK3CB_BAF_L7A2"
		};
		respawnweapons[]=
		{
		"Throw",
		"Put",
		"UK3CB_BAF_L7A2"
		};
				magazines[]=
		{
		"UK3CB_BAF_762_200Rnd",
		"UK3CB_BAF_762_200Rnd",
		"SmokeShell"
		};
		Respawnmagazines[]=
		{
		"UK3CB_BAF_762_200Rnd",
		"UK3CB_BAF_762_200Rnd",
		"SmokeShell"
		};
		linkedItems[]=
		{
			"UK3CB_BAF_V_PLCE_Webbing_DDPM",
			"UK3CB_BAF_H_Mk6_DDPM_A",
			"ItemMap",
			"ItemCompass",
			"ItemWatch"
		};
		respawnLinkedItems[]=
		{
			"UK3CB_BAF_V_PLCE_Webbing_DDPM",
			"ItemMap",
			"ItemCompass",
			"ItemWatch"
		};
	};
	
		class 1990_British_mg_assistant_Desert: 1990_British_Rifleman
	{
		displayName="GPMG Assistant";
		editorSubcategory = "Men_1990D";
		vehicleClass="Men_1990D";
		uniformClass="TWC_Smock_Desert";
		backpack="TWC_Backpack_1990_machineGunner_Desert";
		linkedItems[]=
		{
			"UK3CB_BAF_V_PLCE_Webbing_DDPM",
			"UK3CB_BAF_H_Mk6_DDPM_A",
			"ItemMap",
			"ItemCompass",
			"ItemWatch"
		};
		respawnLinkedItems[]=
		{
			"UK3CB_BAF_V_PLCE_Webbing_DDPM",
			"UK3CB_BAF_H_Mk6_DDPM_A",
			"ItemMap",
			"ItemCompass",
			"ItemWatch"
		};
	};
	
		class 1990_British_quartermaster_Desert: 1990_British_SectionCommander
	{
		displayName="Quartermaster";
		editorSubcategory = "Men_1990D";
		vehicleClass="Men_1990D";
		uniformClass="TWC_Smock_Desert";
		attendant = 1;
		backpack="TWC_Backpack_1990_quartermaster_desert";
		linkedItems[]=
		{
			"UK3CB_BAF_V_PLCE_Webbing_DDPM",
			"UK3CB_BAF_H_Beret_PWRR_PRR",
			"ItemMap",
			"ItemCompass",
			"ItemWatch"
		};
		respawnLinkedItems[]=
		{
			"UK3CB_BAF_V_PLCE_Webbing_DDPM",
			"UK3CB_BAF_H_Beret_PWRR_PRR",
			"ItemMap",
			"ItemCompass",
			"ItemWatch"
		};
	};
//////////////////////////////////////////////////////////////////
//                                                              //
//                    1990 Woodland American                    //
//                                                              //
//////////////////////////////////////////////////////////////////
	class rhsgref_nat_base;
	class rhsgref_nat_woodland: rhsgref_nat_base
	{
		modelSides[] = {0,1,3};
	};
	class twc_men_1990_us_w_base: B_Soldier_base_F
	{
		scope=1;
		displayName="Rifleman";
		faction="twc_public_us";
		editorSubcategory = "twc_men_1990_us_w";
		vehicleClass="twc_men_1990_us_w";
		icon="iconMan";
		backpack="twc_men_1990_us_w_backpack_rifleman";
		nakedUniform="U_BasicBody";
		uniformClass="rhsgref_uniform_woodland";
		linkedItems[]=
		{
			"rhsgref_alice_webbing",
			"rhsgref_helmet_pasgt_woodland",
			"ItemMap",
			"ItemCompass",
			"ItemWatch"
		};
		respawnLinkedItems[]=
		{
			"rhsgref_alice_webbing",
			"rhsgref_helmet_pasgt_woodland",
			"ItemMap",
			"ItemCompass",
			"ItemWatch"
		};
		Items[]=
		{
			"ACE_EarPlugs",
			"ACRE_PRC148",
			"rhsusf_ANPVS_14",
			"ACE_fieldDressing",
			"ACE_fieldDressing",
			"ACE_packingBandage",
			"ACE_packingBandage",
			"ACE_packingBandage",
			"ACE_packingBandage",
			"ACE_packingBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_quikclot",
			"ACE_quikclot",
			"ACE_morphine",
			"ACE_epinephrine",
			"ACE_tourniquet",
			"ACE_tourniquet",
			"ACE_MapTools",
			"ACRE_PRC148"	
		};
		respawnitems[]=
		{
			"ACE_EarPlugs",
			"ACRE_PRC148",
			"rhsusf_ANPVS_14",
			"ACE_fieldDressing",
			"ACE_fieldDressing",
			"ACE_fieldDressing",
			"ACE_fieldDressing",
			"ACE_packingBandage",
			"ACE_packingBandage",
			"ACE_packingBandage",
			"ACE_packingBandage",
			"ACE_packingBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_quikclot",
			"ACE_quikclot",
			"ACE_morphine",
			"ACE_epinephrine",
			"ACE_tourniquet",
			"ACE_tourniquet"
		};		
	};
	class twc_men_1990_us_w_SquadLeader: twc_men_1990_us_w_base
	{
		scope=2;
		displayName="Squad Leader @US Army";
		icon="iconManLeader";
		backpack="twc_men_1990_us_w_backpack_squadlead";
		weapons[]=
		{
			"Throw",
			"Put",
			"ACE_Vector",
			"CUP_arifle_M16A2_GL"
		};
		respawnweapons[]=
		{
			"Throw",
			"Put",
			"ACE_Vector",
			"CUP_arifle_M16A2_GL"
		};
		magazines[]=
		{
			"30Rnd_556x45_Stanag",
			"30Rnd_556x45_Stanag",
			"30Rnd_556x45_Stanag",
			"30Rnd_556x45_Stanag",
			"30Rnd_556x45_Stanag",
			"30Rnd_556x45_Stanag_Tracer_Red",
			"30Rnd_556x45_Stanag_Tracer_Red",
			"30Rnd_556x45_Stanag_Tracer_Red",
			"HandGrenade",
			"HandGrenade",
			"SmokeShell",
			"SmokeShell"
		};
		Respawnmagazines[]=
		{
			"30Rnd_556x45_Stanag",
			"30Rnd_556x45_Stanag",
			"30Rnd_556x45_Stanag",
			"30Rnd_556x45_Stanag",
			"30Rnd_556x45_Stanag",
			"30Rnd_556x45_Stanag_Tracer_Red",
			"30Rnd_556x45_Stanag_Tracer_Red",
			"30Rnd_556x45_Stanag_Tracer_Red",
			"HandGrenade",
			"HandGrenade",
			"SmokeShell",
			"SmokeShell"
		};
	};
	class twc_men_1990_us_w_teamleader: twc_men_1990_us_w_base
	{
		scope=2;
		displayName="Team Leader";
		icon="iconManLeader";
		backpack="twc_men_1990_us_w_backpack_teamlead";
		weapons[]=
		{
			"Throw",
			"Put",
			"Binocular",
			"CUP_arifle_M16A2_GL"
		};
		respawnweapons[]=
		{
			"Throw",
			"Put",
			"Binocular",
			"CUP_arifle_M16A2_GL"
		};
		magazines[]=
		{
			"30Rnd_556x45_Stanag",
			"30Rnd_556x45_Stanag",
			"30Rnd_556x45_Stanag",
			"30Rnd_556x45_Stanag_Tracer_Red",
			"30Rnd_556x45_Stanag_Tracer_Red",
			"1Rnd_HE_Grenade_shell",
			"1Rnd_HE_Grenade_shell",
			"1Rnd_HE_Grenade_shell",
			"HandGrenade",
			"HandGrenade",
			"SmokeShell",
			"SmokeShell"
		};
		Respawnmagazines[]=
		{
			"30Rnd_556x45_Stanag",
			"30Rnd_556x45_Stanag",
			"30Rnd_556x45_Stanag",
			"30Rnd_556x45_Stanag_Tracer_Red",
			"30Rnd_556x45_Stanag_Tracer_Red",
			"1Rnd_HE_Grenade_shell",
			"1Rnd_HE_Grenade_shell",
			"1Rnd_HE_Grenade_shell",
			"HandGrenade",
			"HandGrenade",
			"SmokeShell",
			"SmokeShell"
		};		
	};
	class twc_men_1990_us_w_rifleman: twc_men_1990_us_w_base
	{
		scope=2;
		displayName="Rifleman";
		backpack="twc_men_1990_us_w_backpack_rifleman";
		weapons[]=
		{
			"Throw",
			"Put",	
			"CUP_arifle_M16A2"
		};
		respawnweapons[]=
		{
			"Throw",
			"Put",	
			"CUP_arifle_M16A2"
		};
		magazines[]=
		{
			"30Rnd_556x45_Stanag",
			"30Rnd_556x45_Stanag",
			"30Rnd_556x45_Stanag",
			"30Rnd_556x45_Stanag",
			"30Rnd_556x45_Stanag",
			"30Rnd_556x45_Stanag_Tracer_Red",
			"30Rnd_556x45_Stanag_Tracer_Red",
			"30Rnd_556x45_Stanag_Tracer_Red",
			"HandGrenade",
			"HandGrenade",
			"SmokeShell"
		};
		Respawnmagazines[]=
		{
			"30Rnd_556x45_Stanag",
			"30Rnd_556x45_Stanag",
			"30Rnd_556x45_Stanag",
			"30Rnd_556x45_Stanag",
			"30Rnd_556x45_Stanag",
			"30Rnd_556x45_Stanag_Tracer_Red",
			"30Rnd_556x45_Stanag_Tracer_Red",
			"30Rnd_556x45_Stanag_Tracer_Red",
			"HandGrenade",
			"HandGrenade",
			"SmokeShell"
		};	
	};
	class twc_men_1990_us_w_rifleman_at: twc_men_1990_us_w_base
	{
		scope=2;
		displayName="Rifleman AT";
		backpack="twc_men_1990_us_w_backpack_rifleman";
		weapons[]=
		{
			"Throw",
			"Put",	
			"CUP_arifle_M16A2",
			"rhs_weap_M136"
		};
		respawnweapons[]=
		{
			"Throw",
			"Put",	
			"CUP_arifle_M16A2",
			"rhs_weap_M136"
		};
		magazines[]=
		{
			"30Rnd_556x45_Stanag",
			"30Rnd_556x45_Stanag",
			"30Rnd_556x45_Stanag",
			"30Rnd_556x45_Stanag",
			"30Rnd_556x45_Stanag",
			"30Rnd_556x45_Stanag_Tracer_Red",
			"30Rnd_556x45_Stanag_Tracer_Red",
			"30Rnd_556x45_Stanag_Tracer_Red",
			"HandGrenade",
			"HandGrenade",
			"SmokeShell"
		};
		Respawnmagazines[]=
		{
			"30Rnd_556x45_Stanag",
			"30Rnd_556x45_Stanag",
			"30Rnd_556x45_Stanag",
			"30Rnd_556x45_Stanag",
			"30Rnd_556x45_Stanag",
			"30Rnd_556x45_Stanag_Tracer_Red",
			"30Rnd_556x45_Stanag_Tracer_Red",
			"30Rnd_556x45_Stanag_Tracer_Red",
			"HandGrenade",
			"HandGrenade",
			"SmokeShell"
		};	
	};
	class twc_men_1990_us_w_autorifleman: twc_men_1990_us_w_base
	{
		scope=2;
		displayName="Autorifleman";
		icon="iconManMG";
		backpack="twc_men_1990_us_w_backpack_autorifleman";
		weapons[]=
		{
			"Throw",
			"Put",	
			"rhs_weap_m249"
		};
		respawnweapons[]=
		{
			"Throw",
			"Put",	
			"rhs_weap_m249"
		};
		magazines[]=
		{
			"rhs_200rnd_556x45_B_SAW",
			"rhs_200rnd_556x45_B_SAW",
			"rhsusf_100Rnd_556x45_soft_pouch",
			"HandGrenade",
			"SmokeShell"
		};
		Respawnmagazines[]=
		{
			"rhs_200rnd_556x45_B_SAW",
			"rhs_200rnd_556x45_B_SAW",
			"rhsusf_100Rnd_556x45_soft_pouch",
			"HandGrenade",
			"SmokeShell"
		};		
	};