//REGULAR, DISMOUNTED, TROPIC
//Section
class TWC_Infantry_ColdWar_Regular_Dismounted_Tropic_Rifleman: TWC_Infantry_ColdWar_Regular_Tropic_Rifleman
{
	CATEGORY(TWC_Infantry_Dismounted_Tropic)
	backpack = "TWC_Backpack_ColdWar_Regular_Dismounted_Rifleman";
};
class TWC_Infantry_ColdWar_Regular_Dismounted_Tropic_Rifleman_SUIT: TWC_Infantry_ColdWar_Regular_Tropic_Rifleman_SUIT
{
	CATEGORY(TWC_Infantry_Dismounted_Tropic)
	backpack = "TWC_Backpack_ColdWar_Regular_Dismounted_Rifleman";
};
class TWC_Infantry_ColdWar_Regular_Dismounted_Tropic_SectionCommander: TWC_Infantry_ColdWar_Regular_Tropic_SectionCommander
{
	CATEGORY(TWC_Infantry_Dismounted_Tropic)
};
class TWC_Infantry_ColdWar_Regular_Dismounted_Tropic_2iC: TWC_Infantry_ColdWar_Regular_Tropic_2iC
{
	CATEGORY(TWC_Infantry_Dismounted_Tropic)
};
class TWC_Infantry_ColdWar_Regular_Dismounted_Tropic_AT: TWC_Infantry_ColdWar_Regular_Tropic_AT
{
	CATEGORY(TWC_Infantry_Dismounted_Tropic)
	backpack = "TWC_Backpack_ColdWar_Regular_Dismounted_AT";
};
class TWC_Infantry_ColdWar_Regular_Dismounted_Tropic_ASSAT: TWC_Infantry_ColdWar_Regular_Tropic_ASSAT
{
	CATEGORY(TWC_Infantry_Dismounted_Tropic)
	backpack = "TWC_Backpack_ColdWar_Regular_Dismounted_ATASS";
};
class TWC_Infantry_ColdWar_Regular_Dismounted_Tropic_MG: TWC_Infantry_ColdWar_Regular_Tropic_MG
{
	CATEGORY(TWC_Infantry_Dismounted_Tropic)
	backpack = "TWC_Backpack_ColdWar_Regular_Dismounted_MG";
};
class TWC_Infantry_ColdWar_Regular_Dismounted_Tropic_ASSMG: TWC_Infantry_ColdWar_Regular_Tropic_ASSMG
{
	CATEGORY(TWC_Infantry_Dismounted_Tropic)
	backpack = "TWC_Backpack_ColdWar_Regular_Dismounted_ASSMG";
};

//Platoon Command
class TWC_Infantry_ColdWar_Regular_Dismounted_Tropic_Platoon_Commander: TWC_Infantry_ColdWar_Regular_Tropic_Platoon_Commander
{
	CATEGORY(TWC_Infantry_Dismounted_Tropic)
};
class TWC_Infantry_ColdWar_Regular_Dismounted_Tropic_Platoon_Sergeant: TWC_Infantry_ColdWar_Regular_Tropic_Platoon_Sergeant
{
	CATEGORY(TWC_Infantry_Dismounted_Tropic)
};
class TWC_Infantry_ColdWar_Regular_Dismounted_Tropic_Platoon_Medic: TWC_Infantry_ColdWar_Regular_Tropic_Platoon_Medic
{
	CATEGORY(TWC_Infantry_Dismounted_Tropic)
};
class TWC_Infantry_ColdWar_Regular_Dismounted_Tropic_CSM: TWC_Infantry_ColdWar_Regular_Tropic_CSM
{
	CATEGORY(TWC_Infantry_Dismounted_Tropic)
};