class O_Soldier_Base_F;
	class TWC_Modern_rus_Base: O_Soldier_Base_F
	{
		scope=2;
		displayName="Rifleman";
		faction="rus_units";
		editorSubcategory = "Men_twc_woodland";
		vehicleClass="Men_twc_woodland";
		icon="iconMan";
		nakedUniform="U_BasicBody";
		uniformClass="CUP_U_O_RUS_EMR_1_VDV";
		twc_radioType = "ACRE_PRC343";
		backpack="twc_genbackPack_oli";
		twc_radioChannel = 3;
		linkedItems[]=
		{
			"CUP_V_RUS_6B45_3",
			"CUP_H_RUS_6B27_cover_headset_goggles",
			"ItemMap",
			"ItemCompass",
			"ItemWatch"
		};
		respawnLinkedItems[]=
		{
			"CUP_V_RUS_6B45_3",
			"CUP_H_RUS_6B27_cover_headset_goggles",
			"ItemMap",
			"ItemCompass",
			"ItemWatch"
		};
		weapons[]=
		{
			"Throw",
			"Put",
			"CUP_arifle_AK74M"
		};
		respawnweapons[]=
		{
			"Throw",
			"Put",
			"CUP_arifle_AK74M"
		};
		Items[]=
		{
			"ACE_fieldDressing",
			"ACE_fieldDressing",
			
			"ACE_EarPlugs",
			"ACRE_PRC343",
			"ACE_fieldDressing",
			"ACE_fieldDressing",
			"ACE_fieldDressing",
			"ACE_fieldDressing",
			"ACE_fieldDressing",
			"ACE_fieldDressing",
			"ACE_packingBandage",
			"ACE_packingBandage",
			"ACE_packingBandage",
			"ACE_packingBandage",
			"ACE_packingBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_quikclot",
			"ACE_quikclot",
			"ACE_morphine",
			"ACE_epinephrine",
			"ACE_tourniquet",
			"ACE_tourniquet",
			"ACE_MapTools"
		};
		respawnitems[]=
		{
			"ACE_fieldDressing",
			"ACE_fieldDressing",
			
			"ACE_EarPlugs",
			"ACRE_PRC343",
			"ACE_fieldDressing",
			"ACE_fieldDressing",
			"ACE_fieldDressing",
			"ACE_fieldDressing",
			"ACE_fieldDressing",
			"ACE_packingBandage",
			"ACE_packingBandage",
			"ACE_packingBandage",
			"ACE_packingBandage",
			"ACE_packingBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_quikclot",
			"ACE_quikclot",
			"ACE_morphine",
			"ACE_epinephrine",
			"ACE_tourniquet",
			"ACE_tourniquet"
		};
		magazines[]=
		{
			"CUP_30Rnd_545x39_AK74M_M",
			"CUP_30Rnd_545x39_AK74M_M",
			"CUP_30Rnd_545x39_AK74M_M",
			"CUP_30Rnd_545x39_AK74M_M",
			"CUP_30Rnd_545x39_AK74M_M",
			"CUP_30Rnd_545x39_AK74M_M",
			"CUP_30Rnd_545x39_AK74M_M",
			"CUP_30Rnd_545x39_AK74M_M",
			"CUP_HandGrenade_RGD5",
			"CUP_HandGrenade_RGD5",
			"SmokeShell",
			"SmokeShell",
			"SmokeShell"
		};
		Respawnmagazines[]=
		{
			"CUP_30Rnd_545x39_AK74M_M",
			"CUP_30Rnd_545x39_AK74M_M",
			"CUP_30Rnd_545x39_AK74M_M",
			"CUP_30Rnd_545x39_AK74M_M",
			"CUP_30Rnd_545x39_AK74M_M",
			"CUP_30Rnd_545x39_AK74M_M",
			"CUP_30Rnd_545x39_AK74M_M",
			"CUP_30Rnd_545x39_AK74M_M",
			"CUP_HandGrenade_RGD5",
			"CUP_HandGrenade_RGD5",
			"SmokeShell",
			"SmokeShell",
			"SmokeShell"
		};
	};
	
	class TWC_Modern_rus_Base_l: TWC_Modern_rus_Base
	{
		backpack="";
	};

	class TWC_Modern_rus_Base_d: TWC_Modern_rus_Base
	{
		scope=2;
		editorSubcategory = "Men_twc_desert";
		vehicleClass="Men_twc_desert";
		uniformClass="CUP_U_O_RUS_BeigeDigital_VDV_rolled_up";
		linkedItems[]=
		{
			"CUP_V_RUS_6B45_3",
			"CUP_H_RUS_6B27_cover_headset_goggles",
			"ItemMap",
			"ItemCompass",
			"ItemWatch"
		};
		respawnLinkedItems[]=
		{
			"CUP_V_RUS_6B45_3",
			"CUP_H_RUS_6B27_cover_headset_goggles",
			"ItemMap",
			"ItemCompass",
			"ItemWatch"
		};
	};
	
	class TWC_Modern_rus_Base_d_l: TWC_Modern_rus_Base_d
	{
		backpack="";
	};
	
	
	class TWC_Modern_rus_rifleman_at: TWC_Modern_rus_Base
	{
		scope=2;
		displayName="Rifleman (AT)";
		backpack="pol_backpack_rpg";
		weapons[]=
		{
			"Throw",
			"Put",
			"CUP_launch_RPG7V_PGO7V",
			"CUP_arifle_AK74M"
		};
		respawnweapons[]=
		{
			"Throw",
			"Put",
			"CUP_launch_RPG7V_PGO7V",
			"CUP_arifle_AK74M"
		};
		magazines[]=
		{
			"CUP_PG7V_M",
			"CUP_30Rnd_545x39_AK74M_M",
			"CUP_30Rnd_545x39_AK74M_M",
			"CUP_30Rnd_545x39_AK74M_M",
			"CUP_30Rnd_545x39_AK74M_M",
			"CUP_30Rnd_545x39_AK74M_M",
			"CUP_30Rnd_545x39_AK74M_M",
			"CUP_30Rnd_545x39_AK74M_M",
			"CUP_HandGrenade_RGD5",
			"CUP_HandGrenade_RGD5",
			"SmokeShell",
			"SmokeShell",
			"SmokeShell"
		};
		Respawnmagazines[]=
		{
			"CUP_PG7V_M",
			"CUP_30Rnd_545x39_AK74M_M",
			"CUP_30Rnd_545x39_AK74M_M",
			"CUP_30Rnd_545x39_AK74M_M",
			"CUP_30Rnd_545x39_AK74M_M",
			"CUP_30Rnd_545x39_AK74M_M",
			"CUP_30Rnd_545x39_AK74M_M",
			"CUP_30Rnd_545x39_AK74M_M",
			"CUP_HandGrenade_RGD5",
			"CUP_HandGrenade_RGD5",
			"SmokeShell",
			"SmokeShell",
			"SmokeShell"
		};
	};
	class TWC_Modern_rus_rifleman_at_l: TWC_Modern_rus_rifleman_at
	{
		backpack="";
	};
	
	class TWC_Modern_rus_rifleman_at_d: TWC_Modern_rus_rifleman_at
	{
		scope=2;
		editorSubcategory = "Men_twc_desert";
		vehicleClass="Men_twc_desert";
		uniformClass="CUP_U_O_RUS_BeigeDigital_VDV_rolled_up";
		linkedItems[]=
		{
			"CUP_V_RUS_6B45_3",
			"CUP_H_RUS_6B27_cover_headset_goggles",
			"ItemMap",
			"ItemCompass",
			"ItemWatch"
		};
		respawnLinkedItems[]=
		{
			"CUP_V_RUS_6B45_3",
			"CUP_H_RUS_6B27_cover_headset_goggles",
			"ItemMap",
			"ItemCompass",
			"ItemWatch"
		};
	};
	class TWC_Modern_rus_rifleman_at_d_l: TWC_Modern_rus_rifleman_at_d
	{
		backpack="";
	};
	
	class TWC_Modern_rus_at_assistant: TWC_Modern_rus_Base
	{
		backpack="pol_backpack_rpg";
		displayName="AT Assistant";
	};
	class TWC_Modern_rus_at_assistant_l: TWC_Modern_rus_at_assistant
	{
		backpack="";
	};
	
	class TWC_Modern_rus_at_assistant_d: TWC_Modern_rus_Base
	{
		uniformClass="CUP_U_O_RUS_BeigeDigital_VDV_rolled_up";
		editorSubcategory = "Men_twc_desert";
		vehicleClass="Men_twc_desert";
	};
	class TWC_Modern_rus_at_assistant_d_l: TWC_Modern_rus_at_assistant_d
	{
		backpack="";
	};
	
	
	class TWC_Modern_rus_grenadier: TWC_Modern_rus_Base
	{
		scope=2;
		displayName="Grenadier";
		weapons[]=
		{
			"Throw",
			"Put",
			"CUP_arifle_AK74M_GL_kobra_snds"
		};
		respawnweapons[]=
		{
			"Throw",
			"Put",
			"CUP_arifle_AK74M_GL_kobra_snds"
		};
		magazines[]=
		{
			"CUP_30Rnd_545x39_AK74M_M",
			"CUP_30Rnd_545x39_AK74M_M",
			"CUP_30Rnd_545x39_AK74M_M",
			"CUP_30Rnd_545x39_AK74M_M",
			"CUP_30Rnd_545x39_AK74M_M",
			"CUP_30Rnd_545x39_AK74M_M",
			"CUP_30Rnd_545x39_AK74M_M",
			"CUP_HandGrenade_RGD5",
			"SmokeShell",
			"CUP_1Rnd_HE_GP25_M",
			"CUP_1Rnd_HE_GP25_M",
			"CUP_1Rnd_HE_GP25_M",
			"CUP_1Rnd_HE_GP25_M",
			"CUP_1Rnd_HE_GP25_M",
			"CUP_1Rnd_HE_GP25_M",
			"CUP_1Rnd_HE_GP25_M",
			"CUP_1Rnd_HE_GP25_M"
		};
		Respawnmagazines[]=
		{
			"CUP_30Rnd_545x39_AK74M_M",
			"CUP_30Rnd_545x39_AK74M_M",
			"CUP_30Rnd_545x39_AK74M_M",
			"CUP_30Rnd_545x39_AK74M_M",
			"CUP_30Rnd_545x39_AK74M_M",
			"CUP_30Rnd_545x39_AK74M_M",
			"CUP_30Rnd_545x39_AK74M_M",
			"CUP_HandGrenade_RGD5",
			"SmokeShell",
			"CUP_1Rnd_HE_GP25_M",
			"CUP_1Rnd_HE_GP25_M",
			"CUP_1Rnd_HE_GP25_M",
			"CUP_1Rnd_HE_GP25_M",
			"CUP_1Rnd_HE_GP25_M",
			"CUP_1Rnd_HE_GP25_M",
			"CUP_1Rnd_HE_GP25_M",
			"CUP_1Rnd_HE_GP25_M"
		};
	};
	class TWC_Modern_rus_grenadier_l: TWC_Modern_rus_grenadier
	{
		backpack="";
	};
	
	class TWC_Modern_rus_grenadier_d: TWC_Modern_rus_grenadier
	{
		scope=2;
		editorSubcategory = "Men_twc_desert";
		vehicleClass="Men_twc_desert";
		uniformClass="CUP_U_O_RUS_BeigeDigital_VDV_rolled_up";
		linkedItems[]=
		{
			"CUP_V_RUS_6B45_3",
			"CUP_H_RUS_6B27_cover_headset_goggles",
			"ItemMap",
			"ItemCompass",
			"ItemWatch"
		};
		respawnLinkedItems[]=
		{
			"CUP_V_RUS_6B45_3",
			"CUP_H_RUS_6B27_cover_headset_goggles",
			"ItemMap",
			"ItemCompass",
			"ItemWatch"
		};
	};
	class TWC_Modern_rus_grenadier_d_l: TWC_Modern_rus_grenadier_d
	{
		backpack="";
	};
	
	
	class TWC_Modern_rus_mg: TWC_Modern_rus_Base
	{
		scope=2;
		displayName="Machinegunner";
		backpack="pol_backpack_mg";
		weapons[]=
		{
			"Throw",
			"Put",
			"CUP_lmg_PKM"
		};
		respawnweapons[]=
		{
			"Throw",
			"Put",
			"CUP_lmg_PKM"
		};
		magazines[]=
		{
			"CUP_100Rnd_TE4_LRT4_762x54_PK_Tracer_Green_M",
			"CUP_100Rnd_TE4_LRT4_762x54_PK_Tracer_Green_M",
			"CUP_HandGrenade_RGD5",
			"CUP_HandGrenade_RGD5",
			"SmokeShell",
			"SmokeShell",
			"SmokeShell",
			"SmokeShell"
		};
		Respawnmagazines[]=
		{
			"CUP_100Rnd_TE4_LRT4_762x54_PK_Tracer_Green_M",
			"CUP_100Rnd_TE4_LRT4_762x54_PK_Tracer_Green_M",
			"CUP_HandGrenade_RGD5",
			"CUP_HandGrenade_RGD5",
			"SmokeShell",
			"SmokeShell",
			"SmokeShell",
			"SmokeShell"
		};
	};
	class TWC_Modern_rus_mg_l: TWC_Modern_rus_mg
	{
		backpack="";
	};
	
	class TWC_Modern_rus_mg_d: TWC_Modern_rus_mg
	{
		scope=2;
		editorSubcategory = "Men_twc_desert";
		vehicleClass="Men_twc_desert";
		uniformClass="CUP_U_O_RUS_BeigeDigital_VDV_rolled_up";
		linkedItems[]=
		{
			"CUP_V_RUS_6B45_3",
			"CUP_H_RUS_6B27_cover_headset_goggles",
			"ItemMap",
			"ItemCompass",
			"ItemWatch"
		};
		respawnLinkedItems[]=
		{
			"CUP_V_RUS_6B45_3",
			"CUP_H_RUS_6B27_cover_headset_goggles",
			"ItemMap",
			"ItemCompass",
			"ItemWatch"
		};
	};
	class TWC_Modern_rus_mg_d_l: TWC_Modern_rus_mg_d
	{
		backpack="";
	};
	
	class TWC_Modern_rus_mg_assistant: TWC_Modern_rus_Base
	{
		backpack="pol_backpack_mg";
		displayName="MG Assistant";
	};
	class TWC_Modern_rus_mg_assistant_l: TWC_Modern_rus_mg_assistant
	{
		backpack="";
	};
	
	class TWC_Modern_rus_mg_assistant_d: TWC_Modern_rus_mg_assistant
	{
		editorSubcategory = "Men_twc_desert";
		vehicleClass="Men_twc_desert";
		uniformClass="CUP_U_O_RUS_BeigeDigital_VDV_rolled_up";
		linkedItems[]=
		{
			"CUP_V_RUS_6B45_3",
			"CUP_H_RUS_6B27_cover_headset_goggles",
			"ItemMap",
			"ItemCompass",
			"ItemWatch"
		};
		respawnLinkedItems[]=
		{
			"CUP_V_RUS_6B45_3",
			"CUP_H_RUS_6B27_cover_headset_goggles",
			"ItemMap",
			"ItemCompass",
			"ItemWatch"
		};
	};
	class TWC_Modern_rus_mg_assistant_d_l: TWC_Modern_rus_mg_assistant_d
	{
		backpack="";
	};
	
	
	class TWC_Modern_rus_commander: TWC_Modern_rus_Base
	{
		scope=2;
		displayName="Section Commander @VDV Section";
		backpack="pol_backpack_leader";
		linkedItems[]=
		{
			"CUP_V_RUS_6B45_3",
			"CUP_H_RUS_6B27_cover_headset_goggles",
			"ItemMap",
			"ItemCompass",
			"itemCTAB",
			"ItemWatch"
		};
		respawnLinkedItems[]=
		{
			"CUP_V_RUS_6B45_3",
			"CUP_H_RUS_6B27_cover_headset_goggles",
			"ItemMap",
			"ItemCompass",
			"itemCTAB",
			"ItemWatch"
		};
		weapons[]=
		{
			"Throw",
			"Put",
			"CUP_SOFLAM",
			"CUP_arifle_AK74M_EKP"
		};
		respawnweapons[]=
		{
			"Throw",
			"Put",
			"CUP_SOFLAM",
			"CUP_arifle_AK74M_EKP"
		};
	};
	class TWC_Modern_rus_commander_l: TWC_Modern_rus_commander
	{
		backpack="";
		displayName="Section Commander @VDV Section (Mechanised)";
		Items[]=
		{
			"ACE_fieldDressing",
			"ACE_fieldDressing",
			
			"ACE_EarPlugs",
			"ACRE_PRC343",
			"ACRE_PRC152",
			"ACE_fieldDressing",
			"ACE_fieldDressing",
			"ACE_fieldDressing",
			"ACE_fieldDressing",
			"ACE_fieldDressing",
			"ACE_fieldDressing",
			"ACE_packingBandage",
			"ACE_packingBandage",
			"ACE_packingBandage",
			"ACE_packingBandage",
			"ACE_packingBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_quikclot",
			"ACE_quikclot",
			"ACE_morphine",
			"ACE_epinephrine",
			"ACE_tourniquet",
			"ACE_tourniquet",
			"ACE_MapTools"
		};
		respawnitems[]=
		{
			"ACE_fieldDressing",
			"ACE_fieldDressing",
			
			"ACE_EarPlugs",
			"ACRE_PRC343",
			"ACRE_PRC152",
			"ACE_fieldDressing",
			"ACE_fieldDressing",
			"ACE_fieldDressing",
			"ACE_fieldDressing",
			"ACE_fieldDressing",
			"ACE_packingBandage",
			"ACE_packingBandage",
			"ACE_packingBandage",
			"ACE_packingBandage",
			"ACE_packingBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_quikclot",
			"ACE_quikclot",
			"ACE_morphine",
			"ACE_epinephrine",
			"ACE_tourniquet",
			"ACE_tourniquet"
		};
	};
	
	class TWC_Modern_rus_commander_d: TWC_Modern_rus_commander
	{
		scope=2;
		editorSubcategory = "Men_twc_desert";
		vehicleClass="Men_twc_desert";
		uniformClass="CUP_U_O_RUS_BeigeDigital_VDV_rolled_up";
		linkedItems[]=
		{
			"CUP_V_RUS_6B45_3",
			"CUP_H_RUS_6B27_cover_headset_goggles",
			"ItemMap",
			"ItemCompass",
			"itemCTAB",
			"ItemWatch"
		};
		respawnLinkedItems[]=
		{
			"CUP_V_RUS_6B45_3",
			"CUP_H_RUS_6B27_cover_headset_goggles",
			"ItemMap",
			"ItemCompass",
			"itemCTAB",
			"ItemWatch"
		};
	};
	class TWC_Modern_rus_commander_d_l: TWC_Modern_rus_commander_d
	{
		backpack="";
		Items[]=
		{
			"ACE_fieldDressing",
			"ACE_fieldDressing",
			
			"ACE_EarPlugs",
			"ACRE_PRC343",
			"ACRE_PRC152",
			"ACE_fieldDressing",
			"ACE_fieldDressing",
			"ACE_fieldDressing",
			"ACE_fieldDressing",
			"ACE_fieldDressing",
			"ACE_fieldDressing",
			"ACE_packingBandage",
			"ACE_packingBandage",
			"ACE_packingBandage",
			"ACE_packingBandage",
			"ACE_packingBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_quikclot",
			"ACE_quikclot",
			"ACE_morphine",
			"ACE_epinephrine",
			"ACE_tourniquet",
			"ACE_tourniquet",
			"ACE_MapTools"
		};
		respawnitems[]=
		{
			"ACE_fieldDressing",
			"ACE_fieldDressing",
			
			"ACE_EarPlugs",
			"ACRE_PRC343",
			"ACRE_PRC152",
			"ACE_fieldDressing",
			"ACE_fieldDressing",
			"ACE_fieldDressing",
			"ACE_fieldDressing",
			"ACE_fieldDressing",
			"ACE_packingBandage",
			"ACE_packingBandage",
			"ACE_packingBandage",
			"ACE_packingBandage",
			"ACE_packingBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_quikclot",
			"ACE_quikclot",
			"ACE_morphine",
			"ACE_epinephrine",
			"ACE_tourniquet",
			"ACE_tourniquet"
		};
	};
	
	
	class TWC_Modern_rus_subcommander: TWC_Modern_rus_commander
	{
		scope=2;
		displayName="2ic";
		backpack="rus_backpack_2ic";
		linkedItems[]=
		{
			"CUP_V_RUS_6B45_3",
			"CUP_H_RUS_6B27_cover_headset_goggles",
			"ItemMap",
			"ItemCompass",
			"ItemWatch"
		};
		respawnLinkedItems[]=
		{
			"CUP_V_RUS_6B45_3",
			"CUP_H_RUS_6B27_cover_headset_goggles",
			"ItemMap",
			"ItemCompass",
			"ItemWatch"
		};
		weapons[]=
		{
			"Throw",
			"Put",
			"CUP_arifle_AK74M_GL_kobra_snds"
		};
		respawnweapons[]=
		{
			"Throw",
			"Put",
			"CUP_arifle_AK74M_GL_kobra_snds"
		};
		magazines[]=
		{
			"CUP_30Rnd_545x39_AK74M_M",
			"CUP_30Rnd_545x39_AK74M_M",
			"CUP_30Rnd_545x39_AK74M_M",
			"CUP_30Rnd_545x39_AK74M_M",
			"CUP_30Rnd_545x39_AK74M_M",
			"CUP_30Rnd_545x39_AK74M_M",
			"CUP_30Rnd_545x39_AK74M_M",
			"CUP_HandGrenade_RGD5",
			"SmokeShell",
			"CUP_1Rnd_HE_GP25_M",
			"CUP_1Rnd_HE_GP25_M",
			"CUP_1Rnd_HE_GP25_M",
			"CUP_1Rnd_HE_GP25_M",
			"CUP_1Rnd_HE_GP25_M",
			"CUP_1Rnd_HE_GP25_M",
			"CUP_1Rnd_HE_GP25_M",
			"CUP_1Rnd_HE_GP25_M"
		};
		Respawnmagazines[]=
		{
			"CUP_30Rnd_545x39_AK74M_M",
			"CUP_30Rnd_545x39_AK74M_M",
			"CUP_30Rnd_545x39_AK74M_M",
			"CUP_30Rnd_545x39_AK74M_M",
			"CUP_30Rnd_545x39_AK74M_M",
			"CUP_30Rnd_545x39_AK74M_M",
			"CUP_30Rnd_545x39_AK74M_M",
			"CUP_HandGrenade_RGD5",
			"SmokeShell",
			"CUP_1Rnd_HE_GP25_M",
			"CUP_1Rnd_HE_GP25_M",
			"CUP_1Rnd_HE_GP25_M",
			"CUP_1Rnd_HE_GP25_M",
			"CUP_1Rnd_HE_GP25_M",
			"CUP_1Rnd_HE_GP25_M",
			"CUP_1Rnd_HE_GP25_M",
			"CUP_1Rnd_HE_GP25_M"
		};
	};
	class TWC_Modern_rus_subcommander_l: TWC_Modern_rus_subcommander
	{
		backpack="";
	};
	
	class TWC_Modern_rus_subcommander_d: TWC_Modern_rus_subcommander
	{
		scope=2;
		editorSubcategory = "Men_twc_desert";
		vehicleClass="Men_twc_desert";
		uniformClass="CUP_U_O_RUS_BeigeDigital_VDV_rolled_up";
		linkedItems[]=
		{
			"CUP_V_RUS_6B45_3",
			"CUP_H_RUS_6B27_cover_headset_goggles",
			"ItemMap",
			"ItemCompass",
			"ItemWatch"
		};
		respawnLinkedItems[]=
		{
			"CUP_V_RUS_6B45_3",
			"CUP_H_RUS_6B27_cover_headset_goggles",
			"ItemMap",
			"ItemCompass",
			"ItemWatch"
		};
	};
	class TWC_Modern_rus_subcommander_d_l: TWC_Modern_rus_subcommander_d
	{
		backpack="";
	};
	
	
	class TWC_Modern_rus_medic: TWC_Modern_rus_base
	{
		scope=2;
		displayName="Medic";
		attendant = 1;
		backpack="rus_backpack_medic";
	};
	
	class TWC_Modern_rus_medic_l: TWC_Modern_rus_medic
	{
		backpack="";
	};
	
	
	class TWC_Modern_rus_medic_d: TWC_Modern_rus_medic
	{
		scope=2;
		editorSubcategory = "Men_twc_desert";
		vehicleClass="Men_twc_desert";
		uniformClass="CUP_U_O_RUS_BeigeDigital_VDV_rolled_up";
		linkedItems[]=
		{
			"CUP_V_RUS_6B45_3",
			"CUP_H_RUS_6B27_cover_headset_goggles",
			"ItemMap",
			"ItemCompass",
			"ItemWatch"
		};
		respawnLinkedItems[]=
		{
			"CUP_V_RUS_6B45_3",
			"CUP_H_RUS_6B27_cover_headset_goggles",
			"ItemMap",
			"ItemCompass",
			"ItemWatch"
		};
	};
	class TWC_Modern_rus_medic_d_l: TWC_Modern_rus_medic_d
	{
		backpack="";
	};
	
	
	class TWC_Modern_rus_vehcommander: TWC_Modern_rus_base
	{
		scope=2;
		displayName="Vehicle Commander @Armour Crew";
		backpack="twc_genbackPack_oli";
		linkedItems[]=
		{
			"CUP_V_I_RACS_Carrier_Rig_wdl_3",
			"itemCTAB",
			"CUP_H_SLA_TankerHelmet",
			"ItemMap",
			"ItemCompass",
			"ItemWatch"
		};
		respawnLinkedItems[]=
		{
			"CUP_V_I_RACS_Carrier_Rig_wdl_3",
			"itemCTAB",
			"CUP_H_SLA_TankerHelmet",
			"ItemMap",
			"ItemCompass",
			"ItemWatch"
		};
		weapons[]=
		{
			"Throw",
			"Put",
			"CUP_arifle_AKS74U"
		};
		respawnweapons[]=
		{
			"Throw",
			"Put",
			"CUP_arifle_AKS74U"
		};
		magazines[]=
		{
			"CUP_30Rnd_545x39_AK74M_M",
			"CUP_30Rnd_545x39_AK74M_M",
			"CUP_30Rnd_545x39_AK74M_M",
			"CUP_30Rnd_545x39_AK74M_M",
			"CUP_30Rnd_545x39_AK74M_M",
			"CUP_30Rnd_545x39_AK74M_M",
			"CUP_30Rnd_545x39_AK74M_M",
			"SmokeShell"
		};
		Respawnmagazines[]=
		{
			"CUP_30Rnd_545x39_AK74M_M",
			"CUP_30Rnd_545x39_AK74M_M",
			"CUP_30Rnd_545x39_AK74M_M",
			"CUP_30Rnd_545x39_AK74M_M",
			"CUP_30Rnd_545x39_AK74M_M",
			"CUP_30Rnd_545x39_AK74M_M",
			"CUP_30Rnd_545x39_AK74M_M",
			"SmokeShell"
		};
		Items[]=
		{
			"ACE_fieldDressing",
			"ACE_fieldDressing",
			
			"ACE_EarPlugs",
			"ACRE_PRC343",
			"ACRE_PRC148",
			"ACE_fieldDressing",
			"ACE_fieldDressing",
			"ACE_fieldDressing",
			"ACE_fieldDressing",
			"ACE_fieldDressing",
			"ACE_fieldDressing",
			"ACE_packingBandage",
			"ACE_packingBandage",
			"ACE_packingBandage",
			"ACE_packingBandage",
			"ACE_packingBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_quikclot",
			"ACE_quikclot",
			"ACE_morphine",
			"ACE_epinephrine",
			"ACE_tourniquet",
			"ACE_tourniquet",
			"ACE_MapTools"
		};
		respawnitems[]=
		{
			"ACE_fieldDressing",
			"ACE_fieldDressing",
			
			"ACE_EarPlugs",
			"ACRE_PRC343",
			"ACRE_PRC148",
			"ACE_fieldDressing",
			"ACE_fieldDressing",
			"ACE_fieldDressing",
			"ACE_fieldDressing",
			"ACE_fieldDressing",
			"ACE_packingBandage",
			"ACE_packingBandage",
			"ACE_packingBandage",
			"ACE_packingBandage",
			"ACE_packingBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_quikclot",
			"ACE_quikclot",
			"ACE_morphine",
			"ACE_epinephrine",
			"ACE_tourniquet",
			"ACE_tourniquet"
		};
	};
	
	class TWC_Modern_rus_vehcommander_l: TWC_Modern_rus_vehcommander
	{
		displayName="Vehicle Commander";
		Items[]=
		{
			"ACE_fieldDressing",
			"ACE_fieldDressing",
			
			"ACE_EarPlugs",
			"ACRE_PRC343",
			"ACE_fieldDressing",
			"ACE_fieldDressing",
			"ACE_fieldDressing",
			"ACE_fieldDressing",
			"ACE_fieldDressing",
			"ACE_fieldDressing",
			"ACE_packingBandage",
			"ACE_packingBandage",
			"ACE_packingBandage",
			"ACE_packingBandage",
			"ACE_packingBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_quikclot",
			"ACE_quikclot",
			"ACE_morphine",
			"ACE_epinephrine",
			"ACE_tourniquet",
			"ACE_tourniquet",
			"ACE_MapTools"
		};
		respawnitems[]=
		{
			"ACE_fieldDressing",
			"ACE_fieldDressing",
			
			"ACE_EarPlugs",
			"ACRE_PRC343",
			"ACE_fieldDressing",
			"ACE_fieldDressing",
			"ACE_fieldDressing",
			"ACE_fieldDressing",
			"ACE_fieldDressing",
			"ACE_packingBandage",
			"ACE_packingBandage",
			"ACE_packingBandage",
			"ACE_packingBandage",
			"ACE_packingBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_quikclot",
			"ACE_quikclot",
			"ACE_morphine",
			"ACE_epinephrine",
			"ACE_tourniquet",
			"ACE_tourniquet"
		};
	};
	
	class TWC_Modern_rus_vehcommander_d: TWC_Modern_rus_vehcommander
	{
		scope=2;
		editorSubcategory = "Men_twc_desert";
		vehicleClass="Men_twc_desert";
		uniformClass="CUP_U_O_RUS_BeigeDigital_VDV_rolled_up";
	};
	
	class TWC_Modern_rus_vehcommander_d_l: TWC_Modern_rus_vehcommander_d
	{};
	
	class TWC_Modern_rus_vehcrewman: TWC_Modern_rus_vehcommander
	{
		scope=2;
		displayName="Vehicle Crewman";
		linkedItems[]=
		{
			"CUP_V_O_SLA_M23_1_OD",
			"CUP_H_SLA_TankerHelmet",
			"ItemMap",
			"ItemCompass",
			"ItemWatch"
		};
		respawnLinkedItems[]=
		{
			"CUP_V_O_SLA_M23_1_OD",
			"CUP_H_SLA_TankerHelmet",
			"ItemMap",
			"ItemCompass",
			"ItemWatch"
		};
		Items[]=
		{
			"ACE_fieldDressing",
			"ACE_fieldDressing",
			
			"ACE_EarPlugs",
			"ACRE_PRC343",
			"ACE_fieldDressing",
			"ACE_fieldDressing",
			"ACE_fieldDressing",
			"ACE_fieldDressing",
			"ACE_fieldDressing",
			"ACE_fieldDressing",
			"ACE_packingBandage",
			"ACE_packingBandage",
			"ACE_packingBandage",
			"ACE_packingBandage",
			"ACE_packingBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_quikclot",
			"ACE_quikclot",
			"ACE_morphine",
			"ACE_epinephrine",
			"ACE_tourniquet",
			"ACE_tourniquet",
			"ACE_MapTools"
		};
		respawnitems[]=
		{
			"ACE_fieldDressing",
			"ACE_fieldDressing",
			
			"ACE_EarPlugs",
			"ACRE_PRC343",
			"ACE_fieldDressing",
			"ACE_fieldDressing",
			"ACE_fieldDressing",
			"ACE_fieldDressing",
			"ACE_fieldDressing",
			"ACE_packingBandage",
			"ACE_packingBandage",
			"ACE_packingBandage",
			"ACE_packingBandage",
			"ACE_packingBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_quikclot",
			"ACE_quikclot",
			"ACE_morphine",
			"ACE_epinephrine",
			"ACE_tourniquet",
			"ACE_tourniquet"
		};
	};
	
	class TWC_Modern_rus_vehcrewman_l: TWC_Modern_rus_vehcrewman
	{};
	
	class TWC_Modern_rus_vehcrewman_d: TWC_Modern_rus_vehcrewman
	{
		scope=2;
		editorSubcategory = "Men_twc_desert";
		vehicleClass="Men_twc_desert";
		uniformClass="CUP_U_O_RUS_BeigeDigital_VDV_rolled_up";
	};
	
	class TWC_Modern_rus_vehcrewman_d_l: TWC_Modern_rus_vehcrewman_d
	{};
	
	class TWC_Modern_rus_helipilot: TWC_Modern_rus_vehcrewman
	{
		scope=2;
		displayName="Helicopter Pilot";
		uniformClass="CUP_U_O_SLA_Overalls_Pilot";
		linkedItems[]=
		{
			"Aircrew_vest_2_NH",
			"CUP_H_RUS_ZSH_Shield_Up",
			"ItemMap",
			"ItemCompass",
			"ItemWatch"
		};
		respawnLinkedItems[]=
		{
			"Aircrew_vest_2_NH",
			"CUP_H_RUS_ZSH_Shield_Up",
			"ItemMap",
			"ItemCompass",
			"ItemWatch"
		};
		Items[]=
		{
			"ACE_fieldDressing",
			"ACE_fieldDressing",
			
			"ACE_EarPlugs",
			"ACRE_PRC148",
			"ACE_fieldDressing",
			"ACE_fieldDressing",
			"ACE_fieldDressing",
			"ACE_fieldDressing",
			"ACE_fieldDressing",
			"ACE_fieldDressing",
			"ACE_packingBandage",
			"ACE_packingBandage",
			"ACE_packingBandage",
			"ACE_packingBandage",
			"ACE_packingBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_quikclot",
			"ACE_quikclot",
			"ACE_morphine",
			"ACE_epinephrine",
			"ACE_tourniquet",
			"ACE_tourniquet",
			"ACE_MapTools"
		};
		respawnitems[]=
		{
			"ACE_fieldDressing",
			"ACE_fieldDressing",
			
			"ACE_EarPlugs",
			"ACRE_PRC148",
			"ACE_fieldDressing",
			"ACE_fieldDressing",
			"ACE_fieldDressing",
			"ACE_fieldDressing",
			"ACE_fieldDressing",
			"ACE_packingBandage",
			"ACE_packingBandage",
			"ACE_packingBandage",
			"ACE_packingBandage",
			"ACE_packingBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_quikclot",
			"ACE_quikclot",
			"ACE_morphine",
			"ACE_epinephrine",
			"ACE_tourniquet",
			"ACE_tourniquet"
		};
	};
	
	class TWC_Modern_rus_crewchief: TWC_Modern_rus_helipilot
	{
		scope=2;
		displayName="Helicopter Crew Chief";
		linkedItems[]=
		{
			"Aircrew_vest_2_NH",
			"CUP_H_RUS_ZSH_Shield_Up",
			"ItemMap",
			"ItemCompass",
			"ItemWatch"
		};
		respawnLinkedItems[]=
		{
			"Aircrew_vest_2_NH",
			"CUP_H_RUS_ZSH_Shield_Up",
			"ItemMap",
			"ItemCompass",
			"ItemWatch"
		};
	};
	
	class TWC_Modern_rus_sniper: TWC_Modern_rus_Base
	{
		scope=2;
		displayName="Sniper";
		uniformClass="CUP_U_O_RUS_Ghillie";
		backpack="rus_backpack_sniper";
		linkedItems[]=
		{
			"CUP_V_I_RACS_Carrier_Rig_wdl_3",
			"ItemMap",
			"ItemCompass",
			"ItemWatch"
		};
		respawnLinkedItems[]=
		{
			"CUP_V_I_RACS_Carrier_Rig_wdl_3",
			"ItemMap",
			"ItemCompass",
			"ItemWatch"
		};
		weapons[]=
		{
			"Throw",
			"ACE_MX2A",
			"Put",
			"CUP_srifle_SVD_NSPU"
		};
		respawnweapons[]=
		{
			"Throw",
			"ACE_MX2A",
			"Put",
			"CUP_srifle_SVD_NSPU"
		};
		magazines[]=
		{
			"SmokeShell",
			"CUP_10Rnd_762x54_SVD_M",
			"CUP_10Rnd_762x54_SVD_M",
			"CUP_10Rnd_762x54_SVD_M",
			"CUP_10Rnd_762x54_SVD_M",
			"CUP_10Rnd_762x54_SVD_M",
			"CUP_10Rnd_762x54_SVD_M",
			"ACE_10Rnd_762x54_Tracer_mag",
			"ACE_10Rnd_762x54_Tracer_mag",
			"ACE_10Rnd_762x54_Tracer_mag",
			"ACE_10Rnd_762x54_Tracer_mag",
			"ACE_10Rnd_762x54_Tracer_mag"
		};
		Respawnmagazines[]=
		{
			"SmokeShell",
			"CUP_10Rnd_762x54_SVD_M",
			"CUP_10Rnd_762x54_SVD_M",
			"CUP_10Rnd_762x54_SVD_M",
			"CUP_10Rnd_762x54_SVD_M",
			"CUP_10Rnd_762x54_SVD_M",
			"CUP_10Rnd_762x54_SVD_M",
			"ACE_10Rnd_762x54_Tracer_mag",
			"ACE_10Rnd_762x54_Tracer_mag",
			"ACE_10Rnd_762x54_Tracer_mag",
			"ACE_10Rnd_762x54_Tracer_mag",
			"ACE_10Rnd_762x54_Tracer_mag"
		};
	};
	
	class TWC_Modern_rus_sniper_d: TWC_Modern_rus_sniper
	{
		scope=2;
		editorSubcategory = "Men_twc_desert";
		vehicleClass="Men_twc_desert";
		uniformClass="U_I_FullGhillie_ard";
	};
	
	class TWC_Modern_rus_spotter: TWC_Modern_rus_Base
	{
		scope=2;
		displayName="Spotter @Sniper Team";
		uniformClass="CUP_U_O_RUS_Ghillie";
		backpack="rus_backpack_spotter";
		linkedItems[]=
		{
			"CUP_V_I_RACS_Carrier_Rig_wdl_3",
			"ItemcTab",
			"ItemMap",
			"ItemCompass",
			"ItemWatch"
		};
		respawnLinkedItems[]=
		{
			"CUP_V_I_RACS_Carrier_Rig_wdl_3",
			"ItemcTab",
			"ItemMap",
			"ItemCompass",
			"ItemWatch"
		};
		weapons[]=
		{
			"Throw",
			"Put",
			"CUP_SOFLAM",
			"CUP_arifle_AK74M_pso"
		};
		respawnweapons[]=
		{
			"Throw",
			"Put",
			"CUP_SOFLAM",
			"CUP_arifle_AK74M_pso"
		};
		magazines[]=
		{
			"SmokeShell",
			"CUP_20Rnd_545x39_AKSU_M",
			"CUP_20Rnd_545x39_AKSU_M",
			"CUP_20Rnd_545x39_AKSU_M",
			"CUP_20Rnd_545x39_AKSU_M",
			"CUP_20Rnd_545x39_AKSU_M",
			"CUP_20Rnd_545x39_AKSU_M",
			"CUP_20Rnd_545x39_AKSU_M",
			"CUP_20Rnd_545x39_AKSU_M",
			"CUP_20Rnd_545x39_AKSU_M",
			"CUP_20Rnd_545x39_AKSU_M"
		};
		Respawnmagazines[]=
		{
			"SmokeShell",
			"CUP_20Rnd_545x39_AKSU_M",
			"CUP_20Rnd_545x39_AKSU_M",
			"CUP_20Rnd_545x39_AKSU_M",
			"CUP_20Rnd_545x39_AKSU_M",
			"CUP_20Rnd_545x39_AKSU_M",
			"CUP_20Rnd_545x39_AKSU_M",
			"CUP_20Rnd_545x39_AKSU_M",
			"CUP_20Rnd_545x39_AKSU_M",
			"CUP_20Rnd_545x39_AKSU_M",
			"CUP_20Rnd_545x39_AKSU_M"
		};
		Items[]=
		{
			"ACE_Kestrel4500",
			"ACE_EarPlugs",
			"ACRE_PRC343",
			"ACRE_PRC152",
			"ACE_fieldDressing",
			"ACE_fieldDressing",
			"ACE_fieldDressing",
			"ACE_fieldDressing",
			"ACE_fieldDressing",
			"ACE_fieldDressing",
			"ACE_packingBandage",
			"ACE_packingBandage",
			"ACE_packingBandage",
			"ACE_packingBandage",
			"ACE_packingBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_quikclot",
			"ACE_quikclot",
			"ACE_morphine",
			"ACE_epinephrine",
			"ACE_tourniquet",
			"ACE_tourniquet",
			"ACE_MapTools"
		};
		respawnitems[]=
		{
			"ACE_Kestrel4500",
			"ACE_EarPlugs",
			"ACRE_PRC343",
			"ACRE_PRC152",
			"ACE_fieldDressing",
			"ACE_fieldDressing",
			"ACE_fieldDressing",
			"ACE_fieldDressing",
			"ACE_fieldDressing",
			"ACE_packingBandage",
			"ACE_packingBandage",
			"ACE_packingBandage",
			"ACE_packingBandage",
			"ACE_packingBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_quikclot",
			"ACE_quikclot",
			"ACE_morphine",
			"ACE_epinephrine",
			"ACE_tourniquet",
			"ACE_tourniquet"
		};
	};
	
	class TWC_Modern_rus_spotter_d: TWC_Modern_rus_spotter
	{
		scope=2;
		editorSubcategory = "Men_twc_desert";
		vehicleClass="Men_twc_desert";
		uniformClass="U_I_FullGhillie_ard";
	};
	
	class TWC_Modern_rus_sso_Base: TWC_Modern_rus_Base
	{
		scope=2;
		displayName="Rifleman";
		faction="rus_units_sso";
		editorSubcategory = "Men_twc_woodland";
		vehicleClass="Men_twc_woodland";
		icon="iconMan";
		nakedUniform="U_BasicBody";
		uniformClass="CUP_U_CRYE_MCAM_RUS2_Roll";
		twc_radioType = "ACRE_PRC343";
		backpack="rus_scoutpack_rifleman";
		twc_radioChannel = 2;
		linkedItems[]=
		{
			"CUP_V_B_Ciras_Olive",
			"CUP_H_OpsCore_Spray_SF",
			"ItemMap",
			"ItemCompass",
			"ItemWatch"
		};
		respawnLinkedItems[]=
		{
			"CUP_V_B_Ciras_Olive",
			"CUP_H_OpsCore_Spray_SF",
			"ItemMap",
			"ItemCompass",
			"ItemWatch"
		};
		weapons[]=
		{
			"Throw",
			"Put",
			"UK3CB_BAF_L131A1",
			"CUP_arifle_AK74M_kobra"
		};
		respawnweapons[]=
		{
			"Throw",
			"Put",
			"UK3CB_BAF_L131A1",
			"CUP_arifle_AK74M_kobra"
		};
		magazines[]=
		{
			"SmokeShell",
			"CUP_HandGrenade_RGD5",
			"UK3CB_BAF_9_17Rnd",
			"UK3CB_BAF_9_17Rnd",
			"CUP_30Rnd_545x39_AK74M_M",
			"CUP_30Rnd_545x39_AK74M_M",
			"CUP_30Rnd_545x39_AK74M_M",
			"CUP_30Rnd_545x39_AK74M_M",
			"CUP_30Rnd_545x39_AK74M_M",
			"CUP_30Rnd_545x39_AK74M_M",
			"CUP_30Rnd_545x39_AK74M_M",
			"CUP_30Rnd_545x39_AK74M_M",
			"CUP_30Rnd_545x39_AK74M_M",
			"CUP_30Rnd_545x39_AK74M_M",
			"CUP_30Rnd_545x39_AK74M_M",
			"CUP_30Rnd_545x39_AK74M_M",
			"CUP_30Rnd_545x39_AK74M_M"
		};
		Respawnmagazines[]=
		{
			"SmokeShell",
			"CUP_HandGrenade_RGD5",
			"UK3CB_BAF_9_17Rnd",
			"UK3CB_BAF_9_17Rnd",
			"CUP_30Rnd_545x39_AK74M_M",
			"CUP_30Rnd_545x39_AK74M_M",
			"CUP_30Rnd_545x39_AK74M_M",
			"CUP_30Rnd_545x39_AK74M_M",
			"CUP_30Rnd_545x39_AK74M_M",
			"CUP_30Rnd_545x39_AK74M_M",
			"CUP_30Rnd_545x39_AK74M_M",
			"CUP_30Rnd_545x39_AK74M_M",
			"CUP_30Rnd_545x39_AK74M_M",
			"CUP_30Rnd_545x39_AK74M_M",
			"CUP_30Rnd_545x39_AK74M_M",
			"CUP_30Rnd_545x39_AK74M_M",
			"CUP_30Rnd_545x39_AK74M_M"
		};
	};
	
	class TWC_Modern_rus_sso_Pointman: TWC_Modern_rus_sso_Base
	{
		displayName="Pointman";
		weapons[]=
		{
			"Throw",
			"Put",
			"UK3CB_BAF_L131A1",
			"CUP_arifle_AK74M_kobra"
		};
		respawnweapons[]=
		{
			"Throw",
			"Put",
			"UK3CB_BAF_L131A1",
			"CUP_arifle_AK74M_kobra"
		};
	};
	
	class TWC_Modern_rus_sso_Squadleader: TWC_Modern_rus_sso_Base
	{
		backpack="TWC_Backpack_USMC2000_Sectionleader";
		displayName="Squad Leader @SSO Infantry";
		twc_loadoutstring = "SL";
		linkedItems[]=
		{
			"CUP_V_B_Ciras_Olive",
			"CUP_H_OpsCore_Spray_SF",
			"itemCTAB",
			"ItemMap",
			"ItemCompass",
			"ItemWatch"
		};
		respawnLinkedItems[]=
		{
			"CUP_V_B_Ciras_Olive",
			"CUP_H_OpsCore_Spray_SF",
			"itemCTAB",
			"ItemMap",
			"ItemCompass",
			"ItemWatch"
		};
		weapons[]=
		{
			"Throw",
			"Put",
			"UK3CB_BAF_Soflam_Laserdesignator",
			"UK3CB_BAF_L131A1",
			"CUP_arifle_AK74M_kobra"
		};
		respawnweapons[]=
		{
			"Throw",
			"Put",
			"UK3CB_BAF_Soflam_Laserdesignator",
			"UK3CB_BAF_L131A1",
			"CUP_arifle_AK74M_kobra"
		};
		magazines[]=
		{
			"SmokeShell",
			"UK3CB_BAF_9_17Rnd",
			"UK3CB_BAF_9_17Rnd",
			"Laserbatteries",
			"CUP_30Rnd_545x39_AK74M_M",
			"CUP_30Rnd_545x39_AK74M_M",
			"CUP_30Rnd_545x39_AK74M_M",
			"CUP_30Rnd_545x39_AK74M_M",
			"CUP_30Rnd_545x39_AK74M_M",
			"CUP_30Rnd_545x39_AK74M_M",
			"CUP_30Rnd_545x39_AK74M_M",
			"CUP_30Rnd_545x39_AK74M_M",
			"CUP_30Rnd_545x39_AK74M_M",
			"CUP_30Rnd_545x39_AK74M_M",
			"CUP_30Rnd_545x39_AK74M_M",
			"CUP_30Rnd_545x39_AK74M_M",
			"CUP_30Rnd_545x39_AK74M_M"
		};
		Respawnmagazines[]=
		{
			"SmokeShell",
			"UK3CB_BAF_9_17Rnd",
			"UK3CB_BAF_9_17Rnd",
			"Laserbatteries",
			"CUP_30Rnd_545x39_AK74M_M",
			"CUP_30Rnd_545x39_AK74M_M",
			"CUP_30Rnd_545x39_AK74M_M",
			"CUP_30Rnd_545x39_AK74M_M",
			"CUP_30Rnd_545x39_AK74M_M",
			"CUP_30Rnd_545x39_AK74M_M",
			"CUP_30Rnd_545x39_AK74M_M",
			"CUP_30Rnd_545x39_AK74M_M",
			"CUP_30Rnd_545x39_AK74M_M",
			"CUP_30Rnd_545x39_AK74M_M",
			"CUP_30Rnd_545x39_AK74M_M",
			"CUP_30Rnd_545x39_AK74M_M",
			"CUP_30Rnd_545x39_AK74M_M"
		};
	};
	
	class TWC_Modern_rus_sso_2ic: TWC_Modern_rus_sso_Base
	{
		backpack="rus_sso_backpack_2ic";
		displayName="2IC";
		weapons[]=
		{
			"Throw",
			"Put",
			"CUP_SOFLAM",
			"UK3CB_BAF_L131A1",
			"CUP_arifle_AK74M_kobra"
		};
		respawnweapons[]=
		{
			"Throw",
			"Put",
			"CUP_SOFLAM",
			"UK3CB_BAF_L131A1",
			"CUP_arifle_AK74M_kobra"
		};
	};
	
	class TWC_Modern_rus_sso_Marksman: TWC_Modern_rus_sso_Base
	{
		backpack="";
		displayName="Marksman";
		weapons[]=
		{
			"Throw",
			"Put",
			"UK3CB_BAF_L131A1",
			"CUP_srifle_SVD_pso"
		};
		respawnweapons[]=
		{
			"Throw",
			"Put",
			"UK3CB_BAF_L131A1",
			"CUP_srifle_SVD_pso"
		};
		magazines[]=
		{
			"SmokeShell",
			"UK3CB_BAF_9_17Rnd",
			"UK3CB_BAF_9_17Rnd",
			"CUP_10Rnd_762x54_SVD_M",
			"CUP_10Rnd_762x54_SVD_M",
			"CUP_10Rnd_762x54_SVD_M",
			"CUP_10Rnd_762x54_SVD_M",
			"CUP_10Rnd_762x54_SVD_M",
			"CUP_10Rnd_762x54_SVD_M",
			"CUP_10Rnd_762x54_SVD_M",
			"CUP_10Rnd_762x54_SVD_M",
			"CUP_10Rnd_762x54_SVD_M",
			"CUP_10Rnd_762x54_SVD_M",
			"CUP_10Rnd_762x54_SVD_M"
		};
		Respawnmagazines[]=
		{
			"SmokeShell",
			"UK3CB_BAF_9_17Rnd",
			"UK3CB_BAF_9_17Rnd",
			"CUP_10Rnd_762x54_SVD_M",
			"CUP_10Rnd_762x54_SVD_M",
			"CUP_10Rnd_762x54_SVD_M",
			"CUP_10Rnd_762x54_SVD_M",
			"CUP_10Rnd_762x54_SVD_M",
			"CUP_10Rnd_762x54_SVD_M",
			"CUP_10Rnd_762x54_SVD_M",
			"CUP_10Rnd_762x54_SVD_M",
			"CUP_10Rnd_762x54_SVD_M",
			"CUP_10Rnd_762x54_SVD_M",
			"CUP_10Rnd_762x54_SVD_M"
		};
	};
	
	class TWC_Modern_rus_sso_MG: TWC_Modern_rus_sso_Base
	{
		backpack="rus_backpack_MG";
		displayName="Machinegunner";
		weapons[]=
		{
			"Throw",
			"Put",
			"UK3CB_BAF_L131A1",
			"CUP_lmg_Pecheneg_PScope"
		};
		respawnweapons[]=
		{
			"Throw",
			"Put",
			"UK3CB_BAF_L131A1",
			"CUP_lmg_Pecheneg_PScope"
		};
		magazines[]=
		{
			"SmokeShell",
			"UK3CB_BAF_9_17Rnd",
			"UK3CB_BAF_9_17Rnd",
			"CUP_100Rnd_TE4_LRT4_762x54_PK_Tracer_Green_M",
			"CUP_100Rnd_TE4_LRT4_762x54_PK_Tracer_Green_M",
			"CUP_100Rnd_TE4_LRT4_762x54_PK_Tracer_Green_M"
		};
		Respawnmagazines[]=
		{
			"SmokeShell",
			"UK3CB_BAF_9_17Rnd",
			"UK3CB_BAF_9_17Rnd",
			"CUP_100Rnd_TE4_LRT4_762x54_PK_Tracer_Green_M",
			"CUP_100Rnd_TE4_LRT4_762x54_PK_Tracer_Green_M",
			"CUP_100Rnd_TE4_LRT4_762x54_PK_Tracer_Green_M"
		};
	};
	
	class TWC_Modern_rus_sso_MG_assistant: TWC_Modern_rus_sso_Base
	{
		backpack="rus_backpack_MG";
		displayName="MG Assistant";
		twc_loadoutstring = "mgass";
	};
	
	class TWC_Modern_rus_sso_medic: TWC_Modern_rus_sso_Base
	{
		backpack="rus_backpack_medic";
		displayName="Medic";
		attendant = 1;
	};
	