//COIN, ARCTIC
//Section
class TWC_Infantry_ColdWar_COIN_Arctic_Rifleman: TWC_Infantry_ColdWar_Regular_Arctic_Rifleman
{
	CATEGORY(TWC_Infantry_COIN_Arctic)
	linkedItems[]=
	{
		"SP_P58_FightingOrderNBC",
		"UK3CB_BAF_H_Beret_WG",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
	respawnLinkedItems[]=
	{
		"SP_P58_FightingOrderNBC",
		"UK3CB_BAF_H_Beret_WG",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
	weapons[]=
	{
		"UK3CB_BAF_L1A1_Wood",
		"Throw",
		"Put"
	};
	respawnweapons[]=
	{
		"UK3CB_BAF_L1A1_Wood",
		"Throw",
		"Put"
	};
	magazines[]=
	{
		MAG_7("UK3CB_BAF_762_20Rnd"),
		MAG_2("CUP_HandGrenade_L109A2_HE"),
		"SmokeShell"
	};
	respawnmagazines[]=
	{
		MAG_7("UK3CB_BAF_762_20Rnd"),
		MAG_2("CUP_HandGrenade_L109A2_HE"),
		"SmokeShell"
	};
};
class TWC_Infantry_ColdWar_COIN_Arctic_Rifleman_SUIT: TWC_Infantry_ColdWar_Regular_Arctic_Rifleman_SUIT
{
	CATEGORY(TWC_Infantry_COIN_Arctic)
	linkedItems[]=
	{
		"SP_P58_FightingOrderNBC",
		"UK3CB_BAF_H_Beret_WG",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
	respawnLinkedItems[]=
	{
		"SP_P58_FightingOrderNBC",
		"UK3CB_BAF_H_Beret_WG",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
	weapons[]=
	{
		"TWC_L1A1_SUIT",
		"Throw",
		"Put"
	};
	respawnweapons[]=
	{
		"TWC_L1A1_SUIT",
		"Throw",
		"Put"
	};
	magazines[]=
	{
		MAG_7("UK3CB_BAF_762_20Rnd"),
		MAG_2("CUP_HandGrenade_L109A2_HE"),
		"SmokeShell"
	};
	respawnmagazines[]=
	{
		MAG_7("UK3CB_BAF_762_20Rnd"),
		MAG_2("CUP_HandGrenade_L109A2_HE"),
		"SmokeShell"
	};
};
class TWC_Infantry_ColdWar_COIN_Arctic_SectionCommander: TWC_Infantry_ColdWar_Regular_Arctic_SectionCommander
{
	CATEGORY(TWC_Infantry_COIN_Arctic)
	backpack = "TWC_Backpack_ColdWar_COIN_SectionCommander";
	linkedItems[]=
	{
		"SP_P58_FightingOrderNBC",
		"UK3CB_BAF_H_Beret_WG",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
	respawnLinkedItems[]=
	{
		"SP_P58_FightingOrderNBC",
		"UK3CB_BAF_H_Beret_WG",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
};
class TWC_Infantry_ColdWar_COIN_Arctic_2iC: TWC_Infantry_ColdWar_Regular_Arctic_2iC
{
	CATEGORY(TWC_Infantry_COIN_Arctic)
	backpack = "TWC_Backpack_ColdWar_COIN_2iC";
	linkedItems[]=
	{
		"SP_P58_FightingOrderNBC",
		"UK3CB_BAF_H_Beret_WG",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
	respawnLinkedItems[]=
	{
		"SP_P58_FightingOrderNBC",
		"UK3CB_BAF_H_Beret_WG",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
};
class TWC_Infantry_ColdWar_COIN_Arctic_MG: TWC_Infantry_ColdWar_Regular_Arctic_MG
{
	CATEGORY(TWC_Infantry_COIN_Arctic)
	linkedItems[]=
	{
		"SP_P58_FightingOrderNBC",
		"UK3CB_BAF_H_Beret_WG",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
	respawnLinkedItems[]=
	{
		"SP_P58_FightingOrderNBC",
		"UK3CB_BAF_H_Beret_WG",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
	weapons[]=
	{
		"sp_l4_lmg",
		"Throw",
		"Put"
	};
	respawnweapons[]=
	{
		"sp_l4_lmg",
		"Throw",
		"Put"
	};
	magazines[]=
	{
		MAG_10("SP_30Rnd_762_L4"),
		"SmokeShell"
	};
	respawnmagazines[]=
	{
		MAG_10("SP_30Rnd_762_L4"),
		"SmokeShell"
	};
};
class TWC_Infantry_ColdWar_COIN_Arctic_ASSMG: TWC_Infantry_ColdWar_Regular_Arctic_ASSMG
{
	CATEGORY(TWC_Infantry_COIN_Arctic)
	backpack = "TWC_Backpack_ColdWar_COIN_ASSMG";
	linkedItems[]=
	{
		"SP_P58_FightingOrderNBC",
		"UK3CB_BAF_H_Beret_WG",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
	respawnLinkedItems[]=
	{
		"SP_P58_FightingOrderNBC",
		"UK3CB_BAF_H_Beret_WG",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
};

//Platoon Command
class TWC_Infantry_ColdWar_COIN_Arctic_Platoon_Commander: TWC_Infantry_ColdWar_Regular_Arctic_Platoon_Commander
{
	CATEGORY(TWC_Infantry_COIN_Arctic)
	backpack = "TWC_Backpack_ColdWar_COIN_Platoon_Commander";
	linkedItems[]=
	{
		"SP_P58_FightingOrderNBC",
		"UK3CB_BAF_H_Beret_WG",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
	respawnLinkedItems[]=
	{
		"SP_P58_FightingOrderNBC",
		"UK3CB_BAF_H_Beret_WG",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
};
class TWC_Infantry_ColdWar_COIN_Arctic_Platoon_Sergeant: TWC_Infantry_ColdWar_Regular_Arctic_Platoon_Sergeant
{
	CATEGORY(TWC_Infantry_COIN_Arctic)
	backpack = "TWC_Backpack_ColdWar_COIN_Platoon_Sergeant";
	linkedItems[]=
	{
		"SP_P58_FightingOrderNBC",
		"UK3CB_BAF_H_Beret_WG",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
	respawnLinkedItems[]=
	{
		"SP_P58_FightingOrderNBC",
		"UK3CB_BAF_H_Beret_WG",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
};
class TWC_Infantry_ColdWar_COIN_Arctic_Platoon_Medic: TWC_Infantry_ColdWar_Regular_Arctic_Platoon_Medic
{
	CATEGORY(TWC_Infantry_COIN_Arctic)
	backpack = "TWC_Backpack_ColdWar_COIN_Platoon_Medic";
	linkedItems[]=
	{
		"SP_P58_FightingOrderNBC",
		"UK3CB_BAF_H_Beret_WG",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
	respawnLinkedItems[]=
	{
		"SP_P58_FightingOrderNBC",
		"UK3CB_BAF_H_Beret_WG",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
};
class TWC_Infantry_ColdWar_COIN_Arctic_CSM: TWC_Infantry_ColdWar_Regular_Arctic_CSM
{
	CATEGORY(TWC_Infantry_COIN_Arctic)
	backpack = "TWC_Backpack_ColdWar_COIN_Platoon_Sergeant";
	linkedItems[]=
	{
		"SP_P58_FightingOrderNBC",
		"UK3CB_BAF_H_Beret_WG",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
	respawnLinkedItems[]=
	{
		"SP_P58_FightingOrderNBC",
		"UK3CB_BAF_H_Beret_WG",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
};

//Sniper Team
class TWC_Infantry_ColdWar_COIN_Arctic_Sniper: TWC_Infantry_ColdWar_Regular_Arctic_Sniper
{
	CATEGORY(TWC_Infantry_COIN_Arctic)
	linkedItems[]=
	{
		"SP_P58_FightingOrderNBC",
		"UK3CB_BAF_H_Beret_WG",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
	respawnLinkedItems[]=
	{
		"SP_P58_FightingOrderNBC",
		"UK3CB_BAF_H_Beret_WG",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
};
class TWC_Infantry_ColdWar_COIN_Arctic_Spotter: TWC_Infantry_ColdWar_Regular_Arctic_Spotter
{
	CATEGORY(TWC_Infantry_COIN_Arctic)
	linkedItems[]=
	{
		"SP_P58_FightingOrderNBC",
		"UK3CB_BAF_H_Beret_WG",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
	respawnLinkedItems[]=
	{
		"SP_P58_FightingOrderNBC",
		"UK3CB_BAF_H_Beret_WG",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
};

//Artillery Crew
class TWC_Infantry_ColdWar_COIN_Arctic_Artillery_Commander: TWC_Infantry_ColdWar_Regular_Arctic_Artillery_Commander
{
	CATEGORY(TWC_Infantry_COIN_Arctic)
	linkedItems[]=
	{
		"SP_P58_FightingOrderNBC",
		"UK3CB_BAF_H_Beret_WG",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
	respawnLinkedItems[]=
	{
		"SP_P58_FightingOrderNBC",
		"UK3CB_BAF_H_Beret_WG",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
};
class TWC_Infantry_ColdWar_COIN_Arctic_Artillery_Crew: TWC_Infantry_ColdWar_Regular_Arctic_Artillery_Crew
{
	CATEGORY(TWC_Infantry_COIN_Arctic)
	linkedItems[]=
	{
		"SP_P58_FightingOrderNBC",
		"UK3CB_BAF_H_Beret_WG",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
	respawnLinkedItems[]=
	{
		"SP_P58_FightingOrderNBC",
		"UK3CB_BAF_H_Beret_WG",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
};
class TWC_Infantry_ColdWar_COIN_Arctic_FO: TWC_Infantry_ColdWar_Regular_Arctic_FO
{
	CATEGORY(TWC_Infantry_COIN_Arctic)
	linkedItems[]=
	{
		"SP_P58_FightingOrderNBC",
		"UK3CB_BAF_H_Beret_WG",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
	respawnLinkedItems[]=
	{
		"SP_P58_FightingOrderNBC",
		"UK3CB_BAF_H_Beret_WG",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
};

//Aircraft
class TWC_Infantry_ColdWar_COIN_Arctic_FAC: TWC_Infantry_ColdWar_Regular_Arctic_FAC
{
	CATEGORY(TWC_Infantry_COIN_Arctic)
	linkedItems[]=
	{
		"SP_P58_FightingOrderNBC",
		"UK3CB_BAF_H_Beret_WG",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
	respawnLinkedItems[]=
	{
		"SP_P58_FightingOrderNBC",
		"UK3CB_BAF_H_Beret_WG",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
};