//COIN, TROPIC
//Section
class TWC_Infantry_ColdWar_COIN_Tropic_Rifleman: TWC_Infantry_ColdWar_Regular_Tropic_Rifleman
{
	CATEGORY(TWC_Infantry_COIN_Tropic)
	linkedItems[]=
	{
		"sp_webbing_58pattern_fightingorder_alt",
		"H_Booniehat_oli",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
	respawnLinkedItems[]=
	{
		"sp_webbing_58pattern_fightingorder_alt",
		"H_Booniehat_oli",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
	weapons[]=
	{
		"UK3CB_BAF_L1A1_Wood",
		"Throw",
		"Put"
	};
	respawnweapons[]=
	{
		"UK3CB_BAF_L1A1_Wood",
		"Throw",
		"Put"
	};
	magazines[]=
	{
		MAG_7("UK3CB_BAF_762_20Rnd"),
		MAG_2("CUP_HandGrenade_L109A2_HE"),
		"SmokeShell"
	};
	respawnmagazines[]=
	{
		MAG_7("UK3CB_BAF_762_20Rnd"),
		MAG_2("CUP_HandGrenade_L109A2_HE"),
		"SmokeShell"
	};
};
class TWC_Infantry_ColdWar_COIN_Tropic_Rifleman_SUIT: TWC_Infantry_ColdWar_Regular_Tropic_Rifleman_SUIT
{
	CATEGORY(TWC_Infantry_COIN_Tropic)
	linkedItems[]=
	{
		"sp_webbing_58pattern_fightingorder_alt",
		"H_Booniehat_oli",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
	respawnLinkedItems[]=
	{
		"sp_webbing_58pattern_fightingorder_alt",
		"H_Booniehat_oli",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
	weapons[]=
	{
		"TWC_L1A1_SUIT",
		"Throw",
		"Put"
	};
	respawnweapons[]=
	{
		"TWC_L1A1_SUIT",
		"Throw",
		"Put"
	};
	magazines[]=
	{
		MAG_7("UK3CB_BAF_762_20Rnd"),
		MAG_2("CUP_HandGrenade_L109A2_HE"),
		"SmokeShell"
	};
	respawnmagazines[]=
	{
		MAG_7("UK3CB_BAF_762_20Rnd"),
		MAG_2("CUP_HandGrenade_L109A2_HE"),
		"SmokeShell"
	};
};
class TWC_Infantry_ColdWar_COIN_Tropic_SectionCommander: TWC_Infantry_ColdWar_Regular_Tropic_SectionCommander
{
	CATEGORY(TWC_Infantry_COIN_Tropic)
	backpack = "TWC_Backpack_ColdWar_COIN_SectionCommander";
	linkedItems[]=
	{
		"sp_webbing_58pattern_fightingorder_alt",
		"H_Booniehat_oli",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
	respawnLinkedItems[]=
	{
		"sp_webbing_58pattern_fightingorder_alt",
		"H_Booniehat_oli",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
};
class TWC_Infantry_ColdWar_COIN_Tropic_2iC: TWC_Infantry_ColdWar_Regular_Tropic_2iC
{
	CATEGORY(TWC_Infantry_COIN_Tropic)
	backpack = "TWC_Backpack_ColdWar_COIN_2iC";
	linkedItems[]=
	{
		"sp_webbing_58pattern_fightingorder_alt",
		"H_Booniehat_oli",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
	respawnLinkedItems[]=
	{
		"sp_webbing_58pattern_fightingorder_alt",
		"H_Booniehat_oli",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
};
class TWC_Infantry_ColdWar_COIN_Tropic_MG: TWC_Infantry_ColdWar_Regular_Tropic_MG
{
	CATEGORY(TWC_Infantry_COIN_Tropic)
	linkedItems[]=
	{
		"sp_webbing_58pattern_fightingorder_alt",
		"H_Booniehat_oli",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
	respawnLinkedItems[]=
	{
		"sp_webbing_58pattern_fightingorder_alt",
		"H_Booniehat_oli",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
	weapons[]=
	{
		"sp_l4_lmg",
		"Throw",
		"Put"
	};
	respawnweapons[]=
	{
		"sp_l4_lmg",
		"Throw",
		"Put"
	};
	magazines[]=
	{
		MAG_10("SP_30Rnd_762_L4"),
		"SmokeShell"
	};
	respawnmagazines[]=
	{
		MAG_10("SP_30Rnd_762_L4"),
		"SmokeShell"
	};
};
class TWC_Infantry_ColdWar_COIN_Tropic_ASSMG: TWC_Infantry_ColdWar_Regular_Tropic_ASSMG
{
	CATEGORY(TWC_Infantry_COIN_Tropic)
	backpack = "TWC_Backpack_ColdWar_COIN_ASSMG";
	linkedItems[]=
	{
		"sp_webbing_58pattern_fightingorder_alt",
		"H_Booniehat_oli",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
	respawnLinkedItems[]=
	{
		"sp_webbing_58pattern_fightingorder_alt",
		"H_Booniehat_oli",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
};

//Platoon Command
class TWC_Infantry_ColdWar_COIN_Tropic_Platoon_Commander: TWC_Infantry_ColdWar_Regular_Tropic_Platoon_Commander
{
	CATEGORY(TWC_Infantry_COIN_Tropic)
	backpack = "TWC_Backpack_ColdWar_COIN_Platoon_Commander";
	linkedItems[]=
	{
		"sp_webbing_58pattern_fightingorder_alt",
		"H_Booniehat_oli",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
	respawnLinkedItems[]=
	{
		"sp_webbing_58pattern_fightingorder_alt",
		"H_Booniehat_oli",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
};
class TWC_Infantry_ColdWar_COIN_Tropic_Platoon_Sergeant: TWC_Infantry_ColdWar_Regular_Tropic_Platoon_Sergeant
{
	CATEGORY(TWC_Infantry_COIN_Tropic)
	backpack = "TWC_Backpack_ColdWar_COIN_Platoon_Sergeant";
	linkedItems[]=
	{
		"sp_webbing_58pattern_fightingorder_alt",
		"H_Booniehat_oli",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
	respawnLinkedItems[]=
	{
		"sp_webbing_58pattern_fightingorder_alt",
		"H_Booniehat_oli",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
};
class TWC_Infantry_ColdWar_COIN_Tropic_Platoon_Medic: TWC_Infantry_ColdWar_Regular_Tropic_Platoon_Medic
{
	CATEGORY(TWC_Infantry_COIN_Tropic)
	backpack = "TWC_Backpack_ColdWar_COIN_Platoon_Medic";
	linkedItems[]=
	{
		"sp_webbing_58pattern_fightingorder_alt",
		"H_Booniehat_oli",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
	respawnLinkedItems[]=
	{
		"sp_webbing_58pattern_fightingorder_alt",
		"H_Booniehat_oli",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
};
class TWC_Infantry_ColdWar_COIN_Tropic_CSM: TWC_Infantry_ColdWar_Regular_Tropic_CSM
{
	CATEGORY(TWC_Infantry_COIN_Tropic)
	backpack = "TWC_Backpack_ColdWar_COIN_Platoon_Sergeant";
	linkedItems[]=
	{
		"sp_webbing_58pattern_fightingorder_alt",
		"H_Booniehat_oli",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
	respawnLinkedItems[]=
	{
		"sp_webbing_58pattern_fightingorder_alt",
		"H_Booniehat_oli",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
};

//Company
class TWC_Infantry_ColdWar_COIN_Tropic_Company_Commander: TWC_Infantry_ColdWar_Regular_Tropic_Company_Commander
{
	CATEGORY(TWC_Infantry_COIN_Tropic)
	backpack = "TWC_Backpack_ColdWar_COIN_Platoon_Commander";
	linkedItems[] =
	{
		"sp_webbing_58pattern_fightingorder_alt",
		"H_Booniehat_oli",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
	respawnLinkedItems[] =
	{
		"sp_webbing_58pattern_fightingorder_alt",
		"H_Booniehat_oli",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
};
class TWC_Infantry_ColdWar_COIN_Tropic_Company_2iC: TWC_Infantry_ColdWar_Regular_Tropic_Company_2iC
{
	CATEGORY(TWC_Infantry_COIN_Tropic)
	backpack = "TWC_Backpack_ColdWar_COIN_Platoon_Commander";
	linkedItems[] =
	{
		"sp_webbing_58pattern_fightingorder_alt",
		"H_Booniehat_oli",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
	respawnLinkedItems[] =
	{
		"sp_webbing_58pattern_fightingorder_alt",
		"H_Booniehat_oli",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
};
class TWC_Infantry_ColdWar_COIN_Tropic_Company_Sergeant: TWC_Infantry_ColdWar_Regular_Tropic_Company_Sergeant
{
	CATEGORY(TWC_Infantry_COIN_Tropic)
	backpack = "TWC_Backpack_ColdWar_COIN_Platoon_Sergeant";
	linkedItems[] =
	{
		"sp_webbing_58pattern_fightingorder_alt",
		"H_Booniehat_oli",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
	respawnLinkedItems[] =
	{
		"sp_webbing_58pattern_fightingorder_alt",
		"H_Booniehat_oli",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
};

//Sniper Team
class TWC_Infantry_ColdWar_COIN_Tropic_Sniper: TWC_Infantry_ColdWar_Regular_Tropic_Sniper
{
	CATEGORY(TWC_Infantry_COIN_Tropic)
	linkedItems[]=
	{
		"sp_webbing_58pattern_fightingorder_alt",
		"H_Booniehat_oli",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
	respawnLinkedItems[]=
	{
		"sp_webbing_58pattern_fightingorder_alt",
		"H_Booniehat_oli",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
};
class TWC_Infantry_ColdWar_COIN_Tropic_Spotter: TWC_Infantry_ColdWar_Regular_Tropic_Spotter
{
	CATEGORY(TWC_Infantry_COIN_Tropic)
	linkedItems[]=
	{
		"sp_webbing_58pattern_fightingorder_alt",
		"H_Booniehat_oli",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
	respawnLinkedItems[]=
	{
		"sp_webbing_58pattern_fightingorder_alt",
		"H_Booniehat_oli",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
};

//Artillery Crew
class TWC_Infantry_ColdWar_COIN_Tropic_Artillery_Commander: TWC_Infantry_ColdWar_Regular_Tropic_Artillery_Commander
{
	CATEGORY(TWC_Infantry_COIN_Tropic)
	linkedItems[]=
	{
		"sp_webbing_58pattern_fightingorder_alt",
		"H_Booniehat_oli",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
	respawnLinkedItems[]=
	{
		"sp_webbing_58pattern_fightingorder_alt",
		"H_Booniehat_oli",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
};
class TWC_Infantry_ColdWar_COIN_Tropic_Artillery_Crew: TWC_Infantry_ColdWar_Regular_Tropic_Artillery_Crew
{
	CATEGORY(TWC_Infantry_COIN_Tropic)
	linkedItems[]=
	{
		"sp_webbing_58pattern_fightingorder_alt",
		"H_Booniehat_oli",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
	respawnLinkedItems[]=
	{
		"sp_webbing_58pattern_fightingorder_alt",
		"H_Booniehat_oli",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
};
class TWC_Infantry_ColdWar_COIN_Tropic_FO: TWC_Infantry_ColdWar_Regular_Tropic_FO
{
	CATEGORY(TWC_Infantry_COIN_Tropic)
	linkedItems[]=
	{
		"sp_webbing_58pattern_fightingorder_alt",
		"H_Booniehat_oli",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
	respawnLinkedItems[]=
	{
		"sp_webbing_58pattern_fightingorder_alt",
		"H_Booniehat_oli",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
};

//Aircraft
class TWC_Infantry_ColdWar_COIN_Tropic_FAC: TWC_Infantry_ColdWar_Regular_Tropic_FAC
{
	CATEGORY(TWC_Infantry_COIN_Tropic)
	linkedItems[]=
	{
		"sp_webbing_58pattern_fightingorder_alt",
		"H_Booniehat_oli",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
	respawnLinkedItems[]=
	{
		"sp_webbing_58pattern_fightingorder_alt",
		"H_Booniehat_oli",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
};