//COIN, WOODLAND
//Section
class TWC_Infantry_ColdWar_COIN_Woodland_Rifleman: TWC_Infantry_ColdWar_Regular_Woodland_Rifleman
{
	CATEGORY(TWC_Infantry_COIN_Woodland)
	uniformClass="UK3CB_BAF_U_JumperUniform_Plain";
	linkedItems[]=
	{
		"CUP_V_CDF_6B3_1_Green",
		"UK3CB_BAF_H_Beret_Rifles",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
	respawnLinkedItems[]=
	{
		"CUP_V_CDF_6B3_1_Green",
		"UK3CB_BAF_H_Beret_Rifles",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
	weapons[]=
	{
		"UK3CB_BAF_L1A1_Wood",
		"Throw",
		"Put"
	};
	respawnweapons[]=
	{
		"UK3CB_BAF_L1A1_Wood",
		"Throw",
		"Put"
	};
	magazines[]=
	{
		MAG_7("UK3CB_BAF_762_20Rnd"),
		MAG_2("CUP_HandGrenade_L109A2_HE"),
		"SmokeShell"
	};
	respawnmagazines[]=
	{
		MAG_7("UK3CB_BAF_762_20Rnd"),
		MAG_2("CUP_HandGrenade_L109A2_HE"),
		"SmokeShell"
	};
};
class TWC_Infantry_ColdWar_COIN_Woodland_Rifleman_SUIT: TWC_Infantry_ColdWar_Regular_Woodland_Rifleman_SUIT
{
	CATEGORY(TWC_Infantry_COIN_Woodland)
	uniformClass="UK3CB_BAF_U_JumperUniform_Plain";
	linkedItems[]=
	{
		"CUP_V_CDF_6B3_1_Green",
		"UK3CB_BAF_H_Beret_Rifles",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
	respawnLinkedItems[]=
	{
		"CUP_V_CDF_6B3_1_Green",
		"UK3CB_BAF_H_Beret_Rifles",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
	weapons[]=
	{
		"TWC_L1A1_SUIT",
		"Throw",
		"Put"
	};
	respawnweapons[]=
	{
		"TWC_L1A1_SUIT",
		"Throw",
		"Put"
	};
	magazines[]=
	{
		MAG_7("UK3CB_BAF_762_20Rnd"),
		MAG_2("CUP_HandGrenade_L109A2_HE"),
		"SmokeShell"
	};
	respawnmagazines[]=
	{
		MAG_7("UK3CB_BAF_762_20Rnd"),
		MAG_2("CUP_HandGrenade_L109A2_HE"),
		"SmokeShell"
	};
};
class TWC_Infantry_ColdWar_COIN_Woodland_SectionCommander: TWC_Infantry_ColdWar_Regular_Woodland_SectionCommander
{
	CATEGORY(TWC_Infantry_COIN_Woodland)
	uniformClass="UK3CB_BAF_U_JumperUniform_Plain";
	backpack = "TWC_Backpack_ColdWar_COIN_SectionCommander";
	linkedItems[]=
	{
		"CUP_V_CDF_6B3_1_Green",
		"UK3CB_BAF_H_Beret_Rifles",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
	respawnLinkedItems[]=
	{
		"CUP_V_CDF_6B3_1_Green",
		"UK3CB_BAF_H_Beret_Rifles",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
};
class TWC_Infantry_ColdWar_COIN_Woodland_2iC: TWC_Infantry_ColdWar_Regular_Woodland_2iC
{
	CATEGORY(TWC_Infantry_COIN_Woodland)
	uniformClass="UK3CB_BAF_U_JumperUniform_Plain";
	backpack = "TWC_Backpack_ColdWar_COIN_2iC";
	linkedItems[]=
	{
		"CUP_V_CDF_6B3_1_Green",
		"UK3CB_BAF_H_Beret_Rifles",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
	respawnLinkedItems[]=
	{
		"CUP_V_CDF_6B3_1_Green",
		"UK3CB_BAF_H_Beret_Rifles",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
};
class TWC_Infantry_ColdWar_COIN_Woodland_MG: TWC_Infantry_ColdWar_Regular_Woodland_MG
{
	CATEGORY(TWC_Infantry_COIN_Woodland)
	uniformClass="UK3CB_BAF_U_JumperUniform_Plain";
	linkedItems[]=
	{
		"CUP_V_CDF_6B3_1_Green",
		"UK3CB_BAF_H_Beret_Rifles",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
	respawnLinkedItems[]=
	{
		"CUP_V_CDF_6B3_1_Green",
		"UK3CB_BAF_H_Beret_Rifles",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
	weapons[]=
	{
		"sp_l4_lmg",
		"Throw",
		"Put"
	};
	respawnweapons[]=
	{
		"sp_l4_lmg",
		"Throw",
		"Put"
	};
	magazines[]=
	{
		MAG_10("SP_30Rnd_762_L4"),
		"SmokeShell"
	};
	respawnmagazines[]=
	{
		MAG_10("SP_30Rnd_762_L4"),
		"SmokeShell"
	};
};
class TWC_Infantry_ColdWar_COIN_Woodland_ASSMG: TWC_Infantry_ColdWar_Regular_Woodland_ASSMG
{
	CATEGORY(TWC_Infantry_COIN_Woodland)
	uniformClass="UK3CB_BAF_U_JumperUniform_Plain";
	backpack = "TWC_Backpack_ColdWar_COIN_ASSMG";
	linkedItems[]=
	{
		"CUP_V_CDF_6B3_1_Green",
		"UK3CB_BAF_H_Beret_Rifles",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
	respawnLinkedItems[]=
	{
		"CUP_V_CDF_6B3_1_Green",
		"UK3CB_BAF_H_Beret_Rifles",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
};

//Platoon Command
class TWC_Infantry_ColdWar_COIN_Woodland_Platoon_Commander: TWC_Infantry_ColdWar_Regular_Woodland_Platoon_Commander
{
	CATEGORY(TWC_Infantry_COIN_Woodland)
	uniformClass="UK3CB_BAF_U_JumperUniform_Plain";
	backpack = "TWC_Backpack_ColdWar_COIN_Platoon_Commander";
	linkedItems[]=
	{
		"CUP_V_CDF_6B3_1_Green",
		"UK3CB_BAF_H_Beret_Rifles",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
	respawnLinkedItems[]=
	{
		"CUP_V_CDF_6B3_1_Green",
		"UK3CB_BAF_H_Beret_Rifles",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
};
class TWC_Infantry_ColdWar_COIN_Woodland_Platoon_Sergeant: TWC_Infantry_ColdWar_Regular_Woodland_Platoon_Sergeant
{
	CATEGORY(TWC_Infantry_COIN_Woodland)
	uniformClass="UK3CB_BAF_U_JumperUniform_Plain";
	backpack = "TWC_Backpack_ColdWar_COIN_Platoon_Sergeant";
	linkedItems[]=
	{
		"CUP_V_CDF_6B3_1_Green",
		"UK3CB_BAF_H_Beret_Rifles",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
	respawnLinkedItems[]=
	{
		"CUP_V_CDF_6B3_1_Green",
		"UK3CB_BAF_H_Beret_Rifles",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
};
class TWC_Infantry_ColdWar_COIN_Woodland_Platoon_Medic: TWC_Infantry_ColdWar_Regular_Woodland_Platoon_Medic
{
	CATEGORY(TWC_Infantry_COIN_Woodland)
	uniformClass="UK3CB_BAF_U_JumperUniform_Plain";
	backpack = "TWC_Backpack_ColdWar_COIN_Platoon_Medic";
	linkedItems[]=
	{
		"CUP_V_CDF_6B3_1_Green",
		"UK3CB_BAF_H_Beret_Rifles",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
	respawnLinkedItems[]=
	{
		"CUP_V_CDF_6B3_1_Green",
		"UK3CB_BAF_H_Beret_Rifles",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
};
class TWC_Infantry_ColdWar_COIN_Woodland_CSM: TWC_Infantry_ColdWar_Regular_Woodland_CSM
{
	CATEGORY(TWC_Infantry_COIN_Woodland)
	uniformClass="UK3CB_BAF_U_JumperUniform_Plain";
	backpack = "TWC_Backpack_ColdWar_COIN_Platoon_Sergeant";
	linkedItems[]=
	{
		"CUP_V_CDF_6B3_1_Green",
		"UK3CB_BAF_H_Beret_Rifles",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
	respawnLinkedItems[]=
	{
		"CUP_V_CDF_6B3_1_Green",
		"UK3CB_BAF_H_Beret_Rifles",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
};

//Sniper Team
class TWC_Infantry_ColdWar_COIN_Woodland_Sniper: TWC_Infantry_ColdWar_Regular_Woodland_Sniper
{
	CATEGORY(TWC_Infantry_COIN_Woodland)
	uniformClass="UK3CB_BAF_U_JumperUniform_Plain";
	linkedItems[]=
	{
		"CUP_V_CDF_6B3_1_Green",
		"UK3CB_BAF_H_Beret_Rifles",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
	respawnLinkedItems[]=
	{
		"CUP_V_CDF_6B3_1_Green",
		"UK3CB_BAF_H_Beret_Rifles",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
};
class TWC_Infantry_ColdWar_COIN_Woodland_Spotter: TWC_Infantry_ColdWar_Regular_Woodland_Spotter
{
	CATEGORY(TWC_Infantry_COIN_Woodland)
	uniformClass="UK3CB_BAF_U_JumperUniform_Plain";
	linkedItems[]=
	{
		"CUP_V_CDF_6B3_1_Green",
		"UK3CB_BAF_H_Beret_Rifles",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
	respawnLinkedItems[]=
	{
		"CUP_V_CDF_6B3_1_Green",
		"UK3CB_BAF_H_Beret_Rifles",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
};

//Artillery Crew
class TWC_Infantry_ColdWar_COIN_Woodland_Artillery_Commander: TWC_Infantry_ColdWar_Regular_Woodland_Artillery_Commander
{
	CATEGORY(TWC_Infantry_COIN_Woodland)
	uniformClass="UK3CB_BAF_U_JumperUniform_Plain";
	linkedItems[]=
	{
		"CUP_V_CDF_6B3_1_Green",
		"UK3CB_BAF_H_Beret_Rifles",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
	respawnLinkedItems[]=
	{
		"CUP_V_CDF_6B3_1_Green",
		"UK3CB_BAF_H_Beret_Rifles",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
};
class TWC_Infantry_ColdWar_COIN_Woodland_Artillery_Crew: TWC_Infantry_ColdWar_Regular_Woodland_Artillery_Crew
{
	CATEGORY(TWC_Infantry_COIN_Woodland)
	uniformClass="UK3CB_BAF_U_JumperUniform_Plain";
	linkedItems[]=
	{
		"CUP_V_CDF_6B3_1_Green",
		"UK3CB_BAF_H_Beret_Rifles",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
	respawnLinkedItems[]=
	{
		"CUP_V_CDF_6B3_1_Green",
		"UK3CB_BAF_H_Beret_Rifles",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
};
class TWC_Infantry_ColdWar_COIN_Woodland_FO: TWC_Infantry_ColdWar_Regular_Woodland_FO
{
	CATEGORY(TWC_Infantry_COIN_Woodland)
	uniformClass="UK3CB_BAF_U_JumperUniform_Plain";
	linkedItems[]=
	{
		"CUP_V_CDF_6B3_1_Green",
		"UK3CB_BAF_H_Beret_Rifles",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
	respawnLinkedItems[]=
	{
		"CUP_V_CDF_6B3_1_Green",
		"UK3CB_BAF_H_Beret_Rifles",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
};

//Aircraft
class TWC_Infantry_ColdWar_COIN_Woodland_FAC: TWC_Infantry_ColdWar_Regular_Woodland_FAC
{
	CATEGORY(TWC_Infantry_COIN_Woodland)
	uniformClass="UK3CB_BAF_U_JumperUniform_Plain";
	linkedItems[]=
	{
		"CUP_V_CDF_6B3_1_Green",
		"UK3CB_BAF_H_Beret_Rifles",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
	respawnLinkedItems[]=
	{
		"CUP_V_CDF_6B3_1_Green",
		"UK3CB_BAF_H_Beret_Rifles",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
};