	class O_Soldier_base_F;
	
	class BCCCCP_Base: O_Soldier_base_F
	{
		displayName="Base";
		editorSubcategory = "EdSubcat_Personnel";
		faction="BCCCCP";
		genericNames = "CUP_Names_RussianMen";
		icon="iconMan";
		identityTypes[]=
		{
			"CUP_D_Language_RU",
			"Head_Euro",
			"G_GUERIL_default"
		};
		nakedUniform="U_BasicBody";
		uniformClass="DISCLOSE_BEREZKA";
		backpack="";
		vehicleClass ="BCCCCP_Men";
		linkedItems[]=
		{
			"CUP_V_RUS_Smersh_1",
			"ItemCompass",
			"ItemWatch",
			"CUP_H_SLA_Helmet"
		};
		respawnLinkedItems[]=
		{
			"CUP_V_RUS_Smersh_1",
			"ItemCompass",
			"ItemWatch",
			"CUP_H_SLA_Helmet"
		};
		Items[]=
		{
			"ACE_fieldDressing",
			"ACE_fieldDressing",
			"ACE_fieldDressing",
			"ACE_fieldDressing",
			"ACE_packingBandage",
			"ACE_packingBandage",
			"ACE_packingBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_tourniquet"
		};
		respawntems[]=
		{
			"ACE_fieldDressing",
			"ACE_fieldDressing",
			"ACE_fieldDressing",
			"ACE_fieldDressing",
			"ACE_packingBandage",
			"ACE_packingBandage",
			"ACE_packingBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_tourniquet"
		};		
	};
	class BCCCCP_Rifleman: BCCCCP_Base
	{
		scope = 2;
		displayName="Rifleman";
		weapons[]=
		{
			"Throw",
			"Put",
			"CUP_arifle_AK74"
		};
		respawnweapons[]=
		{
			"Throw",
			"Put",
			"CUP_arifle_AK74"
		};
		magazines[]=
		{
			"CUP_30Rnd_545x39_AK_M",
			"CUP_30Rnd_545x39_AK_M",
			"CUP_30Rnd_545x39_AK_M",
			"CUP_30Rnd_545x39_AK_M",
			"CUP_30Rnd_545x39_AK_M",
			"CUP_30Rnd_545x39_AK_M",
			"CUP_30Rnd_545x39_AK_M",
			"CUP_30Rnd_545x39_AK_M",
			"CUP_30Rnd_545x39_AK_M",
			"CUP_HandGrenade_RGD5",
			"CUP_HandGrenade_RGD5",
			"SmokeShell"
		};
		Respawnmagazines[]=
		{
			"CUP_30Rnd_545x39_AK_M",
			"CUP_30Rnd_545x39_AK_M",
			"CUP_30Rnd_545x39_AK_M",
			"CUP_30Rnd_545x39_AK_M",
			"CUP_30Rnd_545x39_AK_M",
			"CUP_30Rnd_545x39_AK_M",
			"CUP_30Rnd_545x39_AK_M",
			"CUP_30Rnd_545x39_AK_M",
			"CUP_30Rnd_545x39_AK_M",
			"CUP_HandGrenade_RGD5",
			"CUP_HandGrenade_RGD5",
			"SmokeShell"
		};
	};
	class BCCCCP_SenRifleman: BCCCCP_Rifleman
	{
		displayName="Senior Rifleman";
		backpack="BCCCCP_Backpack_Squadlead";
		weapons[]=
		{
			"Throw",
			"Put",
			"CUP_arifle_AK74_GL"
		};
		respawnweapons[]=
		{
			"Throw",
			"Put",
			"CUP_arifle_AK74_GL"
		};
		magazines[]=
		{
			"CUP_30Rnd_545x39_AK_M",
			"CUP_30Rnd_545x39_AK_M",
			"CUP_30Rnd_545x39_AK_M",
			"CUP_30Rnd_545x39_AK_M",
			"CUP_1Rnd_HE_GP25_M",
			"CUP_1Rnd_HE_GP25_M",
			"CUP_1Rnd_HE_GP25_M",
			"CUP_1Rnd_HE_GP25_M",
			"CUP_1Rnd_HE_GP25_M",
			"CUP_1Rnd_HE_GP25_M",
			"CUP_HandGrenade_RGD5",
			"CUP_HandGrenade_RGD5",
			"SmokeShell"
		};
		Respawnmagazines[]=
		{
			"CUP_30Rnd_545x39_AK_M",
			"CUP_30Rnd_545x39_AK_M",
			"CUP_30Rnd_545x39_AK_M",
			"CUP_30Rnd_545x39_AK_M",
			"CUP_1Rnd_HE_GP25_M",
			"CUP_1Rnd_HE_GP25_M",
			"CUP_1Rnd_HE_GP25_M",
			"CUP_1Rnd_HE_GP25_M",
			"CUP_1Rnd_HE_GP25_M",
			"CUP_1Rnd_HE_GP25_M",
			"CUP_HandGrenade_RGD5",
			"CUP_HandGrenade_RGD5",
			"SmokeShell"
		};
	};
	class BCCCCP_Squadlead: BCCCCP_Base
	{
		scope = 2;
		displayName="Squadleader";
		icon="iconManLeader";
		backpack="BCCCCP_Squadlead";
		weapons[]=
		{
			"Throw",
			"Put",
			"CUP_arifle_AK74_GL",
			"Binocular"
		};
		respawnweapons[]=
		{
			"Throw",
			"Put",
			"CUP_arifle_AK74_GL",
			"Binocular"
		};
		magazines[]=
		{
			"CUP_30Rnd_545x39_AK_M",
			"CUP_30Rnd_545x39_AK_M",
			"CUP_30Rnd_545x39_AK_M",
			"CUP_30Rnd_545x39_AK_M",
			"CUP_30Rnd_545x39_AK_M",
			"CUP_hgun_Makarov",
			"CUP_hgun_Makarov",
			"CUP_1Rnd_HE_GP25_M",
			"CUP_1Rnd_HE_GP25_M",
			"CUP_1Rnd_HE_GP25_M",
			"CUP_1Rnd_HE_GP25_M",
			"CUP_1Rnd_HE_GP25_M",
			"CUP_HandGrenade_RGD5",
			"CUP_HandGrenade_RGD5",
			"SmokeShell",
			"SmokeShell",
			"SmokeShell"
		};
		Respawnmagazines[]=
		{
			"CUP_30Rnd_545x39_AK_M",
			"CUP_30Rnd_545x39_AK_M",
			"CUP_30Rnd_545x39_AK_M",
			"CUP_30Rnd_545x39_AK_M",
			"CUP_30Rnd_545x39_AK_M",
			"CUP_hgun_Makarov",
			"CUP_hgun_Makarov",
			"CUP_1Rnd_HE_GP25_M",
			"CUP_1Rnd_HE_GP25_M",
			"CUP_1Rnd_HE_GP25_M",
			"CUP_1Rnd_HE_GP25_M",
			"CUP_1Rnd_HE_GP25_M",
			"CUP_HandGrenade_RGD5",
			"CUP_HandGrenade_RGD5",
			"SmokeShell",
			"SmokeShell",
			"SmokeShell"
		};
	};
	class BCCCCP_Grenadier: BCCCCP_Rifleman
	{
		displayName="Grenadier (RPG)";
		icon="iconManAT";
		backpack="BCCCCP_Backpack_Grenadier";
		weapons[]=
		{
			"Throw",
			"Put",
			"CUP_arifle_AK74",
			"CUP_launch_RPG7V"
		};
		respawnweapons[]=
		{
			"Throw",
			"Put",
			"CUP_arifle_AK74",
			"CUP_launch_RPG7V"
		};
		magazines[]=
		{
			"CUP_30Rnd_545x39_AK_M",
			"CUP_30Rnd_545x39_AK_M",
			"CUP_30Rnd_545x39_AK_M",
			"CUP_30Rnd_545x39_AK_M",
			"CUP_30Rnd_545x39_AK_M",
			"CUP_30Rnd_545x39_AK_M",
			"CUP_30Rnd_545x39_AK_M",
			"CUP_30Rnd_545x39_AK_M",
			"CUP_30Rnd_545x39_AK_M",
			"CUP_HandGrenade_RGD5",
			"CUP_HandGrenade_RGD5",
			"SmokeShell",
			"CUP_PG7VL_M"
		};
		Respawnmagazines[]=
		{
			"CUP_30Rnd_545x39_AK_M",
			"CUP_30Rnd_545x39_AK_M",
			"CUP_30Rnd_545x39_AK_M",
			"CUP_30Rnd_545x39_AK_M",
			"CUP_30Rnd_545x39_AK_M",
			"CUP_30Rnd_545x39_AK_M",
			"CUP_30Rnd_545x39_AK_M",
			"CUP_30Rnd_545x39_AK_M",
			"CUP_30Rnd_545x39_AK_M",
			"CUP_HandGrenade_RGD5",
			"CUP_HandGrenade_RGD5",
			"SmokeShell",
			"CUP_PG7VL_M"
		};
	};
	class BCCCCP_GrenadierAss: BCCCCP_Rifleman
	{
		displayName="Grenadier Assistant";
		backpack="BCCCCP_Backpack_Grenadier";
	};
	class BCCCCP_MG_RPK: BCCCCP_Base
	{
		scope = 2;
		displayName="Machine Gunner (RPK)";
		icon="iconManMG";
		backpack="BCCCCP_Backpack_RPK";
		weapons[]=
		{
			"Throw",
			"Put",
			"CUP_arifle_RPK74_45"
		};
		respawnweapons[]=
		{
			"Throw",
			"Put",
			"CUP_arifle_RPK74_45"
		};
		magazines[]=
		{
			"CUP_45Rnd_TE4_LRT4_Green_Tracer_545x39_RPK_M",
			"CUP_45Rnd_TE4_LRT4_Green_Tracer_545x39_RPK_M",
			"CUP_45Rnd_TE4_LRT4_Green_Tracer_545x39_RPK_M",
			"CUP_45Rnd_TE4_LRT4_Green_Tracer_545x39_RPK_M",
			"CUP_HandGrenade_RGD5",
			"SmokeShell"
		};
		Respawnmagazines[]=
		{
			"CUP_45Rnd_TE4_LRT4_Green_Tracer_545x39_RPK_M",
			"CUP_45Rnd_TE4_LRT4_Green_Tracer_545x39_RPK_M",
			"CUP_45Rnd_TE4_LRT4_Green_Tracer_545x39_RPK_M",
			"CUP_45Rnd_TE4_LRT4_Green_Tracer_545x39_RPK_M",
			"CUP_HandGrenade_RGD5",
			"SmokeShell"
		};
	};
	class BCCCCP_MG_PKM: BCCCCP_Base
	{
		scope = 2;
		displayName="Machine Gunner (PKM)";
		icon="iconManMG";
		weapons[]=
		{
			"Throw",
			"Put",
			"CUP_arifle_RPK74_45"
		};
		respawnweapons[]=
		{
			"Throw",
			"Put",
			"CUP_arifle_RPK74_45"
		};
		magazines[]=
		{
			"CUP_100Rnd_TE4_LRT4_762x54_PK_Tracer_Green_M",
			"CUP_100Rnd_TE4_LRT4_762x54_PK_Tracer_Green_M",
			"CUP_100Rnd_TE4_LRT4_762x54_PK_Tracer_Green_M",
			"SmokeShell"
		};
		Respawnmagazines[]=
		{
			"CUP_100Rnd_TE4_LRT4_762x54_PK_Tracer_Green_M",
			"CUP_100Rnd_TE4_LRT4_762x54_PK_Tracer_Green_M",
			"CUP_100Rnd_TE4_LRT4_762x54_PK_Tracer_Green_M",
			"SmokeShell"
		};
	};
	class BCCCCP_MGAss: BCCCCP_Rifleman
	{
		displayName="Machine Gunner Assistant";
		backpack="BCCCCP_Backpack_PKM";
	};
	class BCCCCP_Sniper: BCCCCP_Base
	{
		scope = 2;
		displayName="Sniper";
		weapons[]=
		{
			"Throw",
			"Put",
			"CUP_srifle_SVD_pso",
			"Binocular"
		};
		respawnweapons[]=
		{
			"Throw",
			"Put",
			"CUP_srifle_SVD_pso",
			"Binocular"
		};
		magazines[]=
		{
			"CUP_10Rnd_762x54_SVD_M",
			"CUP_10Rnd_762x54_SVD_M",
			"CUP_10Rnd_762x54_SVD_M",
			"CUP_10Rnd_762x54_SVD_M",
			"CUP_10Rnd_762x54_SVD_M",
			"CUP_10Rnd_762x54_SVD_M",
			"CUP_10Rnd_762x54_SVD_M",
			"CUP_10Rnd_762x54_SVD_M",
			"CUP_10Rnd_762x54_SVD_M",
			"CUP_HandGrenade_RGD5",
			"SmokeShell",
			"SmokeShell",
			"SmokeShell"
		};
		Respawnmagazines[]=
		{
			"CUP_10Rnd_762x54_SVD_M",
			"CUP_10Rnd_762x54_SVD_M",
			"CUP_10Rnd_762x54_SVD_M",
			"CUP_10Rnd_762x54_SVD_M",
			"CUP_10Rnd_762x54_SVD_M",
			"CUP_10Rnd_762x54_SVD_M",
			"CUP_10Rnd_762x54_SVD_M",
			"CUP_10Rnd_762x54_SVD_M",
			"CUP_10Rnd_762x54_SVD_M",
			"CUP_HandGrenade_RGD5",
			"SmokeShell",
			"SmokeShell"
		};
	};
	class BCCCCP_VDV_Rifleman: BCCCCP_Rifleman
	{
		uniformClass="CUP_U_O_RUS_Flora_1_VDV";
		editorSubcategory = "BCCCCP_VDV";
		vehicleClass ="BCCCCP_VDV";
		weapons[]=
		{
			"Throw",
			"Put",
			"CUP_arifle_AKS74"
		};
		respawnweapons[]=
		{
			"Throw",
			"Put",
			"CUP_arifle_AKS74"
		};
	};
	class BCCCCP_VDV_Rifleman_Para: BCCCCP_VDV_Rifleman
	{
		displayName="Rifleman (Parajump)";
		linkedItems[]=
		{
			"CUP_V_RUS_Smersh_1",
			"ItemCompass",
			"ItemWatch",
			"CUP_H_TK_TankerHelmet"
		};
		respawnLinkedItems[]=
		{
			"CUP_V_RUS_Smersh_1",
			"ItemCompass",
			"ItemWatch",
			"CUP_H_TK_TankerHelmet"
		};
	};
	class BCCCCP_VDV_SenRifleman: BCCCCP_SenRifleman
	{
		uniformClass="CUP_U_O_RUS_Flora_1_VDV";
		editorSubcategory = "BCCCCP_VDV";
		vehicleClass ="BCCCCP_VDV";
	};
	class BCCCCP_VDV_Squadlead: BCCCCP_Squadlead
	{
		uniformClass="CUP_U_O_RUS_Flora_1_VDV";
		editorSubcategory = "BCCCCP_VDV";
		vehicleClass ="BCCCCP_VDV";
	};
	class BCCCCP_VDV_Grenadier: BCCCCP_Grenadier
	{
		uniformClass="CUP_U_O_RUS_Flora_1_VDV";
		editorSubcategory = "BCCCCP_VDV";
		vehicleClass ="BCCCCP_VDV";
	};
	class BCCCCP_VDV_GrenadierAss: BCCCCP_GrenadierAss
	{
		uniformClass="CUP_U_O_RUS_Flora_1_VDV";
		editorSubcategory = "BCCCCP_VDV";
		vehicleClass ="BCCCCP_VDV";
	};
	class BCCCCP_VDV_MG_RPK: BCCCCP_MG_RPK
	{
		uniformClass="CUP_U_O_RUS_Flora_1_VDV";
		editorSubcategory = "BCCCCP_VDV";
	};
	class BCCCCP_VDV_MG_PKM: BCCCCP_MG_PKM
	{
		uniformClass="CUP_U_O_RUS_Flora_1_VDV";
		editorSubcategory = "BCCCCP_VDV";
		vehicleClass ="BCCCCP_VDV";
	};
	class BCCCCP_VDV_MGAss: BCCCCP_MGAss
	{
		uniformClass="CUP_U_O_RUS_Flora_1_VDV";
		editorSubcategory = "BCCCCP_VDV";
		vehicleClass ="BCCCCP_VDV";
	};
	class BCCCCP_VDV_Sniper: BCCCCP_Sniper
	{
		uniformClass="CUP_U_O_RUS_Flora_1_VDV";
		editorSubcategory = "BCCCCP_VDV";
		vehicleClass ="BCCCCP_VDV";
	};
	class BCCCCP_AAGunner: BCCCCP_Rifleman
	{
		displayName="Anti-Air Gunner";
		backpack="BCCCCP_Backpack_AA";
		vehicleClass ="BCCCCP_VDV";
		weapons[]=
		{
			"Throw",
			"Put",
			"CUP_launch_9K32Strela",
			"CUP_arifle_AK74"
		};
		respawnweapons[]=
		{
			"Throw",
			"Put",
			"CUP_launch_9K32Strela",
			"CUP_arifle_AK74"
		};
		magazines[]=
		{
			"CUP_30Rnd_545x39_AK_M",
			"CUP_30Rnd_545x39_AK_M",
			"CUP_30Rnd_545x39_AK_M",
			"CUP_30Rnd_545x39_AK_M",
			"CUP_30Rnd_545x39_AK_M",
			"CUP_30Rnd_545x39_AK_M",
			"CUP_30Rnd_545x39_AK_M",
			"CUP_HandGrenade_RGD5",
			"SmokeShell",
			"CUP_launch_9K32Strela"
		};
		Respawnmagazines[]=
		{
			"CUP_30Rnd_545x39_AK_M",
			"CUP_30Rnd_545x39_AK_M",
			"CUP_30Rnd_545x39_AK_M",
			"CUP_30Rnd_545x39_AK_M",
			"CUP_30Rnd_545x39_AK_M",
			"CUP_30Rnd_545x39_AK_M",
			"CUP_30Rnd_545x39_AK_M",
			"CUP_HandGrenade_RGD5",
			"SmokeShell",
			"CUP_launch_9K32Strela"
		};
	};
	class BCCCCP_AAAssistant: BCCCCP_Rifleman
	{
		displayName="Anti-Air Assistant";
		backpack="BCCCCP_Backpack_AA";
		vehicleClass ="BCCCCP_VDV";
	};
	class BCCCCP_ATGunner: BCCCCP_Rifleman
	{
		displayName="Anti-Tank Gunner";
		icon="iconManAT";
		backpack="BCCCCP_Backpack_AT";
		vehicleClass ="BCCCCP_VDV";
		weapons[]=
		{
			"Throw",
			"Put",
			"CUP_launch_Metis",
			"CUP_arifle_AK74"
		};
		respawnweapons[]=
		{
			"Throw",
			"Put",
			"CUP_launch_Metis",
			"CUP_arifle_AK74"
		};
		magazines[]=
		{
			"CUP_30Rnd_545x39_AK_M",
			"CUP_30Rnd_545x39_AK_M",
			"CUP_30Rnd_545x39_AK_M",
			"CUP_30Rnd_545x39_AK_M",
			"CUP_30Rnd_545x39_AK_M",
			"CUP_30Rnd_545x39_AK_M",
			"CUP_30Rnd_545x39_AK_M",
			"CUP_HandGrenade_RGD5",
			"SmokeShell",
			"CUP_AT13_M"
		};
		Respawnmagazines[]=
		{
			"CUP_30Rnd_545x39_AK_M",
			"CUP_30Rnd_545x39_AK_M",
			"CUP_30Rnd_545x39_AK_M",
			"CUP_30Rnd_545x39_AK_M",
			"CUP_30Rnd_545x39_AK_M",
			"CUP_30Rnd_545x39_AK_M",
			"CUP_30Rnd_545x39_AK_M",
			"CUP_HandGrenade_RGD5",
			"SmokeShell",
			"CUP_AT13_M"
		};
	};
	class BCCCCP_ATAssistant: BCCCCP_Base
	{
		scope = 2;
		displayName="Anti-Tank Assistant";
		backpack="BCCCCP_Backpack_AT";
		vehicleClass ="BCCCCP_VDV";
	};
	class BCCCP_Razvedka_Observer: BCCCCP_Rifleman
	{
		displayName="Observer";
		editorSubcategory = "BCCCCP_Razvedka";
		vehicleClass ="BCCCCP_Razvedka";
		linkedItems[]=
		{
			"CUP_V_RUS_Smersh_1",
			"ItemCompass",
			"ItemWatch",
			"G_Bandanna_oli",
			"H_Booniehat_oli"
		};
		respawnLinkedItems[]=
		{
			"CUP_V_RUS_Smersh_1",
			"ItemCompass",
			"ItemWatch",
			"G_Bandanna_oli",
			"H_Booniehat_oli"
		};
		weapons[]=
		{
			"Throw",
			"Put",
			"CUP_arifle_AKS74_kobra",
			"CUP_launch_RPG18",
			"Binocular"
		};
		respawnweapons[]=
		{
			"Throw",
			"Put",
			"CUP_arifle_AKS74_kobra",
			"CUP_launch_RPG18",
			"Binocular"
		};
	};
	class BCCCP_Razvedka_Marksman: BCCCP_Razvedka_Observer
	{
		displayName="Marksman";
		editorSubcategory = "BCCCCP_Razvedka";
		vehicleClass ="BCCCCP_Razvedka";
		weapons[]=
		{
			"Throw",
			"Put",
			"CUP_arifle_AKS74_pso"
		};
		respawnweapons[]=
		{
			"Throw",
			"Put",
			"CUP_arifle_AKS74_pso"
		};
	};
	class BCCCCP_Spets_Operator: BCCCCP_Base
	{
		scope = 2;
		displayName="Operator";
		editorSubcategory = "BCCCCP_Spetsnaz";
		uniformClass="CUP_U_O_RUS_Gorka_Partizan";
		vehicleClass ="BCCCCP_Spetsnaz";
		linkedItems[]=
		{
			"CUP_V_RUS_Smersh_1",
			"ItemCompass",
			"ItemWatch",
			"G_Bandanna_khk",
			"CUP_H_FR_BandanaGreen"
		};
		respawnLinkedItems[]=
		{
			"CUP_V_RUS_Smersh_1",
			"ItemCompass",
			"ItemWatch",
			"G_Bandanna_khk",
			"CUP_H_FR_BandanaGreen"
		};
		weapons[]=
		{
			"Throw",
			"Put",
			"CUP_arifle_AKS74UN_kobra_snds",
			"CUP_hgun_PB6P9"
		};
		respawnweapons[]=
		{
			"Throw",
			"Put",
			"CUP_arifle_AKS74UN_kobra_snds",
			"CUP_hgun_PB6P9"
		};
		magazines[]=
		{
			"CUP_8Rnd_9x18_Makarov_M",
			"CUP_8Rnd_9x18_Makarov_M",
			"CUP_30Rnd_Subsonic_545x39_AK_M",
			"CUP_30Rnd_Subsonic_545x39_AK_M",
			"CUP_30Rnd_Subsonic_545x39_AK_M",
			"CUP_30Rnd_Subsonic_545x39_AK_M",
			"CUP_30Rnd_Subsonic_545x39_AK_M",
			"CUP_30Rnd_Subsonic_545x39_AK_M",
			"CUP_30Rnd_Subsonic_545x39_AK_M",
			"CUP_30Rnd_Subsonic_545x39_AK_M",
			"CUP_HandGrenade_RGD5",
			"CUP_HandGrenade_RGD5",
			"SmokeShell",
			"SmokeShell"
		};
		Respawnmagazines[]=
		{
			"CUP_8Rnd_9x18_Makarov_M",
			"CUP_8Rnd_9x18_Makarov_M",
			"CUP_30Rnd_Subsonic_545x39_AK_M",
			"CUP_30Rnd_Subsonic_545x39_AK_M",
			"CUP_30Rnd_Subsonic_545x39_AK_M",
			"CUP_30Rnd_Subsonic_545x39_AK_M",
			"CUP_30Rnd_Subsonic_545x39_AK_M",
			"CUP_30Rnd_Subsonic_545x39_AK_M",
			"CUP_30Rnd_Subsonic_545x39_AK_M",
			"CUP_30Rnd_Subsonic_545x39_AK_M",
			"CUP_HandGrenade_RGD5",
			"CUP_HandGrenade_RGD5",
			"SmokeShell",
			"SmokeShell"
		};
	};
	class BCCCCP_Spets_Marksman: BCCCCP_Spets_Operator
	{
		displayName="Marksman";
		vehicleClass ="BCCCCP_Spetsnaz";
		weapons[]=
		{
			"Throw",
			"Put",
			"CUP_srifle_VSSVintorez_pso",
			"CUP_hgun_PB6P9"
		};
		respawnweapons[]=
		{
			"Throw",
			"Put",
			"CUP_srifle_VSSVintorez_pso",
			"CUP_hgun_PB6P9"
		};
		magazines[]=
		{
			"CUP_8Rnd_9x18_Makarov_M",
			"CUP_8Rnd_9x18_Makarov_M",
			"CUP_20Rnd_9x39_SP5_VSS_M",
			"CUP_20Rnd_9x39_SP5_VSS_M",
			"CUP_20Rnd_9x39_SP5_VSS_M",
			"CUP_20Rnd_9x39_SP5_VSS_M",
			"CUP_20Rnd_9x39_SP5_VSS_M",
			"CUP_20Rnd_9x39_SP5_VSS_M",
			"CUP_20Rnd_9x39_SP5_VSS_M",
			"CUP_20Rnd_9x39_SP5_VSS_M",
			"CUP_HandGrenade_RGD5",
			"CUP_HandGrenade_RGD5",
			"SmokeShell",
			"SmokeShell"
		};
		Respawnmagazines[]=
		{
			"CUP_8Rnd_9x18_Makarov_M",
			"CUP_8Rnd_9x18_Makarov_M",
			"CUP_20Rnd_9x39_SP5_VSS_M",
			"CUP_20Rnd_9x39_SP5_VSS_M",
			"CUP_20Rnd_9x39_SP5_VSS_M",
			"CUP_20Rnd_9x39_SP5_VSS_M",
			"CUP_20Rnd_9x39_SP5_VSS_M",
			"CUP_20Rnd_9x39_SP5_VSS_M",
			"CUP_20Rnd_9x39_SP5_VSS_M",
			"CUP_20Rnd_9x39_SP5_VSS_M",
			"CUP_HandGrenade_RGD5",
			"CUP_HandGrenade_RGD5",
			"SmokeShell",
			"SmokeShell"
		};
	};
	class BCCCCP_Crewman_Camo: BCCCCP_Base
	{
		scope = 2;
		displayName="Crewman (Camo)";
		uniformClass="DISCLOSE_BEREZKA";
		linkedItems[]=
		{
			"CUP_V_O_TK_CrewBelt",
			"ItemCompass",
			"ItemWatch",
			"CUP_H_SLA_TankerHelmet"
		};
		respawnLinkedItems[]=
		{
			"CUP_V_O_TK_CrewBelt",
			"ItemCompass",
			"ItemWatch",
			"CUP_H_SLA_TankerHelmet"
		};
		weapons[]=
		{
			"Throw",
			"Put",
			"CUP_arifle_AKS74U"
		};
		respawnweapons[]=
		{
			"Throw",
			"Put",
			"CUP_arifle_AKS74U"
		};
		magazines[]=
		{
			"CUP_30Rnd_545x39_AK_M",
			"CUP_30Rnd_545x39_AK_M",
			"CUP_30Rnd_545x39_AK_M",
			"CUP_30Rnd_545x39_AK_M",
			"CUP_hgun_Makarov",
			"CUP_hgun_Makarov",
			"CUP_HandGrenade_RGD5",
			"SmokeShell"
		};
		Respawnmagazines[]=
		{
			"CUP_30Rnd_545x39_AK_M",
			"CUP_30Rnd_545x39_AK_M",
			"CUP_30Rnd_545x39_AK_M",
			"CUP_30Rnd_545x39_AK_M",
			"CUP_hgun_Makarov",
			"CUP_hgun_Makarov",
			"CUP_HandGrenade_RGD5",
			"SmokeShell"
		};
	};
	class BCCCCP_Crewman_Black: BCCCCP_Crewman_Camo
	{
		scope = 2;
		displayName="Crewman (Black)";
		uniformClass="CUP_U_O_SLA_Overalls_Tank";
		linkedItems[]=
		{
			"CUP_V_O_TK_CrewBelt",
			"ItemCompass",
			"ItemWatch",
			"CUP_H_RUS_TSH_4_Brown"
		};
		respawnLinkedItems[]=
		{
			"CUP_V_O_TK_CrewBelt",
			"ItemCompass",
			"ItemWatch",
			"CUP_H_RUS_TSH_4_Brown"
		};
	};
	class BCCCCP_Driver: BCCCCP_Crewman_Camo
	{
		displayName="Driver";
		linkedItems[]=
		{
			"CUP_V_O_TK_CrewBelt",
			"ItemCompass",
			"ItemWatch",
			"CUP_H_ChDKZ_Beret"
		};
		respawnLinkedItems[]=
		{
			"CUP_V_O_TK_CrewBelt",
			"ItemCompass",
			"ItemWatch",
			"CUP_H_ChDKZ_Beret"
		};
		weapons[]=
		{
			"Throw",
			"Put",
			"CUP_arifle_AKS74"
		};
		respawnweapons[]=
		{
			"Throw",
			"Put",
			"CUP_arifle_AKS74"
		};
	};
	class BCCCCP_Heli_Pilot: BCCCCP_Base
	{
		scope = 2;
		displayName="Helicopter Pilot";
		uniformClass="CUP_U_O_SLA_Overalls_Pilot";
		linkedItems[]=
		{
			"CUP_V_O_TK_CrewBelt",
			"ItemCompass",
			"ItemWatch",
			"CUP_H_RUS_ZSH_Shield_Up"
		};
		respawnLinkedItems[]=
		{
			"CUP_V_O_TK_CrewBelt",
			"ItemCompass",
			"ItemWatch",
			"CUP_H_RUS_ZSH_Shield_Up"
		};
		weapons[]=
		{
			"Throw",
			"Put",
			"CUP_arifle_AKS74U",
			"CUP_hgun_Makarov"
		};
		respawnweapons[]=
		{
			"Throw",
			"Put",
			"CUP_arifle_AKS74U",
			"CUP_hgun_Makarov"
		};
		magazines[]=
		{
			"CUP_30Rnd_545x39_AK_M",
			"CUP_30Rnd_545x39_AK_M",
			"CUP_30Rnd_545x39_AK_M",
			"CUP_hgun_Makarov",
			"CUP_hgun_Makarov",
			"SmokeShell"
		};
		Respawnmagazines[]=
		{
			"CUP_30Rnd_545x39_AK_M",
			"CUP_30Rnd_545x39_AK_M",
			"CUP_30Rnd_545x39_AK_M",
			"CUP_hgun_Makarov",
			"CUP_hgun_Makarov",
			"SmokeShell"
		};
	};
	class BCCCCP_Jet_Pilot: BCCCCP_Base
	{
		scope = 2;
		displayName="Helicopter Pilot";
		uniformClass="U_I_HeliPilotCoveralls";
		linkedItems[]=
		{
			"CUP_V_O_TK_CrewBelt",
			"ItemCompass",
			"ItemWatch",
			"CUP_H_RUS_ZSH_Shield_Down"
		};
		respawnLinkedItems[]=
		{
			"CUP_V_O_TK_CrewBelt",
			"ItemCompass",
			"ItemWatch",
			"CUP_H_RUS_ZSH_Shield_Down"
		};
		weapons[]=
		{
			"Throw",
			"Put",
			"CUP_hgun_Makarov"
		};
		respawnweapons[]=
		{
			"Throw",
			"Put",
			"CUP_hgun_Makarov"
		};
		magazines[]=
		{
			"CUP_hgun_Makarov",
			"CUP_hgun_Makarov",
			"CUP_hgun_Makarov",
			"SmokeShell"
		};
		Respawnmagazines[]=
		{			
			"CUP_hgun_Makarov",
			"CUP_hgun_Makarov",
			"CUP_hgun_Makarov",
			"SmokeShell"
		};
	};