Switch (typeof player) do {
	case "Modern_British_Squadleader" : {execVM "operation_framework\scopes\modern.sqf"};
	case "Modern_British_Rifleman" : {execVM "operation_framework\scopes\modern.sqf"};
	case "Modern_British_Grenadier" : {execVM "operation_framework\scopes\modern.sqf"};
	case "Modern_British_AutomaticRifleman" : {execVM "operation_framework\scopes\modern.sqf"};
	case "Modern_British_2IC" : {execVM "operation_framework\scopes\modern.sqf"};
	case "Mechanized_British_2IC" : {execVM "operation_framework\scopes\modern.sqf"};
	case "Modern_British_Platoon_Commander" : {execVM "operation_framework\scopes\modern.sqf"};
	case "Modern_British_Platoon_Sergeant" : {execVM "operation_framework\scopes\modern.sqf"};
	case "Modern_British_Coin_Squadleader" : {execVM "operation_framework\scopes\modern.sqf"};
	case "Modern_British_Coin_Pointman" : {execVM "operation_framework\scopes\modern.sqf"};
	case "Modern_British_Coin_Grenadier" : {execVM "operation_framework\scopes\modern.sqf"};
	case "Modern_British_Coin_Automaticrifleman" : {execVM "operation_framework\scopes\modern.sqf"};
	case "Modern_British_Coin_2IC" : {execVM "operation_framework\scopes\modern.sqf"};
	case "Modern_British_Coin_Platoon_Commander" : {execVM "operation_framework\scopes\modern.sqf"};
	case "Modern_British_Coin_Platoon_Sergeant" : {execVM "operation_framework\scopes\modern.sqf"};
	case "ColdWar_Section_Leader" : {};
	case "ColdWar_Platoon_Commander" : {};
	case "ColdWar_sergeant" : {};
	case "1990_British_Squadleader" : {execVM "operation_framework\scopes\90.sqf"};
	case "1990_British_Grenadier" : {execVM "operation_framework\scopes\90.sqf"};
	case "1990_British_Gunner" : {execVM "operation_framework\scopes\90.sqf"};
	case "1990_British_Rifleman" : {execVM "operation_framework\scopes\90.sqf"};
	case "1990_British_2IC" : {execVM "operation_framework\scopes\90.sqf"};
	case "1990_British_Platoon_Commander" : {execVM "operation_framework\scopes\90.sqf"};
	case "1990_British_Platoon_Sergeant" : {execVM "operation_framework\scopes\90.sqf"};
	case "1990_British_Squadleader_Desert" : {execVM "operation_framework\scopes\90.sqf"};
	case "1990_British_Grenadier_Desert" : {execVM "operation_framework\scopes\90.sqf"};
	case "1990_British_Gunner_Desert" : {execVM "operation_framework\scopes\90.sqf"};
	case "1990_British_Rifleman_Desert" : {execVM "operation_framework\scopes\90.sqf"};
	case "1990_British_2IC_Desert" : {execVM "operation_framework\scopes\90.sqf"};
	case "1990_British_Platoon_Commander_Desert" : {execVM "operation_framework\scopes\90.sqf"};
	case "1990_British_Platoon_Sergeant_Desert" : {execVM "operation_framework\scopes\90.sqf"};
};