//COIN, Desert
//Base
class TWC_Infantry_ColdWar_COIN_Desert_Base

//Section
class TWC_Infantry_ColdWar_COIN_Desert_Rifleman
class TWC_Infantry_ColdWar_COIN_Desert_Rifleman_SUIT
class TWC_Infantry_ColdWar_COIN_Desert_SectionCommander
class TWC_Infantry_ColdWar_COIN_Desert_2iC
class TWC_Infantry_ColdWar_COIN_Desert_AT
class TWC_Infantry_ColdWar_COIN_Desert_ASSAT
class TWC_Infantry_ColdWar_COIN_Desert_MG
class TWC_Infantry_ColdWar_COIN_Desert_ASSMG

//Platoon Command
class TWC_Infantry_ColdWar_COIN_Desert_Platoon_Commander
class TWC_Infantry_ColdWar_COIN_Desert_Platoon_Sergeant
class TWC_Infantry_ColdWar_COIN_Desert_Platoon_Medic
class TWC_Infantry_ColdWar_COIN_Desert_CSM

//AT + AA
class TWC_Infantry_ColdWar_COIN_Desert_MILAN_Gunner
class TWC_Infantry_ColdWar_COIN_Desert_MILAN_Ass
class TWC_Infantry_ColdWar_COIN_Desert_Blowpipe_Gunner
class TWC_Infantry_ColdWar_COIN_Desert_Blowpipe_Ass

//Sniper Team
class TWC_Infantry_ColdWar_COIN_Desert_Sniper
class TWC_Infantry_ColdWar_COIN_Desert_Spotter

//Artillery Crew
class TWC_Infantry_ColdWar_COIN_Desert_Artillery_Commander
class TWC_Infantry_ColdWar_COIN_Desert_Artillery_Crew
class TWC_Infantry_ColdWar_COIN_Desert_FO

//Aircraft
class TWC_Infantry_ColdWar_COIN_Desert_FAC
class TWC_Infantry_ColdWar_COIN_Desert_Helicopter_Pilot

//FVs
class TWC_Infantry_ColdWar_COIN_Desert_Vehicle_Commander
class TWC_Infantry_ColdWar_COIN_Desert_Vehicle_Crew