//COIN, DISMOUNTED, WOODLAND
//Section
class TWC_Infantry_ColdWar_COIN_Dismounted_Woodland_Rifleman: TWC_Infantry_ColdWar_COIN_Woodland_Rifleman
class TWC_Infantry_ColdWar_COIN_Dismounted_Woodland_Rifleman_SUIT: TWC_Infantry_ColdWar_COIN_Woodland_Rifleman_SUIT
class TWC_Infantry_ColdWar_COIN_Dismounted_Woodland_SectionCommander: TWC_Infantry_ColdWar_COIN_Woodland_SectionCommander
class TWC_Infantry_ColdWar_COIN_Dismounted_Woodland_2iC: TWC_Infantry_ColdWar_COIN_Woodland_2iC
class TWC_Infantry_ColdWar_COIN_Dismounted_Woodland_AT: TWC_Infantry_ColdWar_COIN_Woodland_AT
class TWC_Infantry_ColdWar_COIN_Dismounted_Woodland_ASSAT: TWC_Infantry_ColdWar_COIN_Woodland_ASSAT
class TWC_Infantry_ColdWar_COIN_Dismounted_Woodland_MG: TWC_Infantry_ColdWar_COIN_Woodland_MG
class TWC_Infantry_ColdWar_COIN_Dismounted_Woodland_ASSMG: TWC_Infantry_ColdWar_COIN_Woodland_ASSMG

//Platoon Command
class TWC_Infantry_ColdWar_COIN_Dismounted_Woodland_Platoon_Commander: TWC_Infantry_ColdWar_COIN_Woodland_Platoon_Commander
class TWC_Infantry_ColdWar_COIN_Dismounted_Woodland_Platoon_Sergeant: TWC_Infantry_ColdWar_COIN_Woodland_Platoon_Sergeant
class TWC_Infantry_ColdWar_COIN_Dismounted_Woodland_Platoon_Medic: TWC_Infantry_ColdWar_COIN_Woodland_Platoon_Medic
class TWC_Infantry_ColdWar_COIN_Dismounted_Woodland_CSM: TWC_Infantry_ColdWar_COIN_Woodland_CSM