//COIN, WOODLAND
//Base
class TWC_Infantry_ColdWar_COIN_Woodland_Base

//Section
class TWC_Infantry_ColdWar_COIN_Woodland_Rifleman
class TWC_Infantry_ColdWar_COIN_Woodland_Rifleman_SUIT
class TWC_Infantry_ColdWar_COIN_Woodland_SectionCommander
class TWC_Infantry_ColdWar_COIN_Woodland_2iC
class TWC_Infantry_ColdWar_COIN_Woodland_AT
class TWC_Infantry_ColdWar_COIN_Woodland_ASSAT
class TWC_Infantry_ColdWar_COIN_Woodland_MG
class TWC_Infantry_ColdWar_COIN_Woodland_ASSMG

//Platoon Command
class TWC_Infantry_ColdWar_COIN_Woodland_Platoon_Commander
class TWC_Infantry_ColdWar_COIN_Woodland_Platoon_Sergeant
class TWC_Infantry_ColdWar_COIN_Woodland_Platoon_Medic
class TWC_Infantry_ColdWar_COIN_Woodland_CSM

//AT + AA
class TWC_Infantry_ColdWar_COIN_Woodland_MILAN_Gunner
class TWC_Infantry_ColdWar_COIN_Woodland_MILAN_Ass
class TWC_Infantry_ColdWar_COIN_Woodland_Blowpipe_Gunner
class TWC_Infantry_ColdWar_COIN_Woodland_Blowpipe_Ass

//Sniper Team
class TWC_Infantry_ColdWar_COIN_Woodland_Sniper
class TWC_Infantry_ColdWar_COIN_Woodland_Spotter

//Artillery Crew
class TWC_Infantry_ColdWar_COIN_Woodland_Artillery_Commander
class TWC_Infantry_ColdWar_COIN_Woodland_Artillery_Crew
class TWC_Infantry_ColdWar_COIN_Woodland_FO

//Aircraft
class TWC_Infantry_ColdWar_COIN_Woodland_FAC
class TWC_Infantry_ColdWar_COIN_Woodland_Helicopter_Pilot

//FVs
class TWC_Infantry_ColdWar_COIN_Woodland_Vehicle_Commander
class TWC_Infantry_ColdWar_COIN_Woodland_Vehicle_Crew