//UK, DESERT
//Section
class TWC_Infantry_WW2_UK_Late_Desert_Rifleman: TWC_Infantry_WW2_UK_Late_Woodland_Rifleman
{
	CATEGORY(TWC_Infantry_Regular_Desert)
	uniformClass="U_LIB_UK_KhakiDrills";
	linkedItems[]=
	{
		"V_LIB_UK_P37_Rifleman",
		"H_LIB_UK_Helmet_Mk2_Desert",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
	respawnLinkedItems[]=
	{
		"V_LIB_UK_P37_Rifleman",
		"H_LIB_UK_Helmet_Mk2_Desert",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
};
class TWC_Infantry_WW2_UK_Late_Desert_Grenadier: TWC_Infantry_WW2_UK_Late_Woodland_Grenadier
{
	CATEGORY(TWC_Infantry_Regular_Desert)
	uniformClass="U_LIB_UK_KhakiDrills";
	linkedItems[]=
	{
		"V_LIB_UK_P37_Heavy",
		"H_LIB_UK_Helmet_Mk2_Desert",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
	respawnLinkedItems[]=
	{
		"V_LIB_UK_P37_Heavy",
		"H_LIB_UK_Helmet_Mk2_Desert",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
};
class TWC_Infantry_WW2_UK_Late_Desert_SMG: TWC_Infantry_WW2_UK_Late_Woodland_SMG
{
	CATEGORY(TWC_Infantry_Regular_Desert)
	uniformClass="U_LIB_UK_KhakiDrills";
	linkedItems[]=
	{
		"V_LIB_UK_P37_Sten",
		"H_LIB_UK_Helmet_Mk2_Desert",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
	respawnLinkedItems[]=
	{
		"V_LIB_UK_P37_Sten",
		"H_LIB_UK_Helmet_Mk2_Desert",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
};
class TWC_Infantry_WW2_UK_Late_Desert_MG: TWC_Infantry_WW2_UK_Late_Woodland_MG
{
	CATEGORY(TWC_Infantry_Regular_Desert)
	uniformClass="U_LIB_UK_KhakiDrills";
	linkedItems[]=
	{
		"V_LIB_UK_P37_Heavy",
		"H_LIB_UK_Helmet_Mk2_Desert",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
	respawnLinkedItems[]=
	{
		"V_LIB_UK_P37_Heavy",
		"H_LIB_UK_Helmet_Mk2_Desert",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
};
class TWC_Infantry_WW2_UK_Late_Desert_MGASS: TWC_Infantry_WW2_UK_Late_Woodland_MGASS
{
	CATEGORY(TWC_Infantry_Regular_Desert)
	uniformClass="U_LIB_UK_KhakiDrills";
	linkedItems[]=
	{
		"V_LIB_UK_P37_Rifleman",
		"H_LIB_UK_Helmet_Mk2_Desert",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
	respawnLinkedItems[]=
	{
		"V_LIB_UK_P37_Rifleman",
		"H_LIB_UK_Helmet_Mk2_Desert",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
};
class TWC_Infantry_WW2_UK_Late_Desert_SectionCommander: TWC_Infantry_WW2_UK_Late_Woodland_SectionCommander
{
	CATEGORY(TWC_Infantry_Regular_Desert)
	uniformClass="U_LIB_UK_KhakiDrills";
	linkedItems[]=
	{
		"V_LIB_UK_P37_Sten",
		"H_LIB_UK_Helmet_Mk2_Desert",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
	respawnLinkedItems[]=
	{
		"V_LIB_UK_P37_Sten",
		"H_LIB_UK_Helmet_Mk2_Desert",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
};
class TWC_Infantry_WW2_UK_Late_Desert_2iC: TWC_Infantry_WW2_UK_Late_Woodland_2iC
{
	CATEGORY(TWC_Infantry_Regular_Desert)
	uniformClass="U_LIB_UK_KhakiDrills";
	linkedItems[]=
	{
		"V_LIB_UK_P37_Heavy",
		"H_LIB_UK_Helmet_Mk2_Desert",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
	respawnLinkedItems[]=
	{
		"V_LIB_UK_P37_Heavy",
		"H_LIB_UK_Helmet_Mk2_Desert",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
};

//Platoon Command
class TWC_Infantry_WW2_UK_Late_Desert_Platoon_Commander: TWC_Infantry_WW2_UK_Late_Woodland_Platoon_Commander
{
	CATEGORY(TWC_Infantry_Regular_Desert)
	uniformClass="U_LIB_UK_KhakiDrills";
	linkedItems[]=
	{
		"V_LIB_UK_P37_Sten",
		"H_LIB_UK_Helmet_Mk2_Desert",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
	respawnLinkedItems[]=
	{
		"V_LIB_UK_P37_Sten",
		"H_LIB_UK_Helmet_Mk2_Desert",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
};
class TWC_Infantry_WW2_UK_Late_Desert_Platoon_Sergeant: TWC_Infantry_WW2_UK_Late_Woodland_Platoon_Sergeant
{
	CATEGORY(TWC_Infantry_Regular_Desert)
	uniformClass="U_LIB_UK_KhakiDrills";
	linkedItems[]=
	{
		"V_LIB_UK_P37_Heavy",
		"H_LIB_UK_Helmet_Mk2_Desert",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
	respawnLinkedItems[]=
	{
		"V_LIB_UK_P37_Heavy",
		"H_LIB_UK_Helmet_Mk2_Desert",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
};
class TWC_Infantry_WW2_UK_Late_Desert_Platoon_Medic: TWC_Infantry_WW2_UK_Late_Woodland_Platoon_Medic
{
	CATEGORY(TWC_Infantry_Regular_Desert)
	uniformClass="U_LIB_UK_KhakiDrills";
	linkedItems[]=
	{
		"V_LIB_UK_P37_Sten",
		"H_LIB_UK_Helmet_Mk2_Desert",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
	respawnLinkedItems[]=
	{
		"V_LIB_UK_P37_Sten",
		"H_LIB_UK_Helmet_Mk2_Desert",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
};
class TWC_Infantry_WW2_UK_Late_Desert_Platoon_Runner: TWC_Infantry_WW2_UK_Late_Woodland_Platoon_Runner
{
	CATEGORY(TWC_Infantry_Regular_Desert)
	uniformClass="U_LIB_UK_KhakiDrills";
	linkedItems[]=
	{
		"V_LIB_UK_P37_Rifleman",
		"H_LIB_UK_Helmet_Mk2_Desert",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
	respawnLinkedItems[]=
	{
		"V_LIB_UK_P37_Rifleman",
		"H_LIB_UK_Helmet_Mk2_Desert",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
};
class TWC_Infantry_WW2_UK_Late_Desert_Platoon_Mortar: TWC_Infantry_WW2_UK_Late_Woodland_Platoon_Mortar
{
	CATEGORY(TWC_Infantry_Regular_Desert)
	uniformClass="U_LIB_UK_KhakiDrills";
	linkedItems[]=
	{
		"V_LIB_UK_P37_Heavy",
		"H_LIB_UK_Helmet_Mk2_Desert",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
	respawnLinkedItems[]=
	{
		"V_LIB_UK_P37_Heavy",
		"H_LIB_UK_Helmet_Mk2_Desert",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
};
class TWC_Infantry_WW2_UK_Late_Desert_Platoon_CSM: TWC_Infantry_WW2_UK_Late_Woodland_Platoon_CSM
{
	CATEGORY(TWC_Infantry_Regular_Desert)
	uniformClass="U_LIB_UK_KhakiDrills";
	linkedItems[]=
	{
		"V_LIB_UK_P37_Heavy",
		"H_LIB_UK_Helmet_Mk2_Desert",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
	respawnLinkedItems[]=
	{
		"V_LIB_UK_P37_Heavy",
		"H_LIB_UK_Helmet_Mk2_Desert",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
};

//AT
class TWC_Infantry_WW2_UK_Late_Desert_PIAT_Gunner: TWC_Infantry_WW2_UK_Late_Woodland_PIAT_Gunner
{
	CATEGORY(TWC_Infantry_Regular_Desert)
	uniformClass="U_LIB_UK_KhakiDrills";
	linkedItems[]=
	{
		"V_LIB_UK_P37_Heavy",
		"H_LIB_UK_Helmet_Mk2_Desert",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
	respawnLinkedItems[]=
	{
		"V_LIB_UK_P37_Heavy",
		"H_LIB_UK_Helmet_Mk2_Desert",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
};
class TWC_Infantry_WW2_UK_Late_Desert_PIAT_Ass: TWC_Infantry_WW2_UK_Late_Woodland_PIAT_Ass
{
	CATEGORY(TWC_Infantry_Regular_Desert)
	uniformClass="U_LIB_UK_KhakiDrills";
	linkedItems[]=
	{
		"V_LIB_UK_P37_Sten",
		"H_LIB_UK_Helmet_Mk2_Desert",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
	respawnLinkedItems[]=
	{
		"V_LIB_UK_P37_Sten",
		"H_LIB_UK_Helmet_Mk2_Desert",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
};

//Sniper Team
class TWC_Infantry_WW2_UK_Late_Desert_Sniper: TWC_Infantry_WW2_UK_Late_Woodland_Sniper
{
	CATEGORY(TWC_Infantry_Regular_Desert)
	uniformClass="U_LIB_UK_KhakiDrills";
	linkedItems[]=
	{
		"V_LIB_UK_P37_Rifleman",
		"H_LIB_UK_Helmet_Mk2_Desert",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
	respawnLinkedItems[]=
	{
		"V_LIB_UK_P37_Rifleman",
		"H_LIB_UK_Helmet_Mk2_Desert",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
};
class TWC_Infantry_WW2_UK_Late_Desert_Spotter: TWC_Infantry_WW2_UK_Late_Woodland_Spotter
{
	CATEGORY(TWC_Infantry_Regular_Desert)
	uniformClass="U_LIB_UK_KhakiDrills";
	linkedItems[]=
	{
		"V_LIB_UK_P37_Rifleman",
		"H_LIB_UK_Helmet_Mk2_Desert",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
	respawnLinkedItems[]=
	{
		"V_LIB_UK_P37_Rifleman",
		"H_LIB_UK_Helmet_Mk2_Desert",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
};

//Artillery
class TWC_Infantry_WW2_UK_Late_Desert_Artillery_Commander: TWC_Infantry_WW2_UK_Late_Woodland_Artillery_Commander
{
	CATEGORY(TWC_Infantry_Regular_Desert)
	uniformClass="U_LIB_UK_KhakiDrills";
	linkedItems[]=
	{
		"V_LIB_UK_P37_Sten",
		"H_LIB_UK_Helmet_Mk2_Desert",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
	respawnLinkedItems[]=
	{
		"V_LIB_UK_P37_Sten",
		"H_LIB_UK_Helmet_Mk2_Desert",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
};
class TWC_Infantry_WW2_UK_Late_Desert_Artillery_Crew: TWC_Infantry_WW2_UK_Late_Woodland_Artillery_Crew
{
	CATEGORY(TWC_Infantry_Regular_Desert)
	uniformClass="U_LIB_UK_KhakiDrills";
	linkedItems[]=
	{
		"V_LIB_UK_P37_Sten",
		"H_LIB_UK_Helmet_Mk2_Desert",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
	respawnLinkedItems[]=
	{
		"V_LIB_UK_P37_Sten",
		"H_LIB_UK_Helmet_Mk2_Desert",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
};
class TWC_Infantry_WW2_UK_Late_Desert_FO: TWC_Infantry_WW2_UK_Late_Woodland_FO
{
	CATEGORY(TWC_Infantry_Regular_Desert)
	uniformClass="U_LIB_UK_KhakiDrills";
	linkedItems[]=
	{
		"V_LIB_UK_P37_Sten",
		"H_LIB_UK_Helmet_Mk2_Desert",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
	respawnLinkedItems[]=
	{
		"V_LIB_UK_P37_Sten",
		"H_LIB_UK_Helmet_Mk2_Desert",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
};

//Aircraft
class TWC_Infantry_WW2_UK_Late_Desert_FAC: TWC_Infantry_WW2_UK_Late_Woodland_FAC
{
	CATEGORY(TWC_Infantry_Regular_Desert)
	uniformClass="U_LIB_UK_KhakiDrills";
	linkedItems[]=
	{
		"V_LIB_UK_P37_Sten",
		"H_LIB_UK_Helmet_Mk2_Desert",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
	respawnLinkedItems[]=
	{
		"V_LIB_UK_P37_Sten",
		"H_LIB_UK_Helmet_Mk2_Desert",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
};

//FVs
class TWC_Infantry_WW2_UK_Late_Desert_Vehicle_Commander: TWC_Infantry_WW2_UK_Late_Woodland_Vehicle_Commander
{
	CATEGORY(TWC_Infantry_Regular_Desert)
	uniformClass="U_LIB_UK_KhakiDrills";
};
class TWC_Infantry_WW2_UK_Late_Desert_Vehicle_Crew: TWC_Infantry_WW2_UK_Late_Woodland_Vehicle_Crew
{
	CATEGORY(TWC_Infantry_Regular_Desert)
	uniformClass="U_LIB_UK_KhakiDrills";
};