//UK, DISMOUTNED, WOODLAND
//Section
class TWC_Infantry_WW2_UK_Late_Dismounted_Woodland_Rifleman: TWC_Infantry_WW2_UK_Late_Woodland_Rifleman
{
	CATEGORY(TWC_Infantry_Dismounted_Woodland)
	backpack = "TWC_Backpack_WW2_UK_Late_Dismounted_Rifleman";
};
class TWC_Infantry_WW2_UK_Late_Dismounted_Woodland_Grenadier: TWC_Infantry_WW2_UK_Late_Woodland_Grenadier
{
	CATEGORY(TWC_Infantry_Dismounted_Woodland)
	backpack = "TWC_Backpack_WW2_UK_Late_Dismounted_Grenadier";
};
class TWC_Infantry_WW2_UK_Late_Dismounted_Woodland_SMG: TWC_Infantry_WW2_UK_Late_Woodland_SMG
{
	CATEGORY(TWC_Infantry_Dismounted_Woodland)
	backpack = "TWC_Backpack_WW2_UK_Late_Dismounted_SMG";
};
class TWC_Infantry_WW2_UK_Late_Dismounted_Woodland_MG: TWC_Infantry_WW2_UK_Late_Woodland_MG
{
	CATEGORY(TWC_Infantry_Dismounted_Woodland)
	backpack = "TWC_Backpack_WW2_UK_Late_Dismounted_MG";
};
class TWC_Infantry_WW2_UK_Late_Dismounted_Woodland_MGASS: TWC_Infantry_WW2_UK_Late_Woodland_MGASS
{
	CATEGORY(TWC_Infantry_Dismounted_Woodland)
	backpack = "TWC_Backpack_WW2_UK_Late_Dismounted_MGASS";
};
class TWC_Infantry_WW2_UK_Late_Dismounted_Woodland_SectionCommander: TWC_Infantry_WW2_UK_Late_Woodland_SectionCommander
{
	CATEGORY(TWC_Infantry_Dismounted_Woodland)
	backpack = "TWC_Backpack_WW2_UK_Late_Dismounted_SectionCommander";
};
class TWC_Infantry_WW2_UK_Late_Dismounted_Woodland_2iC: TWC_Infantry_WW2_UK_Late_Woodland_2iC
{
	CATEGORY(TWC_Infantry_Dismounted_Woodland)
	backpack = "TWC_Backpack_WW2_UK_Late_Dismounted_2iC";
};

//Platoon
class TWC_Infantry_WW2_UK_Late_Dismounted_Woodland_Platoon_Commander: TWC_Infantry_WW2_UK_Late_Woodland_Platoon_Commander
{
	CATEGORY(TWC_Infantry_Dismounted_Woodland)
	backpack = "TWC_Backpack_WW2_UK_Late_Dismounted_Platoon_Commander";
};
class TWC_Infantry_WW2_UK_Late_Dismounted_Woodland_Platoon_Sergeant: TWC_Infantry_WW2_UK_Late_Woodland_Platoon_Sergeant
{
	CATEGORY(TWC_Infantry_Dismounted_Woodland)
	backpack = "TWC_Backpack_WW2_UK_Late_Dismounted_Platoon_Sergeant";
};
class TWC_Infantry_WW2_UK_Late_Dismounted_Woodland_Platoon_Medic: TWC_Infantry_WW2_UK_Late_Woodland_Platoon_Medic
{
	CATEGORY(TWC_Infantry_Dismounted_Woodland)
	backpack = "TWC_Backpack_WW2_UK_Late_Dismounted_Platoon_Medic";
};
class TWC_Infantry_WW2_UK_Late_Dismounted_Woodland_Platoon_Runner: TWC_Infantry_WW2_UK_Late_Woodland_Platoon_Runner
{
	CATEGORY(TWC_Infantry_Dismounted_Woodland)
	backpack = "TWC_Backpack_WW2_UK_Late_Dismounted_Rifleman";
};
class TWC_Infantry_WW2_UK_Late_Dismounted_Woodland_Platoon_Mortar: TWC_Infantry_WW2_UK_Late_Woodland_Platoon_Mortar
{
	CATEGORY(TWC_Infantry_Dismounted_Woodland)
	backpack = "TWC_Backpack_WW2_UK_Late_Dismounted_Platoon_Mortar";
};
class TWC_Infantry_WW2_UK_Late_Dismounted_Woodland_Platoon_CSM: TWC_Infantry_WW2_UK_Late_Woodland_Platoon_CSM
{
	CATEGORY(TWC_Infantry_Dismounted_Woodland)
	backpack = "TWC_Backpack_WW2_UK_Late_Dismounted_Platoon_Sergeant";
};