	class PAVN_Base: O_Soldier_base_F
	{
		scope=1;
		displayName="Base";
		faction="TWC_ColdWar";
		editorSubcategory = "Men_PAVN";
		vehicleClass="Men_PAVN";
		icon="iconMan";
		nakedUniform="U_BasicBody";
		uniformClass="UNS_NVA_G";
		backpack="";
		linkedItems[]=
		{
			"UNS_NVA_A2",
			"UNS_NVA_HG",
			"ItemCompass",
			"itemMap",
			"ItemWatch"
		};
		respawnLinkedItems[]=
		{
			"UNS_NVA_A2",
			"UNS_NVA_HG",
			"ItemCompass",
			"itemMap",
			"ItemWatch"
		};
		Items[]=
		{
			"ACE_EarPlugs",
			"ACE_fieldDressing",
			"ACE_fieldDressing",
			"ACE_fieldDressing",
			"ACE_fieldDressing",
			"ACE_packingBandage",
			"ACE_packingBandage",
			"ACE_packingBandage",
			"ACE_packingBandage",
			"ACE_packingBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_quikclot",
			"ACE_quikclot",
			"ACE_morphine",
			"ACE_epinephrine",
			"ACE_tourniquet",
			"ACE_tourniquet"
		};
		respawntems[]=
		{
			"ACE_EarPlugs",
			"ACE_fieldDressing",
			"ACE_fieldDressing",
			"ACE_fieldDressing",
			"ACE_fieldDressing",
			"ACE_packingBandage",
			"ACE_packingBandage",
			"ACE_packingBandage",
			"ACE_packingBandage",
			"ACE_packingBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_quikclot",
			"ACE_quikclot",
			"ACE_morphine",
			"ACE_epinephrine",
			"ACE_tourniquet",
			"ACE_tourniquet"		
		};		
	};
	class PAVN_SquadCommander: PAVN_Base
	{
		scope=2;
		displayName="Squad Commander";
		icon="iconManLeader";
		backpack="Backpack_PAVN_Radio";
		class EventHandlers: EventHandlers
		{
			init = "if(local (_this select 0)) then{(_this select 0) setVariable [""twc_keepMap"",true]};";
		};
		linkedItems[]=
		{
			"UNS_NVA_A1",
			"UNS_NVA_HGG",
			"ItemCompass",
			"itemMap",
			"ItemWatch"
		};
		respawnLinkedItems[]=
		{
			"UNS_NVA_A1",
			"UNS_NVA_HGG",
			"ItemCompass",
			"itemMap",
			"ItemWatch"
		};
		weapons[]=
		{
			"Throw",
			"Put",	
			"uns_sks"	
		};
		respawnweapons[]=
		{
			"Throw",
			"Put",	
			"uns_sks"
		};
		magazines[]=
		{
			"uns_sksmag_NT",
			"uns_sksmag_NT",
			"uns_sksmag_NT",
			"uns_sksmag_NT",
			"uns_sksmag_NT",
			"uns_sksmag_NT",
			"uns_sksmag_NT",
			"uns_sksmag_NT",
			"uns_sksmag_NT",
			"uns_sksmag_NT",
			"uns_sksmag_NT",
			"uns_t67gren",
			"SmokeShell",
			"SmokeShell",
			"SmokeShell"
		};
		Respawnmagazines[]=
		{
			"uns_sksmag_NT",
			"uns_sksmag_NT",
			"uns_sksmag_NT",
			"uns_sksmag_NT",
			"uns_sksmag_NT",
			"uns_sksmag_NT",
			"uns_sksmag_NT",
			"uns_sksmag_NT",
			"uns_sksmag_NT",
			"uns_sksmag_NT",
			"uns_sksmag_NT",
			"uns_t67gren",
			"SmokeShell",
			"SmokeShell",
			"SmokeShell"
		};
	};
	class PAVN_CellLeader_Ass: PAVN_Base
	{
		scope=2;
		displayName="Cell Commander (Assault)";
		backpack="Backpack_PAVN_CellLeader_Ass";
		weapons[]=
		{
			"Throw",
			"Put",	
			"uns_k50mdrum"
		};
		respawnweapons[]=
		{
			"Throw",
			"Put",	
			"uns_k50mdrum"
		};
		magazines[]=
		{
			"uns_ppshmag",
			"uns_ppshmag",
			"uns_ppshmag",
			"uns_ppshmag",
			"uns_ppshmag",
			"uns_t67gren",
			"uns_t67gren",
			"uns_t67gren",
			"uns_t67gren",
			"SmokeShell"
		};
		Respawnmagazines[]=
		{
			"uns_ppshmag",
			"uns_ppshmag",
			"uns_ppshmag",
			"uns_ppshmag",
			"uns_ppshmag",
			"uns_t67gren",
			"uns_t67gren",
			"uns_t67gren",
			"uns_t67gren",
			"SmokeShell"
		};
	};
	class PAVN_CellLeader_AT: PAVN_Base
	{
		scope=2;
		displayName="Cell Leader (AT)";
		backpack="Backpack_PAVN_CellLeader_AT";
		weapons[]=
		{
			"Throw",
			"Put",	
			"CUP_arifle_AKM"	
		};
		respawnweapons[]=
		{
			"Throw",
			"Put",	
			"CUP_arifle_AKM"
		};
		magazines[]=
		{
			"CUP_30Rnd_762x39_AK47_M",
			"CUP_30Rnd_762x39_AK47_M",
			"CUP_30Rnd_762x39_AK47_M",
			"CUP_30Rnd_762x39_AK47_M",
			"CUP_30Rnd_762x39_AK47_M",
			"CUP_30Rnd_762x39_AK47_M",
			"CUP_30Rnd_762x39_AK47_M",
			"uns_t67gren",
			"uns_t67gren",
			"SmokeShell"
		};
		Respawnmagazines[]=
		{
			"CUP_30Rnd_762x39_AK47_M",
			"CUP_30Rnd_762x39_AK47_M",
			"CUP_30Rnd_762x39_AK47_M",
			"CUP_30Rnd_762x39_AK47_M",
			"CUP_30Rnd_762x39_AK47_M",
			"CUP_30Rnd_762x39_AK47_M",
			"CUP_30Rnd_762x39_AK47_M",
			"uns_t67gren",
			"uns_t67gren",
			"SmokeShell"
		};
	};
	class PAVN_CellLeader_MG: PAVN_CellLeader_AT
	{
		displayName="Cell Leader (MG)";
		backpack="Backpack_PAVN_CellLeader_MG";
		linkedItems[]=
		{
			"UNS_NVA_S1",
			"UNS_NVA_HG",
			"ItemCompass",
			"itemMap",
			"ItemWatch"
		};
		respawnLinkedItems[]=
		{
			"UNS_NVA_S1",
			"UNS_NVA_HG",
			"ItemCompass",
			"itemMap",
			"ItemWatch"
		};
		weapons[]=
		{
			"Throw",
			"Put",	
			"uns_sks"	
		};
		respawnweapons[]=
		{
			"Throw",
			"Put",	
			"uns_sks"
		};
		magazines[]=
		{
			"uns_sksmag_NT",
			"uns_sksmag_NT",
			"uns_sksmag_NT",
			"uns_sksmag_NT",
			"uns_sksmag_NT",
			"uns_sksmag_NT",
			"uns_sksmag_NT",
			"uns_sksmag_NT",
			"uns_sksmag_NT",
			"uns_sksmag_NT",
			"uns_sksmag_NT",
			"uns_sksmag_NT",
			"uns_sksmag_NT",
			"uns_sksmag_NT",
			"uns_t67gren",
			"uns_t67gren",
			"SmokeShell"
		};
		Respawnmagazines[]=
		{
			"uns_sksmag_NT",
			"uns_sksmag_NT",
			"uns_sksmag_NT",
			"uns_sksmag_NT",
			"uns_sksmag_NT",
			"uns_sksmag_NT",
			"uns_sksmag_NT",
			"uns_sksmag_NT",
			"uns_sksmag_NT",
			"uns_sksmag_NT",
			"uns_sksmag_NT",
			"uns_sksmag_NT",
			"uns_sksmag_NT",
			"uns_sksmag_NT",
			"uns_t67gren",
			"uns_t67gren",
			"SmokeShell"
		};
	};
	class PAVN_Assaulter: PAVN_Base
	{
		scope=2;
		displayName="Assaulter";
		weapons[]=
		{
			"Throw",
			"Put",	
			"uns_k50mdrum"
		};
		respawnweapons[]=
		{
			"Throw",
			"Put",	
			"uns_k50mdrum"
		};
		magazines[]=
		{
			"uns_ppshmag",
			"uns_ppshmag",
			"uns_ppshmag",
			"uns_ppshmag",
			"uns_ppshmag",
			"uns_t67gren",
			"uns_t67gren",
			"uns_t67gren",
			"uns_t67gren"
		};
		Respawnmagazines[]=
		{
			"uns_ppshmag",
			"uns_ppshmag",
			"uns_ppshmag",
			"uns_ppshmag",
			"uns_ppshmag",
			"uns_t67gren",
			"uns_t67gren",
			"uns_t67gren",
			"uns_t67gren"
		};
	};
	class PAVN_ATRifleman: PAVN_Base
	{
		scope=2;
		displayName="AT Rifleman";
		backpack="Backpack_PAVN_RPG";
		weapons[]=
		{
			"Throw",
			"Put",	
			"CUP_arifle_AKM",
			"CUP_launch_RPG7V"
		};
		respawnweapons[]=
		{
			"Throw",
			"Put",	
			"CUP_arifle_AKM",
			"CUP_launch_RPG7V"
		};
		magazines[]=
		{
			"CUP_30Rnd_762x39_AK47_M",
			"CUP_30Rnd_762x39_AK47_M",
			"CUP_30Rnd_762x39_AK47_M",
			"CUP_30Rnd_762x39_AK47_M",
			"CUP_30Rnd_762x39_AK47_M",
			"CUP_30Rnd_762x39_AK47_M",
			"CUP_30Rnd_762x39_AK47_M",
			"uns_t67gren",
			"uns_t67gren"
		};
		Respawnmagazines[]=
		{
			"CUP_30Rnd_762x39_AK47_M",
			"CUP_30Rnd_762x39_AK47_M",
			"CUP_30Rnd_762x39_AK47_M",
			"CUP_30Rnd_762x39_AK47_M",
			"CUP_30Rnd_762x39_AK47_M",
			"CUP_30Rnd_762x39_AK47_M",
			"CUP_30Rnd_762x39_AK47_M",
			"uns_t67gren",
			"uns_t67gren"
		};
	};
	class PAVN_ATAssistant: PAVN_ATRifleman
	{
		displayName="AT Assistant";
		weapons[]=
		{
			"Throw",
			"Put",	
			"CUP_arifle_AKM"
		};
		respawnweapons[]=
		{
			"Throw",
			"Put",	
			"CUP_arifle_AKM"
		};
	};
	class PAVN_Machinegunner: PAVN_Base
	{
		scope=2;
		displayName="Machine Gunner";
		icon="iconManMG";
		weapons[]=
		{
			"Throw",
			"Put",	
			"CUP_lmg_PKM"
		};
		respawnweapons[]=
		{
			"Throw",
			"Put",	
			"CUP_lmg_PKM"
		};
		magazines[]=
		{
			"CUP_100Rnd_TE4_LRT4_762x54_PK_Tracer_Green_M",	
			"CUP_100Rnd_TE4_LRT4_762x54_PK_Tracer_Green_M",
			"uns_t67gren"
		};
		Respawnmagazines[]=
		{
			"CUP_100Rnd_TE4_LRT4_762x54_PK_Tracer_Green_M",	
			"CUP_100Rnd_TE4_LRT4_762x54_PK_Tracer_Green_M",
			"uns_t67gren"
		};		
	};
	class PAVN_MGAssistant: PAVN_CellLeader_MG
	{
		displayName="Machine Gunner Assistant";
		backpack="Backpack_PAVN_MG";
		magazines[]=
		{
			"uns_sksmag_NT",
			"uns_sksmag_NT",
			"uns_sksmag_NT",
			"uns_sksmag_NT",
			"uns_sksmag_NT",
			"uns_sksmag_NT",
			"uns_sksmag_NT",
			"uns_sksmag_NT",
			"uns_sksmag_NT",
			"uns_sksmag_NT",
			"uns_sksmag_NT",
			"uns_sksmag_NT",
			"uns_sksmag_NT",
			"uns_sksmag_NT",
			"uns_t67gren",
			"uns_t67gren"
		};
		Respawnmagazines[]=
		{
			"uns_sksmag_NT",
			"uns_sksmag_NT",
			"uns_sksmag_NT",
			"uns_sksmag_NT",
			"uns_sksmag_NT",
			"uns_sksmag_NT",
			"uns_sksmag_NT",
			"uns_sksmag_NT",
			"uns_sksmag_NT",
			"uns_sksmag_NT",
			"uns_sksmag_NT",
			"uns_sksmag_NT",
			"uns_sksmag_NT",
			"uns_sksmag_NT",
			"uns_t67gren",
			"uns_t67gren"
		};
	};
	class PAVN_PlatoonCommander: PAVN_SquadCommander
	{
		displayName="Platoon Commander";
		backpack="Backpack_PAVN_Radio";
		class EventHandlers: EventHandlers
		{
			init = "if(local (_this select 0)) then{(_this select 0) setVariable [""twc_keepMap"",true]};";
		};
		linkedItems[]=
		{
			"Binocular",
			"UNS_NVA_S1",
			"UNS_NVA_HGG",
			"ItemCompass",
			"itemMap",
			"ItemWatch"
		};
		respawnLinkedItems[]=
		{
			"Binocular",
			"UNS_NVA_S1",
			"UNS_NVA_HGG",
			"ItemCompass",
			"itemMap",
			"ItemWatch"
		};
		weapons[]=
		{
			"Throw",
			"Put",	
			"uns_sks"	
		};
		respawnweapons[]=
		{
			"Throw",
			"Put",	
			"uns_sks"
		};
		magazines[]=
		{
			"uns_sksmag_NT",
			"uns_sksmag_NT",
			"uns_sksmag_NT",
			"uns_sksmag_NT",
			"uns_sksmag_NT",
			"uns_sksmag_NT",
			"uns_sksmag_NT",
			"uns_sksmag_NT",
			"uns_sksmag_NT",
			"uns_sksmag_NT",
			"uns_sksmag_NT",
			"uns_sksmag_NT",
			"uns_sksmag_NT",
			"uns_sksmag_NT",
			"uns_t67gren",
			"uns_t67gren",
			"SmokeShell"
		};
		Respawnmagazines[]=
		{
			"uns_sksmag_NT",
			"uns_sksmag_NT",
			"uns_sksmag_NT",
			"uns_sksmag_NT",
			"uns_sksmag_NT",
			"uns_sksmag_NT",
			"uns_sksmag_NT",
			"uns_sksmag_NT",
			"uns_sksmag_NT",
			"uns_sksmag_NT",
			"uns_sksmag_NT",
			"uns_sksmag_NT",
			"uns_sksmag_NT",
			"uns_sksmag_NT",
			"uns_t67gren",
			"uns_t67gren",
			"SmokeShell"
		};
	};
	class PAVN_PlatoonSergeant: PAVN_PlatoonCommander
	{
		displayName="Platoon Sergant";
		backpack="Backpack_PAVN_Radio";
	};
	class PAVN_Medic: PAVN_CellLeader_MG
	{
		displayName="Platoon Medic";
		icon="iconManMedic";
		backpack="Backpack_PAVN_Medic";
	};
	class PAVN_TankCommander: PAVN_Base
	{
		scope=2;
		displayName="Crew Commander";
		uniformClass="UNS_NVA_G";
		backpack="Backpack_PAVN_Radio";
		linkedItems[]=
		{
			"Binocular",
			"UNS_M1956_T1",
			"CUP_H_SLA_TankerHelmet",
			"ItemCompass",
			"itemMap",
			"ItemWatch"
		};
		respawnLinkedItems[]=
		{
			"Binocular",
			"UNS_M1956_T1",
			"CUP_H_SLA_TankerHelmet",
			"ItemCompass",
			"itemMap",
			"ItemWatch"
		};
		weapons[]=
		{
			"Throw",
			"Put",	
			"uns_PPS43f"
		};
		respawnweapons[]=
		{
			"Throw",
			"Put",	
			"uns_PPS43f"
		};
		magazines[]=
		{
			"uns_k50mag_NT",
			"uns_k50mag_NT",
			"uns_k50mag_NT",
			"uns_k50mag_NT",
			"SmokeShell"
		};
		Respawnmagazines[]=
		{
			"uns_k50mag_NT",
			"uns_k50mag_NT",
			"uns_k50mag_NT",
			"uns_k50mag_NT",
			"SmokeShell"
		};
	};
	class PAVN_TankCrew: PAVN_TankCommander
	{
		displayName="Crewman";
		backpack="";
	};