//post cup update, russian sf enemies for domination
	class TWC_Russian_SF_Base:O_Soldier_base_F
	{
		scope=2;
		displayName="Rifleman";
		faction="twc_faction";
		editorSubcategory = "Men_Russiansof";
		vehicleClass="Men_Russiansof";
		icon="iconMan";
		nakedUniform="U_BasicBody";
		uniformClass="CUP_U_O_RUS_Gorka_Green";
		identityTypes[] = {"LanguageRUS","Head_Russian","Head_Asian"};
		//uniformClass="twc_cryeG3_russof_roll";
		backpack="";
		linkedItems[]=
		{
        "CUP_H_OpsCore_Green_SF",
        //"CUP_H_OpsCore_Covered_MCAM_SF",
		"ItemMap",
		"ItemCompass",
		"ItemWatch",
		"twc_oli_spc_squadleader"
		//"CUP_V_B_Armatus_BB_MCam"
		};
		respawnLinkedItems[]=
		{
        "CUP_H_OpsCore_Green_SF",
        //"CUP_H_OpsCore_Covered_MCAM_SF",
		"ItemMap",
		"ItemCompass",
		"ItemWatch",
		"twc_oli_spc_squadleader"
		//"CUP_V_B_Armatus_BB_MCam"
		};
		weapons[]=
		{
		"Throw",
		"Put",
		"CUP_launch_RPG18",
		"twc_ak74_sof",
		"CUP_hgun_Glock17"
		};
		respawnweapons[]=
		{
		"Throw",
		"Put",
		"CUP_launch_RPG18",
		"twc_ak74_sof",
		"CUP_hgun_Glock17"
		};
		magazines[]=
		{
		"CUP_17Rnd_9x19_glock17",
		"CUP_17Rnd_9x19_glock17",
		"CUP_30Rnd_545x39_AK_M",
		"CUP_30Rnd_545x39_AK_M",
		"CUP_30Rnd_545x39_AK_M",
		"CUP_30Rnd_545x39_AK_M",
		"CUP_30Rnd_545x39_AK_M",
		"CUP_30Rnd_545x39_AK_M",
		"CUP_30Rnd_545x39_AK_M",
		"SmokeShell"
		};
		Respawnmagazines[]=
		{
		"CUP_17Rnd_9x19_glock17",
		"CUP_17Rnd_9x19_glock17",
		"CUP_30Rnd_545x39_AK_M",
		"CUP_30Rnd_545x39_AK_M",
		"CUP_30Rnd_545x39_AK_M",
		"CUP_30Rnd_545x39_AK_M",
		"CUP_30Rnd_545x39_AK_M",
		"CUP_30Rnd_545x39_AK_M",
		"CUP_30Rnd_545x39_AK_M",
		"SmokeShell"
		};
		Items[]=
		{
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_morphine",
		"ACE_morphine",
		"ACE_EarPlugs"
		};
		respawntems[]=
		{
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_morphine",
		"ACE_morphine",
		"ACE_EarPlugs"	
		};		
	};
	class TWC_Russian_SF_SL:TWC_Russian_SF_Base
	{
		displayName="Squadleader";
		backpack="twc_russof_SL_backpack";
		linkedItems[]=
		{
        //"CUP_H_OpsCore_Covered_MCAM_SF",
        "CUP_H_RUS_6B27",
		"ItemMap",
		"ItemCompass",
		"ItemWatch",
		"CUP_V_RUS_6B3_Flora_1"
		//"CUP_V_B_LBT_LBV_MCam"
		};
		respawnLinkedItems[]=
		{
        //"CUP_H_OpsCore_Covered_MCAM_SF",
        "CUP_H_RUS_6B27",
		"ItemMap",
		"ItemCompass",
		"ItemWatch",
		"CUP_V_RUS_6B3_Flora_1"
		//"CUP_V_B_LBT_LBV_MCam"
		};
		weapons[]=
		{
		"Throw",
		"Put",
		"twc_ak74_sof_afg_suppressed",
		"CUP_hgun_Glock17"
		};
		respawnweapons[]=
		{
		"Throw",
		"Put",
		"twc_ak74_sof_afg_suppressed",
		"CUP_hgun_Glock17"
		};
		magazines[]=
		{
		"CUP_17Rnd_9x19_glock17",
		"CUP_17Rnd_9x19_glock17",
		"CUP_30Rnd_545x39_AK_M",
		"CUP_30Rnd_545x39_AK_M",
		"CUP_30Rnd_545x39_AK_M",
		"CUP_30Rnd_545x39_AK_M",
		"CUP_30Rnd_545x39_AK_M",
		"CUP_30Rnd_545x39_AK_M",
		"CUP_30Rnd_545x39_AK_M",
		"SmokeShell",
		"SmokeShell"
		};
		Respawnmagazines[]=
		{
		"CUP_17Rnd_9x19_glock17",
		"CUP_17Rnd_9x19_glock17",
		"CUP_30Rnd_545x39_AK_M",
		"CUP_30Rnd_545x39_AK_M",
		"CUP_30Rnd_545x39_AK_M",
		"CUP_30Rnd_545x39_AK_M",
		"CUP_30Rnd_545x39_AK_M",
		"CUP_30Rnd_545x39_AK_M",
		"CUP_30Rnd_545x39_AK_M",
		"SmokeShell",
		"SmokeShell"
		};	
	};
	class TWC_Russian_SF_SMG:TWC_Russian_SF_Base
	{
		displayName="Submachinegunner";
		linkedItems[]=
		{
        //"CUP_H_OpsCore_Covered_MCAM_SF",
        "CUP_H_RUS_6B27_goggles",
		"ItemMap",
		"ItemCompass",
		"ItemWatch",
		"CUP_V_RUS_6B3_Flora_1"
		//"CUP_V_B_LBT_LBV_MCam"
		};
		respawnLinkedItems[]=
		{
        //"CUP_H_OpsCore_Covered_MCAM_SF",
        "CUP_H_RUS_6B27_goggles",
		"ItemMap",
		"ItemCompass",
		"ItemWatch",
		"CUP_V_RUS_6B3_Flora_1"
		//"CUP_V_B_LBT_LBV_MCam"
		};
		weapons[]=
		{
		"Throw",
		"Put",
		"CUP_launch_RPG18",
		"CUP_smg_bizon_snds",
		"CUP_hgun_Glock17"
		};
		respawnweapons[]=
		{
		"Throw",
		"Put",
		"CUP_launch_RPG18",
		"CUP_smg_bizon_snds",
		"CUP_hgun_Glock17"
		};
		magazines[]=
		{
		"CUP_17Rnd_9x19_glock17",
		"CUP_17Rnd_9x19_glock17",
		"CUP_64Rnd_9x19_Bizon_M",
		"CUP_64Rnd_9x19_Bizon_M",
		"CUP_64Rnd_9x19_Bizon_M",
		"CUP_64Rnd_9x19_Bizon_M",
		"CUP_64Rnd_9x19_Bizon_M",
		"CUP_64Rnd_9x19_Bizon_M",
		"CUP_64Rnd_9x19_Bizon_M",
		"CUP_64Rnd_9x19_Bizon_M",
		"CUP_64Rnd_9x19_Bizon_M"
		};
		Respawnmagazines[]=
		{
		"CUP_17Rnd_9x19_glock17",
		"CUP_17Rnd_9x19_glock17",
		"CUP_64Rnd_9x19_Bizon_M",
		"CUP_64Rnd_9x19_Bizon_M",
		"CUP_64Rnd_9x19_Bizon_M",
		"CUP_64Rnd_9x19_Bizon_M",
		"CUP_64Rnd_9x19_Bizon_M",
		"CUP_64Rnd_9x19_Bizon_M",
		"CUP_64Rnd_9x19_Bizon_M",
		"CUP_64Rnd_9x19_Bizon_M",
		"CUP_64Rnd_9x19_Bizon_M"
		};	
	};
	class TWC_Russian_SF_MG:TWC_Russian_SF_Base
	{
		displayName="Machinegunner";
		backpack="twc_russof_MG_backpack";
		linkedItems[]=
		{
        //"CUP_H_OpsCore_Covered_MCAM_SF",
        "CUP_H_OpsCore_Green",
		"ItemMap",
		"ItemCompass",
		"ItemWatch",
		"CUP_V_RUS_6B3_Flora_1"
		};
		respawnLinkedItems[]=
		{
        //"CUP_H_OpsCore_Covered_MCAM_SF",
        "CUP_H_OpsCore_Green",
		"ItemMap",
		"ItemCompass",
		"ItemWatch",
		"CUP_V_RUS_6B3_Flora_1"
		};
		weapons[]=
		{
		"Throw",
		"Put",
		"twc_pkp_sof",
		"CUP_hgun_Glock17"
		};
		respawnweapons[]=
		{
		"Throw",
		"Put",
		"twc_pkp_sof",
		"CUP_hgun_Glock17"
		};
		magazines[]=
		{
		"CUP_17Rnd_9x19_glock17",
		"CUP_17Rnd_9x19_glock17",
		"CUP_100Rnd_TE4_LRT4_762x54_PK_Tracer_Green_M",
		"CUP_100Rnd_TE4_LRT4_762x54_PK_Tracer_Green_M",
		"CUP_100Rnd_TE4_LRT4_762x54_PK_Tracer_Green_M",
		"SmokeShell"
		};
		Respawnmagazines[]=
		{
		"CUP_17Rnd_9x19_glock17",
		"CUP_17Rnd_9x19_glock17",
		"CUP_100Rnd_TE4_LRT4_762x54_PK_Tracer_Green_M",
		"CUP_100Rnd_TE4_LRT4_762x54_PK_Tracer_Green_M",
		"CUP_100Rnd_TE4_LRT4_762x54_PK_Tracer_Green_M",
		"SmokeShell"
		};	
	};

	class Russian_Squadleader:O_Soldier_base_F
	{
		_generalMacro="Russian_Squadleader";
		scope=2;
		displayName="Section Leader";
		faction="twc_faction";
		editorSubcategory = "Men_RussianFederation";
		vehicleClass="Men_RussianFederation";
		icon="iconMan";
		nakedUniform="U_BasicBody";
		uniformClass="CUP_U_O_RUS_VSR98_MSV";
		backpack="TWC_Backpack_USSR_Sectionlead";
		linkedItems[]=
		{
        "CUP_V_RUS_6B3_Flora_1",
		"ItemMap",
		"ItemCompass",
		"ItemWatch",
		"CUP_H_RUS_6B27_headset_goggles",
		"ACRE_PRC343"
		};
		respawnLinkedItems[]=
		{
        "CUP_V_RUS_6B3_Flora_1",
		"ItemMap",
		"ItemCompass",
		"ItemWatch",
		"CUP_H_RUS_6B27_headset_goggles",
		"ACRE_PRC343"
		};
		weapons[]=
		{
		"Throw",
		"Put",
		"ACE_Vector",
		"CUP_arifle_AK74M",
		"CUP_hgun_Makarov"
		};
		respawnweapons[]=
		{
		"Throw",
		"Put",
		"ACE_Vector",
		"CUP_arifle_AK74M",
		"CUP_hgun_Makarov"
		};
		magazines[]=
		{
		"CUP_8Rnd_9x18_Makarov_M",
		"CUP_8Rnd_9x18_Makarov_M",
		"CUP_8Rnd_9x18_Makarov_M",
		"CUP_30Rnd_545x39_AK74M_M",
		"CUP_30Rnd_545x39_AK74M_M",
		"CUP_30Rnd_545x39_AK74M_M",
		"CUP_30Rnd_545x39_AK74M_M",
		"CUP_30Rnd_545x39_AK74M_M",
		"CUP_30Rnd_545x39_AK74M_M",
		"CUP_30Rnd_545x39_AK74M_M",
		"CUP_30Rnd_545x39_AK74M_M",
		"CUP_HandGrenade_RGD5",
		"CUP_HandGrenade_RGD5",
		"SmokeShell",
		"SmokeShell",
		"SmokeShell"
		};
		Respawnmagazines[]=
		{
		"CUP_8Rnd_9x18_Makarov_M",
		"CUP_8Rnd_9x18_Makarov_M",
		"CUP_8Rnd_9x18_Makarov_M",
		"CUP_30Rnd_545x39_AK74M_M",
		"CUP_30Rnd_545x39_AK74M_M",
		"CUP_30Rnd_545x39_AK74M_M",
		"CUP_30Rnd_545x39_AK74M_M",
		"CUP_30Rnd_545x39_AK74M_M",
		"CUP_30Rnd_545x39_AK74M_M",
		"CUP_30Rnd_545x39_AK74M_M",
		"CUP_30Rnd_545x39_AK74M_M",
		"CUP_HandGrenade_RGD5",
		"CUP_HandGrenade_RGD5",
		"SmokeShell",
		"SmokeShell",
		"SmokeShell"
		};
		Items[]=
		{
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_morphine",
		"ACE_morphine",
		"ACE_EarPlugs"
		};
		respawntems[]=
		{
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_morphine",
		"ACE_morphine",
		"ACE_EarPlugs"	
		};		
	};
	class Russian_Rifleman:O_Soldier_base_F
	{
		_generalMacro="Russian_Rifleman";
		scope=2;
		displayName="Rifleman";
		faction="twc_faction";
		editorSubcategory = "Men_RussianFederation";
		vehicleClass="Men_RussianFederation";
		icon="iconMan";
		nakedUniform="U_BasicBody";
		uniformClass="CUP_U_O_RUS_VSR98_MSV";
		backpack="TWC_Backpack_USSR_Rifleman";
		linkedItems[]=
		{
        "CUP_V_RUS_6B3_Flora_1",
		"ItemMap",
		"ItemCompass",
		"ItemWatch",
		"CUP_H_RUS_6B27_headset_goggles",
		"ACRE_PRC343"
		};
		respawnLinkedItems[]=
		{
        "CUP_V_RUS_6B3_Flora_1",
		"ItemMap",
		"ItemCompass",
		"ItemWatch",
		"CUP_H_RUS_6B27_headset_goggles",
		"ACRE_PRC343"
		};
		weapons[]=
		{
		"Throw",
		"Put",
		"CUP_arifle_AK74M",
		"CUP_hgun_Makarov"
		};
		respawnweapons[]=
		{
		"Throw",
		"Put",	
		"CUP_arifle_AK74M",
		"CUP_hgun_Makarov"
		};
		magazines[]=
		{
		"CUP_8Rnd_9x18_Makarov_M",
		"CUP_8Rnd_9x18_Makarov_M",
		"CUP_8Rnd_9x18_Makarov_M",
		"CUP_30Rnd_545x39_AK74M_M",
		"CUP_30Rnd_545x39_AK74M_M",
		"CUP_HandGrenade_RGD5",
		"CUP_HandGrenade_RGD5",
		"SmokeShell",
		"SmokeShell",
		"SmokeShell"
		};
		Respawnmagazines[]=
		{
		"CUP_8Rnd_9x18_Makarov_M",
		"CUP_8Rnd_9x18_Makarov_M",
		"CUP_8Rnd_9x18_Makarov_M",
		"CUP_30Rnd_545x39_AK74M_M",
		"CUP_30Rnd_545x39_AK74M_M",
		"CUP_HandGrenade_RGD5",
		"CUP_HandGrenade_RGD5",
		"SmokeShell",
		"SmokeShell",
		"SmokeShell"
		};
		Items[]=
		{
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_morphine",
		"ACE_morphine",
		"ACE_EarPlugs"
		};
		respawntems[]=
		{
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_morphine",
		"ACE_morphine",
		"ACE_EarPlugs"	
		};		
	};
	class Russian_Grenadier:O_Soldier_base_F
	{
		_generalMacro="Russian_Grenadier";
		scope=2;
		displayName="Grenadier";
		faction="twc_faction";
		editorSubcategory = "Men_RussianFederation";
		vehicleClass="Men_RussianFederation";
		icon="iconMan";
		nakedUniform="U_BasicBody";
		uniformClass="CUP_U_O_RUS_VSR98_MSV";
		backpack="TWC_Backpack_USSR_Grenadier";
		linkedItems[]=
		{
        "CUP_V_RUS_6B3_Flora_1",
		"ItemMap",
		"ItemCompass",
		"ItemWatch",
		"CUP_H_RUS_6B27_headset_goggles",
		"ACRE_PRC343"
		};
		respawnLinkedItems[]=
		{
        "CUP_V_RUS_6B3_Flora_1",
		"ItemMap",
		"ItemCompass",
		"ItemWatch",
		"CUP_H_RUS_6B27_headset_goggles",
		"ACRE_PRC343"
		};
		weapons[]=
		{
		"Throw",
		"Put",
		"CUP_arifle_AK74M",
		"CUP_launch_RPG7V_PGO7V",
		"CUP_hgun_Makarov"
		};
		respawnweapons[]=
		{
		"Throw",
		"Put",	
		"CUP_arifle_AK74M",
		"CUP_launch_RPG7V_PGO7V",
		"CUP_hgun_Makarov"
		};
		magazines[]=
		{
		"CUP_8Rnd_9x18_Makarov_M",
		"CUP_8Rnd_9x18_Makarov_M",
		"CUP_8Rnd_9x18_Makarov_M",
		"CUP_30Rnd_545x39_AK74M_M",
		"CUP_30Rnd_545x39_AK74M_M",
		"CUP_30Rnd_545x39_AK74M_M",
		"CUP_30Rnd_545x39_AK74M_M",
		"CUP_HandGrenade_RGD5",
		"CUP_HandGrenade_RGD5",
		"SmokeShell",
		"SmokeShell",
		"SmokeShell"
		};
		Respawnmagazines[]=
		{
		"CUP_8Rnd_9x18_Makarov_M",
		"CUP_8Rnd_9x18_Makarov_M",
		"CUP_8Rnd_9x18_Makarov_M",
		"CUP_30Rnd_545x39_AK74M_M",
		"CUP_30Rnd_545x39_AK74M_M",
		"CUP_30Rnd_545x39_AK74M_M",
		"CUP_30Rnd_545x39_AK74M_M",
		"CUP_HandGrenade_RGD5",
		"CUP_HandGrenade_RGD5",
		"SmokeShell",
		"SmokeShell",
		"SmokeShell"
		};
		Items[]=
		{
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_morphine",
		"ACE_morphine",
		"ACE_EarPlugs"
		};
		respawntems[]=
		{
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_morphine",
		"ACE_morphine",
		"ACE_EarPlugs"	
		};		
	};
	class Russian_Seniorrifleman:O_Soldier_base_F
	{
		_generalMacro="Russian_Seniorrifleman";
		scope=2;
		displayName="Senior Rifleman";
		faction="twc_faction";
		editorSubcategory = "Men_RussianFederation";
		vehicleClass="Men_RussianFederation";
		icon="iconMan";
		nakedUniform="U_BasicBody";
		uniformClass="CUP_U_O_RUS_VSR98_MSV";
		backpack="TWC_Backpack_USSR_Seniorrifleman";
		linkedItems[]=
		{
        "CUP_V_RUS_6B3_Flora_1",
		"ItemMap",
		"ItemCompass",
		"ItemWatch",
		"CUP_H_RUS_6B27_headset_goggles",
		"ACRE_PRC343"
		};
		respawnLinkedItems[]=
		{
        "CUP_V_RUS_6B3_Flora_1",
		"ItemMap",
		"ItemCompass",
		"ItemWatch",
		"CUP_H_RUS_6B27_headset_goggles",
		"ACRE_PRC343"
		};
		weapons[]=
		{
		"Throw",
		"Put",
		"ACE_Vector",
		"CUP_arifle_AK74M",
		"CUP_hgun_Makarov"
		};
		respawnweapons[]=
		{
		"Throw",
		"Put",
		"ACE_Vector",
		"CUP_arifle_AK74M",
		"CUP_hgun_Makarov"
		};
		magazines[]=
		{
		"CUP_8Rnd_9x18_Makarov_M",
		"CUP_8Rnd_9x18_Makarov_M",
		"CUP_8Rnd_9x18_Makarov_M",
		"CUP_30Rnd_545x39_AK74M_M",
		"CUP_30Rnd_545x39_AK74M_M",
		"CUP_HandGrenade_RGD5",
		"CUP_HandGrenade_RGD5",
		"SmokeShell",
		"SmokeShell",
		"SmokeShell"
		};
		Respawnmagazines[]=
		{
		"CUP_8Rnd_9x18_Makarov_M",
		"CUP_8Rnd_9x18_Makarov_M",
		"CUP_8Rnd_9x18_Makarov_M",
		"CUP_30Rnd_545x39_AK74M_M",
		"CUP_30Rnd_545x39_AK74M_M",
		"CUP_HandGrenade_RGD5",
		"CUP_HandGrenade_RGD5",
		"SmokeShell",
		"SmokeShell",
		"SmokeShell"
		};
		Items[]=
		{
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_morphine",
		"ACE_morphine",
		"ACE_EarPlugs"
		};
		respawntems[]=
		{
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_morphine",
		"ACE_morphine",
		"ACE_EarPlugs"	
		};		
	};
	class Russian_Grenadierassistant:O_Soldier_base_F
	{
		_generalMacro="Russian_Grenadierassistant";
		scope=2;
		displayName="Grenadier Assistant";
		faction="twc_faction";
		editorSubcategory = "Men_RussianFederation";
		vehicleClass="Men_RussianFederation";
		icon="iconMan";
		nakedUniform="U_BasicBody";
		uniformClass="CUP_U_O_RUS_VSR98_MSV";
		backpack="TWC_Backpack_USSR_Grenadierassistant";
		linkedItems[]=
		{
        "CUP_V_RUS_6B3_Flora_1",
		"ItemMap",
		"ItemCompass",
		"ItemWatch",
		"CUP_H_RUS_6B27_headset_goggles",
		"ACRE_PRC343"
		};
		respawnLinkedItems[]=
		{
        "CUP_V_RUS_6B3_Flora_1",
		"ItemMap",
		"ItemCompass",
		"ItemWatch",
		"CUP_H_RUS_6B27_headset_goggles",
		"ACRE_PRC343"
		};
		weapons[]=
		{
		"Throw",
		"Put",	
		"CUP_arifle_AK74M",
		"CUP_hgun_Makarov"
		};
		respawnweapons[]=
		{
		"Throw",
		"Put",	
		"CUP_arifle_AK74M",
		"CUP_hgun_Makarov"
		};
		magazines[]=
		{
		"CUP_8Rnd_9x18_Makarov_M",
		"CUP_8Rnd_9x18_Makarov_M",
		"CUP_8Rnd_9x18_Makarov_M",
		"CUP_30Rnd_545x39_AK74M_M",
		"CUP_30Rnd_545x39_AK74M_M",
		"CUP_30Rnd_545x39_AK74M_M",
		"CUP_30Rnd_545x39_AK74M_M",
		"CUP_HandGrenade_RGD5",
		"CUP_HandGrenade_RGD5",
		"SmokeShell",
		"SmokeShell",
		"SmokeShell"
		};
		Respawnmagazines[]=
		{
		"CUP_8Rnd_9x18_Makarov_M",
		"CUP_8Rnd_9x18_Makarov_M",
		"CUP_8Rnd_9x18_Makarov_M",
		"CUP_30Rnd_545x39_AK74M_M",
		"CUP_30Rnd_545x39_AK74M_M",
		"CUP_30Rnd_545x39_AK74M_M",
		"CUP_30Rnd_545x39_AK74M_M",
		"CUP_HandGrenade_RGD5",
		"CUP_HandGrenade_RGD5",
		"SmokeShell",
		"SmokeShell",
		"SmokeShell"
		};
		Items[]=
		{
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_morphine",
		"ACE_morphine",
		"ACE_EarPlugs"
		};
		respawntems[]=
		{
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_morphine",
		"ACE_morphine",
		"ACE_EarPlugs"	
		};		
	};
	class Russian_Automaticrifleman:O_Soldier_base_F
	{
		_generalMacro="Russian_Automaticrifleman";
		scope=2;
		displayName="Automatic Rifleman";
		faction="twc_faction";
		editorSubcategory = "Men_RussianFederation";
		vehicleClass="Men_RussianFederation";
		icon="iconMan";
		nakedUniform="U_BasicBody";
		uniformClass="CUP_U_O_RUS_VSR98_MSV";
		backpack="TWC_Backpack_USSR_Automaticrifleman";
		linkedItems[]=
		{
        "CUP_V_RUS_6B3_Flora_1",
		"ItemMap",
		"ItemCompass",
		"ItemWatch",
		"CUP_H_RUS_6B27_headset_goggles",
		"ACRE_PRC343"
		};
		respawnLinkedItems[]=
		{
        "CUP_V_RUS_6B3_Flora_1",
		"ItemMap",
		"ItemCompass",
		"ItemWatch",
		"CUP_H_RUS_6B27_headset_goggles",
		"ACRE_PRC343"
		};
		weapons[]=
		{
		"Throw",
		"Put",	
		"CUP_lmg_PKM",
		"CUP_hgun_Makarov"
		};
		respawnweapons[]=
		{
		"Throw",
		"Put",	
		"CUP_lmg_PKM",
		"CUP_hgun_Makarov"
		};
		magazines[]=
		{
		"CUP_8Rnd_9x18_Makarov_M",
		"CUP_8Rnd_9x18_Makarov_M",
		"CUP_8Rnd_9x18_Makarov_M",
		"CUP_100Rnd_TE4_LRT4_762x54_PK_Tracer_Green_M",
		"CUP_HandGrenade_RGD5",
		"CUP_HandGrenade_RGD5",
		"SmokeShell",
		"SmokeShell",
		"SmokeShell"
		};
		Respawnmagazines[]=
		{
		"CUP_8Rnd_9x18_Makarov_M",
		"CUP_8Rnd_9x18_Makarov_M",
		"CUP_8Rnd_9x18_Makarov_M",
		"CUP_100Rnd_TE4_LRT4_762x54_PK_Tracer_Green_M",
		"CUP_HandGrenade_RGD5",
		"CUP_HandGrenade_RGD5",
		"SmokeShell",
		"SmokeShell",
		"SmokeShell"
		};
		Items[]=
		{
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_morphine",
		"ACE_morphine",
		"ACE_EarPlugs"
		};
		respawntems[]=
		{
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_morphine",
		"ACE_morphine",
		"ACE_EarPlugs"	
		};		
	};
	class Russian_Vehiclecommander:O_Soldier_base_F
	{
		_generalMacro="Russian_Vehiclecommander";
		scope=2;
		displayName="Vehicle Commander";
		faction="twc_faction";
		editorSubcategory = "Men_RussianFederation";
		vehicleClass="Men_RussianFederation";
		icon="iconMan";
		nakedUniform="U_BasicBody";
		uniformClass="CUP_U_O_RUS_VSR98_MSV";
		backpack="TWC_Backpack_USSR_Vehiclecommander";
		linkedItems[]=
		{
        "CUP_V_O_TK_CrewBelt",
		"ItemMap",
		"ItemCompass",
		"ItemWatch",
		"CUP_H_SLA_TankerHelmet",
		"ACRE_PRC343"
		};
		respawnLinkedItems[]=
		{
        "CUP_V_O_TK_CrewBelt",
		"ItemMap",
		"ItemCompass",
		"ItemWatch",
		"CUP_H_SLA_TankerHelmet",
		"ACRE_PRC343"
		};
		weapons[]=
		{
		"Throw",
		"Put",
		"Binocular",
		"CUP_arifle_AKS74",
		"CUP_hgun_Makarov"
		};
		respawnweapons[]=
		{
		"Throw",
		"Put",
		"Binocular",
		"CUP_arifle_AKS74",
		"CUP_hgun_Makarov"
		};
		magazines[]=
		{
		"CUP_8Rnd_9x18_Makarov_M",
		"CUP_30Rnd_545x39_AK74M_M",
		"CUP_30Rnd_545x39_AK74M_M",
		"CUP_30Rnd_545x39_AK74M_M",
		"CUP_HandGrenade_RGD5",
		"SmokeShell"
		};
		Respawnmagazines[]=
		{
		"CUP_8Rnd_9x18_Makarov_M",
		"CUP_30Rnd_545x39_AK74M_M",
		"CUP_30Rnd_545x39_AK74M_M",
		"CUP_30Rnd_545x39_AK74M_M",
		"CUP_HandGrenade_RGD5",
		"SmokeShell"
		};
		Items[]=
		{
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_morphine",
		"ACE_morphine",
		"ACE_EarPlugs"
		};
		respawntems[]=
		{
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_morphine",
		"ACE_morphine",
		"ACE_EarPlugs"	
		};		
	};
	class Russian_Vehiclecrew:O_Soldier_base_F
	{
		_generalMacro="USSR_Vehiclecrew";
		scope=2;
		displayName="Vehicle Crew";
		faction="twc_faction";
		editorSubcategory = "Men_RussianFederation";
		vehicleClass="Men_RussianFederation";
		icon="iconMan";
		nakedUniform="U_BasicBody";
		uniformClass="CUP_U_O_RUS_VSR98_MSV";
		backpack="";
		linkedItems[]=
		{
        "CUP_V_O_TK_CrewBelt",
		"ItemMap",
		"ItemCompass",
		"ItemWatch",
		"CUP_H_SLA_TankerHelmet",
		"ACRE_PRC343"
		};
		respawnLinkedItems[]=
		{
        "CUP_V_O_TK_CrewBelt",
		"ItemMap",
		"ItemCompass",
		"ItemWatch",
		"CUP_H_SLA_TankerHelmet",
		"ACRE_PRC343"
		};
		weapons[]=
		{
		"Throw",
		"Put",	
		"CUP_arifle_AKS74",
		"CUP_hgun_Makarov"
		};
		respawnweapons[]=
		{
		"Throw",
		"Put",	
		"CUP_arifle_AKS74",
		"CUP_hgun_Makarov"
		};
		magazines[]=
		{
		"CUP_8Rnd_9x18_Makarov_M",
		"CUP_30Rnd_545x39_AK74M_M",
		"CUP_30Rnd_545x39_AK74M_M",
		"CUP_30Rnd_545x39_AK74M_M",
		"CUP_HandGrenade_RGD5",
		"SmokeShell"
		};
		Respawnmagazines[]=
		{
		"CUP_8Rnd_9x18_Makarov_M",
		"CUP_30Rnd_545x39_AK74M_M",
		"CUP_30Rnd_545x39_AK74M_M",
		"CUP_30Rnd_545x39_AK74M_M",
		"CUP_HandGrenade_RGD5",
		"SmokeShell"
		};
		Items[]=
		{
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_morphine",
		"ACE_morphine",
		"ACE_EarPlugs"
		};
		respawntems[]=
		{
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_morphine",
		"ACE_morphine",
		"ACE_EarPlugs"	
		};		
	};