//REGULAR, DISMOUNTED, NBC
//Section
class TWC_Infantry_2000_Regular_Dismounted_NBC_Rifleman: TWC_Infantry_2000_Regular_NBC_Rifleman
{
	CATEGORY(TWC_Infantry_Regular_Dismounted_2000_NBC)
	backpack = "TWC_Backpack_2000_Regular_Dismounted_Woodland_Rifleman";
};
class TWC_Infantry_2000_Regular_Dismounted_NBC_Marksman: TWC_Infantry_2000_Regular_NBC_Marksman
{
	CATEGORY(TWC_Infantry_Regular_Dismounted_2000_NBC)
	backpack = "TWC_Backpack_2000_Regular_Dismounted_Woodland_Marksman";
};
class TWC_Infantry_2000_Regular_Dismounted_NBC_Grenadier: TWC_Infantry_2000_Regular_NBC_Grenadier
{
	CATEGORY(TWC_Infantry_Regular_Dismounted_2000_NBC)
	backpack = "TWC_Backpack_2000_Regular_Dismounted_Woodland_Grenadier";
};
class TWC_Infantry_2000_Regular_Dismounted_NBC_Autorifleman: TWC_Infantry_2000_Regular_NBC_Autorifleman
{
	CATEGORY(TWC_Infantry_Regular_Dismounted_2000_NBC)
	backpack = "TWC_Backpack_2000_Regular_Dismounted_Woodland_Autorifleman";
};
class TWC_Infantry_2000_Regular_Dismounted_NBC_SectionCommander: TWC_Infantry_2000_Regular_NBC_SectionCommander
{
	CATEGORY(TWC_Infantry_Regular_Dismounted_2000_NBC)
	backpack = "TWC_Backpack_2000_Regular_Dismounted_Woodland_SectionCommander";
};
class TWC_Infantry_2000_Regular_Dismounted_NBC_2iC: TWC_Infantry_2000_Regular_NBC_2iC
{
	CATEGORY(TWC_Infantry_Regular_Dismounted_2000_NBC)
	backpack = "TWC_Backpack_2000_Regular_Dismounted_Woodland_2iC";
};

//Platoon Command
class TWC_Infantry_2000_Regular_Dismounted_NBC_Platoon_Commander: TWC_Infantry_2000_Regular_NBC_Platoon_Commander
{
	CATEGORY(TWC_Infantry_Regular_Dismounted_2000_NBC)
	backpack = "TWC_Backpack_2000_Regular_Dismounted_Woodland_Platoon_Commander";
};
class TWC_Infantry_2000_Regular_Dismounted_NBC_Platoon_Sergeant: TWC_Infantry_2000_Regular_NBC_Platoon_Sergeant
{
	CATEGORY(TWC_Infantry_Regular_Dismounted_2000_NBC)
	backpack = "TWC_Backpack_2000_Regular_Dismounted_Woodland_Platoon_Sergeant";
};
class TWC_Infantry_2000_Regular_Dismounted_NBC_Platoon_Medic: TWC_Infantry_2000_Regular_NBC_Platoon_Medic
{
	CATEGORY(TWC_Infantry_Regular_Dismounted_2000_NBC)
	backpack = "TWC_Backpack_2000_Regular_Dismounted_Woodland_Platoon_Medic";
};
class TWC_Infantry_2000_Regular_Dismounted_NBC_Platoon_CSM: TWC_Infantry_2000_Regular_NBC_Platoon_CSM
{
	CATEGORY(TWC_Infantry_Regular_Dismounted_2000_NBC)
	backpack = "TWC_Backpack_2000_Regular_Dismounted_Woodland_Platoon_Sergeant";
};

//Company
class TWC_Infantry_2000_Regular_Dismounted_NBC_Company_Commander: TWC_Infantry_2000_Regular_NBC_Company_Commander
{
	CATEGORY(TWC_Infantry_Regular_Dismounted_2000_NBC)
	backpack = "TWC_Backpack_2000_Regular_Dismounted_Woodland_Platoon_Commander";
};
class TWC_Infantry_2000_Regular_Dismounted_NBC_Company_2iC: TWC_Infantry_2000_Regular_NBC_Company_2iC
{
	CATEGORY(TWC_Infantry_Regular_Dismounted_2000_NBC)
	backpack = "TWC_Backpack_2000_Regular_Dismounted_Woodland_Platoon_Commander";
};
class TWC_Infantry_2000_Regular_Dismounted_NBC_Company_Sergeant: TWC_Infantry_2000_Regular_NBC_Company_Sergeant
{
	CATEGORY(TWC_Infantry_Regular_Dismounted_2000_NBC)
	backpack = "TWC_Backpack_2000_Regular_Dismounted_Woodland_Platoon_Sergeant";
};