#include "defines.sqf";
#include "sys_gameStart\init.sqf";
#include "func\init.sqf";
#include "arsenal\init.sqf";
#include "sys_sites\init.sqf";
#include "sys_roadBlocks\init.sqf";
#include "sys_playerBase\init.sqf";
#include "sys_eventHandlers\init.sqf";
execVM "server\sys_main\init.sqf";