//REGULAR, DISMOUNTED, ARCTIC
//Section
class TWC_Infantry_ColdWar_Regular_Dismounted_Arctic_Rifleman: TWC_Infantry_ColdWar_Regular_Arctic_Rifleman
{
	CATEGORY(TWC_Infantry_Dismounted_Arctic)
	backpack = "TWC_Backpack_ColdWar_Regular_Dismounted_Rifleman";
};
class TWC_Infantry_ColdWar_Regular_Dismounted_Arctic_Rifleman_SUIT: TWC_Infantry_ColdWar_Regular_Arctic_Rifleman_SUIT
{
	CATEGORY(TWC_Infantry_Dismounted_Arctic)
	backpack = "TWC_Backpack_ColdWar_Regular_Dismounted_Rifleman";
};
class TWC_Infantry_ColdWar_Regular_Dismounted_Arctic_SectionCommander: TWC_Infantry_ColdWar_Regular_Arctic_SectionCommander
{
	CATEGORY(TWC_Infantry_Dismounted_Arctic)
};
class TWC_Infantry_ColdWar_Regular_Dismounted_Arctic_2iC: TWC_Infantry_ColdWar_Regular_Arctic_2iC
{
	CATEGORY(TWC_Infantry_Dismounted_Arctic)
};
class TWC_Infantry_ColdWar_Regular_Dismounted_Arctic_AT: TWC_Infantry_ColdWar_Regular_Arctic_AT
{
	CATEGORY(TWC_Infantry_Dismounted_Arctic)
	backpack = "TWC_Backpack_ColdWar_Regular_Dismounted_AT";
};
class TWC_Infantry_ColdWar_Regular_Dismounted_Arctic_ASSAT: TWC_Infantry_ColdWar_Regular_Arctic_ASSAT
{
	CATEGORY(TWC_Infantry_Dismounted_Arctic)
	backpack = "TWC_Backpack_ColdWar_Regular_Dismounted_ATASS";
};
class TWC_Infantry_ColdWar_Regular_Dismounted_Arctic_MG: TWC_Infantry_ColdWar_Regular_Arctic_MG
{
	CATEGORY(TWC_Infantry_Dismounted_Arctic)
	backpack = "TWC_Backpack_ColdWar_Regular_Dismounted_MG";
};
class TWC_Infantry_ColdWar_Regular_Dismounted_Arctic_ASSMG: TWC_Infantry_ColdWar_Regular_Arctic_ASSMG
{
	CATEGORY(TWC_Infantry_Dismounted_Arctic)
	backpack = "TWC_Backpack_ColdWar_Regular_Dismounted_ASSMG";
};

//Platoon Command
class TWC_Infantry_ColdWar_Regular_Dismounted_Arctic_Platoon_Commander: TWC_Infantry_ColdWar_Regular_Arctic_Platoon_Commander
{
	CATEGORY(TWC_Infantry_Dismounted_Arctic)
};
class TWC_Infantry_ColdWar_Regular_Dismounted_Arctic_Platoon_Sergeant: TWC_Infantry_ColdWar_Regular_Arctic_Platoon_Sergeant
{
	CATEGORY(TWC_Infantry_Dismounted_Arctic)
};
class TWC_Infantry_ColdWar_Regular_Dismounted_Arctic_Platoon_Medic: TWC_Infantry_ColdWar_Regular_Arctic_Platoon_Medic
{
	CATEGORY(TWC_Infantry_Dismounted_Arctic)
};
class TWC_Infantry_ColdWar_Regular_Dismounted_Arctic_CSM: TWC_Infantry_ColdWar_Regular_Arctic_CSM
{
	CATEGORY(TWC_Infantry_Dismounted_Arctic)
};