//REGULAR, DESERT
//Section
class TWC_Infantry_ColdWar_Regular_Desert_Rifleman: TWC_Infantry_ColdWar_Regular_Woodland_Rifleman
{
	CATEGORY(TWC_Infantry_Regular_Desert)
	uniformClass="SP_60Pat_aertexshirtcombats_khaki_item";
	linkedItems[]=
	{
		"sp_webbing_58pattern_fightingorder_alt",
		"sp_Helmet_Mk5_Cover_khaki_Scrim_1",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
	respawnLinkedItems[]=
	{
		"sp_webbing_58pattern_fightingorder_alt",
		"sp_Helmet_Mk5_Cover_khaki_Scrim_1",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
};
class TWC_Infantry_ColdWar_Regular_Desert_Rifleman_SUIT: TWC_Infantry_ColdWar_Regular_Woodland_Rifleman_SUIT
{
	CATEGORY(TWC_Infantry_Regular_Desert)
	uniformClass="SP_60Pat_aertexshirtcombats_khaki_item";
	linkedItems[]=
	{
		"sp_webbing_58pattern_fightingorder_alt",
		"sp_Helmet_Mk5_Cover_khaki_Scrim_1",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
	respawnLinkedItems[]=
	{
		"sp_webbing_58pattern_fightingorder_alt",
		"sp_Helmet_Mk5_Cover_khaki_Scrim_1",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
};
class TWC_Infantry_ColdWar_Regular_Desert_SectionCommander: TWC_Infantry_ColdWar_Regular_Woodland_SectionCommander
{
	CATEGORY(TWC_Infantry_Regular_Desert)
	uniformClass="SP_60Pat_aertexshirtcombats_khaki_item";
	linkedItems[]=
	{
		"sp_webbing_58pattern_fightingorder_alt",
		"sp_Helmet_Mk5_Cover_khaki_Scrim_1",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
	respawnLinkedItems[]=
	{
		"sp_webbing_58pattern_fightingorder_alt",
		"sp_Helmet_Mk5_Cover_khaki_Scrim_1",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
};
class TWC_Infantry_ColdWar_Regular_Desert_2iC: TWC_Infantry_ColdWar_Regular_Woodland_2iC
{
	CATEGORY(TWC_Infantry_Regular_Desert)
	uniformClass="SP_60Pat_aertexshirtcombats_khaki_item";
	linkedItems[]=
	{
		"sp_webbing_58pattern_fightingorder_alt",
		"sp_Helmet_Mk5_Cover_khaki_Scrim_1",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
	respawnLinkedItems[]=
	{
		"sp_webbing_58pattern_fightingorder_alt",
		"sp_Helmet_Mk5_Cover_khaki_Scrim_1",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
};
class TWC_Infantry_ColdWar_Regular_Desert_AT: TWC_Infantry_ColdWar_Regular_Woodland_AT
{
	CATEGORY(TWC_Infantry_Regular_Desert)
	uniformClass="SP_60Pat_aertexshirtcombats_khaki_item";
	linkedItems[]=
	{
		"sp_webbing_58pattern_fightingorder_alt",
		"sp_Helmet_Mk5_Cover_khaki_Scrim_1",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
	respawnLinkedItems[]=
	{
		"sp_webbing_58pattern_fightingorder_alt",
		"sp_Helmet_Mk5_Cover_khaki_Scrim_1",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
};
class TWC_Infantry_ColdWar_Regular_Desert_ASSAT: TWC_Infantry_ColdWar_Regular_Woodland_ASSAT
{
	CATEGORY(TWC_Infantry_Regular_Desert)
	uniformClass="SP_60Pat_aertexshirtcombats_khaki_item";
	linkedItems[]=
	{
		"sp_webbing_58pattern_fightingorder_alt",
		"sp_Helmet_Mk5_Cover_khaki_Scrim_1",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
	respawnLinkedItems[]=
	{
		"sp_webbing_58pattern_fightingorder_alt",
		"sp_Helmet_Mk5_Cover_khaki_Scrim_1",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
};
class TWC_Infantry_ColdWar_Regular_Desert_MG: TWC_Infantry_ColdWar_Regular_Woodland_MG
{
	CATEGORY(TWC_Infantry_Regular_Desert)
	uniformClass="SP_60Pat_aertexshirtcombats_khaki_item";
	linkedItems[]=
	{
		"sp_webbing_58pattern_fightingorder_alt",
		"sp_Helmet_Mk5_Cover_khaki_Scrim_1",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
	respawnLinkedItems[]=
	{
		"sp_webbing_58pattern_fightingorder_alt",
		"sp_Helmet_Mk5_Cover_khaki_Scrim_1",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
};
class TWC_Infantry_ColdWar_Regular_Desert_ASSMG: TWC_Infantry_ColdWar_Regular_Woodland_ASSMG
{
	CATEGORY(TWC_Infantry_Regular_Desert)
	uniformClass="SP_60Pat_aertexshirtcombats_khaki_item";
	linkedItems[]=
	{
		"sp_webbing_58pattern_fightingorder_alt",
		"sp_Helmet_Mk5_Cover_khaki_Scrim_1",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
	respawnLinkedItems[]=
	{
		"sp_webbing_58pattern_fightingorder_alt",
		"sp_Helmet_Mk5_Cover_khaki_Scrim_1",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
};

//Platoon Command
class TWC_Infantry_ColdWar_Regular_Desert_Platoon_Commander: TWC_Infantry_ColdWar_Regular_Woodland_Platoon_Commander
{
	CATEGORY(TWC_Infantry_Regular_Desert)
	uniformClass="SP_60Pat_aertexshirtcombats_khaki_item";
	linkedItems[]=
	{
		"sp_webbing_58pattern_fightingorder_alt",
		"SP_Helmet_MkV_Cover_BrownPainted",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
	respawnLinkedItems[]=
	{
		"sp_webbing_58pattern_fightingorder_alt",
		"SP_Helmet_MkV_Cover_BrownPainted",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
};
class TWC_Infantry_ColdWar_Regular_Desert_Platoon_Sergeant: TWC_Infantry_ColdWar_Regular_Woodland_Platoon_Sergeant
{
	CATEGORY(TWC_Infantry_Regular_Desert)
	uniformClass="SP_60Pat_aertexshirtcombats_khaki_item";
	linkedItems[]=
	{
		"sp_webbing_58pattern_fightingorder_alt",
		"SP_Helmet_MkV_Cover_BrownPainted",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
	respawnLinkedItems[]=
	{
		"sp_webbing_58pattern_fightingorder_alt",
		"SP_Helmet_MkV_Cover_BrownPainted",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
};
class TWC_Infantry_ColdWar_Regular_Desert_Platoon_Medic: TWC_Infantry_ColdWar_Regular_Woodland_Platoon_Medic
{
	CATEGORY(TWC_Infantry_Regular_Desert)
	uniformClass="SP_60Pat_aertexshirtcombats_khaki_item";
	linkedItems[]=
	{
		"sp_webbing_58pattern_fightingorder_alt",
		"SP_Helmet_MkV_Cover_BrownPainted",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
	respawnLinkedItems[]=
	{
		"sp_webbing_58pattern_fightingorder_alt",
		"SP_Helmet_MkV_Cover_BrownPainted",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
};
class TWC_Infantry_ColdWar_Regular_Desert_Platoon_Mortar: TWC_Infantry_ColdWar_Regular_Woodland_Platoon_Mortar
{
	CATEGORY(TWC_Infantry_Regular_Desert)
	uniformClass = "SP_60Pat_aertexshirtcombats_khaki_item";
	linkedItems[] =
	{
		"sp_webbing_58pattern_fightingorder_alt",
		"sp_Helmet_Mk5_Cover_khaki_Scrim_1",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
	respawnLinkedItems[] =
	{
		"sp_webbing_58pattern_fightingorder_alt",
		"sp_Helmet_Mk5_Cover_khaki_Scrim_1",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
};
class TWC_Infantry_ColdWar_Regular_Desert_CSM: TWC_Infantry_ColdWar_Regular_Woodland_CSM
{
	CATEGORY(TWC_Infantry_Regular_Desert)
	uniformClass="SP_60Pat_aertexshirtcombats_khaki_item";
	linkedItems[]=
	{
		"sp_webbing_58pattern_fightingorder_alt",
		"SP_Helmet_MkV_Cover_BrownPainted",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
	respawnLinkedItems[]=
	{
		"sp_webbing_58pattern_fightingorder_alt",
		"SP_Helmet_MkV_Cover_BrownPainted",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
};

//Company
class TWC_Infantry_ColdWar_Regular_Desert_Company_Commander: TWC_Infantry_ColdWar_Regular_Woodland_Company_Commander
{
	CATEGORY(TWC_Infantry_Regular_Desert)
	uniformClass="SP_60Pat_aertexshirtcombats_khaki_item";
	linkedItems[]=
	{
		"sp_webbing_58pattern_fightingorder_alt",
		"SP_Helmet_MkV_Cover_BrownPainted",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
	respawnLinkedItems[]=
	{
		"sp_webbing_58pattern_fightingorder_alt",
		"SP_Helmet_MkV_Cover_BrownPainted",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
};
class TWC_Infantry_ColdWar_Regular_Desert_Company_2iC: TWC_Infantry_ColdWar_Regular_Woodland_Company_2iC
{
	CATEGORY(TWC_Infantry_Regular_Desert)
	uniformClass="SP_60Pat_aertexshirtcombats_khaki_item";
	linkedItems[]=
	{
		"sp_webbing_58pattern_fightingorder_alt",
		"SP_Helmet_MkV_Cover_BrownPainted",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
	respawnLinkedItems[]=
	{
		"sp_webbing_58pattern_fightingorder_alt",
		"SP_Helmet_MkV_Cover_BrownPainted",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
};
class TWC_Infantry_ColdWar_Regular_Desert_Company_Sergeant: TWC_Infantry_ColdWar_Regular_Woodland_Company_Sergeant
{
	CATEGORY(TWC_Infantry_Regular_Desert)
	uniformClass="SP_60Pat_aertexshirtcombats_khaki_item";
	linkedItems[]=
	{
		"sp_webbing_58pattern_fightingorder_alt",
		"SP_Helmet_MkV_Cover_BrownPainted",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
	respawnLinkedItems[]=
	{
		"sp_webbing_58pattern_fightingorder_alt",
		"SP_Helmet_MkV_Cover_BrownPainted",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
};

//AT + AA
class TWC_Infantry_ColdWar_Regular_Desert_MILAN_Gunner: TWC_Infantry_ColdWar_Regular_Woodland_MILAN_Gunner
{
	CATEGORY(TWC_Infantry_Regular_Desert)
	uniformClass="SP_60Pat_aertexshirtcombats_khaki_item";
	linkedItems[]=
	{
		"sp_webbing_58pattern_fightingorder_alt",
		"sp_Helmet_Mk5_Cover_khaki_Scrim_1",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
	respawnLinkedItems[]=
	{
		"sp_webbing_58pattern_fightingorder_alt",
		"sp_Helmet_Mk5_Cover_khaki_Scrim_1",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
};
class TWC_Infantry_ColdWar_Regular_Desert_MILAN_Ass: TWC_Infantry_ColdWar_Regular_Woodland_MILAN_Ass
{
	CATEGORY(TWC_Infantry_Regular_Desert)
	uniformClass="SP_60Pat_aertexshirtcombats_khaki_item";
	linkedItems[]=
	{
		"sp_webbing_58pattern_fightingorder_alt",
		"sp_Helmet_Mk5_Cover_khaki_Scrim_1",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
	respawnLinkedItems[]=
	{
		"sp_webbing_58pattern_fightingorder_alt",
		"sp_Helmet_Mk5_Cover_khaki_Scrim_1",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
};
class TWC_Infantry_ColdWar_Regular_Desert_Blowpipe_Gunner: TWC_Infantry_ColdWar_Regular_Woodland_Blowpipe_Gunner
{
	CATEGORY(TWC_Infantry_Regular_Desert)
	uniformClass="SP_60Pat_aertexshirtcombats_khaki_item";
	linkedItems[]=
	{
		"sp_webbing_58pattern_fightingorder_alt",
		"sp_Helmet_Mk5_Cover_khaki_Scrim_1",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
	respawnLinkedItems[]=
	{
		"sp_webbing_58pattern_fightingorder_alt",
		"sp_Helmet_Mk5_Cover_khaki_Scrim_1",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
};
class TWC_Infantry_ColdWar_Regular_Desert_Blowpipe_Ass: TWC_Infantry_ColdWar_Regular_Woodland_Blowpipe_Ass
{
	CATEGORY(TWC_Infantry_Regular_Desert)
	uniformClass="SP_60Pat_aertexshirtcombats_khaki_item";
	linkedItems[]=
	{
		"sp_webbing_58pattern_fightingorder_alt",
		"sp_Helmet_Mk5_Cover_khaki_Scrim_1",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
	respawnLinkedItems[]=
	{
		"sp_webbing_58pattern_fightingorder_alt",
		"sp_Helmet_Mk5_Cover_khaki_Scrim_1",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
};

//Sniper Team
class TWC_Infantry_ColdWar_Regular_Desert_Sniper: TWC_Infantry_ColdWar_Regular_Woodland_Sniper
{
	CATEGORY(TWC_Infantry_Regular_Desert)
	uniformClass="SP_60Pat_aertexshirtcombats_khaki_item";
	linkedItems[]=
	{
		"sp_webbing_58pattern_fightingorder_alt",
		"sp_Helmet_Mk5_Cover_khaki_Scrim_1",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
	respawnLinkedItems[]=
	{
		"sp_webbing_58pattern_fightingorder_alt",
		"sp_Helmet_Mk5_Cover_khaki_Scrim_1",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
};
class TWC_Infantry_ColdWar_Regular_Desert_Spotter: TWC_Infantry_ColdWar_Regular_Woodland_Spotter
{
	CATEGORY(TWC_Infantry_Regular_Desert)
	uniformClass="SP_60Pat_aertexshirtcombats_khaki_item";
	linkedItems[]=
	{
		"sp_webbing_58pattern_fightingorder_alt",
		"sp_Helmet_Mk5_Cover_khaki_Scrim_1",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
	respawnLinkedItems[]=
	{
		"sp_webbing_58pattern_fightingorder_alt",
		"sp_Helmet_Mk5_Cover_khaki_Scrim_1",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
};

//Artillery Crew
class TWC_Infantry_ColdWar_Regular_Desert_Artillery_Commander: TWC_Infantry_ColdWar_Regular_Woodland_Artillery_Commander
{
	CATEGORY(TWC_Infantry_Regular_Desert)
	uniformClass="SP_60Pat_aertexshirtcombats_khaki_item";
	linkedItems[]=
	{
		"sp_webbing_58pattern_fightingorder_alt",
		"sp_Helmet_Mk5_Cover_khaki_Scrim_1",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
	respawnLinkedItems[]=
	{
		"sp_webbing_58pattern_fightingorder_alt",
		"sp_Helmet_Mk5_Cover_khaki_Scrim_1",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
};
class TWC_Infantry_ColdWar_Regular_Desert_Artillery_Crew: TWC_Infantry_ColdWar_Regular_Woodland_Artillery_Crew
{
	CATEGORY(TWC_Infantry_Regular_Desert)
	uniformClass="SP_60Pat_aertexshirtcombats_khaki_item";
	linkedItems[]=
	{
		"sp_webbing_58pattern_fightingorder_alt",
		"sp_Helmet_Mk5_Cover_khaki_Scrim_1",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
	respawnLinkedItems[]=
	{
		"sp_webbing_58pattern_fightingorder_alt",
		"sp_Helmet_Mk5_Cover_khaki_Scrim_1",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
};
class TWC_Infantry_ColdWar_Regular_Desert_FO: TWC_Infantry_ColdWar_Regular_Woodland_FO
{
	CATEGORY(TWC_Infantry_Regular_Desert)
	uniformClass="SP_60Pat_aertexshirtcombats_khaki_item";
	linkedItems[]=
	{
		"sp_webbing_58pattern_fightingorder_alt",
		"sp_Helmet_Mk5_Cover_khaki_Scrim_1",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
	respawnLinkedItems[]=
	{
		"sp_webbing_58pattern_fightingorder_alt",
		"sp_Helmet_Mk5_Cover_khaki_Scrim_1",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
};

//Aircraft
class TWC_Infantry_ColdWar_Regular_Desert_FAC: TWC_Infantry_ColdWar_Regular_Woodland_FAC
{
	CATEGORY(TWC_Infantry_Regular_Desert)
	uniformClass="SP_60Pat_aertexshirtcombats_khaki_item";
	linkedItems[]=
	{
		"sp_webbing_58pattern_fightingorder_alt",
		"sp_Helmet_Mk5_Cover_khaki_Scrim_1",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
	respawnLinkedItems[]=
	{
		"sp_webbing_58pattern_fightingorder_alt",
		"sp_Helmet_Mk5_Cover_khaki_Scrim_1",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
};
class TWC_Infantry_ColdWar_Regular_Desert_Helicopter_Pilot: TWC_Infantry_ColdWar_Regular_Woodland_Helicopter_Pilot
{
	CATEGORY(TWC_Infantry_Regular_Desert)
	uniformClass="SP_60Pat_aertexshirtcombats_khaki_item";
	linkedItems[]=
	{
		"sp_webbing_58pattern_beltorder",
		"CUP_H_BAF_Helmet_Pilot",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
	respawnLinkedItems[]=
	{
		"sp_webbing_58pattern_beltorder",
		"CUP_H_BAF_Helmet_Pilot",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
};

//FVs
class TWC_Infantry_ColdWar_Regular_Desert_Vehicle_Commander: TWC_Infantry_ColdWar_Regular_Woodland_Vehicle_Commander
{
	CATEGORY(TWC_Infantry_Regular_Desert)
	uniformClass="SP_60Pat_aertexshirtcombats_khaki_item";
	linkedItems[]=
	{
		"sp_webbing_58pattern_beltorder",
		"UK3CB_BAF_H_Beret_PWRR_PRR",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
	respawnLinkedItems[]=
	{
		"sp_webbing_58pattern_beltorder",
		"UK3CB_BAF_H_Beret_PWRR_PRR",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
};
class TWC_Infantry_ColdWar_Regular_Desert_Vehicle_Crew: TWC_Infantry_ColdWar_Regular_Woodland_Vehicle_Crew
{
	CATEGORY(TWC_Infantry_Regular_Desert)
	uniformClass="SP_60Pat_aertexshirtcombats_khaki_item";
	linkedItems[]=
	{
		"sp_webbing_58pattern_beltorder",
		"UK3CB_BAF_H_Beret_PWRR_PRR",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
	respawnLinkedItems[]=
	{
		"sp_webbing_58pattern_beltorder",
		"UK3CB_BAF_H_Beret_PWRR_PRR",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
};