//REGULAR, DISMOUNTED, NBC
//Section
class TWC_Infantry_ColdWar_Regular_Dismounted_NBC_Rifleman: TWC_Infantry_ColdWar_Regular_NBC_Rifleman
{
	CATEGORY(TWC_Infantry_Dismounted_NBC)
	backpack = "TWC_Backpack_ColdWar_Regular_Dismounted_Rifleman";
};
class TWC_Infantry_ColdWar_Regular_Dismounted_NBC_Rifleman_SUIT: TWC_Infantry_ColdWar_Regular_NBC_Rifleman_SUIT
{
	CATEGORY(TWC_Infantry_Dismounted_NBC)
	backpack = "TWC_Backpack_ColdWar_Regular_Dismounted_Rifleman";
};
class TWC_Infantry_ColdWar_Regular_Dismounted_NBC_SectionCommander: TWC_Infantry_ColdWar_Regular_NBC_SectionCommander
{
	CATEGORY(TWC_Infantry_Dismounted_NBC)
};
class TWC_Infantry_ColdWar_Regular_Dismounted_NBC_2iC: TWC_Infantry_ColdWar_Regular_NBC_2iC
{
	CATEGORY(TWC_Infantry_Dismounted_NBC)
};
class TWC_Infantry_ColdWar_Regular_Dismounted_NBC_AT: TWC_Infantry_ColdWar_Regular_NBC_AT
{
	CATEGORY(TWC_Infantry_Dismounted_NBC)
	backpack = "TWC_Backpack_ColdWar_Regular_Dismounted_AT";
};
class TWC_Infantry_ColdWar_Regular_Dismounted_NBC_ASSAT: TWC_Infantry_ColdWar_Regular_NBC_ASSAT
{
	CATEGORY(TWC_Infantry_Dismounted_NBC)
	backpack = "TWC_Backpack_ColdWar_Regular_Dismounted_ATASS";
};
class TWC_Infantry_ColdWar_Regular_Dismounted_NBC_MG: TWC_Infantry_ColdWar_Regular_NBC_MG
{
	CATEGORY(TWC_Infantry_Dismounted_NBC)
	backpack = "TWC_Backpack_ColdWar_Regular_Dismounted_MG";
};
class TWC_Infantry_ColdWar_Regular_Dismounted_NBC_ASSMG: TWC_Infantry_ColdWar_Regular_NBC_ASSMG
{
	CATEGORY(TWC_Infantry_Dismounted_NBC)
	backpack = "TWC_Backpack_ColdWar_Regular_Dismounted_ASSMG";
};

//Platoon Command
class TWC_Infantry_ColdWar_Regular_Dismounted_NBC_Platoon_Commander: TWC_Infantry_ColdWar_Regular_NBC_Platoon_Commander
{
	CATEGORY(TWC_Infantry_Dismounted_NBC)
};
class TWC_Infantry_ColdWar_Regular_Dismounted_NBC_Platoon_Sergeant: TWC_Infantry_ColdWar_Regular_NBC_Platoon_Sergeant
{
	CATEGORY(TWC_Infantry_Dismounted_NBC)
};
class TWC_Infantry_ColdWar_Regular_Dismounted_NBC_Platoon_Medic: TWC_Infantry_ColdWar_Regular_NBC_Platoon_Medic
{
	CATEGORY(TWC_Infantry_Dismounted_NBC)
};
class TWC_Infantry_ColdWar_Regular_Dismounted_NBC_CSM: TWC_Infantry_ColdWar_Regular_NBC_CSM
{
	CATEGORY(TWC_Infantry_Dismounted_NBC)
};

//Company
class TWC_Infantry_ColdWar_Regular_Dismounted_NBC_Company_Commander: TWC_Infantry_ColdWar_Regular_NBC_Company_Commander
{
	CATEGORY(TWC_Infantry_Dismounted_NBC)
};
class TWC_Infantry_ColdWar_Regular_Dismounted_NBC_Company_2iC: TWC_Infantry_ColdWar_Regular_NBC_Company_2iC
{
	CATEGORY(TWC_Infantry_Dismounted_NBC)
};
class TWC_Infantry_ColdWar_Regular_Dismounted_NBC_Company_Sergeant: TWC_Infantry_ColdWar_Regular_NBC_Company_Sergeant
{
	CATEGORY(TWC_Infantry_Dismounted_NBC)
};