//REGULAR, TROPIC
//Section
class TWC_Infantry_ColdWar_Regular_Tropic_Rifleman: TWC_Infantry_ColdWar_Regular_Woodland_Rifleman
{
	CATEGORY(TWC_Infantry_Regular_Tropic)
	uniformClass="SP_60PatCombatsRolled_OD_1_Item";
	linkedItems[]=
	{
		"SP_P58_FightingOrderNBC",
		"SP_Helmet_MkV_OD_FoliageLush",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
	respawnLinkedItems[]=
	{
		"SP_P58_FightingOrderNBC",
		"SP_Helmet_MkV_OD_FoliageLush",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
};
class TWC_Infantry_ColdWar_Regular_Tropic_Rifleman_SUIT: TWC_Infantry_ColdWar_Regular_Woodland_Rifleman_SUIT
{
	CATEGORY(TWC_Infantry_Regular_Tropic)
	uniformClass="SP_60PatCombatsRolled_OD_1_Item";
	linkedItems[]=
	{
		"SP_P58_FightingOrderNBC",
		"SP_Helmet_MkV_OD_FoliageLush",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
	respawnLinkedItems[]=
	{
		"SP_P58_FightingOrderNBC",
		"SP_Helmet_MkV_OD_FoliageLush",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
};
class TWC_Infantry_ColdWar_Regular_Tropic_SectionCommander: TWC_Infantry_ColdWar_Regular_Woodland_SectionCommander
{
	CATEGORY(TWC_Infantry_Regular_Tropic)
	uniformClass="SP_60PatCombatsRolled_OD_1_Item";
	linkedItems[]=
	{
		"SP_P58_FightingOrderNBC",
		"SP_Helmet_MkV_OD_FoliageLush",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
	respawnLinkedItems[]=
	{
		"SP_P58_FightingOrderNBC",
		"SP_Helmet_MkV_OD_FoliageLush",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
};
class TWC_Infantry_ColdWar_Regular_Tropic_2iC: TWC_Infantry_ColdWar_Regular_Woodland_2iC
{
	CATEGORY(TWC_Infantry_Regular_Tropic)
	uniformClass="SP_60PatCombatsRolled_OD_1_Item";
	linkedItems[]=
	{
		"SP_P58_FightingOrderNBC",
		"SP_Helmet_MkV_OD_FoliageLush",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
	respawnLinkedItems[]=
	{
		"SP_P58_FightingOrderNBC",
		"SP_Helmet_MkV_OD_FoliageLush",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
};
class TWC_Infantry_ColdWar_Regular_Tropic_AT: TWC_Infantry_ColdWar_Regular_Woodland_AT
{
	CATEGORY(TWC_Infantry_Regular_Tropic)
	uniformClass="SP_60PatCombatsRolled_OD_1_Item";
	linkedItems[]=
	{
		"SP_P58_FightingOrderNBC",
		"SP_Helmet_MkV_OD_FoliageLush",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
	respawnLinkedItems[]=
	{
		"SP_P58_FightingOrderNBC",
		"SP_Helmet_MkV_OD_FoliageLush",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
};
class TWC_Infantry_ColdWar_Regular_Tropic_ASSAT: TWC_Infantry_ColdWar_Regular_Woodland_ASSAT
{
	CATEGORY(TWC_Infantry_Regular_Tropic)
	uniformClass="SP_60PatCombatsRolled_OD_1_Item";
	linkedItems[]=
	{
		"SP_P58_FightingOrderNBC",
		"SP_Helmet_MkV_OD_FoliageLush",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
	respawnLinkedItems[]=
	{
		"SP_P58_FightingOrderNBC",
		"SP_Helmet_MkV_OD_FoliageLush",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
};
class TWC_Infantry_ColdWar_Regular_Tropic_MG: TWC_Infantry_ColdWar_Regular_Woodland_MG
{
	CATEGORY(TWC_Infantry_Regular_Tropic)
	uniformClass="SP_60PatCombatsRolled_OD_1_Item";
	linkedItems[]=
	{
		"SP_P58_FightingOrderNBC",
		"SP_Helmet_MkV_OD_FoliageLush",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
	respawnLinkedItems[]=
	{
		"SP_P58_FightingOrderNBC",
		"SP_Helmet_MkV_OD_FoliageLush",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
};
class TWC_Infantry_ColdWar_Regular_Tropic_ASSMG: TWC_Infantry_ColdWar_Regular_Woodland_ASSMG
{
	CATEGORY(TWC_Infantry_Regular_Tropic)
	uniformClass="SP_60PatCombatsRolled_OD_1_Item";
	linkedItems[]=
	{
		"SP_P58_FightingOrderNBC",
		"SP_Helmet_MkV_OD_FoliageLush",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
	respawnLinkedItems[]=
	{
		"SP_P58_FightingOrderNBC",
		"SP_Helmet_MkV_OD_FoliageLush",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
};

//Platoon Command
class TWC_Infantry_ColdWar_Regular_Tropic_Platoon_Commander: TWC_Infantry_ColdWar_Regular_Woodland_Platoon_Commander
{
	CATEGORY(TWC_Infantry_Regular_Tropic)
	uniformClass="SP_60PatCombatsRolled_OD_1_Item";
	linkedItems[]=
	{
		"SP_P58_FightingOrderNBC",
		"SP_Helmet_MkV_OD_FoliageLush",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
	respawnLinkedItems[]=
	{
		"SP_P58_FightingOrderNBC",
		"SP_Helmet_MkV_OD_FoliageLush",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
};
class TWC_Infantry_ColdWar_Regular_Tropic_Platoon_Sergeant: TWC_Infantry_ColdWar_Regular_Woodland_Platoon_Sergeant
{
	CATEGORY(TWC_Infantry_Regular_Tropic)
	uniformClass="SP_60PatCombatsRolled_OD_1_Item";
	linkedItems[]=
	{
		"SP_P58_FightingOrderNBC",
		"SP_Helmet_MkV_OD_FoliageLush",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
	respawnLinkedItems[]=
	{
		"SP_P58_FightingOrderNBC",
		"SP_Helmet_MkV_OD_FoliageLush",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
};
class TWC_Infantry_ColdWar_Regular_Tropic_Platoon_Medic: TWC_Infantry_ColdWar_Regular_Woodland_Platoon_Medic
{
	CATEGORY(TWC_Infantry_Regular_Tropic)
	uniformClass="SP_60PatCombatsRolled_OD_1_Item";
	linkedItems[]=
	{
		"SP_P58_FightingOrderNBC",
		"SP_Helmet_MkV_ODMedic_FoliageLush",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
	respawnLinkedItems[]=
	{
		"SP_P58_FightingOrderNBC",
		"SP_Helmet_MkV_ODMedic_FoliageLush",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
};
class TWC_Infantry_ColdWar_Regular_Tropic_CSM: TWC_Infantry_ColdWar_Regular_Woodland_CSM
{
	CATEGORY(TWC_Infantry_Regular_Tropic)
	uniformClass="SP_60PatCombatsRolled_OD_1_Item";
	linkedItems[]=
	{
		"SP_P58_FightingOrderNBC",
		"SP_Helmet_MkV_OD_FoliageLush",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
	respawnLinkedItems[]=
	{
		"SP_P58_FightingOrderNBC",
		"SP_Helmet_MkV_OD_FoliageLush",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
};

//AT + AA
class TWC_Infantry_ColdWar_Regular_Tropic_MILAN_Gunner: TWC_Infantry_ColdWar_Regular_Woodland_MILAN_Gunner
{
	CATEGORY(TWC_Infantry_Regular_Tropic)
	uniformClass="SP_60PatCombatsRolled_OD_1_Item";
	linkedItems[]=
	{
		"SP_P58_FightingOrderNBC",
		"SP_Helmet_MkV_OD_FoliageLush",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
	respawnLinkedItems[]=
	{
		"SP_P58_FightingOrderNBC",
		"SP_Helmet_MkV_OD_FoliageLush",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
};
class TWC_Infantry_ColdWar_Regular_Tropic_MILAN_Ass: TWC_Infantry_ColdWar_Regular_Woodland_MILAN_Ass
{
	CATEGORY(TWC_Infantry_Regular_Tropic)
	uniformClass="SP_60PatCombatsRolled_OD_1_Item";
	linkedItems[]=
	{
		"SP_P58_FightingOrderNBC",
		"SP_Helmet_MkV_OD_FoliageLush",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
	respawnLinkedItems[]=
	{
		"SP_P58_FightingOrderNBC",
		"SP_Helmet_MkV_OD_FoliageLush",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
};
class TWC_Infantry_ColdWar_Regular_Tropic_Blowpipe_Gunner: TWC_Infantry_ColdWar_Regular_Woodland_Blowpipe_Gunner
{
	CATEGORY(TWC_Infantry_Regular_Tropic)
	uniformClass="SP_60PatCombatsRolled_OD_1_Item";
	linkedItems[]=
	{
		"SP_P58_FightingOrderNBC",
		"SP_Helmet_MkV_OD_FoliageLush",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
	respawnLinkedItems[]=
	{
		"SP_P58_FightingOrderNBC",
		"SP_Helmet_MkV_OD_FoliageLush",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
};
class TWC_Infantry_ColdWar_Regular_Tropic_Blowpipe_Ass: TWC_Infantry_ColdWar_Regular_Woodland_Blowpipe_Ass
{
	CATEGORY(TWC_Infantry_Regular_Tropic)
	uniformClass="SP_60PatCombatsRolled_OD_1_Item";
	linkedItems[]=
	{
		"SP_P58_FightingOrderNBC",
		"SP_Helmet_MkV_OD_FoliageLush",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
	respawnLinkedItems[]=
	{
		"SP_P58_FightingOrderNBC",
		"SP_Helmet_MkV_OD_FoliageLush",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
};

//Sniper Team
class TWC_Infantry_ColdWar_Regular_Tropic_Sniper: TWC_Infantry_ColdWar_Regular_Woodland_Sniper
{
	CATEGORY(TWC_Infantry_Regular_Tropic)
	uniformClass="SP_60PatCombatsRolled_OD_1_Item";
	linkedItems[]=
	{
		"SP_P58_FightingOrderNBC",
		"SP_Helmet_MkV_OD_FoliageLush",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
	respawnLinkedItems[]=
	{
		"SP_P58_FightingOrderNBC",
		"SP_Helmet_MkV_OD_FoliageLush",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
};
class TWC_Infantry_ColdWar_Regular_Tropic_Spotter: TWC_Infantry_ColdWar_Regular_Woodland_Spotter
{
	CATEGORY(TWC_Infantry_Regular_Tropic)
	uniformClass="SP_60PatCombatsRolled_OD_1_Item";
	linkedItems[]=
	{
		"SP_P58_FightingOrderNBC",
		"SP_Helmet_MkV_OD_FoliageLush",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
	respawnLinkedItems[]=
	{
		"SP_P58_FightingOrderNBC",
		"SP_Helmet_MkV_OD_FoliageLush",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
};

//Artillery Crew
class TWC_Infantry_ColdWar_Regular_Tropic_Artillery_Commander: TWC_Infantry_ColdWar_Regular_Woodland_Artillery_Commander
{
	CATEGORY(TWC_Infantry_Regular_Tropic)
	uniformClass="SP_60PatCombatsRolled_OD_1_Item";
	linkedItems[]=
	{
		"SP_P58_FightingOrderNBC",
		"SP_Helmet_MkV_OD_FoliageLush",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
	respawnLinkedItems[]=
	{
		"SP_P58_FightingOrderNBC",
		"SP_Helmet_MkV_OD_FoliageLush",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
};
class TWC_Infantry_ColdWar_Regular_Tropic_Artillery_Crew: TWC_Infantry_ColdWar_Regular_Woodland_Artillery_Crew
{
	CATEGORY(TWC_Infantry_Regular_Tropic)
	uniformClass="SP_60PatCombatsRolled_OD_1_Item";
	linkedItems[]=
	{
		"SP_P58_FightingOrderNBC",
		"SP_Helmet_MkV_OD_FoliageLush",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
	respawnLinkedItems[]=
	{
		"SP_P58_FightingOrderNBC",
		"SP_Helmet_MkV_OD_FoliageLush",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
};
class TWC_Infantry_ColdWar_Regular_Tropic_FO: TWC_Infantry_ColdWar_Regular_Woodland_FO
{
	CATEGORY(TWC_Infantry_Regular_Tropic)
	uniformClass="SP_60PatCombatsRolled_OD_1_Item";
	linkedItems[]=
	{
		"SP_P58_FightingOrderNBC",
		"SP_Helmet_MkV_OD_FoliageLush",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
	respawnLinkedItems[]=
	{
		"SP_P58_FightingOrderNBC",
		"SP_Helmet_MkV_OD_FoliageLush",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
};

//Aircraft
class TWC_Infantry_ColdWar_Regular_Tropic_FAC: TWC_Infantry_ColdWar_Regular_Woodland_FAC
{
	CATEGORY(TWC_Infantry_Regular_Tropic)
	uniformClass="SP_60PatCombatsRolled_OD_1_Item";
	linkedItems[]=
	{
		"SP_P58_FightingOrderNBC",
		"SP_Helmet_MkV_OD_FoliageLush",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
	respawnLinkedItems[]=
	{
		"SP_P58_FightingOrderNBC",
		"SP_Helmet_MkV_OD_FoliageLush",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
};
class TWC_Infantry_ColdWar_Regular_Tropic_Helicopter_Pilot: TWC_Infantry_ColdWar_Regular_Woodland_Helicopter_Pilot
{
	CATEGORY(TWC_Infantry_Regular_Tropic)
	uniformClass="SP_60PatCombatsRolled_OD_1_Item";
	linkedItems[]=
	{
		"SP_P58_UrbanPatrolNBC",
		"CUP_H_BAF_Helmet_Pilot",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
	respawnLinkedItems[]=
	{
		"SP_P58_UrbanPatrolNBC",
		"CUP_H_BAF_Helmet_Pilot",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
};

//FVs
class TWC_Infantry_ColdWar_Regular_Tropic_Vehicle_Commander: TWC_Infantry_ColdWar_Regular_Woodland_Vehicle_Commander
{
	CATEGORY(TWC_Infantry_Regular_Tropic)
	uniformClass="SP_60PatCombatsRolled_OD_1_Item";
	linkedItems[]=
	{
		"SP_P58_UrbanPatrolNBC",
		"UK3CB_BAF_H_Beret_PWRR_PRR",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
	respawnLinkedItems[]=
	{
		"SP_P58_UrbanPatrolNBC",
		"UK3CB_BAF_H_Beret_PWRR_PRR",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
};
class TWC_Infantry_ColdWar_Regular_Tropic_Vehicle_Crew: TWC_Infantry_ColdWar_Regular_Woodland_Vehicle_Crew
{
	CATEGORY(TWC_Infantry_Regular_Tropic)
	uniformClass="SP_60PatCombatsRolled_OD_1_Item";
	linkedItems[]=
	{
		"SP_P58_UrbanPatrolNBC",
		"UK3CB_BAF_H_Beret_PWRR_PRR",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
	respawnLinkedItems[]=
	{
		"SP_P58_UrbanPatrolNBC",
		"UK3CB_BAF_H_Beret_PWRR_PRR",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
};