class CfgPatches
{
	class twc_faction
	{
		units[]=
		{
			"Cold_War_Argentinian_Squadleader",
			"Cold_War_Argentinian_Rifleman",
			"Cold_War_Argentinian_AT_Rifleman",
			"Cold_War_Argentinian_AT_Assistant",
			"Cold_War_Argentinian_AA",
			"Cold_War_Argentinian_AA_Assistant",
			"Cold_War_Argentinian_Machinegunner",
			"Cold_War_Argentinian_MG_Assistant",
			"ColdWar_Rifleman",
			"ColdWar_AT",
			"ColdWar_AT_ASS",
			"ColdWar_2IC",
			"ColdWar_MG",
			"ColdWar_MG_AS",
			"ColdWar_Section_Leader",
			"ColdWar_Platoon_Commander",
			"ColdWar_sergeant",
			"ColdWar_Medic",
			"ColdWar_FAC",
			"ColdWar_JetPilot",
			"ColdWar_AA_Gunner",
			"ColdWar_AA_Assistant"
		};
		weapons[]={};
		requiredVersion=0.1;
		requiredAddons[]=
		{
			"A3_Characters_F_BLUFOR",
			"A3_Characters_F_OPFOR"
		};
	};
};
class CfgVehicles
{
	class B_Soldier_base_F;
	class O_Soldier_base_F;
	class I_Soldier_F;
/***************************************************
*                      Cold War                    *
***************************************************/
	class ColdWar_Rifleman: B_Soldier_base_F
	{
		_generalMacro="Coldwar_Rifleman";
		scope=2;
		displayName="Rifleman(Coldwar)";
		faction="a_units";
		vehicleClass="Cold_British";
		icon="iconMan";
		nakedUniform="U_BasicBody";
		uniformClass="MNP_CombatUniform_DPMR";
		backpack="TWC_Backpack_Cold_War_Rifleman";
		linkedItems[]=
		{
        "V_sud_nato_vest05",
		"SP_MkBushHelmet_Forrest",
		"ItemCompass",
		"ItemWatch"
		};
		respawnLinkedItems[]=
		{
        "V_sud_nato_vest05",
		"SP_MkBushHelmet_Forrest",
		"ItemCompass",
		"ItemWatch"
		};
		weapons[]=
		{
		"Throw",
		"Put",	
		"hlc_rifle_L1A1SLR",
		"rhsusf_weap_m1911a1",
		"HAFM_LAW"		
		};
		respawnweapons[]=
		{
		"Throw",
		"Put",	
		"hlc_rifle_L1A1SLR",
		"rhsusf_weap_m1911a1",
		"HAFM_LAW"	
		};
		magazines[]=
		{
		"rhsusf_mag_7x45acp_MHP",
		"rhsusf_mag_7x45acp_MHP",
		"rhsusf_mag_7x45acp_MHP",
		"hlc_20Rnd_762x51_B_fal",
		"hlc_20Rnd_762x51_B_fal",
		"hlc_20Rnd_762x51_B_fal",
		"SmokeShell",
		"SmokeShell",
		"SmokeShell",
		"SmokeShell",
		"SmokeShell",
		"CUP_HandGrenade_L109A2_HE",
		"CUP_HandGrenade_L109A2_HE"
		};
		Respawnmagazines[]=
		{
		"rhsusf_mag_7x45acp_MHP",
		"rhsusf_mag_7x45acp_MHP",
		"rhsusf_mag_7x45acp_MHP",	
		"hlc_20Rnd_762x51_B_fal",
		"hlc_20Rnd_762x51_B_fal",
		"hlc_20Rnd_762x51_B_fal",
		"SmokeShell",
		"SmokeShell",
		"SmokeShell",
		"SmokeShell",
		"SmokeShell",
		"CUP_HandGrenade_L109A2_HE",
		"CUP_HandGrenade_L109A2_HE"
		};
		Items[]=
		{
		"ACE_EarPlugs",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_morphine",
		"ACE_morphine"
		};
		respawntems[]=
		{
		"ACE_EarPlugs",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_morphine",
		"ACE_morphine"			
		};		
	};
	class ColdWar_AT: B_Soldier_base_F
	{
		_generalMacro="Coldwar_At";
		scope=2;
		displayName="AT Rifleman(Coldwar)";
		faction="a_units";
		vehicleClass="Cold_British";
		icon="iconMan";
		nakedUniform="U_BasicBody";
		uniformClass="MNP_CombatUniform_DPMR";
		backpack="TWC_Backpack_Cold_War_AT";
		linkedItems[]=
		{
        "V_sud_nato_vest05",
		"SP_MkBushHelmet_Forrest",
		"tf47_optic_m3maaws",
		"ItemCompass",
		"ItemWatch"
		};
		respawnLinkedItems[]=
		{
        "V_sud_nato_vest05",
		"SP_MkBushHelmet_Forrest",
		"ItemCompass",
		"ItemWatch"
		};
		weapons[]=
		{
		"Throw",
		"Put",
		"hlc_rifle_L1A1SLR",
		"tf47_m3maaws",
		"rhsusf_weap_m1911a1"
		};
		respawnweapons[]=
		{
		"Throw",
		"Put",
		"hlc_rifle_L1A1SLR",
		"TWC_Carl_Gustav",
		"rhsusf_weap_m1911a1"
		};
		magazines[]=
		{
		"hlc_20Rnd_762x51_B_fal",
		"hlc_20Rnd_762x51_B_fal",
		"hlc_20Rnd_762x51_B_fal",
		"hlc_20Rnd_762x51_B_fal",
		"hlc_20Rnd_762x51_B_fal",
		"hlc_20Rnd_762x51_B_fal",		
		"rhsusf_mag_7x45acp_MHP",
		"rhsusf_mag_7x45acp_MHP",
		"rhsusf_mag_7x45acp_MHP",
		"tf47_m3maaws_HEAT",
		"SmokeShell",
		"SmokeShell",
		"SmokeShell",
		"SmokeShell",
		"SmokeShell",
		"CUP_HandGrenade_L109A2_HE",
		"CUP_HandGrenade_L109A2_HE"
		};
		Respawnmagazines[]=
		{
		"hlc_20Rnd_762x51_B_fal",
		"hlc_20Rnd_762x51_B_fal",
		"hlc_20Rnd_762x51_B_fal",
		"hlc_20Rnd_762x51_B_fal",
		"hlc_20Rnd_762x51_B_fal",
		"hlc_20Rnd_762x51_B_fal",		
		"rhsusf_mag_7x45acp_MHP",
		"rhsusf_mag_7x45acp_MHP",
		"rhsusf_mag_7x45acp_MHP",
		"tf47_m3maaws_HEAT",
		"SmokeShell",
		"SmokeShell",
		"SmokeShell",
		"SmokeShell",
		"SmokeShell",
		"CUP_HandGrenade_L109A2_HE",
		"CUP_HandGrenade_L109A2_HE"
		};
		Items[]=
		{
		"ACE_EarPlugs",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_morphine",
		"ACE_morphine",
		"tf47_optic_m3maaws"
		};
		respawntems[]=
		{
		"ACE_EarPlugs",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_morphine",
		"ACE_morphine",
		"tf47_optic_m3maaws"		
		};		
	};
	class ColdWar_AT_ASS: B_Soldier_base_F
	{
		_generalMacro="Coldwar_AT_ASS";
		scope=2;
		displayName="AT Assistant Rifleman(Coldwar)";
		faction="a_units";
		vehicleClass="Cold_British";
		icon="iconMan";
		nakedUniform="U_BasicBody";
		uniformClass="MNP_CombatUniform_DPMR";
		backpack="TWC_Backpack_Cold_War_AT";
		linkedItems[]=
		{
        "V_sud_nato_vest05",
		"SP_MkBushHelmet_Forrest",
		"ItemCompass",
		"ItemWatch"
		};
		respawnLinkedItems[]=
		{
        "V_sud_nato_vest05",
		"SP_MkBushHelmet_Forrest",
		"ItemCompass",
		"ItemWatch"
		};
		weapons[]=
		{
	    "Throw",
		"Put",
		"hlc_rifle_L1A1SLR",
		"rhsusf_weap_m1911a1"
		};
		respawnweapons[]=
		{
		"Throw",
		"Put",	
		"hlc_rifle_L1A1SLR",
		"rhsusf_weap_m1911a1"
		};
		magazines[]=
		{
		"hlc_20Rnd_762x51_B_fal",
		"hlc_20Rnd_762x51_B_fal",
		"hlc_20Rnd_762x51_B_fal",
		"hlc_20Rnd_762x51_B_fal",
		"hlc_20Rnd_762x51_B_fal",
		"hlc_20Rnd_762x51_B_fal",		
		"rhsusf_mag_7x45acp_MHP",
		"rhsusf_mag_7x45acp_MHP",
		"rhsusf_mag_7x45acp_MHP",		
		"SmokeShell",
		"SmokeShell",
		"SmokeShell",
		"SmokeShell",
		"SmokeShell",
		"CUP_HandGrenade_L109A2_HE",
		"CUP_HandGrenade_L109A2_HE"
		};
		Respawnmagazines[]=
		{
		"hlc_20Rnd_762x51_B_fal",
		"hlc_20Rnd_762x51_B_fal",
		"hlc_20Rnd_762x51_B_fal",
		"hlc_20Rnd_762x51_B_fal",
		"hlc_20Rnd_762x51_B_fal",
		"hlc_20Rnd_762x51_B_fal",		
		"rhsusf_mag_7x45acp_MHP",
		"rhsusf_mag_7x45acp_MHP",
		"rhsusf_mag_7x45acp_MHP",		
		"SmokeShell",
		"SmokeShell",
		"SmokeShell",
		"SmokeShell",
		"SmokeShell",
		"CUP_HandGrenade_L109A2_HE",
		"CUP_HandGrenade_L109A2_HE"
		};
		Items[]=
		{
		"ACE_EarPlugs",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_morphine",
		"ACE_morphine"
		};
		respawntems[]=
		{
		"ACE_EarPlugs",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_morphine",
		"ACE_morphine"			
		};		
	};
	class ColdWar_2IC: B_Soldier_base_F
	{
		_generalMacro="Coldwar_2IC";
		scope=2;
		displayName="2IC(Coldwar)";
		faction="a_units";
		vehicleClass="Cold_British";
		icon="iconMan";
		nakedUniform="U_BasicBody";
		uniformClass="MNP_CombatUniform_DPMR";
		backpack="TWC_Backpack_Cold_War_2IC";
		linkedItems[]=
		{
		"Binocular",	
        "V_sud_nato_vest04",
		"SP_MkBushHelmet_Forrest",
		"ItemMap",
		"ItemCompass",
		"ItemWatch"
		};
		respawnLinkedItems[]=
		{
		"Binocular",		
        "V_sud_nato_vest04",
		"SP_MkBushHelmet_Forrest",
		"ItemMap",
		"ItemCompass",
		"ItemWatch"
		};
		weapons[]=
		{
		"Throw",
		"Put",
		"Binocular",
		"hlc_rifle_L1A1SLR",
		"rhsusf_weap_m1911a1"
		};
		respawnweapons[]=
		{
		"Throw",
		"Put",
		"Binocular",
		"hlc_rifle_L1A1SLR",
		"rhsusf_weap_m1911a1"
		};
		magazines[]=
		{
		"hlc_20Rnd_762x51_B_fal",
		"hlc_20Rnd_762x51_B_fal",
		"hlc_20Rnd_762x51_B_fal",
		"hlc_20Rnd_762x51_B_fal",
		"hlc_20Rnd_762x51_B_fal",
		"hlc_20Rnd_762x51_B_fal",		
		"rhsusf_mag_7x45acp_MHP",
		"rhsusf_mag_7x45acp_MHP",
		"rhsusf_mag_7x45acp_MHP",		
		"SmokeShell",
		"SmokeShell",
		"SmokeShell",
		"SmokeShell",
		"SmokeShell",
		"CUP_HandGrenade_L109A2_HE",
		"CUP_HandGrenade_L109A2_HE"
		};
		Respawnmagazines[]=
		{
		"hlc_20Rnd_762x51_B_fal",
		"hlc_20Rnd_762x51_B_fal",
		"hlc_20Rnd_762x51_B_fal",
		"hlc_20Rnd_762x51_B_fal",
		"hlc_20Rnd_762x51_B_fal",
		"hlc_20Rnd_762x51_B_fal",		
		"rhsusf_mag_7x45acp_MHP",
		"rhsusf_mag_7x45acp_MHP",
		"rhsusf_mag_7x45acp_MHP",		
		"SmokeShell",
		"SmokeShell",
		"SmokeShell",
		"SmokeShell",
		"SmokeShell",
		"CUP_HandGrenade_L109A2_HE",
		"CUP_HandGrenade_L109A2_HE"
		};
		Items[]=
		{
		"ACE_EarPlugs",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_morphine",
		"ACE_morphine"
		};
		respawntems[]=
		{
		"ACE_EarPlugs",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_morphine",
		"ACE_morphine"			
		};		
	};
	class ColdWar_MG: B_Soldier_base_F
	{
		_generalMacro="Coldwar_MG";
		scope=2;
		displayName="Machine Gunner(Coldwar)";
		faction="a_units";
		vehicleClass="Cold_British";
		icon="iconMan";
		nakedUniform="U_BasicBody";
		uniformClass="MNP_CombatUniform_DPMR";
		backpack="TWC_Backpack_Cold_War_MG";
		linkedItems[]=
		{
        "V_sud_nato_vest02",
		"SP_MkBushHelmet_Forrest",
		"ItemCompass",
		"ItemWatch"
		};
		respawnLinkedItems[]=
		{
        "V_sud_nato_vest02",
		"SP_MkBushHelmet_Forrest",
		"ItemCompass",
		"ItemWatch"
		};
		weapons[]=
		{
		"Throw",
		"Put",	
		"UK3CB_BAF_L7A2",
		"rhsusf_weap_m1911a1"
		};
		respawnweapons[]=
		{
		"Throw",
		"Put",	
		"UK3CB_BAF_L7A2",
		"rhsusf_weap_m1911a1"
		};
		magazines[]=
		{
		"UK3CB_BAF_75Rnd_T",
		"UK3CB_BAF_75Rnd",
		"UK3CB_BAF_75Rnd",	
		"rhsusf_mag_7x45acp_MHP",
		"rhsusf_mag_7x45acp_MHP",
		"rhsusf_mag_7x45acp_MHP",		
		"SmokeShell",
		"SmokeShell",
		"SmokeShell",
		"SmokeShell",
		"SmokeShell",
		"CUP_HandGrenade_L109A2_HE",
		"CUP_HandGrenade_L109A2_HE"
		};
		Respawnmagazines[]=
		{
		"UK3CB_BAF_75Rnd_T",
		"UK3CB_BAF_75Rnd",
		"UK3CB_BAF_75Rnd",	
		"rhsusf_mag_7x45acp_MHP",
		"rhsusf_mag_7x45acp_MHP",
		"rhsusf_mag_7x45acp_MHP",		
		"SmokeShell",
		"SmokeShell",
		"SmokeShell",
		"SmokeShell",
		"SmokeShell",
		"CUP_HandGrenade_L109A2_HE",
		"CUP_HandGrenade_L109A2_HE"
		};
		Items[]=
		{
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_morphine",
		"ACE_morphine",
		"ACE_EarPlugs"	
		};
		respawntems[]=
		{
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_morphine",
		"ACE_morphine",
		"ACE_EarPlugs"			
		};		
	};
	class ColdWar_MG_AS: B_Soldier_base_F
	{
		_generalMacro="Coldwar_MG";
		scope=2;
		displayName="Machine Gunner Assistant(Coldwar)";
		faction="a_units";
		vehicleClass="Cold_British";
		icon="iconMan";
		nakedUniform="U_BasicBody";
		uniformClass="MNP_CombatUniform_DPMR";
		backpack="TWC_Backpack_Cold_War_MGAS";
		linkedItems[]=
		{
        "V_sud_nato_vest02",
		"SP_MkBushHelmet_Forrest",
		"ItemCompass",
		"ItemWatch"
		};
		respawnLinkedItems[]=
		{
        "V_sud_nato_vest02",
		"SP_MkBushHelmet_Forrest",
		"ItemCompass",
		"ItemWatch"
		};
		weapons[]=
		{
		"Throw",
		"Put",	
		"hlc_rifle_L1A1SLR",
		"rhsusf_weap_m1911a1"
		};
		respawnweapons[]=
		{
		"Throw",
		"Put",	
		"hlc_rifle_L1A1SLR",
		"rhsusf_weap_m1911a1"
		};
		magazines[]=
		{
		"hlc_20Rnd_762x51_B_fal",
		"hlc_20Rnd_762x51_B_fal",
		"hlc_20Rnd_762x51_B_fal",
		"hlc_20Rnd_762x51_B_fal",
		"hlc_20Rnd_762x51_B_fal",		
		"rhsusf_mag_7x45acp_MHP",
		"rhsusf_mag_7x45acp_MHP",
		"rhsusf_mag_7x45acp_MHP",		
		"SmokeShell",
		"SmokeShell",
		"SmokeShell",
		"SmokeShell",
		"SmokeShell",
		"CUP_HandGrenade_L109A2_HE",
		"CUP_HandGrenade_L109A2_HE"
		};
		Respawnmagazines[]=
		{
		"hlc_20Rnd_762x51_B_fal",
		"hlc_20Rnd_762x51_B_fal",
		"hlc_20Rnd_762x51_B_fal",
		"hlc_20Rnd_762x51_B_fal",
		"hlc_20Rnd_762x51_B_fal",		
		"rhsusf_mag_7x45acp_MHP",
		"rhsusf_mag_7x45acp_MHP",
		"rhsusf_mag_7x45acp_MHP",		
		"SmokeShell",
		"SmokeShell",
		"SmokeShell",
		"SmokeShell",
		"SmokeShell",
		"CUP_HandGrenade_L109A2_HE",
		"CUP_HandGrenade_L109A2_HE"
		};
		Items[]=
		{
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_morphine",
		"ACE_morphine",
		"ACE_EarPlugs"
		};
		respawntems[]=
		{
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_morphine",
		"ACE_morphine",
		"ACE_EarPlugs"		
		};		
	};
	class ColdWar_Section_Leader: B_Soldier_base_F
	{
		_generalMacro="Coldwar_Section_Leader";
		scope=2;
		displayName="Section Leader(Coldwar)";
		faction="a_units";
		vehicleClass="Cold_British";
		icon="iconMan";
		nakedUniform="U_BasicBody";
		uniformClass="MNP_CombatUniform_DPMR";
		backpack="TWC_Backpack_Cold_War_Section";
		linkedItems[]=
		{
		"Binocular",		
        "V_sud_nato_vest01",
		"SP_MkBushHelmet_Forrest",
		"ItemMap",
		"ItemCompass",
		"ItemWatch"
		};
		respawnLinkedItems[]=
		{
		"Binocular",		
        "V_sud_nato_vest01",
		"SP_MkBushHelmet_Forrest",
		"ItemMap",	
		"ItemCompass",
		"ItemWatch"
		};
		weapons[]=
		{
		"Throw",
		"Put",
		"Binocular",
		"hlc_rifle_L1A1SLR",
		"rhsusf_weap_m1911a1"
		};
		respawnweapons[]=
		{
		"Throw",
		"Put",
		"Binocular",
		"hlc_rifle_L1A1SLR",
		"rhsusf_weap_m1911a1"
		};
		magazines[]=
		{
		"hlc_20Rnd_762x51_B_fal",
		"hlc_20Rnd_762x51_B_fal",
		"rhsusf_mag_7x45acp_MHP",
		"rhsusf_mag_7x45acp_MHP",
		"rhsusf_mag_7x45acp_MHP",		
		"SmokeShell",
		"SmokeShell",
		"SmokeShell",
		"SmokeShell",
		"SmokeShell",
		"CUP_HandGrenade_L109A2_HE",
		"CUP_HandGrenade_L109A2_HE"
		};
		Respawnmagazines[]=
		{
		"hlc_20Rnd_762x51_B_fal",
		"hlc_20Rnd_762x51_B_fal",
		"rhsusf_mag_7x45acp_MHP",
		"rhsusf_mag_7x45acp_MHP",
		"rhsusf_mag_7x45acp_MHP",		
		"SmokeShell",
		"SmokeShell",
		"SmokeShell",
		"SmokeShell",
		"SmokeShell",
		"CUP_HandGrenade_L109A2_HE",
		"CUP_HandGrenade_L109A2_HE"
		};
		Items[]=
		{
		"ACE_EarPlugs",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_morphine",
		"ACE_morphine",
		"UK_Beret_Paras"
		};
		respawntems[]=
		{
		"ACE_EarPlugs",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_morphine",
		"ACE_morphine",
		"UK_Beret_Paras"		
		};		
	};
	class ColdWar_Platoon_Commander: B_Soldier_base_F
	{
		_generalMacro="Coldwar_Platoon_Commander";
		scope=2;
		displayName="Platoon Commander(Coldwar)";
		faction="a_units";
		vehicleClass="Cold_British";
		icon="iconMan";
		nakedUniform="U_BasicBody";
		uniformClass="MNP_CombatUniform_DPMR";
		backpack="TWC_Backpack_Cold_War_Section";
		linkedItems[]=
		{		
        "V_sud_nato_vest03",
		"SP_MkBushHelmet_Forrest",
		"ItemMap",
		"ItemCompass",
		"ItemWatch"
		};
		respawnLinkedItems[]=
		{	
        "V_sud_nato_vest03",
		"SP_MkBushHelmet_Forrest",
		"ItemMap",	
		"ItemCompass",
		"ItemWatch"
		};
		weapons[]=
		{
		"Throw",
		"Put",
		"Binocular",
		"hlc_rifle_L1A1SLR",
		"rhsusf_weap_m1911a1"
		};
		respawnweapons[]=
		{
		"Throw",
		"Put",
		"Binocular",
		"hlc_rifle_L1A1SLR",
		"rhsusf_weap_m1911a1"
		};
		magazines[]=
		{
		"hlc_20Rnd_762x51_B_fal",
		"hlc_20Rnd_762x51_B_fal",
		"rhsusf_mag_7x45acp_MHP",
		"rhsusf_mag_7x45acp_MHP",
		"rhsusf_mag_7x45acp_MHP",		
		"SmokeShell",
		"SmokeShell",
		"SmokeShell",
		"SmokeShell",
		"SmokeShell",
		"CUP_HandGrenade_L109A2_HE",
		"CUP_HandGrenade_L109A2_HE"
		};
		Respawnmagazines[]=
		{
		"hlc_20Rnd_762x51_B_fal",
		"hlc_20Rnd_762x51_B_fal",
		"rhsusf_mag_7x45acp_MHP",
		"rhsusf_mag_7x45acp_MHP",
		"rhsusf_mag_7x45acp_MHP",		
		"SmokeShell",
		"SmokeShell",
		"SmokeShell",
		"SmokeShell",
		"SmokeShell",
		"CUP_HandGrenade_L109A2_HE",
		"CUP_HandGrenade_L109A2_HE"
		};
		Items[]=
		{
		"ACE_EarPlugs",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_morphine",
		"ACE_morphine",
		"UK_Beret_Paras"
		};
		respawntems[]=
		{
		"ACE_EarPlugs",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_morphine",
		"ACE_morphine",
		"UK_Beret_Paras"		
		};		
	};
	class ColdWar_sergeant: B_Soldier_base_F
	{
		_generalMacro="Coldwar_Platoon_sergeant";
		scope=2;
		displayName="Platoon Sergeant(Coldwar)";
		faction="a_units";
		vehicleClass="Cold_British";
		icon="iconMan";
		nakedUniform="U_BasicBody";
		uniformClass="MNP_CombatUniform_DPMR";
		backpack="TWC_Backpack_Cold_War_Section";
		linkedItems[]=
		{		
        "V_sud_nato_vest03",
		"SP_MkBushHelmet_Forrest",
		"ItemMap",
		"ItemCompass",
		"ItemWatch"
		};
		respawnLinkedItems[]=
		{		
        "V_sud_nato_vest03",
		"SP_MkBushHelmet_Forrest",
		"ItemMap",		
		"ItemCompass",
		"ItemWatch"
		};
		weapons[]=
		{
		"Throw",
		"Put",
		"Binocular",
		"hlc_rifle_L1A1SLR",
		"rhsusf_weap_m1911a1"
		};
		respawnweapons[]=
		{
		"Throw",
		"Put",
		"Binocular",
		"hlc_rifle_L1A1SLR",
		"rhsusf_weap_m1911a1"
		};
		magazines[]=
		{
		"hlc_20Rnd_762x51_B_fal",
		"hlc_20Rnd_762x51_B_fal",
		"rhsusf_mag_7x45acp_MHP",
		"rhsusf_mag_7x45acp_MHP",
		"rhsusf_mag_7x45acp_MHP",		
		"SmokeShell",
		"SmokeShell",
		"SmokeShell",
		"SmokeShell",
		"SmokeShell",
		"CUP_HandGrenade_L109A2_HE",
		"CUP_HandGrenade_L109A2_HE"
		};
		Respawnmagazines[]=
		{
		"hlc_20Rnd_762x51_B_fal",
		"hlc_20Rnd_762x51_B_fal",
		"rhsusf_mag_7x45acp_MHP",
		"rhsusf_mag_7x45acp_MHP",
		"rhsusf_mag_7x45acp_MHP",		
		"SmokeShell",
		"SmokeShell",
		"SmokeShell",
		"SmokeShell",
		"SmokeShell",
		"CUP_HandGrenade_L109A2_HE",
		"CUP_HandGrenade_L109A2_HE"
		};
		Items[]=
		{
		"ACE_EarPlugs",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_morphine",
		"ACE_morphine",
		"UK_Beret_Paras"
		};
		respawntems[]=
		{
		"ACE_EarPlugs",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_morphine",
		"ACE_morphine",
		"UK_Beret_Paras"
		};		
	};
	class ColdWar_Medic: B_Soldier_base_F
	{
		_generalMacro="Coldwar_Medic";
		scope=2;
		displayName="Platoon Medic(Coldwar)";
		faction="a_units";
		vehicleClass="Cold_British";
		icon="iconMan";
		nakedUniform="U_BasicBody";
		uniformClass="MNP_CombatUniform_DPMR";
		backpack="TWC_Backpack_Cold_Medic";
		linkedItems[]=
		{
        "V_sud_nato_vest04",
		"SP_MkBushHelmet_Forrest",
		"ItemCompass",
		"ItemWatch"
		};
		respawnLinkedItems[]=
		{
        "V_sud_nato_vest04",
		"SP_MkBushHelmet_Forrest",	
		"ItemCompass",
		"ItemWatch"
		};
		weapons[]=
		{
		"Throw",
		"Put",
		"rhsusf_weap_m1911a1"
		};
		respawnweapons[]=
		{
		"Throw",
		"Put",	
		"rhsusf_weap_m1911a1"
		};
		magazines[]=
		{
		"rhsusf_mag_7x45acp_MHP",
		"rhsusf_mag_7x45acp_MHP",
		"rhsusf_mag_7x45acp_MHP",		
		"SmokeShell",
		"SmokeShell",
		"SmokeShell",
		"SmokeShell",
		"SmokeShell"
		};
		Respawnmagazines[]=
		{
		"rhsusf_mag_7x45acp_MHP",
		"rhsusf_mag_7x45acp_MHP",
		"rhsusf_mag_7x45acp_MHP",		
		"SmokeShell",
		"SmokeShell",
		"SmokeShell",
		"SmokeShell",
		"SmokeShell"
		};
		Items[]=
		{
		"ACE_EarPlugs",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_morphine",
		"ACE_morphine"

		};
		respawntems[]=
		{
		"ACE_EarPlugs",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_morphine",
		"ACE_morphine"
		};		
	};
	class ColdWar_FAC: B_Soldier_base_F
	{
		_generalMacro="Coldwar_Platoon_FAC";
		scope=2;
		displayName="Platoon FAC(Coldwar)";
		faction="a_units";
		vehicleClass="Cold_British";
		icon="iconMan";
		nakedUniform="U_BasicBody";
		uniformClass="MNP_CombatUniform_DPMR";
		backpack="TWC_Backpack_Cold_War_FAC";
		linkedItems[]=
		{		
        "V_sud_nato_vest03",
		"SP_MkBushHelmet_Forrest",
		"ItemMap",
		"ItemCompass",
		"ItemWatch"
		};
		respawnLinkedItems[]=
		{		
        "V_sud_nato_vest03",
		"SP_MkBushHelmet_Forrest",
		"ItemMap",		
		"ItemCompass",
		"ItemWatch"
		};
		weapons[]=
		{
		"Throw",
		"Put",
		"Binocular",
		"hlc_rifle_L1A1SLR",
		"rhsusf_weap_m1911a1"
		};
		respawnweapons[]=
		{
		"Throw",
		"Put",
		"Binocular",
		"hlc_rifle_L1A1SLR",
		"rhsusf_weap_m1911a1"
		};
		magazines[]=
		{
		"rhsusf_mag_7x45acp_MHP",
		"rhsusf_mag_7x45acp_MHP",
		"rhsusf_mag_7x45acp_MHP",
		"hlc_20Rnd_762x51_B_fal",
		"hlc_20Rnd_762x51_B_fal",
		"hlc_20Rnd_762x51_B_fal",
		"SmokeShell",
		"SmokeShell",
		"SmokeShell",
		"SmokeShell",
		"SmokeShell",
		"smokeshellRed",
		"smokeshellRed",
		"smokeshellRed",
		"smokeshellGreen",
		"smokeshellGreen",
		"smokeshellGreen",
		"smokeshellBlue",
		"smokeshellBlue",
		"smokeshellBlue",
		"CUP_HandGrenade_L109A2_HE",
		"CUP_HandGrenade_L109A2_HE"
		};
		Respawnmagazines[]=
		{
		"rhsusf_mag_7x45acp_MHP",
		"rhsusf_mag_7x45acp_MHP",
		"rhsusf_mag_7x45acp_MHP",
		"rhsusf_mag_7x45acp_MHP",
		"hlc_20Rnd_762x51_B_fal",
		"hlc_20Rnd_762x51_B_fal",
		"hlc_20Rnd_762x51_B_fal",
		"SmokeShell",
		"SmokeShell",
		"SmokeShell",
		"SmokeShell",
		"SmokeShell",
		"smokeshellRed",
		"smokeshellRed",
		"smokeshellRed",
		"smokeshellGreen",
		"smokeshellGreen",
		"smokeshellGreen",
		"smokeshellBlue",
		"smokeshellBlue",
		"smokeshellBlue",
		"CUP_HandGrenade_L109A2_HE",
		"CUP_HandGrenade_L109A2_HE"
		};
		Items[]=
		{
		"ACE_EarPlugs",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_morphine",
		"ACE_morphine",
		"UK_Beret_Paras"
		};
		respawntems[]=
		{
		"ACE_EarPlugs",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_morphine",
		"ACE_morphine",
		"UK_Beret_Paras"
		};		
	};
	class ColdWar_HeloPilot: B_Soldier_base_F
	{
		_generalMacro="Coldwar_HelicopterPilot";
		scope=2;
		displayName="Helicopter Pilot(Coldwar)";
		faction="a_units";
		vehicleClass="Cold_British";
		icon="iconMan";
		nakedUniform="U_BasicBody";
		uniformClass="MNP_CombatUniform_DPMR";
		backpack="TWC_Backpack_Cold_War_Pilot";
		linkedItems[]=
		{
		"UK3CB_BAF_H_PilotHelmetHeli_A",
		"ItemMap",
		"ItemCompass",
		"ItemWatch"
		};
		respawnLinkedItems[]=
		{
		"UK3CB_BAF_H_PilotHelmetHeli_A",
		"ItemMap",		
		"ItemCompass",
		"ItemWatch"
		};
		weapons[]=
		{
		"Throw",
		"Put",
		"rhsusf_weap_m1911a1"
		};
		respawnweapons[]=
		{
		"Throw",
		"Put",
		"rhsusf_weap_m1911a1"
		};
		magazines[]=
		{
		"rhsusf_mag_7x45acp_MHP",
		"rhsusf_mag_7x45acp_MHP",	
		"SmokeShell",
		"SmokeShell"
		};
		Respawnmagazines[]=
		{
		"rhsusf_mag_7x45acp_MHP",
		"rhsusf_mag_7x45acp_MHP",	
		"SmokeShell",
		"SmokeShell"
		};
		Items[]=
		{
		"ACE_EarPlugs",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_morphine",
		"ACE_morphine"
		};
		respawntems[]=
		{
		"ACE_EarPlugs",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_morphine",
		"ACE_morphine"
		};		
	};
	class ColdWar_JetPilot: B_Soldier_base_F
	{
		_generalMacro="Coldwar_JetPilot";
		scope=2;
		displayName="Jet Pilot(Coldwar)";
		faction="a_units";
		vehicleClass="Cold_British";
		icon="iconMan";
		nakedUniform="U_BasicBody";
		uniformClass="UK3CB_BAF_U_HeliPilotCoveralls_RAF";
		backpack="TWC_Backpack_Cold_War_Pilot";
		linkedItems[]=
		{
		"RHS_jetpilot_usaf",
		"ItemMap",
		"ItemCompass",
		"ItemWatch"
		};
		respawnLinkedItems[]=
		{
		"RHS_jetpilot_usaf",
		"ItemMap",		
		"ItemCompass",
		"ItemWatch"
		};
		weapons[]=
		{
		"Throw",
		"Put",
		"rhsusf_weap_m1911a1"
		};
		respawnweapons[]=
		{
		"Throw",
		"Put",
		"rhsusf_weap_m1911a1"
		};
		magazines[]=
		{
		"rhsusf_mag_7x45acp_MHP",
		"rhsusf_mag_7x45acp_MHP",	
		"SmokeShell",
		"SmokeShell"
		};
		Respawnmagazines[]=
		{
		"rhsusf_mag_7x45acp_MHP",
		"rhsusf_mag_7x45acp_MHP",	
		"SmokeShell",
		"SmokeShell"
		};
		Items[]=
		{
		"ACE_EarPlugs",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_morphine",
		"ACE_morphine",
		"ACE_morphine",
		"ACE_morphine"
		};
		respawntems[]=
		{
		"ACE_EarPlugs",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_morphine",
		"ACE_morphine",
		"ACE_morphine",
		"ACE_morphine"
		};		
	};
	class ColdWar_AA_Gunner: B_Soldier_base_F
	{
		_generalMacro="Coldwar_AA_Gunner";
		scope=2;
		displayName="AA Gunner(Coldwar)";
		faction="a_units";
		vehicleClass="Cold_British";
		icon="iconMan";
		nakedUniform="U_BasicBody";
		uniformClass="MNP_CombatUniform_DPMR";
		backpack="TWC_Backpack_Cold_War_AA";
		linkedItems[]=
		{
        "V_sud_nato_vest05",
		"SP_MkBushHelmet_Forrest",
		"ItemCompass",
		"ItemWatch"
		};
		respawnLinkedItems[]=
		{
        "V_sud_nato_vest05",
		"SP_MkBushHelmet_Forrest",
		"ItemCompass",
		"ItemWatch"
		};
		weapons[]=
		{
		"Throw",
		"Put",	
		"hlc_rifle_L1A1SLR",
		"rhsusf_weap_m1911a1",
		"FIMStingerA"
		};
		respawnweapons[]=
		{
		"Throw",
		"Put",	
		"hlc_rifle_L1A1SLR",
		"rhsusf_weap_m1911a1",
		"FIMStingerA"
		};
		magazines[]=
		{
		"rhsusf_mag_7x45acp_MHP",
		"rhsusf_mag_7x45acp_MHP",
		"rhsusf_mag_7x45acp_MHP",
		"hlc_20Rnd_762x51_B_fal",
		"hlc_20Rnd_762x51_B_fal",
		"hlc_20Rnd_762x51_B_fal",
		"hlc_20Rnd_762x51_B_fal",
		"SmokeShell",
		"SmokeShell",
		"SmokeShell",
		"SmokeShell",
		"SmokeShell",
		"CUP_HandGrenade_L109A2_HE",
		"CUP_HandGrenade_L109A2_HE",
		"CUP_Stinger_M"
		};
		Respawnmagazines[]=
		{
		"rhsusf_mag_7x45acp_MHP",
		"rhsusf_mag_7x45acp_MHP",
		"rhsusf_mag_7x45acp_MHP",
		"hlc_20Rnd_762x51_B_fal",
		"hlc_20Rnd_762x51_B_fal",
		"hlc_20Rnd_762x51_B_fal",
		"hlc_20Rnd_762x51_B_fal",
		"SmokeShell",
		"SmokeShell",
		"SmokeShell",
		"SmokeShell",
		"SmokeShell",
		"CUP_HandGrenade_L109A2_HE",
		"CUP_HandGrenade_L109A2_HE",
		"CUP_Stinger_M"
		};
		Items[]=
		{
		"ACE_EarPlugs",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_morphine",
		"ACE_morphine"
		};
		respawntems[]=
		{
		"ACE_EarPlugs",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_morphine",
		"ACE_morphine"			
		};		
	};
		class ColdWar_AA_Assistant: B_Soldier_base_F
	{
		_generalMacro="Coldwar_AA_Assistant";
		scope=2;
		displayName="AA Assistant(Coldwar)";
		faction="a_units";
		vehicleClass="Cold_British";
		icon="iconMan";
		nakedUniform="U_BasicBody";
		uniformClass="MNP_CombatUniform_DPMR";
		backpack="TWC_Backpack_Cold_War_AA";
		linkedItems[]=
		{
        "V_sud_nato_vest05",
		"SP_MkBushHelmet_Forrest",
		"ItemCompass",
		"ItemWatch"
		};
		respawnLinkedItems[]=
		{
        "V_sud_nato_vest05",
		"SP_MkBushHelmet_Forrest",
		"ItemCompass",
		"ItemWatch"
		};
		weapons[]=
		{
		"Throw",
		"Put",	
		"hlc_rifle_L1A1SLR",
		"rhsusf_weap_m1911a1"
		};
		respawnweapons[]=
		{
		"Throw",
		"Put",	
		"hlc_rifle_L1A1SLR",
		"rhsusf_weap_m1911a1"
		};
		magazines[]=
		{
		"rhsusf_mag_7x45acp_MHP",
		"rhsusf_mag_7x45acp_MHP",
		"rhsusf_mag_7x45acp_MHP",
		"hlc_20Rnd_762x51_B_fal",
		"hlc_20Rnd_762x51_B_fal",
		"hlc_20Rnd_762x51_B_fal",
		"hlc_20Rnd_762x51_B_fal",
		"SmokeShell",
		"SmokeShell",
		"SmokeShell",
		"SmokeShell",
		"SmokeShell",
		"CUP_HandGrenade_L109A2_HE",
		"CUP_HandGrenade_L109A2_HE"
		};
		Respawnmagazines[]=
		{
		"rhsusf_mag_7x45acp_MHP",
		"rhsusf_mag_7x45acp_MHP",
		"rhsusf_mag_7x45acp_MHP",
		"hlc_20Rnd_762x51_B_fal",
		"hlc_20Rnd_762x51_B_fal",
		"hlc_20Rnd_762x51_B_fal",
		"hlc_20Rnd_762x51_B_fal",
		"SmokeShell",
		"SmokeShell",
		"SmokeShell",
		"SmokeShell",
		"SmokeShell",
		"CUP_HandGrenade_L109A2_HE",
		"CUP_HandGrenade_L109A2_HE"
		};
		Items[]=
		{
		"ACE_EarPlugs",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_morphine",
		"ACE_morphine"
		};
		respawntems[]=
		{
		"ACE_EarPlugs",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_morphine",
		"ACE_morphine"			
		};		
	};
};