class CfgPatches {
	class twc_faction {
		units[] = {
			"GulfWar_Iraqi_Squadleader",
			"GulfWar_Iraqi_Rifleman",
			"GulfWar_Iraqi_RPG",
			"GulfWar_Iraqi_RPGAssistant",
			"GulfWar_Iraqi_MG",
			"GulfWar_Iraqi_MGAssistant",
			"Russian_Squadleader",
			"Russian_Rifleman",
			"Russian_Grenadier",
			"Russian_Seniorrifleman",
			"Russian_Grenadierassistant",
			"Russian_Automaticrifleman",
			"Russian_Vehiclecommander",
			"Russian_Vehiclecrew",
			"ColdWar_USSR_Squadleader",
			"ColdWar_USSR_Rifleman",
			"ColdWar_USSR_Grenadier",
			"ColdWar_USSR_Grenadierassistant",
			"ColdWar_USSR_Efreitor",
			"ColdWar_USSR_MachineGunner",
			"Afr_Mil_Rifleman",
			"Afr_Mil_AT_Assistant",
			"Afr_Mil_RiflemanAT",
			"Afr_Mil_Machinegunner",
			"Afr_Mil_Teamleader",
			"Afr_Mil_Squadleader",
			"Afr_Mil_Officer",
			"Afr_Mil_Crewman",
			"IRA_Squadleader",
			"IRA_Rifleman_M16",
			"IRA_Rifleman_AKM",
			"IRA_Rifleman_FAL",
			"IRA_Rifleman_AT",
			"IRA_Autorifleman",
			"IRA_Field_L42Sniper",
			"IRA_Field_Bren",
			"IRA_Field_Falv1",
			"IRA_Field_Falv2",
			"IRA_Field_AK74V1",
			"IRA_Field_AK74V2",
			"IRA_Field_M16A2v1",
			"IRA_Field_M16A2v2",
			"IRA_Field_SLRv1",
			"IRA_Field_SLRv2",
			"IRA_Field_SLR_AT",
			"IRA_Field_M16A2_AT",
			"IRA_Field_Enfieldv1",
			"IRA_Field_Enfieldv2",
			"IRA_Field_RPK",
			"IRA_Field_M79",
			"IRA_Field_AA",
			"IRA_Field_Static",
			"IRA_Urban_Sterling",
			"IRA_Urban_Pistoleer",
			"IRA_Urban_AKS74U",
			"IRA_Urban_MP5",
			"IRA_Urban_Skorpion",
			"usa_1970_medic",
			"usa_1970_leader",
			"usa_1970_grenadier",
			
			//African Pirates
			"Afr_Pirate_SquadLeader_Random",
			"Afr_Pirate_Rifleman_Random",
			"Afr_Pirate_Grenadier_Random",
			"Afr_Pirate_RPG_Random",
			"Afr_Pirate_MachineGunner",
			"Afr_Pirate_Marksman_Random",
			
			//African Pirates Old
			"Afr_Pirate_Skipper",
			"Afr_Pirate_Captain",
			"Afr_Pirate_AK",
			"Afr_Pirate_AKM",
			"Afr_Pirate_AKS",
			"Afr_Pirate_RPG",
			"Afr_Pirate_AK74",
			"Afr_Pirate_AKS74",
			"Afr_Pirate_AK74GP25",
			"Afr_Pirate_FAL",
			"Afr_Pirate_M14",
			"Afr_Pirate_SMLE",
			"Afr_Pirate_AR_RPD",
			"Afr_Pirate_AR_RPK",
			"Afr_Pirate_MG_M60",
			"Afr_Pirate_MG_PKM",
			"Afr_Pirate_MM_SVD",
			"Asn_Pirate_Skipper",
			"Asn_Pirate_Captain",
			"Asn_Pirate_AK",
			"Asn_Pirate_AKM",
			"Asn_Pirate_AKS",
			"Asn_Pirate_RPG",
			"Asn_Pirate_AK74",
			"Asn_Pirate_AKS74",
			"Asn_Pirate_AK74GP25",
			"Asn_Pirate_FAL",
			"Asn_Pirate_M14",
			"Asn_Pirate_SMLE",
			"Asn_Pirate_AR_RPD",
			"Asn_Pirate_AR_RPK",
			"Asn_Pirate_MG_M60",
			"Asn_Pirate_MG_PKM",
			"Afr_Pirate_MM_SVD",
			
			
			"TWC_WaPArmy_Taviana_Base",
			"TWC_WaPArmy_Taviana_Squadleader",
			"TWC_WaPArmy_Taviana_Grenadier",
			"TWC_WaPArmy_Taviana_Grenadier_Ass",
			"TWC_WaPArmy_Taviana_AutoRifleman",
			"TWC_WaPArmy_Taviana_MG",
			"TWC_WaPArmy_Taviana_Sniper",
			"TWC_WaPArmy_Taviana_AAGunner",
			"TWC_WaPArmy_Taviana_AAAssistant",
			"TWC_WaPArmy_Taviana_ATGunner",
			"TWC_WaPArmy_Taviana_ATAssistant",
			"TWC_WaPArmy_Taviana_Crewman_Camo",
			"TWC_WaPArmy_Taviana_Crewman_Black",
			"TWC_WaPArmy_Taviana_Driver",
			"TWC_WaPArmy_Taviana_HPilot",
			"TWC_WaPArmy_Taviana_JPilot",
			"TWC_WaPArmy_Taviana_Squadleader_Winter",
			"TWC_WaPArmy_Taviana_Grenadier_Winter",
			"TWC_WaPArmy_Taviana_Grenadier_Ass_Winter",
			"TWC_WaPArmy_Taviana_AutoRifleman_Winter",
			"TWC_WaPArmy_Taviana_MG_Winter",
			"TWC_WaPArmy_Taviana_Sniper_Winter",
			"TWC_WaPArmy_Taviana_AAGunner_Winter",
			"TWC_WaPArmy_Taviana_AAAssistant_Winter",
			"TWC_WaPArmy_Taviana_ATGunner_Winter",
			"TWC_WaPArmy_Taviana_ATAssistant_Winter",
			"TWC_WaPArmy_Taviana_Crewman_Camo_Winter",
			"TWC_WaPArmy_Taviana_Driver_Winter",
			"TWC_WaPArmy_Taviana_UAZ_Unarmed",
			"TWC_WaPArmy_Taviana_UAZ_Open",
			"TWC_WaPArmy_Taviana_UAZ_MG",
			"TWC_WaPArmy_Taviana_UAZ_AGS30",
			"TWC_WaPArmy_Taviana_UAZ_SPG9",
			"TWC_WaPArmy_Taviana_UAZ_METIS",
			"TWC_WaPArmy_Taviana_Ural",
			"TWC_WaPArmy_Taviana_Ural_Open",
			"TWC_WaPArmy_Taviana_Ural_Repair",
			"TWC_WaPArmy_Taviana_Ural_Reammo",
			"TWC_WaPArmy_Taviana_Ural_Empty",
			"TWC_WaPArmy_Taviana_Ural_ZU23",
			"TWC_WaPArmy_Taviana_BM21",
			"TWC_WaPArmy_Taviana_BMP1",
			"TWC_WaPArmy_Taviana_BMP2",
			"TWC_WaPArmy_Taviana_BMP2_HQ",
			"TWC_WaPArmy_Taviana_BMP2_Amb",
			"TWC_WaPArmy_Taviana_BMP2_ZU23",
			"TWC_WaPArmy_Taviana_BRDM",
			"TWC_WaPArmy_Taviana_BRDM_ATGM",
			"TWC_WaPArmy_Taviana_BRDM_HQ",
			"TWC_WaPArmy_Taviana_BTR40",
			"TWC_WaPArmy_Taviana_BTR40MG",
			"TWC_WaPArmy_Taviana_BTR60",
			"TWC_WaPArmy_Taviana_T55",
			"TWC_WaPArmy_Taviana_T72",
			"TWC_WaPArmy_Taviana_T72A",
			"TWC_WaPArmy_Taviana_ZSU23"
		};
		
		weapons[] = {};
		requiredVersion = 0.1;
		requiredAddons[] = {
			"A3_Characters_F_BLUFOR",
			"A3_Characters_F_OPFOR",
			"A3_Characters_F_Common",
			"A3_Characters_F",
			"a3_characters_f_beta",
			"a3_characters_f_gamma"
		};
	};
};

#include "CfgEditorSubCategories.hpp"
#include "CfgFactionClasses.hpp"
#include "cfgWeapons.hpp"
class EventHandlers;
#include "cfgVehicles.hpp"
#include "CfgMarkers.hpp"