class oksv_rifleman;
class oksv_gp;
class oksv_machinegunne;
class oksv_sniper;
class oksv_officer;
class TWC_USSR_Afghan_Rifleman_Medic: oksv_rifleman
{
	faction="TWC_USSR_Afghan";
	uniformClass="rhs_uniform_m88_patchless";
	backpack="USSR_small_medic_bag";
	Items[]=
	{
		"ACE_EarPlugs",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_morphine",
		"ACE_epinephrine",
		"ACE_tourniquet",
		"ACE_tourniquet"
	};
	respawntems[]=
	{
		"ACE_EarPlugs",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_morphine",
		"ACE_epinephrine",
		"ACE_tourniquet",
		"ACE_tourniquet"		
	};
	weapons[]=
	{
		"Throw",
		"Put",
		"CUP_arifle_AK74"
	};
	respawnweapons[]=
	{
		"Throw",
		"Put",
		"CUP_arifle_AK74"
	};
	magazines[]=
	{
		"CUP_30Rnd_545x39_AK_M",
		"CUP_30Rnd_545x39_AK_M",
		"CUP_30Rnd_545x39_AK_M",
		"CUP_30Rnd_545x39_AK_M",
		"CUP_30Rnd_545x39_AK_M",
		"CUP_30Rnd_545x39_AK_M",
		"CUP_30Rnd_545x39_AK_M",
		"rhs_mag_rgd5",
		"rhs_mag_rgd5",
		"rhs_mag_rdg2_white"
	};
	Respawnmagazines[]=
	{
		"CUP_30Rnd_545x39_AK_M",
		"CUP_30Rnd_545x39_AK_M",
		"CUP_30Rnd_545x39_AK_M",
		"CUP_30Rnd_545x39_AK_M",
		"CUP_30Rnd_545x39_AK_M",
		"CUP_30Rnd_545x39_AK_M",
		"CUP_30Rnd_545x39_AK_M",
		"rhs_mag_rgd5",
		"rhs_mag_rgd5",
		"rhs_mag_rdg2_white"
	};
};
class TWC_USSR_Afghan_Rifleman: TWC_USSR_Afghan_Rifleman_Medic
{
	backpack="";
};
class TWC_USSR_Afghan_Senior_Rifleman: oksv_gp
{
	faction="TWC_USSR_Afghan";
	uniformClass="rhs_uniform_m88_patchless";
	backpack="USSR_Serg_bag";
	Items[]=
	{
		"ACE_EarPlugs",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_morphine",
		"ACE_epinephrine",
		"ACE_tourniquet",
		"ACE_tourniquet"
	};
	respawntems[]=
	{
		"ACE_EarPlugs",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_morphine",
		"ACE_epinephrine",
		"ACE_tourniquet",
		"ACE_tourniquet"		
	};
	weapons[]=
	{
		"Throw",
		"Put",
		"CUP_arifle_AK74_GL"
	};
	respawnweapons[]=
	{
		"Throw",
		"Put",
		"CUP_arifle_AK74_GL"
	};
	magazines[]=
	{
		"CUP_30Rnd_545x39_AK_M",
		"CUP_30Rnd_545x39_AK_M",
		"CUP_30Rnd_545x39_AK_M",
		"CUP_30Rnd_545x39_AK_M",
		"CUP_30Rnd_545x39_AK_M",
		"CUP_30Rnd_545x39_AK_M",
		"CUP_30Rnd_545x39_AK_M",
		"CUP_1Rnd_HE_GP25_M",
		"CUP_1Rnd_HE_GP25_M",
		"CUP_1Rnd_HE_GP25_M",
		"CUP_1Rnd_HE_GP25_M",
		"CUP_1Rnd_HE_GP25_M",
		"CUP_1Rnd_HE_GP25_M",
		"CUP_1Rnd_HE_GP25_M",
		"CUP_1Rnd_SmokeRed_GP25_M",
		"CUP_1Rnd_SMOKE_GP25_M",
		"CUP_1Rnd_SMOKE_GP25_M",
		"rhs_mag_rgd5",
		"rhs_mag_rgd5",
		"rhs_mag_rdg2_white"
	};
	Respawnmagazines[]=
	{
		"CUP_30Rnd_545x39_AK_M",
		"CUP_30Rnd_545x39_AK_M",
		"CUP_30Rnd_545x39_AK_M",
		"CUP_30Rnd_545x39_AK_M",
		"CUP_30Rnd_545x39_AK_M",
		"CUP_30Rnd_545x39_AK_M",
		"CUP_30Rnd_545x39_AK_M",
		"CUP_1Rnd_HE_GP25_M",
		"CUP_1Rnd_HE_GP25_M",
		"CUP_1Rnd_HE_GP25_M",
		"CUP_1Rnd_HE_GP25_M",
		"CUP_1Rnd_HE_GP25_M",
		"CUP_1Rnd_HE_GP25_M",
		"CUP_1Rnd_HE_GP25_M",
		"CUP_1Rnd_SmokeRed_GP25_M",
		"CUP_1Rnd_SMOKE_GP25_M",
		"CUP_1Rnd_SMOKE_GP25_M",
		"rhs_mag_rgd5",
		"rhs_mag_rgd5",
		"rhs_mag_rdg2_white"
	};
};
class TWC_USSR_Afghan_Grenadier: TWC_USSR_Afghan_Rifleman_Medic
{
	backpack="USSR_RPG_bag";
	weapons[]=
	{
		"Throw",
		"Put",
		"CUP_arifle_AK74",
		"rhs_weap_rpg7"
	};
	respawnweapons[]=
	{
		"Throw",
		"Put",
		"CUP_arifle_AK74",
		"rhs_weap_rpg7"
	};
};
class TWC_USSR_Afghan_Grenadier_Assistant: TWC_USSR_Afghan_Rifleman_Medic
{
	backpack="USSR_RPG_bag";
};
class TWC_USSR_Afghan_AutoRifleman: TWC_USSR_Afghan_Rifleman
{
	weapons[]=
	{
		"Throw",
		"Put",
		"CUP_arifle_RPK74_45"
	};
	respawnweapons[]=
	{
		"Throw",
		"Put",
		"CUP_arifle_RPK74_45"
	};
	magazines[]=
	{
		"CUP_45Rnd_TE4_LRT4_Green_Tracer_545x39_RPK_M",
		"CUP_45Rnd_TE4_LRT4_Green_Tracer_545x39_RPK_M",
		"CUP_45Rnd_TE4_LRT4_Green_Tracer_545x39_RPK_M",
		"CUP_45Rnd_TE4_LRT4_Green_Tracer_545x39_RPK_M",
		"CUP_45Rnd_TE4_LRT4_Green_Tracer_545x39_RPK_M",
		"rhs_mag_rgd5",
		"rhs_mag_rgd5",
		"rhs_mag_rdg2_white"
	};
	Respawnmagazines[]=
	{
		"CUP_45Rnd_TE4_LRT4_Green_Tracer_545x39_RPK_M",
		"CUP_45Rnd_TE4_LRT4_Green_Tracer_545x39_RPK_M",
		"CUP_45Rnd_TE4_LRT4_Green_Tracer_545x39_RPK_M",
		"CUP_45Rnd_TE4_LRT4_Green_Tracer_545x39_RPK_M",
		"CUP_45Rnd_TE4_LRT4_Green_Tracer_545x39_RPK_M",
		"rhs_mag_rgd5",
		"rhs_mag_rgd5",
		"rhs_mag_rdg2_white"
	};
};
class TWC_USSR_Afghan_MachineGunner: oksv_machinegunne
{
	faction="TWC_USSR_Afghan";
	uniformClass="rhs_uniform_m88_patchless";
	Items[]=
	{
		"ACE_EarPlugs",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_morphine",
		"ACE_epinephrine",
		"ACE_tourniquet",
		"ACE_tourniquet"
	};
	respawntems[]=
	{
		"ACE_EarPlugs",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_morphine",
		"ACE_epinephrine",
		"ACE_tourniquet",
		"ACE_tourniquet"		
	};
	weapons[]=
	{
		"Throw",
		"Put",
		"rhs_weap_pkm"
	};
	respawnweapons[]=
	{
		"Throw",
		"Put",
		"rhs_weap_pkm"
	};
	magazines[]=
	{
		"rhs_100Rnd_762x54mmR_green",
		"rhs_100Rnd_762x54mmR_green",
		"rhs_mag_rgd5",
		"rhs_mag_rgd5",
		"rhs_mag_rdg2_white"
	};
	Respawnmagazines[]=
	{
		"rhs_100Rnd_762x54mmR_green",
		"rhs_100Rnd_762x54mmR_green",
		"rhs_mag_rgd5",
		"rhs_mag_rgd5",
		"rhs_mag_rdg2_white"
	};
};
class TWC_USSR_Afghan_Marksman: oksv_sniper
{
	faction="TWC_USSR_Afghan";
	uniformClass="rhs_uniform_m88_patchless";
	Items[]=
	{
		"ACE_EarPlugs",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_morphine",
		"ACE_epinephrine",
		"ACE_tourniquet",
		"ACE_tourniquet"
	};
	respawntems[]=
	{
		"ACE_EarPlugs",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_morphine",
		"ACE_epinephrine",
		"ACE_tourniquet",
		"ACE_tourniquet"		
	};
	weapons[]=
	{
		"Throw",
		"Put",
		"CUP_srifle_SVD"
	};
	respawnweapons[]=
	{
		"Throw",
		"Put",
		"CUP_srifle_SVD"
	};
	magazines[]=
	{
		"CUP_10Rnd_762x54_SVD_M",
		"CUP_10Rnd_762x54_SVD_M",
		"CUP_10Rnd_762x54_SVD_M",
		"CUP_10Rnd_762x54_SVD_M",
		"CUP_10Rnd_762x54_SVD_M",
		"CUP_10Rnd_762x54_SVD_M",
		"CUP_10Rnd_762x54_SVD_M",
		"rhs_mag_rgd5",
		"rhs_mag_rgd5",
		"rhs_mag_rdg2_white"
	};
	Respawnmagazines[]=
	{
		"CUP_10Rnd_762x54_SVD_M",
		"CUP_10Rnd_762x54_SVD_M",
		"CUP_10Rnd_762x54_SVD_M",
		"CUP_10Rnd_762x54_SVD_M",
		"CUP_10Rnd_762x54_SVD_M",
		"CUP_10Rnd_762x54_SVD_M",
		"CUP_10Rnd_762x54_SVD_M",
		"rhs_mag_rgd5",
		"rhs_mag_rgd5",
		"rhs_mag_rdg2_white"
	};
};
class TWC_USSR_Afghan_Officer: oksv_officer
{
	faction="TWC_USSR_Afghan";
	uniformClass="rhs_uniform_m88_patchless";
	linkedItems[] =
	{
		"6B3_RHS_OF",
		"panama_afg2",
		"ItemMap",
		"ItemCompass",
		"ItemWatch"
	};
	Items[]=
	{
		"ACE_EarPlugs",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_morphine",
		"ACE_epinephrine",
		"ACE_tourniquet",
		"ACE_tourniquet"
	};
	respawntems[]=
	{
		"ACE_EarPlugs",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_morphine",
		"ACE_epinephrine",
		"ACE_tourniquet",
		"ACE_tourniquet"		
	};
	weapons[]=
	{
		"Throw",
		"Put",
		"CUP_arifle_AK74"
	};
	respawnweapons[]=
	{
		"Throw",
		"Put",
		"CUP_arifle_AK74"
	};
	magazines[]=
	{
		"CUP_30Rnd_545x39_AK_M",
		"CUP_30Rnd_545x39_AK_M",
		"CUP_30Rnd_545x39_AK_M",
		"CUP_30Rnd_545x39_AK_M",
		"CUP_30Rnd_545x39_AK_M",
		"CUP_30Rnd_545x39_AK_M",
		"CUP_30Rnd_545x39_AK_M",
		"rhs_mag_rgd5",
		"rhs_mag_rgd5",
		"rhs_mag_rdg2_white"
	};
	Respawnmagazines[]=
	{
		"CUP_30Rnd_545x39_AK_M",
		"CUP_30Rnd_545x39_AK_M",
		"CUP_30Rnd_545x39_AK_M",
		"CUP_30Rnd_545x39_AK_M",
		"CUP_30Rnd_545x39_AK_M",
		"CUP_30Rnd_545x39_AK_M",
		"CUP_30Rnd_545x39_AK_M",
		"rhs_mag_rgd5",
		"rhs_mag_rgd5",
		"rhs_mag_rdg2_white"
	};
};
class TWC_USSR_Afghan_Sergeant: TWC_USSR_Afghan_Officer
{
	backpack="USSR_Serg_bag";
};
class TWC_USSR_Afghan_Medic: TWC_USSR_Afghan_Officer
{
	backpack="USSR_big_medic_bag";
};