#define SECTION_FIELDDRESSING 20
#define SECTION_QUIKCLOT 20
#define SECTION_ELASTICBANDAGE 20
#define SECTION_PACKINGBANDAGE 20
#define SECTION_TOURNIQUET 6
#define SECTION_MORPHINE 10
#define SECTION_EPINEPHRINE 6

#define SECTION_SMOKE 6
#define SECTION_GRENADE 6

// Modifiers to the total amount
#define EMPTY_VEHICLE 0
#define WW2_WILLYS 0.5
#define WW2_UNICARRIER 1
#define WW2_GLIDER 2

#define CURRENT_VEHICLE EMPTY_VEHICLE