//COIN, DISMOUNTED, Arctic
//Section
class TWC_Infantry_2000_COIN_Dismounted_Arctic_Rifleman: TWC_Infantry_2000_COIN_Arctic_Rifleman
{
	CATEGORY(TWC_Infantry_Dismounted_COIN_2000_Arctic)
	backpack = "TWC_Backpack_2000_COIN_Dismounted_Arctic_Rifleman";
};
class TWC_Infantry_2000_COIN_Dismounted_Arctic_Marksman: TWC_Infantry_2000_COIN_Arctic_Marksman
{
	CATEGORY(TWC_Infantry_Dismounted_COIN_2000_Arctic)
	backpack = "TWC_Backpack_2000_COIN_Dismounted_Arctic_Marksman";
};
class TWC_Infantry_2000_COIN_Dismounted_Arctic_Grenadier: TWC_Infantry_2000_COIN_Arctic_Grenadier
{
	CATEGORY(TWC_Infantry_Dismounted_COIN_2000_Arctic)
	backpack = "TWC_Backpack_2000_COIN_Dismounted_Arctic_Grenadier";
};
class TWC_Infantry_2000_COIN_Dismounted_Arctic_Autorifleman: TWC_Infantry_2000_COIN_Arctic_Autorifleman
{
	CATEGORY(TWC_Infantry_Dismounted_COIN_2000_Arctic)
	backpack = "TWC_Backpack_2000_COIN_Dismounted_Arctic_Autorifleman";
};
class TWC_Infantry_2000_COIN_Dismounted_Arctic_SectionCommander: TWC_Infantry_2000_COIN_Arctic_SectionCommander
{
	CATEGORY(TWC_Infantry_Dismounted_COIN_2000_Arctic)
	backpack = "TWC_Backpack_2000_COIN_Dismounted_Arctic_SectionCommander";
};
class TWC_Infantry_2000_COIN_Dismounted_Arctic_2iC: TWC_Infantry_2000_COIN_Arctic_2iC
{
	CATEGORY(TWC_Infantry_Dismounted_COIN_2000_Arctic)
	backpack = "TWC_Backpack_2000_COIN_Dismounted_Arctic_2iC";
};

//Platoon Command
class TWC_Infantry_2000_COIN_Dismounted_Arctic_Platoon_Commander: TWC_Infantry_2000_COIN_Arctic_Platoon_Commander
{
	CATEGORY(TWC_Infantry_Dismounted_COIN_2000_Arctic)
	backpack = "TWC_Backpack_2000_COIN_Dismounted_Arctic_Platoon_Commander";
};
class TWC_Infantry_2000_COIN_Dismounted_Arctic_Platoon_Sergeant: TWC_Infantry_2000_COIN_Arctic_Platoon_Sergeant
{
	CATEGORY(TWC_Infantry_Dismounted_COIN_2000_Arctic)
	backpack = "TWC_Backpack_2000_COIN_Dismounted_Arctic_Platoon_Sergeant";
};
class TWC_Infantry_2000_COIN_Dismounted_Arctic_Platoon_Medic: TWC_Infantry_2000_COIN_Arctic_Platoon_Medic
{
	CATEGORY(TWC_Infantry_Dismounted_COIN_2000_Arctic)
	backpack = "TWC_Backpack_2000_COIN_Dismounted_Arctic_Platoon_Medic";
};
class TWC_Infantry_2000_COIN_Dismounted_Arctic_Platoon_CSM: TWC_Infantry_2000_COIN_Arctic_Platoon_CSM
{
	CATEGORY(TWC_Infantry_Dismounted_COIN_2000_Arctic)
	backpack = "TWC_Backpack_2000_COIN_Dismounted_Arctic_Platoon_Sergeant";
};

//Company
class TWC_Infantry_2000_COIN_Dismounted_Arctic_Company_Commander: TWC_Infantry_2000_COIN_Arctic_Company_Commander
{
	CATEGORY(TWC_Infantry_Dismounted_COIN_2000_Arctic)
	backpack = "TWC_Backpack_2000_COIN_Dismounted_Arctic_Platoon_Commander";
};
class TWC_Infantry_2000_COIN_Dismounted_Arctic_Company_2iC: TWC_Infantry_2000_COIN_Arctic_Company_2iC
{
	CATEGORY(TWC_Infantry_Dismounted_COIN_2000_Arctic)
	backpack = "TWC_Backpack_2000_COIN_Dismounted_Arctic_Platoon_Commander";
};
class TWC_Infantry_2000_COIN_Dismounted_Arctic_Company_Sergeant: TWC_Infantry_2000_COIN_Arctic_Company_Sergeant
{
	CATEGORY(TWC_Infantry_Dismounted_COIN_2000_Arctic)
	backpack = "TWC_Backpack_2000_COIN_Dismounted_Arctic_Platoon_Sergeant";
};