//COIN, DISMOUNTED, Desert
//Section
class TWC_Infantry_2000_COIN_Dismounted_Desert_Rifleman: TWC_Infantry_2000_COIN_Desert_Rifleman
{
	CATEGORY(TWC_Infantry_2000_COIN_Dismounted_Desert)
	backpack = "TWC_Backpack_2000_COIN_Dismounted_Desert_Rifleman";
};
class TWC_Infantry_2000_COIN_Dismounted_Desert_Marksman: TWC_Infantry_2000_COIN_Desert_Marksman
{
	CATEGORY(TWC_Infantry_2000_COIN_Dismounted_Desert)
	backpack = "TWC_Backpack_2000_COIN_Dismounted_Desert_Marksman";
};
class TWC_Infantry_2000_COIN_Dismounted_Desert_Grenadier: TWC_Infantry_2000_COIN_Desert_Grenadier
{
	CATEGORY(TWC_Infantry_2000_COIN_Dismounted_Desert)
	backpack = "TWC_Backpack_2000_COIN_Dismounted_Desert_Grenadier";
};
class TWC_Infantry_2000_COIN_Dismounted_Desert_Autorifleman: TWC_Infantry_2000_COIN_Desert_Autorifleman
{
	CATEGORY(TWC_Infantry_2000_COIN_Dismounted_Desert)
	backpack = "TWC_Backpack_2000_COIN_Dismounted_Desert_Autorifleman";
};
class TWC_Infantry_2000_COIN_Dismounted_Desert_SectionCommander: TWC_Infantry_2000_COIN_Desert_SectionCommander
{
	CATEGORY(TWC_Infantry_2000_COIN_Dismounted_Desert)
	backpack = "TWC_Backpack_2000_COIN_Dismounted_Desert_SectionCommander";
};
class TWC_Infantry_2000_COIN_Dismounted_Desert_2iC: TWC_Infantry_2000_COIN_Desert_2iC
{
	CATEGORY(TWC_Infantry_2000_COIN_Dismounted_Desert)
	backpack = "TWC_Backpack_2000_COIN_Dismounted_Desert_2iC";
};

//Platoon Command
class TWC_Infantry_2000_COIN_Dismounted_Desert_Platoon_Commander: TWC_Infantry_2000_COIN_Desert_Platoon_Commander
{
	CATEGORY(TWC_Infantry_2000_COIN_Dismounted_Desert)
	backpack = "TWC_Backpack_2000_COIN_Dismounted_Desert_Platoon_Commander";
};
class TWC_Infantry_2000_COIN_Dismounted_Desert_Platoon_Sergeant: TWC_Infantry_2000_COIN_Desert_Platoon_Sergeant
{
	CATEGORY(TWC_Infantry_2000_COIN_Dismounted_Desert)
	backpack = "TWC_Backpack_2000_COIN_Dismounted_Desert_Platoon_Sergeant";
};
class TWC_Infantry_2000_COIN_Dismounted_Desert_Platoon_Medic: TWC_Infantry_2000_COIN_Desert_Platoon_Medic
{
	CATEGORY(TWC_Infantry_2000_COIN_Dismounted_Desert)
	backpack = "TWC_Backpack_2000_COIN_Dismounted_Desert_Platoon_Medic";
};
class TWC_Infantry_2000_COIN_Dismounted_Desert_Platoon_CSM: TWC_Infantry_2000_COIN_Desert_Platoon_CSM
{
	CATEGORY(TWC_Infantry_2000_COIN_Dismounted_Desert)
	backpack = "TWC_Backpack_2000_COIN_Dismounted_Desert_Platoon_Sergeant";
};

//Company
class TWC_Infantry_2000_COIN_Dismounted_Desert_Company_Commander: TWC_Infantry_2000_COIN_Desert_Company_Commander
{
	CATEGORY(TWC_Infantry_2000_COIN_Dismounted_Desert)
	backpack = "TWC_Backpack_2000_COIN_Dismounted_Desert_Platoon_Commander";
};
class TWC_Infantry_2000_COIN_Dismounted_Desert_Company_2iC: TWC_Infantry_2000_COIN_Desert_Company_2iC
{
	CATEGORY(TWC_Infantry_2000_COIN_Dismounted_Desert)
	backpack = "TWC_Backpack_2000_COIN_Dismounted_Desert_Platoon_Commander";
};
class TWC_Infantry_2000_COIN_Dismounted_Desert_Company_Sergeant: TWC_Infantry_2000_COIN_Desert_Company_Sergeant
{
	CATEGORY(TWC_Infantry_2000_COIN_Dismounted_Desert)
	backpack = "TWC_Backpack_2000_COIN_Dismounted_Desert_Platoon_Sergeant";
};