//COIN, DISMOUNTED, Tropic
//Section
class TWC_Infantry_2000_COIN_Dismounted_Tropic_Rifleman: TWC_Infantry_2000_COIN_Tropic_Rifleman
{
	CATEGORY(TWC_Infantry_Dismounted_COIN_2000_Tropic)
	backpack = "TWC_Backpack_2000_COIN_Dismounted_Tropic_Rifleman";
};
class TWC_Infantry_2000_COIN_Dismounted_Tropic_Marksman: TWC_Infantry_2000_COIN_Tropic_Marksman
{
	CATEGORY(TWC_Infantry_Dismounted_COIN_2000_Tropic)
	backpack = "TWC_Backpack_2000_COIN_Dismounted_Tropic_Marksman";
};
class TWC_Infantry_2000_COIN_Dismounted_Tropic_Grenadier: TWC_Infantry_2000_COIN_Tropic_Grenadier
{
	CATEGORY(TWC_Infantry_Dismounted_COIN_2000_Tropic)
	backpack = "TWC_Backpack_2000_COIN_Dismounted_Tropic_Grenadier";
};
class TWC_Infantry_2000_COIN_Dismounted_Tropic_Autorifleman: TWC_Infantry_2000_COIN_Tropic_Autorifleman
{
	CATEGORY(TWC_Infantry_Dismounted_COIN_2000_Tropic)
	backpack = "TWC_Backpack_2000_COIN_Dismounted_Tropic_Autorifleman";
};
class TWC_Infantry_2000_COIN_Dismounted_Tropic_SectionCommander: TWC_Infantry_2000_COIN_Tropic_SectionCommander
{
	CATEGORY(TWC_Infantry_Dismounted_COIN_2000_Tropic)
	backpack = "TWC_Backpack_2000_COIN_Dismounted_Tropic_SectionCommander";
};
class TWC_Infantry_2000_COIN_Dismounted_Tropic_2iC: TWC_Infantry_2000_COIN_Tropic_2iC
{
	CATEGORY(TWC_Infantry_Dismounted_COIN_2000_Tropic)
	backpack = "TWC_Backpack_2000_COIN_Dismounted_Tropic_2iC";
};

//Platoon Command
class TWC_Infantry_2000_COIN_Dismounted_Tropic_Platoon_Commander: TWC_Infantry_2000_COIN_Tropic_Platoon_Commander
{
	CATEGORY(TWC_Infantry_Dismounted_COIN_2000_Tropic)
	backpack = "TWC_Backpack_2000_COIN_Dismounted_Tropic_Platoon_Commander";
};
class TWC_Infantry_2000_COIN_Dismounted_Tropic_Platoon_Sergeant: TWC_Infantry_2000_COIN_Tropic_Platoon_Sergeant
{
	CATEGORY(TWC_Infantry_Dismounted_COIN_2000_Tropic)
	backpack = "TWC_Backpack_2000_COIN_Dismounted_Tropic_Platoon_Sergeant";
};
class TWC_Infantry_2000_COIN_Dismounted_Tropic_Platoon_Medic: TWC_Infantry_2000_COIN_Tropic_Platoon_Medic
{
	CATEGORY(TWC_Infantry_Dismounted_COIN_2000_Tropic)
	backpack = "TWC_Backpack_2000_COIN_Dismounted_Tropic_Platoon_Medic";
};
class TWC_Infantry_2000_COIN_Dismounted_Tropic_Platoon_CSM: TWC_Infantry_2000_COIN_Tropic_Platoon_CSM
{
	CATEGORY(TWC_Infantry_Dismounted_COIN_2000_Tropic)
	backpack = "TWC_Backpack_2000_COIN_Dismounted_Tropic_Platoon_Sergeant";
};

//Company
class TWC_Infantry_2000_COIN_Dismounted_Tropic_Company_Commander: TWC_Infantry_2000_COIN_Tropic_Company_Commander
{
	CATEGORY(TWC_Infantry_Dismounted_COIN_2000_Tropic)
	backpack = "TWC_Backpack_2000_COIN_Dismounted_Tropic_Platoon_Commander";
};
class TWC_Infantry_2000_COIN_Dismounted_Tropic_Company_2iC: TWC_Infantry_2000_COIN_Tropic_Company_2iC
{
	CATEGORY(TWC_Infantry_Dismounted_COIN_2000_Tropic)
	backpack = "TWC_Backpack_2000_COIN_Dismounted_Tropic_Platoon_Commander";
};
class TWC_Infantry_2000_COIN_Dismounted_Tropic_Company_Sergeant: TWC_Infantry_2000_COIN_Tropic_Company_Sergeant
{
	CATEGORY(TWC_Infantry_Dismounted_COIN_2000_Tropic)
	backpack = "TWC_Backpack_2000_COIN_Dismounted_Tropic_Platoon_Sergeant";
};