class CfgPatches
{
	class twc_faction
	{
		units[]=
		{
			"1990_British_Squadleader",
			"1990_British_Rifleman",
			"1990_British_Grenadier",
			"1990_British_Gunner",
			"1990_British_2IC",
			"1990_British_Platoon_Commander",
			"1990_British_Platoon_Sergeant",
			"1990_British_Medic",
			"1990_HeloPilot",
			"1990_JetPilot",
			"1990_British_Squadleader_Desert",
			"1990_British_Rifleman_Desert",
			"1990_British_Grenadier_Desert",
			"1990_British_Gunner_Desert",
			"1990_British_2IC_Desert",
			"1990_British_Platoon_Commander_Desert",
			"1990_British_Platoon_Sergeant_Desert",
			"1990_British_Medic_Desert",
			"1990_HeloPilot_Desert",
		};
		weapons[]={};
		requiredVersion=0.1;
		requiredAddons[]=
		{
			"A3_Characters_F_BLUFOR",
			"A3_Characters_F_OPFOR"
		};
	};
};
class CfgVehicles
{
	class B_Soldier_base_F;
	class O_Soldier_base_F;
	class I_Soldier_F;
//////////////////////////////////////////////////////////////////
//                                                              //
//                           1990 British                       //
//                                                              //
//////////////////////////////////////////////////////////////////

	class 1990_British_Squadleader: B_Soldier_base_F
	{
		_generalMacro="1990_British_Squadleader";
		scope=2;
		displayName="Section Leader(90`s Woodland)";
		faction="a_units";
		vehicleClass="1990_British";
		icon="iconManLeader";
		nakedUniform="U_BasicBody";
		uniformClass="BAF_Soldier_Base_L_W_Uniform_DG1";
		backpack="TWC_Backpack_1990_Sectionlead";
		linkedItems[]=
		{
        "BAF_Soldier_Officer_Vest_W_DG1",
		"BAF_Soldier_1_Headgear_W_DG1",
		"ItemMap",
		"ItemCompass",
		"ItemWatch",
		"ACRE_PRC343",
		"UK3CB_BAF_G_Tactical_Black"
		};
		respawnLinkedItems[]=
		{
        "BAF_Soldier_Officer_Vest_W_DG1",
		"ItemMap",
		"ItemCompass",
		"ItemWatch",
		"ACRE_PRC343",
		"UK3CB_BAF_G_Tactical_Black"
		};
		weapons[]=
		{
		"Throw",
		"Put",
		"Binocular",
		"UK3CB_BAF_L85A1_SUSAT3D",
		"UK3CB_BAF_L131A1"
		};
		respawnweapons[]=
		{
		"Throw",
		"Put",
		"Binocular",
		"UK3CB_BAF_L85A1_SUSAT3D",
		"UK3CB_BAF_L131A1"
		};
		magazines[]=
		{
		"UK3CB_BAF_17Rnd_9mm",
		"UK3CB_BAF_17Rnd_9mm",
		"UK3CB_BAF_17Rnd_9mm",
		"UK3CB_BAF_30Rnd",
		"UK3CB_BAF_30Rnd",
		"UK3CB_BAF_30Rnd_T",
		"UK3CB_BAF_30Rnd_T",
		"UK3CB_BAF_30Rnd",
		"UK3CB_BAF_30Rnd",
		"CUP_HandGrenade_L109A2_HE",
		"CUP_HandGrenade_L109A2_HE"
		};
		Respawnmagazines[]=
		{
		"UK3CB_BAF_17Rnd_9mm",
		"UK3CB_BAF_17Rnd_9mm",
		"UK3CB_BAF_17Rnd_9mm",
		"UK3CB_BAF_30Rnd_T",
		"UK3CB_BAF_30Rnd",
		"UK3CB_BAF_30Rnd",
		"UK3CB_BAF_30Rnd_T",
		"UK3CB_BAF_30Rnd",
		"UK3CB_BAF_30Rnd",
		"CUP_HandGrenade_L109A2_HE",
		"CUP_HandGrenade_L109A2_HE"
		};
		Items[]=
		{
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_morphine",
		"ACE_morphine",
		"ACE_Flashlight_KSF1",
		"ACE_IR_Strobe_Item",
	    "ACE_MapTools",
		"UK3CB_BAF_HMNVS",
		"ACE_EarPlugs"	
		};
		respawntems[]=
		{
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_morphine",
		"ACE_morphine",
		"ACE_Flashlight_KSF1",
		"ACE_IR_Strobe_Item",
	    "ACE_MapTools",
		"UK3CB_BAF_HMNVS",
		"ACE_EarPlugs"			
		};
	};
	class 1990_British_Rifleman: B_Soldier_base_F
	{
		_generalMacro="1990_British_Rifleman";
		scope=2;
		displayName="RifleMan(90`s Woodland)";
		faction="a_units";
		vehicleClass="1990_British";
		icon="iconMan";
		nakedUniform="U_BasicBody";
		uniformClass="BAF_Soldier_Base_L_W_Uniform_DG1";
		backpack="TWC_Backpack_1990_Rifleman";
		linkedItems[]=
		{
        "BAF_Soldier_1_Vest_W_DG1",
		"BAF_Soldier_1_Headgear_W_DG1",
		"ItemMap",
		"ItemCompass",
		"ItemWatch",
		"ACRE_PRC343",
		"UK3CB_BAF_G_Tactical_Black"
		};
		respawnLinkedItems[]=
		{
        "BAF_Soldier_1_Vest_W_DG1",
		"ItemMap",
		"ItemCompass",
		"ItemWatch",
		"UK3CB_BAF_G_Tactical_Black",
		"ACRE_PRC343"
		};
		weapons[]=
		{
		"Throw",
		"Put",	
		"UK3CB_BAF_L85A1_SUSAT3D",
		"UK3CB_BAF_L131A1",
		"UK3CB_BAF_AT4_CS_AT_Launcher"
		};
		respawnweapons[]=
		{
		"Throw",
		"Put",	
		"UK3CB_BAF_L85A1_SUSAT3D",
		"UK3CB_BAF_L131A1",
		"UK3CB_BAF_AT4_CS_AT_Launcher"
		};
		magazines[]=
		{
		"UK3CB_BAF_17Rnd_9mm",
		"UK3CB_BAF_17Rnd_9mm",
		"UK3CB_BAF_17Rnd_9mm",
		"UK3CB_BAF_30Rnd",
		"UK3CB_BAF_30Rnd_T",
		"UK3CB_BAF_30Rnd_T",
		"CUP_HandGrenade_L109A2_HE",
		"CUP_HandGrenade_L109A2_HE",
		"SmokeShell",
		"SmokeShell",
		"SmokeShell"
		};
		Respawnmagazines[]=
		{
		"UK3CB_BAF_17Rnd_9mm",
		"UK3CB_BAF_17Rnd_9mm",
		"UK3CB_BAF_17Rnd_9mm",
		"UK3CB_BAF_30Rnd",
		"UK3CB_BAF_30Rnd_T",
		"UK3CB_BAF_30Rnd_T",
		"CUP_HandGrenade_L109A2_HE",
		"CUP_HandGrenade_L109A2_HE",
		"SmokeShell",
		"SmokeShell",
		"SmokeShell"
		};
		Items[]=
		{
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_morphine",
		"ACE_morphine",
		"ACE_EarPlugs",	
		"UK3CB_BAF_HMNVS"
		};
		respawntems[]=
		{
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_morphine",
		"ACE_morphine",
		"ACE_EarPlugs",	
		"UK3CB_BAF_HMNVS"		
		};		
	};
	class 1990_British_Grenadier: B_Soldier_base_F
	{
		_generalMacro="1990_British_Grenadier";
		scope=2;
		displayName="Grenadier(90`s Woodland)";
		faction="a_units";
		vehicleClass="1990_British";
		icon="iconManExplosive";
		nakedUniform="U_BasicBody";
		uniformClass="BAF_Soldier_Base_L_W_Uniform_DG1";
		backpack="TWC_Backpack_1990_Grenadier";
		linkedItems[]=
		{
        "BAF_Soldier_gl_Vest_W_DG1",
		"BAF_Soldier_gl_Headgear_W_DG1",
		"ItemMap",
		"ItemCompass",
		"ItemWatch",
		"ACRE_PRC343",
		"UK3CB_BAF_G_Tactical_Black"
		};
		respawnLinkedItems[]=
		{
        "BAF_Soldier_gl_Vest_W_DG1",
		"BAF_Soldier_gl_Headgear_W_DG1",
		"ItemMap",
		"ItemCompass",
		"ItemWatch",
		"ACRE_PRC343",
		"UK3CB_BAF_G_Tactical_Black"
		};
		weapons[]=
		{
		"Throw",
		"Put",
		"UK3CB_BAF_L85A2_UGL_SUSAT3D",
		"UK3CB_BAF_L131A1"
		};
		respawnweapons[]=
		{
		"Throw",
		"Put",
		"UK3CB_BAF_L85A2_UGL_SUSAT3D",
		"UK3CB_BAF_L131A1"
		};
		magazines[]=
		{
		"1Rnd_HE_Grenade_shell",
		"UK3CB_BAF_17Rnd_9mm",
		"UK3CB_BAF_17Rnd_9mm",
		"UK3CB_BAF_17Rnd_9mm",
		"UK3CB_BAF_30Rnd",
		"UK3CB_BAF_30Rnd_T",
		"UK3CB_BAF_30Rnd_T",
		"CUP_HandGrenade_L109A2_HE",
		"CUP_HandGrenade_L109A2_HE",
		"SmokeShell",
		"SmokeShell",
		"SmokeShell"
		};
		Respawnmagazines[]=
		{
		"1Rnd_HE_Grenade_shell",
		"UK3CB_BAF_17Rnd_9mm",
		"UK3CB_BAF_17Rnd_9mm",
		"UK3CB_BAF_17Rnd_9mm",		
		"UK3CB_BAF_30Rnd",
		"UK3CB_BAF_30Rnd_T",
		"UK3CB_BAF_30Rnd_T",
		"CUP_HandGrenade_L109A2_HE",
		"CUP_HandGrenade_L109A2_HE",
		"SmokeShell",
		"SmokeShell",
		"SmokeShell"
		};
		Items[]=
		{
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_morphine",
		"ACE_morphine",
		"ACE_EarPlugs",	
		"UK3CB_BAF_HMNVS"
		};
		respawntems[]=
		{
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_morphine",
		"ACE_morphine",
		"ACE_EarPlugs",	
		"UK3CB_BAF_HMNVS"			
		};
	};
	class 1990_British_Gunner: B_Soldier_base_F
	{
		_generalMacro="1990_British_Gunner";
		scope=2;
		displayName="Gunner(90`s Woodland)";
		faction="a_units";
		vehicleClass="Modern_British";
		icon="iconManMG";
		nakedUniform="U_BasicBody";
		uniformClass="BAF_Soldier_Base_L_W_Uniform_DG1";
		backpack="TWC_Backpack_1990_Gunner";
		linkedItems[]=
		{
        "BAF_Soldier_1_Vest_W_DG1",
		"BAF_Soldier_1_Headgear_W_DG1",
		"ItemMap",
		"ItemCompass",
		"ItemWatch",
		"UK3CB_BAF_G_Tactical_Black",
		"ACRE_PRC343"
		};
		respawnLinkedItems[]=
		{
        "BAF_Soldier_1_Vest_W_DG1",
		"ItemMap",
		"ItemCompass",
		"ItemWatch",
		"ACRE_PRC343",
		"UK3CB_BAF_G_Tactical_Black"
		};
		weapons[]=
		{
		"Throw",
		"Put",	
		"UK3CB_BAF_L86A1_SUSAT3D",
		"UK3CB_BAF_L131A1"
		};
		respawnweapons[]=
		{
		"Throw",
		"Put",	
		"UK3CB_BAF_L86_SUSAT3D",
		"UK3CB_BAF_L131A1"
		};
		magazines[]=
		{
		"UK3CB_BAF_17Rnd_9mm",
		"UK3CB_BAF_17Rnd_9mm",
		"UK3CB_BAF_17Rnd_9mm",
		"UK3CB_BAF_30Rnd",
		"UK3CB_BAF_30Rnd",
		"UK3CB_BAF_30Rnd",
		"CUP_HandGrenade_L109A2_HE",
		"CUP_HandGrenade_L109A2_HE",
		"SmokeShell",
		"SmokeShell",
		"SmokeShell"
		};
		Respawnmagazines[]=
		{
		"UK3CB_BAF_17Rnd_9mm",
		"UK3CB_BAF_17Rnd_9mm",
		"UK3CB_BAF_17Rnd_9mm",
		"UK3CB_BAF_30Rnd",
		"UK3CB_BAF_30Rnd",
		"UK3CB_BAF_30Rnd",
		"CUP_HandGrenade_L109A2_HE",
		"CUP_HandGrenade_L109A2_HE",
		"SmokeShell",
		"SmokeShell",
		"SmokeShell"
		};
		Items[]=
		{
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_morphine",
		"ACE_morphine",
		"ACE_EarPlugs",	
		"UK3CB_BAF_HMNVS"
		};
		respawntems[]=
		{
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_morphine",
		"ACE_morphine",
		"ACE_EarPlugs",	
		"UK3CB_BAF_HMNVS"			
		};
	};
	class 1990_British_2IC: B_Soldier_base_F
	{
		_generalMacro="1990_British_2IC";
		scope=2;
		displayName="2IC(90`s Woodland)";
		faction="a_units";
		vehicleClass="1990_British";
		icon="iconMan";
		nakedUniform="U_BasicBody";
		uniformClass="BAF_Soldier_Base_L_W_Uniform_DG1";
		backpack="TWC_Backpack_1990_2IC";
		linkedItems[]=
		{
        "BAF_Soldier_2_Vest_W_DG1",
		"BAF_Soldier_1_Headgear_W_DG1",
		"ItemMap",
		"ItemCompass",
		"ItemWatch",
		"ACRE_PRC343",
		"UK3CB_BAF_G_Tactical_Black"
		};
		respawnLinkedItems[]=
		{
        "BAF_Soldier_2_Vest_W_DG1",
		"ItemMap",
		"ItemCompass",
		"ItemWatch",
		"ACRE_PRC343",
		"UK3CB_BAF_G_Tactical_Black"
		};
		weapons[]=
		{
		"Throw",
		"Put",
		"Binocular",
		"UK3CB_BAF_L85A1_SUSAT3D",
		"UK3CB_BAF_L131A1"
		};
		respawnweapons[]=
		{
		"Throw",
		"Put",
		"Binocular",
		"UK3CB_BAF_L85A1_SUSAT3D",
		"UK3CB_BAF_L131A1"
		};
		magazines[]=
		{
		"UK3CB_BAF_17Rnd_9mm",
		"UK3CB_BAF_17Rnd_9mm",
		"UK3CB_BAF_17Rnd_9mm",
		"UK3CB_BAF_30Rnd",
		"UK3CB_BAF_30Rnd",
		"UK3CB_BAF_30Rnd",
		"UK3CB_BAF_30Rnd_T",
		"UK3CB_BAF_30Rnd_T",
		"CUP_HandGrenade_L109A2_HE",
		"CUP_HandGrenade_L109A2_HE",
		"SmokeShell",
		"SmokeShell",
		"SmokeShell"
		};
		Respawnmagazines[]=
		{
		"UK3CB_BAF_17Rnd_9mm",
		"UK3CB_BAF_17Rnd_9mm",
		"UK3CB_BAF_17Rnd_9mm",
		"UK3CB_BAF_30Rnd",
		"UK3CB_BAF_30Rnd",
		"UK3CB_BAF_30Rnd",
		"UK3CB_BAF_30Rnd_T",
		"UK3CB_BAF_30Rnd_T",
		"CUP_HandGrenade_L109A2_HE",
		"CUP_HandGrenade_L109A2_HE",
		"SmokeShell",
		"SmokeShell",
		"SmokeShell"
		};
		Items[]=
		{
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_morphine",
		"ACE_morphine",
		"ACE_EarPlugs",	
		"UK3CB_BAF_HMNVS"
		};
		respawntems[]=
		{
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_morphine",
		"ACE_morphine",
		"ACE_EarPlugs",	
		"UK3CB_BAF_HMNVS"		
		};
	};
	class 1990_British_Platoon_Commander: B_Soldier_base_F
	{
		_generalMacro="1990_British_Squadleader";
		scope=2;
		displayName="Platoon Commander(90`s Woodland)";
		faction="a_units";
		vehicleClass="1990_British";
		icon="iconManLeader";
		nakedUniform="U_BasicBody";
		uniformClass="BAF_Soldier_Base_L_W_Uniform_DG1";
		backpack="TWC_Backpack_1990_Platoon_Command";
		linkedItems[]=
		{
        "BAF_Soldier_Light_Vest_W_DG1",
		"BAF_Soldier_1_Headgear_W_DG1",
		"ItemMap",
		"ItemCompass",
		"ItemWatch",
		"ACRE_PRC343",
		"UK3CB_BAF_G_Tactical_Black"
		};
		respawnLinkedItems[]=
		{
        "BAF_Soldier_Light_Vest_W_DG1",
		"ItemMap",
		"ItemCompass",
		"ItemWatch",
		"ACRE_PRC343",
		"UK3CB_BAF_G_Tactical_Black"
		};
		weapons[]=
		{
		"Throw",
		"Put",
		"Binocular",
		"UK3CB_BAF_L85A1_SUSAT3D",
		"UK3CB_BAF_L131A1"
		};
		respawnweapons[]=
		{
		"Throw",
		"Put",
		"Binocular",
		"UK3CB_BAF_L85A1_SUSAT3D",
		"UK3CB_BAF_L131A1"
		};
		magazines[]=
		{
		"UK3CB_BAF_17Rnd_9mm",
		"UK3CB_BAF_17Rnd_9mm",
		"UK3CB_BAF_17Rnd_9mm",
		"UK3CB_BAF_30Rnd",
		"UK3CB_BAF_30Rnd",
		"UK3CB_BAF_30Rnd",
		"UK3CB_BAF_30Rnd",
		"UK3CB_BAF_30Rnd_T",
		"UK3CB_BAF_30Rnd_T",
		"CUP_HandGrenade_L109A2_HE",
		"CUP_HandGrenade_L109A2_HE"
		};
		Respawnmagazines[]=
		{
		"UK3CB_BAF_17Rnd_9mm",
		"UK3CB_BAF_17Rnd_9mm",
		"UK3CB_BAF_17Rnd_9mm",
		"UK3CB_BAF_30Rnd",
		"UK3CB_BAF_30Rnd",
		"UK3CB_BAF_30Rnd",
		"UK3CB_BAF_30Rnd",
		"UK3CB_BAF_30Rnd_T",
		"UK3CB_BAF_30Rnd_T",
		"CUP_HandGrenade_L109A2_HE",
		"CUP_HandGrenade_L109A2_HE"
		};
		Items[]=
		{
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_morphine",
		"ACE_morphine",
		"ACE_Flashlight_KSF1",
		"ACE_IR_Strobe_Item",
	    "ACE_MapTools",
		"UK3CB_BAF_HMNVS",
		"ACE_EarPlugs"	

		};
		respawntems[]=
		{
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_morphine",
		"ACE_morphine",
		"ACE_Flashlight_KSF1",
		"ACE_IR_Strobe_Item",
	    "ACE_MapTools",
		"UK3CB_BAF_HMNVS",
		"ACE_EarPlugs"
		};
	};
	class 1990_British_Platoon_Sergeant: B_Soldier_base_F
	{
		_generalMacro="1990_British_Squadleader";
		scope=2;
		displayName="Platoon Sergeant(90`s Woodland)";
		faction="a_units";
		vehicleClass="1990_British";
		icon="iconManLeader";
		nakedUniform="U_BasicBody";
		uniformClass="BAF_Soldier_Base_L_W_Uniform_DG1";
		backpack="TWC_Backpack_1990_Platoon_Sergeant";
		linkedItems[]=
		{
        "BAF_Soldier_Light_Vest_W_DG1",
		"BAF_Soldier_1_Headgear_W_DG1",
		"ItemMap",
		"ItemCompass",
		"ItemWatch",
		"ACRE_PRC343",
		"UK3CB_BAF_G_Tactical_Black"
		};
		respawnLinkedItems[]=
		{
        "BAF_Soldier_Light_Vest_W_DG1",
		"ItemMap",
		"ItemCompass",
		"ItemWatch",
		"ACRE_PRC343",
		"UK3CB_BAF_G_Tactical_Black"
		};
		weapons[]=
		{
		"Throw",
		"Put",
		"Binocular",
		"UK3CB_BAF_L85A1_SUSAT3D",
		"UK3CB_BAF_L131A1"
		};
		respawnweapons[]=
		{
		"Throw",
		"Put",
		"Binocular",
		"UK3CB_BAF_L85A1_SUSAT3D",
		"UK3CB_BAF_L131A1"
		};
		magazines[]=
		{
		"UK3CB_BAF_17Rnd_9mm",
		"UK3CB_BAF_17Rnd_9mm",
		"UK3CB_BAF_17Rnd_9mm",
		"UK3CB_BAF_30Rnd",
		"UK3CB_BAF_30Rnd",
		"UK3CB_BAF_30Rnd",
		"UK3CB_BAF_30Rnd",
		"UK3CB_BAF_30Rnd_T",
		"UK3CB_BAF_30Rnd_T",
		"CUP_HandGrenade_L109A2_HE",
		"CUP_HandGrenade_L109A2_HE"
		};
		Respawnmagazines[]=
		{
		"UK3CB_BAF_17Rnd_9mm",
		"UK3CB_BAF_17Rnd_9mm",
		"UK3CB_BAF_17Rnd_9mm",
		"UK3CB_BAF_30Rnd",
		"UK3CB_BAF_30Rnd",
		"UK3CB_BAF_30Rnd",
		"UK3CB_BAF_30Rnd",
		"UK3CB_BAF_30Rnd_T",
		"UK3CB_BAF_30Rnd_T",
		"CUP_HandGrenade_L109A2_HE",
		"CUP_HandGrenade_L109A2_HE"
		};
		Items[]=
		{
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_morphine",
		"ACE_morphine",
		"ACE_Flashlight_KSF1",
		"ACE_IR_Strobe_Item",
	    "ACE_MapTools",
		"UK3CB_BAF_HMNVS",
		"ACE_EarPlugs"	

		};
		respawntems[]=
		{
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_morphine",
		"ACE_morphine",
		"ACE_Flashlight_KSF1",
		"ACE_IR_Strobe_Item",
	    "ACE_MapTools",
		"UK3CB_BAF_HMNVS",
		"ACE_EarPlugs"
		};
	};
	class 1990_British_Medic: B_Soldier_base_F
	{
		_generalMacro="1990_British_Marksman";
		scope=2;
		displayName="Medic(90`s Woodland)";
		faction="a_units";
		vehicleClass="1990_British";
		icon="iconMan";
		nakedUniform="U_BasicBody";
		uniformClass="BAF_Soldier_Base_L_W_Uniform_DG1";
		backpack="TWC_Backpack_1990_Medic";
		linkedItems[]=
		{
        "BAF_Soldier_Light_Vest_W_DG1",
		"BAF_Soldier_1_Headgear_W_DG1",
		"ItemMap",
		"ItemCompass",
		"ItemWatch",
		"UK3CB_BAF_G_Tactical_Black",
		"ACRE_PRC343"
		};
		respawnLinkedItems[]=
		{
        "BAF_Soldier_Light_Vest_W_DG1",
		"ItemMap",
		"ItemCompass",
		"ItemWatch",
		"ACRE_PRC343",
		"UK3CB_BAF_G_Tactical_Black"
		};
		weapons[]=
		{
		"Throw",
		"Put",	
		"UK3CB_BAF_L131A1"
		};
		respawnweapons[]=
		{
		"Throw",
		"Put",
		"UK3CB_BAF_L131A1"
		};
		magazines[]=
		{
		"UK3CB_BAF_17Rnd_9mm",
		"UK3CB_BAF_17Rnd_9mm",
		"UK3CB_BAF_17Rnd_9mm",
		"SmokeShell",
		"SmokeShell",
		"SmokeShell",
		"SmokeShell",
		"SmokeShell"
		};
		Respawnmagazines[]=
		{
		"UK3CB_BAF_17Rnd_9mm",
		"UK3CB_BAF_17Rnd_9mm",
		"UK3CB_BAF_17Rnd_9mm",
		"SmokeShell",
		"SmokeShell",
		"SmokeShell",
		"SmokeShell",
		"SmokeShell"
		};
		Items[]=
		{
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_morphine",
		"ACE_morphine",
		"ACE_EarPlugs",	
		"UK3CB_BAF_HMNVS"
		};
		respawntems[]=
		{
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_morphine",
		"ACE_morphine",
		"ACE_EarPlugs",	
		"UK3CB_BAF_HMNVS"			
		};		
	};
	class 1990_HeloPilot: B_Soldier_base_F
	{
		_generalMacro="1990_HelicopterPilot";
		scope=2;
		displayName="Helicopter Pilot(90`s Woodland)";
		faction="a_units";
		vehicleClass="1990_British";
		icon="iconMan";
		nakedUniform="U_BasicBody";
		uniformClass="BAF_Soldier_Base_L_W_Uniform_DG1";
		backpack="TWC_Backpack_Cold_War_Pilot";
		linkedItems[]=
		{
		"UK3CB_BAF_H_PilotHelmetHeli_A",
		"ItemMap",
		"ItemCompass",
		"ItemWatch"
		};
		respawnLinkedItems[]=
		{
		"UK3CB_BAF_H_PilotHelmetHeli_A",
		"ItemMap",		
		"ItemCompass",
		"ItemWatch"
		};
		weapons[]=
		{
		"Throw",
		"Put",
		"UK3CB_BAF_L22A2_SUSAT3D",
		"UK3CB_BAF_L131A1"
		};
		respawnweapons[]=
		{
		"Throw",
		"Put",
		"UK3CB_BAF_L22A2_SUSAT3D",
		"UK3CB_BAF_L131A1"
		};
		magazines[]=
		{
		"UK3CB_BAF_17Rnd_9mm",
		"UK3CB_BAF_17Rnd_9mm",
		"UK3CB_BAF_30Rnd",
		"UK3CB_BAF_30Rnd",
		"SmokeShell",
		"SmokeShell"
		};
		Respawnmagazines[]=
		{
		"UK3CB_BAF_17Rnd_9mm",
		"UK3CB_BAF_17Rnd_9mm",
		"UK3CB_BAF_30Rnd",
		"UK3CB_BAF_30Rnd",
		"SmokeShell",
		"SmokeShell"
		};
		Items[]=
		{
		"ACE_EarPlugs",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_morphine",
		"ACE_morphine"
		};
		respawntems[]=
		{
		"ACE_EarPlugs",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_morphine",
		"ACE_morphine"
		};		
	};
	class 1990_JetPilot: B_Soldier_base_F
	{
		_generalMacro="1990_JetPilot";
		scope=2;
		displayName="Jet Pilot(90`s Woodland)";
		faction="a_units";
		vehicleClass="1990_British";
		icon="iconMan";
		nakedUniform="U_BasicBody";
		uniformClass="UK3CB_BAF_U_HeliPilotCoveralls_RAF";
		backpack="TWC_Backpack_Cold_War_Pilot";
		linkedItems[]=
		{
		"RHS_jetpilot_usaf",
		"ItemMap",
		"ItemCompass",
		"ItemWatch"
		};
		respawnLinkedItems[]=
		{
		"RHS_jetpilot_usaf",
		"ItemMap",		
		"ItemCompass",
		"ItemWatch"
		};
		weapons[]=
		{
		"Throw",
		"Put",
		"UK3CB_BAF_L131A1"
		};
		respawnweapons[]=
		{
		"Throw",
		"Put",
		"UK3CB_BAF_L131A1"
		};
		magazines[]=
		{
		"UK3CB_BAF_17Rnd_9mm",
		"UK3CB_BAF_17Rnd_9mm",
		"SmokeShell",
		"SmokeShell"
		};
		Respawnmagazines[]=
		{
		"UK3CB_BAF_17Rnd_9mm",
		"UK3CB_BAF_17Rnd_9mm",	
		"SmokeShell",
		"SmokeShell"
		};
		Items[]=
		{
		"ACE_EarPlugs",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_morphine",
		"ACE_morphine",
		"ACE_morphine",
		"ACE_morphine"
		};
		respawntems[]=
		{
		"ACE_EarPlugs",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_morphine",
		"ACE_morphine",
		"ACE_morphine",
		"ACE_morphine"
		};		
	};
//////////////////////////////////////////////////////////////////
//                                                              //
//                    1990 Desert British                       //
//                                                              //
//////////////////////////////////////////////////////////////////

	class 1990_British_Squadleader_Desert: B_Soldier_base_F
	{
		_generalMacro="1990_British_Desert_Squadleader";
		scope=2;
		displayName="Section Leader(90`s Desert)";
		faction="a_units";
		vehicleClass="1990_Desert_British";
		icon="iconManLeader";
		nakedUniform="U_BasicBody";
		uniformClass="BAF_Soldier_Base_R_D_Uniform_DG1";
		backpack="TWC_Backpack_1990_Sectionlead";
		linkedItems[]=
		{
        "BAF_Soldier_Officer_Vest_D_DG1",
		"BAF_Soldier_1_Headgear_D_DG1",
		"ItemMap",
		"ItemCompass",
		"ItemWatch",
		"ACRE_PRC343",
		"UK3CB_BAF_G_Tactical_Black"
		};
		respawnLinkedItems[]=
		{
        "BAF_Soldier_Officer_Vest_D_DG1",
		"ItemMap",
		"ItemCompass",
		"ItemWatch",
		"ACRE_PRC343",
		"UK3CB_BAF_G_Tactical_Black"
		};
		weapons[]=
		{
		"Throw",
		"Put",
		"Binocular",
		"UK3CB_BAF_L85A1_SUSAT3D",
		"UK3CB_BAF_L131A1"
		};
		respawnweapons[]=
		{
		"Throw",
		"Put",
		"Binocular",
		"UK3CB_BAF_L85A1_SUSAT3D",
		"UK3CB_BAF_L131A1"
		};
		magazines[]=
		{
		"UK3CB_BAF_17Rnd_9mm",
		"UK3CB_BAF_17Rnd_9mm",
		"UK3CB_BAF_17Rnd_9mm",
		"UK3CB_BAF_30Rnd",
		"UK3CB_BAF_30Rnd",
		"UK3CB_BAF_30Rnd_T",
		"UK3CB_BAF_30Rnd_T",
		"UK3CB_BAF_30Rnd",
		"UK3CB_BAF_30Rnd",
		"CUP_HandGrenade_L109A2_HE",
		"CUP_HandGrenade_L109A2_HE"
		};
		Respawnmagazines[]=
		{
		"UK3CB_BAF_17Rnd_9mm",
		"UK3CB_BAF_17Rnd_9mm",
		"UK3CB_BAF_17Rnd_9mm",
		"UK3CB_BAF_30Rnd",
		"UK3CB_BAF_30Rnd",
		"UK3CB_BAF_30Rnd_T",
		"UK3CB_BAF_30Rnd_T",
		"UK3CB_BAF_30Rnd",
		"UK3CB_BAF_30Rnd",
		"CUP_HandGrenade_L109A2_HE",
		"CUP_HandGrenade_L109A2_HE"
		};
		Items[]=
		{
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_morphine",
		"ACE_morphine",
		"ACE_Flashlight_KSF1",
		"ACE_IR_Strobe_Item",
	    "ACE_MapTools",
		"UK3CB_BAF_HMNVS",
		"ACE_EarPlugs"	
		};
		respawntems[]=
		{
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_morphine",
		"ACE_morphine",
		"ACE_Flashlight_KSF1",
		"ACE_IR_Strobe_Item",
	    "ACE_MapTools",
		"UK3CB_BAF_HMNVS",
		"ACE_EarPlugs"			
		};
	};
	class 1990_British_Rifleman_Desert: B_Soldier_base_F
	{
		_generalMacro="1990_Desert_British_Rifleman";
		scope=2;
		displayName="RifleMan(90`s Desert)";
		faction="a_units";
		vehicleClass="1990_Desert_British";
		icon="iconMan";
		nakedUniform="U_BasicBody";
		uniformClass="BAF_Soldier_Base_R_D_Uniform_DG1";
		backpack="TWC_Backpack_1990_Rifleman";
		linkedItems[]=
		{
        "BAF_Soldier_1_Vest_D_DG1",
		"BAF_Soldier_1_Headgear_D_DG1",
		"ItemMap",
		"ItemCompass",
		"ItemWatch",
		"ACRE_PRC343",
		"UK3CB_BAF_G_Tactical_Black"
		};
		respawnLinkedItems[]=
		{
        "BAF_Soldier_1_Vest_D_DG1",
		"ItemMap",
		"ItemCompass",
		"ItemWatch",
		"UK3CB_BAF_G_Tactical_Black",
		"ACRE_PRC343"
		};
		weapons[]=
		{
		"Throw",
		"Put",	
		"UK3CB_BAF_L85A1_SUSAT3D",
		"UK3CB_BAF_L131A1",
		"UK3CB_BAF_AT4_CS_AT_Launcher"
		};
		respawnweapons[]=
		{
		"Throw",
		"Put",	
		"UK3CB_BAF_L85A1_SUSAT3D",
		"UK3CB_BAF_L131A1",
		"UK3CB_BAF_AT4_CS_AT_Launcher"
		};
		magazines[]=
		{
		"UK3CB_BAF_17Rnd_9mm",
		"UK3CB_BAF_17Rnd_9mm",
		"UK3CB_BAF_17Rnd_9mm",
		"UK3CB_BAF_30Rnd",
		"UK3CB_BAF_30Rnd_T",
		"UK3CB_BAF_30Rnd_T",
		"CUP_HandGrenade_L109A2_HE",
		"CUP_HandGrenade_L109A2_HE",
		"SmokeShell",
		"SmokeShell",
		"SmokeShell"
		};
		Respawnmagazines[]=
		{
		"UK3CB_BAF_17Rnd_9mm",
		"UK3CB_BAF_17Rnd_9mm",
		"UK3CB_BAF_17Rnd_9mm",
		"UK3CB_BAF_30Rnd",
		"UK3CB_BAF_30Rnd_T",
		"UK3CB_BAF_30Rnd_T",
		"CUP_HandGrenade_L109A2_HE",
		"CUP_HandGrenade_L109A2_HE",
		"SmokeShell",
		"SmokeShell",
		"SmokeShell"
		};
		Items[]=
		{
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_morphine",
		"ACE_morphine",
		"ACE_EarPlugs",	
		"UK3CB_BAF_HMNVS"
		};
		respawntems[]=
		{
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_morphine",
		"ACE_morphine",
		"ACE_EarPlugs",	
		"UK3CB_BAF_HMNVS"		
		};		
	};
	class 1990_British_Grenadier_Desert: B_Soldier_base_F
	{
		_generalMacro="1990_Desert_British_Grenadier";
		scope=2;
		displayName="Grenadier(90`s Desert)";
		faction="a_units";
		vehicleClass="1990_Desert_British";
		icon="iconManExplosive";
		nakedUniform="U_BasicBody";
		uniformClass="BAF_Soldier_Base_R_D_Uniform_DG1";
		backpack="TWC_Backpack_1990_Grenadier";
		linkedItems[]=
		{
        "BAF_Soldier_gl_Vest_D_DG1",
		"BAF_Soldier_gl_Headgear_D_DG1",
		"ItemMap",
		"ItemCompass",
		"ItemWatch",
		"ACRE_PRC343",
		"UK3CB_BAF_G_Tactical_Black"
		};
		respawnLinkedItems[]=
		{
        "BAF_Soldier_gl_Vest_D_DG1",
		"BAF_Soldier_gl_Headgear_D_DG1",
		"ItemMap",
		"ItemCompass",
		"ItemWatch",
		"ACRE_PRC343",
		"UK3CB_BAF_G_Tactical_Black"
		};
		weapons[]=
		{
		"Throw",
		"Put",
		"UK3CB_BAF_L85A2_UGL_SUSAT3D",
		"UK3CB_BAF_L131A1"
		};
		respawnweapons[]=
		{
		"Throw",
		"Put",
		"UK3CB_BAF_L85A2_UGL_SUSAT3D",
		"UK3CB_BAF_L131A1"
		};
		magazines[]=
		{
		"1Rnd_HE_Grenade_shell",
		"UK3CB_BAF_17Rnd_9mm",
		"UK3CB_BAF_17Rnd_9mm",
		"UK3CB_BAF_17Rnd_9mm",
		"UK3CB_BAF_30Rnd",
		"UK3CB_BAF_30Rnd_T",
		"UK3CB_BAF_30Rnd_T",
		"CUP_HandGrenade_L109A2_HE",
		"CUP_HandGrenade_L109A2_HE",
		"SmokeShell",
		"SmokeShell",
		"SmokeShell"
		};
		Respawnmagazines[]=
		{
		"1Rnd_HE_Grenade_shell",
		"UK3CB_BAF_17Rnd_9mm",
		"UK3CB_BAF_17Rnd_9mm",
		"UK3CB_BAF_17Rnd_9mm",	
		"UK3CB_BAF_30Rnd",
		"UK3CB_BAF_30Rnd_T",
		"UK3CB_BAF_30Rnd_T",
		"CUP_HandGrenade_L109A2_HE",
		"CUP_HandGrenade_L109A2_HE",
		"SmokeShell",
		"SmokeShell",
		"SmokeShell"
		};
		Items[]=
		{
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_morphine",
		"ACE_morphine",
		"ACE_EarPlugs",	
		"UK3CB_BAF_HMNVS"
		};
		respawntems[]=
		{
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_morphine",
		"ACE_morphine",
		"ACE_EarPlugs",	
		"UK3CB_BAF_HMNVS"			
		};
	};
	class 1990_British_Gunner_Desert: B_Soldier_base_F
	{
		_generalMacro="1990_Desert_British_Gunner";
		scope=2;
		displayName="Gunner(90`s Desert)";
		faction="a_units";
		vehicleClass="1990_Desert_British";
		icon="iconManMG";
		nakedUniform="U_BasicBody";
		uniformClass="BAF_Soldier_Base_R_D_Uniform_DG1";
		backpack="TWC_Backpack_1990_Gunner";
		linkedItems[]=
		{
        "BAF_Soldier_1_Vest_D_DG1",
		"BAF_Soldier_1_Headgear_D_DG1",
		"ItemMap",
		"ItemCompass",
		"ItemWatch",
		"UK3CB_BAF_G_Tactical_Black",
		"ACRE_PRC343"
		};
		respawnLinkedItems[]=
		{
        "BAF_Soldier_1_Vest_D_DG1",
		"ItemMap",
		"ItemCompass",
		"ItemWatch",
		"ACRE_PRC343",
		"UK3CB_BAF_G_Tactical_Black"
		};
		weapons[]=
		{
		"Throw",
		"Put",	
		"UK3CB_BAF_L86A1_SUSAT3D",
		"UK3CB_BAF_L131A1"
		};
		respawnweapons[]=
		{
		"Throw",
		"Put",	
		"UK3CB_BAF_L86_SUSAT3D",
		"UK3CB_BAF_L131A1"
		};
		magazines[]=
		{
		"UK3CB_BAF_17Rnd_9mm",
		"UK3CB_BAF_17Rnd_9mm",
		"UK3CB_BAF_17Rnd_9mm",
		"UK3CB_BAF_30Rnd",
		"UK3CB_BAF_30Rnd",
		"UK3CB_BAF_30Rnd",
		"CUP_HandGrenade_L109A2_HE",
		"CUP_HandGrenade_L109A2_HE",
		"SmokeShell",
		"SmokeShell",
		"SmokeShell"
		};
		Respawnmagazines[]=
		{
		"UK3CB_BAF_17Rnd_9mm",
		"UK3CB_BAF_17Rnd_9mm",
		"UK3CB_BAF_17Rnd_9mm",
		"UK3CB_BAF_30Rnd",
		"UK3CB_BAF_30Rnd",
		"UK3CB_BAF_30Rnd",
		"CUP_HandGrenade_L109A2_HE",
		"CUP_HandGrenade_L109A2_HE",
		"SmokeShell",
		"SmokeShell",
		"SmokeShell"
		};
		Items[]=
		{
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_morphine",
		"ACE_morphine",
		"ACE_EarPlugs",	
		"UK3CB_BAF_HMNVS"
		};
		respawntems[]=
		{
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_morphine",
		"ACE_morphine",
		"ACE_EarPlugs",	
		"UK3CB_BAF_HMNVS"			
		};
	};
	class 1990_British_2IC_Desert: B_Soldier_base_F
	{
		_generalMacro="1990_Desert_British_2IC";
		scope=2;
		displayName="2IC(90`s Desert)";
		faction="a_units";
		vehicleClass="1990_Desert_British";
		icon="iconMan";
		nakedUniform="U_BasicBody";
		uniformClass="BAF_Soldier_Base_R_D_Uniform_DG1";
		backpack="TWC_Backpack_1990_2IC";
		linkedItems[]=
		{
        "BAF_Soldier_2_Vest_D_DG1",
		"BAF_Soldier_1_Headgear_D_DG1",
		"ItemMap",
		"ItemCompass",
		"ItemWatch",
		"ACRE_PRC343",
		"UK3CB_BAF_G_Tactical_Black"
		};
		respawnLinkedItems[]=
		{
        "BAF_Soldier_2_Vest_D_DG1",
		"ItemMap",
		"ItemCompass",
		"ItemWatch",
		"ACRE_PRC343",
		"UK3CB_BAF_G_Tactical_Black"
		};
		weapons[]=
		{
		"Throw",
		"Put",
		"Binocular",
		"UK3CB_BAF_L85A1_SUSAT3D",
		"UK3CB_BAF_L131A1"
		};
		respawnweapons[]=
		{
		"Throw",
		"Put",
		"Binocular",
		"UK3CB_BAF_L85A1_SUSAT3D",
		"UK3CB_BAF_L131A1"
		};
		magazines[]=
		{
		"UK3CB_BAF_17Rnd_9mm",
		"UK3CB_BAF_17Rnd_9mm",
		"UK3CB_BAF_17Rnd_9mm",
		"UK3CB_BAF_30Rnd",
		"UK3CB_BAF_30Rnd",		
		"UK3CB_BAF_30Rnd",
		"UK3CB_BAF_30Rnd_T",
		"UK3CB_BAF_30Rnd_T",
		"CUP_HandGrenade_L109A2_HE",
		"CUP_HandGrenade_L109A2_HE",
		"SmokeShell",
		"SmokeShell",
		"SmokeShell"
		};
		Respawnmagazines[]=
		{
		"UK3CB_BAF_17Rnd_9mm",
		"UK3CB_BAF_17Rnd_9mm",
		"UK3CB_BAF_17Rnd_9mm",
		"UK3CB_BAF_30Rnd",
		"UK3CB_BAF_30Rnd",		
		"UK3CB_BAF_30Rnd",
		"UK3CB_BAF_30Rnd_T",
		"UK3CB_BAF_30Rnd_T",
		"CUP_HandGrenade_L109A2_HE",
		"CUP_HandGrenade_L109A2_HE",
		"SmokeShell",
		"SmokeShell",
		"SmokeShell"
		};
		Items[]=
		{
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_morphine",
		"ACE_morphine",
		"ACE_EarPlugs",	
		"UK3CB_BAF_HMNVS"
		};
		respawntems[]=
		{
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_morphine",
		"ACE_morphine",
		"ACE_EarPlugs",	
		"UK3CB_BAF_HMNVS"		
		};
	};
	class 1990_British_Platoon_Commander_Desert: B_Soldier_base_F
	{
		_generalMacro="1990_Desert_British_Squadleader";
		scope=2;
		displayName="Platoon Commander(90`s Desert)";
		faction="a_units";
		vehicleClass="1990_Desert_British";
		icon="iconManLeader";
		nakedUniform="U_BasicBody";
		uniformClass="BAF_Soldier_Base_R_D_Uniform_DG1";
		backpack="TWC_Backpack_1990_Platoon_Command";
		linkedItems[]=
		{
        "BAF_Soldier_Light_Vest_D_DG1",
		"BAF_Soldier_1_Headgear_D_DG1",
		"ItemMap",
		"ItemCompass",
		"ItemWatch",
		"ACRE_PRC343",
		"UK3CB_BAF_G_Tactical_Black"
		};
		respawnLinkedItems[]=
		{
        "BAF_Soldier_Light_Vest_D_DG1",
		"ItemMap",
		"ItemCompass",
		"ItemWatch",
		"ACRE_PRC343",
		"UK3CB_BAF_G_Tactical_Black"
		};
		weapons[]=
		{
		"Throw",
		"Put",
		"Binocular",
		"UK3CB_BAF_L85A1_SUSAT3D",
		"UK3CB_BAF_L131A1"
		};
		respawnweapons[]=
		{
		"Throw",
		"Put",
		"Binocular",
		"UK3CB_BAF_L85A1_SUSAT3D",
		"UK3CB_BAF_L131A1"
		};
		magazines[]=
		{
		"UK3CB_BAF_17Rnd_9mm",
		"UK3CB_BAF_17Rnd_9mm",
		"UK3CB_BAF_17Rnd_9mm",
		"UK3CB_BAF_30Rnd",
		"UK3CB_BAF_30Rnd",
		"UK3CB_BAF_30Rnd",
		"UK3CB_BAF_30Rnd",
		"UK3CB_BAF_30Rnd_T",
		"UK3CB_BAF_30Rnd_T",
		"CUP_HandGrenade_L109A2_HE",
		"CUP_HandGrenade_L109A2_HE"
		};
		Respawnmagazines[]=
		{
		"UK3CB_BAF_17Rnd_9mm",
		"UK3CB_BAF_17Rnd_9mm",
		"UK3CB_BAF_17Rnd_9mm",
		"UK3CB_BAF_30Rnd",
		"UK3CB_BAF_30Rnd",
		"UK3CB_BAF_30Rnd",
		"UK3CB_BAF_30Rnd",
		"UK3CB_BAF_30Rnd_T",
		"UK3CB_BAF_30Rnd_T",
		"CUP_HandGrenade_L109A2_HE",
		"CUP_HandGrenade_L109A2_HE"
		};
		Items[]=
		{
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_morphine",
		"ACE_morphine",
		"ACE_Flashlight_KSF1",
		"ACE_IR_Strobe_Item",
	    "ACE_MapTools",
		"UK3CB_BAF_HMNVS",
		"ACE_EarPlugs"	

		};
		respawntems[]=
		{
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_morphine",
		"ACE_morphine",
		"ACE_Flashlight_KSF1",
		"ACE_IR_Strobe_Item",
	    "ACE_MapTools",
		"UK3CB_BAF_HMNVS",
		"ACE_EarPlugs"
		};
	};
	class 1990_British_Platoon_Sergeant_Desert: B_Soldier_base_F
	{
		_generalMacro="1990_Desert_British_Squadleader";
		scope=2;
		displayName="Platoon Sergeant(90`s Desert)";
		faction="a_units";
		vehicleClass="1990_Desert_British";
		icon="iconManLeader";
		nakedUniform="U_BasicBody";
		uniformClass="BAF_Soldier_Base_R_D_Uniform_DG1";
		backpack="TWC_Backpack_1990_Platoon_Sergeant";
		linkedItems[]=
		{
        "BAF_Soldier_Light_Vest_D_DG1",
		"BAF_Soldier_1_Headgear_D_DG1",
		"ItemMap",
		"ItemCompass",
		"ItemWatch",
		"ACRE_PRC343",
		"UK3CB_BAF_G_Tactical_Black"
		};
		respawnLinkedItems[]=
		{
        "BAF_Soldier_Light_Vest_D_DG1",
		"ItemMap",
		"ItemCompass",
		"ItemWatch",
		"ACRE_PRC343",
		"UK3CB_BAF_G_Tactical_Black"
		};
		weapons[]=
		{
		"Throw",
		"Put",
		"Binocular",
		"UK3CB_BAF_L85A1_SUSAT3D",
		"UK3CB_BAF_L131A1"
		};
		respawnweapons[]=
		{
		"Throw",
		"Put",
		"Binocular",
		"UK3CB_BAF_L85A1_SUSAT3D",
		"UK3CB_BAF_L131A1"
		};
		magazines[]=
		{
		"UK3CB_BAF_17Rnd_9mm",
		"UK3CB_BAF_17Rnd_9mm",
		"UK3CB_BAF_17Rnd_9mm",
		"UK3CB_BAF_30Rnd",
		"UK3CB_BAF_30Rnd",
		"UK3CB_BAF_30Rnd",
		"UK3CB_BAF_30Rnd",
		"UK3CB_BAF_30Rnd_T",
		"UK3CB_BAF_30Rnd_T",
		"CUP_HandGrenade_L109A2_HE",
		"CUP_HandGrenade_L109A2_HE"
		};
		Respawnmagazines[]=
		{
		"UK3CB_BAF_17Rnd_9mm",
		"UK3CB_BAF_17Rnd_9mm",
		"UK3CB_BAF_17Rnd_9mm",
		"UK3CB_BAF_30Rnd",
		"UK3CB_BAF_30Rnd",
		"UK3CB_BAF_30Rnd",
		"UK3CB_BAF_30Rnd_T",
		"UK3CB_BAF_30Rnd_T",
		"CUP_HandGrenade_L109A2_HE",
		"CUP_HandGrenade_L109A2_HE"
		};
		Items[]=
		{
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_morphine",
		"ACE_morphine",
		"ACE_Flashlight_KSF1",
		"ACE_IR_Strobe_Item",
	    "ACE_MapTools",
		"UK3CB_BAF_HMNVS",
		"ACE_EarPlugs"	

		};
		respawntems[]=
		{
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_morphine",
		"ACE_morphine",
		"ACE_Flashlight_KSF1",
		"ACE_IR_Strobe_Item",
	    "ACE_MapTools",
		"UK3CB_BAF_HMNVS",
		"ACE_EarPlugs"
		};
	};
	class 1990_British_Medic_Desert: B_Soldier_base_F
	{
		_generalMacro="1990_Desert_British_Marksman";
		scope=2;
		displayName="Medic(90`s Desert)";
		faction="a_units";
		vehicleClass="1990_Desert_British";
		icon="iconMan";
		nakedUniform="U_BasicBody";
		uniformClass="BAF_Soldier_Base_R_D_Uniform_DG1";
		backpack="TWC_Backpack_1990_Medic";
		linkedItems[]=
		{
        "BAF_Soldier_Light_Vest_D_DG1",
		"BAF_Soldier_1_Headgear_D_DG1",
		"ItemMap",
		"ItemCompass",
		"ItemWatch",
		"UK3CB_BAF_G_Tactical_Black",
		"ACRE_PRC343"
		};
		respawnLinkedItems[]=
		{
        "BAF_Soldier_Light_Vest_D_DG1",
		"ItemMap",
		"ItemCompass",
		"ItemWatch",
		"ACRE_PRC343",
		"UK3CB_BAF_G_Tactical_Black"
		};
		weapons[]=
		{
		"Throw",
		"Put",	
		"UK3CB_BAF_L131A1"
		};
		respawnweapons[]=
		{
		"Throw",
		"Put",
		"UK3CB_BAF_L131A1"
		};
		magazines[]=
		{
		"UK3CB_BAF_17Rnd_9mm",
		"UK3CB_BAF_17Rnd_9mm",
		"UK3CB_BAF_17Rnd_9mm",
		"SmokeShell",
		"SmokeShell",
		"SmokeShell",
		"SmokeShell",
		"SmokeShell"
		};
		Respawnmagazines[]=
		{
		"UK3CB_BAF_17Rnd_9mm",
		"UK3CB_BAF_17Rnd_9mm",
		"UK3CB_BAF_17Rnd_9mm",
		"SmokeShell",
		"SmokeShell",
		"SmokeShell",
		"SmokeShell",
		"SmokeShell"
		};
		Items[]=
		{
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_morphine",
		"ACE_morphine",
		"ACE_EarPlugs",	
		"UK3CB_BAF_HMNVS"
		};
		respawntems[]=
		{
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_morphine",
		"ACE_morphine",
		"ACE_EarPlugs",	
		"UK3CB_BAF_HMNVS"			
		};		
	};
class 1990_HeloPilot_Desert: B_Soldier_base_F
	{
		_generalMacro="1990_HelicopterPilot_Desert";
		scope=2;
		displayName="Helicopter Pilot(90`s Desert)";
		faction="a_units";
		vehicleClass="1990_British_Desert";
		icon="iconMan";
		nakedUniform="U_BasicBody";
		uniformClass="BAF_Soldier_Base_L_D_Uniform_DG1";
		backpack="TWC_Backpack_Cold_War_Pilot";
		linkedItems[]=
		{
		"UK3CB_BAF_H_PilotHelmetHeli_A",
		"ItemMap",
		"ItemCompass",
		"ItemWatch"
		};
		respawnLinkedItems[]=
		{
		"UK3CB_BAF_H_PilotHelmetHeli_A",
		"ItemMap",		
		"ItemCompass",
		"ItemWatch"
		};
		weapons[]=
		{
		"Throw",
		"Put",
		"UK3CB_BAF_L22A2_SUSAT3D",
		"UK3CB_BAF_L131A1"
		};
		respawnweapons[]=
		{
		"Throw",
		"Put",
		"UK3CB_BAF_L22A2_SUSAT3D",
		"UK3CB_BAF_L131A1"
		};
		magazines[]=
		{
		"UK3CB_BAF_17Rnd_9mm",
		"UK3CB_BAF_17Rnd_9mm",
		"UK3CB_BAF_30Rnd",
		"UK3CB_BAF_30Rnd",
		"SmokeShell",
		"SmokeShell"
		};
		Respawnmagazines[]=
		{
		"UK3CB_BAF_17Rnd_9mm",
		"UK3CB_BAF_17Rnd_9mm",
		"UK3CB_BAF_30Rnd",
		"UK3CB_BAF_30Rnd",
		"SmokeShell",
		"SmokeShell"
		};
		Items[]=
		{
		"ACE_EarPlugs",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_morphine",
		"ACE_morphine"
		};
		respawntems[]=
		{
		"ACE_EarPlugs",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_morphine",
		"ACE_morphine"
		};		
	};	
};