//COIN, DESERT, DISMOUNTED
//Section
class TWC_Infantry_1990_COIN_Dismounted_Desert_Rifleman: TWC_Infantry_1990_COIN_Desert_Rifleman
{
	CATEGORY(TWC_Infantry_COIN_Dismounted_Desert)
	backpack = "TWC_Backpack_1990_COIN_Dismounted_Desert_Rifleman";
};
class TWC_Infantry_1990_COIN_Dismounted_Desert_AT: TWC_Infantry_1990_COIN_Desert_AT
{
	CATEGORY(TWC_Infantry_COIN_Dismounted_Desert)
	backpack = "TWC_Backpack_1990_COIN_Dismounted_Desert_AT";
};
class TWC_Infantry_1990_COIN_Dismounted_Desert_Gunner: TWC_Infantry_1990_COIN_Desert_Gunner
{
	CATEGORY(TWC_Infantry_COIN_Dismounted_Desert)
	backpack = "TWC_Backpack_1990_COIN_Dismounted_Desert_Gunner";
};
class TWC_Infantry_1990_COIN_Dismounted_Desert_SectionCommander: TWC_Infantry_1990_COIN_Desert_SectionCommander
{
	CATEGORY(TWC_Infantry_COIN_Dismounted_Desert)
	backpack = "TWC_Backpack_1990_COIN_Dismounted_Desert_SectionCommander";
};
class TWC_Infantry_1990_COIN_Dismounted_Desert_2iC: TWC_Infantry_1990_COIN_Desert_2iC
{
	CATEGORY(TWC_Infantry_COIN_Dismounted_Desert)
	backpack = "TWC_Backpack_1990_COIN_Dismounted_Desert_2iC";
};
class TWC_Infantry_1990_COIN_Dismounted_Desert_MG: TWC_Infantry_1990_COIN_Desert_MG
{
	CATEGORY(TWC_Infantry_COIN_Dismounted_Desert)
	backpack = "TWC_Backpack_1990_COIN_Dismounted_Desert_MG";
};
class TWC_Infantry_1990_COIN_Dismounted_Desert_ASSMG: TWC_Infantry_1990_COIN_Desert_ASSMG
{
	CATEGORY(TWC_Infantry_COIN_Dismounted_Desert)
	backpack = "TWC_Backpack_1990_COIN_Dismounted_Desert_ASSMG";
};
//Platoon Command
class TWC_Infantry_1990_COIN_Dismounted_Desert_Platoon_Commander: TWC_Infantry_1990_COIN_Desert_Platoon_Commander
{
	CATEGORY(TWC_Infantry_COIN_Dismounted_Desert)
	backpack = "TWC_Backpack_1990_COIN_Dismounted_Desert_Platoon_Commander";
};
class TWC_Infantry_1990_COIN_Dismounted_Desert_Platoon_Sergeant: TWC_Infantry_1990_COIN_Desert_Platoon_Sergeant
{
	CATEGORY(TWC_Infantry_COIN_Dismounted_Desert)
	backpack = "TWC_Backpack_1990_COIN_Dismounted_Desert_Platoon_Sergeant";
};
class TWC_Infantry_1990_COIN_Dismounted_Desert_Platoon_Medic: TWC_Infantry_1990_COIN_Desert_Platoon_Medic
{
	CATEGORY(TWC_Infantry_COIN_Dismounted_Desert)
	backpack = "TWC_Backpack_1990_COIN_Dismounted_Desert_Platoon_Medic";
};
class TWC_Infantry_1990_COIN_Dismounted_Desert_Platoon_CSM: TWC_Infantry_1990_COIN_Desert_Platoon_CSM
{
	CATEGORY(TWC_Infantry_COIN_Dismounted_Desert)
	backpack = "TWC_Backpack_1990_COIN_Dismounted_Desert_Platoon_Sergeant";
};

//Company
class TWC_Infantry_1990_COIN_Dismounted_Desert_Company_Commander: TWC_Infantry_1990_COIN_Desert_Company_Commander
{
	CATEGORY(TWC_Infantry_COIN_Dismounted_Desert)
	backpack = "TWC_Backpack_1990_COIN_Dismounted_Desert_Platoon_Commander";
};
class TWC_Infantry_1990_COIN_Dismounted_Desert_Company_2iC: TWC_Infantry_1990_COIN_Desert_Company_2iC
{
	CATEGORY(TWC_Infantry_COIN_Dismounted_Desert)
	backpack = "TWC_Backpack_1990_COIN_Dismounted_Desert_Platoon_Commander";
};
class TWC_Infantry_1990_COIN_Dismounted_Desert_Company_Sergeant: TWC_Infantry_1990_COIN_Desert_Company_Sergeant
{
	CATEGORY(TWC_Infantry_COIN_Dismounted_Desert)
	backpack = "TWC_Backpack_1990_COIN_Dismounted_Desert_Platoon_Sergeant";
};