//UK, EARLY, DISMOUNTED, ARCITC
//Section
class TWC_Infantry_WW2_UK_Early_Dismounted_Arctic_Rifleman: TWC_Infantry_WW2_UK_Early_Arctic_Rifleman
{
	CATEGORY(TWC_Infantry_EarlyWW2_Dismounted_Arctic)
	backpack = "TWC_Backpack_WW2_UK_Early_Dismounted_Rifleman";
};
class TWC_Infantry_WW2_UK_Early_Dismounted_Arctic_Grenadier: TWC_Infantry_WW2_UK_Early_Arctic_Grenadier
{
	CATEGORY(TWC_Infantry_EarlyWW2_Dismounted_Arctic)
	backpack = "TWC_Backpack_WW2_UK_Early_Dismounted_Grenadier";
};
class TWC_Infantry_WW2_UK_Early_Dismounted_Arctic_SMG: TWC_Infantry_WW2_UK_Early_Arctic_SMG
{
	CATEGORY(TWC_Infantry_EarlyWW2_Dismounted_Arctic)
	backpack = "TWC_Backpack_WW2_UK_Early_Dismounted_SMG";
};
class TWC_Infantry_WW2_UK_Early_Dismounted_Arctic_MG: TWC_Infantry_WW2_UK_Early_Arctic_MG
{
	CATEGORY(TWC_Infantry_EarlyWW2_Dismounted_Arctic)
	backpack = "TWC_Backpack_WW2_UK_Early_Dismounted_MG";
};
class TWC_Infantry_WW2_UK_Early_Dismounted_Arctic_MGASS: TWC_Infantry_WW2_UK_Early_Arctic_MGASS
{
	CATEGORY(TWC_Infantry_EarlyWW2_Dismounted_Arctic)
	backpack = "TWC_Backpack_WW2_UK_Early_Dismounted_MGASS";
};
class TWC_Infantry_WW2_UK_Early_Dismounted_Arctic_SectionCommander: TWC_Infantry_WW2_UK_Early_Arctic_SectionCommander
{
	CATEGORY(TWC_Infantry_EarlyWW2_Dismounted_Arctic)
	backpack = "TWC_Backpack_WW2_UK_Early_Dismounted_SectionCommander";
};
class TWC_Infantry_WW2_UK_Early_Dismounted_Arctic_2iC: TWC_Infantry_WW2_UK_Early_Arctic_2iC
{
	CATEGORY(TWC_Infantry_EarlyWW2_Dismounted_Arctic)
	backpack = "TWC_Backpack_WW2_UK_Early_Dismounted_2iC";
};

//Platoon
class TWC_Infantry_WW2_UK_Early_Dismounted_Arctic_Platoon_Commander: TWC_Infantry_WW2_UK_Early_Arctic_Platoon_Commander
{
	CATEGORY(TWC_Infantry_EarlyWW2_Dismounted_Arctic)
	backpack = "TWC_Backpack_WW2_UK_Early_Dismounted_Platoon_Commander";
};
class TWC_Infantry_WW2_UK_Early_Dismounted_Arctic_Platoon_Sergeant: TWC_Infantry_WW2_UK_Early_Arctic_Platoon_Sergeant
{
	CATEGORY(TWC_Infantry_EarlyWW2_Dismounted_Arctic)
	backpack = "TWC_Backpack_WW2_UK_Early_Dismounted_Platoon_Sergeant";
};
class TWC_Infantry_WW2_UK_Early_Dismounted_Arctic_Platoon_Medic: TWC_Infantry_WW2_UK_Early_Arctic_Platoon_Medic
{
	CATEGORY(TWC_Infantry_EarlyWW2_Dismounted_Arctic)
	backpack = "TWC_Backpack_WW2_UK_Early_Dismounted_Platoon_Medic";
};
class TWC_Infantry_WW2_UK_Early_Dismounted_Arctic_Platoon_Runner: TWC_Infantry_WW2_UK_Early_Arctic_Platoon_Runner
{
	CATEGORY(TWC_Infantry_EarlyWW2_Dismounted_Arctic)
	backpack = "TWC_Backpack_WW2_UK_Early_Dismounted_Rifleman";
};
class TWC_Infantry_WW2_UK_Early_Dismounted_Arctic_Platoon_Mortar: TWC_Infantry_WW2_UK_Early_Arctic_Platoon_Mortar
{
	CATEGORY(TWC_Infantry_EarlyWW2_Dismounted_Arctic)
	backpack = "TWC_Backpack_WW2_UK_Early_Dismounted_Platoon_Mortar";
};
class TWC_Infantry_WW2_UK_Early_Dismounted_Arctic_Platoon_CSM: TWC_Infantry_WW2_UK_Early_Arctic_Platoon_CSM
{
	CATEGORY(TWC_Infantry_EarlyWW2_Dismounted_Arctic)
	backpack = "TWC_Backpack_WW2_UK_Early_Dismounted_Platoon_Sergeant";
};

//Company
class TWC_Infantry_WW2_UK_Early_Dismounted_Arctic_Company_Commander: TWC_Infantry_WW2_UK_Early_Arctic_Company_Commander
{
	CATEGORY(TWC_Infantry_EarlyWW2_Dismounted_Arctic)
	backpack = "TWC_Backpack_WW2_UK_Early_Dismounted_Platoon_Commander";
};
class TWC_Infantry_WW2_UK_Early_Dismounted_Arctic_Company_2iC: TWC_Infantry_WW2_UK_Early_Arctic_Company_2iC
{
	CATEGORY(TWC_Infantry_EarlyWW2_Dismounted_Arctic)
	backpack = "TWC_Backpack_WW2_UK_Early_Dismounted_Platoon_Commander";
};
class TWC_Infantry_WW2_UK_Early_Dismounted_Arctic_Company_Sergeant: TWC_Infantry_WW2_UK_Early_Arctic_Company_Sergeant
{
	CATEGORY(TWC_Infantry_EarlyWW2_Dismounted_Arctic)
	backpack = "TWC_Backpack_WW2_UK_Early_Dismounted_Platoon_Sergeant";
};