//UK, EARLY, DISMOUNTED, DESERT
//Section
class TWC_Infantry_WW2_UK_Early_Dismounted_Desert_Rifleman: TWC_Infantry_WW2_UK_Early_Desert_Rifleman
{
	CATEGORY(TWC_Infantry_EarlyWW2_Dismounted_Desert)
	backpack = "TWC_Backpack_WW2_UK_Early_Dismounted_Rifleman";
};
class TWC_Infantry_WW2_UK_Early_Dismounted_Desert_Grenadier: TWC_Infantry_WW2_UK_Early_Desert_Grenadier
{
	CATEGORY(TWC_Infantry_EarlyWW2_Dismounted_Desert)
	backpack = "TWC_Backpack_WW2_UK_Early_Dismounted_Grenadier";
};
class TWC_Infantry_WW2_UK_Early_Dismounted_Desert_SMG: TWC_Infantry_WW2_UK_Early_Desert_SMG
{
	CATEGORY(TWC_Infantry_EarlyWW2_Dismounted_Desert)
	backpack = "TWC_Backpack_WW2_UK_Early_Dismounted_SMG";
};
class TWC_Infantry_WW2_UK_Early_Dismounted_Desert_MG: TWC_Infantry_WW2_UK_Early_Desert_MG
{
	CATEGORY(TWC_Infantry_EarlyWW2_Dismounted_Desert)
	backpack = "TWC_Backpack_WW2_UK_Early_Dismounted_MG";
};
class TWC_Infantry_WW2_UK_Early_Dismounted_Desert_MGASS: TWC_Infantry_WW2_UK_Early_Desert_MGASS
{
	CATEGORY(TWC_Infantry_EarlyWW2_Dismounted_Desert)
	backpack = "TWC_Backpack_WW2_UK_Early_Dismounted_MGASS";
};
class TWC_Infantry_WW2_UK_Early_Dismounted_Desert_SectionCommander: TWC_Infantry_WW2_UK_Early_Desert_SectionCommander
{
	CATEGORY(TWC_Infantry_EarlyWW2_Dismounted_Desert)
	backpack = "TWC_Backpack_WW2_UK_Early_Dismounted_SectionCommander";
};
class TWC_Infantry_WW2_UK_Early_Dismounted_Desert_2iC: TWC_Infantry_WW2_UK_Early_Desert_2iC
{
	CATEGORY(TWC_Infantry_EarlyWW2_Dismounted_Desert)
	backpack = "TWC_Backpack_WW2_UK_Early_Dismounted_2iC";
};

//Platoon
class TWC_Infantry_WW2_UK_Early_Dismounted_Desert_Platoon_Commander: TWC_Infantry_WW2_UK_Early_Desert_Platoon_Commander
{
	CATEGORY(TWC_Infantry_EarlyWW2_Dismounted_Desert)
	backpack = "TWC_Backpack_WW2_UK_Early_Dismounted_Platoon_Commander";
};
class TWC_Infantry_WW2_UK_Early_Dismounted_Desert_Platoon_Sergeant: TWC_Infantry_WW2_UK_Early_Desert_Platoon_Sergeant
{
	CATEGORY(TWC_Infantry_EarlyWW2_Dismounted_Desert)
	backpack = "TWC_Backpack_WW2_UK_Early_Dismounted_Platoon_Sergeant";
};
class TWC_Infantry_WW2_UK_Early_Dismounted_Desert_Platoon_Medic: TWC_Infantry_WW2_UK_Early_Desert_Platoon_Medic
{
	CATEGORY(TWC_Infantry_EarlyWW2_Dismounted_Desert)
	backpack = "TWC_Backpack_WW2_UK_Early_Dismounted_Platoon_Medic";
};
class TWC_Infantry_WW2_UK_Early_Dismounted_Desert_Platoon_Runner: TWC_Infantry_WW2_UK_Early_Desert_Platoon_Runner
{
	CATEGORY(TWC_Infantry_EarlyWW2_Dismounted_Desert)
	backpack = "TWC_Backpack_WW2_UK_Early_Dismounted_Rifleman";
};
class TWC_Infantry_WW2_UK_Early_Dismounted_Desert_Platoon_Mortar: TWC_Infantry_WW2_UK_Early_Desert_Platoon_Mortar
{
	CATEGORY(TWC_Infantry_EarlyWW2_Dismounted_Desert)
	backpack = "TWC_Backpack_WW2_UK_Early_Dismounted_Platoon_Mortar";
};
class TWC_Infantry_WW2_UK_Early_Dismounted_Desert_Platoon_CSM: TWC_Infantry_WW2_UK_Early_Desert_Platoon_CSM
{
	CATEGORY(TWC_Infantry_EarlyWW2_Dismounted_Desert)
	backpack = "TWC_Backpack_WW2_UK_Early_Dismounted_Platoon_Sergeant";
};


//Company
class TWC_Infantry_WW2_UK_Early_Dismounted_Desert_Company_Commander: TWC_Infantry_WW2_UK_Early_Desert_Company_Commander
{
	CATEGORY(TWC_Infantry_EarlyWW2_Dismounted_Desert)
	backpack = "TWC_Backpack_WW2_UK_Early_Dismounted_Platoon_Commander";
};
class TWC_Infantry_WW2_UK_Early_Dismounted_Desert_Company_2iC: TWC_Infantry_WW2_UK_Early_Desert_Company_2iC
{
	CATEGORY(TWC_Infantry_EarlyWW2_Dismounted_Desert)
	backpack = "TWC_Backpack_WW2_UK_Early_Dismounted_Platoon_Commander";
};
class TWC_Infantry_WW2_UK_Early_Dismounted_Desert_Company_Sergeant: TWC_Infantry_WW2_UK_Early_Desert_Company_Sergeant
{
	CATEGORY(TWC_Infantry_EarlyWW2_Dismounted_Desert)
	backpack = "TWC_Backpack_WW2_UK_Early_Dismounted_Platoon_Sergeant";
};