//AIRBORNE, DESERT
//Section
class TWC_Infantry_ColdWar_Airborne_Desert_Rifleman: TWC_Infantry_ColdWar_Regular_Desert_Rifleman
class TWC_Infantry_ColdWar_Airborne_Desert_Rifleman_SUIT: TWC_Infantry_ColdWar_Regular_Desert_Rifleman_SUIT
class TWC_Infantry_ColdWar_Airborne_Desert_SectionCommander: TWC_Infantry_ColdWar_Regular_Desert_SectionCommander
class TWC_Infantry_ColdWar_Airborne_Desert_2iC: TWC_Infantry_ColdWar_Regular_Desert_2iC
class TWC_Infantry_ColdWar_Airborne_Desert_AT: TWC_Infantry_ColdWar_Regular_Desert_AT
class TWC_Infantry_ColdWar_Airborne_Desert_ASSAT: TWC_Infantry_ColdWar_Regular_Desert_ASSAT
class TWC_Infantry_ColdWar_Airborne_Desert_MG: TWC_Infantry_ColdWar_Regular_Desert_MG
class TWC_Infantry_ColdWar_Airborne_Desert_ASSMG: TWC_Infantry_ColdWar_Regular_Desert_ASSMG

//Platoon Command
class TWC_Infantry_ColdWar_Airborne_Desert_Platoon_Commander: TWC_Infantry_ColdWar_Regular_Desert_Platoon_Commander
class TWC_Infantry_ColdWar_Airborne_Desert_Platoon_Sergeant: TWC_Infantry_ColdWar_Regular_Desert_Platoon_Sergeant
class TWC_Infantry_ColdWar_Airborne_Desert_Platoon_Medic: TWC_Infantry_ColdWar_Regular_Desert_Platoon_Medic
class TWC_Infantry_ColdWar_Airborne_Desert_CSM: TWC_Infantry_ColdWar_Regular_Desert_CSM

//AT + AA
class TWC_Infantry_ColdWar_Airborne_Desert_MILAN_Gunner: TWC_Infantry_ColdWar_Regular_Desert_MILAN_Gunner
class TWC_Infantry_ColdWar_Airborne_Desert_MILAN_Ass: TWC_Infantry_ColdWar_Regular_Desert_MILAN_Ass
class TWC_Infantry_ColdWar_Airborne_Desert_Blowpipe_Gunner: TWC_Infantry_ColdWar_Regular_Desert_Blowpipe_Gunner
class TWC_Infantry_ColdWar_Airborne_Desert_Blowpipe_Ass: TWC_Infantry_ColdWar_Regular_Desert_Blowpipe_Ass

//Sniper Team
class TWC_Infantry_ColdWar_Airborne_Desert_Sniper: TWC_Infantry_ColdWar_Regular_Desert_Sniper
class TWC_Infantry_ColdWar_Airborne_Desert_Spotter: TWC_Infantry_ColdWar_Regular_Desert_Spotter

//Artillery Crew
class TWC_Infantry_ColdWar_Airborne_Desert_Artillery_Commander: TWC_Infantry_ColdWar_Regular_Desert_Artillery_Commander
class TWC_Infantry_ColdWar_Airborne_Desert_Artillery_Crew: TWC_Infantry_ColdWar_Regular_Desert_Artillery_Crew
class TWC_Infantry_ColdWar_Airborne_Desert_FO: TWC_Infantry_ColdWar_Regular_Desert_FO

//Aircraft
class TWC_Infantry_ColdWar_Airborne_Desert_FAC: TWC_Infantry_ColdWar_Regular_Desert_FAC