//AIRBORNE, DESERT
//Section
class TWC_Infantry_ColdWar_Airborne_Desert_Rifleman: TWC_Infantry_ColdWar_Regular_Dismounted_Desert_Rifleman
{
	CATEGORY(TWC_Infantry_Airborne_Desert)
	uniformClass="SP_72Para_DenisonKhaki_1_Item";
	linkedItems[]=
	{
		"SP_P58_FightingOrderNBC",
		"SP_Helmet_Airborne_Khaki",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
	respawnLinkedItems[]=
	{
		"SP_P58_FightingOrderNBC",
		"SP_Helmet_Airborne_Khaki",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
};
class TWC_Infantry_ColdWar_Airborne_Desert_Rifleman_SUIT: TWC_Infantry_ColdWar_Regular_Dismounted_Desert_Rifleman_SUIT
{
	CATEGORY(TWC_Infantry_Airborne_Desert)
	uniformClass="SP_72Para_DenisonKhaki_1_Item";
	linkedItems[]=
	{
		"SP_P58_FightingOrderNBC",
		"SP_Helmet_Airborne_Khaki",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
	respawnLinkedItems[]=
	{
		"SP_P58_FightingOrderNBC",
		"SP_Helmet_Airborne_Khaki",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
};
class TWC_Infantry_ColdWar_Airborne_Desert_SectionCommander: TWC_Infantry_ColdWar_Regular_Dismounted_Desert_SectionCommander
{
	CATEGORY(TWC_Infantry_Airborne_Desert)
	uniformClass="SP_72Para_DenisonKhaki_1_Item";
	linkedItems[]=
	{
		"SP_P58_FightingOrderNBC",
		"SP_Helmet_Airborne_Khaki",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
	respawnLinkedItems[]=
	{
		"SP_P58_FightingOrderNBC",
		"SP_Helmet_Airborne_Khaki",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
};
class TWC_Infantry_ColdWar_Airborne_Desert_2iC: TWC_Infantry_ColdWar_Regular_Dismounted_Desert_2iC
{
	CATEGORY(TWC_Infantry_Airborne_Desert)
	uniformClass="SP_72Para_DenisonKhaki_1_Item";
	linkedItems[]=
	{
		"SP_P58_FightingOrderNBC",
		"SP_Helmet_Airborne_Khaki",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
	respawnLinkedItems[]=
	{
		"SP_P58_FightingOrderNBC",
		"SP_Helmet_Airborne_Khaki",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
};
class TWC_Infantry_ColdWar_Airborne_Desert_AT: TWC_Infantry_ColdWar_Regular_Dismounted_Desert_AT
{
	CATEGORY(TWC_Infantry_Airborne_Desert)
	uniformClass="SP_72Para_DenisonKhaki_1_Item";
	linkedItems[]=
	{
		"SP_P58_FightingOrderNBC",
		"SP_Helmet_Airborne_Khaki",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
	respawnLinkedItems[]=
	{
		"SP_P58_FightingOrderNBC",
		"SP_Helmet_Airborne_Khaki",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
};
class TWC_Infantry_ColdWar_Airborne_Desert_ASSAT: TWC_Infantry_ColdWar_Regular_Dismounted_Desert_ASSAT
{
	CATEGORY(TWC_Infantry_Airborne_Desert)
	uniformClass="SP_72Para_DenisonKhaki_1_Item";
	linkedItems[]=
	{
		"SP_P58_FightingOrderNBC",
		"SP_Helmet_Airborne_Khaki",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
	respawnLinkedItems[]=
	{
		"SP_P58_FightingOrderNBC",
		"SP_Helmet_Airborne_Khaki",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
};
class TWC_Infantry_ColdWar_Airborne_Desert_MG: TWC_Infantry_ColdWar_Regular_Dismounted_Desert_MG
{
	CATEGORY(TWC_Infantry_Airborne_Desert)
	uniformClass="SP_72Para_DenisonKhaki_1_Item";
	linkedItems[]=
	{
		"SP_P58_FightingOrderNBC",
		"SP_Helmet_Airborne_Khaki",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
	respawnLinkedItems[]=
	{
		"SP_P58_FightingOrderNBC",
		"SP_Helmet_Airborne_Khaki",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
};
class TWC_Infantry_ColdWar_Airborne_Desert_ASSMG: TWC_Infantry_ColdWar_Regular_Dismounted_Desert_ASSMG
{
	CATEGORY(TWC_Infantry_Airborne_Desert)
	uniformClass="SP_72Para_DenisonKhaki_1_Item";
	linkedItems[]=
	{
		"SP_P58_FightingOrderNBC",
		"SP_Helmet_Airborne_Khaki",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
	respawnLinkedItems[]=
	{
		"SP_P58_FightingOrderNBC",
		"SP_Helmet_Airborne_Khaki",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
};

//Platoon Command
class TWC_Infantry_ColdWar_Airborne_Desert_Platoon_Commander: TWC_Infantry_ColdWar_Regular_Dismounted_Desert_Platoon_Commander
{
	CATEGORY(TWC_Infantry_Airborne_Desert)
	uniformClass="SP_72Para_DenisonKhaki_1_Item";
	linkedItems[]=
	{
		"SP_P58_FightingOrderNBC",
		"SP_Helmet_Airborne_Khaki",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
	respawnLinkedItems[]=
	{
		"SP_P58_FightingOrderNBC",
		"SP_Helmet_Airborne_Khaki",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
};
class TWC_Infantry_ColdWar_Airborne_Desert_Platoon_Sergeant: TWC_Infantry_ColdWar_Regular_Dismounted_Desert_Platoon_Sergeant
{
	CATEGORY(TWC_Infantry_Airborne_Desert)
	uniformClass="SP_72Para_DenisonKhaki_1_Item";
	linkedItems[]=
	{
		"SP_P58_FightingOrderNBC",
		"SP_Helmet_Airborne_Khaki",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
	respawnLinkedItems[]=
	{
		"SP_P58_FightingOrderNBC",
		"SP_Helmet_Airborne_Khaki",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
};
class TWC_Infantry_ColdWar_Airborne_Desert_Platoon_Medic: TWC_Infantry_ColdWar_Regular_Dismounted_Desert_Platoon_Medic
{
	CATEGORY(TWC_Infantry_Airborne_Desert)
	uniformClass="SP_72Para_DenisonKhaki_1_Item";
	linkedItems[]=
	{
		"SP_P58_FightingOrderNBC",
		"SP_Helmet_Airborne_KhakiMedic",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
	respawnLinkedItems[]=
	{
		"SP_P58_FightingOrderNBC",
		"SP_Helmet_Airborne_KhakiMedic",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
};
class TWC_Infantry_ColdWar_Airborne_Desert_CSM: TWC_Infantry_ColdWar_Regular_Dismounted_Desert_CSM
{
	CATEGORY(TWC_Infantry_Airborne_Desert)
	uniformClass="SP_72Para_DenisonKhaki_1_Item";
	linkedItems[]=
	{
		"SP_P58_FightingOrderNBC",
		"SP_Helmet_Airborne_Khaki",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
	respawnLinkedItems[]=
	{
		"SP_P58_FightingOrderNBC",
		"SP_Helmet_Airborne_Khaki",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
};

//AT + AA
class TWC_Infantry_ColdWar_Airborne_Desert_MILAN_Gunner: TWC_Infantry_ColdWar_Regular_Desert_MILAN_Gunner
{
	CATEGORY(TWC_Infantry_Airborne_Desert)
	uniformClass="SP_72Para_DenisonKhaki_1_Item";
	linkedItems[]=
	{
		"SP_P58_FightingOrderNBC",
		"SP_Helmet_Airborne_Khaki",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
	respawnLinkedItems[]=
	{
		"SP_P58_FightingOrderNBC",
		"SP_Helmet_Airborne_Khaki",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
};
class TWC_Infantry_ColdWar_Airborne_Desert_MILAN_Ass: TWC_Infantry_ColdWar_Regular_Desert_MILAN_Ass
{
	CATEGORY(TWC_Infantry_Airborne_Desert)
	uniformClass="SP_72Para_DenisonKhaki_1_Item";
	linkedItems[]=
	{
		"SP_P58_FightingOrderNBC",
		"SP_Helmet_Airborne_Khaki",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
	respawnLinkedItems[]=
	{
		"SP_P58_FightingOrderNBC",
		"SP_Helmet_Airborne_Khaki",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
};
class TWC_Infantry_ColdWar_Airborne_Desert_Blowpipe_Gunner: TWC_Infantry_ColdWar_Regular_Desert_Blowpipe_Gunner
{
	CATEGORY(TWC_Infantry_Airborne_Desert)
	uniformClass="SP_72Para_DenisonKhaki_1_Item";
	linkedItems[]=
	{
		"SP_P58_FightingOrderNBC",
		"SP_Helmet_Airborne_Khaki",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
	respawnLinkedItems[]=
	{
		"SP_P58_FightingOrderNBC",
		"SP_Helmet_Airborne_Khaki",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
};
class TWC_Infantry_ColdWar_Airborne_Desert_Blowpipe_Ass: TWC_Infantry_ColdWar_Regular_Desert_Blowpipe_Ass
{
	CATEGORY(TWC_Infantry_Airborne_Desert)
	uniformClass="SP_72Para_DenisonKhaki_1_Item";
	linkedItems[]=
	{
		"SP_P58_FightingOrderNBC",
		"SP_Helmet_Airborne_Khaki",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
	respawnLinkedItems[]=
	{
		"SP_P58_FightingOrderNBC",
		"SP_Helmet_Airborne_Khaki",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
};

//Sniper Team
class TWC_Infantry_ColdWar_Airborne_Desert_Sniper: TWC_Infantry_ColdWar_Regular_Desert_Sniper
{
	CATEGORY(TWC_Infantry_Airborne_Desert)
	uniformClass="SP_72Para_DenisonKhaki_1_Item";
	linkedItems[]=
	{
		"SP_P58_FightingOrderNBC",
		"SP_Helmet_Airborne_Khaki",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
	respawnLinkedItems[]=
	{
		"SP_P58_FightingOrderNBC",
		"SP_Helmet_Airborne_Khaki",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
};
class TWC_Infantry_ColdWar_Airborne_Desert_Spotter: TWC_Infantry_ColdWar_Regular_Desert_Spotter
{
	CATEGORY(TWC_Infantry_Airborne_Desert)
	uniformClass="SP_72Para_DenisonKhaki_1_Item";
	linkedItems[]=
	{
		"SP_P58_FightingOrderNBC",
		"SP_Helmet_Airborne_Khaki",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
	respawnLinkedItems[]=
	{
		"SP_P58_FightingOrderNBC",
		"SP_Helmet_Airborne_Khaki",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
};

//Artillery Crew
class TWC_Infantry_ColdWar_Airborne_Desert_Artillery_Commander: TWC_Infantry_ColdWar_Regular_Desert_Artillery_Commander
{
	CATEGORY(TWC_Infantry_Airborne_Desert)
	uniformClass="SP_72Para_DenisonKhaki_1_Item";
	linkedItems[]=
	{
		"SP_P58_FightingOrderNBC",
		"SP_Helmet_Airborne_Khaki",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
	respawnLinkedItems[]=
	{
		"SP_P58_FightingOrderNBC",
		"SP_Helmet_Airborne_Khaki",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
};
class TWC_Infantry_ColdWar_Airborne_Desert_Artillery_Crew: TWC_Infantry_ColdWar_Regular_Desert_Artillery_Crew
{
	CATEGORY(TWC_Infantry_Airborne_Desert)
	uniformClass="SP_72Para_DenisonKhaki_1_Item";
	linkedItems[]=
	{
		"SP_P58_FightingOrderNBC",
		"SP_Helmet_Airborne_Khaki",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
	respawnLinkedItems[]=
	{
		"SP_P58_FightingOrderNBC",
		"SP_Helmet_Airborne_Khaki",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
};
class TWC_Infantry_ColdWar_Airborne_Desert_FO: TWC_Infantry_ColdWar_Regular_Desert_FO
{
	CATEGORY(TWC_Infantry_Airborne_Desert)
	uniformClass="SP_72Para_DenisonKhaki_1_Item";
	linkedItems[]=
	{
		"SP_P58_FightingOrderNBC",
		"SP_Helmet_Airborne_Khaki",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
	respawnLinkedItems[]=
	{
		"SP_P58_FightingOrderNBC",
		"SP_Helmet_Airborne_Khaki",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
};

//Aircraft
class TWC_Infantry_ColdWar_Airborne_Desert_FAC: TWC_Infantry_ColdWar_Regular_Desert_FAC
{
	CATEGORY(TWC_Infantry_Airborne_Desert)
	uniformClass="SP_72Para_DenisonKhaki_1_Item";
	linkedItems[]=
	{
		"SP_P58_FightingOrderNBC",
		"SP_Helmet_Airborne_Khaki",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
	respawnLinkedItems[]=
	{
		"SP_P58_FightingOrderNBC",
		"SP_Helmet_Airborne_Khaki",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
};