//AIRBORNE, WOODLAND
//Section
class TWC_Infantry_ColdWar_Airborne_Woodland_Rifleman: TWC_Infantry_ColdWar_Regular_Woodland_Rifleman
class TWC_Infantry_ColdWar_Airborne_Woodland_Rifleman_SUIT: TWC_Infantry_ColdWar_Regular_Woodland_Rifleman_SUIT
class TWC_Infantry_ColdWar_Airborne_Woodland_SectionCommander: TWC_Infantry_ColdWar_Regular_Woodland_SectionCommander
class TWC_Infantry_ColdWar_Airborne_Woodland_2iC: TWC_Infantry_ColdWar_Regular_Woodland_2iC
class TWC_Infantry_ColdWar_Airborne_Woodland_AT: TWC_Infantry_ColdWar_Regular_Woodland_AT
class TWC_Infantry_ColdWar_Airborne_Woodland_ASSAT: TWC_Infantry_ColdWar_Regular_Woodland_ASSAT
class TWC_Infantry_ColdWar_Airborne_Woodland_MG: TWC_Infantry_ColdWar_Regular_Woodland_MG
class TWC_Infantry_ColdWar_Airborne_Woodland_ASSMG: TWC_Infantry_ColdWar_Regular_Woodland_ASSMG

//Platoon Command
class TWC_Infantry_ColdWar_Airborne_Woodland_Platoon_Commander: TWC_Infantry_ColdWar_Regular_Woodland_Platoon_Commander
class TWC_Infantry_ColdWar_Airborne_Woodland_Platoon_Sergeant: TWC_Infantry_ColdWarRegular_Woodland_Platoon_Sergeant
class TWC_Infantry_ColdWar_Airborne_Woodland_Platoon_Medic: TWC_Infantry_ColdWar_Regular_Woodland_Platoon_Medic
class TWC_Infantry_ColdWar_Airborne_Woodland_CSM: TWC_Infantry_ColdWar_Regular_Woodland_CSM

//AT + AA
class TWC_Infantry_ColdWar_Airborne_Woodland_MILAN_Gunner: TWC_Infantry_ColdWar_Regular_Woodland_MILAN_Gunner
class TWC_Infantry_ColdWar_Airborne_Woodland_MILAN_Ass: TWC_Infantry_ColdWar_Regular_Woodland_MILAN_Ass
class TWC_Infantry_ColdWar_Airborne_Woodland_Blowpipe_Gunner: TWC_Infantry_ColdWar_Regular_Woodland_Blowpipe_Gunner
class TWC_Infantry_ColdWar_Airborne_Woodland_Blowpipe_Ass: TWC_Infantry_ColdWar_Regular_Woodland_Blowpipe_Ass

//Sniper Team
class TWC_Infantry_ColdWar_Airborne_Woodland_Sniper: TWC_Infantry_ColdWar_Regular_Woodland_Sniper
class TWC_Infantry_ColdWar_Airborne_Woodland_Spotter: TWC_Infantry_ColdWar_Regular_Woodland_Spotter

//Artillery Crew
class TWC_Infantry_ColdWar_Airborne_Woodland_Artillery_Commander: TWC_Infantry_ColdWar_Regular_Woodland_Artillery_Commander
class TWC_Infantry_ColdWar_Airborne_Woodland_Artillery_Crew: TWC_Infantry_ColdWar_Regular_Woodland_Artillery_Crew
class TWC_Infantry_ColdWar_Airborne_Woodland_FO: TWC_Infantry_ColdWar_Regular_Woodland_Artillery_Crew

//Aircraft
class TWC_Infantry_ColdWar_Airborne_Woodland_FAC: TWC_Infantry_ColdWar_Regular_Woodland_FAC