	class O_G_officer_F;
	class O_G_Soldier_F;
	class O_G_Soldier_LAT_F;
	class O_G_Soldier_GL_F;
	class O_G_Soldier_AR_F;
	
	class twc_greek_officer: O_G_officer_F
	{
		_generalMacro="Greek_Officer";
		scope=2;
		displayName="Officer";
		faction="greek_units";
		editorSubcategory = "Men_Greek";
		vehicleClass="Men_Greek";
		icon="iconManLeader";
		nakedUniform="U_BasicBody";
		uniformClass="U_OG_Guerilla2_3";
		backpack="";
		linkedItems[]=
		{
        "V_BandollierB_oli",
		"G_Balaclava_blk",
		"ItemMap",
		"ItemCompass",
		"Binocular"
		};
		respawnLinkedItems[]=
		{
        "V_BandollierB_oli",
		"G_Balaclava_blk",
		"ItemMap",
		"ItemCompass",
		"Binocular"
		};
		weapons[]=
		{
		"Throw",
		"Put",
		"CUP_srifle_M14"
		};
		respawnweapons[]=
		{
		"Throw",
		"Put",
		"CUP_srifle_M14"
		};
		magazines[]=
		{
		"CUP_20Rnd_762x51_DMR",
		"CUP_20Rnd_762x51_DMR",
		"CUP_20Rnd_762x51_DMR",
		"CUP_20Rnd_762x51_DMR",
		"CUP_20Rnd_762x51_DMR",
		"HandGrenade",
		"HandGrenade",
		"SmokeShell"
		};
		Respawnmagazines[]=
		{
		"CUP_20Rnd_762x51_DMR",
		"CUP_20Rnd_762x51_DMR",
		"CUP_20Rnd_762x51_DMR",
		"CUP_20Rnd_762x51_DMR",
		"CUP_20Rnd_762x51_DMR",
		"HandGrenade",
		"HandGrenade",
		"SmokeShell"
		};
		Items[]=
		{
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_morphine",
		"ACE_morphine"
		};
		respawntems[]=
		{
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_morphine",
		"ACE_morphine"
		};
	};
	class twc_greek_rifleman: O_G_Soldier_F
	{
		_generalMacro="Greek_Rifleman";
		scope=2;
		displayName="Rifleman";
		faction="greek_units";
		editorSubcategory = "Men_Greek";
		vehicleClass="Men_Greek";
		icon="iconManLeader";
		nakedUniform="U_BasicBody";
		uniformClass="U_OG_Guerilla1_1";
		backpack="";
		linkedItems[]=
		{
        "V_BandollierB_oli",
		"G_Balaclava_blk",
		"ItemMap",
		"ItemCompass",
		"Binocular"
		};
		respawnLinkedItems[]=
		{
        "V_BandollierB_oli",
		"G_Balaclava_blk",
		"ItemMap",
		"ItemCompass",
		"Binocular"
		};
		weapons[]=
		{
		"Throw",
		"Put",
		"CUP_arifle_AK74"
		};
		respawnweapons[]=
		{
		"Throw",
		"Put",
		"CUP_arifle_AK74"
		};
		magazines[]=
		{
		"CUP_30Rnd_545x39_AK_M",
		"CUP_30Rnd_545x39_AK_M",
		"CUP_30Rnd_545x39_AK_M",
		"CUP_30Rnd_545x39_AK_M",
		"CUP_30Rnd_545x39_AK_M",
		"HandGrenade",
		"HandGrenade",
		"SmokeShell"
		};
		Respawnmagazines[]=
		{
		"CUP_30Rnd_545x39_AK_M",
		"CUP_30Rnd_545x39_AK_M",
		"CUP_30Rnd_545x39_AK_M",
		"CUP_30Rnd_545x39_AK_M",
		"CUP_30Rnd_545x39_AK_M",
		"HandGrenade",
		"HandGrenade",
		"SmokeShell"
		};
		Items[]=
		{
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_morphine",
		"ACE_morphine"
		};
		respawntems[]=
		{
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_morphine",
		"ACE_morphine"
		};
	};
	class twc_greek_rifleman_2: O_G_Soldier_F
	{
		_generalMacro="Greek_Rifleman_2";
		scope=2;
		displayName="Rifleman 2";
		faction="greek_units";
		editorSubcategory = "Men_Greek";
		vehicleClass="Men_Greek";
		icon="iconManLeader";
		nakedUniform="U_BasicBody";
		uniformClass="U_OG_Guerilla3_1";
		backpack="";
		linkedItems[]=
		{
        "V_BandollierB_oli",
		"G_Balaclava_blk",
		"ItemMap",
		"ItemCompass",
		"Binocular"
		};
		respawnLinkedItems[]=
		{
        "V_BandollierB_oli",
		"G_Balaclava_blk",
		"ItemMap",
		"ItemCompass",
		"Binocular"
		};
		weapons[]=
		{
		"Throw",
		"Put",
		"CUP_arifle_Sa58P",
		"CUP_launch_M72A6"
		};
		respawnweapons[]=
		{
		"Throw",
		"Put",
		"CUP_arifle_Sa58P",
		"CUP_launch_M72A6"
		};
		magazines[]=
		{
		"CUP_30Rnd_Sa58_M_TracerG",
		"CUP_30Rnd_Sa58_M_TracerG",
		"CUP_30Rnd_Sa58_M_TracerG",
		"CUP_30Rnd_Sa58_M_TracerG",
		"CUP_30Rnd_Sa58_M_TracerG",
		"HandGrenade",
		"HandGrenade",
		"SmokeShell"
		};
		Respawnmagazines[]=
		{
		"CUP_30Rnd_Sa58_M_TracerG",
		"CUP_30Rnd_Sa58_M_TracerG",
		"CUP_30Rnd_Sa58_M_TracerG",
		"CUP_30Rnd_Sa58_M_TracerG",
		"CUP_30Rnd_Sa58_M_TracerG",
		"HandGrenade",
		"HandGrenade",
		"SmokeShell"
		};
		Items[]=
		{
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_morphine",
		"ACE_morphine"
		};
		respawntems[]=
		{
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_morphine",
		"ACE_morphine"
		};
	};
	class twc_greek_rifleman_at: O_G_Soldier_LAT_F
	{
		_generalMacro="Greek_Rifleman_AT";
		scope=2;
		displayName="Rifleman AT";
		faction="greek_units";
		editorSubcategory = "Men_Greek";
		vehicleClass="Men_Greek";
		icon="iconManLeader";
		nakedUniform="U_BasicBody";
		uniformClass="U_OG_Guerrilla_6_1";
		backpack="greek_Backpack_AT";
		linkedItems[]=
		{
        "V_TacVest_blk",
		"G_Balaclava_blk",
		"ItemMap",
		"ItemCompass",
		"Binocular"
		};
		respawnLinkedItems[]=
		{
        "V_TacVest_blk",
		"G_Balaclava_blk",
		"ItemMap",
		"ItemCompass",
		"Binocular"
		};
		weapons[]=
		{
		"Throw",
		"Put",
		"CUP_arifle_M16A2",
		"CUP_launch_RPG7V"
		};
		respawnweapons[]=
		{
		"Throw",
		"Put",
		"CUP_arifle_M16A2",
		"CUP_launch_RPG7V"
		};
		magazines[]=
		{
		"CUP_30Rnd_556x45_Stanag",
		"CUP_30Rnd_556x45_Stanag",
		"CUP_30Rnd_556x45_Stanag",
		"CUP_30Rnd_556x45_Stanag",
		"CUP_30Rnd_556x45_Stanag",
		"CUP_PG7V_M",
		"HandGrenade",
		"HandGrenade",
		"SmokeShell"
		};
		Respawnmagazines[]=
		{
		"CUP_30Rnd_556x45_Stanag",
		"CUP_30Rnd_556x45_Stanag",
		"CUP_30Rnd_556x45_Stanag",
		"CUP_30Rnd_556x45_Stanag",
		"CUP_30Rnd_556x45_Stanag",
		"CUP_PG7V_M",
		"HandGrenade",
		"HandGrenade",
		"SmokeShell"
		};
		Items[]=
		{
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_morphine",
		"ACE_morphine"
		};
		respawntems[]=
		{
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_morphine",
		"ACE_morphine"
		};
	};
	class twc_greek_grenadier: O_G_Soldier_GL_F
	{
		_generalMacro="Greek_Grenadier";
		scope=2;
		displayName="Grenadier";
		faction="greek_units";
		editorSubcategory = "Men_Greek";
		vehicleClass="Men_Greek";
		icon="iconManLeader";
		nakedUniform="U_BasicBody";
		uniformClass="U_OG_Guerilla2_3";
		backpack="";
		linkedItems[]=
		{
        "V_Chestrig_blk",
		"G_Balaclava_blk",
		"ItemMap",
		"ItemCompass",
		"Binocular"
		};
		respawnLinkedItems[]=
		{
        "V_Chestrig_blk",
		"G_Balaclava_blk",
		"ItemMap",
		"ItemCompass",
		"Binocular"
		};
		weapons[]=
		{
		"Throw",
		"Put",
		"CUP_arifle_AK74_GL"
		};
		respawnweapons[]=
		{
		"Throw",
		"Put",
		"CUP_arifle_AK74_GL"
		};
		magazines[]=
		{
		"CUP_30Rnd_545x39_AK_M",
		"CUP_30Rnd_545x39_AK_M",
		"CUP_30Rnd_545x39_AK_M",
		"CUP_30Rnd_545x39_AK_M",
		"CUP_1Rnd_HE_GP25_M",
		"CUP_1Rnd_HE_GP25_M",
		"CUP_1Rnd_HE_GP25_M",
		"CUP_1Rnd_HE_GP25_M",
		"CUP_1Rnd_HE_GP25_M",
		"CUP_1Rnd_HE_GP25_M",
		"SmokeShell"
		};
		Respawnmagazines[]=
		{
		"CUP_30Rnd_545x39_AK_M",
		"CUP_30Rnd_545x39_AK_M",
		"CUP_30Rnd_545x39_AK_M",
		"CUP_30Rnd_545x39_AK_M",
		"CUP_1Rnd_HE_GP25_M",
		"CUP_1Rnd_HE_GP25_M",
		"CUP_1Rnd_HE_GP25_M",
		"CUP_1Rnd_HE_GP25_M",
		"CUP_1Rnd_HE_GP25_M",
		"CUP_1Rnd_HE_GP25_M",
		"SmokeShell"
		};
		Items[]=
		{
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_morphine",
		"ACE_morphine"
		};
		respawntems[]=
		{
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_morphine",
		"ACE_morphine"
		};
	};
	class twc_greek_ar: O_G_Soldier_AR_F
	{
		_generalMacro="Greek_AutomaticRifleman";
		scope=2;
		displayName="Automatic Rifleman";
		faction="greek_units";
		editorSubcategory = "Men_Greek";
		vehicleClass="Men_Greek";
		icon="iconManLeader";
		nakedUniform="U_BasicBody";
		uniformClass="U_OG_Guerilla2_1";
		backpack="";
		linkedItems[]=
		{
        "V_TacVest_blk",
		"G_Balaclava_blk",
		"ItemMap",
		"ItemCompass",
		"Binocular"
		};
		respawnLinkedItems[]=
		{
        "V_TacVest_blk",
		"G_Balaclava_blk",
		"ItemMap",
		"ItemCompass",
		"Binocular"
		};
		weapons[]=
		{
		"Throw",
		"Put",
		"CUP_lmg_m249_pip1"
		};
		respawnweapons[]=
		{
		"Throw",
		"Put",
		"CUP_lmg_m249_pip1"
		};
		magazines[]=
		{
		"CUP_200Rnd_TE4_Red_Tracer_556x45_M249",
		"CUP_200Rnd_TE4_Red_Tracer_556x45_M249",
		"SmokeShell"
		};
		Respawnmagazines[]=
		{
		"CUP_200Rnd_TE4_Red_Tracer_556x45_M249",
		"CUP_200Rnd_TE4_Red_Tracer_556x45_M249",
		"SmokeShell"
		};
		Items[]=
		{
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_morphine",
		"ACE_morphine"
		};
		respawntems[]=
		{
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_morphine",
		"ACE_morphine"
		};
	};
	class twc_greek_mg: O_G_Soldier_AR_F
	{
		_generalMacro="Greek_MachineGunner";
		scope=2;
		displayName="Machine Gunner";
		faction="greek_units";
		editorSubcategory = "Men_Greek";
		vehicleClass="Men_Greek";
		icon="iconManLeader";
		nakedUniform="U_BasicBody";
		uniformClass="U_OG_Guerilla2_1";
		backpack="";
		linkedItems[]=
		{
        "V_TacVest_blk",
		"G_Balaclava_blk",
		"ItemMap",
		"ItemCompass",
		"Binocular"
		};
		respawnLinkedItems[]=
		{
        "V_TacVest_blk",
		"G_Balaclava_blk",
		"ItemMap",
		"ItemCompass",
		"Binocular"
		};
		weapons[]=
		{
		"Throw",
		"Put",
		"CUP_lmg_UK59"
		};
		respawnweapons[]=
		{
		"Throw",
		"Put",
		"CUP_lmg_UK59"
		};
		magazines[]=
		{
		"CUP_50Rnd_UK59_762x54R_Tracer",
		"CUP_50Rnd_UK59_762x54R_Tracer",
		"CUP_50Rnd_UK59_762x54R_Tracer",
		"SmokeShell"
		};
		Respawnmagazines[]=
		{
		"CUP_50Rnd_UK59_762x54R_Tracer",
		"CUP_50Rnd_UK59_762x54R_Tracer",
		"CUP_50Rnd_UK59_762x54R_Tracer",
		"SmokeShell"
		};
		Items[]=
		{
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_morphine",
		"ACE_morphine"
		};
		respawntems[]=
		{
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_morphine",
		"ACE_morphine"
		};
	};
	class twc_greek_aa: O_G_Soldier_F
	{
		_generalMacro="Greek_AA";
		scope=2;
		displayName="Anti-Air";
		faction="greek_units";
		editorSubcategory = "Men_Greek";
		vehicleClass="Men_Greek";
		icon="iconManLeader";
		nakedUniform="U_BasicBody";
		uniformClass="U_OG_Guerilla1_1";
		backpack="";
		linkedItems[]=
		{
        "V_BandollierB_oli",
		"G_Balaclava_blk",
		"ItemMap",
		"ItemCompass",
		"Binocular"
		};
		respawnLinkedItems[]=
		{
        "V_BandollierB_oli",
		"G_Balaclava_blk",
		"ItemMap",
		"ItemCompass",
		"Binocular"
		};
		weapons[]=
		{
		"Throw",
		"Put",
		"CUP_arifle_AK74",
		"CUP_launch_Igla"
		};
		respawnweapons[]=
		{
		"Throw",
		"Put",
		"CUP_arifle_AK74",
		"CUP_launch_Igla"
		};
		magazines[]=
		{
		"CUP_30Rnd_545x39_AK_M",
		"CUP_30Rnd_545x39_AK_M",
		"CUP_30Rnd_545x39_AK_M",
		"CUP_30Rnd_545x39_AK_M",
		"CUP_30Rnd_545x39_AK_M",
		"ACE_PreloadedMissileDummy_Igla_CUP",
		"SmokeShell"
		};
		Respawnmagazines[]=
		{
		"CUP_30Rnd_545x39_AK_M",
		"CUP_30Rnd_545x39_AK_M",
		"CUP_30Rnd_545x39_AK_M",
		"CUP_30Rnd_545x39_AK_M",
		"CUP_30Rnd_545x39_AK_M",
		"ACE_PreloadedMissileDummy_Igla_CUP",
		"SmokeShell"
		};
		Items[]=
		{
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_morphine",
		"ACE_morphine"
		};
		respawntems[]=
		{
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_morphine",
		"ACE_morphine"
		};
	};