	class O_G_officer_F;
	class O_G_Soldier_F;
	class O_G_Soldier_LAT_F;
	class O_G_Soldier_GL_F;
	class O_G_Soldier_AR_F;
	
	class twc_greek_officer: O_G_officer_F
	{
		_generalMacro="Greek_Officer";
		scope=2;
		displayName="Officer";
		faction="greek_units";
		editorSubcategory = "Men_Greek";
		vehicleClass="Men_Greek";
		icon="iconManLeader";
		nakedUniform="U_BasicBody";
		uniformClass="U_OG_Guerilla2_3";
		backpack="";
		linkedItems[]=
		{
        "rhsgref_alice_webbing",
		"CUP_TK_NeckScarf",
		"ItemMap",
		"ItemCompass",
		"Binocular"
		};
		respawnLinkedItems[]=
		{
        "rhsgref_alice_webbing",
		"CUP_TK_NeckScarf",
		"ItemMap",
		"ItemCompass",
		"Binocular"
		};
		weapons[]=
		{
		"Throw",
		"Put",
		"CUP_hgun_SA61"
		};
		respawnweapons[]=
		{
		"Throw",
		"Put",
		"CUP_hgun_SA61"
		};
		magazines[]=
		{
		"CUP_20Rnd_B_765x17_Ball_M",
		"CUP_20Rnd_B_765x17_Ball_M",
		"CUP_20Rnd_B_765x17_Ball_M",
		"CUP_20Rnd_B_765x17_Ball_M",
		"CUP_20Rnd_B_765x17_Ball_M",
		"HandGrenade",
		"SmokeShell"
		};
		Respawnmagazines[]=
		{
		"CUP_20Rnd_B_765x17_Ball_M",
		"CUP_20Rnd_B_765x17_Ball_M",
		"CUP_20Rnd_B_765x17_Ball_M",
		"CUP_20Rnd_B_765x17_Ball_M",
		"CUP_20Rnd_B_765x17_Ball_M",
		"HandGrenade",
		"SmokeShell"
		};
		Items[]=
		{
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_morphine",
		"ACE_morphine"
		};
		respawntems[]=
		{
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_morphine",
		"ACE_morphine"
		};
	};
	class twc_greek_rifleman: O_G_Soldier_F
	{
		_generalMacro="Greek_Rifleman";
		scope=2;
		displayName="Rifleman";
		faction="greek_units";
		editorSubcategory = "Men_Greek";
		vehicleClass="Men_Greek";
		icon="iconManLeader";
		nakedUniform="U_BasicBody";
		uniformClass="rhsgref_uniform_dpm_olive";
		backpack="";
		linkedItems[]=
		{
        "rhsgref_alice_webbing",
		"CUP_TK_NeckScarf",
		"ItemMap",
		"ItemCompass",
		"Binocular"
		};
		respawnLinkedItems[]=
		{
        "rhsgref_alice_webbing",
		"CUP_TK_NeckScarf",
		"ItemMap",
		"ItemCompass",
		"Binocular"
		};
		weapons[]=
		{
		"Throw",
		"Put",
		"CUP_arifle_AK74"
		};
		respawnweapons[]=
		{
		"Throw",
		"Put",
		"CUP_arifle_AK74"
		};
		magazines[]=
		{
		"CUP_30Rnd_545x39_AK_M",
		"CUP_30Rnd_545x39_AK_M",
		"CUP_30Rnd_545x39_AK_M",
		"CUP_30Rnd_545x39_AK_M",
		"CUP_30Rnd_545x39_AK_M",
		"HandGrenade",
		"SmokeShell"
		};
		Respawnmagazines[]=
		{
		"CUP_30Rnd_545x39_AK_M",
		"CUP_30Rnd_545x39_AK_M",
		"CUP_30Rnd_545x39_AK_M",
		"CUP_30Rnd_545x39_AK_M",
		"CUP_30Rnd_545x39_AK_M",
		"HandGrenade",
		"SmokeShell"
		};
		Items[]=
		{
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_morphine",
		"ACE_morphine"
		};
		respawntems[]=
		{
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_morphine",
		"ACE_morphine"
		};
	};
	class twc_greek_rifleman_2: O_G_Soldier_F
	{
		_generalMacro="Greek_Rifleman_2";
		scope=2;
		displayName="Rifleman 2";
		faction="greek_units";
		editorSubcategory = "Men_Greek";
		vehicleClass="Men_Greek";
		icon="iconManLeader";
		nakedUniform="U_BasicBody";
		uniformClass="U_OG_Guerilla3_1";
		backpack="";
		linkedItems[]=
		{
        "CUP_V_O_Ins_Carrier_Rig",
		"G_Balaclava_blk",
		"ItemMap",
		"ItemCompass",
		"Binocular"
		};
		respawnLinkedItems[]=
		{
        "CUP_V_O_Ins_Carrier_Rig",
		"G_Balaclava_blk",
		"ItemMap",
		"ItemCompass",
		"Binocular"
		};
		weapons[]=
		{
		"Throw",
		"Put",
		"CUP_arifle_Sa58P",
		"CUP_launch_M72A6"
		};
		respawnweapons[]=
		{
		"Throw",
		"Put",
		"CUP_arifle_Sa58P",
		"CUP_launch_M72A6"
		};
		magazines[]=
		{
		"CUP_30Rnd_Sa58_M_TracerG",
		"CUP_30Rnd_Sa58_M_TracerG",
		"CUP_30Rnd_Sa58_M_TracerG",
		"CUP_30Rnd_Sa58_M_TracerG",
		"CUP_30Rnd_Sa58_M_TracerG",
		"SmokeShell"
		};
		Respawnmagazines[]=
		{
		"CUP_30Rnd_Sa58_M_TracerG",
		"CUP_30Rnd_Sa58_M_TracerG",
		"CUP_30Rnd_Sa58_M_TracerG",
		"CUP_30Rnd_Sa58_M_TracerG",
		"CUP_30Rnd_Sa58_M_TracerG",
		"SmokeShell"
		};
		Items[]=
		{
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_morphine",
		"ACE_morphine"
		};
		respawntems[]=
		{
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_morphine",
		"ACE_morphine"
		};
	};
	class twc_greek_rifleman_at: O_G_Soldier_LAT_F
	{
		_generalMacro="Greek_Rifleman_AT";
		scope=2;
		displayName="Rifleman AT";
		faction="greek_units";
		editorSubcategory = "Men_Greek";
		vehicleClass="Men_Greek";
		icon="iconManLeader";
		nakedUniform="U_BasicBody";
		uniformClass="U_OG_Guerrilla_6_1";
		backpack="greek_Backpack_AT";
		linkedItems[]=
		{
        "rhsgref_alice_webbing",
		"G_Balaclava_blk",
		"ItemMap",
		"ItemCompass",
		"Binocular"
		};
		respawnLinkedItems[]=
		{
        "rhsgref_alice_webbing",
		"G_Balaclava_blk",
		"ItemMap",
		"ItemCompass",
		"Binocular"
		};
		weapons[]=
		{
		"Throw",
		"Put",
		"CUP_arifle_M16A2",
		"CUP_launch_RPG7V"
		};
		respawnweapons[]=
		{
		"Throw",
		"Put",
		"CUP_arifle_M16A2",
		"CUP_launch_RPG7V"
		};
		magazines[]=
		{
		"CUP_30Rnd_556x45_Stanag",
		"CUP_30Rnd_556x45_Stanag",
		"CUP_30Rnd_556x45_Stanag",
		"CUP_30Rnd_556x45_Stanag",
		"CUP_30Rnd_556x45_Stanag",
		"CUP_PG7V_M",
		"HandGrenade",
		"SmokeShell"
		};
		Respawnmagazines[]=
		{
		"CUP_30Rnd_556x45_Stanag",
		"CUP_30Rnd_556x45_Stanag",
		"CUP_30Rnd_556x45_Stanag",
		"CUP_30Rnd_556x45_Stanag",
		"CUP_30Rnd_556x45_Stanag",
		"CUP_PG7V_M",
		"HandGrenade",
		"SmokeShell"
		};
		Items[]=
		{
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_morphine",
		"ACE_morphine"
		};
		respawntems[]=
		{
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_morphine",
		"ACE_morphine"
		};
	};
	class twc_greek_grenadier: O_G_Soldier_GL_F
	{
		_generalMacro="Greek_Grenadier";
		scope=2;
		displayName="Grenadier";
		faction="greek_units";
		editorSubcategory = "Men_Greek";
		vehicleClass="Men_Greek";
		icon="iconManLeader";
		nakedUniform="U_BasicBody";
		uniformClass="U_OG_Guerilla2_3";
		backpack="";
		linkedItems[]=
		{
        "CUP_V_O_Ins_Carrier_Rig",
		"G_Balaclava_blk",
		"ItemMap",
		"ItemCompass",
		"Binocular"
		};
		respawnLinkedItems[]=
		{
        "CUP_V_O_Ins_Carrier_Rig",
		"G_Balaclava_blk",
		"ItemMap",
		"ItemCompass",
		"Binocular"
		};
		weapons[]=
		{
		"Throw",
		"Put",
		"CUP_arifle_AK74_GL"
		};
		respawnweapons[]=
		{
		"Throw",
		"Put",
		"CUP_arifle_AK74_GL"
		};
		magazines[]=
		{
		"CUP_30Rnd_545x39_AK_M",
		"CUP_30Rnd_545x39_AK_M",
		"CUP_30Rnd_545x39_AK_M",
		"CUP_30Rnd_545x39_AK_M",
		"CUP_1Rnd_HE_GP25_M",
		"CUP_1Rnd_HE_GP25_M",
		"CUP_1Rnd_HE_GP25_M",
		"CUP_1Rnd_HE_GP25_M",
		"CUP_1Rnd_HE_GP25_M",
		"CUP_1Rnd_HE_GP25_M",
		"SmokeShell"
		};
		Respawnmagazines[]=
		{
		"CUP_30Rnd_545x39_AK_M",
		"CUP_30Rnd_545x39_AK_M",
		"CUP_30Rnd_545x39_AK_M",
		"CUP_30Rnd_545x39_AK_M",
		"CUP_1Rnd_HE_GP25_M",
		"CUP_1Rnd_HE_GP25_M",
		"CUP_1Rnd_HE_GP25_M",
		"CUP_1Rnd_HE_GP25_M",
		"CUP_1Rnd_HE_GP25_M",
		"CUP_1Rnd_HE_GP25_M",
		"SmokeShell"
		};
		Items[]=
		{
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_morphine",
		"ACE_morphine"
		};
		respawntems[]=
		{
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_morphine",
		"ACE_morphine"
		};
	};
	class twc_greek_ar: O_G_Soldier_AR_F
	{
		_generalMacro="Greek_AutomaticRifleman";
		scope=2;
		displayName="Automatic Rifleman";
		faction="greek_units";
		editorSubcategory = "Men_Greek";
		vehicleClass="Men_Greek";
		icon="iconManLeader";
		nakedUniform="U_BasicBody";
		uniformClass="U_OG_Guerilla2_1";
		backpack="";
		linkedItems[]=
		{
        "CUP_V_OI_TKI_Jacket1_04",
		"G_Balaclava_blk",
		"ItemMap",
		"ItemCompass",
		"Binocular"
		};
		respawnLinkedItems[]=
		{
        "CUP_V_OI_TKI_Jacket1_04",
		"G_Balaclava_blk",
		"ItemMap",
		"ItemCompass",
		"Binocular"
		};
		weapons[]=
		{
		"Throw",
		"Put",
		"CUP_arifle_RPK74"
		};
		respawnweapons[]=
		{
		"Throw",
		"Put",
		"CUP_arifle_RPK74"
		};
		magazines[]=
		{
		"CUP_75Rnd_TE4_LRT4_Green_Tracer_545x39_RPK_M",
		"CUP_75Rnd_TE4_LRT4_Green_Tracer_545x39_RPK_M",
		"SmokeShell"
		};
		Respawnmagazines[]=
		{
		"CUP_75Rnd_TE4_LRT4_Green_Tracer_545x39_RPK_M",
		"CUP_75Rnd_TE4_LRT4_Green_Tracer_545x39_RPK_M",
		"SmokeShell"
		};
		Items[]=
		{
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_morphine",
		"ACE_morphine"
		};
		respawntems[]=
		{
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_morphine",
		"ACE_morphine"
		};
	};
	class twc_greek_mg: O_G_Soldier_AR_F
	{
		_generalMacro="Greek_MachineGunner";
		scope=2;
		displayName="Machine Gunner";
		faction="greek_units";
		editorSubcategory = "Men_Greek";
		vehicleClass="Men_Greek";
		icon="iconManLeader";
		nakedUniform="U_BasicBody";
		uniformClass="rhsgref_uniform_altis_lizard_olive";
		backpack="UK3CB_BAF_B_Bergen_OLI_Rifleman_A";
		linkedItems[]=
		{
        "CUP_V_O_Ins_Carrier_Rig_MG",
		"CUP_TK_NeckScarf",
		"ItemMap",
		"ItemCompass",
		"Binocular"
		};
		respawnLinkedItems[]=
		{
        "CUP_V_O_Ins_Carrier_Rig_MG",
		"CUP_TK_NeckScarf",
		"ItemMap",
		"ItemCompass",
		"Binocular"
		};
		weapons[]=
		{
		"Throw",
		"Put",
		"CUP_lmg_UK59"
		};
		respawnweapons[]=
		{
		"Throw",
		"Put",
		"CUP_lmg_UK59"
		};
		magazines[]=
		{
		"CUP_50Rnd_UK59_762x54R_Tracer",
		"CUP_50Rnd_UK59_762x54R_Tracer",
		"CUP_50Rnd_UK59_762x54R_Tracer",
		"CUP_50Rnd_UK59_762x54R_Tracer",
		"CUP_50Rnd_UK59_762x54R_Tracer",
		"SmokeShell"
		};
		Respawnmagazines[]=
		{
		"CUP_50Rnd_UK59_762x54R_Tracer",
		"CUP_50Rnd_UK59_762x54R_Tracer",
		"CUP_50Rnd_UK59_762x54R_Tracer",
		"SmokeShell"
		};
		Items[]=
		{
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_morphine",
		"ACE_morphine"
		};
		respawntems[]=
		{
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_morphine",
		"ACE_morphine"
		};
	};
	class twc_greek_aa: O_G_Soldier_F
	{
		_generalMacro="Greek_AA";
		scope=2;
		displayName="Anti-Air";
		faction="greek_units";
		editorSubcategory = "Men_Greek";
		vehicleClass="Men_Greek";
		icon="iconManLeader";
		nakedUniform="U_BasicBody";
		uniformClass="rhs_uniform_gorka_r_g";
		backpack="UK3CB_BAF_B_Bergen_OLI_Rifleman_A";
		linkedItems[]=
		{
		"G_Balaclava_blk",
		"ItemMap",
		"ItemCompass",
		"Binocular"
		};
		respawnLinkedItems[]=
		{
        "CUP_V_O_Ins_Carrier_Rig",
		"G_Balaclava_blk",
		"ItemMap",
		"ItemCompass",
		"Binocular"
		};
		weapons[]=
		{
		"Throw",
		"Put",
		"CUP_arifle_AK74",
		"CUP_launch_Igla"
		};
		respawnweapons[]=
		{
		"Throw",
		"Put",
		"CUP_arifle_AK74",
		"CUP_launch_Igla"
		};
		magazines[]=
		{
		"CUP_30Rnd_545x39_AK_M",
		"CUP_30Rnd_545x39_AK_M",
		"CUP_30Rnd_545x39_AK_M",
		"CUP_30Rnd_545x39_AK_M",
		"CUP_30Rnd_545x39_AK_M",
		"ACE_PreloadedMissileDummy_Igla_CUP",
		"SmokeShell"
		};
		Respawnmagazines[]=
		{
		"CUP_30Rnd_545x39_AK_M",
		"CUP_30Rnd_545x39_AK_M",
		"CUP_30Rnd_545x39_AK_M",
		"CUP_30Rnd_545x39_AK_M",
		"CUP_30Rnd_545x39_AK_M",
		"ACE_PreloadedMissileDummy_Igla_CUP",
		"SmokeShell"
		};
		Items[]=
		{
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_morphine",
		"ACE_morphine"
		};
		respawntems[]=
		{
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_morphine",
		"ACE_morphine"
		};
	};
	
	class twc_greek_heavy: O_G_Soldier_F
	{
		class eventhandlers {
		};
		_generalMacro="Greek_Heavy";
		scope=2;
		displayName="Heavy Rifleman";
		faction="greek_units";
		editorSubcategory = "Men_Greek";
		vehicleClass="Men_Greek";
		icon="iconManLeader";
		nakedUniform="U_BasicBody";
		uniformClass="rhsgref_uniform_olive";
		backpack="";
		linkedItems[]=
		{
        "CUP_V_I_RACS_Carrier_Vest_wdl",
		"rhs_altyn_visordown",
		"G_Bandanna_blk",
		"ItemMap",
		"ItemCompass",
		"Binocular"
		};
		respawnLinkedItems[]=
		{
        "CUP_V_I_RACS_Carrier_Vest_wdl",
		"G_Bandanna_blk",
		"ItemMap",
		"ItemCompass",
		"rhs_altyn_visordown",
		"Binocular"
		};
		weapons[]=
		{
		"Throw",
		"Put",
		"rhs_weap_ak74m_2mag",
		"rhs_weap_makarov_pm"
		};
		respawnweapons[]=
		{
		"Throw",
		"Put",
		"rhs_weap_ak74m_2mag",
		"rhs_weap_makarov_pm"
		};
		magazines[]=
		{
		"rhs_30Rnd_545x39_AK",
		"rhs_30Rnd_545x39_AK",
		"rhs_30Rnd_545x39_AK",
		"rhs_30Rnd_545x39_AK",
		"rhs_30Rnd_545x39_AK",
		"rhs_mag_9x18_8_57N181S",
		"rhs_mag_9x18_8_57N181S",
		"rhs_mag_9x18_8_57N181S",
		"SmokeShell"
		};
		Respawnmagazines[]=
		{
		"rhs_30Rnd_545x39_AK",
		"rhs_30Rnd_545x39_AK",
		"rhs_30Rnd_545x39_AK",
		"rhs_30Rnd_545x39_AK",
		"rhs_30Rnd_545x39_AK",
		"rhs_mag_9x18_8_57N181S",
		"rhs_mag_9x18_8_57N181S",
		"rhs_mag_9x18_8_57N181S",
		"SmokeShell"
		};
		Items[]=
		{
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_morphine",
		"ACE_morphine"
		};
		respawntems[]=
		{
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_morphine",
		"ACE_morphine"
		
		};

	

	};
	
		class twc_greek_rifleman_fal: O_G_Soldier_LAT_F
	{
		_generalMacro="Greek_Rifleman_FAL";
		scope=2;
		displayName="Rifleman FAL";
		faction="greek_units";
		editorSubcategory = "Men_Greek";
		vehicleClass="Men_Greek";
		icon="iconManLeader";
		nakedUniform="U_BasicBody";
		uniformClass="rhsgref_uniform_dpm_olive";
		backpack="";
		linkedItems[]=
		{
        "CUP_V_I_Guerilla_Jacket",
		"ItemMap",
		"ItemCompass",
		"Binocular"
		};
		respawnLinkedItems[]=
		{
        "CUP_V_I_Guerilla_Jacket",
		"ItemMap",
		"ItemCompass",
		"Binocular"
		};
		weapons[]=
		{
		"Throw",
		"Put",
		"CUP_arifle_FNFAL"
		};
		respawnweapons[]=
		{
		"Throw",
		"Put",
		"CUP_arifle_FNFAL"
		};
		magazines[]=
		{
		"CUP_20Rnd_762x51_FNFAL_M",
		"CUP_20Rnd_762x51_FNFAL_M",
		"CUP_20Rnd_762x51_FNFAL_M",
		"CUP_20Rnd_762x51_FNFAL_M",
		"CUP_20Rnd_762x51_FNFAL_M",
		"HandGrenade",
		"SmokeShell"
		};
		Respawnmagazines[]=
		{
		"CUP_20Rnd_762x51_FNFAL_M",
		"CUP_20Rnd_762x51_FNFAL_M",
		"CUP_20Rnd_762x51_FNFAL_M",
		"CUP_20Rnd_762x51_FNFAL_M",
		"CUP_20Rnd_762x51_FNFAL_M",
		"HandGrenade",
		"SmokeShell"
		};
		Items[]=
		{
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_morphine",
		"ACE_morphine"
		};
		respawntems[]=
		{
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_morphine",
		"ACE_morphine"
		};
	};
	
	class twc_greek_farmer: O_G_Soldier_LAT_F
	{
		_generalMacro="Greek_farmer";
		scope=2;
		displayName="Farmer";
		faction="greek_units";
		editorSubcategory = "Men_Greek";
		vehicleClass="Men_Greek";
		icon="iconManLeader";
		nakedUniform="U_BasicBody";
		uniformClass="U_OG_Guerilla3_1";
		backpack="";
		linkedItems[]=
		{
        "H_Hat_Safari_olive_F",
		"ItemMap",
		"ItemCompass",
		"Binocular"
		};
		respawnLinkedItems[]=
		{
        "H_Hat_Safari_olive_F",
		"ItemMap",
		"ItemCompass",
		"Binocular"
		};
		weapons[]=
		{
		"Throw",
		"Put",
		"rhs_weap_m38"
		};
		respawnweapons[]=
		{
		"Throw",
		"Put",
		"rhs_weap_m38"
		};
		magazines[]=
		{
		"rhsgref_5Rnd_762x54_m38",
		"rhsgref_5Rnd_762x54_m38",
		"rhsgref_5Rnd_762x54_m38",
		"rhsgref_5Rnd_762x54_m38",
		"rhsgref_5Rnd_762x54_m38",
		"HandGrenade",
		"SmokeShell"
		};
		Respawnmagazines[]=
		{
		"rhsgref_5Rnd_762x54_m38",
		"rhsgref_5Rnd_762x54_m38",
		"rhsgref_5Rnd_762x54_m38",
		"rhsgref_5Rnd_762x54_m38",
		"rhsgref_5Rnd_762x54_m38",
		"HandGrenade",
		"SmokeShell"
		};
		Items[]=
		{
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_morphine",
		"ACE_morphine"
		};
		respawntems[]=
		{
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_morphine",
		"ACE_morphine"
		};
	};
	
class twc_greek_at2: O_G_Soldier_LAT_F
	{
		_generalMacro="Greek_at2";
		scope=2;
		displayName="Rifleman AT (OG-7)";
		faction="greek_units";
		editorSubcategory = "Men_Greek";
		vehicleClass="Men_Greek";
		icon="iconManLeader";
		nakedUniform="U_BasicBody";
		uniformClass="U_OG_Guerilla2_1";
		backpack="Backpack_AT_og7";
		linkedItems[]=
		{
		"ItemMap",
		"ItemCompass",
		"Binocular"
		};
		respawnLinkedItems[]=
		{
		"ItemMap",
		"ItemCompass",
		"Binocular"
		};
		weapons[]=
		{
		"Throw",
		"Put",
		"rhs_weap_pm63",
		"CUP_launch_RPG7V"
		};
		respawnweapons[]=
		{
		"Throw",
		"Put",
		"rhs_weap_pm63",
		"CUP_launch_RPG7V"
		};
		magazines[]=
		{
		"rhs_30Rnd_762x39mm",
		"rhs_30Rnd_762x39mm",
		"rhs_30Rnd_762x39mm",
		"rhs_30Rnd_762x39mm",
		"rhs_30Rnd_762x39mm",
		"HandGrenade",
		"CUP_OG7_M",
		"SmokeShell"
		};
		Respawnmagazines[]=
		{
		"rhs_30Rnd_762x39mm",
		"rhs_30Rnd_762x39mm",
		"rhs_30Rnd_762x39mm",
		"rhs_30Rnd_762x39mm",
		"rhs_30Rnd_762x39mm",
		"HandGrenade",
		"CUP_OG7_M",
		"SmokeShell"
		};
		Items[]=
		{
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_morphine",
		"ACE_morphine"
		};
		respawntems[]=
		{
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_morphine",
		"ACE_morphine"
		};
	};
	

class twc_greek_smg: O_G_Soldier_LAT_F
	{
		_generalMacro="Greek_smg";
		scope=2;
		displayName="Assaulter SMG";
		faction="greek_units";
		editorSubcategory = "Men_Greek";
		vehicleClass="Men_Greek";
		icon="iconManLeader";
		nakedUniform="U_BasicBody";
		uniformClass="U_OG_Guerilla2_3";
		backpack="";
		linkedItems[]=
		{
		"ItemMap",
		"ItemCompass",
		"Binocular"
		};
		respawnLinkedItems[]=
		{
		"ItemMap",
		"ItemCompass",
		"Binocular"
		};
		weapons[]=
		{
		"Throw",
		"Put",
		"CUP_smg_MP5A5"
		};
		respawnweapons[]=
		{
		"Throw",
		"Put",
		"CUP_smg_MP5A5"
		};
		magazines[]=
		{
		"CUP_30Rnd_9x19_MP5",
		"CUP_30Rnd_9x19_MP5",
		"CUP_30Rnd_9x19_MP5",
		"CUP_30Rnd_9x19_MP5",
		"CUP_30Rnd_9x19_MP5",
		"HandGrenade",
		"CUP_OG7_M",
		"SmokeShell"
		};
		Respawnmagazines[]=
		{
		"CUP_30Rnd_9x19_MP5",
		"CUP_30Rnd_9x19_MP5",
		"CUP_30Rnd_9x19_MP5",
		"CUP_30Rnd_9x19_MP5",
		"CUP_30Rnd_9x19_MP5",
		"HandGrenade",
		"CUP_OG7_M",
		"SmokeShell"
		};
		Items[]=
		{
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_morphine",
		"ACE_morphine"
		};
		respawntems[]=
		{
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_morphine",
		"ACE_morphine"
		};
	};
	

class twc_greek_sniper: O_G_Soldier_LAT_F
	{
			class eventhandlers {
		};
		_generalMacro="Greek_sniper";
		scope=2;
		displayName="Sniper";
		faction="greek_units";
		editorSubcategory = "Men_Greek";
		vehicleClass="Men_Greek";
		icon="iconManLeader";
		nakedUniform="U_BasicBody";
		uniformClass="rhsgref_uniform_dpm_olive";
		backpack="";
		linkedItems[]=
		{
		"ItemMap",
		"ItemCompass",
		"H_Shemag_olive",
		"Binocular"
		};
		respawnLinkedItems[]=
		{
		"ItemMap",
		"ItemCompass",
		"H_Shemag_olive",
		"Binocular"
		};
		weapons[]=
		{
		"Throw",
		"Put",
		"CUP_srifle_M24_wdl_LeupoldMk4LRT"
		};
		respawnweapons[]=
		{
		"Throw",
		"Put",
		"CUP_srifle_M24_wdl_LeupoldMk4LRT"
		};
		magazines[]=
		{
		"CUP_5Rnd_762x51_M24",
		"CUP_5Rnd_762x51_M24",
		"CUP_5Rnd_762x51_M24",
		"CUP_5Rnd_762x51_M24",
		"CUP_5Rnd_762x51_M24",
		"CUP_5Rnd_762x51_M24",
		"HandGrenade",
		"SmokeShell"
		};
		Respawnmagazines[]=
		{
		"CUP_5Rnd_762x51_M24",
		"CUP_5Rnd_762x51_M24",
		"CUP_5Rnd_762x51_M24",
		"CUP_5Rnd_762x51_M24",
		"CUP_5Rnd_762x51_M24",
		"CUP_5Rnd_762x51_M24",
		"HandGrenade",
		"SmokeShell"
		};
		Items[]=
		{
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_morphine",
		"ACE_morphine"
		};
		respawntems[]=
		{
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_morphine",
		"ACE_morphine"
		};
	};
	
