//Woodland
class UK3CB_BAF_B_Bergen_DPMW_SL_A;
class UK3CB_BAF_B_Bergen_DPMW_Rifleman_A;
class UK3CB_BAF_B_Bergen_DPMW_Rifleman_B;
class UK3CB_BAF_B_Bergen_DPMW_JTAC_H_A;

//Desert
class UK3CB_BAF_B_Bergen_DDPM_SL_A;
class UK3CB_BAF_B_Bergen_DDPM_Rifleman_A;
class UK3CB_BAF_B_Bergen_DDPM_Rifleman_B;
class UK3CB_BAF_B_Bergen_DDPM_JTAC_H_A;

//Arctic
class UK3CB_BAF_B_Bergen_Arctic_SL_A;
class UK3CB_BAF_B_Bergen_Arctic_Rifleman_A;
class UK3CB_BAF_B_Bergen_Arctic_Rifleman_B;
class UK3CB_BAF_B_Bergen_Arctic_JTAC_H_A;

//