//REGULAR, DISMOUNTED, Arctic
//Section
class TWC_Infantry_1990_Regular_Dismounted_Arctic_Rifleman: TWC_Infantry_1990_Regular_Arctic_Rifleman
{
	CATEGORY(TWC_Infantry_Dismounted_Arctic)
	backpack = "TWC_Backpack_1990_Regular_Dismounted_Arctic_Rifleman";
};
class TWC_Infantry_1990_Regular_Dismounted_Arctic_AT: TWC_Infantry_1990_Regular_Arctic_AT
{
	CATEGORY(TWC_Infantry_Dismounted_Arctic)
	backpack = "TWC_Backpack_1990_Regular_Dismounted_Arctic_AT";
};
class TWC_Infantry_1990_Regular_Dismounted_Arctic_Gunner: TWC_Infantry_1990_Regular_Arctic_Gunner
{
	CATEGORY(TWC_Infantry_Dismounted_Arctic)
	backpack = "TWC_Backpack_1990_Regular_Dismounted_Arctic_Gunner";
};
class TWC_Infantry_1990_Regular_Dismounted_Arctic_SectionCommander: TWC_Infantry_1990_Regular_Arctic_SectionCommander
{
	CATEGORY(TWC_Infantry_Dismounted_Arctic)
	backpack = "TWC_Backpack_1990_Regular_Dismounted_Arctic_SectionCommander";
};
class TWC_Infantry_1990_Regular_Dismounted_Arctic_2iC: TWC_Infantry_1990_Regular_Arctic_2iC
{
	CATEGORY(TWC_Infantry_Dismounted_Arctic)
	backpack = "TWC_Backpack_1990_Regular_Dismounted_Arctic_2iC";
};

//Platoon Command
class TWC_Infantry_1990_Regular_Dismounted_Arctic_Platoon_Commander: TWC_Infantry_1990_Regular_Arctic_Platoon_Commander
{
	CATEGORY(TWC_Infantry_Dismounted_Arctic)
	backpack = "TWC_Backpack_1990_Regular_Dismounted_Arctic_Platoon_Commander";
};
class TWC_Infantry_1990_Regular_Dismounted_Arctic_Platoon_Sergeant: TWC_Infantry_1990_Regular_Arctic_Platoon_Sergeant
{
	CATEGORY(TWC_Infantry_Dismounted_Arctic)
	backpack = "TWC_Backpack_1990_Regular_Dismounted_Arctic_Platoon_Sergeant";
};
class TWC_Infantry_1990_Regular_Dismounted_Arctic_Platoon_Medic: TWC_Infantry_1990_Regular_Arctic_Platoon_Medic
{
	CATEGORY(TWC_Infantry_Dismounted_Arctic)
	backpack = "TWC_Backpack_1990_Regular_Dismounted_Arctic_Platoon_Medic";
};
class TWC_Infantry_1990_Regular_Dismounted_Arctic_Platoon_CSM: TWC_Infantry_1990_Regular_Arctic_Platoon_CSM
{
	CATEGORY(TWC_Infantry_Dismounted_Arctic)
	backpack = "TWC_Backpack_1990_Regular_Dismounted_Arctic_Platoon_Sergeant";
};

//Company
class TWC_Infantry_1990_Regular_Dismounted_Arctic_Company_Commander: TWC_Infantry_1990_Regular_Arctic_Company_Commander
{
	CATEGORY(TWC_Infantry_Dismounted_Arctic)
	backpack = "TWC_Backpack_1990_Regular_Dismounted_Arctic_Platoon_Commander";
};
class TWC_Infantry_1990_Regular_Dismounted_Arctic_Company_2iC: TWC_Infantry_1990_Regular_Arctic_Company_2iC
{
	CATEGORY(TWC_Infantry_Dismounted_Arctic)
	backpack = "TWC_Backpack_1990_Regular_Dismounted_Arctic_Platoon_Commander";
};
class TWC_Infantry_1990_Regular_Dismounted_Arctic_Company_Sergeant: TWC_Infantry_1990_Regular_Arctic_Company_Sergeant
{
	CATEGORY(TWC_Infantry_Dismounted_Arctic)
	backpack = "TWC_Backpack_1990_Regular_Dismounted_Arctic_Platoon_Sergeant";
};