//REGULAR, DISMOUNTED, WOODLAND
//Section
class TWC_Infantry_1990_Regular_Dismounted_Woodland_Rifleman: TWC_Infantry_1990_Regular_Woodland_Rifleman
{
	CATEGORY(TWC_Infantry_Dismounted_Woodland)
	backpack = "TWC_Backpack_1990_Regular_Dismounted_Woodland_Rifleman";
};
class TWC_Infantry_1990_Regular_Dismounted_Woodland_AT: TWC_Infantry_1990_Regular_Woodland_AT
{
	CATEGORY(TWC_Infantry_Dismounted_Woodland)
	backpack = "TWC_Backpack_1990_Regular_Dismounted_Woodland_AT";
};
class TWC_Infantry_1990_Regular_Dismounted_Woodland_Gunner: TWC_Infantry_1990_Regular_Woodland_Gunner
{
	CATEGORY(TWC_Infantry_Dismounted_Woodland)
	backpack = "TWC_Backpack_1990_Regular_Dismounted_Woodland_Gunner";
};
class TWC_Infantry_1990_Regular_Dismounted_Woodland_SectionCommander: TWC_Infantry_1990_Regular_Woodland_SectionCommander
{
	CATEGORY(TWC_Infantry_Dismounted_Woodland)
	backpack = "TWC_Backpack_1990_Regular_Dismounted_Woodland_SectionCommander";
};
class TWC_Infantry_1990_Regular_Dismounted_Woodland_2iC: TWC_Infantry_1990_Regular_Woodland_2iC
{
	CATEGORY(TWC_Infantry_Dismounted_Woodland)
	backpack = "TWC_Backpack_1990_Regular_Dismounted_Woodland_2iC";
};
class TWC_Infantry_1990_Regular_Dismounted_Woodland_MG: TWC_Infantry_1990_Regular_Woodland_MG
{
	CATEGORY(TWC_Infantry_Dismounted_Woodland)
	backpack = "TWC_Backpack_1990_Regular_Dismounted_Woodland_MG";
};
class TWC_Infantry_1990_Regular_Dismounted_Woodland_ASSMG: TWC_Infantry_1990_Regular_Woodland_ASSMG
{
	CATEGORY(TWC_Infantry_Dismounted_Woodland)
	backpack = "TWC_Backpack_1990_Regular_Dismounted_Woodland_ASSMG";
};

//Platoon Command
class TWC_Infantry_1990_Regular_Dismounted_Woodland_Platoon_Commander: TWC_Infantry_1990_Regular_Woodland_Platoon_Commander
{
	CATEGORY(TWC_Infantry_Dismounted_Woodland)
	backpack = "TWC_Backpack_1990_Regular_Dismounted_Woodland_Platoon_Commander";
};
class TWC_Infantry_1990_Regular_Dismounted_Woodland_Platoon_Sergeant: TWC_Infantry_1990_Regular_Woodland_Platoon_Sergeant
{
	CATEGORY(TWC_Infantry_Dismounted_Woodland)
	backpack = "TWC_Backpack_1990_Regular_Dismounted_Woodland_Platoon_Sergeant";
};
class TWC_Infantry_1990_Regular_Dismounted_Woodland_Platoon_Medic: TWC_Infantry_1990_Regular_Woodland_Platoon_Medic
{
	CATEGORY(TWC_Infantry_Dismounted_Woodland)
	backpack = "TWC_Backpack_1990_Regular_Dismounted_Woodland_Platoon_Medic";
};
class TWC_Infantry_1990_Regular_Dismounted_Woodland_Platoon_CSM: TWC_Infantry_1990_Regular_Woodland_Platoon_CSM
{
	CATEGORY(TWC_Infantry_Dismounted_Woodland)
	backpack = "TWC_Backpack_1990_Regular_Dismounted_Woodland_Platoon_Sergeant";
};

//Company
class TWC_Infantry_1990_Regular_Dismounted_Woodland_Company_Commander: TWC_Infantry_1990_Regular_Woodland_Company_Commander
{
	CATEGORY(TWC_Infantry_Dismounted_Woodland)
	backpack = "TWC_Backpack_1990_Regular_Dismounted_Woodland_Platoon_Commander";
};
class TWC_Infantry_1990_Regular_Dismounted_Woodland_Company_2iC: TWC_Infantry_1990_Regular_Woodland_Company_2iC
{
	CATEGORY(TWC_Infantry_Dismounted_Woodland)
	backpack = "TWC_Backpack_1990_Regular_Dismounted_Woodland_Platoon_Commander";
};
class TWC_Infantry_1990_Regular_Dismounted_Woodland_Company_Sergeant: TWC_Infantry_1990_Regular_Woodland_Company_Sergeant
{
	CATEGORY(TWC_Infantry_Dismounted_Woodland)
	backpack = "TWC_Backpack_1990_Regular_Dismounted_Woodland_Platoon_Sergeant";
};