	class usa_1970_medic: B_Soldier_base_F
	{
		_generalMacro="usa_1970_medic";
		scope=2;
		displayName="Parajumper Medic";
		faction="twc_faction";
		editorSubCategory = "TWC_usa_1970";
		vehicleClass="TWC_usa_1970";
		icon="iconMan";
		nakedUniform="U_BasicBody";
		uniformClass="CUP_U_O_TK_Green";
		backpack="usa_1970_medic_backpack";
		linkedItems[]=
		{
        "CUP_V_O_Ins_Carrier_Rig_Com",
		"CUP_H_USArmy_Helmet_M1_Olive",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
		};
		respawnLinkedItems[]=
		{
        "CUP_V_O_Ins_Carrier_Rig_Com",
		"CUP_H_USArmy_Helmet_M1_Olive",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
		};
		weapons[]=
		{
		"Throw",
		"Put",	
		"CUP_arifle_M16A2"
		};
		respawnweapons[]=
		{
		"Throw",
		"Put",	
		"CUP_arifle_M16A2"
		};
		magazines[]=
		{
		"CUP_20Rnd_556x45_Stanag",
		"CUP_20Rnd_556x45_Stanag",
		"CUP_20Rnd_556x45_Stanag",
		"CUP_20Rnd_556x45_Stanag",
		"CUP_20Rnd_556x45_Stanag",
		"CUP_20Rnd_556x45_Stanag",
		"CUP_20Rnd_556x45_Stanag",
		"CUP_20Rnd_556x45_Stanag",
		"CUP_20Rnd_556x45_Stanag",
		"CUP_20Rnd_556x45_Stanag",
		"CUP_HandGrenade_M67",
		"CUP_HandGrenade_M67"
		};
		Respawnmagazines[]=
		{
		"CUP_20Rnd_556x45_Stanag",
		"CUP_20Rnd_556x45_Stanag",
		"CUP_20Rnd_556x45_Stanag",
		"CUP_20Rnd_556x45_Stanag",
		"CUP_20Rnd_556x45_Stanag",
		"CUP_20Rnd_556x45_Stanag",
		"CUP_20Rnd_556x45_Stanag",
		"CUP_20Rnd_556x45_Stanag",
		"CUP_20Rnd_556x45_Stanag",
		"CUP_20Rnd_556x45_Stanag",
		"CUP_HandGrenade_M67",
		"CUP_HandGrenade_M67"
		};
		Items[]=
		{
		"ACE_EarPlugs",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_morphine",
		"ACE_morphine",
		"ACE_epinephrine",
		"ACE_tourniquet"
		};
		respawntems[]=
		{
		"ACE_EarPlugs",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_morphine",
		"ACE_morphine",
		"ACE_epinephrine",
		"ACE_tourniquet"			
		};		
	};
	class usa_1970_leader: B_Soldier_base_F
	{
		_generalMacro="usa_1970_leader";
		scope=2;
		displayName="Parajumper Leader";
		faction="twc_faction";
		editorSubCategory = "TWC_usa_1970";
		vehicleClass="TWC_usa_1970";
		icon="iconMan";
		nakedUniform="U_BasicBody";
		uniformClass="CUP_U_O_TK_Green";
		backpack="usa_1970_leader_backpack";
		linkedItems[]=
		{
        "CUP_V_O_Ins_Carrier_Rig_Com",
		"CUP_H_USArmy_Helmet_M1_Olive",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
		};
		respawnLinkedItems[]=
		{
        "CUP_V_O_Ins_Carrier_Rig_Com",
		"CUP_H_USArmy_Helmet_M1_Olive",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
		};
		weapons[]=
		{
		"Throw",
		"Put",	
		"CUP_arifle_M16A2"
		};
		respawnweapons[]=
		{
		"Throw",
		"Put",	
		"CUP_arifle_M16A2"
		};
		magazines[]=
		{
		"CUP_20Rnd_556x45_Stanag",
		"CUP_20Rnd_556x45_Stanag",
		"CUP_20Rnd_556x45_Stanag",
		"CUP_20Rnd_556x45_Stanag",
		"CUP_20Rnd_556x45_Stanag",
		"CUP_20Rnd_556x45_Stanag",
		"CUP_20Rnd_556x45_Stanag",
		"CUP_20Rnd_556x45_Stanag",
		"CUP_20Rnd_556x45_Stanag",
		"CUP_20Rnd_556x45_Stanag",
		"CUP_HandGrenade_M67",
		"CUP_HandGrenade_M67"
		};
		Respawnmagazines[]=
		{
		"CUP_20Rnd_556x45_Stanag",
		"CUP_20Rnd_556x45_Stanag",
		"CUP_20Rnd_556x45_Stanag",
		"CUP_20Rnd_556x45_Stanag",
		"CUP_20Rnd_556x45_Stanag",
		"CUP_20Rnd_556x45_Stanag",
		"CUP_20Rnd_556x45_Stanag",
		"CUP_20Rnd_556x45_Stanag",
		"CUP_20Rnd_556x45_Stanag",
		"CUP_20Rnd_556x45_Stanag",
		"CUP_HandGrenade_M67",
		"CUP_HandGrenade_M67"
		};
		Items[]=
		{
		"ACE_EarPlugs",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_morphine",
		"ACE_morphine",
		"ACE_epinephrine",
		"ACE_tourniquet"
		};
		respawntems[]=
		{
		"ACE_EarPlugs",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_morphine",
		"ACE_morphine",
		"ACE_epinephrine",
		"ACE_tourniquet"			
		};		
	};
	class usa_1970_grenadier: B_Soldier_base_F
	{
		_generalMacro="usa_1970_grenadier";
		scope=2;
		displayName="Parajumper Grenadier";
		faction="twc_faction";
		editorSubCategory = "TWC_usa_1970";
		vehicleClass="TWC_usa_1970";
		icon="iconMan";
		nakedUniform="U_BasicBody";
		uniformClass="CUP_U_O_TK_Green";
		backpack="usa_1970_grenadier_backpack";
		linkedItems[]=
		{
        "CUP_V_O_Ins_Carrier_Rig_Com",
		"CUP_H_USArmy_Helmet_M1_Olive",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
		};
		respawnLinkedItems[]=
		{
        "CUP_V_O_Ins_Carrier_Rig_Com",
		"CUP_H_USArmy_Helmet_M1_Olive",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
		};
		weapons[]=
		{
		"Throw",
		"Put",	
		"CUP_arifle_M16A2_GL"
		};
		respawnweapons[]=
		{
		"Throw",
		"Put",	
		"CUP_arifle_M16A2_GL"
		};
		magazines[]=
		{
		"CUP_20Rnd_556x45_Stanag",
		"CUP_20Rnd_556x45_Stanag",
		"CUP_20Rnd_556x45_Stanag",
		"CUP_20Rnd_556x45_Stanag",
		"CUP_20Rnd_556x45_Stanag",
		"CUP_20Rnd_556x45_Stanag",
		"CUP_20Rnd_556x45_Stanag",
		"CUP_20Rnd_556x45_Stanag",
		"CUP_20Rnd_556x45_Stanag",
		"CUP_20Rnd_556x45_Stanag",
		"CUP_HandGrenade_M67",
		"CUP_HandGrenade_M67"
		};
		Respawnmagazines[]=
		{
		"CUP_20Rnd_556x45_Stanag",
		"CUP_20Rnd_556x45_Stanag",
		"CUP_20Rnd_556x45_Stanag",
		"CUP_20Rnd_556x45_Stanag",
		"CUP_20Rnd_556x45_Stanag",
		"CUP_20Rnd_556x45_Stanag",
		"CUP_20Rnd_556x45_Stanag",
		"CUP_20Rnd_556x45_Stanag",
		"CUP_20Rnd_556x45_Stanag",
		"CUP_20Rnd_556x45_Stanag",
		"CUP_HandGrenade_M67",
		"CUP_HandGrenade_M67"
		};
		Items[]=
		{
		"ACE_EarPlugs",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_morphine",
		"ACE_morphine",
		"ACE_epinephrine",
		"ACE_tourniquet"
		};
		respawntems[]=
		{
		"ACE_EarPlugs",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_morphine",
		"ACE_morphine",
		"ACE_epinephrine",
		"ACE_tourniquet"			
		};		
	};
	class usa_1970_pilot: B_Soldier_base_F
	{
		_generalMacro="usa_1970_pilot";
		scope=2;
		displayName="Parajumper Pilot";
		faction="twc_faction";
		editorSubCategory = "TWC_usa_1970";
		vehicleClass="TWC_usa_1970";
		icon="iconMan";
		nakedUniform="U_BasicBody";
		uniformClass="CUP_U_O_TK_Green";
		backpack="usa_1970_leader_backpack";
		linkedItems[]=
		{
        "CUP_V_O_TK_OfficerBelt",
		"CUP_H_TK_PilotHelmet",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
		};
		respawnLinkedItems[]=
		{
        "CUP_V_O_TK_OfficerBelt",
		"CUP_H_TK_PilotHelmet",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
		};
		weapons[]=
		{
		"Throw",
		"Put",	
		"CUP_hgun_Colt1911"
		};
		respawnweapons[]=
		{
		"Throw",
		"Put",	
		"CUP_hgun_Colt1911"
		};
		magazines[]=
		{
		"CUP_7Rnd_45ACP_1911",
		"CUP_7Rnd_45ACP_1911",
		"CUP_7Rnd_45ACP_1911",
		"CUP_7Rnd_45ACP_1911",
		"SmokeShellPurple",
		"SmokeShellPurple",
		"SmokeShellPurple",
		"SmokeShellPurple"
		};
		Respawnmagazines[]=
		{
		"CUP_7Rnd_45ACP_1911",
		"CUP_7Rnd_45ACP_1911",
		"CUP_7Rnd_45ACP_1911",
		"CUP_7Rnd_45ACP_1911",
		"SmokeShellPurple",
		"SmokeShellPurple",
		"SmokeShellPurple",
		"SmokeShellPurple"
		};
		Items[]=
		{
		"ACE_EarPlugs",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_morphine",
		"ACE_morphine",
		"ACE_epinephrine",
		"ACE_tourniquet"
		};
		respawntems[]=
		{
		"ACE_EarPlugs",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_morphine",
		"ACE_morphine",
		"ACE_epinephrine",
		"ACE_tourniquet"			
		};		
	};