//REGULAR, DISMOUNTED, DESERT
//Section
class TWC_Infantry_ColdWar_Regular_Dismounted_Desert_Rifleman:TWC_Infantry_ColdWar_Regular_Desert_Rifleman
class TWC_Infantry_ColdWar_Regular_Dismounted_Desert_Rifleman_SUIT: TWC_Infantry_ColdWar_Regular_Desert_Rifleman_SUIT
class TWC_Infantry_ColdWar_Regular_Dismounted_Desert_SectionCommander: TWC_Infantry_ColdWar_Regular_Desert_SectionCommander
class TWC_Infantry_ColdWar_Regular_Dismounted_Desert_2iC: TWC_Infantry_ColdWar_Regular_Desert_2iC
class TWC_Infantry_ColdWar_Regular_Dismounted_Desert_AT: TWC_Infantry_ColdWar_Regular_Desert_AT
class TWC_Infantry_ColdWar_Regular_Dismounted_Desert_ASSAT: TWC_Infantry_ColdWar_Regular_Desert_ASSAT
class TWC_Infantry_ColdWar_Regular_Dismounted_Desert_MG: TWC_Infantry_ColdWar_Regular_Desert_MG
class TWC_Infantry_ColdWar_Regular_Dismounted_Desert_ASSMG: TWC_Infantry_ColdWar_Regular_Desert_ASSMG

//Platoon Command
class TWC_Infantry_ColdWar_Regular_Dismounted_Desert_Platoon_Commander: TWC_Infantry_ColdWar_Regular_Desert_Platoon_Commander
class TWC_Infantry_ColdWar_Regular_Dismounted_Desert_Platoon_Sergeant: TWC_Infantry_ColdWar_Regular_Desert_Platoon_Sergeant
class TWC_Infantry_ColdWar_Regular_Dismounted_Desert_Platoon_Medic: TWC_Infantry_ColdWar_Regular_Desert_Platoon_Medic
class TWC_Infantry_ColdWar_Regular_Dismounted_Desert_CSM: TWC_Infantry_ColdWar_Regular_Desert_CSM