//REGULAR, DISMOUNTED, WOODLAND
//Section
class TWC_Infantry_ColdWar_Regular_Dismounted_Woodland_Rifleman: TWC_Infantry_ColdWar_Regular_Woodland_Rifleman
{
	CATEGORY(TWC_Infantry_Dismounted_Woodland)
	backpack = "TWC_Backpack_ColdWar_Regular_Dismounted_Rifleman";
};
class TWC_Infantry_ColdWar_Regular_Dismounted_Woodland_Rifleman_SUIT: TWC_Infantry_ColdWar_Regular_Woodland_Rifleman_SUIT
{
	CATEGORY(TWC_Infantry_Dismounted_Woodland)
	backpack = "TWC_Backpack_ColdWar_Regular_Dismounted_Rifleman";
};
class TWC_Infantry_ColdWar_Regular_Dismounted_Woodland_SectionCommander: TWC_Infantry_ColdWar_Regular_Woodland_SectionCommander
{
	CATEGORY(TWC_Infantry_Dismounted_Woodland)
};
class TWC_Infantry_ColdWar_Regular_Dismounted_Woodland_2iC: TWC_Infantry_ColdWar_Regular_Woodland_2iC
{
	CATEGORY(TWC_Infantry_Dismounted_Woodland)
};
class TWC_Infantry_ColdWar_Regular_Dismounted_Woodland_AT: TWC_Infantry_ColdWar_Regular_Woodland_AT
{
	CATEGORY(TWC_Infantry_Dismounted_Woodland)
	backpack = "TWC_Backpack_ColdWar_Regular_Dismounted_AT";
};
class TWC_Infantry_ColdWar_Regular_Dismounted_Woodland_ASSAT: TWC_Infantry_ColdWar_Regular_Woodland_ASSAT
{
	CATEGORY(TWC_Infantry_Dismounted_Woodland)
	backpack = "TWC_Backpack_ColdWar_Regular_Dismounted_ATASS";
};
class TWC_Infantry_ColdWar_Regular_Dismounted_Woodland_MG: TWC_Infantry_ColdWar_Regular_Woodland_MG
{
	CATEGORY(TWC_Infantry_Dismounted_Woodland)
	backpack = "TWC_Backpack_ColdWar_Regular_Dismounted_MG";
};
class TWC_Infantry_ColdWar_Regular_Dismounted_Woodland_ASSMG: TWC_Infantry_ColdWar_Regular_Woodland_ASSMG
{
	CATEGORY(TWC_Infantry_Dismounted_Woodland)
	backpack = "TWC_Backpack_ColdWar_Regular_Dismounted_ASSMG";
};

//Platoon Command
class TWC_Infantry_ColdWar_Regular_Dismounted_Woodland_Platoon_Commander: TWC_Infantry_ColdWar_Regular_Woodland_Platoon_Commander
{
	CATEGORY(TWC_Infantry_Dismounted_Woodland)
};
class TWC_Infantry_ColdWar_Regular_Dismounted_Woodland_Platoon_Sergeant: TWC_Infantry_ColdWar_Regular_Woodland_Platoon_Sergeant
{
	CATEGORY(TWC_Infantry_Dismounted_Woodland)
};
class TWC_Infantry_ColdWar_Regular_Dismounted_Woodland_Platoon_Medic: TWC_Infantry_ColdWar_Regular_Woodland_Platoon_Medic
{
	CATEGORY(TWC_Infantry_Dismounted_Woodland)
};
class TWC_Infantry_ColdWar_Regular_Dismounted_Woodland_CSM: TWC_Infantry_ColdWar_Regular_Woodland_CSM
{
	CATEGORY(TWC_Infantry_Dismounted_Woodland)
};