//AIRBORNE, WOODLAND
//Section
class TWC_Infantry_ColdWar_Airborne_Woodland_Rifleman: TWC_Infantry_ColdWar_Regular_Dismounted_Woodland_Rifleman
{
	CATEGORY(TWC_Infantry_Airborne_Woodland)
	uniformClass="SP_72Para_DenisonTrops_1_Item";
	linkedItems[]=
	{
		"SP_P58_FightingOrderNBC",
		"SP_Helmet_Airborne_OD_FoliageMid",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
	respawnLinkedItems[]=
	{
		"SP_P58_FightingOrderNBC",
		"SP_Helmet_Airborne_OD_FoliageMid",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
};
class TWC_Infantry_ColdWar_Airborne_Woodland_Rifleman_SUIT: TWC_Infantry_ColdWar_Regular_Dismounted_Woodland_Rifleman_SUIT
{
	CATEGORY(TWC_Infantry_Airborne_Woodland)
	uniformClass="SP_72Para_DenisonTrops_1_Item";
	linkedItems[]=
	{
		"SP_P58_FightingOrderNBC",
		"SP_Helmet_Airborne_OD_FoliageMid",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
	respawnLinkedItems[]=
	{
		"SP_P58_FightingOrderNBC",
		"SP_Helmet_Airborne_OD_FoliageMid",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
};
class TWC_Infantry_ColdWar_Airborne_Woodland_SectionCommander: TWC_Infantry_ColdWar_Regular_Dismounted_Woodland_SectionCommander
{
	CATEGORY(TWC_Infantry_Airborne_Woodland)
	uniformClass="SP_72Para_DenisonTrops_1_Item";
	linkedItems[]=
	{
		"SP_P58_FightingOrderNBC",
		"SP_Helmet_Airborne_OD_FoliageMid",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
	respawnLinkedItems[]=
	{
		"SP_P58_FightingOrderNBC",
		"SP_Helmet_Airborne_OD_FoliageMid",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
};
class TWC_Infantry_ColdWar_Airborne_Woodland_2iC: TWC_Infantry_ColdWar_Regular_Dismounted_Woodland_2iC
{
	CATEGORY(TWC_Infantry_Airborne_Woodland)
	uniformClass="SP_72Para_DenisonTrops_1_Item";
	linkedItems[]=
	{
		"SP_P58_FightingOrderNBC",
		"SP_Helmet_Airborne_OD_FoliageMid",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
	respawnLinkedItems[]=
	{
		"SP_P58_FightingOrderNBC",
		"SP_Helmet_Airborne_OD_FoliageMid",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
};
class TWC_Infantry_ColdWar_Airborne_Woodland_AT: TWC_Infantry_ColdWar_Regular_Dismounted_Woodland_AT
{
	CATEGORY(TWC_Infantry_Airborne_Woodland)
	uniformClass="SP_72Para_DenisonTrops_1_Item";
	linkedItems[]=
	{
		"SP_P58_FightingOrderNBC",
		"SP_Helmet_Airborne_OD_FoliageMid",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
	respawnLinkedItems[]=
	{
		"SP_P58_FightingOrderNBC",
		"SP_Helmet_Airborne_OD_FoliageMid",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
};
class TWC_Infantry_ColdWar_Airborne_Woodland_ASSAT: TWC_Infantry_ColdWar_Regular_Dismounted_Woodland_ASSAT
{
	CATEGORY(TWC_Infantry_Airborne_Woodland)
	uniformClass="SP_72Para_DenisonTrops_1_Item";
	linkedItems[]=
	{
		"SP_P58_FightingOrderNBC",
		"SP_Helmet_Airborne_OD_FoliageMid",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
	respawnLinkedItems[]=
	{
		"SP_P58_FightingOrderNBC",
		"SP_Helmet_Airborne_OD_FoliageMid",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
};
class TWC_Infantry_ColdWar_Airborne_Woodland_MG: TWC_Infantry_ColdWar_Regular_Dismounted_Woodland_MG
{
	CATEGORY(TWC_Infantry_Airborne_Woodland)
	uniformClass="SP_72Para_DenisonTrops_1_Item";
	linkedItems[]=
	{
		"SP_P58_FightingOrderNBC",
		"SP_Helmet_Airborne_OD_FoliageMid",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
	respawnLinkedItems[]=
	{
		"SP_P58_FightingOrderNBC",
		"SP_Helmet_Airborne_OD_FoliageMid",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
};
class TWC_Infantry_ColdWar_Airborne_Woodland_ASSMG: TWC_Infantry_ColdWar_Regular_Dismounted_Woodland_ASSMG
{
	CATEGORY(TWC_Infantry_Airborne_Woodland)
	uniformClass="SP_72Para_DenisonTrops_1_Item";
	linkedItems[]=
	{
		"SP_P58_FightingOrderNBC",
		"SP_Helmet_Airborne_OD_FoliageMid",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
	respawnLinkedItems[]=
	{
		"SP_P58_FightingOrderNBC",
		"SP_Helmet_Airborne_OD_FoliageMid",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
};

//Platoon Command
class TWC_Infantry_ColdWar_Airborne_Woodland_Platoon_Commander: TWC_Infantry_ColdWar_Regular_Dismounted_Woodland_Platoon_Commander
{
	CATEGORY(TWC_Infantry_Airborne_Woodland)
	uniformClass="SP_72Para_DenisonTrops_1_Item";
	linkedItems[]=
	{
		"SP_P58_FightingOrderNBC",
		"SP_Helmet_Airborne_OD_Net",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
	respawnLinkedItems[]=
	{
		"SP_P58_FightingOrderNBC",
		"SP_Helmet_Airborne_OD_Net",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
};
class TWC_Infantry_ColdWar_Airborne_Woodland_Platoon_Sergeant: TWC_Infantry_ColdWar_Regular_Dismounted_Woodland_Platoon_Sergeant
{
	CATEGORY(TWC_Infantry_Airborne_Woodland)
	uniformClass="SP_72Para_DenisonTrops_1_Item";
	linkedItems[]=
	{
		"SP_P58_FightingOrderNBC",
		"SP_Helmet_Airborne_OD_Net",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
	respawnLinkedItems[]=
	{
		"SP_P58_FightingOrderNBC",
		"SP_Helmet_Airborne_OD_Net",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
};
class TWC_Infantry_ColdWar_Airborne_Woodland_Platoon_Medic: TWC_Infantry_ColdWar_Regular_Dismounted_Woodland_Platoon_Medic
{
	CATEGORY(TWC_Infantry_Airborne_Woodland)
	uniformClass="SP_72Para_DenisonTrops_1_Item";
	linkedItems[]=
	{
		"SP_P58_FightingOrderNBC",
		"SP_Helmet_Airborne_ODMedic_Net",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
	respawnLinkedItems[]=
	{
		"SP_P58_FightingOrderNBC",
		"SP_Helmet_Airborne_ODMedic_Net",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
};
class TWC_Infantry_ColdWar_Airborne_Woodland_CSM: TWC_Infantry_ColdWar_Regular_Dismounted_Woodland_CSM
{
	CATEGORY(TWC_Infantry_Airborne_Woodland)
	uniformClass="SP_72Para_DenisonTrops_1_Item";
	linkedItems[]=
	{
		"SP_P58_FightingOrderNBC",
		"SP_Helmet_Airborne_OD_Net",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
	respawnLinkedItems[]=
	{
		"SP_P58_FightingOrderNBC",
		"SP_Helmet_Airborne_OD_Net",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
};

//AT + AA
class TWC_Infantry_ColdWar_Airborne_Woodland_MILAN_Gunner: TWC_Infantry_ColdWar_Regular_Woodland_MILAN_Gunner
{
	CATEGORY(TWC_Infantry_Airborne_Woodland)
	uniformClass="SP_72Para_DenisonTrops_1_Item";
	linkedItems[]=
	{
		"SP_P58_FightingOrderNBC",
		"SP_Helmet_Airborne_OD_FoliageMid",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
	respawnLinkedItems[]=
	{
		"SP_P58_FightingOrderNBC",
		"SP_Helmet_Airborne_OD_FoliageMid",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
};
class TWC_Infantry_ColdWar_Airborne_Woodland_MILAN_Ass: TWC_Infantry_ColdWar_Regular_Woodland_MILAN_Ass
{
	CATEGORY(TWC_Infantry_Airborne_Woodland)
	uniformClass="SP_72Para_DenisonTrops_1_Item";
	linkedItems[]=
	{
		"SP_P58_FightingOrderNBC",
		"SP_Helmet_Airborne_OD_FoliageMid",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
	respawnLinkedItems[]=
	{
		"SP_P58_FightingOrderNBC",
		"SP_Helmet_Airborne_OD_FoliageMid",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
};
class TWC_Infantry_ColdWar_Airborne_Woodland_Blowpipe_Gunner: TWC_Infantry_ColdWar_Regular_Woodland_Blowpipe_Gunner
{
	CATEGORY(TWC_Infantry_Airborne_Woodland)
	uniformClass="SP_72Para_DenisonTrops_1_Item";
	linkedItems[]=
	{
		"SP_P58_FightingOrderNBC",
		"SP_Helmet_Airborne_OD_FoliageMid",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
	respawnLinkedItems[]=
	{
		"SP_P58_FightingOrderNBC",
		"SP_Helmet_Airborne_OD_FoliageMid",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
};
class TWC_Infantry_ColdWar_Airborne_Woodland_Blowpipe_Ass: TWC_Infantry_ColdWar_Regular_Woodland_Blowpipe_Ass
{
	CATEGORY(TWC_Infantry_Airborne_Woodland)
	uniformClass="SP_72Para_DenisonTrops_1_Item";
	linkedItems[]=
	{
		"SP_P58_FightingOrderNBC",
		"SP_Helmet_Airborne_OD_FoliageMid",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
	respawnLinkedItems[]=
	{
		"SP_P58_FightingOrderNBC",
		"SP_Helmet_Airborne_OD_FoliageMid",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
};

//Sniper Team
class TWC_Infantry_ColdWar_Airborne_Woodland_Sniper: TWC_Infantry_ColdWar_Regular_Woodland_Sniper
{
	CATEGORY(TWC_Infantry_Airborne_Woodland)
	uniformClass="SP_72Para_DenisonTrops_1_Item";
	linkedItems[]=
	{
		"SP_P58_FightingOrderNBC",
		"SP_Helmet_Airborne_OD_FoliageMid",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
	respawnLinkedItems[]=
	{
		"SP_P58_FightingOrderNBC",
		"SP_Helmet_Airborne_OD_FoliageMid",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
};
class TWC_Infantry_ColdWar_Airborne_Woodland_Spotter: TWC_Infantry_ColdWar_Regular_Woodland_Spotter
{
	CATEGORY(TWC_Infantry_Airborne_Woodland)
	uniformClass="SP_72Para_DenisonTrops_1_Item";
	linkedItems[]=
	{
		"SP_P58_FightingOrderNBC",
		"SP_Helmet_Airborne_OD_FoliageMid",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
	respawnLinkedItems[]=
	{
		"SP_P58_FightingOrderNBC",
		"SP_Helmet_Airborne_OD_FoliageMid",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
};

//Artillery Crew
class TWC_Infantry_ColdWar_Airborne_Woodland_Artillery_Commander: TWC_Infantry_ColdWar_Regular_Woodland_Artillery_Commander
{
	CATEGORY(TWC_Infantry_Airborne_Woodland)
	uniformClass="SP_72Para_DenisonTrops_1_Item";
	linkedItems[]=
	{
		"SP_P58_FightingOrderNBC",
		"SP_Helmet_Airborne_OD_Net",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
	respawnLinkedItems[]=
	{
		"SP_P58_FightingOrderNBC",
		"SP_Helmet_Airborne_OD_Net",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
};
class TWC_Infantry_ColdWar_Airborne_Woodland_Artillery_Crew: TWC_Infantry_ColdWar_Regular_Woodland_Artillery_Crew
{
	CATEGORY(TWC_Infantry_Airborne_Woodland)
	uniformClass="SP_72Para_DenisonTrops_1_Item";
	linkedItems[]=
	{
		"SP_P58_FightingOrderNBC",
		"SP_Helmet_Airborne_OD_Net",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
	respawnLinkedItems[]=
	{
		"SP_P58_FightingOrderNBC",
		"SP_Helmet_Airborne_OD_Net",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
};
class TWC_Infantry_ColdWar_Airborne_Woodland_FO: TWC_Infantry_ColdWar_Regular_Woodland_FO
{
	CATEGORY(TWC_Infantry_Airborne_Woodland)
	uniformClass="SP_72Para_DenisonTrops_1_Item";
	linkedItems[]=
	{
		"SP_P58_FightingOrderNBC",
		"SP_Helmet_Airborne_OD_Net",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
	respawnLinkedItems[]=
	{
		"SP_P58_FightingOrderNBC",
		"SP_Helmet_Airborne_OD_Net",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
};

//Aircraft
class TWC_Infantry_ColdWar_Airborne_Woodland_FAC: TWC_Infantry_ColdWar_Regular_Woodland_FAC
{
	CATEGORY(TWC_Infantry_Airborne_Woodland)
	uniformClass="SP_72Para_DenisonTrops_1_Item";
	linkedItems[]=
	{
		"SP_P58_FightingOrderNBC",
		"SP_Helmet_Airborne_OD_Net",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
	respawnLinkedItems[]=
	{
		"SP_P58_FightingOrderNBC",
		"SP_Helmet_Airborne_OD_Net",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
	};
};