
	class Modern_British_Blank: Modern_British_Base
	{
		scope=2;
		displayName="Blank Unit";
		nakedUniform="U_BasicBody";
		uniformClass="UK3CB_BAF_U_RolledUniform_MTP";
		linkedItems[]=
		{
			"UK3CB_BAF_H_Beret_RLC_Commando"
		};
		respawnLinkedItems[]=
		{
			"UK3CB_BAF_H_Beret_RLC_Commando"
		};
		Items[]=
		{
		};
		respawnitems[]=
		{
		};
		weapons[]=
		{
			"Throw",
			"Put"
		};
		respawnweapons[]=
		{
			"Throw",
			"Put"
		};
		magazines[]=
		{
		};
		Respawnmagazines[]=
		{
		};
	};
	class Modern_British_Squadleader: Modern_British_Base
	{
		scope=2;
		displayName="Section Commander @British Army";
		icon="iconManLeader";
		backpack="TWC_Backpack_Modern_Sectionlead";
		linkedItems[]=
		{
			"UK3CB_BAF_V_Osprey_SL_B",
			"UK3CB_BAF_H_Mk7_Scrim_ESS_B",
			"ItemMap",
			"ItemcTab",
			"ItemCompass",
			"ItemWatch"
		};
		respawnLinkedItems[]=
		{
			"UK3CB_BAF_V_Osprey_SL_B",
			"UK3CB_BAF_H_Mk7_Scrim_ESS_B",
			"ItemMap",
			"ItemcTab",
			"ItemCompass",
			"ItemWatch"
		};
		weapons[]=
		{
			"Throw",
			"Put",
			"ACE_Vector",
			"UK3CB_BAF_L85A2_RIS_ELCAN3D_TAN",
			"UK3CB_BAF_L131A1"
		};
		respawnweapons[]=
		{
			"Throw",
			"Put",
			"ACE_Vector",
			"UK3CB_BAF_L85A2_RIS_ELCAN3D_TAN",
			"UK3CB_BAF_L131A1"
		};
		magazines[]=
		{
			MAG_7("UK3CB_BAF_556_30Rnd"),
			MAG_2("UK3CB_BAF_9_17Rnd"),
			MAG_2("HandGrenade"),
			MAG_3("SmokeShell"),
			"B_IR_Grenade"
		};
		Respawnmagazines[]=
		{
			MAG_7("UK3CB_BAF_556_30Rnd"),
			MAG_2("UK3CB_BAF_9_17Rnd"),
			MAG_2("HandGrenade"),
			MAG_3("SmokeShell"),
			"B_IR_Grenade"
		};
	};
	class Modern_British_Quartermaster: Modern_British_Base
	{
		scope=2;
		displayName="Quartermaster @Management";
		uniformClass="UK3CB_BAF_U_RolledUniform_MTP";
		icon="iconManLeader";
		backpack="";
		attendant = 1;
		linkedItems[]=
		{
			"V_Rangemaster_belt",
			"ItemMap",
			"ItemcTab",
			"ItemCompass",
			"UK3CB_BAF_H_Beret_RLC_Commando_PRR",
			"ItemWatch"
		};
		respawnLinkedItems[]=
		{
			"V_Rangemaster_belt",
			"UK3CB_BAF_H_Beret_RLC_Commando_PRR",
			"ItemMap",
			"ItemcTab",
			"ItemCompass",
			"ItemWatch"
		};
		weapons[]=
		{
			"Throw",
			"Put",
			"ACE_Vector",
			"UK3CB_BAF_L85A2_RIS_ELCAN3D_TAN",
			"UK3CB_BAF_L131A1"
		};
		respawnweapons[]=
		{
			"Throw",
			"Put",
			"ACE_Vector",
			"UK3CB_BAF_L85A2_RIS_ELCAN3D_TAN",
			"UK3CB_BAF_L131A1"
		};
		magazines[]=
		{
			MAG_7("UK3CB_BAF_556_30Rnd"),
			MAG_2("UK3CB_BAF_9_17Rnd"),
			MAG_2("HandGrenade"),
			MAG_3("SmokeShell"),
			"B_IR_Grenade"
		};
		Respawnmagazines[]=
		{
			MAG_7("UK3CB_BAF_556_30Rnd"),
			MAG_2("UK3CB_BAF_9_17Rnd"),
			MAG_2("HandGrenade"),
			MAG_3("SmokeShell"),
			"B_IR_Grenade"
		};
	};


	class Modern_British_Rifleman: Modern_British_Base
	{
		scope=2;
		displayName="Rifleman";
		backpack="UK3CB_BAF_B_Bergen_MTP_Rifleman_L_B";
		linkedItems[]=
		{
			"UK3CB_BAF_V_Osprey_Rifleman_C",
			"UK3CB_BAF_H_Mk7_Scrim_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch"
		};
		respawnLinkedItems[]=
		{
			"UK3CB_BAF_V_Osprey_Rifleman_C",
			"UK3CB_BAF_H_Mk7_Scrim_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch"
		};
		weapons[]=
		{
			"Throw",
			"Put",	
			"UK3CB_BAF_L85A2_RIS_ELCAN3D",
			"launch_NLAW_F"
		};
		respawnweapons[]=
		{
			"Throw",
			"Put",	
			"UK3CB_BAF_L85A2_RIS_ELCAN3D",
			"launch_NLAW_F"
		};
		magazines[]=
		{
			MAG_7("UK3CB_BAF_556_30Rnd"),
			MAG_2("UK3CB_BAF_9_17Rnd"),
			MAG_2("HandGrenade"),
			MAG_3("SmokeShell"),
			"B_IR_Grenade"
		};
		Respawnmagazines[]=
		{
			MAG_7("UK3CB_BAF_556_30Rnd"),
			MAG_2("UK3CB_BAF_9_17Rnd"),
			MAG_2("HandGrenade"),
			MAG_3("SmokeShell"),
			"B_IR_Grenade"
		};
	};
	class Modern_British_Grenadier: Modern_British_Base
	{
		scope=2;
		displayName="Grenadier";
		icon="iconManExplosive";
		backpack="UK3CB_BAF_B_Bergen_MTP_Rifleman_L_B";
		linkedItems[]=
		{
			"UK3CB_BAF_V_Osprey_Grenadier_B",
			"UK3CB_BAF_H_Mk7_Scrim_A",
			"ItemMap",
			"ItemCompass",
			"ItemWatch"
		};
		respawnLinkedItems[]=
		{
			"UK3CB_BAF_V_Osprey_Grenadier_B",
			"UK3CB_BAF_H_Mk7_Scrim_A",
			"ItemMap",
			"ItemCompass",
			"ItemWatch"
		};
		weapons[]=
		{
			"Throw",
			"Put",
			"ACE_Yardage450",
			"UK3CB_BAF_L85A2_UGL_ELCAN3D",
			"CUP_launch_M72A6"
		};
		respawnweapons[]=
		{
			"Throw",
			"Put",
			"ACE_Yardage450",
			"UK3CB_BAF_L85A2_UGL_ELCAN3D",
			"CUP_launch_M72A6"
		};
		magazines[]=
		{
			MAG_7("UK3CB_BAF_556_30Rnd"),
			MAG_2("UK3CB_BAF_9_17Rnd"),
			MAG_2("HandGrenade"),
			MAG_3("SmokeShell"),
			"B_IR_Grenade"
		};
		Respawnmagazines[]=
		{
			MAG_7("UK3CB_BAF_556_30Rnd"),
			MAG_10("1Rnd_HE_Grenade_shell"),
			MAG_3("1Rnd_Smoke_Grenade_shell"),
			MAG_2("1Rnd_SmokeGreen_Grenade_shell"),
			MAG_2("1Rnd_SmokeRed_Grenade_shell"),
			MAG_2("1Rnd_SmokeBlue_Grenade_shell"),
			MAG_2("UK3CB_BAF_9_17Rnd"),
			MAG_2("HandGrenade"),
			MAG_3("SmokeShell"),
			"B_IR_Grenade"
		};
	};
	class Modern_British_Autorifleman: Modern_British_Base
	{
		scope=2;
		displayName="Automatic Rifleman";
		icon="iconManMG";
		backpack="TWC_Backpack_Modern_Autorifleman_Kitbag";
		linkedItems[]=
		{
			"UK3CB_BAF_V_Osprey_MG_A",
			"UK3CB_BAF_H_Mk7_Scrim_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch"
		};
		respawnLinkedItems[]=
		{
			"UK3CB_BAF_V_Osprey_MG_A",
			"UK3CB_BAF_H_Mk7_Scrim_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch"
		};
		weapons[]=
		{
			"Throw",
			"Put",
			"UK3CB_BAF_L110A2_ELCAN3D"
		};
		respawnweapons[]=
		{
			"Throw",
			"Put",	
			"UK3CB_BAF_L110A2_ELCAN3D"
		};
		magazines[]=
		{
			MAG_2("UK3CB_BAF_556_200Rnd_T"),
			MAG_3("SmokeShell"),
			"HandGrenade"
		};
		Respawnmagazines[]=
		{
			MAG_2("UK3CB_BAF_556_200Rnd_T"),
			MAG_3("SmokeShell"),
			"HandGrenade"
		};
	};
	class Modern_British_2IC: Modern_British_Rifleman
	{
		displayName="2IC";
		backpack="TWC_Backpack_Modern_2IC";
		linkedItems[]=
		{
			"UK3CB_BAF_V_Osprey_Rifleman_F",
			"UK3CB_BAF_H_Mk7_Scrim_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch"
		};
		respawnLinkedItems[]=
		{
			"UK3CB_BAF_V_Osprey_Rifleman_F",
			"UK3CB_BAF_H_Mk7_Scrim_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch"
		};
		weapons[]=
		{
			"Throw",
			"Put",
			"ACE_Vector",
			"UK3CB_BAF_L85A2_RIS_ELCAN3D_TAN"
		};
		respawnweapons[]=
		{
			"Throw",
			"Put",
			"ACE_Vector",
			"UK3CB_BAF_L85A2_RIS_ELCAN3D_TAN"
		};
		magazines[]=
		{
			MAG_7("UK3CB_BAF_556_30Rnd"),
			MAG_2("UK3CB_BAF_9_17Rnd"),
			MAG_2("HandGrenade"),
			MAG_3("SmokeShell"),
			"B_IR_Grenade"
		};
		Respawnmagazines[]=
		{
			MAG_7("UK3CB_BAF_556_30Rnd"),
			MAG_2("UK3CB_BAF_9_17Rnd"),
			MAG_2("HandGrenade"),
			MAG_3("SmokeShell"),
			"B_IR_Grenade"
		};
	};
	class Modern_British_Machinegunner: Modern_British_Autorifleman
	{
		scope=2;
		displayName="Machine Gunner";
		backpack="TWC_Backpack_Modern_MachineGunner_Kitbag";
		weapons[]=
		{
			"Throw",
			"Put",	
			"UK3CB_BAF_L7A2",
			"UK3CB_BAF_L131A1"
		};
		respawnweapons[]=
		{
			"Throw",
			"Put",	
			"UK3CB_BAF_L7A2",
			"UK3CB_BAF_L131A1"
		};
		magazines[]=
		{
			MAG_3("UK3CB_BAF_762_100Rnd_T"),
			MAG_2("UK3CB_BAF_9_17Rnd"),
			MAG_2("HandGrenade"),
			MAG_3("SmokeShell")
		};
		Respawnmagazines[]=
		{
			MAG_3("UK3CB_BAF_762_100Rnd_T"),
			MAG_2("UK3CB_BAF_9_17Rnd"),
			MAG_2("HandGrenade"),
			MAG_3("SmokeShell")
		};
	};
	class Modern_British_Marksman: Modern_British_Base
	{
		scope=2;
		displayName="Marksman";
		backpack = "UK3CB_BAF_B_Bergen_MTP_Rifleman_L_B";
		linkedItems[]=
		{
			"UK3CB_BAF_V_Osprey_Marksman_A",
			"UK3CB_BAF_H_Mk7_Scrim_E",
			"ItemMap",
			"ItemCompass",
			"ItemWatch"
		};
		respawnLinkedItems[]=
		{
			"UK3CB_BAF_V_Osprey_Marksman_A",
			"UK3CB_BAF_H_Mk7_Scrim_E",
			"ItemMap",
			"ItemCompass",
			"ItemWatch"
		};
		weapons[]=
		{
			"Throw",
			"Put",
			"ACE_Yardage450",
			"UK3CB_BAF_L129A1_Grippod_TA648",
			"launch_NLAW_F"
		};
		respawnweapons[]=
		{
			"Throw",
			"Put",
			"ACE_Yardage450",
			"UK3CB_BAF_L129A1_Grippod_TA648",
			"launch_NLAW_F"
		};
		magazines[]=
		{
			MAG_5("UK3CB_BAF_762_L42A1_20Rnd"),
			MAG_5("UK3CB_BAF_762_L42A1_20Rnd_T"),
			MAG_2("UK3CB_BAF_9_17Rnd"),
			MAG_2("HandGrenade"),
			MAG_3("SmokeShell")
		};
		Respawnmagazines[]=
		{
			MAG_5("UK3CB_BAF_762_L42A1_20Rnd"),
			MAG_5("UK3CB_BAF_762_L42A1_20Rnd_T"),
			MAG_2("UK3CB_BAF_9_17Rnd"),
			MAG_2("HandGrenade"),
			MAG_3("SmokeShell")
		};
	};
	class Modern_British_Platoon_Commander: Modern_British_Squadleader
	{
		scope=2;
		displayName="Platoon Commander @HQ";
		uniformClass="UK3CB_BAF_U_RolledUniform_MTP";
		backpack="TWC_Backpack_Modern_Sectionlead";
		linkedItems[]=
		{
			"UK3CB_BAF_V_Osprey_SL_A",
			"ItemMap",
			"ItemcTab",
			"ItemCompass",
			"UK3CB_BAF_H_Mk7_Camo_B",
			"ItemWatch"
		};
		respawnLinkedItems[]=
		{
			"UK3CB_BAF_V_Osprey_SL_A",
			"UK3CB_BAF_H_Mk7_Camo_B",
			"ItemMap",
			"ItemcTab",
			"ItemCompass",
			"ItemWatch"
		};
		weapons[]=
		{
			"Throw",
			"Put",
			"ACE_Vector",
			"UK3CB_BAF_L85A2_RIS_ELCAN3D_TAN",
			"UK3CB_BAF_L131A1"
		};
		respawnweapons[]=
		{
			"Throw",
			"Put",
			"ACE_Vector",
			"UK3CB_BAF_L85A2_RIS_ELCAN3D_TAN",
			"UK3CB_BAF_L131A1"
		};
	};
	class Modern_British_Platoon_Sergeant: Modern_British_Platoon_Commander
	{
		scope=2;
		displayName="Platoon Sergeant";
		uniformClass="UK3CB_BAF_U_CombatUniform_MTP";
		icon="iconMan";
	};
	class Modern_British_Platoon_Mortar: Modern_British_Rifleman
	{
		displayName="Platoon Mortar (Modern)";
		icon="iconManExplosive";
		backpack="TWC_Backpack_Modern_Platoon_Mortar";
		weapons[]=
		{
			"Throw",
			"Put",	
			"UK3CB_BAF_L85A2",
			"UK3CB_BAF_M6"
		};
		respawnweapons[]=
		{
			"Throw",
			"Put",	
			"UK3CB_BAF_L85A2",
			"UK3CB_BAF_M6"
		};
		magazines[]=
		{
			MAG_5("UK3CB_BAF_556_30Rnd"),
			MAG_3("UK3CB_BAF_1Rnd_60mm_Mo_Shells"),
			MAG_2("HandGrenade"),
			MAG_2("SmokeShell")
		};
		Respawnmagazines[]=
		{
			MAG_5("UK3CB_BAF_556_30Rnd"),
			MAG_3("UK3CB_BAF_1Rnd_60mm_Mo_Shells"),
			MAG_2("HandGrenade"),
			MAG_2("SmokeShell")
		};
	};
	class Modern_British_Medic: Modern_British_Base
	{
		scope=2;
		displayName="Medic";
		icon="iconManMedic";
		backpack="TWC_Backpack_Modern_Medic";
		attendant = 1;
		linkedItems[]=
		{
			"UK3CB_BAF_V_Osprey_Medic_B",
			"UK3CB_BAF_H_Mk7_Camo_CESS_D",
			"ItemMap",
			"ItemCompass",
			"ItemWatch"
		};
		respawnLinkedItems[]=
		{
			"UK3CB_BAF_V_Osprey_Medic_B",
			"UK3CB_BAF_H_Mk7_Camo_CESS_D",
			"ItemMap",
			"ItemCompass",
			"ItemWatch"
		};
		weapons[]=
		{
			"Throw",
			"Put",
			"UK3CB_BAF_L85A2_RIS_ELCAN3D"
		};
		respawnweapons[]=
		{
			"Throw",
			"Put",
			"UK3CB_BAF_L85A2_RIS_ELCAN3D"
		};
		magazines[]=
		{
			MAG_5("UK3CB_BAF_556_30Rnd"),
			MAG_5("SmokeShell")
		};
		Respawnmagazines[]=
		{
			MAG_5("UK3CB_BAF_556_30Rnd"),
			MAG_5("SmokeShell")
		};
	};
	class Modern_British_Platoon_CSM: Modern_British_Squadleader
	{
		displayName="Company Sergeant Major (Modern)";
		backpack="TWC_Backpack_Modern_Platoon_Sergeant";
		class EventHandlers: EventHandlers
		{
			init = "if(local (_this select 0)) then{(_this select 0) setVariable [""twc_isMolar"",true]};";
		};
	};

	class Modern_British_HeliPilot: Modern_British_Base
	{
		scope=2;
		displayName="Helicopter Pilot";
		uniformClass="UK3CB_BAF_U_Smock_MTP";
		backpack="";
		twc_radioType = "ACRE_PRC148";
		twc_radioChannel = 1;
		linkedItems[]=
		{
			"UK3CB_BAF_H_PilotHelmetHeli_A",
			"UK3CB_BAF_V_Pilot_A",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"itemCTAB"
		};
		respawnLinkedItems[]=
		{
			"UK3CB_BAF_H_PilotHelmetHeli_A",
			"UK3CB_BAF_V_Pilot_A",
			"ItemMap",		
			"ItemCompass",
			"ItemWatch",
			"itemCTAB"
		};
		weapons[]=
		{
			"Throw",
			"Put",
			"TWC_BAF_L22A2_SUSAT",
			"UK3CB_BAF_L131A1"
		};
		respawnweapons[]=
		{
			"Throw",
			"Put",
			"TWC_BAF_L22A2_SUSAT",
			"UK3CB_BAF_L131A1"
		};
		magazines[]=
		{
			"UK3CB_BAF_556_30Rnd",
			MAG_2("UK3CB_BAF_9_17Rnd"),
			"SmokeShell",
			"SmokeShell"
		};
		Respawnmagazines[]=
		{
			"UK3CB_BAF_556_30Rnd",
			MAG_2("UK3CB_BAF_9_17Rnd"),
			"SmokeShell",
			"SmokeShell"
		};
		Items[]=
		{
			MEDICAL_LOADOUT,
			"ACRE_PRC148"
		};
		respawnitems[]=
		{
			MEDICAL_LOADOUT,
			"ACRE_PRC148"
		};
	};

class Modern_British_crewchief:Modern_British_HeliPilot
{
		scope=2;
		displayName="Helicopter Crew Chief";
		backpack="";
		linkedItems[]=
		{
			"H_CrewHelmetHeli_B",
			"UK3CB_BAF_V_Pilot_A",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"itemCTAB"
		};
		respawnLinkedItems[]=
		{
			"H_CrewHelmetHeli_B",
			"UK3CB_BAF_V_Pilot_A",
			"ItemMap",		
			"ItemCompass",
			"ItemWatch",
			"itemCTAB"
		};
};

	class Modern_British_JetPilot: Modern_British_HeliPilot
	{
		_generalMacro="Modern_JetPilot";
		scope=2;
		displayName="Fixed Wing Pilot @Fixed Wing Team";
		faction="twc_public_baf";
		editorSubcategory = "Men_Modern";
		vehicleClass="Men_Modern";
		icon="iconMan";
		nakedUniform="U_BasicBody";
		uniformClass="UK3CB_BAF_U_HeliPilotCoveralls_Army";
		backpack="";
		linkedItems[]=
		{
			"H_PilotHelmetFighter_B",
			"CUP_V_B_PilotVest",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemcTab"
		};
		respawnLinkedItems[]=
		{
			"H_PilotHelmetFighter_B",
			"CUP_V_B_PilotVest",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemcTab"
		};
		weapons[]=
		{
			"Throw",
			"Put",
			"UK3CB_BAF_L131A1"
		};
		respawnweapons[]=
		{
			"Throw",
			"Put",
			"UK3CB_BAF_L131A1"
		};
		magazines[]=
		{
		MAG_2("UK3CB_BAF_9_17Rnd"),
		MAG_2("SmokeShell")
		};
		Respawnmagazines[]=
		{
		MAG_2("UK3CB_BAF_9_17Rnd"),
		MAG_2("SmokeShell")
		};
	};
	class Modern_British_Sniper: Modern_British_Base {
		scope=2;
		displayName="Sniper";
		uniformClass="CUP_U_B_BAF_DPM_Ghillie";
		icon="iconManLeader";
		twc_radioType = "ACRE_PRC343";
		twc_radioChannel = 4;
		backpack="TWC_Backpack_Modern_Sniper";
		linkedItems[]= {
			"V_Rangemaster_belt",
			"ItemMap",
			"ItemCompass",
			"ItemWatch"
		};

		respawnLinkedItems[]= {
			"V_Rangemaster_belt",
			"ItemMap",
			"ItemCompass",
			"ItemWatch"
		};

		weapons[]= {
			"Throw",
			"Put",
			"twc_l115a3_wd_covered",
			"UK3CB_BAF_L131A1"
		};
		respawnweapons[]=
		{
			"Throw",
			"Put",
			"twc_l115a3_wd_covered",
			"UK3CB_BAF_L131A1"
		};

		magazines[]= {
			"UK3CB_BAF_9_17Rnd",
			MAG_3("TWC_5Rnd_338_300gr_HPBT_Mag"),
			"HandGrenade",
			"SmokeShell",
			"B_IR_Grenade"
		};

		Respawnmagazines[]= {
			"UK3CB_BAF_9_17Rnd",
			MAG_3("TWC_5Rnd_338_300gr_HPBT_Mag"),
			"HandGrenade",
			"SmokeShell",
			"B_IR_Grenade"
		};
	};

	class Modern_British_Spotter: Modern_British_Sniper {
		scope=2;
		displayName="Spotter";
		icon="iconManLeader";
		backpack="TWC_Backpack_Modern_Spotter";

		linkedItems[]= {
			"V_Rangemaster_belt",
			"ItemcTab",
			"ItemMap",
			"ItemCompass",
			"ItemWatch"
		};

		respawnLinkedItems[]= {
			"V_Rangemaster_belt",
			"ItemcTab",
			"ItemMap",
			"ItemCompass",
			"ItemWatch"
		};
		Items[]= {
		MEDICAL_LOADOUT,
		"ACE_Kestrel4500",
		"ACE_RangeCard",
		"ACRE_PRC152",
		"ACRE_PRC343"
		};

		respawnItems[]= {
		MEDICAL_LOADOUT,
		"ACE_Kestrel4500",
		"ACE_RangeCard",
		"ACRE_PRC152",
		"ACRE_PRC343"
		};

		weapons[]= {
			"Throw",
			"Put",
			"ACE_Vector",
			"twc_l129a1_spotter",
			"UK3CB_BAF_L131A1"
		};

		respawnweapons[]= {
			"Throw",
			"Put",
			"ACE_Vector",
			"twc_l129a1_spotter",
			"UK3CB_BAF_L131A1"
		};

		magazines[]= {
			"UK3CB_BAF_9_17Rnd",
			MAG_3("UK3CB_BAF_762_L42A1_20Rnd"),
			"HandGrenade",
			"SmokeShell",
			"B_IR_Grenade"
		};

		Respawnmagazines[]= {
			"UK3CB_BAF_9_17Rnd",
			MAG_3("UK3CB_BAF_762_L42A1_20Rnd"),
			"HandGrenade",
			"SmokeShell",
			"B_IR_Grenade"
		};
	};

	class Modern_British_FAC: Modern_British_Base
	{
		scope=2;
		displayName="Forward Air Controller";
		backpack="TWC_Backpack_Modern_FAC";
		linkedItems[]=
		{
			"UK3CB_BAF_V_Osprey_Grenadier_A",
			"UK3CB_BAF_H_Mk7_Net_ESS_A",
			"ItemMap",
			"ItemcTab",
			"ItemCompass",
			"ItemWatch"
		};
		respawnLinkedItems[]=
		{
			"UK3CB_BAF_V_Osprey_Grenadier_A",
			"UK3CB_BAF_H_Mk7_Net_ESS_A",
			"ItemMap",
			"ItemcTab",
			"ItemCompass",
			"ItemWatch"
		};
		weapons[]=
		{
			"Throw",
			"Put",
			"UK3CB_BAF_Soflam_Laserdesignator",
			"UK3CB_BAF_L85A2_UGL_ELCAN3D"
		};
		respawnweapons[]=
		{
			"Throw",
			"Put",
			"UK3CB_BAF_Soflam_Laserdesignator",
			"UK3CB_BAF_L85A2_UGL_ELCAN3D"
		};
		magazines[]=
		{
			MAG_7("UK3CB_BAF_556_30Rnd"),
			MAG_3("1Rnd_HE_Grenade_shell"),
			MAG_4("1Rnd_Smoke_Grenade_shell"),
			MAG_4("1Rnd_SmokeGreen_Grenade_shell"),
			MAG_4("1Rnd_SmokeRed_Grenade_shell"),
			MAG_4("1Rnd_SmokeBlue_Grenade_shell"),
			MAG_2("UK3CB_BAF_9_17Rnd"),
			MAG_2("HandGrenade"),
			MAG_3("SmokeShell"),
			"B_IR_Grenade",
			"Laserbatteries"
		};
		Respawnmagazines[]=
		{
			MAG_7("UK3CB_BAF_556_30Rnd"),
			MAG_3("1Rnd_HE_Grenade_shell"),
			MAG_4("1Rnd_Smoke_Grenade_shell"),
			MAG_4("1Rnd_SmokeGreen_Grenade_shell"),
			MAG_4("1Rnd_SmokeRed_Grenade_shell"),
			MAG_4("1Rnd_SmokeBlue_Grenade_shell"),
			MAG_2("UK3CB_BAF_9_17Rnd"),
			MAG_2("HandGrenade"),
			MAG_3("SmokeShell"),
			"B_IR_Grenade",
			"Laserbatteries"
		};
	};
	class Modern_British_logitech: Modern_British_Base
	{
		scope=2;
		displayName="Logistics Technician";
		uniformClass="UK3CB_BAF_U_CombatUniform_MTP_ShortSleeve";
		icon="iconMan";
		backpack="twc_mtp_belt";
		linkedItems[]=
		{
			"UK3CB_BAF_H_Mk7_Camo_C",
			"UK3CB_BAF_V_Osprey_Rifleman_D",
			"ItemMap",
			"ItemCompass",
			"ItemWatch"
		};
		respawnLinkedItems[]=
		{
			"UK3CB_BAF_H_Mk7_Camo_C",
			"UK3CB_BAF_V_Osprey_Rifleman_D",
			"ItemMap",
			"ItemCompass",
			"ItemWatch"
		};
		weapons[]=
		{
			"Throw",
			"Put",	
			"UK3CB_BAF_L85A2_RIS_AFG"
		};
		respawnweapons[]=
		{
			"Throw",
			"Put",	
			"UK3CB_BAF_L85A2_RIS_AFG"
		};
		magazines[]=
		{
			MAG_2("UK3CB_BAF_556_30Rnd")
		};
		Respawnmagazines[]=
		{
			MAG_2("UK3CB_BAF_556_30Rnd")
		};
	};

	class Modern_British_VehicleCrew: Modern_British_Base
	{
		scope=2;
		displayName="Armour Crewman";
		icon="iconMan";
		linkedItems[]=
		{
			"CUP_H_BAF_MTP_Mk6_EMPTY_PRR",
			"TWC_V_B_BAF_MTP_Osprey_Mk4_Crewman",
			"ItemMap",
			"ItemCompass",
			"ItemWatch"
		};
		respawnLinkedItems[]=
		{
			"CUP_H_BAF_MTP_Mk6_EMPTY_PRR",
			"TWC_V_B_BAF_MTP_Osprey_Mk4_Crewman",
			"ItemMap",
			"ItemCompass",
			"ItemWatch"
		};
		weapons[]=
		{
			"Throw",
			"Put",	
			"UK3CB_BAF_L131A1",
			"TWC_BAF_L22A2_SUSAT"
		};
		respawnweapons[]=
		{
			"Throw",
			"Put",	
			"UK3CB_BAF_L131A1",
			"TWC_BAF_L22A2_SUSAT"
		};
		magazines[]=
		{
			MAG_4("UK3CB_BAF_556_30Rnd"),
			MAG_2("UK3CB_BAF_9_17Rnd"),
			"smokeshell"
		};
		Respawnmagazines[]=
		{
			MAG_4("UK3CB_BAF_556_30Rnd"),
			MAG_2("UK3CB_BAF_9_17Rnd"),
			"smokeshell"
		};
	};
	class Modern_British_VehicleCommander: Modern_British_VehicleCrew
	{
		displayName="Armour Commander";
		icon="iconManLeader";
		nakedUniform="U_BasicBody";
		backpack="twc_mtp_belt";
		weapons[]=
		{
			"Throw",
			"Put",
			"ACE_Vector",
			"UK3CB_BAF_L131A1",
			"TWC_BAF_L22A2_SUSAT"
		};
		respawnweapons[]=
		{
			"Throw",
			"Put",
			"ACE_Vector",
			"UK3CB_BAF_L131A1",
			"TWC_BAF_L22A2_SUSAT"
		};
		Items[]=
		{
		MEDICAL_LOADOUT,
		"ACRE_PRC343"
		};
		respawnitems[]=
		{
		MEDICAL_LOADOUT,
		"ACRE_PRC343"
		};
	};


	class Modern_British_FSTCommander: Modern_British_Base {
		scope=2;
		displayName="FST Commander@Fire Support Team";
		icon="iconManLeader";
		uniformClass="UK3CB_BAF_U_CombatUniform_MTP_ShortSleeve";
		backpack="TWC_Backpack_Modern_Sectionlead";
		twc_radioType = "ACRE_PRC343";
		twc_radioChannel = 3;
		linkedItems[]=
		{
			"UK3CB_BAF_V_Osprey_Lite",
			"UK3CB_BAF_H_Mk7_Net_D",
			"ItemMap",
			"ItemcTab",
			"ItemCompass",
			"ItemWatch"
		};
		respawnLinkedItems[]=
		{
			"UK3CB_BAF_V_Osprey_Lite",
			"UK3CB_BAF_H_Mk7_Net_D",
			"ItemMap",
			"ItemcTab",
			"ItemCompass",
			"ItemWatch"
		};
		weapons[]=
		{
			"Throw",
			"Put",
			"ACE_Vector",
			"UK3CB_BAF_L85A2_RIS_ELCAN3D",
			"UK3CB_BAF_L131A1"
		};
		respawnweapons[]=
		{
			"Throw",
			"Put",
			"ACE_Vector",
			"UK3CB_BAF_L85A2_RIS_ELCAN3D",
			"UK3CB_BAF_L131A1"
		};
		magazines[]=
		{
			MAG_7("UK3CB_BAF_556_30Rnd"),
			MAG_2("UK3CB_BAF_9_17Rnd"),
			MAG_2("HandGrenade"),
			MAG_3("SmokeShell"),
			"B_IR_Grenade"
		};
		Respawnmagazines[]=
		{
			MAG_7("UK3CB_BAF_556_30Rnd"),
			MAG_2("UK3CB_BAF_9_17Rnd"),
			MAG_2("HandGrenade"),
			MAG_3("SmokeShell"),
			"B_IR_Grenade"
		};
	};

	class Modern_British_FSTForwardObserver: Modern_British_Base {
		scope=2;
		displayName="Forward Observer";
		icon="iconManExplosive";
		uniformClass="UK3CB_BAF_U_CombatUniform_MTP_ShortSleeve";
		backpack="TWC_Backpack_Modern_FSTForwardObserver";
		linkedItems[]=
		{
			"UK3CB_BAF_V_Osprey_Grenadier_A",
			"UK3CB_BAF_H_Mk7_Net_D",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ACRE_PRC343",
			"ACRE_PRC152"
		};
		respawnLinkedItems[]=
		{
			"UK3CB_BAF_V_Osprey_Grenadier_A",
			"UK3CB_BAF_H_Mk7_Net_D",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ACRE_PRC343",
			"ACRE_PRC152"
		};
		weapons[]=
		{
			"Throw",
			"Put",
			"UK3CB_BAF_Soflam_Laserdesignator",
			"UK3CB_BAF_L85A2_UGL_ELCAN3D",
			"UK3CB_BAF_L131A1"
		};
		respawnweapons[]=
		{
			"Throw",
			"Put",
			"UK3CB_BAF_Soflam_Laserdesignator",
			"UK3CB_BAF_L85A2_UGL_ELCAN3D",
			"UK3CB_BAF_L131A1"
		};
		magazines[]=
		{
			MAG_7("UK3CB_BAF_556_30Rnd"),
			MAG_2("UK3CB_BAF_9_17Rnd"),
			MAG_2("HandGrenade"),
			MAG_3("SmokeShell"),
			"B_IR_Grenade",
			"Laserbatteries",
			"SmokeShell"
		};
		Respawnmagazines[]=
		{
			MAG_7("UK3CB_BAF_556_30Rnd"),
			MAG_2("UK3CB_BAF_9_17Rnd"),
			MAG_2("HandGrenade"),
			MAG_3("SmokeShell"),
			"B_IR_Grenade",
			"Laserbatteries",
			"SmokeShell"
		};
	};

	class Modern_British_FSTAssistant: Modern_British_Base {
		scope=2;
		displayName="FST Assistant";
		uniformClass="UK3CB_BAF_U_CombatUniform_MTP_ShortSleeve";
		backpack="UK3CB_BAF_B_Carryall_MTP";
		twc_radioType = "ACRE_PRC343";
		twc_radioChannel = 3;
		
		linkedItems[]=
		{
			"UK3CB_BAF_V_Osprey_Lite",
			"UK3CB_BAF_H_Mk7_Net_D",
			"ItemMap",
			"ItemCompass",
			"ItemWatch"
		};
		respawnLinkedItems[]=
		{
			"UK3CB_BAF_V_Osprey_Lite",
			"UK3CB_BAF_H_Mk7_Net_D",
			"ItemMap",
			"ItemCompass",
			"ItemWatch"
		};
		weapons[]=
		{
			"Throw",
			"Put",
			"UK3CB_BAF_L85A2_RIS_ELCAN3D",
			"UK3CB_BAF_L131A1"
		};
		respawnweapons[]=
		{
			"Throw",
			"Put",	
			"UK3CB_BAF_L85A2_RIS_ELCAN3D",
			"UK3CB_BAF_L131A1"
		};
		magazines[]=
		{
			MAG_7("UK3CB_BAF_556_30Rnd"),
			MAG_2("UK3CB_BAF_9_17Rnd"),
			MAG_2("HandGrenade"),
			MAG_3("SmokeShell")
		};
		Respawnmagazines[]=
		{
			MAG_7("UK3CB_BAF_556_30Rnd"),
			MAG_2("UK3CB_BAF_9_17Rnd"),
			MAG_2("HandGrenade"),
			MAG_3("SmokeShell")
		};
	};
	
	class Modern_Artillery_Commander: Modern_British_Base
	{
		scope=2;
		displayName="Artillery Gun Commander";
		icon="iconManLeader";
		backpack="TWC_Backpack_Modern_Sectionlead";
		uniformClass="UK3CB_BAF_U_RolledUniform_MTP";
		linkedItems[]=
		{
			"UK3CB_BAF_V_Osprey_MG_A",
			"UK3CB_BAF_H_Mk7_Camo_D",
			"ItemMap",
			"ItemCompass",
			"ItemWatch"
		};
		respawnLinkedItems[]=
		{
			"UK3CB_BAF_V_Osprey_MG_A",
			"UK3CB_BAF_H_Mk7_Camo_D",
			"ItemMap",
			"ItemCompass",
			"ItemWatch"
		};
		weapons[]=
		{
			"Throw",
			"Put",
			"UK3CB_BAF_L85A2_RIS_ELCAN3D"
		};
		respawnweapons[]=
		{
			"Throw",
			"Put",
			"UK3CB_BAF_L85A2_RIS_ELCAN3D"
		};
		magazines[]=
		{
			MAG_4("UK3CB_BAF_556_30Rnd"),
			MAG_2("UK3CB_BAF_9_17Rnd"),
			MAG_2("SmokeShell")
		};
		Respawnmagazines[]=
		{
			MAG_4("UK3CB_BAF_556_30Rnd"),
			MAG_2("UK3CB_BAF_9_17Rnd"),
			MAG_2("SmokeShell")
		};
	};

	class Modern_Artillery_Gunner: Modern_Artillery_Commander
	{
		scope=2;
		displayName="Artillery Gun Operator";
		backpack="";
		uniformClass="UK3CB_BAF_U_CombatUniform_MTP_TShirt";
		
	};