class Cold_War_Argentinian_Squadleader: I_Soldier_F
	{
		_generalMacro="Cold_War_Argentinian_Squadleader";
		scope=2;
		displayName="Section Leader";
		faction="argentinian_units";
		editorSubcategory = "Men_Argentina";
		vehicleClass="Men_Argentina";
		icon="iconManLeader";
		nakedUniform="U_BasicBody";
		uniformClass="SP_0000_Standard_BattleDressUniform_Green";
		backpack="";
		linkedItems[]=
		{
        "CUP_V_RUS_Smersh_1",
		"SP_M1Helmet_Green",
		"ItemMap",
		"ItemCompass",
		"ACRE_PRC343",
		"Binocular"
		};
		respawnLinkedItems[]=
		{
        "CUP_V_RUS_Smersh_1",
		"ItemMap",
		"ItemCompass",
		"ACRE_PRC343"
		};
		weapons[]=
		{
		"Throw",
		"Put",
		"CUP_arifle_FNFAL"
		};
		respawnweapons[]=
		{
		"Throw",
		"Put",
		"CUP_arifle_FNFAL"
		};
		magazines[]=
		{
		"CUP_20Rnd_762x51_FNFAL_M",
		"CUP_20Rnd_762x51_FNFAL_M",
		"CUP_20Rnd_762x51_FNFAL_M",
		"CUP_20Rnd_762x51_FNFAL_M",
		"CUP_20Rnd_762x51_FNFAL_M",
		"CUP_HandGrenade_M67",
		"CUP_HandGrenade_M67"
		};
		Respawnmagazines[]=
		{
		"CUP_20Rnd_762x51_FNFAL_M",
		"CUP_20Rnd_762x51_FNFAL_M",
		"CUP_20Rnd_762x51_FNFAL_M",
		"CUP_20Rnd_762x51_FNFAL_M",
		"CUP_20Rnd_762x51_FNFAL_M",
		"CUP_HandGrenade_M67",
		"CUP_HandGrenade_M67"
		};
		Items[]=
		{
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_morphine",
		"ACE_morphine",
		"ACE_EarPlugs"	
		};
		respawntems[]=
		{
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_morphine",
		"ACE_morphine",
		"ACE_EarPlugs"			
		};
	};
	
	class Cold_War_Argentinian_Rifleman: I_Soldier_F
	{
		_generalMacro="Cold_War_Argentinian_Rifleman";
		scope=2;
		displayName="Rifleman";
		faction="argentinian_units";
		editorSubcategory = "Men_Argentina";
		vehicleClass="Men_Argentina";
		icon="iconMan";
		nakedUniform="U_BasicBody";
		uniformClass="SP_0000_Standard_BattleDressUniform_Green";
		backpack="";
		linkedItems[]=
		{
        "CUP_V_RUS_Smersh_1",
		"SP_M1Helmet_Green",
		"ItemCompass"
		};
		respawnLinkedItems[]=
		{
        "CUP_V_RUS_Smersh_1",
		"ItemCompass"
		};
		weapons[]=
		{
		"Throw",
		"Put",	
		"CUP_arifle_FNFAL"
		};
		respawnweapons[]=
		{
		"Throw",
		"Put",	
		"CUP_arifle_FNFAL"
		};
		magazines[]=
		{
		"CUP_20Rnd_762x51_FNFAL_M",
		"CUP_20Rnd_762x51_FNFAL_M",
		"CUP_20Rnd_762x51_FNFAL_M",
		"CUP_20Rnd_762x51_FNFAL_M",
		"CUP_20Rnd_762x51_FNFAL_M",
		"CUP_20Rnd_762x51_FNFAL_M",
		"CUP_20Rnd_762x51_FNFAL_M",
		"CUP_20Rnd_762x51_FNFAL_M",
		"CUP_20Rnd_762x51_FNFAL_M",
		"CUP_20Rnd_762x51_FNFAL_M",
		"CUP_20Rnd_762x51_FNFAL_M",
		"CUP_HandGrenade_M67",
		"CUP_HandGrenade_M67",
		"SmokeShell",
		"SmokeShell"
		};
		Respawnmagazines[]=
		{
		"CUP_20Rnd_762x51_FNFAL_M",
		"CUP_20Rnd_762x51_FNFAL_M",
		"CUP_20Rnd_762x51_FNFAL_M",
		"CUP_20Rnd_762x51_FNFAL_M",
		"CUP_20Rnd_762x51_FNFAL_M",
		"CUP_HandGrenade_M67",
		"CUP_HandGrenade_M67",
		"SmokeShell",
		"SmokeShell"
		};
		Items[]=
		{
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_morphine",
		"ACE_morphine"
		};
		respawntems[]=
		{
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_morphine",
		"ACE_morphine"
		};		
	};

	class Cold_War_Argentinian_AT_Rifleman: I_Soldier_F
	{
		_generalMacro="Cold_War_Argentinian_AT_Rifleman";
		scope=2;
		displayName="AT Rifleman";
		faction="argentinian_units";
		editorSubcategory = "Men_Argentina";
		vehicleClass="Men_Argentina";
		icon="iconManExplosive";
		nakedUniform="U_BasicBody";
		uniformClass="SP_0000_Standard_BattleDressUniform_Green";
		backpack="";
		linkedItems[]=
		{
        "CUP_V_RUS_Smersh_1",
		"SP_M1Helmet_Green",
		"ItemCompass"
		};
		respawnLinkedItems[]=
		{
        "CUP_V_RUS_Smersh_1",
		"ItemMap",
		"ItemCompass"
		};
		weapons[]=
		{
		"Throw",
		"Put",
		"CUP_arifle_FNFAL",
		"ukcw_l14a1"
		};
		respawnweapons[]=
		{
		"Throw",
		"Put",	
		"CUP_arifle_FNFAL",
		"ukcw_l14a1"
		};
		magazines[]=
		{
		"CUP_20Rnd_762x51_FNFAL_M",
		"CUP_20Rnd_762x51_FNFAL_M",		
		"CUP_20Rnd_762x51_FNFAL_M",
		"CUP_20Rnd_762x51_FNFAL_M",
		"CUP_20Rnd_762x51_FNFAL_M",
		"CUP_HandGrenade_M67",
		"CUP_HandGrenade_M67",
		"SmokeShell",
		"SmokeShell",
		"ukcw_l14a1_HEAT",
		"ukcw_l14a1_HEAT",
		"ukcw_l14a1_HEAT",
		"ukcw_l14a1_HEAT"
		};
		Respawnmagazines[]=
		{
		"CUP_20Rnd_762x51_FNFAL_M",
		"CUP_20Rnd_762x51_FNFAL_M",		
		"CUP_20Rnd_762x51_FNFAL_M",
		"CUP_20Rnd_762x51_FNFAL_M",
		"CUP_20Rnd_762x51_FNFAL_M",
		"CUP_HandGrenade_M67",
		"CUP_HandGrenade_M67",
		"SmokeShell",
		"SmokeShell",
        "ukcw_l14a1_HEAT",
		"ukcw_l14a1_HEAT",
		"ukcw_l14a1_HEAT",
		"ukcw_l14a1_HEAT"
		};
		Items[]=
		{
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_morphine",
		"ACE_morphine"
		};
		respawntems[]=
		{
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_morphine",
		"ACE_morphine"
		};
	};

	class Cold_War_Argentinian_AT_Assistant: I_Soldier_F
	{
		_generalMacro="Cold_War_Argentinian_AT_Assistant";
		scope=2;
		displayName="AT Assistant";
		faction="argentinian_units";
		editorSubcategory = "Men_Argentina";
		vehicleClass="Men_Argentina";
		icon="iconManMG";
		nakedUniform="U_BasicBody";
		uniformClass="SP_0000_Standard_BattleDressUniform_Green";
		backpack="";
		linkedItems[]=
		{
        "CUP_V_RUS_Smersh_1",
		"SP_M1Helmet_Green",
		"ItemCompass"
		};
		respawnLinkedItems[]=
		{
        "CUP_V_RUS_Smersh_1",
		"ItemMap",
		"ItemCompass"
		};
		weapons[]=
		{
		"Throw",
		"Put",
		"CUP_arifle_FNFAL"
		};
		respawnweapons[]=
		{
		"Throw",
		"Put",	
		"CUP_arifle_FNFAL"
		};
		magazines[]=
		{
		"CUP_20Rnd_762x51_FNFAL_M",
		"CUP_20Rnd_762x51_FNFAL_M",
		"CUP_20Rnd_762x51_FNFAL_M",
		"CUP_20Rnd_762x51_FNFAL_M",
		"CUP_20Rnd_762x51_FNFAL_M",
		"CUP_HandGrenade_M67",
		"CUP_HandGrenade_M67",
		"SmokeShell",
		"SmokeShell",
		"ukcw_l14a1_HEAT",
		"ukcw_l14a1_HEAT",
		"ukcw_l14a1_HEAT",
		"ukcw_l14a1_HEAT"
		};
		Respawnmagazines[]=
		{
		"CUP_20Rnd_762x51_FNFAL_M",
		"CUP_20Rnd_762x51_FNFAL_M",
		"CUP_20Rnd_762x51_FNFAL_M",
		"CUP_20Rnd_762x51_FNFAL_M",
		"CUP_20Rnd_762x51_FNFAL_M",
		"CUP_HandGrenade_M67",
		"CUP_HandGrenade_M67",
		"SmokeShell",
		"SmokeShell",
		"SmokeShell"
		};
		Items[]=
		{
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_morphine",
		"ACE_morphine"
		};
		respawntems[]=
		{
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_morphine",
		"ACE_morphine"	
		};
	};

	class Cold_War_Argentinian_AA: I_Soldier_F
	{
		_generalMacro="Cold_War_Argentinian_AA";
		scope=2;
		displayName="AA Rifleman";
		faction="argentinian_units";
		editorSubcategory = "Men_Argentina";
		vehicleClass="Men_Argentina";
		icon="iconMan";
		nakedUniform="U_BasicBody";
		uniformClass="SP_0000_Standard_BattleDressUniform_Green";
		backpack="";
		linkedItems[]=
		{
        "CUP_V_RUS_Smersh_1",
		"SP_M1Helmet_Green",
		"ItemCompass"
		};
		respawnLinkedItems[]=
		{
        "CUP_V_RUS_Smersh_1",
		"ItemMap",
		"ItemCompass"
		};
		weapons[]=
		{
		"Throw",
		"Put",	
		"CUP_arifle_FNFAL",
		"rhs_weap_fim92"
		};
		respawnweapons[]=
		{
		"Throw",
		"Put",	
		"CUP_arifle_FNFAL",
		"rhs_weap_fim92"
		};
		magazines[]=
		{
		"CUP_20Rnd_762x51_FNFAL_M",
		"CUP_20Rnd_762x51_FNFAL_M",		
		"CUP_20Rnd_762x51_FNFAL_M",
		"CUP_20Rnd_762x51_FNFAL_M",
		"CUP_20Rnd_762x51_FNFAL_M",
		"CUP_20Rnd_762x51_FNFAL_M",
		"CUP_HandGrenade_M67",
		"CUP_HandGrenade_M67",
		"SmokeShell",
		"SmokeShell",
		"rhs_fim92_mag"
		};
		Respawnmagazines[]=
		{
		"CUP_20Rnd_762x51_FNFAL_M",
		"CUP_20Rnd_762x51_FNFAL_M",		
		"CUP_20Rnd_762x51_FNFAL_M",
		"CUP_20Rnd_762x51_FNFAL_M",
		"CUP_20Rnd_762x51_FNFAL_M",
		"CUP_20Rnd_762x51_FNFAL_M",
		"CUP_HandGrenade_M67",
		"CUP_HandGrenade_M67",
		"SmokeShell",
		"SmokeShell",
		"rhs_fim92_mag"
		};
		Items[]=
		{
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_morphine",
		"ACE_morphine"
		};
		respawntems[]=
		{
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_morphine",
		"ACE_morphine"
		};
	};

	class Cold_War_Argentinian_AA_Assistant: I_Soldier_F
	{
		_generalMacro="Cold_War_Argentinian_AA_Assistant";
		scope=2;
		displayName="AA Assistant";
		faction="argentinian_units";
		editorSubcategory = "Men_Argentina";
		vehicleClass="Men_Argentina";
		icon="iconMan";
		nakedUniform="U_BasicBody";
		uniformClass="SP_0000_Standard_BattleDressUniform_Green";
		backpack="";
		linkedItems[]=
		{
        "CUP_V_RUS_Smersh_1",
		"SP_M1Helmet_Green",
		"ItemCompass"
		};
		respawnLinkedItems[]=
		{
        "CUP_V_RUS_Smersh_1",
		"ItemCompass"
		};
		weapons[]=
		{
		"Throw",
		"Put",	
		"CUP_arifle_FNFAL"
		};
		respawnweapons[]=
		{
		"Throw",
		"Put",
		"CUP_arifle_FNFAL"
		};
		magazines[]=
		{
		"CUP_HandGrenade_M67",
		"CUP_HandGrenade_M67",
		"CUP_20Rnd_762x51_FNFAL_M",
		"CUP_20Rnd_762x51_FNFAL_M",
		"CUP_20Rnd_762x51_FNFAL_M",
		"CUP_20Rnd_762x51_FNFAL_M",
		"CUP_20Rnd_762x51_FNFAL_M",
		"SmokeShell",
		"SmokeShell",
		"rhs_fim92_mag"
		};
		Respawnmagazines[]=
		{
		"CUP_HandGrenade_M67",
		"CUP_HandGrenade_M67",
		"CUP_20Rnd_762x51_FNFAL_M",
		"CUP_20Rnd_762x51_FNFAL_M",
		"CUP_20Rnd_762x51_FNFAL_M",
		"CUP_20Rnd_762x51_FNFAL_M",
		"CUP_20Rnd_762x51_FNFAL_M",
		"SmokeShell",
		"SmokeShell",
		"rhs_fim92_mag"
		};
		Items[]=
		{
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_morphine",
		"ACE_morphine"
		};
		respawntems[]=
		{
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_morphine",
		"ACE_morphine"
		};
	};

	class Cold_War_Argentinian_Machinegunner: I_Soldier_F
	{
		_generalMacro="Cold_War_Argentinian_Machinegunner";
		scope=2;
		displayName="Machinegunner";
		faction="argentinian_units";
		editorSubcategory = "Men_Argentina";
		vehicleClass="Men_Argentina";
		icon="iconMan";
		nakedUniform="U_BasicBody";
		uniformClass="SP_0000_Standard_BattleDressUniform_Green";
		backpack="";
		linkedItems[]=
		{
        "CUP_V_RUS_Smersh_1",
		"SP_M1Helmet_Green",
		"ItemCompass"
		};
		respawnLinkedItems[]=
		{
        "CUP_V_RUS_Smersh_1",
		"ItemCompass"
		};
		weapons[]=
		{
		"Throw",
		"Put",	
		"CUP_lmg_L7A2"
		};
		respawnweapons[]=
		{
		"Throw",
		"Put",	
		"CUP_lmg_L7A2"
		};
		magazines[]=
		{
		"CUP_100Rnd_TE4_LRT4_White_Tracer_762x51_Belt_M",
		"CUP_100Rnd_TE4_LRT4_White_Tracer_762x51_Belt_M",
		"CUP_100Rnd_TE4_LRT4_White_Tracer_762x51_Belt_M",
		"CUP_100Rnd_TE4_LRT4_White_Tracer_762x51_Belt_M",
		"CUP_HandGrenade_M67",
		"CUP_HandGrenade_M67",
		"SmokeShell",
		"SmokeShell"
		};
		Respawnmagazines[]=
		{
		"CUP_100Rnd_TE4_LRT4_White_Tracer_762x51_Belt_M",
		"CUP_100Rnd_TE4_LRT4_White_Tracer_762x51_Belt_M",
		"CUP_100Rnd_TE4_LRT4_White_Tracer_762x51_Belt_M",
		"CUP_100Rnd_TE4_LRT4_White_Tracer_762x51_Belt_M",
		"CUP_100Rnd_TE4_LRT4_White_Tracer_762x51_Belt_M",
		"CUP_100Rnd_TE4_LRT4_White_Tracer_762x51_Belt_M",
		"CUP_100Rnd_TE4_LRT4_White_Tracer_762x51_Belt_M",
		"CUP_HandGrenade_M67",
		"CUP_HandGrenade_M67",
		"SmokeShell",
		"SmokeShell"
		};
		Items[]=
		{
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_morphine",
		"ACE_morphine"
		};
		respawntems[]=
		{
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_morphine",
		"ACE_morphine"		
		};		
	};
		class Cold_War_Argentinian_MG_Assistant: I_Soldier_F
	{
		_generalMacro="Cold_War_Argentinian_MG_Assistant";
		scope=2;
		displayName="MG Assistant";
		faction="argentinian_units";
		editorSubcategory = "Men_Argentina";
		vehicleClass="Men_Argentina";
		icon="iconMan";
		nakedUniform="U_BasicBody";
		uniformClass="SP_0000_Standard_BattleDressUniform_Green";
		backpack="";
		linkedItems[]=
		{
        "CUP_V_RUS_Smersh_1",
		"SP_M1Helmet_Green",
		"ItemCompass"
		};
		respawnLinkedItems[]=
		{
        "CUP_V_RUS_Smersh_1",
		"ItemCompass"
		};
		weapons[]=
		{
		"Throw",
		"Put",	
		"CUP_arifle_FNFAL"
		};
		respawnweapons[]=
		{
		"Throw",
		"Put",
		"CUP_arifle_FNFAL"
		};
		magazines[]=
		{
		"CUP_HandGrenade_M67",
		"CUP_HandGrenade_M67",
		"CUP_20Rnd_762x51_FNFAL_M",
		"CUP_20Rnd_762x51_FNFAL_M",
		"CUP_20Rnd_762x51_FNFAL_M",
		"CUP_20Rnd_762x51_FNFAL_M",
		"CUP_20Rnd_762x51_FNFAL_M",
		"SmokeShell",
		"SmokeShell",
		"CUP_100Rnd_TE4_LRT4_White_Tracer_762x51_Belt_M",
		"CUP_100Rnd_TE4_LRT4_White_Tracer_762x51_Belt_M",
		"CUP_100Rnd_TE4_LRT4_White_Tracer_762x51_Belt_M"
		};
		Respawnmagazines[]=
		{
		"CUP_HandGrenade_M67",
		"CUP_HandGrenade_M67",
		"CUP_20Rnd_762x51_FNFAL_M",
		"CUP_20Rnd_762x51_FNFAL_M",
		"CUP_20Rnd_762x51_FNFAL_M",
		"CUP_20Rnd_762x51_FNFAL_M",
		"CUP_20Rnd_762x51_FNFAL_M",
		"SmokeShell",
		"SmokeShell",
		"CUP_100Rnd_TE4_LRT4_White_Tracer_762x51_Belt_M",
		"CUP_100Rnd_TE4_LRT4_White_Tracer_762x51_Belt_M",
		"CUP_100Rnd_TE4_LRT4_White_Tracer_762x51_Belt_M"
		};
		Items[]=
		{
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_morphine",
		"ACE_morphine"
		};
		respawntems[]=
		{
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_morphine",
		"ACE_morphine"
		};
	};