
   class Modern_British_Coin_Squadleader: B_Soldier_base_F
	{
		_generalMacro="Coin_British_Squadleader";
		scope=2;
		displayName="Section Leader(Coin)";
		faction="twc_faction";
		editorSubcategory = "Men_ModernCoin";
		vehicleClass="Men_ModernCoin";
		icon="iconManLeader";
		nakedUniform="U_BasicBody";
		uniformClass="UK3CB_BAF_U_CombatUniform_MTP";
		backpack="TWC_Backpack_Modern_Sectionlead";
		linkedItems[]=
		{
        "UK3CB_BAF_H_Mk7_Scrim_ESS_B",
		"UK3CB_BAF_V_Osprey_SL_D",
		"ItemMap",
		"ItemcTab",
		"ItemCompass",
		"ACRE_PRC343",
		"ItemWatch",
		"UK3CB_BAF_G_Tactical_Black"
		};
		respawnLinkedItems[]=
		{
        "UK3CB_BAF_H_Mk7_Scrim_ESS_B",
		"UK3CB_BAF_V_Osprey_SL_D",
		"ItemMap",
		"ItemcTab",
		"ItemCompass",
		"ItemWatch",
		"ACRE_PRC343",
		"UK3CB_BAF_G_Tactical_Black"
		};
		weapons[]=
		{
		"Throw",
		"Put",
		"ACE_Vector",
		"UK3CB_BAF_L85A2_RIS_AFG_ELCAN3D",
		"UK3CB_BAF_L131A1"
		};
		respawnweapons[]=
		{
		"Throw",
		"Put",
		"ACE_Vector",
		"UK3CB_BAF_L85A2_RIS_AFG_ELCAN3D",
		"UK3CB_BAF_L131A1"
		};
		magazines[]=
		{
		"UK3CB_BAF_9_17Rnd",
		"UK3CB_BAF_9_17Rnd",
		"UK3CB_BAF_556_30Rnd_T",
		"UK3CB_BAF_556_30Rnd_T",
		"UK3CB_BAF_556_30Rnd",
		"UK3CB_BAF_556_30Rnd",
		"UK3CB_BAF_556_30Rnd",
		"UK3CB_BAF_556_30Rnd",
		"UK3CB_BAF_556_30Rnd",
		"UK3CB_BAF_556_30Rnd",
		"UK3CB_BAF_556_30Rnd",
		"UK3CB_BAF_556_30Rnd",
		"CUP_HandGrenade_L109A2_HE",
		"CUP_HandGrenade_L109A2_HE",
		"B_IR_Grenade"
		};
		Respawnmagazines[]=
		{
		"UK3CB_BAF_9_17Rnd",
		"UK3CB_BAF_9_17Rnd",
		"UK3CB_BAF_556_30Rnd_T",
		"UK3CB_BAF_556_30Rnd_T",
		"UK3CB_BAF_556_30Rnd",
		"UK3CB_BAF_556_30Rnd",
		"UK3CB_BAF_556_30Rnd",
		"UK3CB_BAF_556_30Rnd",
		"UK3CB_BAF_556_30Rnd",
		"UK3CB_BAF_556_30Rnd",
		"UK3CB_BAF_556_30Rnd",
		"UK3CB_BAF_556_30Rnd",
		"CUP_HandGrenade_L109A2_HE",
		"CUP_HandGrenade_L109A2_HE",
		"B_IR_Grenade"
		};
		Items[]=
		{
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_morphine",
		"ACE_morphine",
		"ACE_epinephrine",
		"ACE_tourniquet",
		"ACE_Flashlight_KSF1",
		"ACE_IR_Strobe_Item",
	    "ACE_MapTools",
		"UK3CB_BAF_HMNVS",
		"ACRE_PRC343",
		"ACE_EarPlugs"
		};
		respawntems[]=
		{
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_morphine",
		"ACE_morphine",
		"ACE_epinephrine",
		"ACE_tourniquet",
		"ACE_Flashlight_KSF1",
		"ACE_IR_Strobe_Item",
	    "ACE_MapTools",
		"UK3CB_BAF_HMNVS",
		"ACRE_PRC343",
		"ACE_EarPlugs"		
		};
	};	
	class Modern_British_Coin_Pointman: B_Soldier_base_F
	{
		_generalMacro="British_Coin_Pointman";
		scope=2;
		displayName="PointMan(Coin)";
		faction="twc_faction";
		editorSubcategory = "Men_ModernCoin";
		vehicleClass="Men_ModernCoin";
		icon="iconMan";
		nakedUniform="U_BasicBody";
		uniformClass="UK3CB_BAF_U_CombatUniform_MTP";
		backpack="TWC_Backpack_Modern_Pointman";
		linkedItems[]=
		{
        "UK3CB_BAF_V_Osprey_Rifleman_B",
		"UK3CB_BAF_H_Mk7_Scrim_B",
		"ItemMap",
		"ItemCompass",
		"ItemWatch",
		"ACRE_PRC343",
		"UK3CB_BAF_G_Tactical_Black"
		};
		respawnLinkedItems[]=
		{
        "UK3CB_BAF_V_Osprey_Rifleman_B",
		"UK3CB_BAF_H_Mk7_Scrim_B",
		"ItemMap",
		"ItemCompass",
		"ItemWatch",
		"UK3CB_BAF_G_Tactical_Black",
		"ACRE_PRC343"
		};
		weapons[]=
		{
		"Throw",
		"Put",	
		"UK3CB_BAF_L85A2_RIS_AFG_ELCAN3D",
		"ACE_VMH3",
		"HAFM_LAW"
		};
		respawnweapons[]=
		{
		"Throw",
		"Put",	
		"UK3CB_BAF_L85A2_RIS_AFG_ELCAN3D",
		"ACE_VMH3",
		"HAFM_LAW"
		};
		magazines[]=
		{
		"UK3CB_BAF_556_30Rnd",
		"UK3CB_BAF_556_30Rnd",
		"UK3CB_BAF_556_30Rnd",
		"UK3CB_BAF_556_30Rnd",
		"UK3CB_BAF_556_30Rnd",
		"UK3CB_BAF_556_30Rnd",
		"UK3CB_BAF_556_30Rnd",
		"UK3CB_BAF_556_30Rnd",
		"UK3CB_BAF_556_30Rnd_T",
		"UK3CB_BAF_556_30Rnd_T",
		"CUP_HandGrenade_L109A2_HE",
		"CUP_HandGrenade_L109A2_HE"
		};
		Respawnmagazines[]=
		{
		"UK3CB_BAF_556_30Rnd",
		"UK3CB_BAF_556_30Rnd",
		"UK3CB_BAF_556_30Rnd",
		"UK3CB_BAF_556_30Rnd",
		"UK3CB_BAF_556_30Rnd",
		"UK3CB_BAF_556_30Rnd",
		"UK3CB_BAF_556_30Rnd",
		"UK3CB_BAF_556_30Rnd",
		"UK3CB_BAF_556_30Rnd_T",
		"UK3CB_BAF_556_30Rnd_T",
		"CUP_HandGrenade_L109A2_HE",
		"CUP_HandGrenade_L109A2_HE"
		};
		Items[]=
		{
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_morphine",
		"ACE_morphine",
		"ACE_epinephrine",
		"ACE_tourniquet",
		"ACE_EarPlugs",	
		"UK3CB_BAF_HMNVS",
		"ACRE_PRC343"
		};
		respawntems[]=
		{
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_morphine",
		"ACE_morphine",
		"ACE_epinephrine",
		"ACE_tourniquet",
		"ACE_EarPlugs",	
		"UK3CB_BAF_HMNVS",
		"ACRE_PRC343"	
		};		
	};

class Modern_British_Coin_Grenadier: B_Soldier_base_F
	{
		_generalMacro="Modern_British_Coin_Grenadier";
		scope=2;
		displayName="Grenadier(Coin)";
		faction="twc_faction";
		editorSubcategory = "Men_ModernCoin";
		vehicleClass="Men_ModernCoin";
		icon="iconManExplosive";
		nakedUniform="U_BasicBody";
		uniformClass="UK3CB_BAF_U_CombatUniform_MTP";
		backpack="TWC_Backpack_Modern_Grenadier";
		linkedItems[]=
		{
        "UK3CB_BAF_V_Osprey_Grenadier_B",
		"UK3CB_BAF_H_Mk7_Scrim_A",
		"ItemMap",
		"ItemCompass",
		"ItemWatch",
		"ACRE_PRC343",
		"UK3CB_BAF_G_Tactical_Black"
		};
		respawnLinkedItems[]=
		{
        "UK3CB_BAF_V_Osprey_Grenadier_B",
		"UK3CB_BAF_H_Mk7_Scrim_A",
		"ItemMap",
		"ItemCompass",
		"ItemWatch",
		"ACRE_PRC343",
		"UK3CB_BAF_G_Tactical_Black"
		};
		weapons[]=
		{
		"Throw",
		"Put",
		"ACE_Vector",
		"UK3CB_BAF_L85A2_UGL_ELCAN3D",
		"UK3CB_BAF_L131A1",
		"HAFM_LAW"
		};
		respawnweapons[]=
		{
		"Throw",
		"Put",
		"ACE_Vector",
		"UK3CB_BAF_L85A2_UGL_ELCAN3D",
		"UK3CB_BAF_L131A1",
		"HAFM_LAW"
		};
		magazines[]=
		{
		"UK3CB_BAF_9_17Rnd",
		"UK3CB_BAF_9_17Rnd",
		"UK3CB_BAF_556_30Rnd",
		"UK3CB_BAF_556_30Rnd",
		"UK3CB_BAF_556_30Rnd",
		"UK3CB_BAF_556_30Rnd",
		"UK3CB_BAF_556_30Rnd",
		"UK3CB_BAF_556_30Rnd",
		"UK3CB_BAF_556_30Rnd",		
		"UK3CB_BAF_556_30Rnd",
		"UK3CB_BAF_556_30Rnd_T",
		"UK3CB_BAF_556_30Rnd_T",
		"CUP_HandGrenade_L109A2_HE",
		"CUP_HandGrenade_L109A2_HE"
		};
		Respawnmagazines[]=
		{
		"UK3CB_BAF_9_17Rnd",
		"UK3CB_BAF_9_17Rnd",
		"UK3CB_BAF_556_30Rnd",
		"UK3CB_BAF_556_30Rnd",
		"UK3CB_BAF_556_30Rnd",
		"UK3CB_BAF_556_30Rnd",
		"UK3CB_BAF_556_30Rnd",
		"UK3CB_BAF_556_30Rnd",
		"UK3CB_BAF_556_30Rnd",		
		"UK3CB_BAF_556_30Rnd",
		"UK3CB_BAF_556_30Rnd_T",
		"UK3CB_BAF_556_30Rnd_T",
		"CUP_HandGrenade_L109A2_HE",
		"CUP_HandGrenade_L109A2_HE"
		};
		Items[]=
		{
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_morphine",
		"ACE_morphine",
		"ACE_epinephrine",
		"ACE_tourniquet",
		"ACE_EarPlugs",	
		"UK3CB_BAF_HMNVS",
		"ACRE_PRC343"
		};
		respawntems[]=
		{
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_morphine",
		"ACE_morphine",
		"ACE_epinephrine",
		"ACE_tourniquet",
		"ACE_EarPlugs",	
		"UK3CB_BAF_HMNVS",
		"ACRE_PRC343"			
		};
	};

	class Modern_British_Coin_Automaticrifleman: B_Soldier_base_F
	{
		_generalMacro="Modern_British_Coin_Automaticrifleman";
		scope=2;
		displayName="Automatic Rifleman(Coin)";
		faction="twc_faction";
		editorSubcategory = "Men_ModernCoin";
		vehicleClass="Men_ModernCoin";
		icon="iconManMG";
		nakedUniform="U_BasicBody";
		uniformClass="UK3CB_BAF_U_CombatUniform_MTP";
		backpack="TWC_Backpack_Modern_Automatic_Rifleman";
		linkedItems[]=
		{
        "UK3CB_BAF_V_Osprey_MG_B",
		"UK3CB_BAF_H_Mk7_Scrim_C",
		"ItemMap",
		"ItemCompass",
		"ItemWatch",
		"UK3CB_BAF_G_Tactical_Black",
		"ACRE_PRC343"
		};
		respawnLinkedItems[]=
		{
        "UK3CB_BAF_V_Osprey_MG_B",
		"UK3CB_BAF_H_Mk7_Scrim_C",
		"ItemMap",
		"ItemCompass",
		"ItemWatch",
		"ACRE_PRC343",
		"UK3CB_BAF_G_Tactical_Black"
		};
		weapons[]=
		{
		"Throw",
		"Put",	
		"UK3CB_BAF_L110A2_ELCAN3D",
		"UK3CB_BAF_L131A1",
		"HAFM_LAW"
		};
		respawnweapons[]=
		{
		"Throw",
		"Put",	
		"UK3CB_BAF_L110A2_ELCAN3D",
		"UK3CB_BAF_L131A1",
		"HAFM_LAW"
		};
		magazines[]=
		{
		"UK3CB_BAF_9_17Rnd",
		"UK3CB_BAF_9_17Rnd",
		"UK3CB_BAF_556_200Rnd",
		"UK3CB_BAF_556_200Rnd",
		"CUP_HandGrenade_L109A2_HE",
		"CUP_HandGrenade_L109A2_HE"
		};
		Respawnmagazines[]=
		{
		"UK3CB_BAF_9_17Rnd",
		"UK3CB_BAF_9_17Rnd",
		"UK3CB_BAF_556_200Rnd",
		"UK3CB_BAF_556_200Rnd",
		"CUP_HandGrenade_L109A2_HE",
		"CUP_HandGrenade_L109A2_HE"
		};
		Items[]=
		{
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_morphine",
		"ACE_morphine",
		"ACE_epinephrine",
		"ACE_tourniquet",
		"ACE_EarPlugs",	
		"UK3CB_BAF_HMNVS",
		"ACRE_PRC343"
		};
		respawntems[]=
		{
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_morphine",
		"ACE_morphine",
		"ACE_epinephrine",
		"ACE_tourniquet",
		"ACE_EarPlugs",	
		"UK3CB_BAF_HMNVS",
		"ACRE_PRC343"		
		};
	};

	class Modern_British_Coin_2IC: B_Soldier_base_F
	{
		_generalMacro="Modern_British_Coin_2IC";
		scope=2;
		displayName="2IC(Coin)";
		faction="twc_faction";
		editorSubcategory = "Men_ModernCoin";
		vehicleClass="Men_ModernCoin";
		icon="iconMan";
		nakedUniform="U_BasicBody";
		uniformClass="UK3CB_BAF_U_CombatUniform_MTP";
		backpack="TWC_Backpack_Modern_Coin_2IC";
		linkedItems[]=
		{
        "UK3CB_BAF_V_Osprey_Rifleman_C",
		"UK3CB_BAF_H_Mk7_Scrim_ESS_B",
		"ItemMap",
		"ItemCompass",
		"ItemWatch",
		"ACRE_PRC343",
		"UK3CB_BAF_G_Tactical_Black"
		};
		respawnLinkedItems[]=
		{
        "UK3CB_BAF_V_Osprey_Rifleman_C",
		"UK3CB_BAF_H_Mk7_Scrim_ESS_B",
		"ItemMap",
		"ItemCompass",
		"ItemWatch",
		"ACRE_PRC343",
		"UK3CB_BAF_G_Tactical_Black"
		};
		weapons[]=
		{
		"Throw",
		"Put",
		"ACE_Vector",
		"UK3CB_BAF_L85A2_RIS_AFG_ELCAN3D",
		"UK3CB_BAF_L131A1"
		};
		respawnweapons[]=
		{
		"Throw",
		"Put",
		"ACE_Vector",
		"UK3CB_BAF_L85A2_RIS_AFG_ELCAN3D",
		"UK3CB_BAF_L131A1"
		};
		magazines[]=
		{
		"UK3CB_BAF_9_17Rnd",
		"UK3CB_BAF_9_17Rnd",
		"UK3CB_BAF_556_30Rnd",
		"UK3CB_BAF_556_30Rnd",		
		"UK3CB_BAF_556_30Rnd",
		"UK3CB_BAF_556_30Rnd",
		"UK3CB_BAF_556_30Rnd",
		"UK3CB_BAF_556_30Rnd",
		"UK3CB_BAF_556_30Rnd",
		"UK3CB_BAF_556_30Rnd",
		"UK3CB_BAF_556_30Rnd_T",
		"UK3CB_BAF_556_30Rnd_T",
		"CUP_HandGrenade_L109A2_HE",
		"CUP_HandGrenade_L109A2_HE",
		"B_IR_Grenade"
		};
		Respawnmagazines[]=
		{
		"UK3CB_BAF_9_17Rnd",
		"UK3CB_BAF_9_17Rnd",
		"UK3CB_BAF_556_30Rnd",
		"UK3CB_BAF_556_30Rnd",		
		"UK3CB_BAF_556_30Rnd",
		"UK3CB_BAF_556_30Rnd",
		"UK3CB_BAF_556_30Rnd",
		"UK3CB_BAF_556_30Rnd",
		"UK3CB_BAF_556_30Rnd",
		"UK3CB_BAF_556_30Rnd",
		"UK3CB_BAF_556_30Rnd_T",
		"UK3CB_BAF_556_30Rnd_T",
		"CUP_HandGrenade_L109A2_HE",
		"CUP_HandGrenade_L109A2_HE",
		"B_IR_Grenade"
		};
		Items[]=
		{
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_morphine",
		"ACE_morphine",
		"ACE_epinephrine",
		"ACE_tourniquet",
		"ACE_EarPlugs",	
		"ACRE_PRC343",
		"UK3CB_BAF_HMNVS"
		};
		respawntems[]=
		{
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_morphine",
		"ACE_morphine",
		"ACE_epinephrine",
		"ACE_tourniquet",
		"ACE_EarPlugs",	
		"ACRE_PRC343",
		"UK3CB_BAF_HMNVS"			
		};
	};
	class Modern_British_Coin_Machinegunner: B_Soldier_base_F
	{
		_generalMacro="Modern_British_Coin_Machinegunner";
		scope=2;
		displayName="Machine Gunner(Coin)";
		faction="twc_faction";
		editorSubcategory = "Men_ModernCoin";
		vehicleClass="Men_ModernCoin";
		icon="iconMan";
		nakedUniform="U_BasicBody";
		uniformClass="UK3CB_BAF_U_CombatUniform_MTP";
		backpack="TWC_Backpack_Modern_Machine_Gunner";
		linkedItems[]=
		{
        "UK3CB_BAF_V_Osprey_MG_B",
		"UK3CB_BAF_H_Mk7_Scrim_D",
		"ItemMap",
		"ItemCompass",
		"ItemWatch",
		"UK3CB_BAF_G_Tactical_Black",
		"ACRE_PRC343"
		};
		respawnLinkedItems[]=
		{
        "UK3CB_BAF_V_Osprey_MG_B",
		"UK3CB_BAF_H_Mk7_Scrim_D",
		"ItemMap",
		"ItemCompass",
		"ItemWatch",
		"UK3CB_BAF_G_Tactical_Black",
		"ACRE_PRC343"
		};
		weapons[]=
		{
		"Throw",
		"Put",	
		"UK3CB_BAF_L7A2",
		"UK3CB_BAF_L131A1"
		};
		respawnweapons[]=
		{
		"Throw",
		"Put",	
		"UK3CB_BAF_L7A2",
		"UK3CB_BAF_L131A1"
		};
		magazines[]=
		{
		"UK3CB_BAF_9_17Rnd",
		"UK3CB_BAF_9_17Rnd",
		"UK3CB_BAF_762_100Rnd",
		"UK3CB_BAF_762_100Rnd",
		"CUP_HandGrenade_L109A2_HE",
		"CUP_HandGrenade_L109A2_HE"
		};
		Respawnmagazines[]=
		{
		"UK3CB_BAF_9_17Rnd",
		"UK3CB_BAF_9_17Rnd",
		"UK3CB_BAF_762_100Rnd",
		"UK3CB_BAF_762_100Rnd",
		"CUP_HandGrenade_L109A2_HE",
		"CUP_HandGrenade_L109A2_HE"
		};
		Items[]=
		{
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_morphine",
		"ACE_morphine",
		"ACE_epinephrine",
		"ACE_tourniquet",
		"ACE_EarPlugs",	
		"UK3CB_BAF_HMNVS",
		"ACRE_PRC343"
		};
		respawntems[]=
		{
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_morphine",
		"ACE_morphine",
		"ACE_epinephrine",
		"ACE_tourniquet",
		"ACE_EarPlugs",	
		"UK3CB_BAF_HMNVS",
		"ACRE_PRC343"	
		};
	};

	class Modern_British_Coin_Marksman: B_Soldier_base_F
	{
		_generalMacro="Modern_British_Coin_Marksman";
		scope=2;
		displayName="Marksman(Coin)";
		faction="twc_faction";
		editorSubcategory = "Men_ModernCoin";
		vehicleClass="Men_ModernCoin";
		icon="iconMan";
		nakedUniform="U_BasicBody";
		uniformClass="UK3CB_BAF_U_CombatUniform_MTP";
		backpack="TWC_Backpack_Modern_Marksman";
		linkedItems[]=
		{
        "UK3CB_BAF_V_Osprey_Marksman_A",
		"UK3CB_BAF_H_Mk7_Scrim_E",
		"ItemMap",
		"ItemCompass",
		"ItemWatch",
		"UK3CB_BAF_G_Tactical_Black",
		"ACRE_PRC343"
		};
		respawnLinkedItems[]=
		{
        "UK3CB_BAF_V_Osprey_Marksman_A",
		"UK3CB_BAF_H_Mk7_Scrim_E",
		"ItemMap",
		"ItemCompass",
		"ItemWatch",
		"ACRE_PRC343",
		"UK3CB_BAF_G_Tactical_Black"
		};
		weapons[]=
		{
		"Throw",
		"Put",	
		"ACE_Vector",
		"UK3CB_BAF_L129A1_Grippod_TA648",
		"UK3CB_BAF_L131A1",
		"HAFM_LAW"
		};
		respawnweapons[]=
		{
		"Throw",
		"Put",
		"ACE_Vector",
		"UK3CB_BAF_L129A1_Grippod_TA648",
		"UK3CB_BAF_L131A1",
		"HAFM_LAW"
		};
		magazines[]=
		{
		"UK3CB_BAF_762_L42A1_20Rnd",
		"UK3CB_BAF_762_L42A1_20Rnd",
		"UK3CB_BAF_762_L42A1_20Rnd",
		"UK3CB_BAF_762_L42A1_20Rnd",
		"UK3CB_BAF_762_L42A1_20Rnd",
		"UK3CB_BAF_762_L42A1_20Rnd",
		"UK3CB_BAF_762_L42A1_20Rnd",
		"UK3CB_BAF_762_L42A1_20Rnd",
		"UK3CB_BAF_762_L42A1_20Rnd_T",
		"UK3CB_BAF_762_L42A1_20Rnd_T",
		"CUP_HandGrenade_L109A2_HE",
		"CUP_HandGrenade_L109A2_HE"
		};
		Respawnmagazines[]=
		{
		"UK3CB_BAF_762_L42A1_20Rnd",
		"UK3CB_BAF_762_L42A1_20Rnd",
		"UK3CB_BAF_762_L42A1_20Rnd",
		"UK3CB_BAF_762_L42A1_20Rnd",
		"UK3CB_BAF_762_L42A1_20Rnd",
		"UK3CB_BAF_762_L42A1_20Rnd",
		"UK3CB_BAF_762_L42A1_20Rnd",
		"UK3CB_BAF_762_L42A1_20Rnd",
		"UK3CB_BAF_762_L42A1_20Rnd_T",
		"UK3CB_BAF_762_L42A1_20Rnd_T",
		"CUP_HandGrenade_L109A2_HE",
		"CUP_HandGrenade_L109A2_HE"
		};
		Items[]=
		{
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_morphine",
		"ACE_morphine",
		"ACE_epinephrine",
		"ACE_tourniquet",
		"ACE_EarPlugs",	
		"UK3CB_BAF_HMNVS",
		"ACRE_PRC343"
		};
		respawntems[]=
		{
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_morphine",
		"ACE_morphine",
		"ACE_epinephrine",
		"ACE_tourniquet",
		"ACE_EarPlugs",	
		"UK3CB_BAF_HMNVS",
		"ACRE_PRC343"	
		};		
	};
	class Modern_British_Coin_Platoon_Commander: B_Soldier_base_F
	{
		_generalMacro="Modern_British_Squadleader";
		scope=2;
		displayName="Platoon Commander(Coin)";
		faction="twc_faction";
		editorSubcategory = "Men_ModernCoin";
		vehicleClass="Men_ModernCoin";
		icon="iconManLeader";
		nakedUniform="U_BasicBody";
		uniformClass="UK3CB_BAF_U_CombatUniform_MTP";
		backpack="TWC_Backpack_Modern_Platoon_Command";
		linkedItems[]=
		{
        "UK3CB_BAF_V_Osprey_Holster",
		"UK3CB_BAF_H_Mk7_Camo_D",
		"ItemMap",
		"ItemcTab",
		"ItemCompass",
		"ItemWatch",
		"ACRE_PRC343",
		"UK3CB_BAF_G_Tactical_Black"
		};
		respawnLinkedItems[]=
		{
        "UK3CB_BAF_V_Osprey_Holster",
		"UK3CB_BAF_H_Mk7_Camo_D",
		"ItemMap",
		"ItemcTab",
		"ItemCompass",
		"ItemWatch",
		"ACRE_PRC343",
		"UK3CB_BAF_G_Tactical_Black"
		};
		weapons[]=
		{
		"Throw",
		"Put",
		"Binocular",
		"UK3CB_BAF_L85A2_RIS_AFG_ELCAN3D",
		"UK3CB_BAF_L131A1"
		};
		respawnweapons[]=
		{
		"Throw",
		"Put",
		"Binocular",
		"UK3CB_BAF_L85A2_RIS_AFG_ELCAN3D",
		"UK3CB_BAF_L131A1"
		};
		magazines[]=
		{
		"UK3CB_BAF_9_17Rnd",
		"UK3CB_BAF_9_17Rnd",
		"UK3CB_BAF_556_30Rnd",
		"UK3CB_BAF_556_30Rnd",
		"UK3CB_BAF_556_30Rnd",
		"UK3CB_BAF_556_30Rnd_T",
		"UK3CB_BAF_556_30Rnd_T",
		"CUP_HandGrenade_L109A2_HE",
		"CUP_HandGrenade_L109A2_HE",
		"B_IR_Grenade"
		};
		Respawnmagazines[]=
		{
		"UK3CB_BAF_9_17Rnd",
		"UK3CB_BAF_9_17Rnd",
		"UK3CB_BAF_556_30Rnd",
		"UK3CB_BAF_556_30Rnd",
		"UK3CB_BAF_556_30Rnd",
		"UK3CB_BAF_556_30Rnd_T",
		"UK3CB_BAF_556_30Rnd_T",
		"CUP_HandGrenade_L109A2_HE",
		"CUP_HandGrenade_L109A2_HE",
		"B_IR_Grenade"
		};
		Items[]=
		{
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_morphine",
		"ACE_morphine",
		"ACE_epinephrine",
		"ACE_tourniquet",
		"ACE_Flashlight_KSF1",
		"ACE_IR_Strobe_Item",
	    "ACE_MapTools",
		"UK3CB_BAF_HMNVS",
		"ACE_EarPlugs",
		"ACRE_PRC343"

		};
		respawntems[]=
		{
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_morphine",
		"ACE_morphine",
		"ACE_epinephrine",
		"ACE_tourniquet",
		"ACE_Flashlight_KSF1",
		"ACE_IR_Strobe_Item",
	    "ACE_MapTools",
		"UK3CB_BAF_HMNVS",
		"ACE_EarPlugs",
		"ACRE_PRC343"		
		};
	};
	class Modern_British_Coin_Platoon_Sergeant: B_Soldier_base_F
	{
		_generalMacro="Modern_British_Squadleader";
		scope=2;
		displayName="Platoon Sergeant(Coin)";
		faction="twc_faction";
		editorSubcategory = "Men_ModernCoin";
		vehicleClass="Men_ModernCoin";
		icon="iconManLeader";
		nakedUniform="U_BasicBody";
		uniformClass="UK3CB_BAF_U_CombatUniform_MTP";
		backpack="TWC_Backpack_Modern_Platoon_Sergeant";
		linkedItems[]=
		{
        "UK3CB_BAF_V_Osprey_Holster",
		"UK3CB_BAF_H_Mk7_Camo_B",
		"ItemMap",
		"ItemcTab",
		"ItemCompass",
		"ItemWatch",
		"ACRE_PRC343",
		"UK3CB_BAF_G_Tactical_Black"
		};
		respawnLinkedItems[]=
		{
        "UK3CB_BAF_V_Osprey_Holster",
		"UK3CB_BAF_H_Mk7_Camo_B",
		"ItemMap",
		"ItemcTab",
		"ItemCompass",
		"ItemWatch",
		"ACRE_PRC343",
		"UK3CB_BAF_G_Tactical_Black"
		};
		weapons[]=
		{
		"Throw",
		"Put",	
		"Binocular",
		"UK3CB_BAF_L85A2_RIS_AFG_ELCAN3D",
		"UK3CB_BAF_L131A1"
		};
		respawnweapons[]=
		{
		"Throw",
		"Put",
		"Binocular",
		"UK3CB_BAF_L85A2_RIS_AFG_ELCAN3D",
		"UK3CB_BAF_L131A1"
		};
		magazines[]=
		{
		"UK3CB_BAF_9_17Rnd",
		"UK3CB_BAF_9_17Rnd",
		"UK3CB_BAF_556_30Rnd",
		"UK3CB_BAF_556_30Rnd",
		"UK3CB_BAF_556_30Rnd",
		"UK3CB_BAF_556_30Rnd_T",
		"UK3CB_BAF_556_30Rnd_T",
		"CUP_HandGrenade_L109A2_HE",
		"CUP_HandGrenade_L109A2_HE",
		"B_IR_Grenade"
		};
		Respawnmagazines[]=
		{
		"UK3CB_BAF_9_17Rnd",
		"UK3CB_BAF_9_17Rnd",
		"UK3CB_BAF_556_30Rnd",
		"UK3CB_BAF_556_30Rnd",
		"UK3CB_BAF_556_30Rnd",
		"UK3CB_BAF_556_30Rnd",
		"UK3CB_BAF_556_30Rnd_T",
		"UK3CB_BAF_556_30Rnd_T",
		"CUP_HandGrenade_L109A2_HE",
		"CUP_HandGrenade_L109A2_HE",
		"B_IR_Grenade"
		};
		Items[]=
		{
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_morphine",
		"ACE_morphine",
		"ACE_epinephrine",
		"ACE_tourniquet",
		"ACE_Flashlight_KSF1",
		"ACE_IR_Strobe_Item",
	    "ACE_MapTools",
		"UK3CB_BAF_HMNVS",
		"ACE_EarPlugs",
		"ACRE_PRC343"
		};
		respawntems[]=
		{
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_morphine",
		"ACE_morphine",
		"ACE_epinephrine",
		"ACE_tourniquet",
		"ACE_Flashlight_KSF1",
		"ACE_IR_Strobe_Item",
	    "ACE_MapTools",
		"UK3CB_BAF_HMNVS",
		"ACE_EarPlugs",
		"ACRE_PRC343"		
		};
	};
	class Modern_British_Coin_Medic: B_Soldier_base_F
	{
		_generalMacro="Modern_British_Marksman";
		scope=2;
		displayName="Medic(Coin)";
		faction="twc_faction";
		editorSubcategory = "Men_ModernCoin";
		vehicleClass="Men_ModernCoin";
		icon="iconMan";
		nakedUniform="U_BasicBody";
		uniformClass="UK3CB_BAF_U_CombatUniform_MTP";
		backpack="TWC_Backpack_Modern_Medic";
		linkedItems[]=
		{
        "UK3CB_BAF_V_Osprey_Medic_D",
		"UK3CB_BAF_H_Mk7_Camo_CESS_D",
		"ItemMap",
		"ItemCompass",
		"ItemWatch",
		"UK3CB_BAF_G_Tactical_Black",
		"ACRE_PRC343"
		};
		respawnLinkedItems[]=
		{
        "UK3CB_BAF_V_Osprey_Medic_D",
		"UK3CB_BAF_H_Mk7_Camo_CESS_D",
		"ItemMap",
		"ItemCompass",
		"ItemWatch",
		"ACRE_PRC343",
		"UK3CB_BAF_G_Tactical_Black"
		};
		weapons[]=
		{
		"Throw",
		"Put",	
		"UK3CB_BAF_L85A2_RIS_AFG_ELCAN3D",
		"UK3CB_BAF_L131A1"
		};
		respawnweapons[]=
		{
		"Throw",
		"Put",
		"UK3CB_BAF_L85A2_RIS_AFG_ELCAN3D",
		"UK3CB_BAF_L131A1"
		};
		magazines[]=
		{
		"UK3CB_BAF_556_30Rnd",
		"UK3CB_BAF_556_30Rnd",
		"UK3CB_BAF_9_17Rnd",
		"UK3CB_BAF_9_17Rnd",
		"SmokeShell",
		"SmokeShell",
		"SmokeShell",
		"SmokeShell",
		"SmokeShell"
		};
		Respawnmagazines[]=
		{
		"UK3CB_BAF_556_30Rnd",
		"UK3CB_BAF_556_30Rnd",
		"UK3CB_BAF_9_17Rnd",
		"UK3CB_BAF_9_17Rnd",
		"SmokeShell",
		"SmokeShell",
		"SmokeShell",
		"SmokeShell",
		"SmokeShell"
		};
		Items[]=
		{
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_morphine",
		"ACE_morphine",
		"ACE_epinephrine",
		"ACE_tourniquet",
		"ACE_EarPlugs",	
		"UK3CB_BAF_HMNVS"
		};
		respawntems[]=
		{
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_morphine",
		"ACE_morphine",
		"ACE_epinephrine",
		"ACE_tourniquet",
		"ACE_EarPlugs",	
		"UK3CB_BAF_HMNVS"		
		};
	};
