
class ColdWar_Base: B_Soldier_base_F
	{
		scope=1;
		displayName="Base (Coldwar)";
		faction="twc_faction";
		editorSubCategory = "Men_ColdWar";
		vehicleClass="Men_ColdWar";
		icon="iconMan";
		nakedUniform="U_BasicBody";
		uniformClass="UK3CB_BAF_U_Smock_DPMW";
		backpack="UK3CB_BAF_B_Bergen_OLI_Rifleman_A";
		linkedItems[]=
		{
			"UK3CB_BAF_V_PLCE_Webbing_OLI",
			"SP_MkBushHelmet_Forrest",
			"ItemCompass",
			"itemMap",
			"ItemWatch"
		};
		respawnLinkedItems[]=
		{
			"CUP_V_RUS_Smersh_1",
			"SP_MkBushHelmet_Forrest",
			"ItemCompass",
			"itemMap",
			"ItemWatch"
		};
		Items[]=
		{
			"ACE_EarPlugs",
			"ACE_fieldDressing",
			"ACE_fieldDressing",
			"ACE_fieldDressing",
			"ACE_fieldDressing",
			"ACE_packingBandage",
			"ACE_packingBandage",
			"ACE_packingBandage",
			"ACE_packingBandage",
			"ACE_packingBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_quikclot",
			"ACE_quikclot",
			"ACE_morphine",
			"ACE_tourniquet",
			"ACE_tourniquet"
		};
		respawntems[]=
		{
			"ACE_EarPlugs",
			"ACE_fieldDressing",
			"ACE_fieldDressing",
			"ACE_fieldDressing",
			"ACE_fieldDressing",
			"ACE_packingBandage",
			"ACE_packingBandage",
			"ACE_packingBandage",
			"ACE_packingBandage",
			"ACE_packingBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_quikclot",
			"ACE_quikclot",
			"ACE_morphine",
			"ACE_tourniquet",
			"ACE_tourniquet"		
		};		
	};
	class ColdWar_Rifleman: ColdWar_Base
	{
		scope=2;
		scope=2;
		displayName="Rifleman (Coldwar)";
		weapons[]=
		{
			"Throw",
			"Put",	
			"UK3CB_BAF_L1A1_Wood",
			"HAFM_LAW"		
		};
		respawnweapons[]=
		{
			"Throw",
			"Put",	
			"UK3CB_BAF_L1A1_Wood",
			"HAFM_LAW"	
		};
		magazines[]=
		{
			"UK3CB_BAF_762_20Rnd",
			"UK3CB_BAF_762_20Rnd",
			"UK3CB_BAF_762_20Rnd",
			"UK3CB_BAF_762_20Rnd",
			"UK3CB_BAF_762_20Rnd",
			"UK3CB_BAF_762_20Rnd",
			"UK3CB_BAF_762_20Rnd",
			"UK3CB_BAF_762_20Rnd",
			"CUP_HandGrenade_L109A2_HE",
			"CUP_HandGrenade_L109A2_HE"
		};
		Respawnmagazines[]=
		{
			"UK3CB_BAF_762_20Rnd",
			"UK3CB_BAF_762_20Rnd",
			"UK3CB_BAF_762_20Rnd",
			"UK3CB_BAF_762_20Rnd",
			"UK3CB_BAF_762_20Rnd",
			"UK3CB_BAF_762_20Rnd",
			"UK3CB_BAF_762_20Rnd",
			"UK3CB_BAF_762_20Rnd",
			"CUP_HandGrenade_L109A2_HE",
			"CUP_HandGrenade_L109A2_HE"
		};
	};
	class ColdWar_Rifleman_SUIT: ColdWar_Rifleman
	{
		displayName="Rifleman SUIT(Coldwar)";
		weapons[]=
		{
			"Throw",
			"Put",	
			"twc_L1A1_SUIT",
			"HAFM_LAW"		
		};
		respawnweapons[]=
		{
			"Throw",
			"Put",	
			"twc_L1A1_SUIT",
			"HAFM_LAW"	
		};
	};
	class ColdWar_AT: ColdWar_Base
	{
		scope=2;
		displayName="AT Rifleman(Coldwar)";
		icon="iconManAT";
		backpack="TWC_Backpack_Cold_War_AT";
		linkedItems[]=
		{
			"UK3CB_BAF_V_PLCE_Webbing_OLI",
			"SP_MkBushHelmet_Forrest",
			"tf47_optic_m3maaws",
			"ItemCompass",
			"itemMap",
			"ItemWatch"
		};
		respawnLinkedItems[]=
		{
			"UK3CB_BAF_V_PLCE_Webbing_OLI",
			"SP_MkBushHelmet_Forrest",
			"ItemCompass",
			"itemMap",
			"ItemWatch"
		};
		weapons[]=
		{
			"Throw",
			"Put",
			"TWC_Sterling_Sub",
			"TWC_Carl_Gustav"
		};
		respawnweapons[]=
		{
			"Throw",
			"Put",
			"TWC_Sterling_Sub",
			"TWC_Carl_Gustav"
		};
		magazines[]=
		{
			"34_rnd_sterling_mag",
			"34_rnd_sterling_mag",
			"34_rnd_sterling_mag",
			"34_rnd_sterling_mag",
			"34_rnd_sterling_mag",
			"34_rnd_sterling_mag",
			"34_rnd_sterling_mag",
			"34_rnd_sterling_mag",
			"SmokeShell"
		};
		Respawnmagazines[]=
		{
			"34_rnd_sterling_mag",
			"34_rnd_sterling_mag",
			"34_rnd_sterling_mag",
			"34_rnd_sterling_mag",
			"34_rnd_sterling_mag",
			"34_rnd_sterling_mag",
			"34_rnd_sterling_mag",
			"34_rnd_sterling_mag",
			"SmokeShell"
		};
	};
	class ColdWar_AT_ASS: ColdWar_Rifleman
	{
		displayName="AT Assistant Rifleman (Coldwar)";
		backpack="TWC_Backpack_Cold_War_AAT";
	};
	class ColdWar_2IC: ColdWar_Rifleman
	{
		displayName="2IC (Coldwar)";
		backpack="TWC_Backpack_Cold_War_2IC";
	};
	class ColdWar_MG: ColdWar_Base
	{
		scope=2;
		displayName="Machine Gunner (Coldwar)";
		icon="iconManMG";
		backpack="TWC_Backpack_Cold_War_MG";
		weapons[]=
		{
			"Throw",
			"Put",	
			"UK3CB_BAF_L7A2",
			"rhsusf_weap_m1911a1"
		};
		respawnweapons[]=
		{
			"Throw",
			"Put",	
			"UK3CB_BAF_L7A2",
			"rhsusf_weap_m1911a1"
		};
		magazines[]=
		{
			"UK3CB_BAF_762_100Rnd",	
			"rhsusf_mag_7x45acp_MHP",
			"rhsusf_mag_7x45acp_MHP",
			"SmokeShell"
		};
		Respawnmagazines[]=
		{
			"UK3CB_BAF_762_100Rnd",	
			"rhsusf_mag_7x45acp_MHP",
			"rhsusf_mag_7x45acp_MHP",
			"SmokeShell"
		};		
	};
	class ColdWar_MG_AS: ColdWar_Rifleman
	{
		displayName="Machine Gunner (Coldwar)";
		backpack="TWC_Backpack_Cold_War_MGAS";
	};
	class ColdWar_Section_Leader: ColdWar_Rifleman
	{
		displayName="Section Leader (Coldwar)";
		icon="iconManLeader";
		backpack="TWC_Backpack_Cold_War_Section";
		linkedItems[]=
		{
		"Binocular",		
        "UK3CB_BAF_V_PLCE_Webbing_OLI",
		"SP_MkBushHelmet_Forrest",
		"ItemMap",
		"ItemCompass",
		"ItemWatch"
		};
		respawnLinkedItems[]=
		{
		"Binocular",		
        "UK3CB_BAF_V_PLCE_Webbing_OLI",
		"SP_MkBushHelmet_Forrest",
		"ItemMap",	
		"ItemCompass",
		"ItemWatch"
		};
		weapons[]=
		{
		"Throw",
		"Put",
		"Binocular",
		"UK3CB_BAF_L1A1_Wood",
		"rhsusf_weap_m1911a1"
		};
		respawnweapons[]=
		{
		"Throw",
		"Put",
		"Binocular",
		"UK3CB_BAF_L1A1_Wood",
		"rhsusf_weap_m1911a1"
		};
		magazines[]=
		{
			"UK3CB_BAF_762_20Rnd",
			"UK3CB_BAF_762_20Rnd",
			"UK3CB_BAF_762_20Rnd",
			"UK3CB_BAF_762_20Rnd",
			"UK3CB_BAF_762_20Rnd",
			"UK3CB_BAF_762_20Rnd",
			"UK3CB_BAF_762_20Rnd_T",
			"UK3CB_BAF_762_20Rnd_T",
			"rhsusf_mag_7x45acp_MHP",
			"rhsusf_mag_7x45acp_MHP",
			"CUP_HandGrenade_L109A2_HE",
			"CUP_HandGrenade_L109A2_HE"
		};
		Respawnmagazines[]=
		{
			"UK3CB_BAF_762_20Rnd",
			"UK3CB_BAF_762_20Rnd",
			"UK3CB_BAF_762_20Rnd",
			"UK3CB_BAF_762_20Rnd",
			"UK3CB_BAF_762_20Rnd",
			"UK3CB_BAF_762_20Rnd",
			"UK3CB_BAF_762_20Rnd_T",
			"UK3CB_BAF_762_20Rnd_T",
			"rhsusf_mag_7x45acp_MHP",
			"rhsusf_mag_7x45acp_MHP",
			"CUP_HandGrenade_L109A2_HE",
			"CUP_HandGrenade_L109A2_HE"

		};	
	};
	class ColdWar_Platoon_Commander: ColdWar_Section_Leader
	{
		displayName="Platoon Commander (Coldwar)";
		weapons[]=
		{
			"Throw",
			"Put",
			"Binocular",
			"TWC_Sterling_Sub",
			"rhsusf_weap_m1911a1"
		};
		respawnweapons[]=
		{
			"Throw",
			"Put",
			"Binocular",
			"TWC_Sterling_Sub",
			"rhsusf_weap_m1911a1"
		};
		magazines[]=
		{
			"34_rnd_sterling_mag",
			"34_rnd_sterling_mag",
			"34_rnd_sterling_mag",
			"34_rnd_sterling_mag",
			"34_rnd_sterling_mag",
			"34_rnd_sterling_mag",
			"34_rnd_sterling_mag",
			"34_rnd_sterling_mag",
			"rhsusf_mag_7x45acp_MHP",
			"rhsusf_mag_7x45acp_MHP",
			"CUP_HandGrenade_L109A2_HE"
		};
		Respawnmagazines[]=
		{
			"34_rnd_sterling_mag",
			"34_rnd_sterling_mag",
			"34_rnd_sterling_mag",
			"34_rnd_sterling_mag",
			"34_rnd_sterling_mag",
			"34_rnd_sterling_mag",
			"34_rnd_sterling_mag",
			"34_rnd_sterling_mag",
			"rhsusf_mag_7x45acp_MHP",
			"rhsusf_mag_7x45acp_MHP",
			"CUP_HandGrenade_L109A2_HE"
		};
	};
	class ColdWar_Sergeant: ColdWar_Platoon_Commander
	{
		displayName="Platoon Sergeant (Coldwar)";
		backpack="TWC_Backpack_Cold_War_Sergeant";
	};
	class ColdWar_Medic: ColdWar_Base
	{
		scope=2;
		displayName="Platoon Medic (Coldwar)";
		icon="iconManMedic";
		backpack="TWC_Backpack_Cold_Medic";
		weapons[]=
		{
			"Throw",
			"Put",
			"TWC_Sterling_Sub"
		};
		respawnweapons[]=
		{
			"Throw",
			"Put",	
			"TWC_Sterling_Sub"
		};
		magazines[]=
		{
			"34_rnd_sterling_mag",
			"34_rnd_sterling_mag",
			"34_rnd_sterling_mag",
			"34_rnd_sterling_mag",
			"34_rnd_sterling_mag"
		};
		Respawnmagazines[]=
		{
			"34_rnd_sterling_mag",
			"34_rnd_sterling_mag",
			"34_rnd_sterling_mag",
			"34_rnd_sterling_mag",
			"34_rnd_sterling_mag"
		};
	};
	class ColdWar_FAC: ColdWar_Section_Leader
	{
		displayName="Platoon FAC (Coldwar)";
		backpack="TWC_Backpack_Cold_War_FAC";
	};
	class ColdWar_HeliPilot: ColdWar_Base
	{
		scope=2;
		displayName="Helicopter Pilot (Coldwar)";
		uniformClass="UK3CB_BAF_U_Smock_DPMW_OLI";
		backpack="TWC_Backpack_Cold_War_Pilot";
		linkedItems[]=
		{
			"UK3CB_BAF_H_PilotHelmetHeli_A",
			"UK3CB_BAF_V_Pilot_DPMW",
			"ItemMap",
			"ItemCompass",
			"ItemWatch"
		};
		respawnLinkedItems[]=
		{
			"UK3CB_BAF_H_PilotHelmetHeli_A",
			"UK3CB_BAF_V_Pilot_DPMW",
			"ItemMap",
			"ItemCompass",
			"ItemWatch"

		};
		weapons[]=
		{
			"Throw",
			"Put",
			"TWC_Sterling_Sub"
		};
		respawnweapons[]=
		{
			"Throw",
			"Put",
			"TWC_Sterling_Sub"
		};
		magazines[]=
		{
			"34_rnd_sterling_mag",
			"34_rnd_sterling_mag",
			"34_rnd_sterling_mag",
			"SmokeShell",
			"SmokeShell"
		};
		Respawnmagazines[]=
		{
			"34_rnd_sterling_mag",
			"34_rnd_sterling_mag",
			"34_rnd_sterling_mag",
			"SmokeShell",
			"SmokeShell"

		};
	};
	class ColdWar_JetPilot: ColdWar_HeliPilot
	{
		displayName="Jet Pilot (Coldwar)";
		uniformClass="UK3CB_BAF_U_HeliPilotCoveralls_RAF";
		backpack="TWC_Backpack_Cold_War_Pilot";
		linkedItems[]=
		{
			"RHS_jetpilot_usaf",
			"CUP_V_B_PilotVest",
			"ItemMap",
			"ItemCompass",
			"ItemWatch"
		};
		respawnLinkedItems[]=
		{
			"RHS_jetpilot_usaf",
			"CUP_V_B_PilotVest",
			"ItemMap",
			"ItemCompass",
			"ItemWatch"

		};	
	};
	class ColdWar_AA_Gunner: ColdWar_AT
	{
		displayName="AA Gunner (Coldwar)";
		faction="twc_faction";
		editorSubCategory = "Men_ColdWar";
		vehicleClass="Men_ColdWar";
		icon="iconManExplosive";
		backpack="TWC_Backpack_Cold_War_AA";
		linkedItems[]=
		{
			"UK3CB_BAF_V_PLCE_Webbing_OLI",
			"SP_MkBushHelmet_Forrest",
			"ItemCompass",
			"itemMap",
			"ItemWatch"
		};
		respawnLinkedItems[]=
		{
			"UK3CB_BAF_V_PLCE_Webbing_OLI",
			"SP_MkBushHelmet_Forrest",
			"ItemCompass",
			"itemMap",
			"ItemWatch"
		};
		weapons[]=
		{
			"Throw",
			"Put",	
			"TWC_Sterling_Sub",
			"FIMStingerA"
		};
		respawnweapons[]=
		{
			"Throw",
			"Put",	
			"TWC_Sterling_Sub",
			"FIMStingerA"
		};	
	};
		class ColdWar_AA_Assistant: ColdWar_AA_Gunner
	{
		displayName="AA Assistant (Coldwar)";
		weapons[]=
		{
			"Throw",
			"Put",	
			"TWC_Sterling_Sub"
		};
		respawnweapons[]=
		{
			"Throw",
			"Put",	
			"TWC_Sterling_Sub"
		};
	};
	class ColdWar_MilanGunner: ColdWar_AT
	{
		displayName="Milan Gunner (Coldwar)";
		backpack="TWC_Backpack_Cold_War_Milan";
		weapons[]=
		{
			"Throw",
			"Put",	
			"TWC_Sterling_Sub",
			"TWC_Milan_Tripod_Disassemabled"	
		};
		respawnweapons[]=
		{
			"Throw",
			"Put",	
			"TWC_Sterling_Sub",
			"TWC_Milan_Tripod_Disassemabled"
		};
	};
	class ColdWar_MilanAssistant: ColdWar_MilanGunner
	{
		displayName="Milan Assistant (Coldwar)";
		weapons[]=
		{
			"Throw",
			"Put",	
			"TWC_Sterling_Sub",
			"TWC_Milan_Launcher_Disassemabled"	
		};
		respawnweapons[]=
		{
			"Throw",
			"Put",	
			"TWC_Sterling_Sub",
			"TWC_Milan_Launcher_Disassemabled"
		};
	};
	class ColdWar_Vehicle_Commander: ColdWar_Base
	{
		scope=2;
		displayName="Vehicle Commander (Coldwar)";
		icon="iconManLeader";
		uniformClass="UK3CB_BAF_U_CrewmanCoveralls_RTR";
		backpack="TWC_Backpack_Cold_War_Pilot";
		linkedItems[]=
		{
			"CUP_V_C_Police_Holster",
			"UK3CB_BAF_H_Beret_RTR_PRR_Over",
			"ItemCompass",
			"itemMap",
			"ItemWatch"
		};
		respawnLinkedItems[]=
		{
       		"CUP_V_C_Police_Holster",
			"UK3CB_BAF_H_Beret_RTR_PRR_Over",
			"ItemCompass",
			"itemMap",
			"ItemWatch"
		};
		weapons[]=
		{
			"Throw",
			"Put",	
			"TWC_Sterling_Sub"	
		};
		respawnweapons[]=
		{
			"Throw",
			"Put",	
			"TWC_Sterling_Sub"
		};
		magazines[]=
		{
		"34_rnd_sterling_mag",
		"34_rnd_sterling_mag",
		"34_rnd_sterling_mag",
		"34_rnd_sterling_mag",
		"SmokeShell",
		"SmokeShell"
		};
		Respawnmagazines[]=
		{
		"34_rnd_sterling_mag",
		"34_rnd_sterling_mag",
		"34_rnd_sterling_mag",
		"34_rnd_sterling_mag",
		"SmokeShell",
		"SmokeShell"
		};
	};
	
	class ColdWar_Vehicle_Crewman: ColdWar_Vehicle_Commander
	{
		displayName="Vehicle Crew (Coldwar)";
		icon="iconMan";
		backpack="";
		linkedItems[]=
		{
			"CUP_V_C_Police_Holster",
			"UK3CB_BAF_H_Beret_RTR",
			"ItemCompass",
			"itemMap",
			"ItemWatch"
		};
		respawnLinkedItems[]=
		{
			"CUP_V_RUS_Smersh_1",
			"SP_MkBushHelmet_Forrest",
			"ItemCompass",
			"itemMap",
			"ItemWatch"
		};
	};
