
	class ColdWar_Rifleman: B_Soldier_base_F
	{
		_generalMacro="Coldwar_Rifleman";
		scope=2;
		displayName="Rifleman(Coldwar)";
		faction="twc_faction";
		editorSubCategory = "Men_ColdWar";
		vehicleClass="Men_ColdWar";
		icon="iconMan";
		nakedUniform="U_BasicBody";
		uniformClass="MNP_CombatUniform_DPMR";
		backpack="TWC_Backpack_Cold_War_Rifleman";
		linkedItems[]=
		{
        "CUP_V_RUS_Smersh_1",
		"SP_MkBushHelmet_Forrest",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
		};
		respawnLinkedItems[]=
		{
        "CUP_V_RUS_Smersh_1",
		"SP_MkBushHelmet_Forrest",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
		};
		weapons[]=
		{
		"Throw",
		"Put",	
		"UK3CB_BAF_L1A1_Wood",
		"HAFM_LAW"		
		};
		respawnweapons[]=
		{
		"Throw",
		"Put",	
		"UK3CB_BAF_L1A1_Wood",
		"HAFM_LAW"	
		};
		magazines[]=
		{
		"UK3CB_BAF_762_20Rnd",
		"UK3CB_BAF_762_20Rnd",
		"UK3CB_BAF_762_20Rnd",
		"UK3CB_BAF_762_20Rnd",
		"UK3CB_BAF_762_20Rnd",
		"UK3CB_BAF_762_20Rnd",
		"UK3CB_BAF_762_20Rnd",
		"UK3CB_BAF_762_20Rnd",
		"UK3CB_BAF_762_20Rnd",
		"UK3CB_BAF_762_20Rnd",
		"CUP_HandGrenade_L109A2_HE",
		"CUP_HandGrenade_L109A2_HE"
		};
		Respawnmagazines[]=
		{
		"UK3CB_BAF_762_20Rnd",
		"UK3CB_BAF_762_20Rnd",
		"UK3CB_BAF_762_20Rnd",
		"UK3CB_BAF_762_20Rnd",
		"UK3CB_BAF_762_20Rnd",
		"UK3CB_BAF_762_20Rnd",
		"UK3CB_BAF_762_20Rnd",
		"UK3CB_BAF_762_20Rnd",
		"UK3CB_BAF_762_20Rnd",
		"UK3CB_BAF_762_20Rnd",
		"CUP_HandGrenade_L109A2_HE",
		"CUP_HandGrenade_L109A2_HE"
		};
		Items[]=
		{
		"ACE_EarPlugs",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_morphine",
		"ACE_morphine",
		"ACE_epinephrine",
		"ACE_tourniquet"
		};
		respawntems[]=
		{
		"ACE_EarPlugs",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_morphine",
		"ACE_morphine",
		"ACE_epinephrine",
		"ACE_tourniquet"			
		};		
	};
	class ColdWar_Rifleman_SUIT: B_Soldier_base_F
	{
		_generalMacro="Coldwar_Rifleman_SUIT";
		scope=2;
		displayName="Rifleman SUIT(Coldwar)";
		faction="twc_faction";
		editorSubCategory = "Men_ColdWar";
		vehicleClass="Men_ColdWar";
		icon="iconMan";
		nakedUniform="U_BasicBody";
		uniformClass="MNP_CombatUniform_DPMR";
		backpack="TWC_Backpack_Cold_War_Rifleman";
		linkedItems[]=
		{
        "CUP_V_RUS_Smersh_1",
		"SP_MkBushHelmet_Forrest",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
		};
		respawnLinkedItems[]=
		{
        "CUP_V_RUS_Smersh_1",
		"SP_MkBushHelmet_Forrest",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
		};
		weapons[]=
		{
		"Throw",
		"Put",	
		"twc_L1A1_SUIT",
		"HAFM_LAW"		
		};
		respawnweapons[]=
		{
		"Throw",
		"Put",	
		"twc_L1A1_SUIT",
		"HAFM_LAW"	
		};
		magazines[]=
		{
		"UK3CB_BAF_762_20Rnd",
		"UK3CB_BAF_762_20Rnd",
		"UK3CB_BAF_762_20Rnd",
		"UK3CB_BAF_762_20Rnd",
		"UK3CB_BAF_762_20Rnd",
		"UK3CB_BAF_762_20Rnd",
		"UK3CB_BAF_762_20Rnd",
		"UK3CB_BAF_762_20Rnd",
		"UK3CB_BAF_762_20Rnd_T",
		"UK3CB_BAF_762_20Rnd_T",
		"CUP_HandGrenade_L109A2_HE",
		"CUP_HandGrenade_L109A2_HE"
		};
		Respawnmagazines[]=
		{
		"UK3CB_BAF_762_20Rnd",
		"UK3CB_BAF_762_20Rnd",
		"UK3CB_BAF_762_20Rnd",
		"UK3CB_BAF_762_20Rnd",
		"UK3CB_BAF_762_20Rnd",
		"UK3CB_BAF_762_20Rnd",
		"UK3CB_BAF_762_20Rnd",
		"UK3CB_BAF_762_20Rnd",
		"UK3CB_BAF_762_20Rnd_T",
		"UK3CB_BAF_762_20Rnd_T",
		"CUP_HandGrenade_L109A2_HE",
		"CUP_HandGrenade_L109A2_HE"
		};
		Items[]=
		{
		"ACE_EarPlugs",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_morphine",
		"ACE_morphine",
		"ACE_epinephrine",
		"ACE_tourniquet"
		};
		respawntems[]=
		{
		"ACE_EarPlugs",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_morphine",
		"ACE_morphine",
		"ACE_epinephrine",
		"ACE_tourniquet"			
		};		
	};
	class ColdWar_AT: B_Soldier_base_F
	{
		_generalMacro="Coldwar_At";
		scope=2;
		displayName="AT Rifleman(Coldwar)";
		faction="twc_faction";
		editorSubCategory = "Men_ColdWar";
		vehicleClass="Men_ColdWar";
		icon="iconMan";
		nakedUniform="U_BasicBody";
		uniformClass="MNP_CombatUniform_DPMR";
		backpack="TWC_Backpack_Cold_War_AT";
		linkedItems[]=
		{
        "CUP_V_RUS_Smersh_1",
		"SP_MkBushHelmet_Forrest",
		"tf47_optic_m3maaws",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
		};
		respawnLinkedItems[]=
		{
        "CUP_V_RUS_Smersh_1",
		"SP_MkBushHelmet_Forrest",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
		};
		weapons[]=
		{
		"Throw",
		"Put",
		"TWC_Sterling_Sub",
		"TWC_Carl_Gustav"
		};
		respawnweapons[]=
		{
		"Throw",
		"Put",
		"TWC_Sterling_Sub",
		"TWC_Carl_Gustav"
		};
		magazines[]=
		{
		"34_rnd_sterling_mag",
		"34_rnd_sterling_mag",
		"34_rnd_sterling_mag",
		"34_rnd_sterling_mag",
		"34_rnd_sterling_mag",
		"34_rnd_sterling_mag",
		"34_rnd_sterling_mag",
		"34_rnd_sterling_mag",
		"34_rnd_sterling_mag",
		"34_rnd_sterling_mag",
		"tf47_m3maaws_HEAT",
		"CUP_HandGrenade_L109A2_HE",
		"CUP_HandGrenade_L109A2_HE"
		};
		Respawnmagazines[]=
		{
		"34_rnd_sterling_mag",
		"34_rnd_sterling_mag",
		"34_rnd_sterling_mag",
		"34_rnd_sterling_mag",
		"34_rnd_sterling_mag",
		"34_rnd_sterling_mag",
		"34_rnd_sterling_mag",
		"34_rnd_sterling_mag",
		"34_rnd_sterling_mag",
		"34_rnd_sterling_mag",
		"tf47_m3maaws_HEAT",
		"CUP_HandGrenade_L109A2_HE",
		"CUP_HandGrenade_L109A2_HE"
		};
		Items[]=
		{
		"ACE_EarPlugs",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_morphine",
		"ACE_morphine",
		"ACE_epinephrine",
		"ACE_tourniquet",
		"tf47_optic_m3maaws"
		};
		respawntems[]=
		{
		"ACE_EarPlugs",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_morphine",
		"ACE_morphine",
		"ACE_epinephrine",
		"ACE_tourniquet",
		"tf47_optic_m3maaws"		
		};		
	};
	class ColdWar_AT_ASS: B_Soldier_base_F
	{
		_generalMacro="Coldwar_AT_ASS";
		scope=2;
		displayName="AT Assistant Rifleman(Coldwar)";
		faction="twc_faction";
		editorSubCategory = "Men_ColdWar";
		vehicleClass="Men_ColdWar";
		icon="iconMan";
		nakedUniform="U_BasicBody";
		uniformClass="MNP_CombatUniform_DPMR";
		backpack="TWC_Backpack_Cold_War_AT";
		linkedItems[]=
		{
        "CUP_V_RUS_Smersh_1",
		"SP_MkBushHelmet_Forrest",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
		};
		respawnLinkedItems[]=
		{
        "CUP_V_RUS_Smersh_1",
		"SP_MkBushHelmet_Forrest",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
		};
		weapons[]=
		{
	    "Throw",
		"Put",
		"UK3CB_BAF_L1A1_Wood"
		};
		respawnweapons[]=
		{
		"Throw",
		"Put",	
		"UK3CB_BAF_L1A1_Wood"
		};
		magazines[]=
		{
		"UK3CB_BAF_762_20Rnd",
		"UK3CB_BAF_762_20Rnd",
		"UK3CB_BAF_762_20Rnd",
		"UK3CB_BAF_762_20Rnd",
		"UK3CB_BAF_762_20Rnd",
		"UK3CB_BAF_762_20Rnd",
		"UK3CB_BAF_762_20Rnd",	
		"UK3CB_BAF_762_20Rnd",	
		"UK3CB_BAF_762_20Rnd",	
		"UK3CB_BAF_762_20Rnd",		
		"CUP_HandGrenade_L109A2_HE",
		"CUP_HandGrenade_L109A2_HE"
		};
		Respawnmagazines[]=
		{
		"UK3CB_BAF_762_20Rnd",
		"UK3CB_BAF_762_20Rnd",
		"UK3CB_BAF_762_20Rnd",
		"UK3CB_BAF_762_20Rnd",
		"UK3CB_BAF_762_20Rnd",
		"UK3CB_BAF_762_20Rnd",
		"UK3CB_BAF_762_20Rnd",	
		"UK3CB_BAF_762_20Rnd",	
		"UK3CB_BAF_762_20Rnd",	
		"UK3CB_BAF_762_20Rnd",		
		"CUP_HandGrenade_L109A2_HE",
		"CUP_HandGrenade_L109A2_HE"
		};
		Items[]=
		{
		"ACE_EarPlugs",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_morphine",
		"ACE_morphine",
		"ACE_epinephrine",
		"ACE_tourniquet"
		};
		respawntems[]=
		{
		"ACE_EarPlugs",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_morphine",
		"ACE_morphine",
		"ACE_epinephrine",
		"ACE_tourniquet"		
		};		
	};
	class ColdWar_2IC: B_Soldier_base_F
	{
		_generalMacro="Coldwar_2IC";
		scope=2;
		displayName="2IC(Coldwar)";
		faction="twc_faction";
		editorSubCategory = "Men_ColdWar";
		vehicleClass="Men_ColdWar";
		icon="iconMan";
		nakedUniform="U_BasicBody";
		uniformClass="MNP_CombatUniform_DPMR";
		backpack="TWC_Backpack_Cold_War_2IC";
		linkedItems[]=
		{
		"Binocular",	
        "CUP_V_RUS_Smersh_1",
		"SP_MkBushHelmet_Forrest",
		"ItemMap",
		"itemMap",
		"ItemCompass",
		"ItemWatch"
		};
		respawnLinkedItems[]=
		{
		"Binocular",		
        "CUP_V_RUS_Smersh_1",
		"SP_MkBushHelmet_Forrest",
		"ItemMap",
		"itemMap",
		"ItemCompass",
		"ItemWatch"
		};
		weapons[]=
		{
		"Throw",
		"Put",
		"Binocular",
		"UK3CB_BAF_L1A1_Wood"
		};
		respawnweapons[]=
		{
		"Throw",
		"Put",
		"Binocular",
		"UK3CB_BAF_L1A1_Wood"
		};
		magazines[]=
		{
		"UK3CB_BAF_762_20Rnd",
		"UK3CB_BAF_762_20Rnd",
		"UK3CB_BAF_762_20Rnd",
		"UK3CB_BAF_762_20Rnd",
		"UK3CB_BAF_762_20Rnd",
		"UK3CB_BAF_762_20Rnd",
		"UK3CB_BAF_762_20Rnd",
		"UK3CB_BAF_762_20Rnd",
		"UK3CB_BAF_762_20Rnd",
		"UK3CB_BAF_762_20Rnd",		
		"CUP_HandGrenade_L109A2_HE",
		"CUP_HandGrenade_L109A2_HE"
		};
		Respawnmagazines[]=
		{
		"UK3CB_BAF_762_20Rnd",
		"UK3CB_BAF_762_20Rnd",
		"UK3CB_BAF_762_20Rnd",
		"UK3CB_BAF_762_20Rnd",
		"UK3CB_BAF_762_20Rnd",
		"UK3CB_BAF_762_20Rnd",
		"UK3CB_BAF_762_20Rnd",
		"UK3CB_BAF_762_20Rnd",
		"UK3CB_BAF_762_20Rnd",
		"UK3CB_BAF_762_20Rnd",		
		"CUP_HandGrenade_L109A2_HE",
		"CUP_HandGrenade_L109A2_HE"
		};
		Items[]=
		{
		"ACE_EarPlugs",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_morphine",
		"ACE_morphine",
		"ACE_epinephrine",
		"ACE_tourniquet"
		};
		respawntems[]=
		{
		"ACE_EarPlugs",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_morphine",
		"ACE_morphine",
		"ACE_epinephrine",
		"ACE_tourniquet"			
		};		
	};
	class ColdWar_MG: B_Soldier_base_F
	{
		_generalMacro="Coldwar_MG";
		scope=2;
		displayName="Machine Gunner(Coldwar)";
		faction="twc_faction";
		editorSubCategory = "Men_ColdWar";
		vehicleClass="Men_ColdWar";
		icon="iconMan";
		nakedUniform="U_BasicBody";
		uniformClass="MNP_CombatUniform_DPMR";
		backpack="TWC_Backpack_Cold_War_MG";
		linkedItems[]=
		{
        "CUP_V_RUS_Smersh_1",
		"SP_MkBushHelmet_Forrest",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
		};
		respawnLinkedItems[]=
		{
        "CUP_V_RUS_Smersh_1",
		"SP_MkBushHelmet_Forrest",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
		};
		weapons[]=
		{
		"Throw",
		"Put",	
		"UK3CB_BAF_L7A2",
		"rhsusf_weap_m1911a1"
		};
		respawnweapons[]=
		{
		"Throw",
		"Put",	
		"UK3CB_BAF_L7A2",
		"rhsusf_weap_m1911a1"
		};
		magazines[]=
		{
		"UK3CB_BAF_762_100Rnd_T",
		"UK3CB_BAF_762_100Rnd",
		"UK3CB_BAF_762_100Rnd",	
		"rhsusf_mag_7x45acp_MHP",
		"rhsusf_mag_7x45acp_MHP",
		"CUP_HandGrenade_L109A2_HE",
		"CUP_HandGrenade_L109A2_HE"
		};
		Respawnmagazines[]=
		{
		"UK3CB_BAF_762_100Rnd_T",
		"UK3CB_BAF_762_100Rnd",
		"UK3CB_BAF_762_100Rnd",	
		"rhsusf_mag_7x45acp_MHP",
		"rhsusf_mag_7x45acp_MHP",
		"CUP_HandGrenade_L109A2_HE",
		"CUP_HandGrenade_L109A2_HE"
		};
		Items[]=
		{
		"ACE_EarPlugs",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_morphine",
		"ACE_morphine",
		"ACE_epinephrine",
		"ACE_tourniquet"
		};
		respawntems[]=
		{
		"ACE_EarPlugs",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_morphine",
		"ACE_morphine",
		"ACE_epinephrine",
		"ACE_tourniquet"		
		};		
	};
	class ColdWar_MG_AS: B_Soldier_base_F
	{
		_generalMacro="Coldwar_MG";
		scope=2;
		displayName="Machine Gunner Assistant(Coldwar)";
		faction="twc_faction";
		editorSubCategory = "Men_ColdWar";
		vehicleClass="Men_ColdWar";
		icon="iconMan";
		nakedUniform="U_BasicBody";
		uniformClass="MNP_CombatUniform_DPMR";
		backpack="TWC_Backpack_Cold_War_MGAS";
		linkedItems[]=
		{
        "CUP_V_RUS_Smersh_1",
		"SP_MkBushHelmet_Forrest",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
		};
		respawnLinkedItems[]=
		{
        "CUP_V_RUS_Smersh_1",
		"SP_MkBushHelmet_Forrest",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
		};
		weapons[]=
		{
		"Throw",
		"Put",	
		"UK3CB_BAF_L1A1_Wood"
		};
		respawnweapons[]=
		{
		"Throw",
		"Put",	
		"UK3CB_BAF_L1A1_Wood"
		};
		magazines[]=
		{
		"UK3CB_BAF_762_20Rnd",
		"UK3CB_BAF_762_20Rnd",
		"UK3CB_BAF_762_20Rnd",
		"UK3CB_BAF_762_20Rnd",
		"UK3CB_BAF_762_20Rnd",
		"UK3CB_BAF_762_20Rnd",
		"UK3CB_BAF_762_20Rnd",
		"UK3CB_BAF_762_20Rnd",
		"UK3CB_BAF_762_20Rnd",
		"UK3CB_BAF_762_20Rnd",
		"CUP_HandGrenade_L109A2_HE",
		"CUP_HandGrenade_L109A2_HE"
		};
		Respawnmagazines[]=
		{
		"UK3CB_BAF_762_20Rnd",
		"UK3CB_BAF_762_20Rnd",
		"UK3CB_BAF_762_20Rnd",
		"UK3CB_BAF_762_20Rnd",
		"UK3CB_BAF_762_20Rnd",
		"UK3CB_BAF_762_20Rnd",
		"UK3CB_BAF_762_20Rnd",
		"UK3CB_BAF_762_20Rnd",
		"UK3CB_BAF_762_20Rnd",
		"UK3CB_BAF_762_20Rnd",
		"CUP_HandGrenade_L109A2_HE",
		"CUP_HandGrenade_L109A2_HE"
		};
		Items[]=
		{
		"ACE_EarPlugs",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_morphine",
		"ACE_morphine",
		"ACE_epinephrine",
		"ACE_tourniquet"
		};
		respawntems[]=
		{
		"ACE_EarPlugs",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_morphine",
		"ACE_morphine",
		"ACE_epinephrine",
		"ACE_tourniquet"
		};		
	};
	class ColdWar_Section_Leader: B_Soldier_base_F
	{
		_generalMacro="Coldwar_Section_Leader";
		scope=2;
		displayName="Section Leader(Coldwar)";
		faction="twc_faction";
		editorSubCategory = "Men_ColdWar";
		vehicleClass="Men_ColdWar";
		icon="iconMan";
		nakedUniform="U_BasicBody";
		uniformClass="MNP_CombatUniform_DPMR";
		backpack="TWC_Backpack_Cold_War_Section";
		linkedItems[]=
		{
		"Binocular",		
        "CUP_V_RUS_Smersh_1",
		"SP_MkBushHelmet_Forrest",
		"ItemMap",
		"ItemCompass",
		"ItemWatch"
		};
		respawnLinkedItems[]=
		{
		"Binocular",		
        "CUP_V_RUS_Smersh_1",
		"SP_MkBushHelmet_Forrest",
		"ItemMap",	
		"ItemCompass",
		"ItemWatch"
		};
		weapons[]=
		{
		"Throw",
		"Put",
		"Binocular",
		"UK3CB_BAF_L1A1_Wood",
		"rhsusf_weap_m1911a1"
		};
		respawnweapons[]=
		{
		"Throw",
		"Put",
		"Binocular",
		"UK3CB_BAF_L1A1_Wood",
		"rhsusf_weap_m1911a1"
		};
		magazines[]=
		{
		"UK3CB_BAF_762_20Rnd",
		"UK3CB_BAF_762_20Rnd",
		"UK3CB_BAF_762_20Rnd",
		"UK3CB_BAF_762_20Rnd",
		"UK3CB_BAF_762_20Rnd",
		"UK3CB_BAF_762_20Rnd",
		"UK3CB_BAF_762_20Rnd",
		"UK3CB_BAF_762_20Rnd",
		"UK3CB_BAF_762_20Rnd_T",
		"UK3CB_BAF_762_20Rnd_T",
		"rhsusf_mag_7x45acp_MHP",
		"rhsusf_mag_7x45acp_MHP",
		"CUP_HandGrenade_L109A2_HE",
		"CUP_HandGrenade_L109A2_HE"
		};
		Respawnmagazines[]=
		{
		"UK3CB_BAF_762_20Rnd",
		"UK3CB_BAF_762_20Rnd",
		"UK3CB_BAF_762_20Rnd",
		"UK3CB_BAF_762_20Rnd",
		"UK3CB_BAF_762_20Rnd",
		"UK3CB_BAF_762_20Rnd",
		"UK3CB_BAF_762_20Rnd",
		"UK3CB_BAF_762_20Rnd",
		"UK3CB_BAF_762_20Rnd_T",
		"UK3CB_BAF_762_20Rnd_T",
		"rhsusf_mag_7x45acp_MHP",
		"rhsusf_mag_7x45acp_MHP",
		"CUP_HandGrenade_L109A2_HE",
		"CUP_HandGrenade_L109A2_HE"
		};
		Items[]=
		{
		"ACE_EarPlugs",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_morphine",
		"ACE_morphine",
		"ACE_epinephrine",
		"ACE_tourniquet"
		};
		respawntems[]=
		{
		"ACE_EarPlugs",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_morphine",
		"ACE_morphine",
		"ACE_epinephrine",
		"ACE_tourniquet"		
		};		
	};
	class ColdWar_Platoon_Commander: B_Soldier_base_F
	{
		_generalMacro="Coldwar_Platoon_Commander";
		scope=2;
		displayName="Platoon Commander(Coldwar)";
		faction="twc_faction";
		editorSubCategory = "Men_ColdWar";
		vehicleClass="Men_ColdWar";
		icon="iconMan";
		nakedUniform="U_BasicBody";
		uniformClass="MNP_CombatUniform_DPMR";
		backpack="TWC_Backpack_Cold_War_Section";
		linkedItems[]=
		{		
        "CUP_V_RUS_Smersh_1",
		"SP_MkBushHelmet_Forrest",
		"ItemMap",
		"ItemCompass",
		"ItemWatch"
		};
		respawnLinkedItems[]=
		{	
        "CUP_V_RUS_Smersh_1",
		"SP_MkBushHelmet_Forrest",
		"ItemMap",	
		"ItemCompass",
		"ItemWatch"
		};
		weapons[]=
		{
		"Throw",
		"Put",
		"Binocular",
		"TWC_Sterling_Sub",
		"rhsusf_weap_m1911a1"
		};
		respawnweapons[]=
		{
		"Throw",
		"Put",
		"Binocular",
		"TWC_Sterling_Sub",
		"rhsusf_weap_m1911a1"
		};
		magazines[]=
		{
		"34_rnd_sterling_mag",
		"34_rnd_sterling_mag",
		"34_rnd_sterling_mag",
		"34_rnd_sterling_mag",
		"34_rnd_sterling_mag",
		"rhsusf_mag_7x45acp_MHP",
		"rhsusf_mag_7x45acp_MHP",		
		"CUP_HandGrenade_L109A2_HE",
		"CUP_HandGrenade_L109A2_HE"
		};
		Respawnmagazines[]=
		{
		"34_rnd_sterling_mag",
		"34_rnd_sterling_mag",
		"34_rnd_sterling_mag",
		"34_rnd_sterling_mag",
		"34_rnd_sterling_mag",
		"rhsusf_mag_7x45acp_MHP",
		"rhsusf_mag_7x45acp_MHP",		
		"CUP_HandGrenade_L109A2_HE",
		"CUP_HandGrenade_L109A2_HE"
		};
		Items[]=
		{
		"ACE_EarPlugs",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_morphine",
		"ACE_morphine",
		"ACE_epinephrine",
		"ACE_tourniquet"
		};
		respawntems[]=
		{
		"ACE_EarPlugs",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_morphine",
		"ACE_morphine",
		"ACE_epinephrine",
		"ACE_tourniquet"		
		};		
	};
	class ColdWar_sergeant: B_Soldier_base_F
	{
		_generalMacro="Coldwar_Platoon_sergeant";
		scope=2;
		displayName="Platoon Sergeant(Coldwar)";
		faction="twc_faction";
		editorSubCategory = "Men_ColdWar";
		vehicleClass="Men_ColdWar";
		icon="iconMan";
		nakedUniform="U_BasicBody";
		uniformClass="MNP_CombatUniform_DPMR";
		backpack="TWC_Backpack_Cold_War_Section";
		linkedItems[]=
		{		
        "CUP_V_RUS_Smersh_1",
		"SP_MkBushHelmet_Forrest",
		"ItemMap",
		"ItemCompass",
		"ItemWatch"
		};
		respawnLinkedItems[]=
		{		
        "CUP_V_RUS_Smersh_1",
		"SP_MkBushHelmet_Forrest",
		"ItemMap",		
		"ItemCompass",
		"ItemWatch"
		};
		weapons[]=
		{
		"Throw",
		"Put",
		"Binocular",
		"TWC_Sterling_Sub",
		"rhsusf_weap_m1911a1"
		};
		respawnweapons[]=
		{
		"Throw",
		"Put",
		"Binocular",
		"TWC_Sterling_Sub",
		"rhsusf_weap_m1911a1"
		};
		magazines[]=
		{
		"34_rnd_sterling_mag",
		"34_rnd_sterling_mag",
		"34_rnd_sterling_mag",
		"34_rnd_sterling_mag",
		"34_rnd_sterling_mag",
		"rhsusf_mag_7x45acp_MHP",
		"rhsusf_mag_7x45acp_MHP",		
		"CUP_HandGrenade_L109A2_HE",
		"CUP_HandGrenade_L109A2_HE"
		};
		Respawnmagazines[]=
		{
		"34_rnd_sterling_mag",
		"34_rnd_sterling_mag",
		"34_rnd_sterling_mag",
		"34_rnd_sterling_mag",
		"34_rnd_sterling_mag",
		"rhsusf_mag_7x45acp_MHP",
		"rhsusf_mag_7x45acp_MHP",		
		"CUP_HandGrenade_L109A2_HE",
		"CUP_HandGrenade_L109A2_HE"
		};
		Items[]=
		{
		"ACE_EarPlugs",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_morphine",
		"ACE_morphine",
		"ACE_epinephrine",
		"ACE_tourniquet"
		};
		respawntems[]=
		{
		"ACE_EarPlugs",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_morphine",
		"ACE_morphine",
		"ACE_epinephrine",
		"ACE_tourniquet"
		};		
	};
	class ColdWar_Medic: B_Soldier_base_F
	{
		_generalMacro="Coldwar_Medic";
		scope=2;
		displayName="Platoon Medic(Coldwar)";
		faction="twc_faction";
		editorSubCategory = "Men_ColdWar";
		vehicleClass="Men_ColdWar";
		icon="iconMan";
		nakedUniform="U_BasicBody";
		uniformClass="MNP_CombatUniform_DPMR";
		backpack="TWC_Backpack_Cold_Medic";
		linkedItems[]=
		{
        "CUP_V_RUS_Smersh_1",
		"SP_MkBushHelmet_Forrest",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
		};
		respawnLinkedItems[]=
		{
        "CUP_V_RUS_Smersh_1",
		"SP_MkBushHelmet_Forrest",	
		"ItemCompass",
		"itemMap",
		"ItemWatch"
		};
		weapons[]=
		{
		"Throw",
		"Put",
		"TWC_Sterling_Sub"
		};
		respawnweapons[]=
		{
		"Throw",
		"Put",	
		"TWC_Sterling_Sub"
		};
		magazines[]=
		{
		"34_rnd_sterling_mag",
		"34_rnd_sterling_mag",
		"34_rnd_sterling_mag",
		"34_rnd_sterling_mag",
		"34_rnd_sterling_mag"
		};
		Respawnmagazines[]=
		{
		"34_rnd_sterling_mag",
		"34_rnd_sterling_mag",
		"34_rnd_sterling_mag",
		"34_rnd_sterling_mag",
		"34_rnd_sterling_mag"
		};
		Items[]=
		{
		"ACE_EarPlugs",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_morphine",
		"ACE_morphine",
		"ACE_epinephrine",
		"ACE_tourniquet"

		};
		respawntems[]=
		{
		"ACE_EarPlugs",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_morphine",
		"ACE_morphine",
		"ACE_epinephrine",
		"ACE_tourniquet"
		};		
	};
	class ColdWar_FAC: B_Soldier_base_F
	{
		_generalMacro="Coldwar_Platoon_FAC";
		scope=2;
		displayName="Platoon FAC(Coldwar)";
		faction="twc_faction";
		editorSubCategory = "Men_ColdWar";
		vehicleClass="Men_ColdWar";
		icon="iconMan";
		nakedUniform="U_BasicBody";
		uniformClass="MNP_CombatUniform_DPMR";
		backpack="TWC_Backpack_Cold_War_FAC";
		linkedItems[]=
		{		
        "CUP_V_RUS_Smersh_1",
		"SP_MkBushHelmet_Forrest",
		"ItemMap",
		"ItemCompass",
		"ItemWatch"
		};
		respawnLinkedItems[]=
		{		
        "CUP_V_RUS_Smersh_1",
		"SP_MkBushHelmet_Forrest",
		"ItemMap",		
		"ItemCompass",
		"ItemWatch"
		};
		weapons[]=
		{
		"Throw",
		"Put",
		"Binocular",
		"UK3CB_BAF_L1A1_Wood",
		"rhsusf_weap_m1911a1"
		};
		respawnweapons[]=
		{
		"Throw",
		"Put",
		"Binocular",
		"UK3CB_BAF_L1A1_Wood",
		"rhsusf_weap_m1911a1"
		};
		magazines[]=
		{
		"rhsusf_mag_7x45acp_MHP",
		"rhsusf_mag_7x45acp_MHP",
		"UK3CB_BAF_762_20Rnd",
		"UK3CB_BAF_762_20Rnd",
		"UK3CB_BAF_762_20Rnd",
		"UK3CB_BAF_762_20Rnd",
		"UK3CB_BAF_762_20Rnd",
		"UK3CB_BAF_762_20Rnd",
		"UK3CB_BAF_762_20Rnd",
		"UK3CB_BAF_762_20Rnd",
		"UK3CB_BAF_762_20Rnd",
		"UK3CB_BAF_762_20Rnd",
		"CUP_HandGrenade_L109A2_HE",
		"CUP_HandGrenade_L109A2_HE"
		};
		Respawnmagazines[]=
		{
		"rhsusf_mag_7x45acp_MHP",
		"rhsusf_mag_7x45acp_MHP",
		"UK3CB_BAF_762_20Rnd",
		"UK3CB_BAF_762_20Rnd",
		"UK3CB_BAF_762_20Rnd",
		"UK3CB_BAF_762_20Rnd",
		"UK3CB_BAF_762_20Rnd",
		"UK3CB_BAF_762_20Rnd",
		"UK3CB_BAF_762_20Rnd",
		"UK3CB_BAF_762_20Rnd",
		"UK3CB_BAF_762_20Rnd",
		"UK3CB_BAF_762_20Rnd",
		"CUP_HandGrenade_L109A2_HE",
		"CUP_HandGrenade_L109A2_HE"
		};
		Items[]=
		{
		"ACE_EarPlugs",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_morphine",
		"ACE_morphine",
		"ACE_epinephrine",
		"ACE_tourniquet"
		};
		respawntems[]=
		{
		"ACE_EarPlugs",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_morphine",
		"ACE_morphine",
		"ACE_epinephrine",
		"ACE_tourniquet"
		};		
	};
	class ColdWar_HeloPilot: B_Soldier_base_F
	{
		_generalMacro="Coldwar_HelicopterPilot";
		scope=2;
		displayName="Helicopter Pilot(Coldwar)";
		faction="twc_faction";
		editorSubCategory = "Men_ColdWar";
		vehicleClass="Men_ColdWar";
		icon="iconMan";
		nakedUniform="U_BasicBody";
		uniformClass="MNP_CombatUniform_DPMR";
		backpack="TWC_Backpack_Cold_War_Pilot";
		linkedItems[]=
		{
		"UK3CB_BAF_H_PilotHelmetHeli_A",
		"ItemMap",
		"ItemCompass",
		"ItemWatch"
		};
		respawnLinkedItems[]=
		{
		"UK3CB_BAF_H_PilotHelmetHeli_A",
		"ItemMap",		
		"ItemCompass",
		"ItemWatch"
		};
		weapons[]=
		{
		"Throw",
		"Put",
		"rhsusf_weap_m1911a1"
		};
		respawnweapons[]=
		{
		"Throw",
		"Put",
		"rhsusf_weap_m1911a1"
		};
		magazines[]=
		{
		"rhsusf_mag_7x45acp_MHP",
		"rhsusf_mag_7x45acp_MHP",	
		"SmokeShell",
		"SmokeShell"
		};
		Respawnmagazines[]=
		{
		"rhsusf_mag_7x45acp_MHP",
		"rhsusf_mag_7x45acp_MHP",	
		"SmokeShell",
		"SmokeShell"
		};
		Items[]=
		{
		"ACE_EarPlugs",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_morphine",
		"ACE_morphine",
		"ACE_epinephrine",
		"ACE_tourniquet",
		"ACE_microDAGR_Item"
		};
		respawntems[]=
		{
		"ACE_EarPlugs",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_morphine",
		"ACE_morphine",
		"ACE_epinephrine",
		"ACE_tourniquet",
		"ACE_microDAGR_Item"
		};		
	};
	class ColdWar_JetPilot: B_Soldier_base_F
	{
		_generalMacro="Coldwar_JetPilot";
		scope=2;
		displayName="Jet Pilot(Coldwar)";
		faction="twc_faction";
		editorSubCategory = "Men_ColdWar";
		vehicleClass="Men_ColdWar";
		icon="iconMan";
		nakedUniform="U_BasicBody";
		uniformClass="UK3CB_BAF_U_HeliPilotCoveralls_RAF";
		backpack="TWC_Backpack_Cold_War_Pilot";
		linkedItems[]=
		{
		"RHS_jetpilot_usaf",
		"ItemMap",
		"ItemCompass",
		"ItemWatch"
		};
		respawnLinkedItems[]=
		{
		"RHS_jetpilot_usaf",
		"ItemMap",		
		"ItemCompass",
		"ItemWatch"
		};
		weapons[]=
		{
		"Throw",
		"Put",
		"rhsusf_weap_m1911a1"
		};
		respawnweapons[]=
		{
		"Throw",
		"Put",
		"rhsusf_weap_m1911a1"
		};
		magazines[]=
		{
		"rhsusf_mag_7x45acp_MHP",
		"rhsusf_mag_7x45acp_MHP",	
		"SmokeShell",
		"SmokeShell"
		};
		Respawnmagazines[]=
		{
		"rhsusf_mag_7x45acp_MHP",
		"rhsusf_mag_7x45acp_MHP",	
		"SmokeShell",
		"SmokeShell"
		};
		Items[]=
		{
		"ACE_EarPlugs",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_morphine",
		"ACE_morphine",
		"ACE_epinephrine",
		"ACE_tourniquet",
		"ACE_microDAGR_Item"
		};
		respawntems[]=
		{
		"ACE_EarPlugs",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_morphine",
		"ACE_morphine",
		"ACE_epinephrine",
		"ACE_tourniquet",
		"ACE_microDAGR_Item"
		};		
	};
	class ColdWar_AA_Gunner: B_Soldier_base_F
	{
		_generalMacro="Coldwar_AA_Gunner";
		scope=2;
		displayName="AA Gunner(Coldwar)";
		faction="twc_faction";
		editorSubCategory = "Men_ColdWar";
		vehicleClass="Men_ColdWar";
		icon="iconMan";
		nakedUniform="U_BasicBody";
		uniformClass="MNP_CombatUniform_DPMR";
		backpack="TWC_Backpack_Cold_War_AA";
		linkedItems[]=
		{
        "CUP_V_RUS_Smersh_1",
		"SP_MkBushHelmet_Forrest",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
		};
		respawnLinkedItems[]=
		{
        "CUP_V_RUS_Smersh_1",
		"SP_MkBushHelmet_Forrest",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
		};
		weapons[]=
		{
		"Throw",
		"Put",	
		"TWC_Sterling_Sub",
		"FIMStingerA"
		};
		respawnweapons[]=
		{
		"Throw",
		"Put",	
		"TWC_Sterling_Sub",
		"FIMStingerA"
		};
		magazines[]=
		{
		"34_rnd_sterling_mag",
		"34_rnd_sterling_mag",
		"34_rnd_sterling_mag",
		"34_rnd_sterling_mag",
		"34_rnd_sterling_mag",
		"CUP_Stinger_M"
		};
		Respawnmagazines[]=
		{
		"34_rnd_sterling_mag",
		"34_rnd_sterling_mag",
		"34_rnd_sterling_mag",
		"34_rnd_sterling_mag",
		"34_rnd_sterling_mag",
		"CUP_Stinger_M"
		};
		Items[]=
		{
		"ACE_EarPlugs",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_morphine",
		"ACE_morphine",
		"ACE_epinephrine",
		"ACE_tourniquet"
		};
		respawntems[]=
		{
		"ACE_EarPlugs",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_morphine",
		"ACE_morphine",
		"ACE_epinephrine",
		"ACE_tourniquet"		
		};		
	};
		class ColdWar_AA_Assistant: B_Soldier_base_F
	{
		_generalMacro="Coldwar_AA_Assistant";
		scope=2;
		displayName="AA Assistant(Coldwar)";
		faction="twc_faction";
		editorSubCategory = "Men_ColdWar";
		vehicleClass="Men_ColdWar";
		icon="iconMan";
		nakedUniform="U_BasicBody";
		uniformClass="MNP_CombatUniform_DPMR";
		backpack="TWC_Backpack_Cold_War_AA";
		linkedItems[]=
		{
        "CUP_V_RUS_Smersh_1",
		"SP_MkBushHelmet_Forrest",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
		};
		respawnLinkedItems[]=
		{
        "CUP_V_RUS_Smersh_1",
		"SP_MkBushHelmet_Forrest",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
		};
		weapons[]=
		{
		"Throw",
		"Put",	
		"TWC_Sterling_Sub"
		};
		respawnweapons[]=
		{
		"Throw",
		"Put",	
		"TWC_Sterling_Sub"
		};
		magazines[]=
		{
		"34_rnd_sterling_mag",
		"34_rnd_sterling_mag",
		"34_rnd_sterling_mag",
		"34_rnd_sterling_mag",
		"34_rnd_sterling_mag"
		};
		Respawnmagazines[]=
		{
		"34_rnd_sterling_mag",
		"34_rnd_sterling_mag",
		"34_rnd_sterling_mag",
		"34_rnd_sterling_mag",
		"34_rnd_sterling_mag"
		};
		Items[]=
		{
		"ACE_EarPlugs",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_morphine",
		"ACE_morphine",
		"ACE_epinephrine",
		"ACE_tourniquet"
		};
		respawntems[]=
		{
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_morphine",
		"ACE_morphine",
		"ACE_epinephrine",
		"ACE_tourniquet"		
		};		
	};
	class ColdWar_MilanGunner: B_Soldier_base_F
	{
		_generalMacro="Coldwar_MilanGunner";
		scope=2;
		displayName="Milan Gunner(Coldwar)";
		faction="twc_faction";
		editorSubCategory = "Men_ColdWar";
		vehicleClass="Men_ColdWar";
		icon="iconMan";
		nakedUniform="U_BasicBody";
		uniformClass="MNP_CombatUniform_DPMR";
		backpack="TWC_Backpack_Cold_War_Milan";
		linkedItems[]=
		{
        "CUP_V_RUS_Smersh_1",
		"SP_MkBushHelmet_Forrest",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
		};
		respawnLinkedItems[]=
		{
        "CUP_V_RUS_Smersh_1",
		"SP_MkBushHelmet_Forrest",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
		};
		weapons[]=
		{
		"Throw",
		"Put",	
		"TWC_Sterling_Sub",
		"TWC_Milan_Tripod_Disassemabled"	
		};
		respawnweapons[]=
		{
		"Throw",
		"Put",	
		"TWC_Sterling_Sub",
		"TWC_Milan_Tripod_Disassemabled"
		};
		magazines[]=
		{
		"34_rnd_sterling_mag",
		"34_rnd_sterling_mag",
		"34_rnd_sterling_mag",
		"34_rnd_sterling_mag",
		"34_rnd_sterling_mag"
		};
		Respawnmagazines[]=
		{	
		"34_rnd_sterling_mag",
		"34_rnd_sterling_mag",
		"34_rnd_sterling_mag",
		"34_rnd_sterling_mag",
		"34_rnd_sterling_mag"
		};
		Items[]=
		{
		"ACE_EarPlugs",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_morphine",
		"ACE_morphine",
		"ACE_epinephrine",
		"ACE_tourniquet"
		};
		respawntems[]=
		{
		"ACE_EarPlugs",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_morphine",
		"ACE_morphine",
		"ACE_epinephrine",
		"ACE_tourniquet"			
		};		
	};
	class ColdWar_MilanAssistant: B_Soldier_base_F
	{
		_generalMacro="Coldwar_MilanAssistant";
		scope=2;
		displayName="Milan Assistant(Coldwar)";
		faction="twc_faction";
		editorSubCategory = "Men_ColdWar";
		vehicleClass="Men_ColdWar";
		icon="iconMan";
		nakedUniform="U_BasicBody";
		uniformClass="MNP_CombatUniform_DPMR";
		backpack="TWC_Backpack_Cold_War_Milan";
		linkedItems[]=
		{
        "CUP_V_RUS_Smersh_1",
		"SP_MkBushHelmet_Forrest",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
		};
		respawnLinkedItems[]=
		{
        "CUP_V_RUS_Smersh_1",
		"SP_MkBushHelmet_Forrest",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
		};
		weapons[]=
		{
		"Throw",
		"Put",	
		"TWC_Sterling_Sub",
		"TWC_Milan_Launcher_Disassemabled"	
		};
		respawnweapons[]=
		{
		"Throw",
		"Put",	
		"TWC_Sterling_Sub",
		"TWC_Milan_Launcher_Disassemabled"
		};
		magazines[]=
		{
		"34_rnd_sterling_mag",
		"34_rnd_sterling_mag",
		"34_rnd_sterling_mag",
		"34_rnd_sterling_mag",
		"34_rnd_sterling_mag"
		};
		Respawnmagazines[]=
		{
		"34_rnd_sterling_mag",
		"34_rnd_sterling_mag",
		"34_rnd_sterling_mag",
		"34_rnd_sterling_mag",
		"34_rnd_sterling_mag"
		};
		Items[]=
		{
		"ACE_EarPlugs",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_morphine",
		"ACE_morphine",
		"ACE_epinephrine",
		"ACE_tourniquet"
		};
		respawntems[]=
		{
		"ACE_EarPlugs",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_morphine",
		"ACE_morphine",
		"ACE_epinephrine",
		"ACE_tourniquet"			
		};		
	};
	class ColdWar_MortarGunner: B_Soldier_base_F
	{
		_generalMacro="Coldwar_MortarGunner";
		scope=2;
		displayName="Mortar Gunner(Coldwar)";
		faction="twc_faction";
		editorSubCategory = "Men_ColdWar";
		vehicleClass="Men_ColdWar";
		icon="iconMan";
		nakedUniform="U_BasicBody";
		uniformClass="MNP_CombatUniform_DPMR";
		backpack="TWC_Backpack_Cold_War_MortarGunner";
		linkedItems[]=
		{
        "CUP_V_RUS_Smersh_1",
		"SP_MkBushHelmet_Forrest",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
		};
		respawnLinkedItems[]=
		{
        "CUP_V_RUS_Smersh_1",
		"SP_MkBushHelmet_Forrest",
		"ItemCompass",
		"itemMap",
		"ItemWatch"
		};
		weapons[]=
		{
		"Throw",
		"Put",	
		"TWC_Sterling_Sub",
		"UK3CB_BAF_M6"		
		};
		respawnweapons[]=
		{
		"Throw",
		"Put",	
		"TWC_Sterling_Sub",
		"UK3CB_BAF_M6"	
		};
		magazines[]=
		{
		"34_rnd_sterling_mag",
		"34_rnd_sterling_mag",
		"34_rnd_sterling_mag",
		"34_rnd_sterling_mag",
		"34_rnd_sterling_mag",
		"UK3CB_BAF_1Rnd_60mm_Mo_Shells",
		"UK3CB_BAF_1Rnd_60mm_Mo_Smoke_White",
		"UK3CB_BAF_1Rnd_60mm_Mo_Smoke_White"
		};
		Respawnmagazines[]=
		{
		"34_rnd_sterling_mag",
		"34_rnd_sterling_mag",
		"34_rnd_sterling_mag",
		"34_rnd_sterling_mag",
		"34_rnd_sterling_mag",
		"UK3CB_BAF_1Rnd_60mm_Mo_Shells",
		"UK3CB_BAF_1Rnd_60mm_Mo_Smoke_White",
		"UK3CB_BAF_1Rnd_60mm_Mo_Smoke_White"
		};
		Items[]=
		{
		"ACE_EarPlugs",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_morphine",
		"ACE_morphine",
		"ACE_epinephrine",
		"ACE_tourniquet"
		};
		respawntems[]=
		{
		"ACE_EarPlugs",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_morphine",
		"ACE_morphine",
		"ACE_epinephrine",
		"ACE_tourniquet"			
		};		
	};
