class CfgPatches
{
	class twc_faction
	{
		units[]=
		{
			"Modern_British_Squadleader",
			"GulfWar_Iraqi_Squadleader",
			"GulfWar_Iraqi_Rifleman",
			"GulfWar_Iraqi_RPG",
			"GulfWar_Iraqi_RPGAssistant",
			"GulfWar_Iraqi_MG",
			"GulfWar_Iraqi_MGAssistant",
			"USSR_Squadleader",
			"USSR_Rifleman",
			"USSR_Grenadier",
			"USSR_Seniorrifleman",
			"USSR_Grenadierassistant",
			"USSR_Automaticrifleman",
			"USSR_Vehiclecommander",
			"USSR_Vehiclecrew"
		};
		weapons[]={};
		requiredVersion=0.1;
		requiredAddons[]=
		{
			"A3_Characters_F_BLUFOR",
			"A3_Characters_F_OPFOR"
		};
	};
};
class CfgFactionClasses
{
	class a_units
	{
		displayName="TWC Operation Units";
		author="FakeMatty";
		icon="TWClogo.paa";
		priority=2;
		side=1;
	};
	class Veh_units
	{
		displayName="TWC Vehicles";
		author="FakeMatty";
		icon="TWClogo.paa";
		priority=2;
		side=1;
	};
	class Iraqi_units
	{
		displayName="Iraqi Army Gulf War Units";
		author="Rik";
		icon="TWClogo.paa";
		priority=2;
		side=0;
	};
	class argentinian_units
	{
		displayName="Argentinian Units";
		author="Rik";
		icon="TWClogo.paa";
		priority=2;
		side=2;
	};
};
class CfgVehicleClasses
{
	class Modern_British
	{
		displayName="Modern British";
	};
	class Coin_British
	{
		displayName="Modern COIN British";
	};
	class Cold_British
	{
		displayName="Cold War British";
	};
	class 1990_British
	{
		displayName="1990 British";
	};
	class 1990_Desert_British
	{
		displayName = "1990 Desert British";
	};
	class USSR
	{
		displayName="USSR";
	};
	class Attachments
	{
		displayName="Attachments";
	};
	class NewVehicles
	{
		displayName="Vehicles";
	};
	class GulfWar_Iraqi
	{
		displayName="Gulf War Iraqi";
	};
	class Cold_War_Argentinian
	{
		displayname="Cold War Argentinia";
	};
};
class CfgVehicles
{
	class B_Soldier_base_F;
	class O_Soldier_base_F;
	class I_Soldier_F;
	
/*///////////////////////////////////////
//                                     //
//              USSR                   //
//                                     //
///////////////////////////////////////*/
	class USSR_Squadleader:O_Soldier_base_F
	{
		_generalMacro="USSR_Squadleader";
		scope=2;
		displayName="Section Leader";
		faction="a_units";
		vehicleClass="USSR";
		icon="iconMan";
		nakedUniform="U_BasicBody";
		uniformClass="rhs_uniform_flora";
		backpack="TWC_Backpack_USSR_Sectionlead";
		linkedItems[]=
		{
        "rhs_6b23_6sh92_headset_mapcase",
		"ItemMap",
		"ItemCompass",
		"ItemWatch",
		"rhs_6b26_ess",
		"ACRE_PRC343"
		};
		respawnLinkedItems[]=
		{
        "rhs_6b23_6sh92_headset_mapcase",
		"ItemMap",
		"ItemCompass",
		"ItemWatch",
		"rhs_6b26_ess",
		"ACRE_PRC343"
		};
		weapons[]=
		{
		"Throw",
		"Put",
		"ACE_Vector",
		"USSR_AK74_1p29",
		"rhs_weap_makarov_pmm"
		};
		respawnweapons[]=
		{
		"Throw",
		"Put",
		"ACE_Vector",
		"USSR_AK74_1p29",
		"rhs_weap_makarov_pmm"
		};
		magazines[]=
		{
		"rhs_mag_9x18_12_57N181S",
		"rhs_mag_9x18_12_57N181S",
		"rhs_mag_9x18_12_57N181S",
		"rhs_30Rnd_545x39_7N10_AK",
		"rhs_30Rnd_545x39_7N10_AK",
		"rhs_30Rnd_545x39_7N10_AK",
		"rhs_30Rnd_545x39_7N10_AK",
		"rhs_30Rnd_545x39_7N10_AK",
		"rhs_30Rnd_545x39_7N10_AK",
		"rhs_30Rnd_545x39_7N10_AK",
		"rhs_30Rnd_545x39_7N10_AK",
		"rhs_mag_rgd5",
		"rhs_mag_rgd5",
		"SmokeShell",
		"SmokeShell",
		"SmokeShell"
		};
		Respawnmagazines[]=
		{
		"rhs_mag_9x18_12_57N181S",
		"rhs_mag_9x18_12_57N181S",
		"rhs_mag_9x18_12_57N181S",
		"rhs_30Rnd_545x39_7N10_AK",
		"rhs_30Rnd_545x39_7N10_AK",
		"rhs_30Rnd_545x39_7N10_AK",
		"rhs_30Rnd_545x39_7N10_AK",
		"rhs_30Rnd_545x39_7N10_AK",
		"rhs_30Rnd_545x39_7N10_AK",
		"rhs_30Rnd_545x39_7N10_AK",
		"rhs_30Rnd_545x39_7N10_AK",
		"rhs_mag_rgd5",
		"rhs_mag_rgd5",
		"SmokeShell",
		"SmokeShell",
		"SmokeShell"
		};
		Items[]=
		{
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_morphine",
		"ACE_morphine",
		"ACE_EarPlugs"
		};
		respawntems[]=
		{
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_morphine",
		"ACE_morphine",
		"ACE_EarPlugs"	
		};		
	};
	class USSR_Rifleman:O_Soldier_base_F
	{
		_generalMacro="USSR_Rifleman";
		scope=2;
		displayName="Rifleman";
		faction="a_units";
		vehicleClass="USSR";
		icon="iconMan";
		nakedUniform="U_BasicBody";
		uniformClass="rhs_uniform_flora";
		backpack="TWC_Backpack_USSR_Rifleman";
		linkedItems[]=
		{
        "rhs_6b23_6sh92",
		"BAF_Soldier_1_Headgear_W_DG1",
		"ItemMap",
		"ItemCompass",
		"ItemWatch",
		"rhs_6b26",
		"ACRE_PRC343"
		};
		respawnLinkedItems[]=
		{
        "rhs_6b23_6sh92_headset_mapcase",
		"ItemMap",
		"ItemCompass",
		"ItemWatch",
		"rhs_6b26",
		"ACRE_PRC343"
		};
		weapons[]=
		{
		"Throw",
		"Put",
		"rhs_weap_ak74m_dtk",
		"rhs_weap_makarov_pmm"
		};
		respawnweapons[]=
		{
		"Throw",
		"Put",	
		"rhs_weap_ak74m_dtk",
		"rhs_weap_makarov_pmm"
		};
		magazines[]=
		{
		"rhs_mag_9x18_12_57N181S",
		"rhs_mag_9x18_12_57N181S",
		"rhs_mag_9x18_12_57N181S",
		"rhs_30Rnd_545x39_7N10_AK",
		"rhs_30Rnd_545x39_7N10_AK",
		"rhs_mag_rgd5",
		"rhs_mag_rgd5",
		"SmokeShell",
		"SmokeShell",
		"SmokeShell"
		};
		Respawnmagazines[]=
		{
		"rhs_mag_9x18_12_57N181S",
		"rhs_mag_9x18_12_57N181S",
		"rhs_mag_9x18_12_57N181S",
		"rhs_30Rnd_545x39_7N10_AK",
		"rhs_30Rnd_545x39_7N10_AK",
		"rhs_mag_rgd5",
		"rhs_mag_rgd5",
		"SmokeShell",
		"SmokeShell",
		"SmokeShell"
		};
		Items[]=
		{
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_morphine",
		"ACE_morphine",
		"ACE_EarPlugs"
		};
		respawntems[]=
		{
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_morphine",
		"ACE_morphine",
		"ACE_EarPlugs"	
		};		
	};
	class USSR_Grenadier:O_Soldier_base_F
	{
		_generalMacro="USSR_Grenadier";
		scope=2;
		displayName="Grenadier";
		faction="a_units";
		vehicleClass="USSR";
		icon="iconMan";
		nakedUniform="U_BasicBody";
		uniformClass="rhs_uniform_flora";
		backpack="TWC_Backpack_USSR_Grenadier";
		linkedItems[]=
		{
        "rhs_6b23_6sh92",
		"BAF_Soldier_1_Headgear_W_DG1",
		"ItemMap",
		"ItemCompass",
		"ItemWatch",
		"rhs_6b26",
		"ACRE_PRC343"
		};
		respawnLinkedItems[]=
		{
        "rhs_6b23_6sh92_headset_mapcase",
		"ItemMap",
		"ItemCompass",
		"ItemWatch",
		"rhs_6b26",
		"ACRE_PRC343"
		};
		weapons[]=
		{
		"Throw",
		"Put",
		"rhs_weap_ak74m_dtk",
		"rhs_weap_rpg7",
		"rhs_weap_makarov_pmm"
		};
		respawnweapons[]=
		{
		"Throw",
		"Put",	
		"rhs_weap_ak74m_dtk",
		"rhs_weap_rpg7",
		"rhs_weap_makarov_pmm"
		};
		magazines[]=
		{
		"rhs_mag_9x18_12_57N181S",
		"rhs_mag_9x18_12_57N181S",
		"rhs_mag_9x18_12_57N181S",
		"rhs_30Rnd_545x39_7N10_AK",
		"rhs_30Rnd_545x39_7N10_AK",
		"rhs_30Rnd_545x39_7N10_AK",
		"rhs_30Rnd_545x39_7N10_AK",
		"rhs_mag_rgd5",
		"rhs_mag_rgd5",
		"SmokeShell",
		"SmokeShell",
		"SmokeShell"
		};
		Respawnmagazines[]=
		{
		"rhs_mag_9x18_12_57N181S",
		"rhs_mag_9x18_12_57N181S",
		"rhs_mag_9x18_12_57N181S",
		"rhs_30Rnd_545x39_7N10_AK",
		"rhs_30Rnd_545x39_7N10_AK",
		"rhs_30Rnd_545x39_7N10_AK",
		"rhs_30Rnd_545x39_7N10_AK",
		"rhs_mag_rgd5",
		"rhs_mag_rgd5",
		"SmokeShell",
		"SmokeShell",
		"SmokeShell"
		};
		Items[]=
		{
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_morphine",
		"ACE_morphine",
		"ACE_EarPlugs"
		};
		respawntems[]=
		{
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_morphine",
		"ACE_morphine",
		"ACE_EarPlugs"	
		};		
	};
	class USSR_Seniorrifleman:O_Soldier_base_F
	{
		_generalMacro="USSR_Seniorrifleman";
		scope=2;
		displayName="Senior Rifleman";
		faction="a_units";
		vehicleClass="USSR";
		icon="iconMan";
		nakedUniform="U_BasicBody";
		uniformClass="rhs_uniform_flora";
		backpack="TWC_Backpack_USSR_Seniorrifleman";
		linkedItems[]=
		{
        "rhs_6b23_6sh92",
		"BAF_Soldier_1_Headgear_W_DG1",
		"ItemMap",
		"ItemCompass",
		"ItemWatch",
		"rhs_6b26",
		"ACRE_PRC343"
		};
		respawnLinkedItems[]=
		{
        "rhs_6b23_6sh92_headset_mapcase",
		"ItemMap",
		"ItemCompass",
		"ItemWatch",
		"rhs_6b26",
		"ACRE_PRC343"
		};
		weapons[]=
		{
		"Throw",
		"Put",
		"ACE_Vector",
		"USSR_AK74_1p29",
		"rhs_weap_makarov_pmm"
		};
		respawnweapons[]=
		{
		"Throw",
		"Put",
		"ACE_Vector",
		"USSR_AK74_1p29",
		"rhs_weap_makarov_pmm"
		};
		magazines[]=
		{
		"rhs_mag_9x18_12_57N181S",
		"rhs_mag_9x18_12_57N181S",
		"rhs_mag_9x18_12_57N181S",
		"rhs_30Rnd_545x39_7N10_AK",
		"rhs_30Rnd_545x39_7N10_AK",
		"rhs_mag_rgd5",
		"rhs_mag_rgd5",
		"SmokeShell",
		"SmokeShell",
		"SmokeShell"
		};
		Respawnmagazines[]=
		{
		"rhs_mag_9x18_12_57N181S",
		"rhs_mag_9x18_12_57N181S",
		"rhs_mag_9x18_12_57N181S",
		"rhs_30Rnd_545x39_7N10_AK",
		"rhs_30Rnd_545x39_7N10_AK",
		"rhs_mag_rgd5",
		"rhs_mag_rgd5",
		"SmokeShell",
		"SmokeShell",
		"SmokeShell"
		};
		Items[]=
		{
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_morphine",
		"ACE_morphine",
		"ACE_EarPlugs"
		};
		respawntems[]=
		{
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_morphine",
		"ACE_morphine",
		"ACE_EarPlugs"	
		};		
	};
	class USSR_Grenadierassistant:O_Soldier_base_F
	{
		_generalMacro="USSR_Grenadierassistant";
		scope=2;
		displayName="Grenadier Assistant";
		faction="a_units";
		vehicleClass="USSR";
		icon="iconMan";
		nakedUniform="U_BasicBody";
		uniformClass="rhs_uniform_flora";
		backpack="TWC_Backpack_USSR_Grenadierassistant";
		linkedItems[]=
		{
        "rhs_6b23_6sh92",
		"BAF_Soldier_1_Headgear_W_DG1",
		"ItemMap",
		"ItemCompass",
		"ItemWatch",
		"rhs_6b26",
		"ACRE_PRC343"
		};
		respawnLinkedItems[]=
		{
        "rhs_6b23_6sh92_headset_mapcase",
		"ItemMap",
		"ItemCompass",
		"ItemWatch",
		"rhs_6b26",
		"ACRE_PRC343"
		};
		weapons[]=
		{
		"Throw",
		"Put",	
		"rhs_weap_ak74m_dtk",
		"rhs_weap_makarov_pmm"
		};
		respawnweapons[]=
		{
		"Throw",
		"Put",	
		"rhs_weap_ak74m_dtk",
		"rhs_weap_makarov_pmm"
		};
		magazines[]=
		{
		"rhs_mag_9x18_12_57N181S",
		"rhs_mag_9x18_12_57N181S",
		"rhs_mag_9x18_12_57N181S",
		"rhs_30Rnd_545x39_7N10_AK",
		"rhs_30Rnd_545x39_7N10_AK",
		"rhs_30Rnd_545x39_7N10_AK",
		"rhs_30Rnd_545x39_7N10_AK",
		"rhs_mag_rgd5",
		"rhs_mag_rgd5",
		"SmokeShell",
		"SmokeShell",
		"SmokeShell"
		};
		Respawnmagazines[]=
		{
		"rhs_mag_9x18_12_57N181S",
		"rhs_mag_9x18_12_57N181S",
		"rhs_mag_9x18_12_57N181S",
		"rhs_30Rnd_545x39_7N10_AK",
		"rhs_30Rnd_545x39_7N10_AK",
		"rhs_30Rnd_545x39_7N10_AK",
		"rhs_30Rnd_545x39_7N10_AK",
		"rhs_mag_rgd5",
		"rhs_mag_rgd5",
		"SmokeShell",
		"SmokeShell",
		"SmokeShell"
		};
		Items[]=
		{
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_morphine",
		"ACE_morphine",
		"ACE_EarPlugs"
		};
		respawntems[]=
		{
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_morphine",
		"ACE_morphine",
		"ACE_EarPlugs"	
		};		
	};
	class USSR_Automaticrifleman:O_Soldier_base_F
	{
		_generalMacro="USSR_Automaticrifleman";
		scope=2;
		displayName="Automatic Rifleman";
		faction="a_units";
		vehicleClass="USSR";
		icon="iconMan";
		nakedUniform="U_BasicBody";
		uniformClass="rhs_uniform_flora";
		backpack="TWC_Backpack_USSR_Automaticrifleman";
		linkedItems[]=
		{
        "rhs_6b23_6sh92",
		"BAF_Soldier_1_Headgear_W_DG1",
		"ItemMap",
		"ItemCompass",
		"ItemWatch",
		"rhs_6b26",
		"ACRE_PRC343"
		};
		respawnLinkedItems[]=
		{
        "rhs_6b23_6sh92_headset_mapcase",
		"ItemMap",
		"ItemCompass",
		"ItemWatch",
		"rhs_6b26",
		"ACRE_PRC343"
		};
		weapons[]=
		{
		"Throw",
		"Put",	
		"rhs_weap_pkm",
		"rhs_weap_makarov_pmm"
		};
		respawnweapons[]=
		{
		"Throw",
		"Put",	
		"rhs_weap_pkm",
		"rhs_weap_makarov_pmm"
		};
		magazines[]=
		{
		"rhs_mag_9x18_12_57N181S",
		"rhs_mag_9x18_12_57N181S",
		"rhs_mag_9x18_12_57N181S",
		"rhs_100Rnd_762X54mmR",
		"rhs_mag_rgd5",
		"rhs_mag_rgd5",
		"SmokeShell",
		"SmokeShell",
		"SmokeShell"
		};
		Respawnmagazines[]=
		{
		"rhs_mag_9x18_12_57N181S",
		"rhs_mag_9x18_12_57N181S",
		"rhs_mag_9x18_12_57N181S",
		"rhs_100Rnd_762X54mmR",
		"rhs_mag_rgd5",
		"rhs_mag_rgd5",
		"SmokeShell",
		"SmokeShell",
		"SmokeShell"
		};
		Items[]=
		{
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_morphine",
		"ACE_morphine",
		"ACE_EarPlugs"
		};
		respawntems[]=
		{
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_morphine",
		"ACE_morphine",
		"ACE_EarPlugs"	
		};		
	};
	class USSR_Vehiclecommander:O_Soldier_base_F
	{
		_generalMacro="USSR_Vehiclecommander";
		scope=2;
		displayName="Vehicle Commander";
		faction="a_units";
		vehicleClass="USSR";
		icon="iconMan";
		nakedUniform="U_BasicBody";
		uniformClass="rhs_uniform_msv_emr";
		backpack="TWC_Backpack_USSR_Vehiclecommander";
		linkedItems[]=
		{
        "rhs_vest_commander",
		"ItemMap",
		"ItemCompass",
		"ItemWatch",
		"rhs_tsh4",
		"ACRE_PRC343"
		};
		respawnLinkedItems[]=
		{
        "rhs_vest_commander",
		"ItemMap",
		"ItemCompass",
		"ItemWatch",
		"rhs_tsh4",
		"ACRE_PRC343"
		};
		weapons[]=
		{
		"Throw",
		"Put",
		"Binocular",
		"rhs_weap_ak74m_folded_dtk",
		"rhs_weap_makarov_pmm"
		};
		respawnweapons[]=
		{
		"Throw",
		"Put",
		"Binocular",
		"rhs_weap_ak74m_folded_dtk",
		"rhs_weap_makarov_pmm"
		};
		magazines[]=
		{
		"rhs_mag_9x18_12_57N181S",
		"rhs_30Rnd_545x39_7N10_AK",
		"rhs_30Rnd_545x39_7N10_AK",
		"rhs_30Rnd_545x39_7N10_AK",
		"rhs_mag_rgd5",
		"SmokeShell"
		};
		Respawnmagazines[]=
		{
		"rhs_mag_9x18_12_57N181S",
		"rhs_30Rnd_545x39_7N10_AK",
		"rhs_30Rnd_545x39_7N10_AK",
		"rhs_30Rnd_545x39_7N10_AK",
		"rhs_mag_rgd5",
		"SmokeShell"
		};
		Items[]=
		{
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_morphine",
		"ACE_morphine",
		"ACE_EarPlugs"
		};
		respawntems[]=
		{
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_morphine",
		"ACE_morphine",
		"ACE_EarPlugs"	
		};		
	};
	class USSR_Vehiclecrew:O_Soldier_base_F
	{
		_generalMacro="USSR_Vehiclecrew";
		scope=2;
		displayName="Vehicle Crew";
		faction="a_units";
		vehicleClass="USSR";
		icon="iconMan";
		nakedUniform="U_BasicBody";
		uniformClass="rhs_uniform_msv_emr";
		backpack="";
		linkedItems[]=
		{
        "rhs_vest_commander",
		"ItemMap",
		"ItemCompass",
		"ItemWatch",
		"rhs_tsh4",
		"ACRE_PRC343"
		};
		respawnLinkedItems[]=
		{
        "rhs_vest_commander",
		"ItemMap",
		"ItemCompass",
		"ItemWatch",
		"rhs_tsh4",
		"ACRE_PRC343"
		};
		weapons[]=
		{
		"Throw",
		"Put",	
		"rhs_weap_ak74m_folded_dtk",
		"rhs_weap_makarov_pmm"
		};
		respawnweapons[]=
		{
		"Throw",
		"Put",	
		"rhs_weap_ak74m_folded_dtk",
		"rhs_weap_makarov_pmm"
		};
		magazines[]=
		{
		"rhs_mag_9x18_12_57N181S",
		"rhs_30Rnd_545x39_7N10_AK",
		"rhs_30Rnd_545x39_7N10_AK",
		"rhs_30Rnd_545x39_7N10_AK",
		"rhs_mag_rgd5",
		"SmokeShell"
		};
		Respawnmagazines[]=
		{
		"rhs_mag_9x18_12_57N181S",
		"rhs_30Rnd_545x39_7N10_AK",
		"rhs_30Rnd_545x39_7N10_AK",
		"rhs_30Rnd_545x39_7N10_AK",
		"rhs_mag_rgd5",
		"SmokeShell"
		};
		Items[]=
		{
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_morphine",
		"ACE_morphine",
		"ACE_EarPlugs"
		};
		respawntems[]=
		{
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_morphine",
		"ACE_morphine",
		"ACE_EarPlugs"	
		};		
	};
/* ***********************************
*
*            Iraqi Units
*
************************************* */
	class GulfWar_Iraqi_Squadleader: O_Soldier_base_F
	{
		_generalMacro="GulfWar_Iraqi_Squadleader";
		scope=2;
		displayName="Section Leader";
		faction="Iraqi_units";
		vehicleClass="GulfWar_Iraqi";
		icon="iconManLeader";
		nakedUniform="U_BasicBody";
		uniformClass="MNP_CombatUniform_NKR_Rg";
		backpack="";
		linkedItems[]=
		{
        "V_sud_ussr_vest05",
		"SP_M1Helmet_GrayDim",
		"ItemMap",
		"ItemCompass",
		"ItemWatch"
		};
		respawnLinkedItems[]=
		{
        "V_sud_ussr_vest05",
		"ItemMap",
		"ItemCompass",
		"ItemWatch"
		};
		weapons[]=
		{
		"Throw",
		"Put",
		"Binocular",
		"CUP_arifle_AK74",
		"CUP_hgun_Makarov"
		};
		respawnweapons[]=
		{
		"Throw",
		"Put",
		"Binocular",
		"CUP_arifle_AK74",
		"CUP_hgun_Makarov"
		};
		magazines[]=
		{
		"CUP_30Rnd_545x39_AK_M",
		"CUP_30Rnd_545x39_AK_M",
		"CUP_30Rnd_545x39_AK_M",
	    "CUP_30Rnd_545x39_AK_M",
	    "CUP_30Rnd_545x39_AK_M",
		"CUP_30Rnd_545x39_AK_M",
		"CUP_30Rnd_545x39_AK_M",
		"CUP_30Rnd_545x39_AK_M",
		"CUP_8Rnd_9x18_Makarov_M",
		"CUP_HandGrenade_RGO",
		"CUP_HandGrenade_RGO"
		};
		Respawnmagazines[]=
		{
		"CUP_30Rnd_545x39_AK_M",
		"CUP_30Rnd_545x39_AK_M",
		"CUP_30Rnd_545x39_AK_M",
	    "CUP_30Rnd_545x39_AK_M",
	    "CUP_30Rnd_545x39_AK_M",
		"CUP_30Rnd_545x39_AK_M",
		"CUP_30Rnd_545x39_AK_M",
		"CUP_30Rnd_545x39_AK_M",
		"CUP_8Rnd_9x18_Makarov_M",
		"CUP_HandGrenade_RGO",
		"CUP_HandGrenade_RGO"
		};
		Items[]=
		{
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_morphine",
		"ACE_morphine",
		"ACE_EarPlugs"	
		};
		respawntems[]=
		{
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_morphine",
		"ACE_morphine",
		"ACE_EarPlugs"			
		};
	};
	
	class GulfWar_Iraqi_Rifleman: O_Soldier_base_F
	{
		_generalMacro="GulfWar_Iraqi_Rifleman";
		scope=2;
		displayName="Rifleman";
		faction="Iraqi_units";
		vehicleClass="GulfWar_Iraqi";
		icon="iconMan";
		nakedUniform="U_BasicBody";
		uniformClass="MNP_CombatUniform_NKR_Rg";
		backpack="";
		linkedItems[]=
		{
        "V_sud_ussr_vest05",
		"SP_M1Helmet_GrayDim"
		};
		respawnLinkedItems[]=
		{
        "V_sud_ussr_vest05"
		};
		weapons[]=
		{
		"Throw",
		"Put",	
		"CUP_arifle_AK74",
		"CUP_hgun_Makarov"
		};
		respawnweapons[]=
		{
		"Throw",
		"Put",	
		"CUP_arifle_AK74",
		"CUP_hgun_Makarov"
		};
		magazines[]=
		{
		"CUP_30Rnd_545x39_AK_M",
		"CUP_30Rnd_545x39_AK_M",
		"CUP_30Rnd_545x39_AK_M",
		"CUP_30Rnd_545x39_AK_M",
		"CUP_30Rnd_545x39_AK_M",
		"CUP_30Rnd_545x39_AK_M",
		"CUP_30Rnd_545x39_AK_M",
		"CUP_30Rnd_545x39_AK_M",
		"CUP_8Rnd_9x18_Makarov_M",
		"CUP_HandGrenade_RGO",
		"CUP_HandGrenade_RGO",
		"SmokeShell",
		"SmokeShell"
		};
		Respawnmagazines[]=
		{
		"CUP_30Rnd_545x39_AK_M",
		"CUP_30Rnd_545x39_AK_M",
		"CUP_30Rnd_545x39_AK_M",
		"CUP_30Rnd_545x39_AK_M",
		"CUP_30Rnd_545x39_AK_M",
		"CUP_30Rnd_545x39_AK_M",
		"CUP_30Rnd_545x39_AK_M",
		"CUP_30Rnd_545x39_AK_M",
		"CUP_8Rnd_9x18_Makarov_M",
		"CUP_HandGrenade_RGO",
		"CUP_HandGrenade_RGO",
		"SmokeShell",
		"SmokeShell"
		};
		Items[]=
		{
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_morphine",
		"ACE_morphine",
		"ACE_EarPlugs"
		};
		respawntems[]=
		{
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_morphine",
		"ACE_morphine",
		"ACE_EarPlugs"	
		};		
	};

	class GulfWar_Iraqi_RPG: O_Soldier_base_F
	{
		_generalMacro="GulfWar_Iraqi_RPG";
		scope=2;
		displayName="RPG Gunner";
		faction="Iraqi_units";
		vehicleClass="GulfWar_Iraqi";
		icon="iconManExplosive";
		nakedUniform="U_BasicBody";
		uniformClass="MNP_CombatUniform_NKR_Rg";
		backpack="B_mas_m_Bergen_rpg";
		linkedItems[]=
		{
        "V_sud_ussr_vest05",
		"SP_M1Helmet_GrayDim"
		};
		respawnLinkedItems[]=
		{
        "V_sud_ussr_vest05"
		};
		weapons[]=
		{
		"Throw",
		"Put",
		"CUP_arifle_AK74",
		"CUP_hgun_Makarov",
		"CUP_launch_RPG7V"
		};
		respawnweapons[]=
		{
		"Throw",
		"Put",
		"CUP_arifle_AK74",
		"CUP_hgun_Makarov",
		"CUP_launch_RPG7V"
		};
		magazines[]=
		{
		"CUP_30Rnd_545x39_AK_M",
		"CUP_30Rnd_545x39_AK_M",		
		"CUP_30Rnd_545x39_AK_M",
		"CUP_30Rnd_545x39_AK_M",
		"CUP_30Rnd_545x39_AK_M",
		"CUP_30Rnd_545x39_AK_M",	
		"CUP_30Rnd_545x39_AK_M",	
		"CUP_30Rnd_545x39_AK_M",
		"CUP_8Rnd_9x18_Makarov_M",
		"CUP_PG7V_M",
		"CUP_PG7V_M",
		"CUP_PG7V_M",
		"CUP_PG7V_M",
		"CUP_HandGrenade_RGO",
		"CUP_HandGrenade_RGO",
		"SmokeShell",
		"SmokeShell"
		};
		Respawnmagazines[]=
		{
		"CUP_30Rnd_545x39_AK_M",
		"CUP_30Rnd_545x39_AK_M",		
		"CUP_30Rnd_545x39_AK_M",
		"CUP_30Rnd_545x39_AK_M",
		"CUP_30Rnd_545x39_AK_M",
		"CUP_30Rnd_545x39_AK_M",	
		"CUP_30Rnd_545x39_AK_M",	
		"CUP_30Rnd_545x39_AK_M",
		"CUP_8Rnd_9x18_Makarov_M",
		"CUP_HandGrenade_RGO",
		"CUP_HandGrenade_RGO",
		"SmokeShell",
		"SmokeShell"
		};
		Items[]=
		{
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_morphine",
		"ACE_morphine",
		"ACE_EarPlugs"
		};
		respawntems[]=
		{
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_morphine",
		"ACE_morphine",
		"ACE_EarPlugs"	
		};
	};

	class GulfWar_Iraqi_RPGAssistant: O_Soldier_base_F
	{
		_generalMacro="GulfWar_Iraqi_RPGAssistant";
		scope=2;
		displayName="RPG Assistant";
		faction="Iraqi_units";
		vehicleClass="GulfWar_Iraqi";
		icon="iconManMG";
		nakedUniform="U_BasicBody";
		uniformClass="MNP_CombatUniform_NKR_Rg";
		backpack="B_SUD_RPG";
		linkedItems[]=
		{
        "V_sud_ussr_vest05",
		"SP_M1Helmet_GrayDim"
		};
		respawnLinkedItems[]=
		{
        "V_sud_ussr_vest05"
		};
		weapons[]=
		{
		"Throw",
		"Put",
		"CUP_arifle_AK74",
		"CUP_hgun_Makarov"
		};
		respawnweapons[]=
		{
		"Throw",
		"Put",
		"CUP_arifle_AK74",
		"CUP_hgun_Makarov"
		};
		magazines[]=
		{
		"CUP_30Rnd_545x39_AK_M",
		"CUP_30Rnd_545x39_AK_M",
		"CUP_30Rnd_545x39_AK_M",
		"CUP_30Rnd_545x39_AK_M",
		"CUP_30Rnd_545x39_AK_M",
		"CUP_30Rnd_545x39_AK_M",
		"CUP_30Rnd_545x39_AK_M",
		"CUP_30Rnd_545x39_AK_M",
		"CUP_8Rnd_9x18_Makarov_M",
		"SUD_PG7VL",
		"SUD_PG7VL",
		"SUD_PG7VL",
		"CUP_HandGrenade_RGO",
		"CUP_HandGrenade_RGO",
		"SmokeShell",
		"SmokeShell"
		};
		Respawnmagazines[]=
		{
		"CUP_30Rnd_545x39_AK_M",
		"CUP_30Rnd_545x39_AK_M",
		"CUP_30Rnd_545x39_AK_M",
		"CUP_30Rnd_545x39_AK_M",
		"CUP_30Rnd_545x39_AK_M",
		"CUP_30Rnd_545x39_AK_M",
		"CUP_30Rnd_545x39_AK_M",
		"CUP_30Rnd_545x39_AK_M",
		"CUP_8Rnd_9x18_Makarov_M",
		"CUP_HandGrenade_RGO",
		"CUP_HandGrenade_RGO",
		"SmokeShell",
		"SmokeShell"
		};
		Items[]=
		{
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_morphine",
		"ACE_morphine",
		"ACE_EarPlugs"
		};
		respawntems[]=
		{
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_morphine",
		"ACE_morphine",
		"ACE_EarPlugs"		
		};
	};

	class GulfWar_Iraqi_MG: O_Soldier_base_F
	{
		_generalMacro="GulfWar_Iraqi_MG";
		scope=2;
		displayName="Machinegunner";
		faction="Iraqi_units";
		vehicleClass="GulfWar_Iraqi";
		icon="iconMan";
		nakedUniform="U_BasicBody";
		uniformClass="MNP_CombatUniform_NKR_Rg";
		backpack="";
		linkedItems[]=
		{
        "V_sud_ussr_vest05",
		"SP_M1Helmet_GrayDim"
		};
		respawnLinkedItems[]=
		{
        "V_sud_ussr_vest05"
		};
		weapons[]=
		{
		"Throw",
		"Put",	
		"CUP_arifle_RPK74",
		"CUP_hgun_Makarov"
		};
		respawnweapons[]=
		{
		"Throw",
		"Put",	
		"CUP_arifle_AK74",
		"CUP_hgun_Makarov"
		};
		magazines[]=
		{
		"CUP_45Rnd_TE4_LRT4_Green_Tracer_545x39_RPK_M",
		"CUP_45Rnd_TE4_LRT4_Green_Tracer_545x39_RPK_M",	
		"CUP_45Rnd_TE4_LRT4_Green_Tracer_545x39_RPK_M",
		"CUP_45Rnd_TE4_LRT4_Green_Tracer_545x39_RPK_M",
		"CUP_8Rnd_9x18_Makarov_M",
		"CUP_HandGrenade_RGO",
		"CUP_HandGrenade_RGO",
		"SmokeShell",
		"SmokeShell"
		};
		Respawnmagazines[]=
		{
		"CUP_45Rnd_TE4_LRT4_Green_Tracer_545x39_RPK_M",
		"CUP_45Rnd_TE4_LRT4_Green_Tracer_545x39_RPK_M",	
		"CUP_45Rnd_TE4_LRT4_Green_Tracer_545x39_RPK_M",
		"CUP_45Rnd_TE4_LRT4_Green_Tracer_545x39_RPK_M",
		"CUP_8Rnd_9x18_Makarov_M",
		"CUP_HandGrenade_RGO",
		"CUP_HandGrenade_RGO",
		"SmokeShell",
		"SmokeShell"
		};
		Items[]=
		{
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_morphine",
		"ACE_morphine",
		"ACE_EarPlugs"
		};
		respawntems[]=
		{
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_morphine",
		"ACE_morphine",
		"ACE_EarPlugs"
		};
	};

	class GulfWar_Iraqi_MGAssistant: O_Soldier_base_F
	{
		_generalMacro="GulfWar_Iraqi_MachinegunnerAssistant";
		scope=2;
		displayName="MG Assistant";
		faction="Iraqi_units";
		vehicleClass="GulfWar_Iraqi";
		icon="iconMan";
		nakedUniform="U_BasicBody";
		uniformClass="MNP_CombatUniform_NKR_Rg";
		backpack="";
		linkedItems[]=
		{
        "V_sud_ussr_vest05",
		"SP_M1Helmet_GrayDim"
		};
		respawnLinkedItems[]=
		{
        "V_sud_ussr_vest05"
		};
		weapons[]=
		{
		"Throw",
		"Put",	
		"CUP_arifle_AK74",
		"CUP_hgun_Makarov"
		};
		respawnweapons[]=
		{
		"Throw",
		"Put",	
		"CUP_arifle_AK74",
		"CUP_hgun_Makarov"
		};
		magazines[]=
		{
		"CUP_30Rnd_545x39_AK_M",
		"CUP_30Rnd_545x39_AK_M",
		"CUP_30Rnd_545x39_AK_M",
		"CUP_30Rnd_545x39_AK_M",
		"CUP_45Rnd_TE4_LRT4_Green_Tracer_545x39_RPK_M",
		"CUP_45Rnd_TE4_LRT4_Green_Tracer_545x39_RPK_M",
		"CUP_8Rnd_9x18_Makarov_M",
		"CUP_HandGrenade_RGO",
		"CUP_HandGrenade_RGO",
		"SmokeShell",
		"SmokeShell"
		};
		Respawnmagazines[]=
		{
		"CUP_30Rnd_545x39_AK_M",
		"CUP_30Rnd_545x39_AK_M",
		"CUP_30Rnd_545x39_AK_M",
		"CUP_30Rnd_545x39_AK_M",
		"CUP_45Rnd_TE4_LRT4_Green_Tracer_545x39_RPK_M",
		"CUP_45Rnd_TE4_LRT4_Green_Tracer_545x39_RPK_M",
		"CUP_8Rnd_9x18_Makarov_M",
		"CUP_HandGrenade_RGO",
		"CUP_HandGrenade_RGO",
		"SmokeShell",
		"SmokeShell"
		};
		Items[]=
		{
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_morphine",
		"ACE_morphine",
		"ACE_EarPlugs"
		};
		respawntems[]=
		{
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_morphine",
		"ACE_morphine",
		"ACE_EarPlugs"
		};
	};
/***************************************************
*                      Cold War                    *
*                      Argentina                   *
***************************************************/
	class Cold_War_Argentinian_Squadleader: I_Soldier_F
	{
		_generalMacro="Cold_War_Argentinian_Squadleader";
		scope=2;
		displayName="Section Leader";
		faction="argentinian_units";
		vehicleClass="Cold_War_Argentinian";
		icon="iconManLeader";
		nakedUniform="U_BasicBody";
		uniformClass="MNP_CombatUniform_OD_Rg";
		backpack="B_mas_m_Bergen_al";
		linkedItems[]=
		{
        "V_sud_nato_vest01",
		"SP_M1Helmet_Green",
		"ItemMap",
		"ItemCompass",
		"ACRE_PRC343",
		"Binocular"
		};
		respawnLinkedItems[]=
		{
        "V_sud_nato_vest01",
		"ItemMap",
		"ItemCompass",
		"ACRE_PRC343"
		};
		weapons[]=
		{
		"Throw",
		"Put",
		"CUP_arifle_FNFAL",
		"hgun_mas_bhp_F"
		};
		respawnweapons[]=
		{
		"Throw",
		"Put",
		"CUP_arifle_FNFAL",
		"hgun_mas_bhp_F"
		};
		magazines[]=
		{
		"15Rnd_mas_9x21_Mag",
		"15Rnd_mas_9x21_Mag",
		"15Rnd_mas_9x21_Mag",
		"CUP_20Rnd_762x51_FNFAL_M",
		"CUP_20Rnd_762x51_FNFAL_M",
		"CUP_20Rnd_762x51_FNFAL_M",
		"CUP_20Rnd_762x51_FNFAL_M",
		"CUP_20Rnd_762x51_FNFAL_M",
		"CUP_HandGrenade_M67",
		"CUP_HandGrenade_M67"
		};
		Respawnmagazines[]=
		{
		"15Rnd_mas_9x21_Mag",
		"15Rnd_mas_9x21_Mag",
		"15Rnd_mas_9x21_Mag",
		"CUP_20Rnd_762x51_FNFAL_M",
		"CUP_20Rnd_762x51_FNFAL_M",
		"CUP_20Rnd_762x51_FNFAL_M",
		"CUP_20Rnd_762x51_FNFAL_M",
		"CUP_20Rnd_762x51_FNFAL_M",
		"CUP_HandGrenade_M67",
		"CUP_HandGrenade_M67"
		};
		Items[]=
		{
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_morphine",
		"ACE_morphine",
		"ACE_EarPlugs"	
		};
		respawntems[]=
		{
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_morphine",
		"ACE_morphine",
		"ACE_EarPlugs"			
		};
	};
	
	class Cold_War_Argentinian_Rifleman: I_Soldier_F
	{
		_generalMacro="Cold_War_Argentinian_Rifleman";
		scope=2;
		displayName="Rifleman";
		faction="argentinian_units";
		vehicleClass="Cold_War_Argentinian";
		icon="iconMan";
		nakedUniform="U_BasicBody";
		uniformClass="MNP_CombatUniform_OD_Rg";
		backpack="B_mas_m_Bergen_al";
		linkedItems[]=
		{
        "V_sud_nato_vest01",
		"SP_M1Helmet_Green",
		"ItemCompass"
		};
		respawnLinkedItems[]=
		{
        "V_sud_nato_vest01",
		"ItemCompass"
		};
		weapons[]=
		{
		"Throw",
		"Put",	
		"CUP_arifle_FNFAL"
		};
		respawnweapons[]=
		{
		"Throw",
		"Put",	
		"CUP_arifle_FNFAL",
		"hgun_mas_bhp_F"
		};
		magazines[]=
		{
		"15Rnd_mas_9x21_Mag",
		"15Rnd_mas_9x21_Mag",
		"15Rnd_mas_9x21_Mag",
		"CUP_20Rnd_762x51_FNFAL_M",
		"CUP_20Rnd_762x51_FNFAL_M",
		"CUP_20Rnd_762x51_FNFAL_M",
		"CUP_20Rnd_762x51_FNFAL_M",
		"CUP_20Rnd_762x51_FNFAL_M",
		"CUP_20Rnd_762x51_FNFAL_M",
		"CUP_20Rnd_762x51_FNFAL_M",
		"CUP_20Rnd_762x51_FNFAL_M",
		"CUP_20Rnd_762x51_FNFAL_M",
		"CUP_20Rnd_762x51_FNFAL_M",
		"CUP_20Rnd_762x51_FNFAL_M",
		"CUP_HandGrenade_M67",
		"CUP_HandGrenade_M67",
		"SmokeShell",
		"SmokeShell"
		};
		Respawnmagazines[]=
		{
		"15Rnd_mas_9x21_Mag",
		"15Rnd_mas_9x21_Mag",
		"15Rnd_mas_9x21_Mag",
		"CUP_20Rnd_762x51_FNFAL_M",
		"CUP_20Rnd_762x51_FNFAL_M",
		"CUP_20Rnd_762x51_FNFAL_M",
		"CUP_20Rnd_762x51_FNFAL_M",
		"CUP_20Rnd_762x51_FNFAL_M",
		"CUP_HandGrenade_M67",
		"CUP_HandGrenade_M67",
		"SmokeShell",
		"SmokeShell"
		};
		Items[]=
		{
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_morphine",
		"ACE_morphine"
		};
		respawntems[]=
		{
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_morphine",
		"ACE_morphine"
		};		
	};

	class Cold_War_Argentinian_AT_Rifleman: I_Soldier_F
	{
		_generalMacro="Cold_War_Argentinian_AT_Rifleman";
		scope=2;
		displayName="AT Rifleman";
		faction="argentinian_units";
		vehicleClass="Cold_War_Argentinian";
		icon="iconManExplosive";
		nakedUniform="U_BasicBody";
		uniformClass="MNP_CombatUniform_OD_Rg";
		backpack="B_mas_m_Bergen_al";
		linkedItems[]=
		{
        "V_sud_nato_vest01",
		"SP_M1Helmet_Green",
		"ItemCompass"
		};
		respawnLinkedItems[]=
		{
        "V_sud_nato_vest01",
		"ItemMap",
		"ItemCompass"
		};
		weapons[]=
		{
		"Throw",
		"Put",
		"CUP_arifle_FNFAL",
		"mas_launch_maaws_F",
		"hgun_mas_bhp_F"
		};
		respawnweapons[]=
		{
		"Throw",
		"Put",	
		"CUP_arifle_FNFAL",
		"mas_launch_maaws_F"
		};
		magazines[]=
		{
		"15Rnd_mas_9x21_Mag",
		"15Rnd_mas_9x21_Mag",
		"15Rnd_mas_9x21_Mag",
		"CUP_20Rnd_762x51_FNFAL_M",
		"CUP_20Rnd_762x51_FNFAL_M",		
		"CUP_20Rnd_762x51_FNFAL_M",
		"CUP_20Rnd_762x51_FNFAL_M",
		"CUP_20Rnd_762x51_FNFAL_M",
		"CUP_HandGrenade_M67",
		"CUP_HandGrenade_M67",
		"SmokeShell",
		"SmokeShell",
		"mas_MAAWS_HE",
		"mas_MAAWS_HE",
		"mas_MAAWS_HE",
		"mas_MAAWS_HE"
		};
		Respawnmagazines[]=
		{
		"15Rnd_mas_9x21_Mag",
		"15Rnd_mas_9x21_Mag",
		"15Rnd_mas_9x21_Mag",
		"CUP_20Rnd_762x51_FNFAL_M",
		"CUP_20Rnd_762x51_FNFAL_M",		
		"CUP_20Rnd_762x51_FNFAL_M",
		"CUP_20Rnd_762x51_FNFAL_M",
		"CUP_20Rnd_762x51_FNFAL_M",
		"CUP_HandGrenade_M67",
		"CUP_HandGrenade_M67",
		"SmokeShell",
		"SmokeShell",
        "mas_MAAWS_HE",
		"mas_MAAWS_HE",
		"mas_MAAWS_HE",
		"mas_MAAWS_HE"
		};
		Items[]=
		{
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_morphine",
		"ACE_morphine"
		};
		respawntems[]=
		{
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_morphine",
		"ACE_morphine"
		};
	};

	class Cold_War_Argentinian_AT_Assistant: I_Soldier_F
	{
		_generalMacro="Cold_War_Argentinian_AT_Assistant";
		scope=2;
		displayName="AT Assistant";
		faction="argentinian_units";
		vehicleClass="Cold_War_Argentinian";
		icon="iconManMG";
		nakedUniform="U_BasicBody";
		uniformClass="MNP_CombatUniform_OD_Rg";
		backpack="B_mas_m_Bergen_al";
		linkedItems[]=
		{
        "V_sud_nato_vest01",
		"SP_M1Helmet_Green",
		"ItemCompass"
		};
		respawnLinkedItems[]=
		{
        "V_sud_nato_vest01",
		"ItemMap",
		"ItemCompass"
		};
		weapons[]=
		{
		"Throw",
		"Put",
		"CUP_arifle_FNFAL",
		"hgun_mas_bhp_F"
		};
		respawnweapons[]=
		{
		"Throw",
		"Put",	
		"CUP_arifle_FNFAL"
		};
		magazines[]=
		{
		"15Rnd_mas_9x21_Mag",
		"15Rnd_mas_9x21_Mag",
		"15Rnd_mas_9x21_Mag",
		"CUP_20Rnd_762x51_FNFAL_M",
		"CUP_20Rnd_762x51_FNFAL_M",
		"CUP_20Rnd_762x51_FNFAL_M",
		"CUP_20Rnd_762x51_FNFAL_M",
		"CUP_20Rnd_762x51_FNFAL_M",
		"CUP_HandGrenade_M67",
		"CUP_HandGrenade_M67",
		"SmokeShell",
		"SmokeShell",
		"mas_MAAWS_HE",
		"mas_MAAWS_HE",
		"mas_MAAWS_HE",
		"mas_MAAWS_HE"
		};
		Respawnmagazines[]=
		{
		"15Rnd_mas_9x21_Mag",
		"15Rnd_mas_9x21_Mag",
		"15Rnd_mas_9x21_Mag",
		"CUP_20Rnd_762x51_FNFAL_M",
		"CUP_20Rnd_762x51_FNFAL_M",
		"CUP_20Rnd_762x51_FNFAL_M",
		"CUP_20Rnd_762x51_FNFAL_M",
		"CUP_20Rnd_762x51_FNFAL_M",
		"CUP_HandGrenade_M67",
		"CUP_HandGrenade_M67",
		"SmokeShell",
		"SmokeShell",
		"SmokeShell"
		};
		Items[]=
		{
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_morphine",
		"ACE_morphine"
		};
		respawntems[]=
		{
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_morphine",
		"ACE_morphine"	
		};
	};

	class Cold_War_Argentinian_AA: I_Soldier_F
	{
		_generalMacro="Cold_War_Argentinian_AA";
		scope=2;
		displayName="AA Rifleman";
		faction="argentinian_units";
		vehicleClass="Cold_War_Argentinian";
		icon="iconMan";
		nakedUniform="U_BasicBody";
		uniformClass="MNP_CombatUniform_OD_Rg";
		backpack="B_mas_m_Bergen_al";
		linkedItems[]=
		{
        "V_sud_nato_vest01",
		"SP_M1Helmet_Green",
		"ItemCompass"
		};
		respawnLinkedItems[]=
		{
        "V_sud_nato_vest01",
		"ItemMap",
		"ItemCompass"
		};
		weapons[]=
		{
		"Throw",
		"Put",	
		"CUP_arifle_FNFAL",
		"rhs_weap_fim92",
		"hgun_mas_bhp_F"
		};
		respawnweapons[]=
		{
		"Throw",
		"Put",	
		"CUP_arifle_FNFAL",
		"rhs_weap_fim92"
		};
		magazines[]=
		{
		"15Rnd_mas_9x21_Mag",
		"15Rnd_mas_9x21_Mag",
		"15Rnd_mas_9x21_Mag",
		"CUP_20Rnd_762x51_FNFAL_M",
		"CUP_20Rnd_762x51_FNFAL_M",		
		"CUP_20Rnd_762x51_FNFAL_M",
		"CUP_20Rnd_762x51_FNFAL_M",
		"CUP_20Rnd_762x51_FNFAL_M",
		"CUP_20Rnd_762x51_FNFAL_M",
		"CUP_HandGrenade_M67",
		"CUP_HandGrenade_M67",
		"SmokeShell",
		"SmokeShell",
		"rhs_fim92_mag",
		"rhs_fim92_mag"
		};
		Respawnmagazines[]=
		{
		"15Rnd_mas_9x21_Mag",
		"15Rnd_mas_9x21_Mag",
		"15Rnd_mas_9x21_Mag",
		"CUP_20Rnd_762x51_FNFAL_M",
		"CUP_20Rnd_762x51_FNFAL_M",		
		"CUP_20Rnd_762x51_FNFAL_M",
		"CUP_20Rnd_762x51_FNFAL_M",
		"CUP_20Rnd_762x51_FNFAL_M",
		"CUP_20Rnd_762x51_FNFAL_M",
		"CUP_HandGrenade_M67",
		"CUP_HandGrenade_M67",
		"SmokeShell",
		"SmokeShell",
		"rhs_fim92_mag",
		"rhs_fim92_mag",
		"rhs_fim92_mag"
		};
		Items[]=
		{
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_morphine",
		"ACE_morphine"
		};
		respawntems[]=
		{
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_morphine",
		"ACE_morphine"
		};
	};

	class Cold_War_Argentinian_AA_Assistant: I_Soldier_F
	{
		_generalMacro="Cold_War_Argentinian_AA_Assistant";
		scope=2;
		displayName="AA Assistant";
		faction="argentinian_units";
		vehicleClass="Cold_War_Argentinian";
		icon="iconMan";
		nakedUniform="U_BasicBody";
		uniformClass="MNP_CombatUniform_OD_Rg";
		backpack="B_mas_m_Bergen_al";
		linkedItems[]=
		{
        "V_sud_nato_vest01",
		"SP_M1Helmet_Green",
		"ItemCompass"
		};
		respawnLinkedItems[]=
		{
        "V_sud_nato_vest01",
		"ItemCompass"
		};
		weapons[]=
		{
		"Throw",
		"Put",	
		"CUP_arifle_FNFAL",
		"hgun_mas_bhp_F"
		};
		respawnweapons[]=
		{
		"Throw",
		"Put",
		"CUP_arifle_FNFAL"
		};
		magazines[]=
		{
		"15Rnd_mas_9x21_Mag",
		"15Rnd_mas_9x21_Mag",
		"15Rnd_mas_9x21_Mag",
		"CUP_HandGrenade_M67",
		"CUP_HandGrenade_M67",
		"CUP_20Rnd_762x51_FNFAL_M",
		"CUP_20Rnd_762x51_FNFAL_M",
		"CUP_20Rnd_762x51_FNFAL_M",
		"CUP_20Rnd_762x51_FNFAL_M",
		"CUP_20Rnd_762x51_FNFAL_M",
		"SmokeShell",
		"SmokeShell",
		"rhs_fim92_mag",
		"rhs_fim92_mag",
		"rhs_fim92_mag"
		};
		Respawnmagazines[]=
		{
		"15Rnd_mas_9x21_Mag",
		"15Rnd_mas_9x21_Mag",
		"15Rnd_mas_9x21_Mag",
		"CUP_HandGrenade_M67",
		"CUP_HandGrenade_M67",
		"CUP_20Rnd_762x51_FNFAL_M",
		"CUP_20Rnd_762x51_FNFAL_M",
		"CUP_20Rnd_762x51_FNFAL_M",
		"CUP_20Rnd_762x51_FNFAL_M",
		"CUP_20Rnd_762x51_FNFAL_M",
		"SmokeShell",
		"SmokeShell",
		"rhs_fim92_mag",
		"rhs_fim92_mag",
		"rhs_fim92_mag"
		};
		Items[]=
		{
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_morphine",
		"ACE_morphine"
		};
		respawntems[]=
		{
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_morphine",
		"ACE_morphine"
		};
	};

	class Cold_War_Argentinian_Machinegunner: I_Soldier_F
	{
		_generalMacro="Cold_War_Argentinian_Machinegunner";
		scope=2;
		displayName="Machinegunner";
		faction="argentinian_units";
		vehicleClass="Cold_War_Argentinian";
		icon="iconMan";
		nakedUniform="U_BasicBody";
		uniformClass="MNP_CombatUniform_OD_Rg";
		backpack="B_mas_m_Bergen_al";
		linkedItems[]=
		{
        "V_sud_nato_vest01",
		"SP_M1Helmet_Green",
		"ItemCompass"
		};
		respawnLinkedItems[]=
		{
        "V_sud_nato_vest01",
		"ItemCompass"
		};
		weapons[]=
		{
		"Throw",
		"Put",	
		"CUP_lmg_L7A2",
		"hgun_mas_bhp_F"
		};
		respawnweapons[]=
		{
		"Throw",
		"Put",	
		"CUP_lmg_L7A2"
		};
		magazines[]=
		{
		"15Rnd_mas_9x21_Mag",
		"15Rnd_mas_9x21_Mag",
		"15Rnd_mas_9x21_Mag",
		"CUP_100Rnd_TE4_LRT4_White_Tracer_762x51_Belt_M",
		"CUP_100Rnd_TE4_LRT4_White_Tracer_762x51_Belt_M",
		"CUP_100Rnd_TE4_LRT4_White_Tracer_762x51_Belt_M",
		"CUP_100Rnd_TE4_LRT4_White_Tracer_762x51_Belt_M",
		"CUP_HandGrenade_M67",
		"CUP_HandGrenade_M67",
		"SmokeShell",
		"SmokeShell"
		};
		Respawnmagazines[]=
		{
		"15Rnd_mas_9x21_Mag",
		"15Rnd_mas_9x21_Mag",
		"15Rnd_mas_9x21_Mag",
		"CUP_100Rnd_TE4_LRT4_White_Tracer_762x51_Belt_M",
		"CUP_100Rnd_TE4_LRT4_White_Tracer_762x51_Belt_M",
		"CUP_100Rnd_TE4_LRT4_White_Tracer_762x51_Belt_M",
		"CUP_100Rnd_TE4_LRT4_White_Tracer_762x51_Belt_M",
		"CUP_100Rnd_TE4_LRT4_White_Tracer_762x51_Belt_M",
		"CUP_100Rnd_TE4_LRT4_White_Tracer_762x51_Belt_M",
		"CUP_100Rnd_TE4_LRT4_White_Tracer_762x51_Belt_M",
		"CUP_HandGrenade_M67",
		"CUP_HandGrenade_M67",
		"SmokeShell",
		"SmokeShell"
		};
		Items[]=
		{
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_morphine",
		"ACE_morphine"
		};
		respawntems[]=
		{
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_morphine",
		"ACE_morphine"		
		};		
	};
		class Cold_War_Argentinian_MG_Assistant: I_Soldier_F
	{
		_generalMacro="Cold_War_Argentinian_MG_Assistant";
		scope=2;
		displayName="MG Assistant";
		faction="argentinian_units";
		vehicleClass="Cold_War_Argentinian";
		icon="iconMan";
		nakedUniform="U_BasicBody";
		uniformClass="MNP_CombatUniform_OD_Rg";
		backpack="B_mas_m_Bergen_al";
		linkedItems[]=
		{
        "V_sud_nato_vest01",
		"SP_M1Helmet_Green",
		"ItemCompass"
		};
		respawnLinkedItems[]=
		{
        "V_sud_nato_vest01",
		"ItemCompass"
		};
		weapons[]=
		{
		"Throw",
		"Put",	
		"CUP_arifle_FNFAL",
		"hgun_mas_bhp_F"
		};
		respawnweapons[]=
		{
		"Throw",
		"Put",
		"CUP_arifle_FNFAL"
		};
		magazines[]=
		{
		"15Rnd_mas_9x21_Mag",
		"15Rnd_mas_9x21_Mag",
		"15Rnd_mas_9x21_Mag",
		"CUP_HandGrenade_M67",
		"CUP_HandGrenade_M67",
		"CUP_20Rnd_762x51_FNFAL_M",
		"CUP_20Rnd_762x51_FNFAL_M",
		"CUP_20Rnd_762x51_FNFAL_M",
		"CUP_20Rnd_762x51_FNFAL_M",
		"CUP_20Rnd_762x51_FNFAL_M",
		"SmokeShell",
		"SmokeShell",
		"CUP_100Rnd_TE4_LRT4_White_Tracer_762x51_Belt_M",
		"CUP_100Rnd_TE4_LRT4_White_Tracer_762x51_Belt_M",
		"CUP_100Rnd_TE4_LRT4_White_Tracer_762x51_Belt_M"
		};
		Respawnmagazines[]=
		{
		"15Rnd_mas_9x21_Mag",
		"15Rnd_mas_9x21_Mag",
		"15Rnd_mas_9x21_Mag",
		"CUP_HandGrenade_M67",
		"CUP_HandGrenade_M67",
		"CUP_20Rnd_762x51_FNFAL_M",
		"CUP_20Rnd_762x51_FNFAL_M",
		"CUP_20Rnd_762x51_FNFAL_M",
		"CUP_20Rnd_762x51_FNFAL_M",
		"CUP_20Rnd_762x51_FNFAL_M",
		"SmokeShell",
		"SmokeShell",
		"CUP_100Rnd_TE4_LRT4_White_Tracer_762x51_Belt_M",
		"CUP_100Rnd_TE4_LRT4_White_Tracer_762x51_Belt_M",
		"CUP_100Rnd_TE4_LRT4_White_Tracer_762x51_Belt_M"
		};
		Items[]=
		{
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_morphine",
		"ACE_morphine"
		};
		respawntems[]=
		{
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_morphine",
		"ACE_morphine"
		};
	};

};