	class GulfWar_Iraqi_Squadleader: O_Soldier_base_F
	{
		_generalMacro="GulfWar_Iraqi_Squadleader";
		scope=2;
		displayName="Section Leader";
		faction="Iraqi_units";
		vehicleClass="GulfWar_Iraqi";
		icon="iconManLeader";
		nakedUniform="U_BasicBody";
		uniformClass="MNP_CombatUniform_NKR_Rg";
		backpack="";
		linkedItems[]=
		{
        "V_sud_ussr_vest05",
		"SP_M1Helmet_GrayDim",
		"ItemMap",
		"ItemCompass",
		"ItemWatch"
		};
		respawnLinkedItems[]=
		{
        "V_sud_ussr_vest05",
		"ItemMap",
		"ItemCompass",
		"ItemWatch"
		};
		weapons[]=
		{
		"Throw",
		"Put",
		"Binocular",
		"CUP_arifle_AK74",
		"CUP_hgun_Makarov"
		};
		respawnweapons[]=
		{
		"Throw",
		"Put",
		"Binocular",
		"CUP_arifle_AK74",
		"CUP_hgun_Makarov"
		};
		magazines[]=
		{
		"CUP_30Rnd_545x39_AK_M",
		"CUP_30Rnd_545x39_AK_M",
		"CUP_30Rnd_545x39_AK_M",
	    "CUP_30Rnd_545x39_AK_M",
	    "CUP_30Rnd_545x39_AK_M",
		"CUP_30Rnd_545x39_AK_M",
		"CUP_30Rnd_545x39_AK_M",
		"CUP_30Rnd_545x39_AK_M",
		"CUP_8Rnd_9x18_Makarov_M",
		"CUP_HandGrenade_RGO",
		"CUP_HandGrenade_RGO"
		};
		Respawnmagazines[]=
		{
		"CUP_30Rnd_545x39_AK_M",
		"CUP_30Rnd_545x39_AK_M",
		"CUP_30Rnd_545x39_AK_M",
	    "CUP_30Rnd_545x39_AK_M",
	    "CUP_30Rnd_545x39_AK_M",
		"CUP_30Rnd_545x39_AK_M",
		"CUP_30Rnd_545x39_AK_M",
		"CUP_30Rnd_545x39_AK_M",
		"CUP_8Rnd_9x18_Makarov_M",
		"CUP_HandGrenade_RGO",
		"CUP_HandGrenade_RGO"
		};
		Items[]=
		{
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_morphine",
		"ACE_morphine",
		"ACE_EarPlugs"	
		};
		respawntems[]=
		{
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_morphine",
		"ACE_morphine",
		"ACE_EarPlugs"			
		};
	};
	
	class GulfWar_Iraqi_Rifleman: O_Soldier_base_F
	{
		_generalMacro="GulfWar_Iraqi_Rifleman";
		scope=2;
		displayName="Rifleman";
		faction="Iraqi_units";
		vehicleClass="GulfWar_Iraqi";
		icon="iconMan";
		nakedUniform="U_BasicBody";
		uniformClass="MNP_CombatUniform_NKR_Rg";
		backpack="";
		linkedItems[]=
		{
        "V_sud_ussr_vest05",
		"SP_M1Helmet_GrayDim"
		};
		respawnLinkedItems[]=
		{
        "V_sud_ussr_vest05"
		};
		weapons[]=
		{
		"Throw",
		"Put",	
		"CUP_arifle_AK74",
		"CUP_hgun_Makarov"
		};
		respawnweapons[]=
		{
		"Throw",
		"Put",	
		"CUP_arifle_AK74",
		"CUP_hgun_Makarov"
		};
		magazines[]=
		{
		"CUP_30Rnd_545x39_AK_M",
		"CUP_30Rnd_545x39_AK_M",
		"CUP_30Rnd_545x39_AK_M",
		"CUP_30Rnd_545x39_AK_M",
		"CUP_30Rnd_545x39_AK_M",
		"CUP_30Rnd_545x39_AK_M",
		"CUP_30Rnd_545x39_AK_M",
		"CUP_30Rnd_545x39_AK_M",
		"CUP_8Rnd_9x18_Makarov_M",
		"CUP_HandGrenade_RGO",
		"CUP_HandGrenade_RGO",
		"SmokeShell",
		"SmokeShell"
		};
		Respawnmagazines[]=
		{
		"CUP_30Rnd_545x39_AK_M",
		"CUP_30Rnd_545x39_AK_M",
		"CUP_30Rnd_545x39_AK_M",
		"CUP_30Rnd_545x39_AK_M",
		"CUP_30Rnd_545x39_AK_M",
		"CUP_30Rnd_545x39_AK_M",
		"CUP_30Rnd_545x39_AK_M",
		"CUP_30Rnd_545x39_AK_M",
		"CUP_8Rnd_9x18_Makarov_M",
		"CUP_HandGrenade_RGO",
		"CUP_HandGrenade_RGO",
		"SmokeShell",
		"SmokeShell"
		};
		Items[]=
		{
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_morphine",
		"ACE_morphine",
		"ACE_EarPlugs"
		};
		respawntems[]=
		{
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_morphine",
		"ACE_morphine",
		"ACE_EarPlugs"	
		};		
	};

	class GulfWar_Iraqi_RPG: O_Soldier_base_F
	{
		_generalMacro="GulfWar_Iraqi_RPG";
		scope=2;
		displayName="RPG Gunner";
		faction="Iraqi_units";
		vehicleClass="GulfWar_Iraqi";
		icon="iconManExplosive";
		nakedUniform="U_BasicBody";
		uniformClass="MNP_CombatUniform_NKR_Rg";
		backpack="B_mas_m_Bergen_rpg";
		linkedItems[]=
		{
        "V_sud_ussr_vest05",
		"SP_M1Helmet_GrayDim"
		};
		respawnLinkedItems[]=
		{
        "V_sud_ussr_vest05"
		};
		weapons[]=
		{
		"Throw",
		"Put",
		"CUP_arifle_AK74",
		"CUP_hgun_Makarov",
		"CUP_launch_RPG7V"
		};
		respawnweapons[]=
		{
		"Throw",
		"Put",
		"CUP_arifle_AK74",
		"CUP_hgun_Makarov",
		"CUP_launch_RPG7V"
		};
		magazines[]=
		{
		"CUP_30Rnd_545x39_AK_M",
		"CUP_30Rnd_545x39_AK_M",		
		"CUP_30Rnd_545x39_AK_M",
		"CUP_30Rnd_545x39_AK_M",
		"CUP_30Rnd_545x39_AK_M",
		"CUP_30Rnd_545x39_AK_M",	
		"CUP_30Rnd_545x39_AK_M",	
		"CUP_30Rnd_545x39_AK_M",
		"CUP_8Rnd_9x18_Makarov_M",
		"CUP_PG7V_M",
		"CUP_PG7V_M",
		"CUP_PG7V_M",
		"CUP_PG7V_M",
		"CUP_HandGrenade_RGO",
		"CUP_HandGrenade_RGO",
		"SmokeShell",
		"SmokeShell"
		};
		Respawnmagazines[]=
		{
		"CUP_30Rnd_545x39_AK_M",
		"CUP_30Rnd_545x39_AK_M",		
		"CUP_30Rnd_545x39_AK_M",
		"CUP_30Rnd_545x39_AK_M",
		"CUP_30Rnd_545x39_AK_M",
		"CUP_30Rnd_545x39_AK_M",	
		"CUP_30Rnd_545x39_AK_M",	
		"CUP_30Rnd_545x39_AK_M",
		"CUP_8Rnd_9x18_Makarov_M",
		"CUP_HandGrenade_RGO",
		"CUP_HandGrenade_RGO",
		"SmokeShell",
		"SmokeShell"
		};
		Items[]=
		{
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_morphine",
		"ACE_morphine",
		"ACE_EarPlugs"
		};
		respawntems[]=
		{
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_morphine",
		"ACE_morphine",
		"ACE_EarPlugs"	
		};
	};

	class GulfWar_Iraqi_RPGAssistant: O_Soldier_base_F
	{
		_generalMacro="GulfWar_Iraqi_RPGAssistant";
		scope=2;
		displayName="RPG Assistant";
		faction="Iraqi_units";
		vehicleClass="GulfWar_Iraqi";
		icon="iconManMG";
		nakedUniform="U_BasicBody";
		uniformClass="MNP_CombatUniform_NKR_Rg";
		backpack="B_SUD_RPG";
		linkedItems[]=
		{
        "V_sud_ussr_vest05",
		"SP_M1Helmet_GrayDim"
		};
		respawnLinkedItems[]=
		{
        "V_sud_ussr_vest05"
		};
		weapons[]=
		{
		"Throw",
		"Put",
		"CUP_arifle_AK74",
		"CUP_hgun_Makarov"
		};
		respawnweapons[]=
		{
		"Throw",
		"Put",
		"CUP_arifle_AK74",
		"CUP_hgun_Makarov"
		};
		magazines[]=
		{
		"CUP_30Rnd_545x39_AK_M",
		"CUP_30Rnd_545x39_AK_M",
		"CUP_30Rnd_545x39_AK_M",
		"CUP_30Rnd_545x39_AK_M",
		"CUP_30Rnd_545x39_AK_M",
		"CUP_30Rnd_545x39_AK_M",
		"CUP_30Rnd_545x39_AK_M",
		"CUP_30Rnd_545x39_AK_M",
		"CUP_8Rnd_9x18_Makarov_M",
		"SUD_PG7VL",
		"SUD_PG7VL",
		"SUD_PG7VL",
		"CUP_HandGrenade_RGO",
		"CUP_HandGrenade_RGO",
		"SmokeShell",
		"SmokeShell"
		};
		Respawnmagazines[]=
		{
		"CUP_30Rnd_545x39_AK_M",
		"CUP_30Rnd_545x39_AK_M",
		"CUP_30Rnd_545x39_AK_M",
		"CUP_30Rnd_545x39_AK_M",
		"CUP_30Rnd_545x39_AK_M",
		"CUP_30Rnd_545x39_AK_M",
		"CUP_30Rnd_545x39_AK_M",
		"CUP_30Rnd_545x39_AK_M",
		"CUP_8Rnd_9x18_Makarov_M",
		"CUP_HandGrenade_RGO",
		"CUP_HandGrenade_RGO",
		"SmokeShell",
		"SmokeShell"
		};
		Items[]=
		{
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_morphine",
		"ACE_morphine",
		"ACE_EarPlugs"
		};
		respawntems[]=
		{
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_morphine",
		"ACE_morphine",
		"ACE_EarPlugs"		
		};
	};

	class GulfWar_Iraqi_MG: O_Soldier_base_F
	{
		_generalMacro="GulfWar_Iraqi_MG";
		scope=2;
		displayName="Machinegunner";
		faction="Iraqi_units";
		vehicleClass="GulfWar_Iraqi";
		icon="iconMan";
		nakedUniform="U_BasicBody";
		uniformClass="MNP_CombatUniform_NKR_Rg";
		backpack="";
		linkedItems[]=
		{
        "V_sud_ussr_vest05",
		"SP_M1Helmet_GrayDim"
		};
		respawnLinkedItems[]=
		{
        "V_sud_ussr_vest05"
		};
		weapons[]=
		{
		"Throw",
		"Put",	
		"CUP_arifle_RPK74",
		"CUP_hgun_Makarov"
		};
		respawnweapons[]=
		{
		"Throw",
		"Put",	
		"CUP_arifle_AK74",
		"CUP_hgun_Makarov"
		};
		magazines[]=
		{
		"CUP_45Rnd_TE4_LRT4_Green_Tracer_545x39_RPK_M",
		"CUP_45Rnd_TE4_LRT4_Green_Tracer_545x39_RPK_M",	
		"CUP_45Rnd_TE4_LRT4_Green_Tracer_545x39_RPK_M",
		"CUP_45Rnd_TE4_LRT4_Green_Tracer_545x39_RPK_M",
		"CUP_8Rnd_9x18_Makarov_M",
		"CUP_HandGrenade_RGO",
		"CUP_HandGrenade_RGO",
		"SmokeShell",
		"SmokeShell"
		};
		Respawnmagazines[]=
		{
		"CUP_45Rnd_TE4_LRT4_Green_Tracer_545x39_RPK_M",
		"CUP_45Rnd_TE4_LRT4_Green_Tracer_545x39_RPK_M",	
		"CUP_45Rnd_TE4_LRT4_Green_Tracer_545x39_RPK_M",
		"CUP_45Rnd_TE4_LRT4_Green_Tracer_545x39_RPK_M",
		"CUP_8Rnd_9x18_Makarov_M",
		"CUP_HandGrenade_RGO",
		"CUP_HandGrenade_RGO",
		"SmokeShell",
		"SmokeShell"
		};
		Items[]=
		{
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_morphine",
		"ACE_morphine",
		"ACE_EarPlugs"
		};
		respawntems[]=
		{
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_morphine",
		"ACE_morphine",
		"ACE_EarPlugs"
		};
	};

	class GulfWar_Iraqi_MGAssistant: O_Soldier_base_F
	{
		_generalMacro="GulfWar_Iraqi_MachinegunnerAssistant";
		scope=2;
		displayName="MG Assistant";
		faction="Iraqi_units";
		vehicleClass="GulfWar_Iraqi";
		icon="iconMan";
		nakedUniform="U_BasicBody";
		uniformClass="MNP_CombatUniform_NKR_Rg";
		backpack="";
		linkedItems[]=
		{
        "V_sud_ussr_vest05",
		"SP_M1Helmet_GrayDim"
		};
		respawnLinkedItems[]=
		{
        "V_sud_ussr_vest05"
		};
		weapons[]=
		{
		"Throw",
		"Put",	
		"CUP_arifle_AK74",
		"CUP_hgun_Makarov"
		};
		respawnweapons[]=
		{
		"Throw",
		"Put",	
		"CUP_arifle_AK74",
		"CUP_hgun_Makarov"
		};
		magazines[]=
		{
		"CUP_30Rnd_545x39_AK_M",
		"CUP_30Rnd_545x39_AK_M",
		"CUP_30Rnd_545x39_AK_M",
		"CUP_30Rnd_545x39_AK_M",
		"CUP_45Rnd_TE4_LRT4_Green_Tracer_545x39_RPK_M",
		"CUP_45Rnd_TE4_LRT4_Green_Tracer_545x39_RPK_M",
		"CUP_8Rnd_9x18_Makarov_M",
		"CUP_HandGrenade_RGO",
		"CUP_HandGrenade_RGO",
		"SmokeShell",
		"SmokeShell"
		};
		Respawnmagazines[]=
		{
		"CUP_30Rnd_545x39_AK_M",
		"CUP_30Rnd_545x39_AK_M",
		"CUP_30Rnd_545x39_AK_M",
		"CUP_30Rnd_545x39_AK_M",
		"CUP_45Rnd_TE4_LRT4_Green_Tracer_545x39_RPK_M",
		"CUP_45Rnd_TE4_LRT4_Green_Tracer_545x39_RPK_M",
		"CUP_8Rnd_9x18_Makarov_M",
		"CUP_HandGrenade_RGO",
		"CUP_HandGrenade_RGO",
		"SmokeShell",
		"SmokeShell"
		};
		Items[]=
		{
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_morphine",
		"ACE_morphine",
		"ACE_EarPlugs"
		};
		respawntems[]=
		{
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_morphine",
		"ACE_morphine",
		"ACE_EarPlugs"
		};
	};
	
	class ColdWar_USSR_AAGunner:O_Soldier_base_F
	{
		_generalMacro="ColdWar_USSR_AAGunner";
		scope=2;
		displayName="AA Gunner(ColdWar)";
		faction="a_units";
		vehicleClass="USSR";
		icon="iconMan";
		nakedUniform="U_BasicBody";
		uniformClass="DISCLOSE_BEREZKA";
		backpack="TWC_Backpack_USSR_AATeam";
		linkedItems[]=
		{
        "rhs_6b13_EMR_6sh92",
		"ItemCompass",
		"ItemWatch",
		"rhs_6b26_green"
		};
		respawnLinkedItems[]=
		{
        "rhs_6b13_EMR_6sh92",
		"ItemCompass",
		"ItemWatch",
		"rhs_6b26_green"
		};
		weapons[]=
		{
		"Throw",
		"Put",
		"rhs_weap_ak74m_dtk",
		"CUP_launch_9K32Strela"
		};
		respawnweapons[]=
		{
		"Throw",
		"Put",
		"rhs_weap_ak74m_dtk",
		"CUP_launch_9K32Strela"
		};
		magazines[]=
		{
		"CUP_Strela_2_M",
		"rhs_30Rnd_545x39_7N10_AK",
		"rhs_30Rnd_545x39_7N10_AK",
		"rhs_30Rnd_545x39_7N10_AK",
		"rhs_30Rnd_545x39_7N10_AK",
		"rhs_30Rnd_545x39_7N10_AK",
		"rhs_30Rnd_545x39_7N10_AK",
		"rhs_30Rnd_545x39_7N10_AK",
		"rhs_30Rnd_545x39_7N10_AK",
		"rhs_mag_rgd5",
		"rhs_mag_rgd5",
		"SmokeShell",
		"SmokeShell"
		};
		Respawnmagazines[]=
		{
		"CUP_Strela_2_M",
		"rhs_30Rnd_545x39_7N10_AK",
		"rhs_30Rnd_545x39_7N10_AK",
		"rhs_30Rnd_545x39_7N10_AK",
		"rhs_30Rnd_545x39_7N10_AK",
		"rhs_30Rnd_545x39_7N10_AK",
		"rhs_30Rnd_545x39_7N10_AK",
		"rhs_30Rnd_545x39_7N10_AK",
		"rhs_30Rnd_545x39_7N10_AK",
		"rhs_mag_rgd5",
		"rhs_mag_rgd5",
		"SmokeShell",
		"SmokeShell"
		};
		Items[]=
		{
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_morphine",
		"ACE_morphine",
		"ACE_EarPlugs"
		};
		respawntems[]=
		{
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_morphine",
		"ACE_morphine",
		"ACE_EarPlugs"	
		};		
	};
	
	class ColdWar_USSR_AAAssistant:O_Soldier_base_F
	{
		_generalMacro="ColdWar_USSR_AAAssistant";
		scope=2;
		displayName="AA Assistant(ColdWar)";
		faction="a_units";
		vehicleClass="USSR";
		icon="iconMan";
		nakedUniform="U_BasicBody";
		uniformClass="DISCLOSE_BEREZKA";
		backpack="TWC_Backpack_USSR_AATeam";
		linkedItems[]=
		{
        "rhs_6b13_EMR_6sh92",
		"ItemCompass",
		"ItemWatch",
		"rhs_6b26_green"
		};
		respawnLinkedItems[]=
		{
        "rhs_6b13_EMR_6sh92",
		"ItemCompass",
		"ItemWatch",
		"rhs_6b26_green"
		};
		weapons[]=
		{
		"Throw",
		"Put",
		"rhs_weap_ak74m_dtk"
		};
		respawnweapons[]=
		{
		"Throw",
		"Put",
		"rhs_weap_ak74m_dtk"
		};
		magazines[]=
		{
		"rhs_30Rnd_545x39_7N10_AK",
		"rhs_30Rnd_545x39_7N10_AK",
		"rhs_30Rnd_545x39_7N10_AK",
		"rhs_30Rnd_545x39_7N10_AK",
		"rhs_30Rnd_545x39_7N10_AK",
		"rhs_30Rnd_545x39_7N10_AK",
		"rhs_30Rnd_545x39_7N10_AK",
		"rhs_30Rnd_545x39_7N10_AK",
		"rhs_mag_rgd5",
		"rhs_mag_rgd5",
		"SmokeShell",
		"SmokeShell"
		};
		Respawnmagazines[]=
		{
		"rhs_30Rnd_545x39_7N10_AK",
		"rhs_30Rnd_545x39_7N10_AK",
		"rhs_30Rnd_545x39_7N10_AK",
		"rhs_30Rnd_545x39_7N10_AK",
		"rhs_30Rnd_545x39_7N10_AK",
		"rhs_30Rnd_545x39_7N10_AK",
		"rhs_30Rnd_545x39_7N10_AK",
		"rhs_30Rnd_545x39_7N10_AK",
		"rhs_mag_rgd5",
		"rhs_mag_rgd5",
		"SmokeShell",
		"SmokeShell"
		};
		Items[]=
		{
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_morphine",
		"ACE_morphine",
		"ACE_EarPlugs"
		};
		respawntems[]=
		{
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_morphine",
		"ACE_morphine",
		"ACE_EarPlugs"	
		};		
	};