	class IRA_Squadleader: I_Soldier_F
	{
		_generalMacro="IRA_Squadleader";
		scope=2;
		displayName="Section Leader";
		faction="ira_units";
		editorSubcategory = "Men_IRA";
		vehicleClass="Men_IRA";
		icon="iconManLeader";
		nakedUniform="U_BasicBody";
		uniformClass="U_IG_Guerrilla_6_1";
		backpack="";
		linkedItems[]=
		{
        "V_BandollierB_oli",
		"G_Balaclava_blk",
		"ItemMap",
		"ItemCompass",
		"Binocular"
		};
		respawnLinkedItems[]=
		{
        "V_BandollierB_oli",
		"G_Balaclava_blk",
		"ItemMap",
		"ItemCompass",
		"Binocular"
		};
		weapons[]=
		{
		"Throw",
		"Put",
		"CUP_srifle_LeeEnfield"
		};
		respawnweapons[]=
		{
		"Throw",
		"Put",
		"CUP_srifle_LeeEnfield"
		};
		magazines[]=
		{
		"CUP_10x_303_M",
		"CUP_10x_303_M",
		"CUP_10x_303_M",
		"CUP_10x_303_M",
		"CUP_10x_303_M",
		"HandGrenade",
		"HandGrenade",
		"SmokeShell"
		};
		Respawnmagazines[]=
		{
		"CUP_10x_303_M",
		"CUP_10x_303_M",
		"CUP_10x_303_M",
		"CUP_10x_303_M",
		"CUP_10x_303_M",
		"HandGrenade",
		"HandGrenade",
		"SmokeShell"
		};
		Items[]=
		{
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_morphine",
		"ACE_morphine"
		};
		respawntems[]=
		{
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_morphine",
		"ACE_morphine"
		};
	};
	
	class IRA_Rifleman_M16: I_Soldier_F
	{
		_generalMacro="IRA_Rifleman_M16";
		scope=2;
		displayName="Rifleman (M16)";
		faction="ira_units";
		editorSubcategory = "Men_IRA";
		vehicleClass="Men_IRA";
		icon="iconManLeader";
		nakedUniform="U_BasicBody";
		uniformClass="U_IG_Guerilla3_1";
		backpack="";
		linkedItems[]=
		{
        "V_BandollierB_cbr",
		"G_Balaclava_blk",
		"ItemMap",
		"ItemCompass"
		};
		respawnLinkedItems[]=
		{
        "V_BandollierB_cbr",
		"G_Balaclava_blk",
		"ItemMap",
		"ItemCompass"
		};
		weapons[]=
		{
		"Throw",
		"Put",
		"CUP_arifle_M16A2"
		};
		respawnweapons[]=
		{
		"Throw",
		"Put",
		"CUP_arifle_M16A2"
		};
		magazines[]=
		{
		"30Rnd_556x45_Stanag",
		"30Rnd_556x45_Stanag",
		"30Rnd_556x45_Stanag",
		"30Rnd_556x45_Stanag",
		"30Rnd_556x45_Stanag",
		"30Rnd_556x45_Stanag",
		"HandGrenade",
		"HandGrenade",
		"SmokeShell"
		};
		Respawnmagazines[]=
		{
		"30Rnd_556x45_Stanag",
		"30Rnd_556x45_Stanag",
		"30Rnd_556x45_Stanag",
		"30Rnd_556x45_Stanag",
		"30Rnd_556x45_Stanag",
		"30Rnd_556x45_Stanag",
		"HandGrenade",
		"HandGrenade",
		"SmokeShell"
		};
		Items[]=
		{
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_morphine",
		"ACE_morphine"
		};
		respawntems[]=
		{
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_morphine",
		"ACE_morphine"
		};
	};
	
	class IRA_Rifleman_AKM: I_Soldier_F
	{
		_generalMacro="IRA_Rifleman_AKM";
		scope=2;
		displayName="Rifleman (AKM)";
		faction="ira_units";
		editorSubcategory = "Men_IRA";
		vehicleClass="Men_IRA";
		icon="iconManLeader";
		nakedUniform="U_BasicBody";
		uniformClass="U_IG_Guerrilla_6_1";
		backpack="";
		linkedItems[]=
		{
        "V_BandollierB_rgr",
		"G_Balaclava_blk",
		"ItemMap",
		"ItemCompass"
		};
		respawnLinkedItems[]=
		{
        "V_BandollierB_rgr",
		"G_Balaclava_blk",
		"ItemMap",
		"ItemCompass"
		};
		weapons[]=
		{
		"Throw",
		"Put",
		"CUP_arifle_AKM"
		};
		respawnweapons[]=
		{
		"Throw",
		"Put",
		"CUP_arifle_AKM"
		};
		magazines[]=
		{
		"CUP_30Rnd_762x39_AK47_M",
		"CUP_30Rnd_762x39_AK47_M",
		"CUP_30Rnd_762x39_AK47_M",
		"CUP_30Rnd_762x39_AK47_M",
		"HandGrenade",
		"HandGrenade",
		"SmokeShell"
		};
		Respawnmagazines[]=
		{
		"CUP_30Rnd_762x39_AK47_M",
		"CUP_30Rnd_762x39_AK47_M",
		"CUP_30Rnd_762x39_AK47_M",
		"CUP_30Rnd_762x39_AK47_M",
		"HandGrenade",
		"HandGrenade",
		"SmokeShell"
		};
		Items[]=
		{
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_morphine",
		"ACE_morphine"
		};
		respawntems[]=
		{
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_morphine",
		"ACE_morphine"
		};
	};
	
	class IRA_Rifleman_FAL: I_Soldier_F
	{
		_generalMacro="IRA_Rifleman_FAL";
		scope=2;
		displayName="Rifleman (FAL)";
		faction="ira_units";
		editorSubcategory = "Men_IRA";
		vehicleClass="Men_IRA";
		icon="iconManLeader";
		nakedUniform="U_BasicBody";
		uniformClass="U_IG_Guerilla3_1";
		backpack="";
		linkedItems[]=
		{
        "V_BandollierB_cbr",
		"G_Balaclava_blk",
		"ItemMap",
		"ItemCompass"
		};
		respawnLinkedItems[]=
		{
        "V_BandollierB_cbr",
		"G_Balaclava_blk",
		"ItemMap",
		"ItemCompass"
		};
		weapons[]=
		{
		"Throw",
		"Put",
		"CUP_arifle_FNFAL"
		};
		respawnweapons[]=
		{
		"Throw",
		"Put",
		"CUP_arifle_FNFAL"
		};
		magazines[]=
		{
		"CUP_20Rnd_762x51_FNFAL_M",
		"CUP_20Rnd_762x51_FNFAL_M",
		"CUP_20Rnd_762x51_FNFAL_M",
		"CUP_20Rnd_762x51_FNFAL_M",
		"CUP_20Rnd_762x51_FNFAL_M",
		"HandGrenade",
		"HandGrenade",
		"SmokeShell"
		};
		Respawnmagazines[]=
		{
		"CUP_20Rnd_762x51_FNFAL_M",
		"CUP_20Rnd_762x51_FNFAL_M",
		"CUP_20Rnd_762x51_FNFAL_M",
		"CUP_20Rnd_762x51_FNFAL_M",
		"CUP_20Rnd_762x51_FNFAL_M",
		"HandGrenade",
		"HandGrenade",
		"SmokeShell"
		};
		Items[]=
		{
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_morphine",
		"ACE_morphine"
		};
		respawntems[]=
		{
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_morphine",
		"ACE_morphine"
		};
	};
	
	class IRA_Rifleman_AT: I_Soldier_F
	{
		_generalMacro="IRA_Rifleman_AT";
		scope=2;
		displayName="AT Rifleman";
		faction="ira_units";
		editorSubcategory = "Men_IRA";
		vehicleClass="Men_IRA";
		icon="iconManLeader";
		nakedUniform="U_BasicBody";
		uniformClass="U_IG_Guerilla3_1";
		backpack="Afr_Backpack_AT";
		linkedItems[]=
		{
        "V_BandollierB_cbr",
		"G_Balaclava_oli",
		"ItemMap",
		"ItemCompass"
		};
		respawnLinkedItems[]=
		{
        "V_BandollierB_cbr",
		"G_Balaclava_oli",
		"ItemMap",
		"ItemCompass"
		};
		weapons[]=
		{
		"Throw",
		"Put",
		"CUP_arifle_AKM",
		"CUP_launch_RPG7V"
		};
		respawnweapons[]=
		{
		"Throw",
		"Put",
		"CUP_arifle_AKM",
		"CUP_launch_RPG7V"
		};
		magazines[]=
		{
		"CUP_PG7V_M",
		"CUP_30Rnd_762x39_AK47_M",
		"CUP_30Rnd_762x39_AK47_M",
		"CUP_30Rnd_762x39_AK47_M",
		"HandGrenade",
		"HandGrenade",
		"SmokeShell"
		};
		Respawnmagazines[]=
		{
		"CUP_PG7V_M",
		"CUP_30Rnd_762x39_AK47_M",
		"CUP_30Rnd_762x39_AK47_M",
		"CUP_30Rnd_762x39_AK47_M",
		"HandGrenade",
		"HandGrenade",
		"SmokeShell"
		};
		Items[]=
		{
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_morphine",
		"ACE_morphine"
		};
		respawntems[]=
		{
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_morphine",
		"ACE_morphine"
		};
	};
	
	class IRA_Autorifleman: I_Soldier_F
	{
		_generalMacro="IRA_Autorifleman";
		scope=2;
		displayName="Autorifleman";
		faction="ira_units";
		editorSubcategory = "Men_IRA";
		vehicleClass="Men_IRA";
		icon="iconManLeader";
		nakedUniform="U_BasicBody";
		uniformClass="U_IG_Guerilla2_3";
		backpack="";
		linkedItems[]=
		{
        "V_BandollierB_oli",
		"G_Balaclava_blk",
		"ItemMap",
		"ItemCompass"
		};
		respawnLinkedItems[]=
		{
        "V_BandollierB_oli",
		"G_Balaclava_blk",
		"ItemMap",
		"ItemCompass"
		};
		weapons[]=
		{
		"Throw",
		"Put",
		"CUP_lmg_L7A2"
		};
		respawnweapons[]=
		{
		"Throw",
		"Put",
		"CUP_lmg_L7A2"
		};
		magazines[]=
		{
		"CUP_100Rnd_TE4_LRT4_Red_Tracer_762x51_Belt_M",
		"CUP_100Rnd_TE4_LRT4_Red_Tracer_762x51_Belt_M",
		"SmokeShell"
		};
		Respawnmagazines[]=
		{
		"CUP_100Rnd_TE4_LRT4_Red_Tracer_762x51_Belt_M",
		"CUP_100Rnd_TE4_LRT4_Red_Tracer_762x51_Belt_M",
		"SmokeShell"
		};
		Items[]=
		{
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_morphine",
		"ACE_morphine"
		};
		respawntems[]=
		{
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_morphine",
		"ACE_morphine"
		};
	};