
	class Modern_British_VehicleCrew: B_Soldier_base_F
	{
		_generalMacro="Modern_British_VehicleCrew";
		scope=2;
		displayName="Modern Vehicle Crewman(Modern)";
		faction="a_units";
		vehicleClass="Attachments";
		icon="iconManLeader";
		nakedUniform="U_BasicBody";
		uniformClass="UK3CB_BAF_U_CombatUniform_MTP";
		backpack="";
		linkedItems[]=
		{
		"UK3CB_BAF_H_CrewHelmet_A",
		"UK3CB_BAF_V_Osprey",
		"ItemMap",
		"ItemCompass",
		"ItemWatch",
		"ACRE_PRC343",
		"UK3CB_BAF_G_Tactical_Black"
		};
		respawnLinkedItems[]=
		{
		"UK3CB_BAF_H_CrewHelmet_A",
		"UK3CB_BAF_V_Osprey",
		"ItemMap",
		"ItemCompass",
		"ItemWatch",
		"ACRE_PRC343",
		"UK3CB_BAF_G_Tactical_Black"
		};
		weapons[]=
		{
		"Throw",
		"Put",	
		"UK3CB_BAF_L22A2_SUSAT3D"
		};
		respawnweapons[]=
		{
		"Throw",
		"Put",	
		"UK3CB_BAF_L22A2_SUSAT3D"
		};
		magazines[]=
		{
		"UK3CB_BAF_556_30Rnd",
		"UK3CB_BAF_556_30Rnd",
		"smokeshell"
		};
		Respawnmagazines[]=
		{
		"UK3CB_BAF_556_30Rnd",
		"UK3CB_BAF_556_30Rnd",
		"smokeshell"
		};
		Items[]=
		{
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_morphine",
		"ACE_morphine",
		"ACE_Flashlight_KSF1",
		"ACE_IR_Strobe_Item",
	    "ACE_MapTools",
		"UK3CB_BAF_HMNVS",
		"ACE_EarPlugs"	
		};
		respawntems[]=
		{
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_morphine",
		"ACE_morphine",
		"ACE_Flashlight_KSF1",
		"ACE_IR_Strobe_Item",
	    "ACE_MapTools",
		"UK3CB_BAF_HMNVS"		
		};
	};
	class Modern_British_VehicleCommander: B_Soldier_base_F
	{
		_generalMacro="Modern_British_VehicleCrew";
		scope=2;
		displayName="Modern Vehicle Commander(Modern)";
		faction="a_units";
		vehicleClass="Attachments";
		icon="iconManLeader";
		nakedUniform="U_BasicBody";
		uniformClass="UK3CB_BAF_U_CombatUniform_MTP";
		backpack="TWC_Backpack_Modern_Vehiclecommander";
		linkedItems[]=
		{	
		"UK3CB_BAF_H_CrewHelmet_ESS_A",
		"UK3CB_BAF_V_Osprey",
		"ItemMap",
		"ItemcTab",
		"ItemCompass",
		"ItemWatch",
		"ACRE_PRC343",
		"UK3CB_BAF_G_Tactical_Black"
		};
		respawnLinkedItems[]=
		{		
		"UK3CB_BAF_H_CrewHelmet_ESS_A",
		"UK3CB_BAF_V_Osprey",
		"ItemMap",
		"ItemcTab",
		"ItemCompass",
		"ItemWatch",
		"ACRE_PRC343",
		"UK3CB_BAF_G_Tactical_Black"
		};
		weapons[]=
		{
		"Throw",
		"Put",
		"ACE_Vector",
		"UK3CB_BAF_L22A2_SUSAT3D"
		};
		respawnweapons[]=
		{
		"Throw",
		"Put",
		"ACE_Vector",
		"UK3CB_BAF_L22A2_SUSAT3D"
		};
		magazines[]=
		{
		"UK3CB_BAF_556_30Rnd",
		"UK3CB_BAF_556_30Rnd",
		"smokeshell",
		"smokeshell"
		};
		Respawnmagazines[]=
		{
		"UK3CB_BAF_556_30Rnd",
		"UK3CB_BAF_556_30Rnd",
		"smokeshell",
		"smokeshell"
		};
		Items[]=
		{
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_morphine",
		"ACE_morphine",
		"ACE_Flashlight_KSF1",
		"ACE_IR_Strobe_Item",
	    "ACE_MapTools",
		"UK3CB_BAF_HMNVS",
		"ACE_EarPlugs"	
		};
		respawntems[]=
		{
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_morphine",
		"ACE_morphine",
		"ACE_Flashlight_KSF1",
		"ACE_IR_Strobe_Item",
	    "ACE_MapTools",
		"UK3CB_BAF_HMNVS"
		};
	};
	
	class Mechanized_British_2IC: B_Soldier_base_F
	{
		_generalMacro="Mechanized_British_2IC";
		scope=2;
		displayName="2IC(Modern)";
		faction="a_units";
		vehicleClass="Modern_British";
		icon="iconMan";
		nakedUniform="U_BasicBody";
		uniformClass="UK3CB_BAF_U_CombatUniform_MTP";
		backpack="TWC_Backpack_Mechanized_2IC";
		linkedItems[]=
		{
        "UK3CB_BAF_H_Mk7_Scrim_ESS_B",
		"UK3CB_BAF_V_Osprey_Rifleman_C",
		"ItemMap",
		"ItemCompass",
		"ItemWatch",
		"ACRE_PRC343",
		"UK3CB_BAF_G_Tactical_Black"
		};
		respawnLinkedItems[]=
		{
        "UK3CB_BAF_H_Mk7_Scrim_ESS_B",
		"UK3CB_BAF_V_Osprey_Rifleman_C",
		"ItemMap",
		"ItemCompass",
		"ItemWatch",
		"ACRE_PRC343",
		"UK3CB_BAF_G_Tactical_Black"
		};
		weapons[]=
		{
		"Throw",
		"Put",
		"ACE_Vector",
		"UK3CB_BAF_L85A2_RIS_AFG_ELCAN3D"
		};
		respawnweapons[]=
		{
		"Throw",
		"Put",
		"ACE_Vector",
		"UK3CB_BAF_L85A2_RIS_AFG_ELCAN3D"
		};
		magazines[]=
		{
		"UK3CB_BAF_556_30Rnd",
		"UK3CB_BAF_556_30Rnd",		
		"UK3CB_BAF_556_30Rnd",
		"UK3CB_BAF_556_30Rnd",
		"UK3CB_BAF_556_30Rnd_T",
		"UK3CB_BAF_556_30Rnd_T",
		"CUP_HandGrenade_L109A2_HE",
		"CUP_HandGrenade_L109A2_HE",
		"SmokeShell",
		"SmokeShell",
		"SmokeShell"
		};
		Respawnmagazines[]=
		{
		"UK3CB_BAF_556_30Rnd",
		"UK3CB_BAF_556_30Rnd",		
		"UK3CB_BAF_556_30Rnd",
		"UK3CB_BAF_556_30Rnd",
		"UK3CB_BAF_556_30Rnd_T",
		"UK3CB_BAF_556_30Rnd_T",
		"CUP_HandGrenade_L109A2_HE",
		"CUP_HandGrenade_L109A2_HE",
		"SmokeShell",
		"SmokeShell",
		"SmokeShell"
		};
		Items[]=
		{
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_morphine",
		"ACE_morphine",
		"ACE_EarPlugs",
		"ACE_DAGR",		
		"UK3CB_BAF_HMNVS"
		};
		respawntems[]=
		{
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_morphine",
		"ACE_morphine",
		"ACE_EarPlugs",	
		"UK3CB_BAF_HMNVS"		
		};
	};
	
	class Mechanized_British_Marksman: B_Soldier_base_F
	{
		_generalMacro="Modern_British_Marksman";
		scope=2;
		displayName="Marksman(Modern)";
		faction="a_units";
		vehicleClass="Modern_British";
		icon="iconMan";
		nakedUniform="U_BasicBody";
		uniformClass="UK3CB_BAF_U_CombatUniform_MTP";
		backpack="TWC_Backpack_Mechanized_Marksman";
		linkedItems[]=
		{
        "UK3CB_BAF_V_Osprey_Marksman_A",
		"UK3CB_BAF_H_Mk7_Scrim_E",
		"ItemMap",
		"ItemCompass",
		"ItemWatch",
		"UK3CB_BAF_G_Tactical_Black",
		"ACRE_PRC343"
		};
		respawnLinkedItems[]=
		{
        "UK3CB_BAF_V_Osprey_Marksman_A",
		"UK3CB_BAF_H_Mk7_Scrim_E",
		"ItemMap",
		"ItemCompass",
		"ItemWatch",
		"ACRE_PRC343",
		"UK3CB_BAF_G_Tactical_Black"
		};
		weapons[]=
		{
		"Throw",
		"Put",
		"ACE_Vector",
		"UK3CB_BAF_L129A1_Grippod_TA648",
		"UK3CB_BAF_NLAW_Launcher"
		};
		respawnweapons[]=
		{
		"Throw",
		"Put",
		"ACE_Vector",
		"UK3CB_BAF_L129A1_Grippod_TA648",
		"UK3CB_BAF_NLAW_Launcher"
		};
		magazines[]=
		{
		"CUP_HandGrenade_L109A2_HE",
		"CUP_HandGrenade_L109A2_HE",
		"SmokeShell",
		"SmokeShell",
		"SmokeShell"
		};
		Respawnmagazines[]=
		{
		"CUP_HandGrenade_L109A2_HE",
		"CUP_HandGrenade_L109A2_HE",
		"SmokeShell",
		"SmokeShell",
		"SmokeShell"
		};
		Items[]=
		{
			"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_morphine",
		"ACE_morphine",
		"ACE_epinephrine",
		"ACE_tourniquet",
		"ACE_EarPlugs",	
		"UK3CB_BAF_HMNVS"
		};
		respawntems[]=
		{
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_morphine",
		"ACE_morphine",
		"ACE_EarPlugs",	
		"UK3CB_BAF_HMNVS"			
		};		
	};
