
	class Modern_British_VehicleCrew: B_Soldier_base_F
	{
		_generalMacro="Modern_British_VehicleCrew";
		scope=2;
		displayName="Modern Vehicle Crewman(Modern)";
		faction="twc_faction";
		editorSubcategory = "Men_Modern";
		vehicleClass="Men_Modern";
		icon="iconManLeader";
		nakedUniform="U_BasicBody";
		uniformClass="UK3CB_BAF_U_CombatUniform_MTP";
		backpack="";
		linkedItems[]=
		{
		"UK3CB_BAF_H_CrewHelmet_A",
		"UK3CB_BAF_V_Osprey",
		"ItemMap",
		"ItemCompass",
		"ItemWatch",
		"UK3CB_BAF_G_Tactical_Black"
		};
		respawnLinkedItems[]=
		{
		"UK3CB_BAF_H_CrewHelmet_A",
		"UK3CB_BAF_V_Osprey",
		"ItemMap",
		"ItemCompass",
		"ItemWatch",
		"UK3CB_BAF_G_Tactical_Black"
		};
		weapons[]=
		{
		"Throw",
		"Put",	
		"UK3CB_BAF_L22A2_SUSAT3D"
		};
		respawnweapons[]=
		{
		"Throw",
		"Put",	
		"UK3CB_BAF_L22A2_SUSAT3D"
		};
		magazines[]=
		{
		"UK3CB_BAF_556_30Rnd",
		"UK3CB_BAF_556_30Rnd",
		"smokeshell"
		};
		Respawnmagazines[]=
		{
		"UK3CB_BAF_556_30Rnd",
		"UK3CB_BAF_556_30Rnd",
		"smokeshell"
		};
		Items[]=
		{
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_morphine",
		"ACE_morphine",
		"ACE_epinephrine",
		"ACE_tourniquet",
		"ACE_EarPlugs",	
		"UK3CB_BAF_HMNVS",
		"ACRE_PRC343"
		};
		respawntems[]=
		{
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_morphine",
		"ACE_morphine",
		"ACE_epinephrine",
		"ACE_tourniquet",
		"ACE_EarPlugs",	
		"UK3CB_BAF_HMNVS",
		"ACRE_PRC343"		
		};
	};
	class Modern_British_VehicleCommander: B_Soldier_base_F
	{
		_generalMacro="Modern_British_VehicleCrew";
		scope=2;
		displayName="Modern Vehicle Commander(Modern)";
		faction="twc_faction";
		editorSubcategory = "Men_Modern";
		vehicleClass="Men_Modern";
		icon="iconManLeader";
		nakedUniform="U_BasicBody";
		uniformClass="UK3CB_BAF_U_CombatUniform_MTP";
		backpack="TWC_Backpack_Modern_Vehiclecommander";
		linkedItems[]=
		{	
		"UK3CB_BAF_H_CrewHelmet_ESS_A",
		"UK3CB_BAF_V_Osprey",
		"ItemMap",
		"ItemcTab",
		"ItemCompass",
		"ItemWatch",
		"UK3CB_BAF_G_Tactical_Black"
		};
		respawnLinkedItems[]=
		{		
		"UK3CB_BAF_H_CrewHelmet_ESS_A",
		"UK3CB_BAF_V_Osprey",
		"ItemMap",
		"ItemcTab",
		"ItemCompass",
		"ItemWatch",
		"UK3CB_BAF_G_Tactical_Black"
		};
		weapons[]=
		{
		"Throw",
		"Put",
		"ACE_Vector",
		"UK3CB_BAF_L22A2_SUSAT3D"
		};
		respawnweapons[]=
		{
		"Throw",
		"Put",
		"ACE_Vector",
		"UK3CB_BAF_L22A2_SUSAT3D"
		};
		magazines[]=
		{
		"UK3CB_BAF_556_30Rnd",
		"UK3CB_BAF_556_30Rnd",
		"B_IR_Grenade"
		};
		Respawnmagazines[]=
		{
		"UK3CB_BAF_556_30Rnd",
		"UK3CB_BAF_556_30Rnd",
		"B_IR_Grenade"
		};
		Items[]=
		{
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_morphine",
		"ACE_morphine",
		"ACE_epinephrine",
		"ACE_tourniquet",
		"ACE_EarPlugs",	
		"UK3CB_BAF_HMNVS",
		"ACRE_PRC343"
		};
		respawntems[]=
		{
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_morphine",
		"ACE_morphine",
		"ACE_epinephrine",
		"ACE_tourniquet",
		"ACE_EarPlugs",	
		"UK3CB_BAF_HMNVS",
		"ACRE_PRC343"
		};
	};
	
	class Mechanized_British_Marksman: B_Soldier_base_F
	{
		_generalMacro="Modern_British_Marksman";
		scope=2;
		displayName="Marksman(Modern)";
		faction="twc_faction";
		editorSubcategory = "Men_Modern";
		vehicleClass="Men_Modern";
		icon="iconMan";
		nakedUniform="U_BasicBody";
		uniformClass="UK3CB_BAF_U_CombatUniform_MTP";
		backpack="TWC_Backpack_Mechanized_Marksman";
		linkedItems[]=
		{
        "UK3CB_BAF_V_Osprey_Marksman_A",
		"UK3CB_BAF_H_Mk7_Scrim_E",
		"ItemMap",
		"ItemCompass",
		"ItemWatch",
		"UK3CB_BAF_G_Tactical_Black"
		};
		respawnLinkedItems[]=
		{
        "UK3CB_BAF_V_Osprey_Marksman_A",
		"UK3CB_BAF_H_Mk7_Scrim_E",
		"ItemMap",
		"ItemCompass",
		"ItemWatch",
		"UK3CB_BAF_G_Tactical_Black"
		};
		weapons[]=
		{
		"Throw",
		"Put",
		"ACE_Vector",
		"UK3CB_BAF_L129A1_Grippod_TA648",
		"launch_NLAW_F"
		};
		respawnweapons[]=
		{
		"Throw",
		"Put",
		"ACE_Vector",
		"UK3CB_BAF_L129A1_Grippod_TA648",
		"launch_NLAW_F"
		};
		magazines[]=
		{
		"UK3CB_BAF_762_L42A1_20Rnd",
		"UK3CB_BAF_762_L42A1_20Rnd",
		"UK3CB_BAF_762_L42A1_20Rnd",
		"UK3CB_BAF_762_L42A1_20Rnd",
		"UK3CB_BAF_762_L42A1_20Rnd",
		"UK3CB_BAF_762_L42A1_20Rnd",
		"UK3CB_BAF_762_L42A1_20Rnd",
		"UK3CB_BAF_762_L42A1_20Rnd",
		"UK3CB_BAF_762_L42A1_20Rnd_T",
		"UK3CB_BAF_762_L42A1_20Rnd_T",
		"CUP_HandGrenade_L109A2_HE",
		"CUP_HandGrenade_L109A2_HE"
		};
		Respawnmagazines[]=
		{
		"UK3CB_BAF_762_L42A1_20Rnd",
		"UK3CB_BAF_762_L42A1_20Rnd",
		"UK3CB_BAF_762_L42A1_20Rnd",
		"UK3CB_BAF_762_L42A1_20Rnd",
		"UK3CB_BAF_762_L42A1_20Rnd",
		"UK3CB_BAF_762_L42A1_20Rnd",
		"UK3CB_BAF_762_L42A1_20Rnd",
		"UK3CB_BAF_762_L42A1_20Rnd",
		"UK3CB_BAF_762_L42A1_20Rnd_T",
		"UK3CB_BAF_762_L42A1_20Rnd_T",
		"CUP_HandGrenade_L109A2_HE",
		"CUP_HandGrenade_L109A2_HE"
		};
		Items[]=
		{
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_morphine",
		"ACE_morphine",
		"ACE_epinephrine",
		"ACE_tourniquet",
		"ACE_EarPlugs",	
		"UK3CB_BAF_HMNVS",
		"ACRE_PRC343"
		};
		respawntems[]=
		{
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_morphine",
		"ACE_morphine",
		"ACE_epinephrine",
		"ACE_tourniquet",
		"ACE_EarPlugs",	
		"UK3CB_BAF_HMNVS",
		"ACRE_PRC343"			
		};		
	};
	class Mechanized_British_Coin_Marksman: B_Soldier_base_F
	{
		_generalMacro="Modern_British_Coin_Marksman";
		scope=2;
		displayName="Marksman(Coin)";
		faction="twc_faction";
		editorSubcategory = "Men_ModernCoin";
		vehicleClass="Men_ModernCoin";
		icon="iconMan";
		nakedUniform="U_BasicBody";
		uniformClass="UK3CB_BAF_U_CombatUniform_MTP";
		backpack="TWC_Backpack_Mechanized_Marksman";
		linkedItems[]=
		{
        "UK3CB_BAF_V_Osprey_Marksman_A",
		"UK3CB_BAF_H_Mk7_Scrim_E",
		"ItemMap",
		"ItemCompass",
		"ItemWatch",
		"UK3CB_BAF_G_Tactical_Black"
		};
		respawnLinkedItems[]=
		{
        "UK3CB_BAF_V_Osprey_Marksman_A",
		"UK3CB_BAF_H_Mk7_Scrim_E",
		"ItemMap",
		"ItemCompass",
		"ItemWatch",
		"UK3CB_BAF_G_Tactical_Black"
		};
		weapons[]=
		{
		"Throw",
		"Put",	
		"ACE_Vector",
		"UK3CB_BAF_L129A1_Grippod_TA648",
		"UK3CB_BAF_L131A1",
		"launch_NLAW_F"
		};
		respawnweapons[]=
		{
		"Throw",
		"Put",
		"ACE_Vector",
		"UK3CB_BAF_L129A1_Grippod_TA648",
		"UK3CB_BAF_L131A1",
		"launch_NLAW_F"
		};
		magazines[]=
		{
		"UK3CB_BAF_9_17Rnd",
		"UK3CB_BAF_9_17Rnd",
		"UK3CB_BAF_762_L42A1_20Rnd",
		"UK3CB_BAF_762_L42A1_20Rnd",
		"UK3CB_BAF_762_L42A1_20Rnd",
		"UK3CB_BAF_762_L42A1_20Rnd",
		"UK3CB_BAF_762_L42A1_20Rnd",
		"UK3CB_BAF_762_L42A1_20Rnd",
		"UK3CB_BAF_762_L42A1_20Rnd",
		"UK3CB_BAF_762_L42A1_20Rnd",
		"UK3CB_BAF_762_L42A1_20Rnd_T",
		"UK3CB_BAF_762_L42A1_20Rnd_T",
		"CUP_HandGrenade_L109A2_HE",
		"CUP_HandGrenade_L109A2_HE"
		};
		Respawnmagazines[]=
		{
		"UK3CB_BAF_9_17Rnd",
		"UK3CB_BAF_9_17Rnd",
		"UK3CB_BAF_762_L42A1_20Rnd",
		"UK3CB_BAF_762_L42A1_20Rnd",
		"UK3CB_BAF_762_L42A1_20Rnd",
		"UK3CB_BAF_762_L42A1_20Rnd",
		"UK3CB_BAF_762_L42A1_20Rnd",
		"UK3CB_BAF_762_L42A1_20Rnd",
		"UK3CB_BAF_762_L42A1_20Rnd",
		"UK3CB_BAF_762_L42A1_20Rnd",
		"UK3CB_BAF_762_L42A1_20Rnd_T",
		"UK3CB_BAF_762_L42A1_20Rnd_T",
		"CUP_HandGrenade_L109A2_HE",
		"CUP_HandGrenade_L109A2_HE"
		};
		Items[]=
		{
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_morphine",
		"ACE_morphine",
		"ACE_epinephrine",
		"ACE_tourniquet",
		"ACE_EarPlugs",	
		"UK3CB_BAF_HMNVS",
		"ACRE_PRC343"
		};
		respawntems[]=
		{
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_morphine",
		"ACE_morphine",
		"ACE_epinephrine",
		"ACE_tourniquet",
		"ACE_EarPlugs",	
		"UK3CB_BAF_HMNVS",
		"ACRE_PRC343"	
		};		
	};
