	class Modern_British_Squadleader: B_Soldier_base_F
	{
		_generalMacro="Modern_British_Squadleader";
		scope=2;
		displayName="Section Leader(Modern)";
		faction="a_units";
		vehicleClass="Modern_British";
		icon="iconManLeader";
		nakedUniform="U_BasicBody";
		uniformClass="UK3CB_BAF_U_CombatUniform_MTP";
		backpack="TWC_Backpack_Modern_Sectionlead";
		linkedItems[]=
		{
        "UK3CB_BAF_V_Osprey_SL_D",
		"UK3CB_BAF_H_Mk7_Scrim_ESS_B",
		"ItemMap",
		"ItemcTab",
		"ItemCompass",
		"ItemWatch",
		"ACRE_PRC343",
		"UK3CB_BAF_G_Tactical_Black"
		};
		respawnLinkedItems[]=
		{
        "UK3CB_BAF_V_Osprey_SL_D",
		"UK3CB_BAF_H_Mk7_Scrim_ESS_B",
		"ItemMap",
		"ItemcTab",
		"ItemCompass",
		"ItemWatch",
		"ACRE_PRC343",
		"UK3CB_BAF_G_Tactical_Black"
		};
		weapons[]=
		{
		"Throw",
		"Put",
		"ACE_Vector",
		"UK3CB_BAF_L85A2_RIS_AFG_ELCAN3D",
		"UK3CB_BAF_L131A1"
		};
		respawnweapons[]=
		{
		"Throw",
		"Put",
		"ACE_Vector",
		"UK3CB_BAF_L85A2_RIS_AFG_ELCAN3D",
		"UK3CB_BAF_L131A1"
		};
		magazines[]=
		{
		"UK3CB_BAF_17Rnd_9mm",
		"UK3CB_BAF_17Rnd_9mm",
		"UK3CB_BAF_17Rnd_9mm",
		"UK3CB_BAF_30Rnd_T",
		"UK3CB_BAF_30Rnd_T",
		"UK3CB_BAF_30Rnd",
		"UK3CB_BAF_30Rnd",
		"UK3CB_BAF_30Rnd",
		"CUP_HandGrenade_L109A2_HE",
		"CUP_HandGrenade_L109A2_HE"
		};
		Respawnmagazines[]=
		{
		"UK3CB_BAF_17Rnd_9mm",
		"UK3CB_BAF_17Rnd_9mm",
		"UK3CB_BAF_17Rnd_9mm",
		"UK3CB_BAF_30Rnd_T",
		"UK3CB_BAF_30Rnd_T",
		"UK3CB_BAF_30Rnd",
		"UK3CB_BAF_30Rnd",
		"UK3CB_BAF_30Rnd",
		"CUP_HandGrenade_L109A2_HE",
		"CUP_HandGrenade_L109A2_HE"
		};
		Items[]=
		{
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_morphine",
		"ACE_morphine",
		"ACE_epinephrine",
		"ACE_tourniquet",
		"ACE_Flashlight_KSF1",
		"ACE_IR_Strobe_Item",
	    "ACE_MapTools",
		"UK3CB_BAF_HMNVS",
		"ACE_DAGR",
		"ACE_EarPlugs"	
		};
		respawntems[]=
		{
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_morphine",
		"ACE_morphine",
		"ACE_Flashlight_KSF1",
		"ACE_IR_Strobe_Item",
	    "ACE_MapTools",
		"UK3CB_BAF_HMNVS",
		"ACE_EarPlugs"			
		};
	};
	
	class Modern_British_Rifleman: B_Soldier_base_F
	{
		_generalMacro="Modern_British_Rifleman";
		scope=2;
		displayName="RifleMan(Modern)";
		faction="a_units";
		vehicleClass="Modern_British";
		icon="iconMan";
		nakedUniform="U_BasicBody";
		uniformClass="UK3CB_BAF_U_CombatUniform_MTP";
		backpack="TWC_Backpack_Modern_Rifleman";
		linkedItems[]=
		{
        "UK3CB_BAF_V_Osprey_Rifleman_B",
		"UK3CB_BAF_H_Mk7_Scrim_B",
		"ItemMap",
		"ItemCompass",
		"ItemWatch",
		"ACRE_PRC343",
		"UK3CB_BAF_G_Tactical_Black"
		};
		respawnLinkedItems[]=
		{
        "UK3CB_BAF_V_Osprey_Rifleman_B",
		"UK3CB_BAF_H_Mk7_Scrim_B",
		"ItemMap",
		"ItemCompass",
		"ItemWatch",
		"UK3CB_BAF_G_Tactical_Black",
		"ACRE_PRC343"
		};
		weapons[]=
		{
		"Throw",
		"Put",	
		"UK3CB_BAF_L85A2_RIS_AFG_ELCAN3D",
		"UK3CB_BAF_NLAW_Launcher"
		};
		respawnweapons[]=
		{
		"Throw",
		"Put",	
		"UK3CB_BAF_L85A2_RIS_AFG_ELCAN3D",
		"UK3CB_BAF_NLAW_Launcher"
		};
		magazines[]=
		{
		"UK3CB_BAF_30Rnd_T",
		"UK3CB_BAF_30Rnd_T",
		"CUP_HandGrenade_L109A2_HE",
		"CUP_HandGrenade_L109A2_HE",
		"SmokeShell",
		"SmokeShell",
		"SmokeShell"
		};
		Respawnmagazines[]=
		{
		"UK3CB_BAF_30Rnd_T",
		"UK3CB_BAF_30Rnd_T",
		"CUP_HandGrenade_L109A2_HE",
		"CUP_HandGrenade_L109A2_HE",
		"SmokeShell",
		"SmokeShell",
		"SmokeShell"
		};
		Items[]=
		{
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_morphine",
		"ACE_morphine",
		"ACE_epinephrine",
		"ACE_tourniquet",
		"ACE_EarPlugs",	
		"UK3CB_BAF_HMNVS"
		};
		respawntems[]=
		{
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_morphine",
		"ACE_morphine",
		"ACE_EarPlugs",	
		"UK3CB_BAF_HMNVS"		
		};		
	};

	class Modern_British_Grenadier: B_Soldier_base_F
	{
		_generalMacro="Modern_British_Grenadier";
		scope=2;
		displayName="Grenadier(Modern)";
		faction="a_units";
		vehicleClass="Modern_British";
		icon="iconManExplosive";
		nakedUniform="U_BasicBody";
		uniformClass="UK3CB_BAF_U_CombatUniform_MTP";
		backpack="TWC_Backpack_Modern_Grenadier";
		linkedItems[]=
		{
        "UK3CB_BAF_V_Osprey_Grenadier_B",
		"UK3CB_BAF_H_Mk7_Scrim_A",
		"ItemMap",
		"ItemCompass",
		"ItemWatch",
		"ACRE_PRC343",
		"UK3CB_BAF_G_Tactical_Black"
		};
		respawnLinkedItems[]=
		{
        "UK3CB_BAF_V_Osprey_Grenadier_B",
		"UK3CB_BAF_H_Mk7_Scrim_A",
		"ItemMap",
		"ItemCompass",
		"ItemWatch",
		"UK3CB_BAF_G_Tactical_Black"
		};
		weapons[]=
		{
		"Throw",
		"Put",
		"ACE_Vector",
		"UK3CB_BAF_L85A2_UGL_ELCAN3D",
		"HAFM_LAW"
		};
		respawnweapons[]=
		{
		"Throw",
		"Put",
		"ACE_Vector",
		"UK3CB_BAF_L85A2_UGL_ELCAN3D",
		"HAFM_LAW"
		};
		magazines[]=
		{
		"UK3CB_BAF_30Rnd",
		"UK3CB_BAF_30Rnd",		
		"UK3CB_BAF_30Rnd",
		"UK3CB_BAF_30Rnd_T",
		"UK3CB_BAF_30Rnd_T",
		"CUP_HandGrenade_L109A2_HE",
		"CUP_HandGrenade_L109A2_HE",
		"SmokeShell",
		"SmokeShell",
		"SmokeShell"
		};
		Respawnmagazines[]=
		{
		"UK3CB_BAF_30Rnd",
		"UK3CB_BAF_30Rnd",		
		"UK3CB_BAF_30Rnd",
		"UK3CB_BAF_30Rnd_T",
		"UK3CB_BAF_30Rnd_T",
		"CUP_HandGrenade_L109A2_HE",
		"CUP_HandGrenade_L109A2_HE",
		"SmokeShell",
		"SmokeShell",
		"SmokeShell"
		};
		Items[]=
		{
			"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_morphine",
		"ACE_morphine",
		"ACE_epinephrine",
		"ACE_tourniquet",
		"ACE_EarPlugs",	
		"UK3CB_BAF_HMNVS"
		};
		respawntems[]=
		{
			"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_morphine",
		"ACE_morphine",
		"ACE_epinephrine",
		"ACE_tourniquet",
		"ACE_EarPlugs",	
		"UK3CB_BAF_HMNVS"			
		};
	};

	class Modern_British_Automaticrifleman: B_Soldier_base_F
	{
		_generalMacro="Modern_British_Automaticrifleman";
		scope=2;
		displayName="Automatic Rifleman(Modern)";
		faction="a_units";
		vehicleClass="Modern_British";
		icon="iconManMG";
		nakedUniform="U_BasicBody";
		uniformClass="UK3CB_BAF_U_CombatUniform_MTP";
		backpack="TWC_Backpack_Modern_Automatic_Rifleman";
		linkedItems[]=
		{
        "UK3CB_BAF_V_Osprey_MG_B",
		"UK3CB_BAF_H_Mk7_Scrim_C",
		"ItemMap",
		"ItemCompass",
		"ItemWatch",
		"UK3CB_BAF_G_Tactical_Black",
		"ACRE_PRC343"
		};
		respawnLinkedItems[]=
		{
        "UK3CB_BAF_V_Osprey_MG_B",
		"UK3CB_BAF_H_Mk7_Scrim_C",
		"ItemMap",
		"ItemCompass",
		"ItemWatch",
		"ACRE_PRC343",
		"UK3CB_BAF_G_Tactical_Black"
		};
		weapons[]=
		{
		"Throw",
		"Put",
		"UK3CB_BAF_L110A2_ELCAN3D",
		"UK3CB_BAF_L131A1",
		"HAFM_LAW"
		};
		respawnweapons[]=
		{
		"Throw",
		"Put",	
		"UK3CB_BAF_L110A2_ELCAN3D",
		"UK3CB_BAF_L131A1",
		"HAFM_LAW"
		};
		magazines[]=
		{
		"UK3CB_BAF_17Rnd_9mm",
		"UK3CB_BAF_17Rnd_9mm",
		"UK3CB_BAF_17Rnd_9mm",
		"UK3CB_BAF_200Rnd_T",
		"CUP_HandGrenade_L109A2_HE",
		"CUP_HandGrenade_L109A2_HE",
		"SmokeShell",
		"SmokeShell",
		"SmokeShell"
		};
		Respawnmagazines[]=
		{
		"UK3CB_BAF_17Rnd_9mm",
		"UK3CB_BAF_17Rnd_9mm",
		"UK3CB_BAF_17Rnd_9mm",
		"UK3CB_BAF_200Rnd_T",
		"CUP_HandGrenade_L109A2_HE",
		"CUP_HandGrenade_L109A2_HE",
		"SmokeShell",
		"SmokeShell",
		"SmokeShell"
		};
		Items[]=
		{
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_morphine",
		"ACE_morphine",
		"ACE_epinephrine",
		"ACE_tourniquet",
		"ACE_EarPlugs",	
		"UK3CB_BAF_HMNVS"
		};
		respawntems[]=
		{
			"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_morphine",
		"ACE_morphine",
		"ACE_epinephrine",
		"ACE_tourniquet",
		"ACE_EarPlugs",	
		"UK3CB_BAF_HMNVS"			
		};
	};

	class Modern_British_2IC: B_Soldier_base_F
	{
		_generalMacro="Modern_British_2IC";
		scope=2;
		displayName="2IC(Modern)";
		faction="a_units";
		vehicleClass="Modern_British";
		icon="iconMan";
		nakedUniform="U_BasicBody";
		uniformClass="UK3CB_BAF_U_CombatUniform_MTP";
		backpack="TWC_Backpack_Modern_2IC";
		linkedItems[]=
		{
        "UK3CB_BAF_V_Osprey_Rifleman_C",
		"UK3CB_BAF_H_Mk7_Scrim_ESS_B",
		"ItemMap",
		"ItemCompass",
		"ItemWatch",
		"ACRE_PRC343",
		"UK3CB_BAF_G_Tactical_Black"
		};
		respawnLinkedItems[]=
		{
        "UK3CB_BAF_V_Osprey_Rifleman_C",
		"UK3CB_BAF_H_Mk7_Scrim_ESS_B",
		"ItemMap",
		"ItemCompass",
		"ItemWatch",
		"ACRE_PRC343",
		"UK3CB_BAF_G_Tactical_Black"
		};
		weapons[]=
		{
		"Throw",
		"Put",
		"ACE_Vector",
		"UK3CB_BAF_L85A2_RIS_AFG_ELCAN3D"
		};
		respawnweapons[]=
		{
		"Throw",
		"Put",
		"ACE_Vector",
		"UK3CB_BAF_L85A2_RIS_AFG_ELCAN3D"
		};
		magazines[]=
		{
		"UK3CB_BAF_30Rnd",
		"UK3CB_BAF_30Rnd",		
		"UK3CB_BAF_30Rnd",
		"UK3CB_BAF_30Rnd",
		"UK3CB_BAF_30Rnd_T",
		"UK3CB_BAF_30Rnd_T",
		"CUP_HandGrenade_L109A2_HE",
		"CUP_HandGrenade_L109A2_HE",
		"SmokeShell",
		"SmokeShell",
		"SmokeShell"
		};
		Respawnmagazines[]=
		{
		"UK3CB_BAF_30Rnd",
		"UK3CB_BAF_30Rnd",		
		"UK3CB_BAF_30Rnd",
		"UK3CB_BAF_30Rnd",
		"UK3CB_BAF_30Rnd_T",
		"UK3CB_BAF_30Rnd_T",
		"CUP_HandGrenade_L109A2_HE",
		"CUP_HandGrenade_L109A2_HE",
		"SmokeShell",
		"SmokeShell",
		"SmokeShell"
		};
		Items[]=
		{
			"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_morphine",
		"ACE_morphine",
		"ACE_epinephrine",
		"ACE_tourniquet",
		"ACE_EarPlugs",	
		"ACE_DAGR",		
		"UK3CB_BAF_HMNVS"
		};
		respawntems[]=
		{
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_morphine",
		"ACE_morphine",
		"ACE_EarPlugs",	
		"UK3CB_BAF_HMNVS"		
		};
	};

	class Modern_British_Machinegunner: B_Soldier_base_F
	{
		_generalMacro="Modern_British_Machinegunner";
		scope=2;
		displayName="Machine Gunner(Modern)";
		faction="a_units";
		vehicleClass="Modern_British";
		icon="iconMan";
		nakedUniform="U_BasicBody";
		uniformClass="UK3CB_BAF_U_CombatUniform_MTP";
		backpack="TWC_Backpack_Modern_Machine_Gunner";
		linkedItems[]=
		{
        "UK3CB_BAF_V_Osprey_MG_B",
		"UK3CB_BAF_H_Mk7_Scrim_D",
		"ItemMap",
		"ItemCompass",
		"ItemWatch",
		"UK3CB_BAF_G_Tactical_Black",
		"ACRE_PRC343"
		};
		respawnLinkedItems[]=
		{
        "UK3CB_BAF_V_Osprey_MG_B",
		"UK3CB_BAF_H_Mk7_Scrim_D",
		"ItemMap",
		"ItemCompass",
		"ItemWatch",
		"UK3CB_BAF_G_Tactical_Black",
		"ACRE_PRC343"
		};
		weapons[]=
		{
		"Throw",
		"Put",	
		"UK3CB_BAF_L7A2",
		"UK3CB_BAF_L131A1"
		};
		respawnweapons[]=
		{
		"Throw",
		"Put",	
		"UK3CB_BAF_L7A2",
		"UK3CB_BAF_L131A1"
		};
		magazines[]=
		{
		"UK3CB_BAF_17Rnd_9mm",
		"UK3CB_BAF_17Rnd_9mm",
		"UK3CB_BAF_17Rnd_9mm",
		"CUP_HandGrenade_L109A2_HE",
		"CUP_HandGrenade_L109A2_HE",
		"SmokeShell",
		"SmokeShell",
		"SmokeShell"
		};
		Respawnmagazines[]=
		{
		"UK3CB_BAF_17Rnd_9mm",
		"UK3CB_BAF_17Rnd_9mm",
		"UK3CB_BAF_17Rnd_9mm",
		"CUP_HandGrenade_L109A2_HE",
		"CUP_HandGrenade_L109A2_HE",
		"SmokeShell",
		"SmokeShell",
		"SmokeShell"
		};
		Items[]=
		{
			"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_morphine",
		"ACE_morphine",
		"ACE_epinephrine",
		"ACE_tourniquet",
		"ACE_EarPlugs",	
		"UK3CB_BAF_HMNVS"
		};
		respawntems[]=
		{
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_morphine",
		"ACE_morphine",
		"ACE_EarPlugs",	
		"UK3CB_BAF_HMNVS"		
		};
	};

	class Modern_British_Marksman: B_Soldier_base_F
	{
		_generalMacro="Modern_British_Marksman";
		scope=2;
		displayName="Marksman(Modern)";
		faction="a_units";
		vehicleClass="Modern_British";
		icon="iconMan";
		nakedUniform="U_BasicBody";
		uniformClass="UK3CB_BAF_U_CombatUniform_MTP";
		backpack="TWC_Backpack_Modern_Marksman";
		linkedItems[]=
		{
        "UK3CB_BAF_V_Osprey_Marksman_A",
		"UK3CB_BAF_H_Mk7_Scrim_E",
		"ItemMap",
		"ItemCompass",
		"ItemWatch",
		"UK3CB_BAF_G_Tactical_Black",
		"ACRE_PRC343"
		};
		respawnLinkedItems[]=
		{
        "UK3CB_BAF_V_Osprey_Marksman_A",
		"UK3CB_BAF_H_Mk7_Scrim_E",
		"ItemMap",
		"ItemCompass",
		"ItemWatch",
		"ACRE_PRC343",
		"UK3CB_BAF_G_Tactical_Black"
		};
		weapons[]=
		{
		"Throw",
		"Put",
		"ACE_Vector",
		"UK3CB_BAF_L129A1_Grippod_TA648",
		"UK3CB_BAF_NLAW_Launcher"
		};
		respawnweapons[]=
		{
		"Throw",
		"Put",
		"ACE_Vector",
		"UK3CB_BAF_L129A1_Grippod_TA648",
		"UK3CB_BAF_NLAW_Launcher"
		};
		magazines[]=
		{
		"CUP_HandGrenade_L109A2_HE",
		"CUP_HandGrenade_L109A2_HE",
		"SmokeShell",
		"SmokeShell",
		"SmokeShell"
		};
		Respawnmagazines[]=
		{
		"CUP_HandGrenade_L109A2_HE",
		"CUP_HandGrenade_L109A2_HE",
		"SmokeShell",
		"SmokeShell",
		"SmokeShell"
		};
		Items[]=
		{
			"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_morphine",
		"ACE_morphine",
		"ACE_epinephrine",
		"ACE_tourniquet",
		"ACE_EarPlugs",	
		"UK3CB_BAF_HMNVS"
		};
		respawntems[]=
		{
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_morphine",
		"ACE_morphine",
		"ACE_EarPlugs",	
		"UK3CB_BAF_HMNVS"			
		};		
	};
	class Modern_British_Platoon_Commander: B_Soldier_base_F
	{
		_generalMacro="Modern_British_Squadleader";
		scope=2;
		displayName="Platoon Commander(Modern)";
		faction="a_units";
		vehicleClass="Modern_British";
		icon="iconManLeader";
		nakedUniform="U_BasicBody";
		uniformClass="UK3CB_BAF_U_CombatUniform_MTP";
		backpack="TWC_Backpack_Modern_Platoon_Command";
		linkedItems[]=
		{
        "UK3CB_BAF_V_Osprey_Holster",
		"UK3CB_BAF_H_Mk7_Camo_D",
		"ItemMap",
		"ItemcTab",
		"ItemCompass",
		"ACRE_PRC343",
		"ItemWatch",
		"UK3CB_BAF_G_Tactical_Black"
		};
		respawnLinkedItems[]=
		{
        "UK3CB_BAF_V_Osprey_Holster",
		"ItemMap",
		"ItemcTab",
		"ItemCompass",
		"ItemWatch",
		"ACRE_PRC343",
		"UK3CB_BAF_G_Tactical_Black"
		};
		weapons[]=
		{
		"Throw",
		"Put",	
		"Binocular",
		"UK3CB_BAF_L85A2_RIS_AFG_ELCAN3D",
		"UK3CB_BAF_L131A1"
		};
		respawnweapons[]=
		{
		"Throw",
		"Put",
		"Binocular",
		"UK3CB_BAF_L85A2_RIS_AFG_ELCAN3D",
		"UK3CB_BAF_L131A1"
		};
		magazines[]=
		{
		"UK3CB_BAF_17Rnd_9mm",
		"UK3CB_BAF_17Rnd_9mm",
		"UK3CB_BAF_17Rnd_9mm",
		"UK3CB_BAF_30Rnd",
		"UK3CB_BAF_30Rnd",
		"UK3CB_BAF_30Rnd",
		"UK3CB_BAF_30Rnd",
		"UK3CB_BAF_30Rnd_T",
		"UK3CB_BAF_30Rnd_T",
		"CUP_HandGrenade_L109A2_HE",
		"CUP_HandGrenade_L109A2_HE"
		};
		Respawnmagazines[]=
		{
		"UK3CB_BAF_17Rnd_9mm",
		"UK3CB_BAF_17Rnd_9mm",
		"UK3CB_BAF_17Rnd_9mm",
		"UK3CB_BAF_30Rnd",
		"UK3CB_BAF_30Rnd",
		"UK3CB_BAF_30Rnd",
		"UK3CB_BAF_30Rnd",
		"UK3CB_BAF_30Rnd_T",
		"UK3CB_BAF_30Rnd_T",
		"CUP_HandGrenade_L109A2_HE",
		"CUP_HandGrenade_L109A2_HE"
		};
		Items[]=
		{
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_morphine",
		"ACE_morphine",
		"ACE_epinephrine",
		"ACE_tourniquet",
		"ACE_Flashlight_KSF1",
		"ACE_IR_Strobe_Item",
	    "ACE_MapTools",
		"UK3CB_BAF_HMNVS",
		"ACE_DAGR",
		"ACE_EarPlugs"	

		};
		respawntems[]=
		{
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_morphine",
		"ACE_morphine",
		"ACE_Flashlight_KSF1",
		"ACE_IR_Strobe_Item",
	    "ACE_MapTools",
		"UK3CB_BAF_HMNVS"		
		};
	};
	class Modern_British_Platoon_Sergeant: B_Soldier_base_F
	{
		_generalMacro="Modern_British_Squadleader";
		scope=2;
		displayName="Platoon Sergeant(Modern)";
		faction="a_units";
		vehicleClass="Modern_British";
		icon="iconManLeader";
		nakedUniform="U_BasicBody";
		uniformClass="UK3CB_BAF_U_CombatUniform_MTP";
		backpack="TWC_Backpack_Modern_Platoon_Sergeant";
		linkedItems[]=
		{
        "UK3CB_BAF_V_Osprey_Holster",
		"UK3CB_BAF_H_Mk7_Camo_D",
		"ItemMap",
		"ItemcTab",
		"ItemCompass",
		"ACRE_PRC343",
		"ItemWatch",
		"UK3CB_BAF_G_Tactical_Black"
		};
		respawnLinkedItems[]=
		{
        "UK3CB_BAF_V_Osprey_Holster",
		"ItemMap",
		"ItemcTab",
		"ItemCompass",
		"ItemWatch",
		"ACRE_PRC343",
		"UK3CB_BAF_G_Tactical_Black"
		};
		weapons[]=
		{
		"Throw",
		"Put",
		"Binocular",
		"UK3CB_BAF_L85A2_RIS_AFG_ELCAN3D",
		"UK3CB_BAF_L131A1"
		};
		respawnweapons[]=
		{
		"Throw",
		"Put",
		"Binocular",
		"UK3CB_BAF_L85A2_RIS_AFG_ELCAN3D",
		"UK3CB_BAF_L131A1"
		};
		magazines[]=
		{
		"UK3CB_BAF_17Rnd_9mm",
		"UK3CB_BAF_17Rnd_9mm",
		"UK3CB_BAF_17Rnd_9mm",
		"UK3CB_BAF_30Rnd",
		"UK3CB_BAF_30Rnd",
		"UK3CB_BAF_30Rnd",
		"UK3CB_BAF_30Rnd",
		"UK3CB_BAF_30Rnd_T",
		"UK3CB_BAF_30Rnd_T",
		"CUP_HandGrenade_L109A2_HE",
		"CUP_HandGrenade_L109A2_HE"
		};
		Respawnmagazines[]=
		{
		"UK3CB_BAF_17Rnd_9mm",
		"UK3CB_BAF_17Rnd_9mm",
		"UK3CB_BAF_17Rnd_9mm",
		"UK3CB_BAF_30Rnd",
		"UK3CB_BAF_30Rnd",
		"UK3CB_BAF_30Rnd",
		"UK3CB_BAF_30Rnd",
		"UK3CB_BAF_30Rnd_T",
		"UK3CB_BAF_30Rnd_T",
		"CUP_HandGrenade_L109A2_HE",
		"CUP_HandGrenade_L109A2_HE"
		};
		Items[]=
		{
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_morphine",
		"ACE_morphine",
		"ACE_Flashlight_KSF1",
		"ACE_IR_Strobe_Item",
	    "ACE_MapTools",
		"UK3CB_BAF_HMNVS",
		"ACE_DAGR",
		"ACE_EarPlugs"
		};
		respawntems[]=
		{
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_morphine",
		"ACE_morphine",
		"ACE_Flashlight_KSF1",
		"ACE_IR_Strobe_Item",
	    "ACE_MapTools",
		"UK3CB_BAF_HMNVS"		
		};
	};
	class Modern_British_Medic: B_Soldier_base_F
	{
		_generalMacro="Modern_British_Marksman";
		scope=2;
		displayName="Medic(Modern)";
		faction="a_units";
		vehicleClass="Modern_British";
		icon="iconMan";
		nakedUniform="U_BasicBody";
		uniformClass="UK3CB_BAF_U_CombatUniform_MTP";
		backpack="TWC_Backpack_Modern_Medic";
		linkedItems[]=
		{
        "UK3CB_BAF_V_Osprey_Medic_D",
		"UK3CB_BAF_H_Mk7_Camo_CESS_D",
		"ItemMap",
		"ItemCompass",
		"ItemWatch",
		"UK3CB_BAF_G_Tactical_Black",
		"ACRE_PRC343"
		};
		respawnLinkedItems[]=
		{
        "UK3CB_BAF_V_Osprey_Medic_D",
		"UK3CB_BAF_H_Mk7_Camo_CESS_D",
		"ItemMap",
		"ItemCompass",
		"ItemWatch",
		"ACRE_PRC343",
		"UK3CB_BAF_G_Tactical_Black"
		};
		weapons[]=
		{
		"Throw",
		"Put",
		"UK3CB_BAF_L85A2_RIS_AFG_ELCAN3D"
		};
		respawnweapons[]=
		{
		"Throw",
		"Put",
		"UK3CB_BAF_L85A2_RIS_AFG_ELCAN3D"
		};
		magazines[]=
		{
		"UK3CB_BAF_30Rnd",
		"UK3CB_BAF_30Rnd",
		"UK3CB_BAF_30Rnd",
		"SmokeShell",
		"SmokeShell",
		"SmokeShell",
		"SmokeShell",
		"SmokeShell"
		};
		Respawnmagazines[]=
		{
		"UK3CB_BAF_30Rnd",
		"UK3CB_BAF_30Rnd",
		"UK3CB_BAF_30Rnd",
		"SmokeShell",
		"SmokeShell",
		"SmokeShell",
		"SmokeShell",
		"SmokeShell"
		};
		Items[]=
		{
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_morphine",
		"ACE_morphine",
		"ACE_epinephrine",
		"ACE_tourniquet",
		"ACE_EarPlugs",	
		"UK3CB_BAF_HMNVS"
		};
		respawntems[]=
		{
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_morphine",
		"ACE_morphine",
		"ACE_EarPlugs",	
		"UK3CB_BAF_HMNVS"			
		};		
	};
	class Modern_HeloPilot: B_Soldier_base_F
	{
		_generalMacro="Modern_HelicopterPilot";
		scope=2;
		displayName="Helicopter Pilot(Modern)";
		faction="a_units";
		vehicleClass="Modern_British";
		icon="iconMan";
		nakedUniform="U_BasicBody";
		uniformClass="UK3CB_BAF_U_CombatUniform_MTP";
		backpack="TWC_Backpack_Cold_War_Pilot";
		linkedItems[]=
		{
		"UK3CB_BAF_H_PilotHelmetHeli_A",
		"ItemMap",
		"ItemCompass",
		"ItemWatch",
		"ACE_microDAGR_Item"
		};
		respawnLinkedItems[]=
		{
		"UK3CB_BAF_H_PilotHelmetHeli_A",
		"ItemMap",		
		"ItemCompass",
		"ItemWatch",
		"ACE_microDAGR_Item"
		};
		weapons[]=
		{
		"Throw",
		"Put",
		"UK3CB_BAF_L22A2_SUSAT3D"
		};
		respawnweapons[]=
		{
		"Throw",
		"Put",
		"UK3CB_BAF_L22A2_SUSAT3D"
		};
		magazines[]=
		{
		"UK3CB_BAF_30Rnd",
		"UK3CB_BAF_30Rnd",
		"SmokeShell",
		"SmokeShell"
		};
		Respawnmagazines[]=
		{
		"UK3CB_BAF_30Rnd",
		"UK3CB_BAF_30Rnd",
		"SmokeShell",
		"SmokeShell"
		};
		Items[]=
		{
			"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_morphine",
		"ACE_morphine",
		"ACE_epinephrine",
		"ACE_tourniquet",
		"ACE_EarPlugs",	
		"UK3CB_BAF_HMNVS"
		};
		respawntems[]=
		{
		"ACE_EarPlugs",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_morphine",
		"ACE_morphine"
		};		
	};
	class Modern_JetPilot: B_Soldier_base_F
	{
		_generalMacro="Modern_JetPilot";
		scope=2;
		displayName="Jet Pilot(Modern)";
		faction="a_units";
		vehicleClass="Modern_British";
		icon="iconMan";
		nakedUniform="U_BasicBody";
		uniformClass="UK3CB_BAF_U_HeliPilotCoveralls_RAF";
		backpack="TWC_Backpack_Cold_War_Pilot";
		linkedItems[]=
		{
		"RHS_jetpilot_usaf",
		"ItemMap",
		"ItemCompass",
		"ItemWatch",
		"ACE_microDAGR_Item"
		};
		respawnLinkedItems[]=
		{
		"RHS_jetpilot_usaf",
		"ItemMap",		
		"ItemCompass",
		"ItemWatch",
		"ACE_microDAGR_Item"
		};
		weapons[]=
		{
		"Throw",
		"Put",
		"UK3CB_BAF_L131A1"
		};
		respawnweapons[]=
		{
		"Throw",
		"Put",
		"UK3CB_BAF_L131A1"
		};
		magazines[]=
		{
		"UK3CB_BAF_17Rnd_9mm",
		"UK3CB_BAF_17Rnd_9mm",
		"SmokeShell",
		"SmokeShell"
		};
		Respawnmagazines[]=
		{
		"UK3CB_BAF_17Rnd_9mm",
		"UK3CB_BAF_17Rnd_9mm",	
		"SmokeShell",
		"SmokeShell"
		};
		Items[]=
		{
			"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_morphine",
		"ACE_morphine",
		"ACE_epinephrine",
		"ACE_tourniquet",
		"ACE_EarPlugs",	
		"UK3CB_BAF_HMNVS"
		};
		respawntems[]=
		{
		"ACE_EarPlugs",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_morphine",
		"ACE_morphine",
		"ACE_morphine",
		"ACE_morphine"
		};		
	};
	class Modern_British_MortarGunner: B_Soldier_base_F
	{
		_generalMacro="Modern_British_MortarGunner";
		scope=2;
		displayName="Mortar Gunner(Modern)";
		faction="a_units";
		vehicleClass="Modern_British";
		icon="iconMan";
		nakedUniform="U_BasicBody";
		uniformClass="UK3CB_BAF_U_CombatUniform_MTP";
		backpack="TWC_Backpack_Modern_MortarGunner";
		linkedItems[]=
		{
        "UK3CB_BAF_V_Osprey_Rifleman_B",
		"UK3CB_BAF_H_Mk7_Scrim_B",
		"ItemMap",
		"ItemCompass",
		"ItemWatch",
		"ACRE_PRC343",
		"UK3CB_BAF_G_Tactical_Black"
		};
		respawnLinkedItems[]=
		{
        "UK3CB_BAF_V_Osprey_Rifleman_B",
		"UK3CB_BAF_H_Mk7_Scrim_B",
		"ItemMap",
		"ItemCompass",
		"ItemWatch",
		"UK3CB_BAF_G_Tactical_Black",
		"ACRE_PRC343"
		};
		weapons[]=
		{
		"Throw",
		"Put",	
		"UK3CB_BAF_L85A2",
		"UK3CB_BAF_L16"
		};
		respawnweapons[]=
		{
		"Throw",
		"Put",	
		"UK3CB_BAF_L85A2",
		"UK3CB_BAF_L16"
		};
		magazines[]=
		{
		"UK3CB_BAF_30Rnd",
		"UK3CB_BAF_30Rnd_T",
		"UK3CB_BAF_30Rnd_T",
		"CUP_HandGrenade_L109A2_HE",
		"CUP_HandGrenade_L109A2_HE",
		"SmokeShell",
		"SmokeShell",
		"SmokeShell"
		};
		Respawnmagazines[]=
		{
		"UK3CB_BAF_30Rnd",
		"UK3CB_BAF_30Rnd_T",
		"UK3CB_BAF_30Rnd_T",
		"CUP_HandGrenade_L109A2_HE",
		"CUP_HandGrenade_L109A2_HE",
		"SmokeShell",
		"SmokeShell",
		"SmokeShell"
		};
		Items[]=
		{
			"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_morphine",
		"ACE_morphine",
		"ACE_epinephrine",
		"ACE_tourniquet",
		"ACE_EarPlugs",	
		"UK3CB_BAF_HMNVS"
		};
		respawntems[]=
		{
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_morphine",
		"ACE_morphine",
		"ACE_EarPlugs",	
		"UK3CB_BAF_HMNVS"		
		};		
	};
	class Modern_British_MortarAssistant: B_Soldier_base_F
	{
		_generalMacro="Modern_British_MortarAssistant";
		scope=2;
		displayName="Mortar Assistant(Modern)";
		faction="a_units";
		vehicleClass="Modern_British";
		icon="iconMan";
		nakedUniform="U_BasicBody";
		uniformClass="UK3CB_BAF_U_CombatUniform_MTP";
		backpack="TWC_Backpack_Modern_MortarAssistant";
		linkedItems[]=
		{
        "UK3CB_BAF_V_Osprey_Rifleman_B",
		"UK3CB_BAF_H_Mk7_Scrim_B",
		"ItemMap",
		"ItemCompass",
		"ItemWatch",
		"ACRE_PRC343",
		"UK3CB_BAF_G_Tactical_Black"
		};
		respawnLinkedItems[]=
		{
        "UK3CB_BAF_V_Osprey_Rifleman_B",
		"UK3CB_BAF_H_Mk7_Scrim_B",
		"ItemMap",
		"ItemCompass",
		"ItemWatch",
		"UK3CB_BAF_G_Tactical_Black",
		"ACRE_PRC343"
		};
		weapons[]=
		{
		"Throw",
		"Put",	
		"UK3CB_BAF_L85A2",
		"UK3CB_BAF_L16_Tripod"
		};
		respawnweapons[]=
		{
		"Throw",
		"Put",	
		"UK3CB_BAF_L85A2",
		"UK3CB_BAF_L16_Tripod"
		};
		magazines[]=
		{
		"UK3CB_BAF_30Rnd",
		"UK3CB_BAF_30Rnd_T",
		"UK3CB_BAF_30Rnd_T",
		"CUP_HandGrenade_L109A2_HE",
		"CUP_HandGrenade_L109A2_HE",
		"SmokeShell",
		"SmokeShell",
		"SmokeShell"
		};
		Respawnmagazines[]=
		{
		"UK3CB_BAF_30Rnd",
		"UK3CB_BAF_30Rnd_T",
		"UK3CB_BAF_30Rnd_T",
		"CUP_HandGrenade_L109A2_HE",
		"CUP_HandGrenade_L109A2_HE",
		"SmokeShell",
		"SmokeShell",
		"SmokeShell"
		};
		Items[]=
		{
			"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_morphine",
		"ACE_morphine",
		"ACE_epinephrine",
		"ACE_tourniquet",
		"ACE_EarPlugs",	
		"UK3CB_BAF_HMNVS"
		};
		respawntems[]=
		{
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_morphine",
		"ACE_morphine",
		"ACE_EarPlugs",	
		"UK3CB_BAF_HMNVS"		
		};		
	};
	class Pilot_British: B_Soldier_base_F
	{
		_generalMacro="Helicopter Pilot";
		scope=2;
		displayName="Wildcat Pilot(Modern)";
		faction="a_units";
		vehicleClass="Modern_British";
		icon="iconMan";
		nakedUniform="U_BasicBody";
		uniformClass="UK3CB_BAF_U_CombatUniform_MTP";
		backpack="TWC_Backpack_Modern_Vehiclecommander";
		linkedItems[]=
		{
        "UK3CB_BAF_V_Pilot_A",
		"UK3CB_BAF_H_PilotHelmetHeli_A",
		"ItemMap",
		"ItemCompass",
		"ItemWatch",
		"ACRE_PRC343",
		"UK3CB_BAF_G_Tactical_Black",
		"ACE_microDAGR_Item"
		};
		respawnLinkedItems[]=
		{
        "UK3CB_BAF_V_Pilot_A",
		"UK3CB_BAF_H_PilotHelmetHeli_A",
		"ItemMap",
		"ItemCompass",
		"ItemWatch",
		"ACRE_PRC343",
		"UK3CB_BAF_G_Tactical_Black",
		"ACE_microDAGR_Item"
		};
		weapons[]=
		{
		"Throw",
		"Put",
		"Binocular",
		"UK3CB_BAF_L22A2"
		};
		respawnweapons[]=
		{
		"Throw",
		"Put",
		"Binocular",
		"UK3CB_BAF_L22A2"
		};
		magazines[]=
		{
		"UK3CB_BAF_30Rnd",
		"UK3CB_BAF_30Rnd",
		"smokeshell",
		"smokeshell"
		};
		Respawnmagazines[]=
		{
		"UK3CB_BAF_30Rnd",
		"UK3CB_BAF_30Rnd",
		"smokeshell",
		"smokeshell"
		};
		Items[]=
		{
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_morphine",
		"ACE_morphine",
		"ACE_Flashlight_KSF1",
		"ACE_IR_Strobe_Item",
	    "ACE_MapTools",
		"UK3CB_BAF_HMNVS",
		"ACE_EarPlugs",
		"ItemcTab",
		"ACE_DAGR"
		};
		respawntems[]=
		{
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_morphine",
		"ACE_morphine",
		"ACE_Flashlight_KSF1",
		"ACE_IR_Strobe_Item",
	    "ACE_MapTools",
		"UK3CB_BAF_HMNVS",
		"ItemcTab",
		"ACE_DAGR"
		};
	};
