	class Russian_Squadleader:O_Soldier_base_F
	{
		_generalMacro="Russian_Squadleader";
		scope=2;
		displayName="Section Leader";
		faction="a_units";
		vehicleClass="Russian";
		icon="iconMan";
		nakedUniform="U_BasicBody";
		uniformClass="rhs_uniform_flora";
		backpack="TWC_Backpack_USSR_Sectionlead";
		linkedItems[]=
		{
        "rhs_6b23_6sh92_headset_mapcase",
		"ItemMap",
		"ItemCompass",
		"ItemWatch",
		"rhs_6b26_ess",
		"ACRE_PRC343"
		};
		respawnLinkedItems[]=
		{
        "rhs_6b23_6sh92_headset_mapcase",
		"ItemMap",
		"ItemCompass",
		"ItemWatch",
		"rhs_6b26_ess",
		"ACRE_PRC343"
		};
		weapons[]=
		{
		"Throw",
		"Put",
		"ACE_Vector",
		"USSR_AK74_1p29",
		"rhs_weap_makarov_pmm"
		};
		respawnweapons[]=
		{
		"Throw",
		"Put",
		"ACE_Vector",
		"USSR_AK74_1p29",
		"rhs_weap_makarov_pmm"
		};
		magazines[]=
		{
		"rhs_mag_9x18_12_57N181S",
		"rhs_mag_9x18_12_57N181S",
		"rhs_mag_9x18_12_57N181S",
		"rhs_30Rnd_545x39_7N10_AK",
		"rhs_30Rnd_545x39_7N10_AK",
		"rhs_30Rnd_545x39_7N10_AK",
		"rhs_30Rnd_545x39_7N10_AK",
		"rhs_30Rnd_545x39_7N10_AK",
		"rhs_30Rnd_545x39_7N10_AK",
		"rhs_30Rnd_545x39_7N10_AK",
		"rhs_30Rnd_545x39_7N10_AK",
		"rhs_mag_rgd5",
		"rhs_mag_rgd5",
		"SmokeShell",
		"SmokeShell",
		"SmokeShell"
		};
		Respawnmagazines[]=
		{
		"rhs_mag_9x18_12_57N181S",
		"rhs_mag_9x18_12_57N181S",
		"rhs_mag_9x18_12_57N181S",
		"rhs_30Rnd_545x39_7N10_AK",
		"rhs_30Rnd_545x39_7N10_AK",
		"rhs_30Rnd_545x39_7N10_AK",
		"rhs_30Rnd_545x39_7N10_AK",
		"rhs_30Rnd_545x39_7N10_AK",
		"rhs_30Rnd_545x39_7N10_AK",
		"rhs_30Rnd_545x39_7N10_AK",
		"rhs_30Rnd_545x39_7N10_AK",
		"rhs_mag_rgd5",
		"rhs_mag_rgd5",
		"SmokeShell",
		"SmokeShell",
		"SmokeShell"
		};
		Items[]=
		{
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_morphine",
		"ACE_morphine",
		"ACE_EarPlugs"
		};
		respawntems[]=
		{
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_morphine",
		"ACE_morphine",
		"ACE_EarPlugs"	
		};		
	};
	class Russian_Rifleman:O_Soldier_base_F
	{
		_generalMacro="Russian_Rifleman";
		scope=2;
		displayName="Rifleman";
		faction="a_units";
		vehicleClass="Russian";
		icon="iconMan";
		nakedUniform="U_BasicBody";
		uniformClass="rhs_uniform_flora";
		backpack="TWC_Backpack_USSR_Rifleman";
		linkedItems[]=
		{
        "rhs_6b23_6sh92",
		"BAF_Soldier_1_Headgear_W_DG1",
		"ItemMap",
		"ItemCompass",
		"ItemWatch",
		"rhs_6b26",
		"ACRE_PRC343"
		};
		respawnLinkedItems[]=
		{
        "rhs_6b23_6sh92_headset_mapcase",
		"ItemMap",
		"ItemCompass",
		"ItemWatch",
		"rhs_6b26",
		"ACRE_PRC343"
		};
		weapons[]=
		{
		"Throw",
		"Put",
		"rhs_weap_ak74m_dtk",
		"rhs_weap_makarov_pmm"
		};
		respawnweapons[]=
		{
		"Throw",
		"Put",	
		"rhs_weap_ak74m_dtk",
		"rhs_weap_makarov_pmm"
		};
		magazines[]=
		{
		"rhs_mag_9x18_12_57N181S",
		"rhs_mag_9x18_12_57N181S",
		"rhs_mag_9x18_12_57N181S",
		"rhs_30Rnd_545x39_7N10_AK",
		"rhs_30Rnd_545x39_7N10_AK",
		"rhs_mag_rgd5",
		"rhs_mag_rgd5",
		"SmokeShell",
		"SmokeShell",
		"SmokeShell"
		};
		Respawnmagazines[]=
		{
		"rhs_mag_9x18_12_57N181S",
		"rhs_mag_9x18_12_57N181S",
		"rhs_mag_9x18_12_57N181S",
		"rhs_30Rnd_545x39_7N10_AK",
		"rhs_30Rnd_545x39_7N10_AK",
		"rhs_mag_rgd5",
		"rhs_mag_rgd5",
		"SmokeShell",
		"SmokeShell",
		"SmokeShell"
		};
		Items[]=
		{
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_morphine",
		"ACE_morphine",
		"ACE_EarPlugs"
		};
		respawntems[]=
		{
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_morphine",
		"ACE_morphine",
		"ACE_EarPlugs"	
		};		
	};
	class Russian_Grenadier:O_Soldier_base_F
	{
		_generalMacro="Russian_Grenadier";
		scope=2;
		displayName="Grenadier";
		faction="a_units";
		vehicleClass="Russian";
		icon="iconMan";
		nakedUniform="U_BasicBody";
		uniformClass="rhs_uniform_flora";
		backpack="TWC_Backpack_USSR_Grenadier";
		linkedItems[]=
		{
        "rhs_6b23_6sh92",
		"BAF_Soldier_1_Headgear_W_DG1",
		"ItemMap",
		"ItemCompass",
		"ItemWatch",
		"rhs_6b26",
		"ACRE_PRC343"
		};
		respawnLinkedItems[]=
		{
        "rhs_6b23_6sh92_headset_mapcase",
		"ItemMap",
		"ItemCompass",
		"ItemWatch",
		"rhs_6b26",
		"ACRE_PRC343"
		};
		weapons[]=
		{
		"Throw",
		"Put",
		"rhs_weap_ak74m_dtk",
		"rhs_weap_rpg7",
		"rhs_weap_makarov_pmm"
		};
		respawnweapons[]=
		{
		"Throw",
		"Put",	
		"rhs_weap_ak74m_dtk",
		"rhs_weap_rpg7",
		"rhs_weap_makarov_pmm"
		};
		magazines[]=
		{
		"rhs_mag_9x18_12_57N181S",
		"rhs_mag_9x18_12_57N181S",
		"rhs_mag_9x18_12_57N181S",
		"rhs_30Rnd_545x39_7N10_AK",
		"rhs_30Rnd_545x39_7N10_AK",
		"rhs_30Rnd_545x39_7N10_AK",
		"rhs_30Rnd_545x39_7N10_AK",
		"rhs_mag_rgd5",
		"rhs_mag_rgd5",
		"SmokeShell",
		"SmokeShell",
		"SmokeShell"
		};
		Respawnmagazines[]=
		{
		"rhs_mag_9x18_12_57N181S",
		"rhs_mag_9x18_12_57N181S",
		"rhs_mag_9x18_12_57N181S",
		"rhs_30Rnd_545x39_7N10_AK",
		"rhs_30Rnd_545x39_7N10_AK",
		"rhs_30Rnd_545x39_7N10_AK",
		"rhs_30Rnd_545x39_7N10_AK",
		"rhs_mag_rgd5",
		"rhs_mag_rgd5",
		"SmokeShell",
		"SmokeShell",
		"SmokeShell"
		};
		Items[]=
		{
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_morphine",
		"ACE_morphine",
		"ACE_EarPlugs"
		};
		respawntems[]=
		{
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_morphine",
		"ACE_morphine",
		"ACE_EarPlugs"	
		};		
	};
	class Russian_Seniorrifleman:O_Soldier_base_F
	{
		_generalMacro="Russian_Seniorrifleman";
		scope=2;
		displayName="Senior Rifleman";
		faction="a_units";
		vehicleClass="Russian";
		icon="iconMan";
		nakedUniform="U_BasicBody";
		uniformClass="rhs_uniform_flora";
		backpack="TWC_Backpack_USSR_Seniorrifleman";
		linkedItems[]=
		{
        "rhs_6b23_6sh92",
		"BAF_Soldier_1_Headgear_W_DG1",
		"ItemMap",
		"ItemCompass",
		"ItemWatch",
		"rhs_6b26",
		"ACRE_PRC343"
		};
		respawnLinkedItems[]=
		{
        "rhs_6b23_6sh92_headset_mapcase",
		"ItemMap",
		"ItemCompass",
		"ItemWatch",
		"rhs_6b26",
		"ACRE_PRC343"
		};
		weapons[]=
		{
		"Throw",
		"Put",
		"ACE_Vector",
		"USSR_AK74_1p29",
		"rhs_weap_makarov_pmm"
		};
		respawnweapons[]=
		{
		"Throw",
		"Put",
		"ACE_Vector",
		"USSR_AK74_1p29",
		"rhs_weap_makarov_pmm"
		};
		magazines[]=
		{
		"rhs_mag_9x18_12_57N181S",
		"rhs_mag_9x18_12_57N181S",
		"rhs_mag_9x18_12_57N181S",
		"rhs_30Rnd_545x39_7N10_AK",
		"rhs_30Rnd_545x39_7N10_AK",
		"rhs_mag_rgd5",
		"rhs_mag_rgd5",
		"SmokeShell",
		"SmokeShell",
		"SmokeShell"
		};
		Respawnmagazines[]=
		{
		"rhs_mag_9x18_12_57N181S",
		"rhs_mag_9x18_12_57N181S",
		"rhs_mag_9x18_12_57N181S",
		"rhs_30Rnd_545x39_7N10_AK",
		"rhs_30Rnd_545x39_7N10_AK",
		"rhs_mag_rgd5",
		"rhs_mag_rgd5",
		"SmokeShell",
		"SmokeShell",
		"SmokeShell"
		};
		Items[]=
		{
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_morphine",
		"ACE_morphine",
		"ACE_EarPlugs"
		};
		respawntems[]=
		{
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_morphine",
		"ACE_morphine",
		"ACE_EarPlugs"	
		};		
	};
	class Russian_Grenadierassistant:O_Soldier_base_F
	{
		_generalMacro="Russian_Grenadierassistant";
		scope=2;
		displayName="Grenadier Assistant";
		faction="a_units";
		vehicleClass="Russian";
		icon="iconMan";
		nakedUniform="U_BasicBody";
		uniformClass="rhs_uniform_flora";
		backpack="TWC_Backpack_USSR_Grenadierassistant";
		linkedItems[]=
		{
        "rhs_6b23_6sh92",
		"BAF_Soldier_1_Headgear_W_DG1",
		"ItemMap",
		"ItemCompass",
		"ItemWatch",
		"rhs_6b26",
		"ACRE_PRC343"
		};
		respawnLinkedItems[]=
		{
        "rhs_6b23_6sh92_headset_mapcase",
		"ItemMap",
		"ItemCompass",
		"ItemWatch",
		"rhs_6b26",
		"ACRE_PRC343"
		};
		weapons[]=
		{
		"Throw",
		"Put",	
		"rhs_weap_ak74m_dtk",
		"rhs_weap_makarov_pmm"
		};
		respawnweapons[]=
		{
		"Throw",
		"Put",	
		"rhs_weap_ak74m_dtk",
		"rhs_weap_makarov_pmm"
		};
		magazines[]=
		{
		"rhs_mag_9x18_12_57N181S",
		"rhs_mag_9x18_12_57N181S",
		"rhs_mag_9x18_12_57N181S",
		"rhs_30Rnd_545x39_7N10_AK",
		"rhs_30Rnd_545x39_7N10_AK",
		"rhs_30Rnd_545x39_7N10_AK",
		"rhs_30Rnd_545x39_7N10_AK",
		"rhs_mag_rgd5",
		"rhs_mag_rgd5",
		"SmokeShell",
		"SmokeShell",
		"SmokeShell"
		};
		Respawnmagazines[]=
		{
		"rhs_mag_9x18_12_57N181S",
		"rhs_mag_9x18_12_57N181S",
		"rhs_mag_9x18_12_57N181S",
		"rhs_30Rnd_545x39_7N10_AK",
		"rhs_30Rnd_545x39_7N10_AK",
		"rhs_30Rnd_545x39_7N10_AK",
		"rhs_30Rnd_545x39_7N10_AK",
		"rhs_mag_rgd5",
		"rhs_mag_rgd5",
		"SmokeShell",
		"SmokeShell",
		"SmokeShell"
		};
		Items[]=
		{
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_morphine",
		"ACE_morphine",
		"ACE_EarPlugs"
		};
		respawntems[]=
		{
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_morphine",
		"ACE_morphine",
		"ACE_EarPlugs"	
		};		
	};
	class Russian_Automaticrifleman:O_Soldier_base_F
	{
		_generalMacro="Russian_Automaticrifleman";
		scope=2;
		displayName="Automatic Rifleman";
		faction="a_units";
		vehicleClass="Russian";
		icon="iconMan";
		nakedUniform="U_BasicBody";
		uniformClass="rhs_uniform_flora";
		backpack="TWC_Backpack_USSR_Automaticrifleman";
		linkedItems[]=
		{
        "rhs_6b23_6sh92",
		"BAF_Soldier_1_Headgear_W_DG1",
		"ItemMap",
		"ItemCompass",
		"ItemWatch",
		"rhs_6b26",
		"ACRE_PRC343"
		};
		respawnLinkedItems[]=
		{
        "rhs_6b23_6sh92_headset_mapcase",
		"ItemMap",
		"ItemCompass",
		"ItemWatch",
		"rhs_6b26",
		"ACRE_PRC343"
		};
		weapons[]=
		{
		"Throw",
		"Put",	
		"rhs_weap_pkm",
		"rhs_weap_makarov_pmm"
		};
		respawnweapons[]=
		{
		"Throw",
		"Put",	
		"rhs_weap_pkm",
		"rhs_weap_makarov_pmm"
		};
		magazines[]=
		{
		"rhs_mag_9x18_12_57N181S",
		"rhs_mag_9x18_12_57N181S",
		"rhs_mag_9x18_12_57N181S",
		"rhs_100Rnd_762X54mmR",
		"rhs_mag_rgd5",
		"rhs_mag_rgd5",
		"SmokeShell",
		"SmokeShell",
		"SmokeShell"
		};
		Respawnmagazines[]=
		{
		"rhs_mag_9x18_12_57N181S",
		"rhs_mag_9x18_12_57N181S",
		"rhs_mag_9x18_12_57N181S",
		"rhs_100Rnd_762X54mmR",
		"rhs_mag_rgd5",
		"rhs_mag_rgd5",
		"SmokeShell",
		"SmokeShell",
		"SmokeShell"
		};
		Items[]=
		{
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_morphine",
		"ACE_morphine",
		"ACE_EarPlugs"
		};
		respawntems[]=
		{
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_morphine",
		"ACE_morphine",
		"ACE_EarPlugs"	
		};		
	};
	class Russian_Vehiclecommander:O_Soldier_base_F
	{
		_generalMacro="Russian_Vehiclecommander";
		scope=2;
		displayName="Vehicle Commander";
		faction="a_units";
		vehicleClass="Russian";
		icon="iconMan";
		nakedUniform="U_BasicBody";
		uniformClass="rhs_uniform_msv_emr";
		backpack="TWC_Backpack_USSR_Vehiclecommander";
		linkedItems[]=
		{
        "rhs_vest_commander",
		"ItemMap",
		"ItemCompass",
		"ItemWatch",
		"rhs_tsh4",
		"ACRE_PRC343"
		};
		respawnLinkedItems[]=
		{
        "rhs_vest_commander",
		"ItemMap",
		"ItemCompass",
		"ItemWatch",
		"rhs_tsh4",
		"ACRE_PRC343"
		};
		weapons[]=
		{
		"Throw",
		"Put",
		"Binocular",
		"rhs_weap_ak74m_folded_dtk",
		"rhs_weap_makarov_pmm"
		};
		respawnweapons[]=
		{
		"Throw",
		"Put",
		"Binocular",
		"rhs_weap_ak74m_folded_dtk",
		"rhs_weap_makarov_pmm"
		};
		magazines[]=
		{
		"rhs_mag_9x18_12_57N181S",
		"rhs_30Rnd_545x39_7N10_AK",
		"rhs_30Rnd_545x39_7N10_AK",
		"rhs_30Rnd_545x39_7N10_AK",
		"rhs_mag_rgd5",
		"SmokeShell"
		};
		Respawnmagazines[]=
		{
		"rhs_mag_9x18_12_57N181S",
		"rhs_30Rnd_545x39_7N10_AK",
		"rhs_30Rnd_545x39_7N10_AK",
		"rhs_30Rnd_545x39_7N10_AK",
		"rhs_mag_rgd5",
		"SmokeShell"
		};
		Items[]=
		{
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_morphine",
		"ACE_morphine",
		"ACE_EarPlugs"
		};
		respawntems[]=
		{
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_morphine",
		"ACE_morphine",
		"ACE_EarPlugs"	
		};		
	};
	class Russian_Vehiclecrew:O_Soldier_base_F
	{
		_generalMacro="USSR_Vehiclecrew";
		scope=2;
		displayName="Vehicle Crew";
		faction="a_units";
		vehicleClass="Russian";
		icon="iconMan";
		nakedUniform="U_BasicBody";
		uniformClass="rhs_uniform_msv_emr";
		backpack="";
		linkedItems[]=
		{
        "rhs_vest_commander",
		"ItemMap",
		"ItemCompass",
		"ItemWatch",
		"rhs_tsh4",
		"ACRE_PRC343"
		};
		respawnLinkedItems[]=
		{
        "rhs_vest_commander",
		"ItemMap",
		"ItemCompass",
		"ItemWatch",
		"rhs_tsh4",
		"ACRE_PRC343"
		};
		weapons[]=
		{
		"Throw",
		"Put",	
		"rhs_weap_ak74m_folded_dtk",
		"rhs_weap_makarov_pmm"
		};
		respawnweapons[]=
		{
		"Throw",
		"Put",	
		"rhs_weap_ak74m_folded_dtk",
		"rhs_weap_makarov_pmm"
		};
		magazines[]=
		{
		"rhs_mag_9x18_12_57N181S",
		"rhs_30Rnd_545x39_7N10_AK",
		"rhs_30Rnd_545x39_7N10_AK",
		"rhs_30Rnd_545x39_7N10_AK",
		"rhs_mag_rgd5",
		"SmokeShell"
		};
		Respawnmagazines[]=
		{
		"rhs_mag_9x18_12_57N181S",
		"rhs_30Rnd_545x39_7N10_AK",
		"rhs_30Rnd_545x39_7N10_AK",
		"rhs_30Rnd_545x39_7N10_AK",
		"rhs_mag_rgd5",
		"SmokeShell"
		};
		Items[]=
		{
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_morphine",
		"ACE_morphine",
		"ACE_EarPlugs"
		};
		respawntems[]=
		{
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_morphine",
		"ACE_morphine",
		"ACE_EarPlugs"	
		};		
	};