	class ColdWar_USSR_Squadleader:O_Soldier_base_F
	{
		_generalMacro="ColdWar_USSR_Squadleader";
		scope=2;
		displayName="Section Leader(ColdWar)";
		faction="twc_faction";
		editorSubcategory = "Men_USSR";
		vehicleClass="Men_USSR";
		icon="iconMan";
		nakedUniform="U_BasicBody";
		uniformClass="DISCLOSE_BEREZKA";
		backpack="";
		linkedItems[]=
		{
        "CUP_V_CDF_6B3_1_Green",
		"ItemMap",
		"ItemCompass",
		"ItemWatch",
		"CUP_H_SLA_Helmet"
		};
		respawnLinkedItems[]=
		{
        "CUP_V_CDF_6B3_1_Green",
		"ItemMap",
		"ItemCompass",
		"ItemWatch",
		"CUP_H_SLA_Helmet"
		};
		weapons[]=
		{
		"Throw",
		"Put",
		"CUP_arifle_AK74M",
		"CUP_hgun_Makarov"
		};
		respawnweapons[]=
		{
		"Throw",
		"Put",
		"CUP_arifle_AK74M",
		"CUP_hgun_Makarov"
		};
		magazines[]=
		{
		"CUP_8Rnd_9x18_Makarov_M",
		"CUP_8Rnd_9x18_Makarov_M",
		"CUP_30Rnd_545x39_AK_M",
		"CUP_30Rnd_545x39_AK_M",
		"CUP_30Rnd_545x39_AK_M",
		"CUP_30Rnd_545x39_AK_M",
		"CUP_30Rnd_545x39_AK_M",
		"CUP_30Rnd_545x39_AK_M",
		"CUP_30Rnd_545x39_AK_M",
		"CUP_30Rnd_545x39_AK_M",
		"CUP_HandGrenade_RGD5",
		"CUP_HandGrenade_RGD5",
		"SmokeShell",
		"SmokeShell",
		"SmokeShell"
		};
		Respawnmagazines[]=
		{
		"CUP_8Rnd_9x18_Makarov_M",
		"CUP_8Rnd_9x18_Makarov_M",
		"CUP_30Rnd_545x39_AK_M",
		"CUP_30Rnd_545x39_AK_M",
		"CUP_30Rnd_545x39_AK_M",
		"CUP_30Rnd_545x39_AK_M",
		"CUP_30Rnd_545x39_AK_M",
		"CUP_30Rnd_545x39_AK_M",
		"CUP_30Rnd_545x39_AK_M",
		"CUP_30Rnd_545x39_AK_M",
		"CUP_HandGrenade_RGD5",
		"CUP_HandGrenade_RGD5",
		"SmokeShell",
		"SmokeShell",
		"SmokeShell"
		};
		Items[]=
		{
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_morphine",
		"ACE_morphine",
		"ACE_EarPlugs"
		};
		respawntems[]=
		{
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_morphine",
		"ACE_morphine",
		"ACE_EarPlugs"	
		};		
	};
	
	class ColdWar_USSR_Rifleman:O_Soldier_base_F
	{
		_generalMacro="ColdWar_USSR_Rifleman";
		scope=2;
		displayName="Rifleman(ColdWar)";
		faction="twc_faction";
		editorSubcategory = "Men_USSR";
		vehicleClass="Men_USSR";
		icon="iconMan";
		nakedUniform="U_BasicBody";
		uniformClass="DISCLOSE_BEREZKA";
		backpack="";
		linkedItems[]=
		{
        "CUP_V_CDF_6B3_1_Green",
		"ItemCompass",
		"ItemWatch",
		"CUP_H_SLA_Helmet"
		};
		respawnLinkedItems[]=
		{
        "CUP_V_CDF_6B3_1_Green",
		"ItemCompass",
		"ItemWatch",
		"CUP_H_SLA_Helmet"
		};
		weapons[]=
		{
		"Throw",
		"Put",
		"CUP_arifle_AK74M"
		};
		respawnweapons[]=
		{
		"Throw",
		"Put",
		"CUP_arifle_AK74M"
		};
		magazines[]=
		{
		"CUP_30Rnd_545x39_AK_M",
		"CUP_30Rnd_545x39_AK_M",
		"CUP_30Rnd_545x39_AK_M",
		"CUP_30Rnd_545x39_AK_M",
		"CUP_30Rnd_545x39_AK_M",
		"CUP_30Rnd_545x39_AK_M",
		"CUP_30Rnd_545x39_AK_M",
		"CUP_30Rnd_545x39_AK_M",
		"CUP_HandGrenade_RGD5",
		"CUP_HandGrenade_RGD5",
		"SmokeShell",
		"SmokeShell"
		};
		Respawnmagazines[]=
		{
		"CUP_30Rnd_545x39_AK_M",
		"CUP_30Rnd_545x39_AK_M",
		"CUP_30Rnd_545x39_AK_M",
		"CUP_30Rnd_545x39_AK_M",
		"CUP_30Rnd_545x39_AK_M",
		"CUP_30Rnd_545x39_AK_M",
		"CUP_30Rnd_545x39_AK_M",
		"CUP_30Rnd_545x39_AK_M",
		"CUP_HandGrenade_RGD5",
		"CUP_HandGrenade_RGD5",
		"SmokeShell",
		"SmokeShell"
		};
		Items[]=
		{
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_morphine",
		"ACE_morphine",
		"ACE_EarPlugs"
		};
		respawntems[]=
		{
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_morphine",
		"ACE_morphine",
		"ACE_EarPlugs"	
		};		
	};
	
	class ColdWar_USSR_Grenadier:O_Soldier_base_F
	{
		_generalMacro="ColdWar_USSR_Grenadier";
		scope=2;
		displayName="Grenadier(ColdWar)";
		faction="twc_faction";
		editorSubcategory = "Men_USSR";
		vehicleClass="Men_USSR";
		icon="iconMan";
		nakedUniform="U_BasicBody";
		uniformClass="DISCLOSE_BEREZKA";
		backpack="CUP_B_RPGPack_Khaki";
		linkedItems[]=
		{
        "CUP_V_CDF_6B3_1_Green",
		"ItemCompass",
		"ItemWatch",
		"CUP_H_SLA_Helmet"
		};
		respawnLinkedItems[]=
		{
        "CUP_V_CDF_6B3_1_Green",
		"ItemCompass",
		"ItemWatch",
		"CUP_H_SLA_Helmet"
		};
		weapons[]=
		{
		"Throw",
		"Put",
		"CUP_arifle_AK74M",
		"CUP_launch_RPG7V"
		};
		respawnweapons[]=
		{
		"Throw",
		"Put",
		"CUP_arifle_AK74M",
		"CUP_launch_RPG7V"
		};
		magazines[]=
		{
		"CUP_PG7V_M",
		"CUP_30Rnd_545x39_AK_M",
		"CUP_30Rnd_545x39_AK_M",
		"CUP_30Rnd_545x39_AK_M",
		"CUP_30Rnd_545x39_AK_M",
		"CUP_30Rnd_545x39_AK_M",
		"CUP_HandGrenade_RGD5",
		"CUP_HandGrenade_RGD5",
		"SmokeShell",
		"SmokeShell"
		};
		Respawnmagazines[]=
		{
		"CUP_PG7V_M",
		"CUP_30Rnd_545x39_AK_M",
		"CUP_30Rnd_545x39_AK_M",
		"CUP_30Rnd_545x39_AK_M",
		"CUP_30Rnd_545x39_AK_M",
		"CUP_30Rnd_545x39_AK_M",
		"CUP_HandGrenade_RGD5",
		"CUP_HandGrenade_RGD5",
		"SmokeShell",
		"SmokeShell"
		};
		Items[]=
		{
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_morphine",
		"ACE_morphine",
		"ACE_EarPlugs"
		};
		respawntems[]=
		{
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_morphine",
		"ACE_morphine",
		"ACE_EarPlugs"	
		};		
	};
	
	class ColdWar_USSR_Grenadierassistant:O_Soldier_base_F
	{
		_generalMacro="ColdWar_USSR_Rifleman";
		scope=2;
		displayName="Grenadier Assistant(ColdWar)";
		faction="twc_faction";
		editorSubcategory = "Men_USSR";
		vehicleClass="Men_USSR";
		icon="iconMan";
		nakedUniform="U_BasicBody";
		uniformClass="DISCLOSE_BEREZKA";
		backpack="CUP_B_RPGPack_Khaki";
		linkedItems[]=
		{
        "CUP_V_CDF_6B3_1_Green",
		"ItemCompass",
		"ItemWatch",
		"CUP_H_SLA_Helmet"
		};
		respawnLinkedItems[]=
		{
        "CUP_V_CDF_6B3_1_Green",
		"ItemCompass",
		"ItemWatch",
		"CUP_H_SLA_Helmet"
		};
		weapons[]=
		{
		"Throw",
		"Put",
		"CUP_arifle_AK74M"
		};
		respawnweapons[]=
		{
		"Throw",
		"Put",
		"CUP_arifle_AK74M"
		};
		magazines[]=
		{
		"CUP_30Rnd_545x39_AK_M",
		"CUP_30Rnd_545x39_AK_M",
		"CUP_30Rnd_545x39_AK_M",
		"CUP_30Rnd_545x39_AK_M",
		"CUP_30Rnd_545x39_AK_M",
		"CUP_30Rnd_545x39_AK_M",
		"CUP_30Rnd_545x39_AK_M",
		"CUP_30Rnd_545x39_AK_M",
		"CUP_HandGrenade_RGD5",
		"CUP_HandGrenade_RGD5",
		"SmokeShell",
		"SmokeShell"
		};
		Respawnmagazines[]=
		{
		"CUP_30Rnd_545x39_AK_M",
		"CUP_30Rnd_545x39_AK_M",
		"CUP_30Rnd_545x39_AK_M",
		"CUP_30Rnd_545x39_AK_M",
		"CUP_30Rnd_545x39_AK_M",
		"CUP_30Rnd_545x39_AK_M",
		"CUP_30Rnd_545x39_AK_M",
		"CUP_30Rnd_545x39_AK_M",
		"CUP_HandGrenade_RGD5",
		"CUP_HandGrenade_RGD5",
		"SmokeShell",
		"SmokeShell"
		};
		Items[]=
		{
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_morphine",
		"ACE_morphine",
		"ACE_EarPlugs"
		};
		respawntems[]=
		{
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_morphine",
		"ACE_morphine",
		"ACE_EarPlugs"	
		};		
	};
	
	class ColdWar_USSR_Efreitor:O_Soldier_base_F
	{
		_generalMacro="ColdWar_USSR_Efreitor";
		scope=2;
		displayName="Efreitor(ColdWar)";
		faction="twc_faction";
		editorSubcategory = "Men_USSR";
		vehicleClass="Men_USSR";
		icon="iconMan";
		nakedUniform="U_BasicBody";
		uniformClass="DISCLOSE_BEREZKA";
		backpack="";
		linkedItems[]=
		{
        "CUP_V_CDF_6B3_1_Green",
		"ItemMap",
		"ItemCompass",
		"ItemWatch",
		"CUP_H_SLA_Helmet"
		};
		respawnLinkedItems[]=
		{
        "CUP_V_CDF_6B3_1_Green",
		"ItemMap",
		"ItemCompass",
		"ItemWatch",
		"CUP_H_SLA_Helmet"
		};
		weapons[]=
		{
		"Throw",
		"Put",
		"CUP_arifle_AK74M"
		};
		respawnweapons[]=
		{
		"Throw",
		"Put",
		"CUP_arifle_AK74M"
		};
		magazines[]=
		{
		"CUP_8Rnd_9x18_Makarov_M",
		"CUP_8Rnd_9x18_Makarov_M",
		"CUP_30Rnd_545x39_AK_M",
		"CUP_30Rnd_545x39_AK_M",
		"CUP_30Rnd_545x39_AK_M",
		"CUP_30Rnd_545x39_AK_M",
		"CUP_30Rnd_545x39_AK_M",
		"CUP_30Rnd_545x39_AK_M",
		"CUP_30Rnd_545x39_AK_M",
		"CUP_30Rnd_545x39_AK_M",
		"CUP_HandGrenade_RGD5",
		"CUP_HandGrenade_RGD5",
		"SmokeShell",
		"SmokeShell",
		"SmokeShell"
		};
		Respawnmagazines[]=
		{
		"CUP_8Rnd_9x18_Makarov_M",
		"CUP_8Rnd_9x18_Makarov_M",
		"CUP_30Rnd_545x39_AK_M",
		"CUP_30Rnd_545x39_AK_M",
		"CUP_30Rnd_545x39_AK_M",
		"CUP_30Rnd_545x39_AK_M",
		"CUP_30Rnd_545x39_AK_M",
		"CUP_30Rnd_545x39_AK_M",
		"CUP_30Rnd_545x39_AK_M",
		"CUP_30Rnd_545x39_AK_M",
		"CUP_HandGrenade_RGD5",
		"CUP_HandGrenade_RGD5",
		"SmokeShell",
		"SmokeShell",
		"SmokeShell"
		};
		Items[]=
		{
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_morphine",
		"ACE_morphine",
		"ACE_EarPlugs"
		};
		respawntems[]=
		{
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_morphine",
		"ACE_morphine",
		"ACE_EarPlugs"	
		};		
	};
	
	class ColdWar_USSR_MachineGunner:O_Soldier_base_F
	{
		_generalMacro="ColdWar_USSR_MachineGunner";
		scope=2;
		displayName="Machine Gunner(ColdWar)";
		faction="twc_faction";
		editorSubcategory = "Men_USSR";
		vehicleClass="Men_USSR";
		icon="iconMan";
		nakedUniform="U_BasicBody";
		uniformClass="DISCLOSE_BEREZKA";
		backpack="TWC_Backpack_USSR_Automaticrifleman";
		linkedItems[]=
		{
        "CUP_V_CDF_6B3_1_Green",
		"ItemMap",
		"ItemCompass",
		"ItemWatch",
		"CUP_H_SLA_Helmet"
		};
		respawnLinkedItems[]=
		{
        "CUP_V_CDF_6B3_1_Green",
		"ItemMap",
		"ItemCompass",
		"ItemWatch",
		"CUP_H_SLA_Helmet"
		};
		weapons[]=
		{
		"Throw",
		"Put",
		"CUP_lmg_PKM"
		};
		respawnweapons[]=
		{
		"Throw",
		"Put",
		"CUP_lmg_PKM"
		};
		magazines[]=
		{
		"CUP_100Rnd_TE4_LRT4_762x54_PK_Tracer_Green_M",
		"CUP_100Rnd_TE4_LRT4_762x54_PK_Tracer_Green_M",
		"CUP_HandGrenade_RGD5",
		"CUP_HandGrenade_RGD5",
		"SmokeShell",
		"SmokeShell",
		"SmokeShell"
		};
		Respawnmagazines[]=
		{
		"CUP_100Rnd_TE4_LRT4_762x54_PK_Tracer_Green_M",
		"CUP_100Rnd_TE4_LRT4_762x54_PK_Tracer_Green_M",
		"CUP_HandGrenade_RGD5",
		"CUP_HandGrenade_RGD5",
		"SmokeShell",
		"SmokeShell",
		"SmokeShell"
		};
		Items[]=
		{
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_morphine",
		"ACE_morphine",
		"ACE_EarPlugs"
		};
		respawntems[]=
		{
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_morphine",
		"ACE_morphine",
		"ACE_EarPlugs"	
		};		
	};
	class ColdWar_USSR_AAGunner:O_Soldier_base_F
	{
		_generalMacro="ColdWar_USSR_AAGunner";
		scope=2;
		displayName="AA Gunner(ColdWar)";
		faction="twc_faction";
		editorSubcategory = "Men_USSR";
		vehicleClass="Men_USSR";
		icon="iconMan";
		nakedUniform="U_BasicBody";
		uniformClass="DISCLOSE_BEREZKA";
		backpack="TWC_Backpack_USSR_AATeam";
		linkedItems[]=
		{
        "CUP_V_CDF_6B3_1_Green",
		"ItemCompass",
		"ItemWatch",
		"CUP_H_SLA_Helmet"
		};
		respawnLinkedItems[]=
		{
        "CUP_V_CDF_6B3_1_Green",
		"ItemCompass",
		"ItemWatch",
		"CUP_H_SLA_Helmet"
		};
		weapons[]=
		{
		"Throw",
		"Put",
		"CUP_arifle_AK74M",
		"CUP_launch_9K32Strela"
		};
		respawnweapons[]=
		{
		"Throw",
		"Put",
		"CUP_arifle_AK74M",
		"CUP_launch_9K32Strela"
		};
		magazines[]=
		{
		"CUP_Strela_2_M",
		"CUP_30Rnd_545x39_AK_M",
		"CUP_30Rnd_545x39_AK_M",
		"CUP_30Rnd_545x39_AK_M",
		"CUP_30Rnd_545x39_AK_M",
		"CUP_30Rnd_545x39_AK_M",
		"CUP_30Rnd_545x39_AK_M",
		"CUP_30Rnd_545x39_AK_M",
		"CUP_30Rnd_545x39_AK_M",
		"CUP_HandGrenade_RGD5",
		"CUP_HandGrenade_RGD5",
		"SmokeShell",
		"SmokeShell"
		};
		Respawnmagazines[]=
		{
		"CUP_Strela_2_M",
		"CUP_30Rnd_545x39_AK_M",
		"CUP_30Rnd_545x39_AK_M",
		"CUP_30Rnd_545x39_AK_M",
		"CUP_30Rnd_545x39_AK_M",
		"CUP_30Rnd_545x39_AK_M",
		"CUP_30Rnd_545x39_AK_M",
		"CUP_30Rnd_545x39_AK_M",
		"CUP_30Rnd_545x39_AK_M",
		"CUP_HandGrenade_RGD5",
		"CUP_HandGrenade_RGD5",
		"SmokeShell",
		"SmokeShell"
		};
		Items[]=
		{
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_morphine",
		"ACE_morphine",
		"ACE_EarPlugs"
		};
		respawntems[]=
		{
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_morphine",
		"ACE_morphine",
		"ACE_EarPlugs"	
		};		
	};	
	class ColdWar_USSR_AAAssistant:O_Soldier_base_F
	{
		_generalMacro="ColdWar_USSR_AAAssistant";
		scope=2;
		displayName="AA Assistant(ColdWar)";
		faction="twc_faction";
		editorSubcategory = "Men_USSR";
		vehicleClass="Men_USSR";
		icon="iconMan";
		nakedUniform="U_BasicBody";
		uniformClass="DISCLOSE_BEREZKA";
		backpack="TWC_Backpack_USSR_AATeam";
		linkedItems[]=
		{
        "CUP_V_CDF_6B3_1_Green",
		"ItemCompass",
		"ItemWatch",
		"CUP_H_SLA_Helmet"
		};
		respawnLinkedItems[]=
		{
        "CUP_V_CDF_6B3_1_Green",
		"ItemCompass",
		"ItemWatch",
		"CUP_H_SLA_Helmet"
		};
		weapons[]=
		{
		"Throw",
		"Put",
		"CUP_arifle_AK74M"
		};
		respawnweapons[]=
		{
		"Throw",
		"Put",
		"CUP_arifle_AK74M"
		};
		magazines[]=
		{
		"CUP_30Rnd_545x39_AK_M",
		"CUP_30Rnd_545x39_AK_M",
		"CUP_30Rnd_545x39_AK_M",
		"CUP_30Rnd_545x39_AK_M",
		"CUP_30Rnd_545x39_AK_M",
		"CUP_30Rnd_545x39_AK_M",
		"CUP_30Rnd_545x39_AK_M",
		"CUP_30Rnd_545x39_AK_M",
		"CUP_HandGrenade_RGD5",
		"CUP_HandGrenade_RGD5",
		"SmokeShell",
		"SmokeShell"
		};
		Respawnmagazines[]=
		{
		"CUP_30Rnd_545x39_AK_M",
		"CUP_30Rnd_545x39_AK_M",
		"CUP_30Rnd_545x39_AK_M",
		"CUP_30Rnd_545x39_AK_M",
		"CUP_30Rnd_545x39_AK_M",
		"CUP_30Rnd_545x39_AK_M",
		"CUP_30Rnd_545x39_AK_M",
		"CUP_30Rnd_545x39_AK_M",
		"CUP_HandGrenade_RGD5",
		"CUP_HandGrenade_RGD5",
		"SmokeShell",
		"SmokeShell"
		};
		Items[]=
		{
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_morphine",
		"ACE_morphine",
		"ACE_EarPlugs"
		};
		respawntems[]=
		{
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_morphine",
		"ACE_morphine",
		"ACE_EarPlugs"	
		};		
	};