	class ColdWar_USSR_Squadleader:O_Soldier_base_F
	{
		_generalMacro="ColdWar_USSR_Squadleader";
		scope=2;
		displayName="Section Leader(ColdWar)";
		faction="a_units";
		vehicleClass="USSR";
		icon="iconMan";
		nakedUniform="U_BasicBody";
		uniformClass="DISCLOSE_BEREZKA";
		backpack="";
		linkedItems[]=
		{
        "rhs_6b13_EMR_6sh92",
		"ItemMap",
		"ItemCompass",
		"ItemWatch",
		"rhs_6b26_green"
		};
		respawnLinkedItems[]=
		{
        "rhs_6b13_EMR_6sh92",
		"ItemMap",
		"ItemCompass",
		"ItemWatch",
		"rhs_6b26_green"
		};
		weapons[]=
		{
		"Throw",
		"Put",
		"rhs_weap_ak74m_dtk",
		"rhs_weap_makarov_pm"
		};
		respawnweapons[]=
		{
		"Throw",
		"Put",
		"rhs_weap_ak74m_dtk",
		"rhs_weap_makarov_pm"
		};
		magazines[]=
		{
		"rhs_mag_9x18_12_57N181S",
		"rhs_mag_9x18_12_57N181S",
		"rhs_30Rnd_545x39_7N10_AK",
		"rhs_30Rnd_545x39_7N10_AK",
		"rhs_30Rnd_545x39_7N10_AK",
		"rhs_30Rnd_545x39_7N10_AK",
		"rhs_30Rnd_545x39_7N10_AK",
		"rhs_30Rnd_545x39_7N10_AK",
		"rhs_30Rnd_545x39_7N10_AK",
		"rhs_30Rnd_545x39_7N10_AK",
		"rhs_mag_rgd5",
		"rhs_mag_rgd5",
		"SmokeShell",
		"SmokeShell",
		"SmokeShell"
		};
		Respawnmagazines[]=
		{
		"rhs_mag_9x18_12_57N181S",
		"rhs_mag_9x18_12_57N181S",
		"rhs_30Rnd_545x39_7N10_AK",
		"rhs_30Rnd_545x39_7N10_AK",
		"rhs_30Rnd_545x39_7N10_AK",
		"rhs_30Rnd_545x39_7N10_AK",
		"rhs_30Rnd_545x39_7N10_AK",
		"rhs_30Rnd_545x39_7N10_AK",
		"rhs_30Rnd_545x39_7N10_AK",
		"rhs_30Rnd_545x39_7N10_AK",
		"rhs_mag_rgd5",
		"rhs_mag_rgd5",
		"SmokeShell",
		"SmokeShell",
		"SmokeShell"
		};
		Items[]=
		{
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_morphine",
		"ACE_morphine",
		"ACE_EarPlugs"
		};
		respawntems[]=
		{
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_morphine",
		"ACE_morphine",
		"ACE_EarPlugs"	
		};		
	};
	
	class ColdWar_USSR_Rifleman:O_Soldier_base_F
	{
		_generalMacro="ColdWar_USSR_Rifleman";
		scope=2;
		displayName="Rifleman(ColdWar)";
		faction="a_units";
		vehicleClass="USSR";
		icon="iconMan";
		nakedUniform="U_BasicBody";
		uniformClass="DISCLOSE_BEREZKA";
		backpack="";
		linkedItems[]=
		{
        "rhs_6b13_EMR_6sh92",
		"ItemCompass",
		"ItemWatch",
		"rhs_6b26_green"
		};
		respawnLinkedItems[]=
		{
        "rhs_6b13_EMR_6sh92",
		"ItemCompass",
		"ItemWatch",
		"rhs_6b26_green"
		};
		weapons[]=
		{
		"Throw",
		"Put",
		"rhs_weap_ak74m_dtk"
		};
		respawnweapons[]=
		{
		"Throw",
		"Put",
		"rhs_weap_ak74m_dtk"
		};
		magazines[]=
		{
		"rhs_30Rnd_545x39_7N10_AK",
		"rhs_30Rnd_545x39_7N10_AK",
		"rhs_30Rnd_545x39_7N10_AK",
		"rhs_30Rnd_545x39_7N10_AK",
		"rhs_30Rnd_545x39_7N10_AK",
		"rhs_30Rnd_545x39_7N10_AK",
		"rhs_30Rnd_545x39_7N10_AK",
		"rhs_30Rnd_545x39_7N10_AK",
		"rhs_mag_rgd5",
		"rhs_mag_rgd5",
		"SmokeShell",
		"SmokeShell"
		};
		Respawnmagazines[]=
		{
		"rhs_30Rnd_545x39_7N10_AK",
		"rhs_30Rnd_545x39_7N10_AK",
		"rhs_30Rnd_545x39_7N10_AK",
		"rhs_30Rnd_545x39_7N10_AK",
		"rhs_30Rnd_545x39_7N10_AK",
		"rhs_30Rnd_545x39_7N10_AK",
		"rhs_30Rnd_545x39_7N10_AK",
		"rhs_30Rnd_545x39_7N10_AK",
		"rhs_mag_rgd5",
		"rhs_mag_rgd5",
		"SmokeShell",
		"SmokeShell"
		};
		Items[]=
		{
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_morphine",
		"ACE_morphine",
		"ACE_EarPlugs"
		};
		respawntems[]=
		{
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_morphine",
		"ACE_morphine",
		"ACE_EarPlugs"	
		};		
	};
	
	class ColdWar_USSR_Grenadier:O_Soldier_base_F
	{
		_generalMacro="ColdWar_USSR_Grenadier";
		scope=2;
		displayName="Grenadier(ColdWar)";
		faction="a_units";
		vehicleClass="USSR";
		icon="iconMan";
		nakedUniform="U_BasicBody";
		uniformClass="DISCLOSE_BEREZKA";
		backpack="TWC_Backpack_USSR_Grenadier";
		linkedItems[]=
		{
        "rhs_6b13_EMR_6sh92",
		"ItemCompass",
		"ItemWatch",
		"rhs_6b26_green"
		};
		respawnLinkedItems[]=
		{
        "rhs_6b13_EMR_6sh92",
		"ItemCompass",
		"ItemWatch",
		"rhs_6b26_green"
		};
		weapons[]=
		{
		"Throw",
		"Put",
		"rhs_weap_ak74m_dtk",
		"rhs_weap_rpg7"
		};
		respawnweapons[]=
		{
		"Throw",
		"Put",
		"rhs_weap_ak74m_dtk",
		"rhs_weap_rpg7"
		};
		magazines[]=
		{
		"rhs_rpg7_PG7VL_mag",
		"rhs_30Rnd_545x39_7N10_AK",
		"rhs_30Rnd_545x39_7N10_AK",
		"rhs_30Rnd_545x39_7N10_AK",
		"rhs_30Rnd_545x39_7N10_AK",
		"rhs_30Rnd_545x39_7N10_AK",
		"rhs_mag_rgd5",
		"rhs_mag_rgd5",
		"SmokeShell",
		"SmokeShell"
		};
		Respawnmagazines[]=
		{
		"rhs_rpg7_PG7VL_mag",
		"rhs_30Rnd_545x39_7N10_AK",
		"rhs_30Rnd_545x39_7N10_AK",
		"rhs_30Rnd_545x39_7N10_AK",
		"rhs_30Rnd_545x39_7N10_AK",
		"rhs_30Rnd_545x39_7N10_AK",
		"rhs_mag_rgd5",
		"rhs_mag_rgd5",
		"SmokeShell",
		"SmokeShell"
		};
		Items[]=
		{
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_morphine",
		"ACE_morphine",
		"ACE_EarPlugs"
		};
		respawntems[]=
		{
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_morphine",
		"ACE_morphine",
		"ACE_EarPlugs"	
		};		
	};
	
	class ColdWar_USSR_Grenadierassistant:O_Soldier_base_F
	{
		_generalMacro="ColdWar_USSR_Rifleman";
		scope=2;
		displayName="Grenadier Assistant(ColdWar)";
		faction="a_units";
		vehicleClass="USSR";
		icon="iconMan";
		nakedUniform="U_BasicBody";
		uniformClass="DISCLOSE_BEREZKA";
		backpack="TWC_Backpack_USSR_Grenadier";
		linkedItems[]=
		{
        "rhs_6b13_EMR_6sh92",
		"ItemCompass",
		"ItemWatch",
		"rhs_6b26_green"
		};
		respawnLinkedItems[]=
		{
        "rhs_6b13_EMR_6sh92",
		"ItemCompass",
		"ItemWatch",
		"rhs_6b26_green"
		};
		weapons[]=
		{
		"Throw",
		"Put",
		"rhs_weap_ak74m_dtk"
		};
		respawnweapons[]=
		{
		"Throw",
		"Put",
		"rhs_weap_ak74m_dtk"
		};
		magazines[]=
		{
		"rhs_30Rnd_545x39_7N10_AK",
		"rhs_30Rnd_545x39_7N10_AK",
		"rhs_30Rnd_545x39_7N10_AK",
		"rhs_30Rnd_545x39_7N10_AK",
		"rhs_30Rnd_545x39_7N10_AK",
		"rhs_30Rnd_545x39_7N10_AK",
		"rhs_30Rnd_545x39_7N10_AK",
		"rhs_30Rnd_545x39_7N10_AK",
		"rhs_mag_rgd5",
		"rhs_mag_rgd5",
		"SmokeShell",
		"SmokeShell"
		};
		Respawnmagazines[]=
		{
		"rhs_30Rnd_545x39_7N10_AK",
		"rhs_30Rnd_545x39_7N10_AK",
		"rhs_30Rnd_545x39_7N10_AK",
		"rhs_30Rnd_545x39_7N10_AK",
		"rhs_30Rnd_545x39_7N10_AK",
		"rhs_30Rnd_545x39_7N10_AK",
		"rhs_30Rnd_545x39_7N10_AK",
		"rhs_30Rnd_545x39_7N10_AK",
		"rhs_mag_rgd5",
		"rhs_mag_rgd5",
		"SmokeShell",
		"SmokeShell"
		};
		Items[]=
		{
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_morphine",
		"ACE_morphine",
		"ACE_EarPlugs"
		};
		respawntems[]=
		{
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_morphine",
		"ACE_morphine",
		"ACE_EarPlugs"	
		};		
	};
	
	class ColdWar_USSR_Efreitor:O_Soldier_base_F
	{
		_generalMacro="ColdWar_USSR_Efreitor";
		scope=2;
		displayName="Efreitor(ColdWar)";
		faction="a_units";
		vehicleClass="USSR";
		icon="iconMan";
		nakedUniform="U_BasicBody";
		uniformClass="DISCLOSE_BEREZKA";
		backpack="";
		linkedItems[]=
		{
        "rhs_6b13_EMR_6sh92",
		"ItemMap",
		"ItemCompass",
		"ItemWatch",
		"rhs_6b26_green"
		};
		respawnLinkedItems[]=
		{
        "rhs_6b13_EMR_6sh92",
		"ItemMap",
		"ItemCompass",
		"ItemWatch",
		"rhs_6b26_green"
		};
		weapons[]=
		{
		"Throw",
		"Put",
		"rhs_weap_ak74m_dtk"
		};
		respawnweapons[]=
		{
		"Throw",
		"Put",
		"rhs_weap_ak74m_dtk"
		};
		magazines[]=
		{
		"rhs_mag_9x18_12_57N181S",
		"rhs_mag_9x18_12_57N181S",
		"rhs_30Rnd_545x39_7N10_AK",
		"rhs_30Rnd_545x39_7N10_AK",
		"rhs_30Rnd_545x39_7N10_AK",
		"rhs_30Rnd_545x39_7N10_AK",
		"rhs_30Rnd_545x39_7N10_AK",
		"rhs_30Rnd_545x39_7N10_AK",
		"rhs_30Rnd_545x39_7N10_AK",
		"rhs_30Rnd_545x39_7N10_AK",
		"rhs_mag_rgd5",
		"rhs_mag_rgd5",
		"SmokeShell",
		"SmokeShell",
		"SmokeShell"
		};
		Respawnmagazines[]=
		{
		"rhs_mag_9x18_12_57N181S",
		"rhs_mag_9x18_12_57N181S",
		"rhs_30Rnd_545x39_7N10_AK",
		"rhs_30Rnd_545x39_7N10_AK",
		"rhs_30Rnd_545x39_7N10_AK",
		"rhs_30Rnd_545x39_7N10_AK",
		"rhs_30Rnd_545x39_7N10_AK",
		"rhs_30Rnd_545x39_7N10_AK",
		"rhs_30Rnd_545x39_7N10_AK",
		"rhs_30Rnd_545x39_7N10_AK",
		"rhs_mag_rgd5",
		"rhs_mag_rgd5",
		"SmokeShell",
		"SmokeShell",
		"SmokeShell"
		};
		Items[]=
		{
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_morphine",
		"ACE_morphine",
		"ACE_EarPlugs"
		};
		respawntems[]=
		{
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_morphine",
		"ACE_morphine",
		"ACE_EarPlugs"	
		};		
	};
	
	class ColdWar_USSR_MachineGunner:O_Soldier_base_F
	{
		_generalMacro="ColdWar_USSR_MachineGunner";
		scope=2;
		displayName="Machine Gunner(ColdWar)";
		faction="a_units";
		vehicleClass="USSR";
		icon="iconMan";
		nakedUniform="U_BasicBody";
		uniformClass="DISCLOSE_BEREZKA";
		backpack="TWC_Backpack_USSR_Automaticrifleman";
		linkedItems[]=
		{
        "rhs_6b13_EMR_6sh92",
		"ItemMap",
		"ItemCompass",
		"ItemWatch",
		"rhs_6b26_green"
		};
		respawnLinkedItems[]=
		{
        "rhs_6b13_EMR_6sh92",
		"ItemMap",
		"ItemCompass",
		"ItemWatch",
		"rhs_6b26_green"
		};
		weapons[]=
		{
		"Throw",
		"Put",
		"rhs_weap_pkm"
		};
		respawnweapons[]=
		{
		"Throw",
		"Put",
		"rhs_weap_pkm"
		};
		magazines[]=
		{
		"rhs_100Rnd_762x54mmR",
		"rhs_100Rnd_762x54mmR",
		"rhs_mag_rgd5",
		"rhs_mag_rgd5",
		"SmokeShell",
		"SmokeShell",
		"SmokeShell"
		};
		Respawnmagazines[]=
		{
		"rhs_100Rnd_762x54mmR",
		"rhs_100Rnd_762x54mmR",
		"rhs_mag_rgd5",
		"rhs_mag_rgd5",
		"SmokeShell",
		"SmokeShell",
		"SmokeShell"
		};
		Items[]=
		{
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_morphine",
		"ACE_morphine",
		"ACE_EarPlugs"
		};
		respawntems[]=
		{
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_morphine",
		"ACE_morphine",
		"ACE_EarPlugs"	
		};		
	};