	class WW2_British_Platoon_Commander: B_Soldier_base_F
	{
		_generalMacro="WW2_British_Platoon_Commander";
		scope=2;
		displayName="Platoon Commander(WW2)";
		faction="twc_faction";
		editorSubcategory = "Men_WW2";
		vehicleClass="Men_WW2";
		icon="iconManLeader";
		nakedUniform="U_BasicBody";
		uniformClass="U_mas_ww2_B_CombatUniform_uk";
		backpack="B_mas_ww2_Bergen_uk";
		linkedItems[]=
		{
        "V_mas_ww2_vest_UK",
		"H_mas_ww2_helmet_uk_B",
		"ItemMap",
		"ItemCompass",
		"ItemWatch"
		};
		respawnLinkedItems[]=
		{
        "V_mas_ww2_vest_UK",
		"H_mas_ww2_helmet_uk_B",
		"ItemMap",
		"ItemCompass",
		"ItemWatch"
		};
		weapons[]=
		{
		"Throw",
		"Put",
		"arifle_mas_ww2_sten"
		};
		respawnweapons[]=
		{
		"Throw",
		"Put",
		"arifle_mas_ww2_sten"
		};
		magazines[]=
		{
		"30Rnd_mas_ww2_sten",
		"30Rnd_mas_ww2_sten",
		"30Rnd_mas_ww2_sten",
		"SmokeShell",
		"SmokeShell",
		"SmokeShell"
		};
		Respawnmagazines[]=
		{
		"30Rnd_mas_ww2_sten",
		"30Rnd_mas_ww2_sten",
		"30Rnd_mas_ww2_sten",
		"SmokeShell",
		"SmokeShell",
		"SmokeShell"
		};
		Items[]=
		{
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_morphine",
		"ACE_morphine",
		"ACE_epinephrine",
		"ACE_tourniquet",
		"ACE_EarPlugs"	
		};
		respawntems[]=
		{
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_morphine",
		"ACE_morphine",
		"ACE_epinephrine",
		"ACE_tourniquet",
		"ACE_EarPlugs"		
		};
	};
	class WW2_British_Platoon_Sergeant: B_Soldier_base_F
	{
		_generalMacro="WW2_British_Platoon_Sergeant";
		scope=2;
		displayName="Platoon Sergeant(WW2)";
		faction="twc_faction";
		editorSubcategory = "Men_WW2";
		vehicleClass="Men_WW2";
		icon="iconManLeader";
		nakedUniform="U_BasicBody";
		uniformClass="U_mas_ww2_B_CombatUniform_uk";
		backpack="B_mas_ww2_Bergen_uk";
		linkedItems[]=
		{
        "V_mas_ww2_vest_UK",
		"H_mas_ww2_helmet_uk_B",
		"ItemMap",
		"ItemCompass",
		"ItemWatch"
		};
		respawnLinkedItems[]=
		{
        "V_mas_ww2_vest_UK",
		"H_mas_ww2_helmet_uk_B",
		"ItemMap",
		"ItemCompass",
		"ItemWatch"
		};
		weapons[]=
		{
		"Throw",
		"Put",
		"arifle_mas_ww2_sten"
		};
		respawnweapons[]=
		{
		"Throw",
		"Put",
		"arifle_mas_ww2_sten"
		};
		magazines[]=
		{
		"30Rnd_mas_ww2_sten",
		"30Rnd_mas_ww2_sten",
		"30Rnd_mas_ww2_sten",
		"SmokeShell",
		"SmokeShell",
		"SmokeShell"
		};
		Respawnmagazines[]=
		{
		"30Rnd_mas_ww2_sten",
		"30Rnd_mas_ww2_sten",
		"30Rnd_mas_ww2_sten",
		"SmokeShell",
		"SmokeShell",
		"SmokeShell"
		};
		Items[]=
		{
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_morphine",
		"ACE_morphine",
		"ACE_epinephrine",
		"ACE_tourniquet",
		"ACE_EarPlugs"	
		};
		respawntems[]=
		{
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_morphine",
		"ACE_morphine",
		"ACE_epinephrine",
		"ACE_tourniquet",
		"ACE_EarPlugs"		
		};
	};
	class WW2_British_Medic: B_Soldier_base_F
	{
		_generalMacro="WW2_British_Medic";
		scope=2;
		displayName="Medic(WW2)";
		faction="twc_faction";
		editorSubcategory = "Men_WW2";
		vehicleClass="Men_WW2";
		icon="iconManLeader";
		nakedUniform="U_BasicBody";
		uniformClass="U_mas_ww2_B_CombatUniform_uk";
		backpack="TWC_Backpack_WW2_Medic";
		linkedItems[]=
		{
        "V_mas_ww2_vest_UK",
		"H_mas_ww2_helmet_uk_B",
		"ItemMap",
		"ItemCompass",
		"ItemWatch"
		};
		respawnLinkedItems[]=
		{
        "V_mas_ww2_vest_UK",
		"H_mas_ww2_helmet_uk_B",
		"ItemMap",
		"ItemCompass",
		"ItemWatch"
		};
		weapons[]=
		{
		"Throw",
		"Put",
		"arifle_mas_ww2_sten"
		};
		respawnweapons[]=
		{
		"Throw",
		"Put",
		"arifle_mas_ww2_sten"
		};
		magazines[]=
		{
		"30Rnd_mas_ww2_sten",
		"30Rnd_mas_ww2_sten",
		"30Rnd_mas_ww2_sten",
		"SmokeShell",
		"SmokeShell",
		"SmokeShell"
		};
		Respawnmagazines[]=
		{
		"30Rnd_mas_ww2_sten",
		"30Rnd_mas_ww2_sten",
		"30Rnd_mas_ww2_sten",
		"SmokeShell",
		"SmokeShell",
		"SmokeShell"
		};
		Items[]=
		{
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_morphine",
		"ACE_morphine",
		"ACE_epinephrine",
		"ACE_tourniquet",
		"ACE_EarPlugs"	
		};
		respawntems[]=
		{
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_morphine",
		"ACE_morphine",
		"ACE_epinephrine",
		"ACE_tourniquet",
		"ACE_EarPlugs"		
		};
	};
	class WW2_British_Section_Commander: B_Soldier_base_F
	{
		_generalMacro="WW2_British_Section_Commander";
		scope=2;
		displayName="Section Commander(WW2)";
		faction="twc_faction";
		editorSubcategory = "Men_WW2";
		vehicleClass="Men_WW2";
		icon="iconManLeader";
		nakedUniform="U_BasicBody";
		uniformClass="U_mas_ww2_B_CombatUniform_uk";
		backpack="B_mas_ww2_Bergen_uk";
		linkedItems[]=
		{
        "V_mas_ww2_vest_UK",
		"H_mas_ww2_helmet_uk_B",
		"ItemMap",
		"ItemCompass",
		"ItemWatch"
		};
		respawnLinkedItems[]=
		{
        "V_mas_ww2_vest_UK",
		"H_mas_ww2_helmet_uk_B",
		"ItemMap",
		"ItemCompass",
		"ItemWatch"
		};
		weapons[]=
		{
		"Throw",
		"Put",
		"arifle_mas_ww2_sten"
		};
		respawnweapons[]=
		{
		"Throw",
		"Put",
		"arifle_mas_ww2_sten"
		};
		magazines[]=
		{
		"30Rnd_mas_ww2_sten",
		"30Rnd_mas_ww2_sten",
		"30Rnd_mas_ww2_sten",
		"30Rnd_mas_ww2_sten",
		"30Rnd_mas_ww2_sten",
		"30Rnd_mas_ww2_sten",
		"30Rnd_mas_ww2_sten",
		"30Rnd_mas_ww2_sten",
		"CUP_HandGrenade_L109A2_HE",
		"CUP_HandGrenade_L109A2_HE",
		"SmokeShell",
		"SmokeShell",
		"SmokeShell"
		};
		Respawnmagazines[]=
		{
		"30Rnd_mas_ww2_sten",
		"30Rnd_mas_ww2_sten",
		"30Rnd_mas_ww2_sten",
		"30Rnd_mas_ww2_sten",
		"30Rnd_mas_ww2_sten",
		"30Rnd_mas_ww2_sten",
		"30Rnd_mas_ww2_sten",
		"30Rnd_mas_ww2_sten",
		"CUP_HandGrenade_L109A2_HE",
		"CUP_HandGrenade_L109A2_HE",
		"SmokeShell",
		"SmokeShell",
		"SmokeShell"
		};
		Items[]=
		{
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_morphine",
		"ACE_morphine",
		"ACE_epinephrine",
		"ACE_tourniquet",
		"ACE_EarPlugs"	
		};
		respawntems[]=
		{
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_morphine",
		"ACE_morphine",
		"ACE_epinephrine",
		"ACE_tourniquet",
		"ACE_EarPlugs"		
		};
	};
	class WW2_British_Rifleman: B_Soldier_base_F
	{
		_generalMacro="WW2_British_Rifleman";
		scope=2;
		displayName="Rifleman(WW2)";
		faction="twc_faction";
		editorSubcategory = "Men_WW2";
		vehicleClass="Men_WW2";
		icon="iconManLeader";
		nakedUniform="U_BasicBody";
		uniformClass="U_mas_ww2_B_CombatUniform_uk";
		backpack="";
		linkedItems[]=
		{
        "V_mas_ww2_vest_UK",
		"H_mas_ww2_helmet_uk_B",
		"ItemMap",
		"ItemCompass",
		"ItemWatch"
		};
		respawnLinkedItems[]=
		{
        "V_mas_ww2_vest_UK",
		"H_mas_ww2_helmet_uk_B",
		"ItemMap",
		"ItemCompass",
		"ItemWatch"
		};
		weapons[]=
		{
		"Throw",
		"Put",
		"CUP_srifle_LeeEnfield"
		};
		respawnweapons[]=
		{
		"Throw",
		"Put",
		"CUP_srifle_LeeEnfield"
		};
		magazines[]=
		{
		"CUP_10x_303_M",
		"CUP_10x_303_M",
		"CUP_10x_303_M",
		"CUP_10x_303_M",
		"CUP_10x_303_M",
		"CUP_10x_303_M",
		"CUP_10x_303_M",
		"CUP_10x_303_M",
		"CUP_HandGrenade_L109A2_HE",
		"CUP_HandGrenade_L109A2_HE"
		};
		Respawnmagazines[]=
		{
		"CUP_10x_303_M",
		"CUP_10x_303_M",
		"CUP_10x_303_M",
		"CUP_10x_303_M",
		"CUP_10x_303_M",
		"CUP_10x_303_M",
		"CUP_10x_303_M",
		"CUP_10x_303_M",
		"CUP_HandGrenade_L109A2_HE",
		"CUP_HandGrenade_L109A2_HE"
		};
		Items[]=
		{
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_morphine",
		"ACE_morphine",
		"ACE_epinephrine",
		"ACE_tourniquet",
		"ACE_EarPlugs"	
		};
		respawntems[]=
		{
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_morphine",
		"ACE_morphine",
		"ACE_epinephrine",
		"ACE_tourniquet",
		"ACE_EarPlugs"		
		};
	};
	class WW2_British_2IC: B_Soldier_base_F
	{
		_generalMacro="WW2_British_2IC";
		scope=2;
		displayName="2IC(WW2)";
		faction="twc_faction";
		editorSubcategory = "Men_WW2";
		vehicleClass="Men_WW2";
		icon="iconManLeader";
		nakedUniform="U_BasicBody";
		uniformClass="U_mas_ww2_B_CombatUniform_uk";
		backpack="TWC_Backpack_WW2_2IC";
		linkedItems[]=
		{
        "V_mas_ww2_vest_UK",
		"H_mas_ww2_helmet_uk_B",
		"ItemMap",
		"ItemCompass",
		"ItemWatch"
		};
		respawnLinkedItems[]=
		{
        "V_mas_ww2_vest_UK",
		"H_mas_ww2_helmet_uk_B",
		"ItemMap",
		"ItemCompass",
		"ItemWatch"
		};
		weapons[]=
		{
		"Throw",
		"Put",
		"CUP_srifle_LeeEnfield"
		};
		respawnweapons[]=
		{
		"Throw",
		"Put",
		"CUP_srifle_LeeEnfield"
		};
		magazines[]=
		{
		"CUP_10x_303_M",
		"CUP_10x_303_M",
		"CUP_10x_303_M",
		"CUP_10x_303_M",
		"CUP_10x_303_M",
		"CUP_10x_303_M",
		"CUP_10x_303_M",
		"CUP_10x_303_M",
		"CUP_HandGrenade_L109A2_HE",
		"CUP_HandGrenade_L109A2_HE",
		"SmokeShell",
		"SmokeShell",
		"SmokeShell"
		};
		Respawnmagazines[]=
		{
		"CUP_10x_303_M",
		"CUP_10x_303_M",
		"CUP_10x_303_M",
		"CUP_10x_303_M",
		"CUP_10x_303_M",
		"CUP_10x_303_M",
		"CUP_10x_303_M",
		"CUP_10x_303_M",
		"CUP_HandGrenade_L109A2_HE",
		"CUP_HandGrenade_L109A2_HE",
		"SmokeShell",
		"SmokeShell",
		"SmokeShell"
		};
		Items[]=
		{
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_morphine",
		"ACE_morphine",
		"ACE_epinephrine",
		"ACE_tourniquet",
		"ACE_EarPlugs"	
		};
		respawntems[]=
		{
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_morphine",
		"ACE_morphine",
		"ACE_epinephrine",
		"ACE_tourniquet",
		"ACE_EarPlugs"		
		};
	};
	class WW2_British_MG: B_Soldier_base_F
	{
		_generalMacro="WW2_British_Rifleman";
		scope=2;
		displayName="Machine Gunner(WW2)";
		faction="twc_faction";
		editorSubcategory = "Men_WW2";
		vehicleClass="Men_WW2";
		icon="iconManLeader";
		nakedUniform="U_BasicBody";
		uniformClass="U_mas_ww2_B_CombatUniform_uk";
		backpack="TWC_Backpack_WW2_MG";
		linkedItems[]=
		{
        "V_mas_ww2_vest_UK",
		"H_mas_ww2_helmet_uk_B",
		"ItemMap",
		"ItemCompass",
		"ItemWatch"
		};
		respawnLinkedItems[]=
		{
        "V_mas_ww2_vest_UK",
		"H_mas_ww2_helmet_uk_B",
		"ItemMap",
		"ItemCompass",
		"ItemWatch"
		};
		weapons[]=
		{
		"Throw",
		"Put",
		"I44_BrenMk1"
		};
		respawnweapons[]=
		{
		"Throw",
		"Put",
		"I44_BrenMk1"
		};
		magazines[]=
		{
		"I44_30rd_77x56R_Mix_Bren",
		"I44_30rd_77x56R_Mix_Bren",
		"I44_30rd_77x56R_Mix_Bren",
		"I44_30rd_77x56R_Mix_Bren",
		"I44_30rd_77x56R_Mix_Bren"
		};
		Respawnmagazines[]=
		{
		"I44_30rd_77x56R_Mix_Bren",
		"I44_30rd_77x56R_Mix_Bren",
		"I44_30rd_77x56R_Mix_Bren",
		"I44_30rd_77x56R_Mix_Bren",
		"I44_30rd_77x56R_Mix_Bren"
		};
		Items[]=
		{
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_morphine",
		"ACE_morphine",
		"ACE_epinephrine",
		"ACE_tourniquet",
		"ACE_EarPlugs"	
		};
		respawntems[]=
		{
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_morphine",
		"ACE_morphine",
		"ACE_epinephrine",
		"ACE_tourniquet",
		"ACE_EarPlugs"		
		};
	};
	class WW2_British_MGASS: B_Soldier_base_F
	{
		_generalMacro="WW2_British_MGASS";
		scope=2;
		displayName="Machine Gunner Assistant(WW2)";
		faction="twc_faction";
		editorSubcategory = "Men_WW2";
		vehicleClass="Men_WW2";
		icon="iconManLeader";
		nakedUniform="U_BasicBody";
		uniformClass="U_mas_ww2_B_CombatUniform_uk";
		backpack="TWC_Backpack_WW2_MG";
		linkedItems[]=
		{
        "V_mas_ww2_vest_UK",
		"H_mas_ww2_helmet_uk_B",
		"ItemMap",
		"ItemCompass",
		"ItemWatch"
		};
		respawnLinkedItems[]=
		{
        "V_mas_ww2_vest_UK",
		"H_mas_ww2_helmet_uk_B",
		"ItemMap",
		"ItemCompass",
		"ItemWatch"
		};
		weapons[]=
		{
		"Throw",
		"Put",
		"CUP_srifle_LeeEnfield"
		};
		respawnweapons[]=
		{
		"Throw",
		"Put",
		"CUP_srifle_LeeEnfield"
		};
		magazines[]=
		{
		"CUP_10x_303_M",
		"CUP_10x_303_M",
		"CUP_10x_303_M",
		"CUP_10x_303_M",
		"CUP_10x_303_M",
		"CUP_10x_303_M",
		"CUP_10x_303_M",
		"CUP_10x_303_M",
		"CUP_HandGrenade_L109A2_HE",
		"CUP_HandGrenade_L109A2_HE"
		};
		Respawnmagazines[]=
		{
		"CUP_10x_303_M",
		"CUP_10x_303_M",
		"CUP_10x_303_M",
		"CUP_10x_303_M",
		"CUP_10x_303_M",
		"CUP_10x_303_M",
		"CUP_10x_303_M",
		"CUP_10x_303_M",
		"CUP_HandGrenade_L109A2_HE",
		"CUP_HandGrenade_L109A2_HE"
		};
		Items[]=
		{
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_morphine",
		"ACE_morphine",
		"ACE_epinephrine",
		"ACE_tourniquet",
		"ACE_EarPlugs"	
		};
		respawntems[]=
		{
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_packingBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_elasticBandage",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_quikclot",
		"ACE_morphine",
		"ACE_morphine",
		"ACE_epinephrine",
		"ACE_tourniquet",
		"ACE_EarPlugs"		
		};
	};