	class BurIns_Base: O_Soldier_base_F
	{
		author="Saxon";
		scope=1;
		displayName="Burmese Insurgent Base";
		faction="TWC_OPFOR_BurIns";
		vehicleClass="TWC_BurIns_Men";
		uniformClass="U_I_C_Soldier_Para_5_F";
		nakedUniform="U_BasicBody";
		genericNames="ChineseMen";
		identityTypes[]=
		{
			"LanguageCHI_F",
			"Head_Asian",
			"G_CIVIL_male"
		};
	};
	class BurIns_Rifleman_Enfield: BurIns_Base
	{
		scope=2;
		scopeCurator = 2;
		displayName="Rifleman (Lee Enfield)";
		uniformClass="U_I_C_Soldier_Bandit_1_F";
		linkedItems[]=
		{
			"H_Hat_Safari_olive_F",
			"cwr3_i_vest_chicom",
			"ItemMap",
			"ItemCompass"
		};
		respawnLinkedItems[]=
		{
			"H_Hat_Safari_olive_F",
			"cwr3_i_vest_chicom",
			"ItemMap",
			"ItemCompass"
		};
		weapons[]=
		{
			"Throw",
			"Put",
			"CUP_srifle_LeeEnfield"
		};
		respawnweapons[]=
		{
			"Throw",
			"Put",
			"CUP_srifle_LeeEnfield"
		};
		magazines[]=
		{
			"CUP_10x_303_M",
			"CUP_10x_303_M",
			"CUP_10x_303_M",
			"CUP_10x_303_M",
			"CUP_10x_303_M",
			"CUP_10x_303_M",
			"CUP_10x_303_M",
			"CUP_HandGrenade_RGO",
			"SmokeShell"
		};
		Respawnmagazines[]=
		{
			"CUP_10x_303_M",
			"CUP_10x_303_M",
			"CUP_10x_303_M",
			"CUP_10x_303_M",
			"CUP_10x_303_M",
			"CUP_10x_303_M",
			"CUP_10x_303_M",
			"CUP_HandGrenade_RGO",
			"SmokeShell"
		};
	};
	class BurIns_Rifleman_Mosin: BurIns_Base
	{
		scope=2;
		scopeCurator = 2;
		displayName="Rifleman (Mosin-Nagant)";
		linkedItems[]=
		{
			"CUP_H_TKI_Lungee_Open_01",
			"cwr3_i_vest_chicom",
			"ItemMap",
			"ItemCompass"
		};
		respawnLinkedItems[]=
		{
			"CUP_H_TKI_Lungee_Open_01",
			"cwr3_i_vest_chicom",
			"ItemMap",
			"ItemCompass"
		};
		weapons[]=
		{
			"Throw",
			"Put",
			"CUP_srifle_Mosin_Nagant"
		};
		respawnweapons[]=
		{
			"Throw",
			"Put",
			"CUP_srifle_Mosin_Nagant"
		};
		magazines[]=
		{
			"CUP_5Rnd_762x54_Mosin_M",
			"CUP_5Rnd_762x54_Mosin_M",
			"CUP_5Rnd_762x54_Mosin_M",
			"CUP_5Rnd_762x54_Mosin_M",
			"CUP_5Rnd_762x54_Mosin_M",
			"CUP_5Rnd_762x54_Mosin_M",
			"CUP_5Rnd_762x54_Mosin_M",
			"CUP_5Rnd_762x54_Mosin_M",
			"CUP_5Rnd_762x54_Mosin_M",
			"CUP_5Rnd_762x54_Mosin_M",
			"CUP_5Rnd_762x54_Mosin_M",
			"CUP_HandGrenade_RGO",
			"SmokeShell"
		};
		Respawnmagazines[]=
		{
			"CUP_5Rnd_762x54_Mosin_M",
			"CUP_5Rnd_762x54_Mosin_M",
			"CUP_5Rnd_762x54_Mosin_M",
			"CUP_5Rnd_762x54_Mosin_M",
			"CUP_5Rnd_762x54_Mosin_M",
			"CUP_5Rnd_762x54_Mosin_M",
			"CUP_5Rnd_762x54_Mosin_M",
			"CUP_5Rnd_762x54_Mosin_M",
			"CUP_5Rnd_762x54_Mosin_M",
			"CUP_5Rnd_762x54_Mosin_M",
			"CUP_5Rnd_762x54_Mosin_M",
			"CUP_HandGrenade_RGO",
			"SmokeShell"
		};
	};
	class BurIns_Rifleman_SKS: BurIns_Base
	{
		scope=2;
		scopeCurator = 2;
		displayName="Rifleman (SKS)";
		linkedItems[]=
		{
			"H_Bandanna_gry",
			"cwr3_i_vest_chicom",
			"ItemMap",
			"ItemCompass"
		};
		respawnLinkedItems[]=
		{
			"H_Bandanna_gry",
			"cwr3_i_vest_chicom",
			"ItemMap",
			"ItemCompass"
		};
		weapons[]=
		{
			"Throw",
			"Put",
			"CUP_SKS"
		};
		respawnweapons[]=
		{
			"Throw",
			"Put",
			"CUP_SKS"
		};
		magazines[]=
		{
			"CUP_10Rnd_762x39_SKS_M",
			"CUP_10Rnd_762x39_SKS_M",
			"CUP_10Rnd_762x39_SKS_M",
			"CUP_10Rnd_762x39_SKS_M",
			"CUP_10Rnd_762x39_SKS_M",
			"CUP_10Rnd_762x39_SKS_M",
			"CUP_10Rnd_762x39_SKS_M",
			"CUP_HandGrenade_RGO",
			"SmokeShell"
		};
		Respawnmagazines[]=
		{
			"CUP_10Rnd_762x39_SKS_M",
			"CUP_10Rnd_762x39_SKS_M",
			"CUP_10Rnd_762x39_SKS_M",
			"CUP_10Rnd_762x39_SKS_M",
			"CUP_10Rnd_762x39_SKS_M",
			"CUP_10Rnd_762x39_SKS_M",
			"CUP_10Rnd_762x39_SKS_M",
			"CUP_HandGrenade_RGO",
			"SmokeShell"
		};
	};
	class BurIns_Rifleman_AK: BurIns_Base
	{
		scope=2;
		scopeCurator = 2;
		displayName="Rifleman (AK)";
		linkedItems[]=
		{
			"CUP_H_TKI_Lungee_Open_01",
			"cwr3_i_vest_chicom",
			"ItemMap",
			"ItemCompass"
		};
		respawnLinkedItems[]=
		{
			"CUP_H_SLA_Helmet_URB_worn",
			"cwr3_i_vest_chicom",
			"ItemMap",
			"ItemCompass"
		};
		weapons[]=
		{
			"Throw",
			"Put",
			"CUP_arifle_AK47_Early"
		};
		respawnweapons[]=
		{
			"Throw",
			"Put",
			"CUP_arifle_AK47_Early"
		};
		magazines[]=
		{
			"CUP_30Rnd_762x39_AK47_M",
			"CUP_30Rnd_762x39_AK47_M",
			"CUP_30Rnd_762x39_AK47_M",
			"CUP_30Rnd_762x39_AK47_M",
			"CUP_30Rnd_762x39_AK47_M",
			"CUP_30Rnd_762x39_AK47_M",
			"CUP_30Rnd_762x39_AK47_M",
			"CUP_HandGrenade_RGO",
			"SmokeShell"
		};
		Respawnmagazines[]=
		{
			"CUP_30Rnd_762x39_AK47_M",
			"CUP_30Rnd_762x39_AK47_M",
			"CUP_30Rnd_762x39_AK47_M",
			"CUP_30Rnd_762x39_AK47_M",
			"CUP_30Rnd_762x39_AK47_M",
			"CUP_30Rnd_762x39_AK47_M",
			"CUP_30Rnd_762x39_AK47_M",
			"CUP_HandGrenade_RGO",
			"SmokeShell"
		};
	};
	class BurIns_Rifleman_AKS: BurIns_Base
	{
		scope=2;
		scopeCurator = 2;
		displayName="Rifleman (AKS)";
		linkedItems[]=
		{
			"CUP_H_SLA_Helmet_OD_worn",
			"cwr3_i_vest_chicom",
			"ItemMap",
			"ItemCompass"
		};
		respawnLinkedItems[]=
		{
			"CUP_H_SLA_Helmet_OD_worn",
			"cwr3_i_vest_chicom",
			"ItemMap",
			"ItemCompass"
		};
		weapons[]=
		{
			"Throw",
			"Put",
			"CUP_arifle_AKS"
		};
		respawnweapons[]=
		{
			"Throw",
			"Put",
			"CUP_arifle_AKS"
		};
		magazines[]=
		{
			"CUP_30Rnd_762x39_AK47_M",
			"CUP_30Rnd_762x39_AK47_M",
			"CUP_30Rnd_762x39_AK47_M",
			"CUP_30Rnd_762x39_AK47_M",
			"CUP_30Rnd_762x39_AK47_M",
			"CUP_30Rnd_762x39_AK47_M",
			"CUP_30Rnd_762x39_AK47_M",
			"CUP_HandGrenade_RGO",
			"SmokeShell"
		};
		Respawnmagazines[]=
		{
			"CUP_30Rnd_762x39_AK47_M",
			"CUP_30Rnd_762x39_AK47_M",
			"CUP_30Rnd_762x39_AK47_M",
			"CUP_30Rnd_762x39_AK47_M",
			"CUP_30Rnd_762x39_AK47_M",
			"CUP_30Rnd_762x39_AK47_M",
			"CUP_30Rnd_762x39_AK47_M",
			"CUP_HandGrenade_RGO",
			"SmokeShell"
		};
	};
	class BurIns_MG_RPD: BurIns_Base
	{
		scope=2;
		scopeCurator = 2;
		displayName="Machinegunner (RPD)";
		linkedItems[]=
		{
			"CUP_H_SLA_Helmet_OD_worn",
			"cwr3_i_vest_chicom",
			"ItemMap",
			"ItemCompass"
		};
		respawnLinkedItems[]=
		{
			"CUP_H_SLA_Helmet_OD_worn",
			"cwr3_i_vest_chicom",
			"ItemMap",
			"ItemCompass"
		};
		weapons[]=
		{
			"Throw",
			"Put",
			"TWC_RPD"
		};
		respawnweapons[]=
		{
			"Throw",
			"Put",
			"TWC_RPD"
		};
		magazines[]=
		{
			"twc_100Rnd_762x39_RPD",
			"twc_100Rnd_762x39_RPD",
			"twc_100Rnd_762x39_RPD",
			"twc_100Rnd_762x39_RPD",
			"twc_100Rnd_762x39_RPD",
			"twc_100Rnd_762x39_RPD",
			"SmokeShell"
		};
		Respawnmagazines[]=
		{
			"twc_100Rnd_762x39_RPD",
			"twc_100Rnd_762x39_RPD",
			"twc_100Rnd_762x39_RPD",
			"twc_100Rnd_762x39_RPD",
			"twc_100Rnd_762x39_RPD",
			"twc_100Rnd_762x39_RPD",
			"SmokeShell"
		};
	};
	class BurIns_MG_Bren: BurIns_Base
	{
		scope=2;
		scopeCurator = 2;
		displayName="Machine Gunner (Bren)";
		uniformClass="U_I_C_Soldier_Bandit_1_F";
		linkedItems[]=
		{
			"CUP_H_TK_Lungee",
			"cwr3_i_vest_chicom",
			"ItemMap",
			"ItemCompass"
		};
		respawnLinkedItems[]=
		{
			"CUP_H_TK_Lungee",
			"cwr3_i_vest_chicom",
			"ItemMap",
			"ItemCompass"
		};
		weapons[]=
		{
			"Throw",
			"Put",
			"SP_l4_lmg"
		};
		respawnweapons[]=
		{
			"Throw",
			"Put",
			"SP_l4_lmg"
		};
		magazines[]=
		{
			"SP_30Rnd_762_L4",
			"SP_30Rnd_762_L4",
			"SP_30Rnd_762_L4",
			"SP_30Rnd_762_L4",
			"SP_30Rnd_762_L4",
			"SP_30Rnd_762_L4",
			"SP_30Rnd_762_L4",
			"SP_30Rnd_762_L4",
			"SP_30Rnd_762_L4",
			"SmokeShell"
		};
		Respawnmagazines[]=
		{
			"SP_30Rnd_762_L4",
			"SP_30Rnd_762_L4",
			"SP_30Rnd_762_L4",
			"SP_30Rnd_762_L4",
			"SP_30Rnd_762_L4",
			"SP_30Rnd_762_L4",
			"SP_30Rnd_762_L4",
			"SP_30Rnd_762_L4",
			"SP_30Rnd_762_L4",
			"SmokeShell"
		};
	};
	class BurIns_SMG_M3: BurIns_Base
	{
		scope=2;
		scopeCurator = 2;
		displayName="Submachine Gunner (M3)";
		linkedItems[]=
		{
			"CUP_H_SLA_Helmet_URB_worn",
			"cwr3_i_vest_chicom",
			"ItemMap",
			"ItemCompass"
		};
		respawnLinkedItems[]=
		{
			"CUP_H_SLA_Helmet_URB_worn",
			"cwr3_i_vest_chicom",
			"ItemMap",
			"ItemCompass"
		};
		weapons[]=
		{
			"Throw",
			"Put",
			"CUP_smg_M3A1_blk"
		};
		respawnweapons[]=
		{
			"Throw",
			"Put",
			"CUP_smg_M3A1_blk"
		};
		magazines[]=
		{
			"CUP_30Rnd_45ACP_M3A1_BLK_M",
			"CUP_30Rnd_45ACP_M3A1_BLK_M",
			"CUP_30Rnd_45ACP_M3A1_BLK_M",
			"CUP_30Rnd_45ACP_M3A1_BLK_M",
			"CUP_30Rnd_45ACP_M3A1_BLK_M",
			"CUP_30Rnd_45ACP_M3A1_BLK_M",
			"CUP_30Rnd_45ACP_M3A1_BLK_M",
			"CUP_30Rnd_45ACP_M3A1_BLK_M",
			"CUP_30Rnd_45ACP_M3A1_BLK_M",
			"CUP_HandGrenade_RGO",
			"CUP_HandGrenade_RGO",
			"SmokeShell"
		};
		Respawnmagazines[]=
		{
			"CUP_30Rnd_45ACP_M3A1_BLK_M",
			"CUP_30Rnd_45ACP_M3A1_BLK_M",
			"CUP_30Rnd_45ACP_M3A1_BLK_M",
			"CUP_30Rnd_45ACP_M3A1_BLK_M",
			"CUP_30Rnd_45ACP_M3A1_BLK_M",
			"CUP_30Rnd_45ACP_M3A1_BLK_M",
			"CUP_30Rnd_45ACP_M3A1_BLK_M",
			"CUP_30Rnd_45ACP_M3A1_BLK_M",
			"CUP_30Rnd_45ACP_M3A1_BLK_M",
			"CUP_HandGrenade_RGO",
			"CUP_HandGrenade_RGO",
			"SmokeShell"
		};
	};
	class BurIns_SMG_Sterling: BurIns_Base
	{
		scope=2;
		scopeCurator = 2;
		displayName="Submachine Gunner (Sterling)";
		uniformClass="U_I_C_Soldier_Bandit_1_F";
		linkedItems[]=
		{
			"CUP_H_SLA_Helmet_OD_worn",
			"cwr3_i_vest_chicom",
			"ItemMap",
			"ItemCompass"
		};
		respawnLinkedItems[]=
		{
			"CUP_H_SLA_Helmet_OD_worn",
			"cwr3_i_vest_chicom",
			"ItemMap",
			"ItemCompass"
		};
		weapons[]=
		{
			"Throw",
			"Put",
			"SP_smg_sterling_old"
		};
		respawnweapons[]=
		{
			"Throw",
			"Put",
			"SP_smg_sterling_old"
		};
		magazines[]=
		{
			"SP_30Rnd_9x19_L2A3_Sterling_old",
			"SP_30Rnd_9x19_L2A3_Sterling_old",
			"SP_30Rnd_9x19_L2A3_Sterling_old",
			"SP_30Rnd_9x19_L2A3_Sterling_old",
			"SP_30Rnd_9x19_L2A3_Sterling_old",
			"SP_30Rnd_9x19_L2A3_Sterling_old",
			"SP_30Rnd_9x19_L2A3_Sterling_old",
			"SP_30Rnd_9x19_L2A3_Sterling_old",
			"SP_30Rnd_9x19_L2A3_Sterling_old",
			"CUP_HandGrenade_RGO",
			"CUP_HandGrenade_RGO",
			"SmokeShell"
		};
		Respawnmagazines[]=
		{
			"SP_30Rnd_9x19_L2A3_Sterling_old",
			"SP_30Rnd_9x19_L2A3_Sterling_old",
			"SP_30Rnd_9x19_L2A3_Sterling_old",
			"SP_30Rnd_9x19_L2A3_Sterling_old",
			"SP_30Rnd_9x19_L2A3_Sterling_old",
			"SP_30Rnd_9x19_L2A3_Sterling_old",
			"SP_30Rnd_9x19_L2A3_Sterling_old",
			"SP_30Rnd_9x19_L2A3_Sterling_old",
			"SP_30Rnd_9x19_L2A3_Sterling_old",
			"CUP_HandGrenade_RGO",
			"CUP_HandGrenade_RGO",
			"SmokeShell"
		};
	};
	class BurIns_AT_Specialist_Mosin: BurIns_Rifleman_Mosin
	{
		scope=2;
		scopeCurator = 2;
		displayName="AT Specialist (Mosin-Nagant)";
		backpack="Afr_Backpack_AT";
		linkedItems[]=
		{
			"CUP_H_SLA_Helmet_URB_worn",
			"cwr3_i_vest_chicom",
			"ItemMap",
			"ItemCompass"
		};
		respawnLinkedItems[]=
		{
			"CUP_H_SLA_Helmet_URB_worn",
			"cwr3_i_vest_chicom",
			"ItemMap",
			"ItemCompass"
		};
		weapons[]=
		{
			"Throw",
			"Put",
			"CUP_srifle_Mosin_Nagant",
			"CUP_launch_RPG7V"
		};
		respawnweapons[]=
		{
			"Throw",
			"Put",
			"CUP_srifle_Mosin_Nagant",
			"CUP_launch_RPG7V"
		};
		magazines[]=
		{
			"CUP_5Rnd_762x54_Mosin_M",
			"CUP_5Rnd_762x54_Mosin_M",
			"CUP_5Rnd_762x54_Mosin_M",
			"CUP_5Rnd_762x54_Mosin_M",
			"CUP_5Rnd_762x54_Mosin_M",
			"CUP_5Rnd_762x54_Mosin_M",
			"CUP_5Rnd_762x54_Mosin_M",
			"CUP_5Rnd_762x54_Mosin_M",
			"CUP_5Rnd_762x54_Mosin_M",
			"CUP_5Rnd_762x54_Mosin_M",
			"CUP_5Rnd_762x54_Mosin_M",
			"CUP_HandGrenade_RGO",
			"SmokeShell",
			"CUP_PG7V_M"
		};
		Respawnmagazines[]=
		{
			"CUP_5Rnd_762x54_Mosin_M",
			"CUP_5Rnd_762x54_Mosin_M",
			"CUP_5Rnd_762x54_Mosin_M",
			"CUP_5Rnd_762x54_Mosin_M",
			"CUP_5Rnd_762x54_Mosin_M",
			"CUP_5Rnd_762x54_Mosin_M",
			"CUP_5Rnd_762x54_Mosin_M",
			"CUP_5Rnd_762x54_Mosin_M",
			"CUP_5Rnd_762x54_Mosin_M",
			"CUP_5Rnd_762x54_Mosin_M",
			"CUP_5Rnd_762x54_Mosin_M",
			"CUP_HandGrenade_RGO",
			"SmokeShell",
			"CUP_PG7V_M"
		};
	};
	class BurIns_AT_Specialist_M3: BurIns_SMG_M3
	{
		scope=2;
		scopeCurator = 2;
		displayName="AT Specialist (M3)";
		backpack="Afr_Backpack_AT";
		linkedItems[]=
		{
			"CUP_H_SLA_Helmet_OB",
			"cwr3_i_vest_chicom",
			"ItemMap",
			"ItemCompass"
		};
		respawnLinkedItems[]=
		{
			"CUP_H_SLA_Helmet_OB",
			"cwr3_i_vest_chicom",
			"ItemMap",
			"ItemCompass"
		};
		weapons[]=
		{
			"Throw",
			"Put",
			"CUP_smg_M3A1_blk",
			"CUP_launch_RPG7V"
		};
		respawnweapons[]=
		{
			"Throw",
			"Put",
			"CUP_smg_M3A1_blk",
			"CUP_launch_RPG7V"
		};
		magazines[]=
		{
			"CUP_30Rnd_45ACP_M3A1_BLK_M",
			"CUP_30Rnd_45ACP_M3A1_BLK_M",
			"CUP_30Rnd_45ACP_M3A1_BLK_M",
			"CUP_30Rnd_45ACP_M3A1_BLK_M",
			"CUP_30Rnd_45ACP_M3A1_BLK_M",
			"CUP_30Rnd_45ACP_M3A1_BLK_M",
			"CUP_30Rnd_45ACP_M3A1_BLK_M",
			"CUP_30Rnd_45ACP_M3A1_BLK_M",
			"CUP_30Rnd_45ACP_M3A1_BLK_M",
			"CUP_HandGrenade_RGO",
			"SmokeShell",
			"CUP_PG7V_M"
		};
		Respawnmagazines[]=
		{
			"CUP_30Rnd_45ACP_M3A1_BLK_M",
			"CUP_30Rnd_45ACP_M3A1_BLK_M",
			"CUP_30Rnd_45ACP_M3A1_BLK_M",
			"CUP_30Rnd_45ACP_M3A1_BLK_M",
			"CUP_30Rnd_45ACP_M3A1_BLK_M",
			"CUP_30Rnd_45ACP_M3A1_BLK_M",
			"CUP_30Rnd_45ACP_M3A1_BLK_M",
			"CUP_30Rnd_45ACP_M3A1_BLK_M",
			"CUP_30Rnd_45ACP_M3A1_BLK_M",
			"CUP_HandGrenade_RGO",
			"SmokeShell",
			"CUP_PG7V_M"
		};
	};
	class BurIns_AA_Specialist: BurIns_Rifleman_Enfield
	{
		scope=2;
		scopeCurator = 2;
		displayName="AA Specialist";
		linkedItems[]=
		{
			"CUP_H_TKI_Lungee_Open_01",
			"cwr3_i_vest_chicom",
			"ItemMap",
			"ItemCompass"
		};
		respawnLinkedItems[]=
		{
			"CUP_H_TKI_Lungee_Open_01",
			"cwr3_i_vest_chicom",
			"ItemMap",
			"ItemCompass"
		};
		weapons[]=
		{
			"Throw",
			"Put",
			"CUP_srifle_LeeEnfield",
			"CUP_launch_9K32Strela"
		};
		respawnweapons[]=
		{
			"Throw",
			"Put",
			"CUP_srifle_LeeEnfield",
			"CUP_launch_9K32Strela"
		};
		magazines[]=
		{
			"CUP_10x_303_M",
			"CUP_10x_303_M",
			"CUP_10x_303_M",
			"CUP_10x_303_M",
			"CUP_10x_303_M",
			"CUP_10x_303_M",
			"CUP_10x_303_M",
			"SmokeShell"
		};
		Respawnmagazines[]=
		{
			"CUP_10x_303_M",
			"CUP_10x_303_M",
			"CUP_10x_303_M",
			"CUP_10x_303_M",
			"CUP_10x_303_M",
			"CUP_10x_303_M",
			"CUP_10x_303_M",
			"SmokeShell"
		};
	};
	class BurIns_Crew: BurIns_SMG_M3
	{
		scope=2;
		scopeCurator = 2;
		displayName="Crewman";
		uniformClass="cwr3_b_uniform_tanksuit";
		linkedItems[]=
		{
			"cwr3_o_headgear_tsh3",
			"cwr3_o_vest_beltkit_ak74",
			"ItemMap",
			"ItemCompass"
		};
		respawnLinkedItems[]=
		{
			"cwr3_o_headgear_tsh3",
			"cwr3_o_vest_beltkit_ak74",
			"ItemMap",
			"ItemCompass"
		};
		magazines[]=
		{
			"CUP_30Rnd_45ACP_M3A1_BLK_M",
			"CUP_30Rnd_45ACP_M3A1_BLK_M",
			"CUP_30Rnd_45ACP_M3A1_BLK_M",
			"CUP_30Rnd_45ACP_M3A1_BLK_M",
			"CUP_HandGrenade_RGO",
			"SmokeShell"
		};
		Respawnmagazines[]=
		{
			"CUP_30Rnd_45ACP_M3A1_BLK_M",
			"CUP_30Rnd_45ACP_M3A1_BLK_M",
			"CUP_30Rnd_45ACP_M3A1_BLK_M",
			"CUP_30Rnd_45ACP_M3A1_BLK_M",
			"CUP_HandGrenade_RGO",
			"SmokeShell"
		};
	};