class FARC_Base: O_Soldier_base_F
{
	author="Sarge";
	scope=1;
	displayName="Soldier Base";
	faction="TWC_FARC_Units";
	editorSubcategory = "TWC_FARC_Men";
	vehicleClass="TWC_FARC_Men";
	nakedUniform="U_BasicBody";
	uniformClass="CUP_U_O_SLA_Green";
	
};
class FARC_RiflemanAKM: FARC_Base
{
	scope=2;
	scopeCurator = 2;
	displayName="Rifleman (AKM)";
	linkedItems[]=
	{
		"CUP_V_O_Ins_Carrier_Rig_Light",
		"CUP_H_ChDKZ_Beret",
		"ItemCompass",
		"ItemWatch"
	};
	respawnLinkedItems[]=
	{
		"CUP_V_O_Ins_Carrier_Rig_Light",
		"CUP_H_ChDKZ_Beret",
		"ItemCompass",
		"ItemWatch"
	};
	Weapons[]=
	{
		"CUP_arifle_AKM_Early",
		"Throw",
		"Put"
	};
	respawnWeapons[]=
	{
		"CUP_arifle_AKM_Early",
		"Throw",
		"Put"
	};
	magazines[]=
	{
		MAG_7("CUP_30Rnd_762x39_AK47_bakelite_M"),
		"CUP_HandGrenade_RGD5",
		"CUP_HandGrenade_RGD5",
		"SmokeShell"
	};
	respawnMagazines[]=
	{
		MAG_7("CUP_30Rnd_762x39_AK47_bakelite_M"),
		"CUP_HandGrenade_RGD5",
		"CUP_HandGrenade_RGD5",
		"SmokeShell"
	};
	Items[]=
	{
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_morphine",
		"ACE_morphine",
		"ACE_EarPlugs"
	};
	respawnItems[]=
	{
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_morphine",
		"ACE_morphine",
		"ACE_EarPlugs"
	};
};

class FARC_RiflemanM16: FARC_Base
{
	scope=2;
	scopeCurator = 2;
	displayName="Rifleman (M16)";
	linkedItems[]=
	{
		"CUP_V_O_Ins_Carrier_Rig_Light",
		"CUP_H_ChDKZ_Beret",
		"ItemCompass",
		"ItemWatch"
	};
	respawnLinkedItems[]=
	{
		"CUP_V_O_Ins_Carrier_Rig_Light",
		"CUP_H_ChDKZ_Beret",
		"ItemCompass",
		"ItemWatch"
	};
	Weapons[]=
	{
		"CUP_arifle_M16A2",
		"Throw",
		"Put"
	};
	respawnWeapons[]=
	{
		"CUP_arifle_M16A2",
		"Throw",
		"Put"
	};
	magazines[]=
	{
		MAG_7("CUP_30Rnd_556x45_Stanag"),
		"CUP_HandGrenade_RGD5",
		"CUP_HandGrenade_RGD5",
		"SmokeShell"
	};
	Respawnmagazines[]=
	{
		MAG_7("CUP_30Rnd_556x45_Stanag"),
		"CUP_HandGrenade_RGD5",
		"CUP_HandGrenade_RGD5",
		"SmokeShell"
	};
	Items[]=
	{
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_morphine",
		"ACE_morphine",
		"ACE_EarPlugs"
	};
	respawnItems[]=
	{
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_morphine",
		"ACE_morphine",
		"ACE_EarPlugs"
	};
};

class FARC_AT_Assistant: FARC_RiflemanAKM
{
	scope=2;
	scopeCurator = 2;
	displayName="AT-Assistant";
	backpack="Afr_Backpack_AT";
};

class FARC_RiflemanAT: FARC_RiflemanAKM
{
	scope=2;
	scopeCurator = 2;
	displayName="Rifleman AT";
	icon="iconManAT";
	backpack="Afr_Backpack_AT";
	Weapons[]=
	{
		"Throw",
		"Put",
		"CUP_arifle_AKM_Early",
		"CUP_launch_RPG7V"
	};
	respawnWeapons[]=
	{
		"Throw",
		"Put",
		"CUP_arifle_AKM_Early",
		"CUP_launch_RPG7V"
	};
};

class FARC_Machinegunner: FARC_Base
{
	scope=2;
	scopeCurator = 2;
	displayName="Machinegunner";
	backpack="Afr_Backpack_MG";
	icon="iconManMG";
	linkedItems[]=
	{
		"CUP_V_O_Ins_Carrier_Rig_MG",
		"CUP_H_ChDKZ_Beret",
		"ItemCompass",
		"ItemWatch"
	};
	respawnLinkedItems[]=
	{
		"CUP_V_O_Ins_Carrier_Rig_MG",
		"CUP_H_ChDKZ_Beret",
		"ItemCompass",
		"ItemWatch"
	};
	weapons[]=
	{
		"CUP_lmg_PKM",
		"Throw",
		"Put"
	};
	respawnweapons[]=
	{
		"CUP_lmg_PKM",
		"Throw",
		"Put"
	};
	magazines[]=
	{
		"CUP_100Rnd_TE4_LRT4_762x54_PK_Tracer_Green_M",
		"CUP_100Rnd_TE4_LRT4_762x54_PK_Tracer_Green_M",
		"CUP_HandGrenade_RGD5",
		"SmokeShell"
	};
	respawnMagazines[]=
	{
		"CUP_100Rnd_TE4_LRT4_762x54_PK_Tracer_Green_M",
		"CUP_100Rnd_TE4_LRT4_762x54_PK_Tracer_Green_M",
		"CUP_HandGrenade_RGD5",
		"SmokeShell"
	};
	Items[]=
	{
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_morphine",
		"ACE_morphine",
		"ACE_EarPlugs"
	};
	respawnItems[]=
	{
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_morphine",
		"ACE_morphine",
		"ACE_EarPlugs"
	};
};
class FARC_Grenadier: FARC_Base
{
	scope=2;
	scopeCurator = 2;
	displayName="Grenadier";
	linkedItems[]=
	{
		"CUP_V_O_Ins_Carrier_Rig",
		"CUP_H_ChDKZ_Beret",
		"ItemCompass",
		"ItemWatch"
	};
	respawnLinkedItems[]=
	{
		"CUP_V_O_Ins_Carrier_Rig",
		"CUP_H_ChDKZ_Beret",
		"ItemCompass",
		"ItemWatch"
	};
	weapons[]=
	{
		"CUP_arifle_M16A2_GL",
		"Throw",
		"Put"
	};
	respawnWeapons[]=
	{
		"CUP_arifle_M16A2_GL",
		"Throw",
		"Put"
	};
	magazines[]=
	{
		MAG_6("CUP_30Rnd_556x45_Stanag"),
		MAG_6("CUP_1Rnd_HE_M203"),
		"SmokeShell",
		"SmokeShell"
	};
	RespawnMagazines[]=
	{
		MAG_6("CUP_30Rnd_556x45_Stanag"),
		MAG_6("CUP_1Rnd_HE_M203"),
		"SmokeShell",
		"SmokeShell"
	};
	Items[]=
	{
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_morphine",
		"ACE_morphine",
		"ACE_EarPlugs"
	};
	respawnItems[]=
	{
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_morphine",
		"ACE_morphine",
		"ACE_EarPlugs"
	};
};
class FARC_Squadleader: FARC_RiflemanAKM
{
	scope=2;
	scopeCurator = 2;
	displayName="Squadleader";
	icon="iconManLeader";
	linkedItems[]=
	{
		"CUP_V_O_Ins_Carrier_Rig_Com",
		"CUP_H_ChDKZ_Beret",
		"ItemCompass",
		"ItemWatch",
		"ItemRadio"
	};
	respawnLinkedItems[]=
	{
		"CUP_V_O_Ins_Carrier_Rig_Com",
		"CUP_H_ChDKZ_Beret",
		"ItemCompass",
		"ItemWatch",
		"ItemRadio"
	};
	weapons[] =
	{
		"CUP_arifle_Galil_SAR_black",
		"Binocular",
		"Throw",
		"Put"
	};
	respawnWeapons[] =
	{
		"CUP_arifle_Galil_SAR_black",
		"Binocular",
		"Throw",
		"Put"
	};
	magazines[]=
	{
		MAG_7("CUP_35Rnd_556x45_Galil_Mag"),
		"CUP_HandGrenade_RGD5",
		"CUP_HandGrenade_RGD5",
		"SmokeShell",
		"SmokeShell"
	};
	RespawnMagazines[]=
	{
		MAG_7("CUP_35Rnd_556x45_Galil_Mag"),
		"CUP_HandGrenade_RGD5",
		"CUP_HandGrenade_RGD5",
		"SmokeShell",
		"SmokeShell"
	};
};
class FARC_Officer: FARC_Squadleader
{
	scope=2;
	scopeCurator = 2;
	displayName="Officer";
	icon="iconManOfficer";
	linkedItems[]=
	{
		"CUP_V_O_Ins_Carrier_Rig_Com",
		"CUP_H_SLA_Beret",
		"ItemCompass",
		"ItemWatch",
		"ItemRadio"
	};
	respawnLinkedItems[]=
	{
		"CUP_V_O_Ins_Carrier_Rig_Com",
		"CUP_H_SLA_Beret",
		"ItemCompass",
		"ItemWatch",
		"ItemRadio"
	};
	weapons[] =
	{
		"CUP_arifle_M4A1",
		"Binocular",
		"Throw",
		"Put"
	};
	respawnWeapons[] =
	{
		"CUP_arifle_M4A1",
		"Binocular",
		"Throw",
		"Put"
	};
	magazines[]=
	{
		MAG_7("CUP_30Rnd_556x45_Stanag"),
		"CUP_HandGrenade_RGD5",
		"SmokeShell",
		"SmokeShell"
	};
	RespawnMagazines[]=
	{
		MAG_7("CUP_30Rnd_556x45_Stanag"),
		"CUP_HandGrenade_RGD5",
		"SmokeShell",
		"SmokeShell"
	};
};