	class GulfWar_Iraqi_Squadleader: O_Soldier_base_F
	{
		_generalMacro="GulfWar_Iraqi_Squadleader";
		scope=2;
		displayName="Section Leader";
		faction="TWC_OPFOR_Units_Iraq";
		editorSubcategory = "Men_Iraq";
		vehicleClass="Men_Iraq";
		icon="iconManLeader";
		nakedUniform="U_BasicBody";
		uniformClass="CUP_U_O_TK_Green";
		backpack="";
		linkedItems[]=
		{
			"CUP_V_B_GER_Carrier_Rig_2_Brown",
			"CUP_H_SLA_Helmet",
			"ItemMap",
			"ItemCompass",
			"ItemWatch"
		};
		respawnLinkedItems[]=
		{
			"CUP_V_B_GER_Carrier_Rig_2_Brown",
			"ItemMap",
			"ItemCompass",
			"ItemWatch"
		};
		weapons[]=
		{
			"Throw",
			"Put",
			"Binocular",
			"CUP_arifle_AK74",
			"CUP_hgun_Makarov"
		};
		respawnweapons[]=
		{
			"Throw",
			"Put",
			"Binocular",
			"CUP_arifle_AK74",
			"CUP_hgun_Makarov"
		};
		magazines[]=
		{
			"CUP_30Rnd_545x39_AK_M",
			"CUP_30Rnd_545x39_AK_M",
			"CUP_30Rnd_545x39_AK_M",
			"CUP_30Rnd_545x39_AK_M",
			"CUP_30Rnd_545x39_AK_M",
			"CUP_30Rnd_545x39_AK_M",
			"CUP_30Rnd_545x39_AK_M",
			"CUP_30Rnd_545x39_AK_M",
			"CUP_8Rnd_9x18_Makarov_M",
			"CUP_HandGrenade_RGO",
			"CUP_HandGrenade_RGO"
		};
		Respawnmagazines[]=
		{
			"CUP_30Rnd_545x39_AK_M",
			"CUP_30Rnd_545x39_AK_M",
			"CUP_30Rnd_545x39_AK_M",
			"CUP_30Rnd_545x39_AK_M",
			"CUP_30Rnd_545x39_AK_M",
			"CUP_30Rnd_545x39_AK_M",
			"CUP_30Rnd_545x39_AK_M",
			"CUP_30Rnd_545x39_AK_M",
			"CUP_8Rnd_9x18_Makarov_M",
			"CUP_HandGrenade_RGO",
			"CUP_HandGrenade_RGO"
		};
		Items[]=
		{
			"ACE_fieldDressing",
			"ACE_fieldDressing",
			"ACE_fieldDressing",
			"ACE_fieldDressing",
			"ACE_fieldDressing",
			"ACE_morphine",
			"ACE_morphine",
			"ACE_EarPlugs"
		};
		respawntems[]=
		{
			"ACE_fieldDressing",
			"ACE_fieldDressing",
			"ACE_fieldDressing",
			"ACE_fieldDressing",
			"ACE_fieldDressing",
			"ACE_morphine",
			"ACE_morphine",
			"ACE_EarPlugs"
		};
	};
	
	class GulfWar_Iraqi_Rifleman: O_Soldier_base_F
	{
		_generalMacro="GulfWar_Iraqi_Rifleman";
		scope=2;
		displayName="Rifleman";
		faction="TWC_OPFOR_Units_Iraq";
		editorSubcategory = "Men_Iraq";
		vehicleClass="Men_Iraq";
		icon="iconMan";
		nakedUniform="U_BasicBody";
		uniformClass="CUP_U_O_TK_Green";
		backpack="";
		linkedItems[]=
		{
			"CUP_V_B_GER_Carrier_Rig_2_Brown",
		"CUP_H_SLA_Helmet"
		};
		respawnLinkedItems[]=
		{
			"CUP_V_B_GER_Carrier_Rig_2_Brown"
		};
		weapons[]=
		{
			"Throw",
			"Put",
			"CUP_arifle_AK74",
			"CUP_hgun_Makarov"
		};
		respawnweapons[]=
		{
			"Throw",
			"Put",
			"CUP_arifle_AK74",
			"CUP_hgun_Makarov"
		};
		magazines[]=
		{
			"CUP_30Rnd_545x39_AK_M",
			"CUP_30Rnd_545x39_AK_M",
			"CUP_30Rnd_545x39_AK_M",
			"CUP_30Rnd_545x39_AK_M",
			"CUP_30Rnd_545x39_AK_M",
			"CUP_30Rnd_545x39_AK_M",
			"CUP_30Rnd_545x39_AK_M",
			"CUP_30Rnd_545x39_AK_M",
			"CUP_8Rnd_9x18_Makarov_M",
			"CUP_HandGrenade_RGO",
			"CUP_HandGrenade_RGO",
			"SmokeShell",
			"SmokeShell"
		};
		Respawnmagazines[]=
		{
			"CUP_30Rnd_545x39_AK_M",
			"CUP_30Rnd_545x39_AK_M",
			"CUP_30Rnd_545x39_AK_M",
			"CUP_30Rnd_545x39_AK_M",
			"CUP_30Rnd_545x39_AK_M",
			"CUP_30Rnd_545x39_AK_M",
			"CUP_30Rnd_545x39_AK_M",
			"CUP_30Rnd_545x39_AK_M",
			"CUP_8Rnd_9x18_Makarov_M",
			"CUP_HandGrenade_RGO",
			"CUP_HandGrenade_RGO",
			"SmokeShell",
			"SmokeShell"
		};
		Items[]=
		{
			"ACE_fieldDressing",
			"ACE_fieldDressing",
			"ACE_fieldDressing",
			"ACE_fieldDressing",
			"ACE_fieldDressing",
			"ACE_morphine",
			"ACE_morphine",
			"ACE_EarPlugs"
		};
		respawntems[]=
		{
			"ACE_fieldDressing",
			"ACE_fieldDressing",
			"ACE_fieldDressing",
			"ACE_fieldDressing",
			"ACE_fieldDressing",
			"ACE_morphine",
			"ACE_morphine",
			"ACE_EarPlugs"
		};
	};

	class GulfWar_Iraqi_RPG: O_Soldier_base_F
	{
		_generalMacro="GulfWar_Iraqi_RPG";
		scope=2;
		displayName="RPG Gunner";
		faction="TWC_OPFOR_Units_Iraq";
		editorSubcategory = "Men_Iraq";
		vehicleClass="Men_Iraq";
		icon="iconManExplosive";
		nakedUniform="U_BasicBody";
		uniformClass="CUP_U_O_TK_Green";
		backpack="Afr_Backpack_AT";
		linkedItems[]=
		{
        "CUP_V_B_GER_Carrier_Rig_2_Brown",
		"CUP_H_SLA_Helmet"
		};
		respawnLinkedItems[]=
		{
        "CUP_V_B_GER_Carrier_Rig_2_Brown"
		};
		weapons[]=
		{
		"Throw",
		"Put",
		"CUP_arifle_AK74",
		"CUP_hgun_Makarov",
		"CUP_launch_RPG7V"
		};
		respawnweapons[]=
		{
		"Throw",
		"Put",
		"CUP_arifle_AK74",
		"CUP_hgun_Makarov",
		"CUP_launch_RPG7V"
		};
		magazines[]=
		{
		"CUP_30Rnd_545x39_AK_M",
		"CUP_30Rnd_545x39_AK_M",		
		"CUP_30Rnd_545x39_AK_M",
		"CUP_30Rnd_545x39_AK_M",
		"CUP_30Rnd_545x39_AK_M",
		"CUP_30Rnd_545x39_AK_M",	
		"CUP_30Rnd_545x39_AK_M",	
		"CUP_30Rnd_545x39_AK_M",
		"CUP_8Rnd_9x18_Makarov_M",
		"CUP_PG7V_M",
		"CUP_PG7V_M",
		"CUP_PG7V_M",
		"CUP_PG7V_M",
		"CUP_HandGrenade_RGO",
		"CUP_HandGrenade_RGO",
		"SmokeShell",
		"SmokeShell"
		};
		Respawnmagazines[]=
		{
		"CUP_30Rnd_545x39_AK_M",
		"CUP_30Rnd_545x39_AK_M",		
		"CUP_30Rnd_545x39_AK_M",
		"CUP_30Rnd_545x39_AK_M",
		"CUP_30Rnd_545x39_AK_M",
		"CUP_30Rnd_545x39_AK_M",	
		"CUP_30Rnd_545x39_AK_M",	
		"CUP_30Rnd_545x39_AK_M",
		"CUP_8Rnd_9x18_Makarov_M",
		"CUP_HandGrenade_RGO",
		"CUP_HandGrenade_RGO",
		"SmokeShell",
		"SmokeShell"
		};
		Items[]=
		{
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_morphine",
		"ACE_morphine",
		"ACE_EarPlugs"
		};
		respawntems[]=
		{
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_morphine",
		"ACE_morphine",
		"ACE_EarPlugs"	
		};
	};

	class GulfWar_Iraqi_RPGAssistant: O_Soldier_base_F
	{
		_generalMacro="GulfWar_Iraqi_RPGAssistant";
		scope=2;
		displayName="RPG Assistant";
		faction="TWC_OPFOR_Units_Iraq";
		editorSubcategory = "Men_Iraq";
		vehicleClass="Men_Iraq";
		icon="iconManMG";
		nakedUniform="U_BasicBody";
		uniformClass="CUP_U_O_TK_Green";
		backpack="Afr_Backpack_AT";
		linkedItems[]=
		{
        "CUP_V_B_GER_Carrier_Rig_2_Brown",
		"CUP_H_SLA_Helmet"
		};
		respawnLinkedItems[]=
		{
        "CUP_V_B_GER_Carrier_Rig_2_Brown"
		};
		weapons[]=
		{
		"Throw",
		"Put",
		"CUP_arifle_AK74",
		"CUP_hgun_Makarov"
		};
		respawnweapons[]=
		{
		"Throw",
		"Put",
		"CUP_arifle_AK74",
		"CUP_hgun_Makarov"
		};
		magazines[]=
		{
		"CUP_30Rnd_545x39_AK_M",
		"CUP_30Rnd_545x39_AK_M",
		"CUP_30Rnd_545x39_AK_M",
		"CUP_30Rnd_545x39_AK_M",
		"CUP_30Rnd_545x39_AK_M",
		"CUP_30Rnd_545x39_AK_M",
		"CUP_30Rnd_545x39_AK_M",
		"CUP_30Rnd_545x39_AK_M",
		"CUP_8Rnd_9x18_Makarov_M",
		"CUP_PG7V_M",
		"CUP_PG7V_M",
		"CUP_PG7V_M",
		"CUP_HandGrenade_RGO",
		"CUP_HandGrenade_RGO",
		"SmokeShell",
		"SmokeShell"
		};
		Respawnmagazines[]=
		{
		"CUP_30Rnd_545x39_AK_M",
		"CUP_30Rnd_545x39_AK_M",
		"CUP_30Rnd_545x39_AK_M",
		"CUP_30Rnd_545x39_AK_M",
		"CUP_30Rnd_545x39_AK_M",
		"CUP_30Rnd_545x39_AK_M",
		"CUP_30Rnd_545x39_AK_M",
		"CUP_30Rnd_545x39_AK_M",
		"CUP_8Rnd_9x18_Makarov_M",
		"CUP_HandGrenade_RGO",
		"CUP_HandGrenade_RGO",
		"SmokeShell",
		"SmokeShell"
		};
		Items[]=
		{
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_morphine",
		"ACE_morphine",
		"ACE_EarPlugs"
		};
		respawntems[]=
		{
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_morphine",
		"ACE_morphine",
		"ACE_EarPlugs"		
		};
	};

	class GulfWar_Iraqi_MG: O_Soldier_base_F
	{
		_generalMacro="GulfWar_Iraqi_MG";
		scope=2;
		displayName="Machinegunner";
		faction="TWC_OPFOR_Units_Iraq";
		editorSubcategory = "Men_Iraq";
		vehicleClass="Men_Iraq";
		icon="iconMan";
		nakedUniform="U_BasicBody";
		uniformClass="CUP_U_O_TK_Green";
		backpack="";
		linkedItems[]=
		{
			"CUP_V_B_GER_Carrier_Rig_2_Brown",
			"CUP_H_SLA_Helmet"
		};
		respawnLinkedItems[]=
		{
			"CUP_V_B_GER_Carrier_Rig_2_Brown",
			"CUP_H_SLA_Helmet"
		};
		weapons[]=
		{
			"Throw",
			"Put",
			"CUP_arifle_RPK74",
			"CUP_hgun_Makarov"
		};
		respawnweapons[]=
		{
			"Throw",
			"Put",
			"CUP_arifle_RPK74",
			"CUP_hgun_Makarov"
		};
		magazines[]=
		{
			"CUP_75Rnd_TE4_LRT4_Green_Tracer_762x39_RPK_M",
			"CUP_75Rnd_TE4_LRT4_Green_Tracer_762x39_RPK_M",
			"CUP_75Rnd_TE4_LRT4_Green_Tracer_762x39_RPK_M",
			"CUP_75Rnd_TE4_LRT4_Green_Tracer_762x39_RPK_M",
			"CUP_8Rnd_9x18_Makarov_M",
			"CUP_HandGrenade_RGO",
			"CUP_HandGrenade_RGO",
			"SmokeShell",
			"SmokeShell"
		};
		Respawnmagazines[]=
		{
			"CUP_75Rnd_TE4_LRT4_Green_Tracer_762x39_RPK_M",
			"CUP_75Rnd_TE4_LRT4_Green_Tracer_762x39_RPK_M",
			"CUP_75Rnd_TE4_LRT4_Green_Tracer_762x39_RPK_M",
			"CUP_75Rnd_TE4_LRT4_Green_Tracer_762x39_RPK_M",
			"CUP_8Rnd_9x18_Makarov_M",
			"CUP_HandGrenade_RGO",
			"CUP_HandGrenade_RGO",
			"SmokeShell",
			"SmokeShell"
		};
		Items[]=
		{
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_morphine",
		"ACE_morphine",
		"ACE_EarPlugs"
		};
		respawntems[]=
		{
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_morphine",
		"ACE_morphine",
		"ACE_EarPlugs"
		};
	};

	class GulfWar_Iraqi_MGAssistant: O_Soldier_base_F
	{
		_generalMacro="GulfWar_Iraqi_MachinegunnerAssistant";
		scope=2;
		displayName="MG Assistant";
		faction="TWC_OPFOR_Units_Iraq";
		editorSubcategory = "Men_Iraq";
		vehicleClass="Men_Iraq";
		icon="iconMan";
		nakedUniform="U_BasicBody";
		uniformClass="CUP_U_O_TK_Green";
		backpack="";
		linkedItems[]=
		{
        "CUP_V_B_GER_Carrier_Rig_2_Brown",
		"CUP_H_SLA_Helmet"
		};
		respawnLinkedItems[]=
		{
        "CUP_V_B_GER_Carrier_Rig_2_Brown"
		};
		weapons[]=
		{
		"Throw",
		"Put",	
		"CUP_arifle_AK74",
		"CUP_hgun_Makarov"
		};
		respawnweapons[]=
		{
		"Throw",
		"Put",	
		"CUP_arifle_AK74",
		"CUP_hgun_Makarov"
		};
		magazines[]=
		{
			"CUP_30Rnd_545x39_AK_M",
			"CUP_30Rnd_545x39_AK_M",
			"CUP_30Rnd_545x39_AK_M",
			"CUP_30Rnd_545x39_AK_M",
			"CUP_75Rnd_TE4_LRT4_Green_Tracer_762x39_RPK_M",
			"CUP_75Rnd_TE4_LRT4_Green_Tracer_762x39_RPK_M",
			"CUP_8Rnd_9x18_Makarov_M",
			"CUP_HandGrenade_RGO",
			"CUP_HandGrenade_RGO",
			"SmokeShell",
			"SmokeShell"
		};
		Respawnmagazines[]=
		{
			"CUP_30Rnd_545x39_AK_M",
			"CUP_30Rnd_545x39_AK_M",
			"CUP_30Rnd_545x39_AK_M",
			"CUP_30Rnd_545x39_AK_M",
			"CUP_75Rnd_TE4_LRT4_Green_Tracer_762x39_RPK_M",
			"CUP_75Rnd_TE4_LRT4_Green_Tracer_762x39_RPK_M",
			"CUP_8Rnd_9x18_Makarov_M",
			"CUP_HandGrenade_RGO",
			"CUP_HandGrenade_RGO",
			"SmokeShell",
			"SmokeShell"
		};
		Items[]=
		{
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_morphine",
		"ACE_morphine",
		"ACE_EarPlugs"
		};
		respawntems[]=
		{
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_fieldDressing",
		"ACE_morphine",
		"ACE_morphine",
		"ACE_EarPlugs"
		};
	};