cacheListA = ["CACHEA1", "CACHEA2","CACHEA3", "CACHEA4", "CACHEA5", "CACHEA6", "CACHEA7", "CACHEA8"];

cacheListB = ["CACHEB1", "CACHEB2","CACHEB3", "CACHEB4", "CACHEB5", "CACHEB6", "CACHEB7", "CACHEB8"];

//cacheListC = ["CACHEC1", "CACHEC2","CACHEC3", "CACHEC4", "CACHEC5", "CACHEC6", "CACHEC7", "CACHEC8"];

cacheListD = ["CACHED1", "CACHED2","CACHED3", "CACHED4", "CACHED5", "CACHED6", "CACHED7", "CACHED8"];

cacheListE = ["CACHEE1", "CACHEE2","CACHEE3", "CACHEE4", "CACHEE5", "CACHEE6", "CACHEE7", "CACHEE8"];