class Afr_Mil_Base: O_Soldier_base_F
	{
		_generalMacro="Afr_Militia_Base";
		author="Saxon";
		scope=1;
		displayName="Soldier Base";
		faction="african_units";
		vehicleClass="Men_AfricanMilitia";
		nakedUniform="U_BasicBody";
		uniformClass="CUP_U_O_SLA_MixedCamo";
		genericNames="AfroMen";
		identityTypes[]=
		{
			"LanguagePER_F",
			"Head_African",
			"G_GUERIL_default"
		};
		
	};
	class Afr_Mil_Rifleman: Afr_Mil_Base
	{
		scope=2;
		scopeCurator = 2;
		displayName="Rifleman";
		backpack="Afr_Backpack_Rifleman";
		linkedItems[]=
		{
			"CUP_V_O_SLA_Carrier_Belt02",
			"CUP_H_SLA_Helmet",
			"ItemCompass",
			"ItemWatch"
		};
		respawnLinkedItems[]=
		{
			"CUP_V_O_SLA_Carrier_Belt02",
			"CUP_H_SLA_Helmet",
			"ItemCompass",
			"ItemWatch"
		};
		weapons[]=
		{
			"Throw",
			"Put",
			"CUP_arifle_AK47"
		};
		respawnweapons[]=
		{
			"Throw",
			"Put",
			"CUP_arifle_AK47"
		};
		magazines[]=
		{
			"CUP_30Rnd_762x39_AK47_M",
			"CUP_30Rnd_762x39_AK47_M",
			"CUP_30Rnd_762x39_AK47_M",
			"CUP_HandGrenade_RGD5",
			"CUP_HandGrenade_RGD5",
			"SmokeShell"
		};
		Respawnmagazines[]=
		{
			"CUP_30Rnd_762x39_AK47_M",
			"CUP_30Rnd_762x39_AK47_M",
			"CUP_30Rnd_762x39_AK47_M",
			"CUP_HandGrenade_RGD5",
			"CUP_HandGrenade_RGD5",
			"SmokeShell"
		};
		Items[]=
		{
			"ACE_fieldDressing",
			"ACE_fieldDressing",
			"ACE_morphine",
			"ACE_tourniquet"
		};
		respawntems[]=
		{
			"ACE_fieldDressing",
			"ACE_fieldDressing",
			"ACE_morphine",
			"ACE_tourniquet"
		};
	};
	class Afr_Mil_AT_Assistant: Afr_Mil_Base
	{
		scope=2;
		scopeCurator = 2;
		displayName="AT-Assistant";
		backpack="Afr_Backpack_AT";
		linkedItems[]=
		{
			"CUP_V_O_SLA_Carrier_Belt02",
			"CUP_H_SLA_Helmet",
			"ItemCompass",
			"ItemWatch"
		};
		respawnLinkedItems[]=
		{
			"CUP_V_O_SLA_Carrier_Belt02",
			"CUP_H_SLA_Helmet",
			"ItemCompass",
			"ItemWatch"
		};
		weapons[]=
		{
			"Throw",
			"Put",
			"CUP_arifle_AK47"
		};
		respawnweapons[]=
		{
			"Throw",
			"Put",
			"CUP_arifle_AK47"
		};
		magazines[]=
		{
			"CUP_30Rnd_762x39_AK47_M",
			"CUP_30Rnd_762x39_AK47_M",
			"CUP_30Rnd_762x39_AK47_M",
			"CUP_HandGrenade_RGD5",
			"CUP_HandGrenade_RGD5",
			"SmokeShell"
		};
		Respawnmagazines[]=
		{
			"CUP_30Rnd_762x39_AK47_M",
			"CUP_30Rnd_762x39_AK47_M",
			"CUP_30Rnd_762x39_AK47_M",
			"CUP_HandGrenade_RGD5",
			"CUP_HandGrenade_RGD5",
			"SmokeShell"
		};
		Items[]=
		{
			"ACE_fieldDressing",
			"ACE_fieldDressing",
			"ACE_morphine",
			"ACE_tourniquet"
		};
		respawntems[]=
		{
			"ACE_fieldDressing",
			"ACE_fieldDressing",
			"ACE_morphine",
			"ACE_tourniquet"
		};
	};
	class Afr_Mil_RiflemanAT: Afr_Mil_Base
	{
		scope=2;
		scopeCurator = 2;
		displayName="Rifleman AT";
		icon="iconManAT";
		backpack="Afr_Backpack_AT";
		linkedItems[]=
		{
			"CUP_V_O_SLA_Carrier_Belt02",
			"CUP_H_SLA_Helmet",
			"ItemCompass",
			"ItemWatch"
		};
		respawnLinkedItems[]=
		{
			"CUP_V_O_SLA_Carrier_Belt02",
			"CUP_H_SLA_Helmet",
			"ItemCompass",
			"ItemWatch"
		};
		weapons[]=
		{
			"Throw",
			"Put",
			"CUP_arifle_AK47",
			"CUP_launch_RPG7V"
		};
		respawnweapons[]=
		{
			"Throw",
			"Put",
			"CUP_arifle_AK47",
			"CUP_launch_RPG7V"
		};
		magazines[]=
		{
			"CUP_30Rnd_762x39_AK47_M",
			"CUP_30Rnd_762x39_AK47_M",
			"CUP_30Rnd_762x39_AK47_M",
			"CUP_HandGrenade_RGD5",
			"CUP_HandGrenade_RGD5",
			"SmokeShell"
		};
		Respawnmagazines[]=
		{
			"CUP_30Rnd_762x39_AK47_M",
			"CUP_30Rnd_762x39_AK47_M",
			"CUP_30Rnd_762x39_AK47_M",
			"CUP_HandGrenade_RGD5",
			"CUP_HandGrenade_RGD5",
			"SmokeShell"
		};
		Items[]=
		{
			"ACE_fieldDressing",
			"ACE_fieldDressing",
			"ACE_morphine",
			"ACE_tourniquet"
		};
		respawntems[]=
		{
			"ACE_fieldDressing",
			"ACE_fieldDressing",
			"ACE_morphine",
			"ACE_tourniquet"
		};
	};
	
	class Afr_Mil_Machinegunner: Afr_Mil_Base
	{
		scope=2;
		scopeCurator = 2;
		displayName="Machinegunner";
		backpack="Afr_Backpack_MG";
		icon="iconManMG";
		linkedItems[]=
		{
			"CUP_V_O_SLA_Carrier_Belt02",
			"CUP_H_SLA_Helmet",
			"ItemCompass",
			"ItemWatch"
		};
		respawnLinkedItems[]=
		{
			"CUP_V_O_SLA_Carrier_Belt02",
			"CUP_H_SLA_Helmet",
			"ItemCompass",
			"ItemWatch"
		};
		weapons[]=
		{
			"Throw",
			"Put",
			"CUP_lmg_PKM"
		};
		respawnweapons[]=
		{
			"Throw",
			"Put",
			"CUP_arifle_AK47"
		};
		magazines[]=
		{
			"CUP_100Rnd_TE4_LRT4_762x54_PK_Tracer_Green_M",
			"CUP_100Rnd_TE4_LRT4_762x54_PK_Tracer_Green_M",
			"CUP_HandGrenade_RGD5",
			"SmokeShell"
		};
		Respawnmagazines[]=
		{
			"CUP_100Rnd_TE4_LRT4_762x54_PK_Tracer_Green_M",
			"CUP_100Rnd_TE4_LRT4_762x54_PK_Tracer_Green_M",
			"CUP_HandGrenade_RGD5",
			"SmokeShell"
		};
		Items[]=
		{
			"ACE_fieldDressing",
			"ACE_fieldDressing",
			"ACE_morphine",
			"ACE_tourniquet"
		};
		respawntems[]=
		{
			"ACE_fieldDressing",
			"ACE_fieldDressing",
			"ACE_morphine",
			"ACE_tourniquet"
		};
	};
	class Afr_Mil_Teamleader: Afr_Mil_Base
	{
		scope=2;
		scopeCurator = 2;
		displayName="Teamleader";
		backpack="Afr_Backpack_Rifleman";
		linkedItems[]=
		{
			"CUP_V_O_SLA_Flak_Vest03",
			"CUP_H_SLA_Helmet",
			"ItemCompass",
			"ItemWatch"
		};
		respawnLinkedItems[]=
		{
			"CUP_V_O_SLA_Flak_Vest03",
			"CUP_H_SLA_Helmet",
			"ItemCompass",
			"ItemWatch"
		};
		weapons[]=
		{
			"Throw",
			"Put",
			"CUP_arifle_AK47"
		};
		respawnweapons[]=
		{
			"Throw",
			"Put",
			"CUP_arifle_AK47"
		};
		magazines[]=
		{
			"CUP_30Rnd_762x39_AK47_M",
			"CUP_30Rnd_762x39_AK47_M",
			"CUP_30Rnd_762x39_AK47_M",
			"CUP_HandGrenade_RGD5",
			"CUP_HandGrenade_RGD5",
			"SmokeShell",
			"SmokeShell"
		};
		Respawnmagazines[]=
		{
			"CUP_30Rnd_762x39_AK47_M",
			"CUP_30Rnd_762x39_AK47_M",
			"CUP_30Rnd_762x39_AK47_M",
			"CUP_HandGrenade_RGD5",
			"CUP_HandGrenade_RGD5",
			"SmokeShell",
			"SmokeShell"
		};
		Items[]=
		{
			"ACE_fieldDressing",
			"ACE_fieldDressing",
			"ACE_morphine",
			"ACE_tourniquet"
		};
		respawntems[]=
		{
			"ACE_fieldDressing",
			"ACE_fieldDressing",
			"ACE_morphine",
			"ACE_tourniquet"
		};
	};
	class Afr_Mil_Squadleader: Afr_Mil_Base
	{
		scope=2;
		scopeCurator = 2;
		displayName="Squadleader";
		icon="iconManLeader";
		backpack="Afr_Backpack_Rifleman";
		linkedItems[]=
		{
			"CUP_V_O_SLA_Flak_Vest03",
			"CUP_H_SLA_SLCap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]=
		{
			"CUP_V_O_SLA_Flak_Vest03",
			"CUP_H_SLA_SLCap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		weapons[]=
		{
			"Throw",
			"Put",
			"CUP_arifle_AK47",
			"Binocular"
		};
		respawnweapons[]=
		{
			"Throw",
			"Put",
			"CUP_arifle_AK47",
			"Binocular"
		};
		magazines[]=
		{
			"CUP_30Rnd_762x39_AK47_M",
			"CUP_30Rnd_762x39_AK47_M",
			"CUP_30Rnd_762x39_AK47_M",
			"CUP_HandGrenade_RGD5",
			"CUP_HandGrenade_RGD5",
			"SmokeShell",
			"SmokeShell"
		};
		Respawnmagazines[]=
		{
			"CUP_30Rnd_762x39_AK47_M",
			"CUP_30Rnd_762x39_AK47_M",
			"CUP_30Rnd_762x39_AK47_M",
			"CUP_HandGrenade_RGD5",
			"CUP_HandGrenade_RGD5",
			"SmokeShell",
			"SmokeShell"
		};
		Items[]=
		{
			"ACE_fieldDressing",
			"ACE_fieldDressing",
			"ACE_morphine",
			"ACE_tourniquet"
		};
		respawntems[]=
		{
			"ACE_fieldDressing",
			"ACE_fieldDressing",
			"ACE_morphine",
			"ACE_tourniquet"
		};
	};
	class Afr_Mil_Officer: Afr_Mil_Base
	{
		scope=2;
		scopeCurator = 2;
		displayName="Officer";
		icon="iconManOfficer";
		linkedItems[]=
		{
			"CUP_V_O_SLA_Flak_Vest03",
			"CUP_H_SLA_BeretRed",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]=
		{
			"CUP_V_O_SLA_Flak_Vest03",
			"CUP_H_SLA_BeretRed",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		weapons[]=
		{
			"Throw",
			"Put",
			"CUP_hgun_SA61",
			"Binocular"
		};
		respawnweapons[]=
		{
			"Throw",
			"Put",
			"CUP_hgun_SA61",
			"Binocular"
		};
		magazines[]=
		{
			"CUP_20Rnd_B_765x17_Ball_M",
			"CUP_20Rnd_B_765x17_Ball_M",
			"CUP_20Rnd_B_765x17_Ball_M",
			"CUP_20Rnd_B_765x17_Ball_M",
			"CUP_20Rnd_B_765x17_Ball_M",
			"CUP_HandGrenade_RGD5",
			"SmokeShell",
			"SmokeShell"
		};
		Respawnmagazines[]=
		{
			"CUP_20Rnd_B_765x17_Ball_M",
			"CUP_20Rnd_B_765x17_Ball_M",
			"CUP_20Rnd_B_765x17_Ball_M",
			"CUP_20Rnd_B_765x17_Ball_M",
			"CUP_20Rnd_B_765x17_Ball_M",
			"CUP_HandGrenade_RGD5",
			"SmokeShell",
			"SmokeShell"
		};
		Items[]=
		{
			"ACE_fieldDressing",
			"ACE_fieldDressing",
			"ACE_morphine",
			"ACE_tourniquet"
		};
		respawntems[]=
		{
			"ACE_fieldDressing",
			"ACE_fieldDressing",
			"ACE_morphine",
			"ACE_tourniquet"
		};
	};
	class Afr_Mil_Crewman: Afr_Mil_Base
	{
		scope=2;
		scopeCurator = 2;
		displayName="Pilot";
		icon="iconMan";
		uniformClass="CUP_U_O_SLA_Overalls_Pilot";
		linkedItems[]=
		{
			"CUP_V_O_TK_CrewBelt",
			"CUP_H_SLA_Pilot_Helmet",
			"ItemCompass",
			"ItemWatch"
		};
		respawnLinkedItems[]=
		{
			"CUP_V_O_TK_CrewBelt",
			"CUP_H_SLA_Pilot_Helmet",
			"ItemCompass",
			"ItemWatch"
		};
		weapons[]=
		{
			"Throw",
			"Put",
			"CUP_hgun_SA61"
		};
		respawnweapons[]=
		{
			"Throw",
			"Put",
			"CUP_hgun_SA61"
		};
		magazines[]=
		{
			"CUP_20Rnd_B_765x17_Ball_M",
			"CUP_20Rnd_B_765x17_Ball_M",
			"CUP_20Rnd_B_765x17_Ball_M",
			"CUP_20Rnd_B_765x17_Ball_M",
			"SmokeShell"
		};
		Respawnmagazines[]=
		{
			"CUP_20Rnd_B_765x17_Ball_M",
			"CUP_20Rnd_B_765x17_Ball_M",
			"CUP_20Rnd_B_765x17_Ball_M",
			"CUP_20Rnd_B_765x17_Ball_M",
			"SmokeShell"
		};
		Items[]=
		{
			"ACE_fieldDressing",
			"ACE_fieldDressing",
			"ACE_morphine",
			"ACE_tourniquet",
			"ItemRadio"
		};
		respawntems[]=
		{
			"ACE_fieldDressing",
			"ACE_fieldDressing",
			"ACE_morphine",
			"ACE_tourniquet",
			"ItemRadio"
		};
	};